### ISSUE TITLE
[Qwik city starter express] - TypeError: createCache is not a function

### ISSUE THREAD

**Issue by mr-moto** [BuilderIO/qwik#1008]
### Qwik Version

0.0.41

### Operating System (or Browser)

macOS

### Node Version (if applicable)

16.16.0

### Which component is affected?

Qwik City

### Expected Behaviour

qwik city express starter:
refreshing the page after `npm run build && npm run serve` should console log `http://localhost:8080/` ( based on the starter )

### Actual Behaviour

throws an error after refresh.

error:
```
file:///node_modules/@builder.io/qwik-react/lib/server.f07a53ac.js:9
const cache = createCache({
              ^

TypeError: createCache is not a function
    at file:///node_modules/@builder.io/qwik-react/lib/server.f07a53ac.js:9:15
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async renderToString (file:///node_modules/@builder.io/qwik-react/lib/index.qwik.mjs:82:15)
    at async file:///server/entry.express.js:1674:20
```

### Additional Information

`@builder.io/qwik-city` was updated to `v0.0.32` because of a missing type in `v0.0.30`

**Comment by adamdbradley** [comment]
Should be fixed in latest qwik release, thanks
