### ISSUE TITLE
[DOCS] Main page example bug

### ISSUE THREAD

**Issue by Eccenux** [BuilderIO/qwik#1028]
**How can the documentation be improved?**
 You use `on$:click`, but docs says it should be `onClick$`. And also on$ doesn't work in the playground.

**Comment by Eccenux** [comment]
Oh, and probably you wanted to increment on click do `state.count++` in onClick$ I assume 🙂

**Comment by adamdbradley** [comment]
Good catch, we'll get that fixed up, thanks

**Comment by adamdbradley** [comment]
Fixed, thanks
