### ISSUE TITLE
[Feat]: Buffer and control size of streaming

### ISSUE THREAD

**Issue by adamdbradley** [BuilderIO/qwik#1030]
### Is your feature request related to a problem?

Currently streaming is always immediate, no matter how small each chunk is. Because the response returns a status but yet to stream the body content, the browser may render a white screen first, then later stream in the body as it's rendered. (To be clear, the response being too fast is a good problem to have.)

### Describe the solution you'd like

Provide better defaults so the initial chunk of body content can contain above the fold HTML, so the user's first rendered content is complete, and the rest below the fold can be streamed in. 

Also allow users to configure these settings, while first providing good defaults.

**Comment by manucorporat** [comment]
Fixed https://github.com/BuilderIO/qwik/pull/1039
