### ISSUE TITLE
Inputs lose state on quick interactions (or on slow networks)

### ISSUE THREAD

**Issue by dario-piotrowicz** [BuilderIO/qwik#1032]
### Qwik Version

0.0.42

### Operating System (or Browser)

macOS Monterey (Chrome v.104) and Ubuntu 20.04 LTS (Chromium v.104)

### Which component is affected?

Qwik Runtime

### Expected Behaviour

When interacting with inputs the text typed into them should persist but if the user is fast enough and the network is slow the text can actually be completely (or partially) removed.

### Actual Behaviour

You can see in this [stackblitz reproduction](https://stackblitz.com/edit/qwik-vite-todoapp-k43bzm?file=src%2Fmain.tsx,src%2Fentry.server.tsx,src%2Fbase.css,vite.config.ts) that if you type quickly enough in the first input and switch into the second and keep typing, the text typed into the second input gets removed.

For example see the following gif:
![qwik-issue](https://user-images.githubusercontent.com/61631103/184026010-7ef9ec1a-0260-43e2-bb16-a86ab1feeff9.gif)

There I am typing three ones (`111`) in both inputs, but as you can see 2 `1`s in the second input just disappear (but you do need to be quite fast to trigger the bug).

That is the best reproduction I could do on stackblitz, there the issue is difficult to reproduce since their web containers don't allow you to throttle the network (and serve the js files instantaneously via service workers), but if you run the reproduction locally the issue is very easy to reproduce (and it shows more clearly how this can be an issue with the user experience):
![qwik-local-repro](https://user-images.githubusercontent.com/61631103/184027067-7ec4837d-c8f1-46eb-a355-ead642cc20da.gif)

(naturally in the second gif I am not deleting the text myself, it is getting remove as soon as the `core.mjs` file is downloaded)

### Additional Information

I'm sorry if this is a minor bug or it is expected by the asynchronous way Qwik is implemented

(PS: not sure why the core there is 1.5mb it does seem way way too large, it is probably because I was just running the app locally in dev mode, but even with a smaller js file, if the network is slow enough and/or the user's interaction is fast enough the issue would appear)

Another thing to mention is that this only happens initially when the js file gets fetched, after that no state gets lost anymore.

**Comment by nnelgxorz** [comment]
I think this might be because Qwik doesn't do prefetching when running the dev server. Have you tried reproducing on a build?

**Comment by nnelgxorz** [comment]
Also, bundles are going to be larger in dev mode, so that's probably not helping either

**Comment by dario-piotrowicz** [comment]
Hi @nnelgxorz thank you so very much for the quick reply 🙂 

Good point, I actually tried on a build as you can see here: https://qwik-app.dario-piotrowicz.workers.dev/

And there yeah the files are much smaller which make the issue less problematic, but it is still there

![qwik-deployed-repro](https://user-images.githubusercontent.com/61631103/184105945-ffa22810-c50c-469b-a910-80d60ed29e13.gif)

**Comment by nnelgxorz** [comment]
No problem, @dario-piotrowicz! So, I had this same problem and Misko helped me. I'll explain.

In your network log, you can see that the code is being prefetched (the .js files with the gray square next to them), but then they are being re-fetched on interaction (the .js files with the yellow square next to them).

That's because you have Disable Cache checked in your dev tools. If you disable that you should see the prefetched code being used and the delay should go away.

**Comment by dario-piotrowicz** [comment]
Thanks for the explanation @nnelgxorz :slightly_smiling_face: 

But it seems that even with `Disable cache` not checked the issue is still there:
![no-network-throttling](https://user-images.githubusercontent.com/61631103/184195485-59570083-ff7a-482b-88f9-5cd7421acda4.gif)

**Comment by nnelgxorz** [comment]
@dario-piotrowicz Thanks for reporting back. Something odd is happening there. I'll dig into your reproduction when I get a chance. 👍

**Comment by dario-piotrowicz** [comment]
no problem @nnelgxorz , there is no rush and I wonder if this could be bit of an edge-case, I'm looking forward to see what you can find about it :smiley:

**Comment by nnelgxorz** [comment]
@dario-piotrowicz Can you change your onChange$ handlers to onInput$ handlers and see if that gives you the expected behavior?

**Comment by dario-piotrowicz** [comment]
@nnelgxorz ah yeah you're right, with `onInput$` the issue doesn't seem to appear :slightly_smiling_face: (I can't believe I didn't try that myself :sweat_smile:) and `onInput` does seem to be the more correct event anyways :smile: :tada: 

regardless on that, I feel like the issue should not happen even if `onChange$` was used, what do you think? :slightly_smiling_face:

**Comment by nnelgxorz** [comment]
Awesome! 🥳 

Yeah, it's weird because the onChange won't fire until the text input loses focus. I'm not sure if there's a way around that happening as it seems like the correct behavior. 🤔

**Comment by dario-piotrowicz** [comment]
Ah, yeah I see what you mean, this is likely the "correct" behaviour, the `onChange$` handler starts getting fetched when you blur the first input, then you start typing into the second one, no state updates happen, and when the `onChange$` fetch returns it causes a refresh of the component so the input's value (which hasn't been recorder in the state) is removed.

It does look a bit unfortunate but yeah I agree that this looks to me the way things should work, and it is up to the developer to make sure that it doesn't happen (as for example with the `onInput$` change as you suggested).

____

Ok, so I'm closing the issue as I do think all here is working as expected 🙂 , @nnelgxorz thank you so very much for your help! (and sorry if it was a silly issue/mistake on my part 😓 )

**Comment by nnelgxorz** [comment]
Happy to help, @dario-piotrowicz!

**Comment by manucorporat** [comment]
You guys are amazing! Yep on change behavior is a bit odd, react fakes it behaving like oninput. But we will not do this, seems a bit against the standards
