### ISSUE TITLE
Editor on example page is broken

### ISSUE THREAD

**Issue by simerlec** [BuilderIO/qwik#1037]
### Qwik Version

latest

### Operating System (or Browser)

MacOS Monterey (12.3.1 [21E258])

### Which component is affected?

Starters / CLI

### Expected Behaviour

- Go to `https://qwik.builder.io/examples/reactivity/watch` (or any example)
- Editor should have full height

### Actual Behaviour

Editor is limited to a very small container

### Additional Information

![image](https://user-images.githubusercontent.com/5793380/184093174-23f8a3c9-f6c6-46b5-8ea5-7e5b2c3fe712.png)
Browser: Brave Version 1.42.88 Chromium: 104.0.5112.81 (Official Build) (arm64), Safari (15.4 [17613.1.17.1.13])

Sorry, I did not know which `affected component` I should pick, so I went with Starters/CLI

kind regards

**Comment by simerlec** [comment]
Just realized that the same issue is present on all other pages that show the editor
https://qwik.builder.io/tutorial/welcome/overview
https://qwik.builder.io/playground

**Comment by manucorporat** [comment]
It's working for me! is this still an issue? I will close, but if it's i will be happy to reopen

**Comment by simerlec** [comment]
@manucorporat Seems to be working again 👍

**Comment by roryjarrard** [comment]
It is not working in the tutorial on Sep. 28 2022
![image](https://user-images.githubusercontent.com/5709884/192790680-8b05f128-d6ea-4feb-a389-6b4edecb3cd8.png)

Error: "Cannot find module '@builder.io/qwik' or its corresponding type declarations"

**Comment by wtho** [comment]
@roryjarrard that is a different issue. Previously it was not loading, your screenshot seems to have issues of not being able to load data from `data.jsdelivr.com`.

Maybe you can observe it for a few days and check on different browsers. If it still won't load, you can open a new issue.

**Comment by ubarbaxor** [comment]
I'm using this issue as it's the first result when searching for "Qwik playground broken".
Seems to be so again.

![image](https://user-images.githubusercontent.com/26365493/222823051-40065603-d44e-49f5-9988-6c63365092f7.png)

![image](https://user-images.githubusercontent.com/26365493/222823103-b1c62f02-888c-4a43-955a-02b7175dcd1b.png)
```
Error: Unable to require() path "@builder.io/qwik/build" from a browser environment. at globalThis.qwikServer.globalThis.require (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:33:11) at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:164:20) at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:783:26) at g (https://qwik.builder.io/repl/repl-sw.js:1:377) at async B (https://qwik.builder.io/repl/repl-sw.js:1:1357) at async F (https://qwik.builder.io/repl/repl-sw.js:12:5469)
```
