### ISSUE TITLE
srcDir option from QwikVitePluginOptions is ignored (qwikVite configuration)

### ISSUE THREAD

**Issue by felixsanz** [BuilderIO/qwik#1045]
### Qwik Version

0.0.41

### Operating System (or Browser)

Node

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

I may be missing something, but I think `srcDir` option passed to `qwikVite` plugin is not working.

If I set it like this:

```js
qwikVite({
  srcDir: './src/components',
}),
```
And then I move `./src/root.tsx` to `./src/components/Root.tsx`, I get this error:

```
[vite-plugin-qwik] Qwik input "......./qwik/blog/src/root.tsx" not found.
```

So I was thinking that maybe this root.tsx was hardcoded. And yes it is, ([here](https://github.com/BuilderIO/qwik/blob/a11e52b06b330a9ad1124d142903581c1532f365/packages/qwik/src/optimizer/src/plugins/plugin.ts#L175)):

```
// packages/qwik/src/optimizer/src/plugins/plugin.ts#L175
opts.input = [path.resolve(srcDir, 'root.tsx')];
```

So then I modified `root.tsx` and used `Root.tsx` instead. Now the error is:

```
[vite-plugin-qwik] Qwik input "......./qwik/blog/src/Root.tsx" not found
```
So this confirms that the line number 175 is indeed in charge of this, but also confirms that `srcDir` it's not being used.

### Actual Behaviour

.

**Comment by manucorporat** [comment]
Fixed in latest release!

**Comment by felixsanz** [comment]
> Fixed in latest release!

To me, `root.tsx` is a component (a lite one), that's why I wanted to move it to `src/components` and set `srcDir` according. But yeah, you're moving the whole srcDir so it also expects `entry.*.tsx` files inside `components` folder, which doesn't make much sense.

Can we have an option to just move `root.tsx`? like `rootFile: src/components/root.tsx`? It's OK if we don't, this is totally unnecessary but all I wanted to do is move the root component to the components folder and discovered this issue in the way xD

Thanks!
