### ISSUE TITLE
QWIK WARN Can not rerender in server platform

### ISSUE THREAD

**Issue by gioboa** [BuilderIO/qwik#1057]
### Qwik Version

Qwik 0.0.100 - Qwik City 0.0.101

### Operating System (or Browser)

macOs + Chrome

### Node Version (if applicable)

v18.4.0

### Which component is affected?

Qwik City

### Expected Behaviour

In the previous Qwik/Qwik City version when I update the state inside of useMount, Qwik rerender the DOM

### Actual Behaviour

Here a repo that show the error
https://stackblitz.com/github/gioboa/qwik-city-issue?file=src%2Froutes%2Findex.tsx

If I change useMount with useClientEffect works but this is not a valid solution because I need useMount hook

**Comment by manucorporat** [comment]
Amazing repo! looking into it asap, indeed looks like an issue

**Comment by manucorporat** [comment]
So strange, our e2e tests does not reproduce it, also in the playground it works...
https://qwik.builder.io/playground#version=0.0.100&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMkMlMjB1c2VNb3VudCUyNCUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWsnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMEFwcCUyMCUzRCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCJTIwbWVzc2FnZSUzQSUyMCd0ZXh0JyU3RCklM0IlNUNuJTIwJTIwdXNlTW91bnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwc3RhdGUubWVzc2FnZSUyMCUzRCUyMCdob2xhJyUzQiU1Q24lMjAlMjAlN0QpJTNCJTVDbiUyMCUyMHJldHVybiUyMCUzQ3AlM0UlN0JzdGF0ZS5tZXNzYWdlJTdEJTNDJTJGcCUzRSUzQiU1Q24lN0QpJTNCJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlbmRlclRvU3RyaW5nJTJDJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBBcHAlMjAlN0QlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D

**Comment by gioboa** [comment]
in my local machine and also in the public repo the server is running in SSR mode -> `npm run dev.ssr` 🤔 
maybe is something related about this

**Comment by nnelgxorz** [comment]
I think this is a regression: https://github.com/BuilderIO/qwik/issues/580

**Comment by jwickers** [comment]
Have the same issue with `useServerMount`, I see the reproduction above is simpler and has the same issue so I won't attach another(one can just init a fresh qwik-city project and change the index.tsx as he did to see the issue).

**Comment by gioboa** [comment]
The repo is generated from this repo https://github.com/gioboa/qwik-city-issue/commits/main
