### ISSUE TITLE
[DOCS] Missing list of filetypes on https://qwik.builder.io/qwikcity/routing/overview

### ISSUE THREAD

**Issue by mj6uc** [BuilderIO/qwik#1061]
**How can the documentation be improved?**

On the page: 
https://qwik.builder.io/qwikcity/routing/overview

The list of filetypes is missing. 
(Probably should be tsx,ts,js,jsx,md,mdx)

See attached.
<img width="1536" alt="Screenshot 2022-08-14 at 7 04 38 PM" src="https://user-images.githubusercontent.com/54877/184539665-e0c424d1-aaf0-405e-9025-982b6a99f12a.png">

**Comment by nnelgxorz** [comment]
Wow, not sure what happened there. Thanks for the heads up!
