### ISSUE TITLE
feat request: conditioning `preventdefault:event `

### ISSUE THREAD

**Issue by youngboy** [BuilderIO/qwik#1067]
### Is your feature request related to a problem?

Implementing a search box, need a way to skip keydown event only when the key is `ArrowUp` , `ArrowDown`

### Describe the solution you'd like

let attribute value be more descriptive by certain structure ? such as `preventdefault:keydown="{ key: ['arrow'] }"` ?

### Describe alternatives you've considered

1. Considering Vue have event key modifier like `@keydonw.enter` we can do the similar `preventdefault:keydown.enter` ?
2. add a special way to bind event handle in sync for edge case that have to  prevent dynamically ?

**Comment by nnelgxorz** [comment]
I like this idea. Seems like 

```typescript
preventDefault:event={(e: Event) => bool}
```

would be the most flexible? How do you feel about that option @youngboy?

**Comment by youngboy** [comment]
That would be great. I was though the attribute value is have to be string 😂

**Comment by nnelgxorz** [comment]
The preventDefault type is defined by Qwik, so we can do whatever we want. 😆 Whether the merge it is a different story.

**Comment by nnelgxorz** [comment]
I think there would be implications for serialization, so there would need to be some investigating to see what the tradeoffs are or if this is a good idea.

**Comment by manucorporat** [comment]
Problem is that all this logic would need to go in the qwikloader, ie, the minimun amount of JS shipped with Qwik, kind of sensitive part of the framework, but i can see the utility of this

```
preventDefault:event={(e: Event) => bool}
```
not sure how this would work, it owuld not be able to use state of anything, simple rules, but that imposes a strange restriction to developers

**Comment by nnelgxorz** [comment]
Yeah, I'd be curious how much it adds to the Qwikloader size. I don't know if the simple rules are an issue for most use cases. I mean, as of right now preventDefault with no conditions seems to work for 99.9% of the use cases.

**Comment by youngboy** [comment]
Maybe could provide a way to allow developer add add-ons to extend qwik loader or build his own loader ?

although only by this case isn't convincible to support this, that will increase some maintenance burden. is there other needs to extend qwik loader ?

**Comment by nnelgxorz** [comment]
Custom events? Although, I thunk the solution there should be more automatic than manual.

https://github.com/BuilderIO/qwik/issues/786

**Comment by mhevery** [comment]
My current simple thinking on this is that we should not complicate things. For now, I think the best solution is to register your own code, something like is described in [synchronous events](https://qwik.builder.io/tutorial/events/synchronous/), and there you can do whatever you want. Yes, it forces your application to eagerly wake up, but as long as the amount of code is small, it should be OK. 

```typescript

```

**Comment by ulic75** [comment]
Here is the use case where I'm running into an issue.

I'm try to develop a UI component that responds to Home/End buttons (there are several designed with this, sliders and changing tabs).  I need to prevent default when using Home/End so the browser doesn't scroll to the top/bottom of the page.  However, if I prevent default, then I can no longer use the tab key to move from the current control onto whatever the next one might be.

**Comment by literalpie** [comment]
I need this for a form that has an editable list of strings within it. If you are editing a string, I want "enter" to commit the string without submitting the whole form. 
I'll use the synchronous events approach for now.

**Comment by shairez** [comment]
@noeliadv yeah this issue is not solved yet

Related to #4496 

We need to find a solution for this once and for all

A workaround is to use something like @mhevery suggested - 

```
const anchorElement = useSignal<Element>();
useVisibleTask$(() => {
  const handler = (event: Event) => {
    event.preventDefault();
    // do something here
  };
  anchorElement.value!.addEventListener('click', handler);
  return () => anchorElement.value!.removeEventListener('click', handler);
});
  
  ```

**Comment by shairez** [comment]
closing this in favor of #4496
