### ISSUE TITLE
[bug] QwikCity useResoruce + useStore

### ISSUE THREAD

**Issue by gioboa** [BuilderIO/qwik#1078]
### Qwik Version

Qwik 0.0.100 - Qwik City 0.0.101

### Operating System (or Browser)

macOs + Chrome

### Node Version (if applicable)

v18.4.0

### Which component is affected?

Qwik City

### Expected Behaviour

My expectation is a dom rerender If I change app state inside useResource

### Actual Behaviour

here the GitHub repository https://github.com/gioboa/qwik-useresource-state/commits/main
and [here the playground](https://stackblitz.com/github/gioboa/qwik-useresource-state?file=src%2Froutes%2Findex.tsx)

### Additional Information

If I move the "dynamic" code outside the Resource section, it works as expected

**Comment by youngboy** [comment]
a simple workaround to this is let onResolved return a single component

```jsx
export default component$(() => {
  const state = useStore<{ char: string }>({
    char: 'A',
  });

  const searchData = useResource$(async ({ previous }) => {});
  return (
    <>
      <h1>{state.char}</h1>
      <Resource
        resource={searchData}
        onPending={() => <></>}
        onResolved={() => (
          <button
            onClick$={() => {
              state.char = 'B';
            }}
          >
            Change state at runtime
          </button>
        )}
      />
    </>
  );
});
```
