### ISSUE TITLE
track is not a function

### ISSUE THREAD

**Issue by carlostobon** [BuilderIO/qwik#1080]
### Qwik Version

0.0.100

### Operating System (or Browser)

Linux

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Following the guide to learn the framework. track seems to be not working

### Actual Behaviour

cant find the function

**Comment by youngboy** [comment]
can you show code snippets in which part of guide is not working ? there's breaking change since 0.0.40 https://github.com/BuilderIO/qwik/releases/tag/v0.0.40 , maybe some outdating content in guide.

you can console.log arguments to verify where is the `track`

**Comment by youngboy** [comment]
ha. found one outdated:

doc url, https://qwik.builder.io/tutorial/reactivity/explicit
source file https://github.com/BuilderIO/qwik/blob/main/packages/docs/src/routes/tutorial/reactivity/explicit/problem/app.tsx#L14

**Comment by carlostobon** [comment]
Oh man thanks it's now an object.
