### ISSUE TITLE
useStylesScoped$ breaks when using pseudo-selectors

### ISSUE THREAD

**Issue by felixsanz** [BuilderIO/qwik#1081]
### Qwik Version

0.0.100

### Operating System (or Browser)

Node

### Which component is affected?

Qwik Runtime

### Expected Behaviour

useStylesScoped$ adds a scoped class to ALL things, but pseudo-selectors like `::after` have no classes (no actual elements) so the class is not added. This causes that the CSS that is generated is wrong, as it tries to target something like `::after.⭐️aymlju-0`, which is never going to happen.

Since we added `:global()` it's possible to workaround it with `:global(a::before)` but it's a very very bad idea to rely on this.

Example to run at https://qwik.builder.io/playground

```ts
import { component$, useStyles$, useStylesScoped$ } from '@builder.io/qwik';

export const stylesNormal = `
span.normal {
  position: relative;
  color: blue;
  }

span.normal::before {
  content: "";
  position: absolute;
  right: -20px;
  border: 10px solid blue;
}
`

export const stylesScoped = `
span.scoped {
  position: relative;
  color: blue;
  }

span.scoped::before {
  content: "";
  position: absolute;
  right: -20px;
  border: 10px solid blue;
}
`

export const App = component$(() => {
  useStyles$(stylesNormal)
  useStylesScoped$(stylesScoped)

  return (
    <>    
    <span class="normal">Normal</span>
    <br /><br />
    <span class="scoped">Scoped</span>
    </>
  );
});
```

### Actual Behaviour

.

**Comment by youngboy** [comment]
There's some tests I think would be useful.

```javascript
scopedStyles('attribute selector', () => {
  equal(scopeStylesheet('.class[attr^=value] {}', 'ABC'), '.class[attr^=value].⭐️ABC {}');
});

scopedStyles('class scoping with pseudo selectors and elements', () => {
  equal(scopeStylesheet('.class:hover {}', 'ABC'), '.class.⭐️ABC:hover {}');
  equal(scopeStylesheet('.class::after {}', 'ABC'), '.class.⭐️ABC::after {}');
  equal(scopeStylesheet('.classA:not(.class) {}', 'ABC'), '.classA:not(.class).⭐️ABC {}');
  equal(
    scopeStylesheet(':is(section, article) h1 {}', 'ABC'),
    ':is(section, article) h1.⭐️ABC {}'
  );
});

scopedStyles('keyframes', () => {
  equal(
    scopeStylesheet(
      '@keyframes slide {0%{top:-100%;}100%{top:0;}} .a{animation: 2s slide;}',
      'ABC'
    ),
    '@keyframes slide-⭐️ABC {0%{top:-100%;}100%{top:0;}}.a.⭐️ABC{animation: 2s slide-⭐️ABC;}'
  );
});
```

**Comment by felixsanz** [comment]
> There's some tests I think would be useful.
> 
> ```js
> scopedStyles('attribute selector', () => {
>   equal(scopeStylesheet('.class[attr^=value] {}', 'ABC'), '.class[attr^=value].⭐️ABC {}');
> });
> 
> scopedStyles('class scoping with pseudo selectors and elements', () => {
>   equal(scopeStylesheet('.class:hover {}', 'ABC'), '.class:hover.⭐️ABC {}');
>   equal(scopeStylesheet('.classA:not(.class) {}', 'ABC'), '.classA:not(.class).⭐️ABC {}');
>   equal(
>     scopeStylesheet(':is(section, article) h1 {}', 'ABC'),
>     ':is(section, article) h1.⭐️ABC {}'
>   );
>   equal(scopeStylesheet('.class::after {}', 'ABC'), '.class.⭐️ABC::after {}');
> });
> 
> scopedStyles('keyframes', () => {
>   equal(
>     scopeStylesheet(
>       '@keyframes slide {0%{top:-100%;}100%{top:0;}} .a{animation: 2s slide;}',
>       'ABC'
>     ),
>     '@keyframes slide-⭐️ABC {0%{top:-100%;}100%{top:0;}} .a.⭐️ABC{animation: 2s slide-⭐️ABC;}'
>   );
> });
> ```

i think this is not valid CSS? all of them should be `.class.⭐️ABC:hover` not `.class:hover.⭐️ABC` . (pseudos the last thing)

also i'm not sure about changing keyframes names... none of the frameworks/libraries that does scoping change the names

**Comment by youngboy** [comment]
As for grammar, source I could find: https://www.w3.org/TR/2011/REC-css3-selectors-20110929/#w3cselgrammar . there is no ordering requirement for `simple_selector_sequence`. For pseudo element, it is different story,  for example `p::first-line:hover`,  `p:hover::first-line` just have different meaning, doesn't mean that it is not valid css, there is no such problem in pseudo class. But I agree with you, for developer `.class.⭐️ABC:hover` may make more sense.

Yesterday I saw keyframes name is transformed in postcss-modules-scope test case. And same as vue-loader.  Any thing inside scoped styles should be scoped if possible IMHO

**Comment by felixsanz** [comment]
no no, i was wrong. you can add classes to `:hover`. You can't however add them to `::after`, so you were right!

**Comment by mhevery** [comment]
I believe this has been resolved and can be closed. @felixsanz can you confirm/close?

**Comment by mhevery** [comment]
https://github.com/BuilderIO/qwik/pull/1104

**Comment by felixsanz** [comment]
> I believe this has been resolved and can be closed. @felixsanz can you confirm/close?

yes, all OK. forgot to close it, thanks!
