### ISSUE TITLE
Express: optional parameter breaks everything

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#1085]
### Qwik Version

0.0.100

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

v16

### Which component is affected?

Qwik City

### Expected Behaviour

A project folder like this:

```
- routes
    - [...skuId]
        - index.tsx
```

should work as in `dev --mode ssr` when an _Express.js_ server is used.

### Actual Behaviour

Reproduction: https://stackblitz.com/edit/vitejs-vite-mfpvdp?file=src%2Froutes%2F[...skuId]%2Findex.tsx

Stop the Vite server and run: `npm run build && npm run serve`

Currently the optional parameter `[...skuId]` _located in the root_ of the `routes `directory cause the following:

- The `index` components is called multiple times (see _INIT COMPONENT_ in Terminal)
- The chunks are not loaded at runtime (_Failed to fetch dynamically imported module_ in console)
- Fetch requests to public folder fail (_Failed to fetch dynamically imported module_ in console)

(Instead, It works if the parameter is not optional `[skuId]`, or the optional parameter is nested `details[...skuId]`)

### Additional Information

I tried to investigate, but without result: I only found that [here](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/middleware/request-handler/request-handler.ts#L23) the routes loaded from `cityPlan `are broken. The parameter `skuId `contains every chunk, like `{"params":{"skuId":"build/q-1e730e3d.js"},"mods":[{}]}`, `favicon.ico` and so on (instead they are correct in dev mode).

I don't know if other middlewares are affected by the same issue.

Thanks

**Comment by adamdbradley** [comment]
Great issue, thanks for creating a repo case. I've made the changes to the starter so the express app first has the static assets middleware before qwik city. https://github.com/BuilderIO/qwik/blob/a45b32c90e24597390a83f82a464c5254ddbe90b/starters/servers/express/src/entry.express.tsx#L18-L22

Which also reminds me to ensure the other servers handle it the same way. Thanks for creating the issue!

**Comment by adamdbradley** [comment]
https://github.com/BuilderIO/qwik/pull/1111
