### ISSUE TITLE
[BUG] State with array don't refresh/rerender in client.

### ISSUE THREAD

**Issue by acgalbany** [BuilderIO/qwik#1088]
### Qwik Version

0.0.100

### Operating System (or Browser)

W11 - chrome

### Node Version (if applicable)

16

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Update the array in the state and see the changes reflected in HTML

### Actual Behaviour

The array is updated in the state, the changes are reflected in the console, but the changes are not reflected in HTML.

### Additional Information

https://qwik.builder.io/playground#version=0.0.100&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMkMlMjB1c2VDbGllbnRFZmZlY3QlMjQlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzdGF0ZSUyMCUzRCUyMHVzZVN0b3JlKCU1Q24lMjAlMjAlMjAlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwdGV4dHMlM0ElMjAlNUInSGVsbG8lMjBRd2lrJyUyQyUyMCdTZWNvbmQlMjBsaW5lJyU1RCUyQyU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwKSUzQiU1Q24lNUNuJTIwJTIwdXNlQ2xpZW50RWZmZWN0JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnN0JTIwaW50ZXJ2YWwlMjAlM0QlMjBzZXRJbnRlcnZhbCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZygnVGV4dCUyMGFkZGVkJyklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwc3RhdGUudGV4dHMucHVzaCgnQWxleCcpJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCUyQyUyMDEwMDApJTNCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMCgpJTIwJTNEJTNFJTIwY2xlYXJJbnRlcnZhbChpbnRlcnZhbCklM0IlNUNuJTIwJTIwJTdEKSUzQiU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NkaXYlM0UlNUNuJTIwJTIwJTIwJTIwJTdCc3RhdGUudGV4dHMlM0YubWFwKCh0ZXh0JTNBJTIwYW55KSUyMCUzRCUzRSUyMCglNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDcCUzRSU3QnRleHQlN0QlM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCkpJTdEJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmRpdiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFwcCUyMCU3RCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE

**Comment by youngboy** [comment]
not experts, but I think two options here

1. use recursive 

```javascript
  const state = useStore(
    {
      texts: ['Hello Qwik', 'Second line'],
    }, {
      recursive: true,
    }
  );
```

2. change array value it self

```javascript
state.texts = [...state.texts, 'alex']
```

**Comment by manucorporat** [comment]
Indeed stores does not watch for changes recursively:
```tsx
  const state = useStore(
    {
      texts: ['Hello Qwik', 'Second line'],
    }, {
      recursive: true,
    }
  );
```
should fix it!
