### ISSUE TITLE
useWatch only called once when updating nested values.

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#1096]
### Qwik Version

0.0.100

### Operating System (or Browser)

Debian Linux

### Which component is affected?

Qwik Runtime

### Expected Behaviour

If I call useWatch to track a context object, it should run every time the context changes.

### Actual Behaviour

it is only called once.

### Additional Information

Click inside the black box and move your mouse. There are also console logs to show when each function fires. It seems to be related to setting nested values in the base store. Setting recursive: true doesn't seem to make a difference. 

Broken example:
https://qwik.builder.io/playground#version=0.0.100&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMkMlMjBjcmVhdGVDb250ZXh0JTJDJTIwdXNlQ29udGV4dCUyQyUyMHVzZUNvbnRleHRQcm92aWRlciUyQyUyMHVzZVdhdGNoJTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGludGVyZmFjZSUyMFBvcyUyMCU3QiU1Q24lMjAlMjB4JTNBJTIwbnVtYmVyJTJDJTVDbiUyMCUyMHklM0ElMjBudW1iZXIlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBpbnRlcmZhY2UlMjBTdGF0ZSUyMCU3QiU1Q24lMjAlMjBkcmFnJTNBJTIwJTdCJTIwc3RhcnQlM0ElMjBQb3MlMkMlMjBjdXJyZW50JTNBJTIwUG9zJTIwJTdEJTIwJTdDJTIwdW5kZWZpbmVkJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBDVFglMjAlM0QlMjBjcmVhdGVDb250ZXh0JTNDU3RhdGUlM0UoJ0FwcFN0YXRlJyklM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwV2lkZ2V0JTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwcG9zaXRpb24lMjAlM0QlMjB1c2VTdG9yZSglN0IlMjB4JTNBJTIwMCUyQyUyMHklM0ElMjAwJTIwJTdEKSUzQiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTIwJTNEJTIwdXNlQ29udGV4dChDVFgpJTNCJTVDbiUyMCUyMHVzZVdhdGNoJTI0KCglN0J0cmFjayU3RCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBkcmFnJTIwJTNEJTIwdHJhY2soc3RhdGUlMkMlMjAnZHJhZycpJTNCJTVDbiUyMCUyMCUyMCUyMGlmJTIwKGRyYWcpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGxldCUyMGQlM0ElMjBQb3MlMjAlM0QlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIweCUzQSUyMGRyYWcuc3RhcnQueCUyMC0lMjBkcmFnLmN1cnJlbnQueCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB5JTNBJTIwZHJhZy5zdGFydC55JTIwLSUyMGRyYWcuY3VycmVudC55JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBwb3NpdGlvbi54JTIwJTNEJTIwcG9zaXRpb24ueCUyMC0lMjBkLnglM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwcG9zaXRpb24ueSUyMCUzRCUyMHBvc2l0aW9uLnklMjAtJTIwZC55JTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZygndXNlV2F0Y2gnKSUzQiU1Q24lMjAlMjAlN0QpJTVDbiUyMCUyMHJldHVybiUyMCUzQ2RpdiUyMHN0eWxlJTNEJTVDJTIyYmFja2dyb3VuZC1jb2xvciUzQSUyMGJsYWNrJTNCJTIwY29sb3IlM0ElMjB3aGl0ZSUzQiUyMHBhZGRpbmclM0ElMjAxcmVtJTNCJTIwdXNlci1zZWxlY3QlM0ElMjBub25lJTNCJTVDJTIyJTIwb25Nb3VzZURvd24lMjQlM0QlN0IoZSklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ2RyYWclMjBzdGFydCcpJTNCJTVDbiUyMCUyMCUyMCUyMHN0YXRlLmRyYWclMjAlM0QlMjAlN0IlMjAlNUNuJTIwJTIwJTIwJTIwJTIwJTIwc3RhcnQlM0ElMjAlN0J4JTNBJTIwZS5jbGllbnRYJTJDJTIweSUzQWUuY2xpZW50WSU3RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjdXJyZW50JTNBJTIwJTdCeCUzQSUyMGUuY2xpZW50WCUyQyUyMHklM0ElMjBlLmNsaWVudFklMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCU3RCU3RCUzRUNsaWNrJTIwYW5kJTIwRHJhZyUyMCU3QiU2MCUyNCU3QnBvc2l0aW9uLnglN0QlMkMlMjAlMjQlN0Jwb3NpdGlvbi55JTdEJTYwJTdEJTNDJTJGZGl2JTNFJTVDbiU3RCklNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwc3RvcmUlM0ElMjBTdGF0ZSUyMCUzRCUyMHVzZVN0b3JlKCU3QmRyYWclM0ElMjB1bmRlZmluZWQlN0QpJTVDbiUyMCUyMHVzZUNvbnRleHRQcm92aWRlcihDVFglMkMlMjBzdG9yZSklM0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTIwZG9jdW1lbnQlM0Fvbk1vdXNlTW92ZSUyNCUzRCU3QihlKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBpZiUyMChzdG9yZS5kcmFnKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZygnZHJhZ2dpbmcnKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBzdG9yZS5kcmFnLmN1cnJlbnQlMjAlM0QlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIweCUzQSUyMGUuY2xpZW50WCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB5JTNBJTIwZS5jbGllbnRZJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTdEJTdEJTVDbiUyMCUyMGRvY3VtZW50JTNBb25Nb3VzZVVwJTI0JTNEJTdCKCklMjAlM0QlM0UlMjAlN0Jjb25zb2xlLmxvZygnZHJhZyUyMGVuZCcpJTNCJTIwc3RvcmUuZHJhZyUyMCUzRCUyMHVuZGVmaW5lZCU3RCU3RCU1Q24lMjAlMjAlM0UlNUNuJTIwJTIwJTIwJTIwJTNDV2lkZ2V0JTJGJTNFJTVDbiUyMCUyMCUzQyUyRmRpdiUzRSUzQiU1Q24lN0QpJTNCJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFwcCUyMCU3RCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE

Working example:
https://qwik.builder.io/playground#version=0.0.100&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMkMlMjBjcmVhdGVDb250ZXh0JTJDJTIwdXNlQ29udGV4dCUyQyUyMHVzZUNvbnRleHRQcm92aWRlciUyQyUyMHVzZVdhdGNoJTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGludGVyZmFjZSUyMFBvcyUyMCU3QiU1Q24lMjAlMjB4JTNBJTIwbnVtYmVyJTJDJTVDbiUyMCUyMHklM0ElMjBudW1iZXIlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBpbnRlcmZhY2UlMjBTdGF0ZSUyMCU3QiU1Q24lMjAlMjBkcmFnJTNBJTIwJTdCJTIwc3RhcnQlM0ElMjBQb3MlMkMlMjBjdXJyZW50JTNBJTIwUG9zJTIwJTdEJTIwJTdDJTIwdW5kZWZpbmVkJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBDVFglMjAlM0QlMjBjcmVhdGVDb250ZXh0JTNDU3RhdGUlM0UoJ0FwcFN0YXRlJyklM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwV2lkZ2V0JTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwcG9zaXRpb24lMjAlM0QlMjB1c2VTdG9yZSglN0IlMjB4JTNBJTIwMCUyQyUyMHklM0ElMjAwJTIwJTdEKSUzQiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTIwJTNEJTIwdXNlQ29udGV4dChDVFgpJTNCJTVDbiUyMCUyMHVzZVdhdGNoJTI0KCglN0J0cmFjayU3RCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBkcmFnJTIwJTNEJTIwdHJhY2soc3RhdGUlMkMlMjAnZHJhZycpJTNCJTVDbiUyMCUyMCUyMCUyMGlmJTIwKGRyYWcpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGxldCUyMGQlM0ElMjBQb3MlMjAlM0QlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIweCUzQSUyMGRyYWcuc3RhcnQueCUyMC0lMjBkcmFnLmN1cnJlbnQueCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB5JTNBJTIwZHJhZy5zdGFydC55JTIwLSUyMGRyYWcuY3VycmVudC55JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBwb3NpdGlvbi54JTIwJTNEJTIwcG9zaXRpb24ueCUyMC0lMjBkLnglM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwcG9zaXRpb24ueSUyMCUzRCUyMHBvc2l0aW9uLnklMjAtJTIwZC55JTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZygndXNlV2F0Y2gnKSUzQiU1Q24lMjAlMjAlN0QpJTVDbiUyMCUyMHJldHVybiUyMCUzQ2RpdiUyMHN0eWxlJTNEJTVDJTIyYmFja2dyb3VuZC1jb2xvciUzQSUyMGJsYWNrJTNCJTIwY29sb3IlM0ElMjB3aGl0ZSUzQiUyMHBhZGRpbmclM0ElMjAxcmVtJTNCJTIwdXNlci1zZWxlY3QlM0ElMjBub25lJTNCJTVDJTIyJTIwb25Nb3VzZURvd24lMjQlM0QlN0IoZSklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ2RyYWclMjBzdGFydCcpJTNCJTVDbiUyMCUyMCUyMCUyMHN0YXRlLmRyYWclMjAlM0QlMjAlN0IlMjAlNUNuJTIwJTIwJTIwJTIwJTIwJTIwc3RhcnQlM0ElMjAlN0J4JTNBJTIwZS5jbGllbnRYJTJDJTIweSUzQWUuY2xpZW50WSU3RCUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjdXJyZW50JTNBJTIwJTdCeCUzQSUyMGUuY2xpZW50WCUyQyUyMHklM0ElMjBlLmNsaWVudFklMjAlN0QlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCU3RCU3RCUzRUNsaWNrJTIwYW5kJTIwRHJhZyUyMCU3QiU2MCUyNCU3QnBvc2l0aW9uLnglN0QlMkMlMjAlMjQlN0Jwb3NpdGlvbi55JTdEJTYwJTdEJTNDJTJGZGl2JTNFJTVDbiU3RCklNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwc3RvcmUlM0ElMjBTdGF0ZSUyMCUzRCUyMHVzZVN0b3JlKCU3QmRyYWclM0ElMjB1bmRlZmluZWQlN0QpJTVDbiUyMCUyMHVzZUNvbnRleHRQcm92aWRlcihDVFglMkMlMjBzdG9yZSklM0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTIwZG9jdW1lbnQlM0Fvbk1vdXNlTW92ZSUyNCUzRCU3QihlKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBpZiUyMChzdG9yZS5kcmFnKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZygnZHJhZ2dpbmcnKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBzdG9yZS5kcmFnJTIwJTNEJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMC4uLnN0b3JlLmRyYWclMkMlMjAlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY3VycmVudCUzQSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB4JTNBJTIwZS5jbGllbnRYJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHklM0ElMjBlLmNsaWVudFklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTdEJTdEJTVDbiUyMCUyMGRvY3VtZW50JTNBb25Nb3VzZVVwJTI0JTNEJTdCKCklMjAlM0QlM0UlMjAlN0Jjb25zb2xlLmxvZygnZHJhZyUyMGVuZCcpJTNCJTIwc3RvcmUuZHJhZyUyMCUzRCUyMHVuZGVmaW5lZCU3RCU3RCU1Q24lMjAlMjAlM0UlNUNuJTIwJTIwJTIwJTIwJTNDV2lkZ2V0JTJGJTNFJTVDbiUyMCUyMCUzQyUyRmRpdiUzRSUzQiU1Q24lN0QpJTNCJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFwcCUyMCU3RCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE

Relevant change starts on line 44 in each.

**Comment by manucorporat** [comment]
I am not sure this is a bug, in the first example:

```
track(store, 'drag')
```

is doing exactly that, tracking the drag property of store, but it's not changing, I can see the confusing, but track() is not recursive

**Comment by nnelgxorz** [comment]
Fair enough. Would it be possible to make track recursive with an option like useStore? I'll open a feature request if so. 👍
