### ISSUE TITLE
[DOCS] update the docs to precise meaning of «closure»

### ISSUE THREAD

**Issue by tidiview** [BuilderIO/qwik#1099]
**How can the documentation be improved?**
By precising the meaning of term «closure» in [https://qwik.builder.io/tutorial/component/inline/](https://qwik.builder.io/tutorial/component/inline/).
I'm sorry, I don't understand what is meant here:
«More than just components: Qwik lazy-loads any closure including components, event listeners, effects, and behaviors.»
and here:
«$ marks a closure as lazy-loadable.»
it seems like an important concept of Qwik syntax but it's too schematic right now.
What does it close? or towards what it is open?
How is it a closure? to what?
What is the relationship with lazy-loading?

**Comment by manucorporat** [comment]
Agreed, we jump very quickly into low level concepts.
One of the primitives of Qwik is the ability to serialize functions! but not only functions but closures!!
https://en.wikipedia.org/wiki/Closure_(computer_programming)

Closure if a function + environment:
```tsx
function foo() {
  const state = 123;
  return () => { // this is a closure (ie a function + captures state variable)
    console.log(state);
  };
};
```

**Comment by tidiview** [comment]
Thanks for the explanation: it more clear now _but_ how do you introduce this definition in the tutorial so that it's clearer?
