### ISSUE TITLE
SSR build should use prod mode in build

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#1109]
### Qwik Version

0.0.101

### Operating System (or Browser)

all

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

When building for production using the vite plugin, the SSR build executes in dev mode. While we still want the ssr build to not be minified by default, it's very costly to have qDev enabled.

### Actual Behaviour

in prod mode qDev === false

**Comment by manucorporat** [comment]
Fixed!

**Comment by shairez** [comment]
That was qwik @manucorporat ! 😀
great job! 💪👏
