### ISSUE TITLE
error with entry.cloudflare.tsx after updating 0.0.101

### ISSUE THREAD

**Issue by tidiview** [BuilderIO/qwik#1110]
### Qwik Version

v0.0.101

### Operating System (or Browser)

windows

### Node Version (if applicable)

16.16.0

### Which component is affected?

Qwik City

### Expected Behaviour

normal behaviour build command

### Actual Behaviour

here the error I encountered:
![error-following-101-update](https://user-images.githubusercontent.com/14911996/185906060-2c22eda8-28a1-4bd4-8fcf-37ebc2c8e79e.jpg)
it seems that 0.0.101 uses a new way with cloudflares pages and that is source of the bug.

### Additional Information

I used Cloudflares pages.
0.0.101 is introducing a middleware that changes `entry.cloudflare.tsx`.
But that seems not to be updated in the process of updating with version 0.0.101.

**Comment by tidiview** [comment]
log from cloudflare pages deployment log monitor:
![error-following-101-update-2](https://user-images.githubusercontent.com/14911996/185984788-fd37b191-5199-49ed-9b00-b847fdc00a43.jpg)

**Comment by tidiview** [comment]
I have been able to run a new starter project from cli to cloudflare pages, so the problem is for a existing project that is updated from 0.0.100 to 0.0.101

**Comment by adamdbradley** [comment]
This should be fixed with the latest version of Qwik and Qwik City. Please reopen if you are still seeing an issue, thanks.

**Comment by tidiview** [comment]
I reopen as I am not using Qwik City therefore, the problem has not been fixed with the upgrade of only Qwik. What can I do?
