### ISSUE TITLE
Provide URL information in envData by the qwikVite plugin

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#1112]
### Qwik Version

latest

### Operating System (or Browser)

any

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

useEnvData('url') should provide the href as string

### Actual Behaviour

There is no way to get the URL

**Comment by adamdbradley** [comment]
Closed with https://github.com/BuilderIO/qwik/pull/1116
