### ISSUE TITLE
dev.ssr performance when route name same as root file in user's disk

### ISSUE THREAD

**Issue by youngboy** [BuilderIO/qwik#1125]
### Qwik Version

0.0.102

### Operating System (or Browser)

mac

### Which component is affected?

Qwik City

### Expected Behaviour

issue report from `steranevdy` on discord, reproduce in my machine as well
version 
```
"@builder.io/qwik": "0.0.102"
"@builder.io/qwik-city": "0.0.104"
```

In starters, create route named `home`, run command `npm run dev.ssr`

expect page render speed is on 20ms~

### Actual Behaviour

page render speed is around 300ms ~ 1s

### Additional Information

not expert on vite, but I tried to debugging at my best, found out every request will go through vite:resolve plugin at first, if no match then qwik-city's devServer middleware.

so code in https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/resolve.ts#L260

handling '/home' html request, will attempt to search '/home' absolute file path, then hit without read permission (at least in mac or my machine....). 

then result in issue of https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/resolve.ts#L508 

IMHO, There is chance to optimize dev perf for HTML request no need to go through whole vite plugins middleware one by one( or at least let qwik-city handle it first), https://vitejs.dev/guide/ssr.html#setting-up-the-dev-server might helps here.

Also noticed that default vite's conf `appType` default is SPA, maybe need to change something else.

**Comment by adamdbradley** [comment]
Closed w/ https://github.com/BuilderIO/qwik/commit/a84e0d9a5fcb32c22bfb333cc0bd1c79a1f0032b
