### ISSUE TITLE
SSR Styling - Flash of unstyled content

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#1128]
When page is render in SSR `<style>` tags are inserted with the component. These `<style>` tags need to move to `<head>`. This is done while rendering, but there is a bug where the `<style>` is removed, the browser renders, and then the `<style>` is reinserted. This causes a flash of unstyled content.

I think a better way to do this is to just close the stream with this code:
```html
<script>document.querySelectorAll('style[q\\:style]').forEach(s => document.head.appendChild(s))</script>
```

The above code will move the styles as soon as the streaming is done, and because the move is done in a single tick, there is no flash of unstyled content.

**Comment by wmertens** [comment]
Why do the styles need to move to `<head>`? Doesn't this interfere with containers?

**Comment by wmertens** [comment]
I just understood the real issue - that when useStyles$ renders a style, and that component gets removed, it removes the style too.

Even worse, other still mounted components will lose their style, no?

I agree that this code should be inserted when useStyles*$ was used.

**Comment by wmertens** [comment]
@mhevery it is my understanding that this is fully fixed and this can be closed
