### ISSUE TITLE
 error with entry.cloudflare.tsx after updating 0.0.101 #1110 

### ISSUE THREAD

**Issue by tidiview** [BuilderIO/qwik#1131]
I reopen as I am not using Qwik City therefore, the problem has not been fixed with the upgrade of only Qwik. What can I do?
What I see is same as above locally.

_Originally posted by @tidiview in https://github.com/BuilderIO/qwik/issues/1110#issuecomment-1223731662_

**Comment by mrmcc3** [comment]
My understanding is `entry.cloudflare.tsx` is provided as part of the qwik city starter. It exports the qwik city middleware. If you're not using qwik city then you'll likely have to setup your own cloudflare entry point that uses qwik directly to render responses from cloudflare pages functions.

**Comment by tidiview** [comment]
That makes sense.
So before update, you could use Qwik with Cloudflare, but update made it part of Qwik City therefore, it's not working anymore.
