### ISSUE TITLE
Improve debugging component experience

### ISSUE THREAD

**Issue by youngboy** [BuilderIO/qwik#1140]
### Is your feature request related to a problem?

inspecting element in dev tools hard to locate the components wrote

### Describe the solution you'd like

add name property to virtual host if in dev mode.

### Describe alternatives you've considered

implement dev tool extension, then we can collapse component, inspect how props pass by

### Additional context

Not sure if it is need, and how much it will helps on develop experience

**Comment by manucorporat** [comment]
We could fork react devtools for this purpose, but i think it's two things. Adding a name property is easy compared.

I think it should be easy enough to add the name

**Comment by zanettin** [comment]
@youngboy i just saw that @manucorporat has created a new issue covering this topic over here https://github.com/BuilderIO/qwik/issues/2252.

**Comment by zanettin** [comment]
Hi @youngboy 
I close this issue due to the above mentioned reason. if smth is not working as expected, feel free to create a new issue 🙏  thanks
