### ISSUE TITLE
Input in basic starter loses focus after loading script

### ISSUE THREAD

**Issue by jesperp** [BuilderIO/qwik#116]
Hi, 
First of all, thanks for building this very exciting piece of technology :)
I'm just trying the [simple starter ](https://stackblitz.com/edit/qwik-starter) and I think there is something that's not working as intended. When I first start typing something in the text field it loses focus almost immediately (when the script finishes loading?). But this doesn't happen re-focusing and typing again, check my short video for demonstration. This is surely not the intended behaviour?

https://user-images.githubusercontent.com/376921/147286688-487b0ab0-dd96-4666-8342-036bc240969c.mov

**Comment by manucorporat** [comment]
I noticed this issue too

**Comment by jesperp** [comment]
Tried a few different scenarios and looked at the flash of updates in dev tools...

Original example
<img width="571" alt="Screenshot 2021-12-25 at 21 16 55" src="https://user-images.githubusercontent.com/376921/147393136-9232303b-897a-4c1e-8e01-2babf5565d6f.png">

Put the text in a paragraph (focus issue goes away)
<img width="581" alt="Screenshot 2021-12-25 at 21 17 15" src="https://user-images.githubusercontent.com/376921/147393139-8af7a1a5-9d5e-47e6-82f3-b6bb3b3493aa.png">

Placing the input as a lone sibling and things work as expected?
<img width="521" alt="Screenshot 2021-12-25 at 21 34 33" src="https://user-images.githubusercontent.com/376921/147393249-bdb18983-1640-4d16-a329-43414c7ddb2f.png">

Any ideas? 🤔

**Comment by igrep** [comment]
I found that [the `replaceNode` function](https://github.com/BuilderIO/qwik/blob/63b66fdc112cda3e9695de2477e13ef1df97b42a/src/core/render/cursor.ts#L411) causes this by removing the `input` element before putting the mounted `input`. So perhaps it should keep focus after replacing. You'll see this by setting a break point when the initial `input` element is removed.

**Comment by mhevery** [comment]
I looked into it. The issue with this line: https://github.com/BuilderIO/qwik/blob/e4493e57f1e5bdad89b071ab0c824a9efd367e93/starters/apps/starter/src/my-app.tsx#L25

Notice that there is text + `{' '}`. Thes creates two text nodes. When these text nodes get serialized into HTML they get merged into one. Once the reconciliation algorithm runs the result is that the JSX does not match the HTML and results in the `<input` being destroyed and re-created. This results in loss of focus.

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/commit/7fadd186e2358c95cd5902a800c24b448e6d19c5
