### ISSUE TITLE
Support history router

### ISSUE THREAD

**Issue by lzxb** [BuilderIO/qwik#1187]
### Is your feature request related to a problem?

When I see the routing solutions given in the official documents, the page will be refreshed

### Describe the solution you'd like

Similar to react router

### Describe alternatives you've considered

-

**Comment by zanettin** [comment]
Hi @lzxb 👋 
Do you mean with `history router` SPA navigation? This would be possible by using the `<Link>` [component](https://qwik.builder.io/qwikcity/api/#link). Or something else? Thanks for your reply 🙏

**Comment by lzxb** [comment]
it is supported
