### ISSUE TITLE
[DOCS] Whether the container has been implemented and there are corresponding examples

### ISSUE THREAD

**Issue by lzxb** [BuilderIO/qwik#1189]
docs: https://qwik.builder.io/docs/advanced/containers/

Our team is currently using vue2 to build a large-scale SSR microservice architecture. With the development of business scale, the amount of code is increasing. QWIK can solve the problems we currently encounter

**Comment by zanettin** [comment]
Hi @lzxb 
Just wanted to share a link from Manu where he's talking about the containers:
https://www.youtube.com/watch?v=Mi7udzhcCDQ&t=1753s. Guess we still need to add some examples to the docs 👍 
@manucorporat do you have any examples we could share on the docs page?

**Comment by dmitry-stepanenko** [comment]
There's also a good resource here https://blog.cloudflare.com/fragment-piercing/ along with an implementation with qwik+nx here https://github.com/gioboa/qwik-dream-demo

**Comment by gioboa** [comment]
Here is the [containers documentation page](https://qwik.builder.io/docs/advanced/containers/)
