### ISSUE TITLE
The useResource$ hook is not fetching the resource properly, causing an error in the edge function. (works locally, but not in deployment via Netlify Edge middleware).

### ISSUE THREAD

**Issue by ghost** [BuilderIO/qwik#1190]
### Qwik Version

v0.0.105 (Qwik) and v0.0.104 (Qwik City)

### Operating System (or Browser)

Ubuntu Linux, through WSL

### Node Version (if applicable)

v18.8.0

### Which component is affected?

Qwik City

### Expected Behaviour

The data (that does show up properly at the endpoint by the way) should be loaded into the useResource$ hook instance as expected, and display on the screen.

### Actual Behaviour

The resource is constantly in the loading state, and the edge function through netlify displays an error as such:
![image](https://user-images.githubusercontent.com/108161206/187818415-61515133-a548-4e3f-a05c-2f09af8d8288.png)

The endpoint displays the correct REST data, but it is unable to be fetched via the endpoint located inside of the same app.

### Additional Information

I believe that it is related to the Netlify Edge middleware, but I am not too sure.

**Comment by mhevery** [comment]
This seems like the server is throwing in error something like `Recusive ....` And then client is trying to parse it which then displays the parsing Error, as it is not valid JSON.

Could you look into the dev-tools network tab and see what the actual error is?

**Comment by zanettin** [comment]
Hi @ghost 👋 
Did you already have a chance to try the latest version of qwik? would be great to have the data Misko requested to debug it 🙏

**Comment by zanettin** [comment]
The creator of this issue has deleted his account and we don't have a repro. I am closing this 🧹
