### ISSUE TITLE
Unable to use `useContext()` in `<Global/>` component

### ISSUE THREAD

**Issue by brechtbilliet** [BuilderIO/qwik#1191]
### Qwik Version

0.0.107

### Operating System (or Browser)

Mac os (chrome)

### Which component is affected?

Qwik Runtime

### Expected Behaviour

# What I'm trying to do

I tried to keep this repo as minimal as possible so it would be easier to focus on the bug.
Nevertheless, let me explain what I'm trying to achieve.

I want to use clientside routing so I'm not using QwikCity. I want my components to be able to set
the title. Let's say we have a detail user page. That component should set the title
 to `<title>Details of John Doe</title>`. Since the `useDocument()` was removed there was no way
 to set the title and description anymore. We have to set it at the root of the application.
 
 Since the `root.tsx` is not a component we can't use `useContext` or `useStore` there.
 
 Then I've tried to create a `<Head>` component but that also needed a parent to communicate between
 the other components and itself.
 
 After that I've created a `<Global>` component which is here inside this demo.
 Everything works perfectly until I use `const rootState = useContext(ROOTSTATE);`

I expect this to work without any errors
 

### Actual Behaviour

I get the following error
 
 <blockquote>
 QWIK ERROR Missing &lt;head&gt;. Global styles could not be rendered. Please render a &lt;head&gt; element at the root of the app Error: Missing &lt;head&gt;. Global styles could not be rendered. Please render a &lt;head&gt; element at the root of the app

 </blockquote>
 

### Additional Information

 So we can put everything inside a `<Global/>` and that works until we use `useContext` there.
Here is the repo to reproduce this issue:
https://github.com/rosahealth/qwik-global-error

**Comment by ptz0n** [comment]
I believe other cases with similar needs would be when rendering modal dialogs and navigation components. You want to resolve properties at a route to then be accessible globally when needed.

**Comment by manucorporat** [comment]
In the repo i dont see any place using useContextProvider() 
https://qwik.builder.io/docs/components/context/#usecontextprovider

Regarding: `Missing <head>. Global styles could not be rendered. ` might be related wit the fact that a componen t is rendering `<html>` this is unfortunately not possible. <html> is implicit, it's the container of the app.

Going to update some of the docs + better logs right now

**Comment by brechtbilliet** [comment]
> In the repo i dont see any place using useContextProvider() https://qwik.builder.io/docs/components/context/#usecontextprovider
> 
> Regarding: `Missing <head>. Global styles could not be rendered. ` might be related wit the fact that a componen t is rendering `<html>` this is unfortunately not possible. is implicit, it's the container of the app.
> 
> Going to update some of the docs + better logs right now

I added `useContextProvider` but I get the same issue

**Comment by manucorporat** [comment]
useContextProvider() needs to be set on a parent

**Comment by brechtbilliet** [comment]
It's set on the `Global` component which lives directly under `root.tsx` I believe this is the highest parent

**Comment by manucorporat** [comment]
you are setting the context in the same component you are reading it… why? useContext() gets it from a parent, this is by design, so components can rewrite the context. I am bit confused, what is expected to work?

**Comment by brechtbilliet** [comment]
I managed to get it working. I pushed to the repo... The problem was the following.
The `root.tsx` needed to have the `<html>` tags in there. Otherwise it gave an error of something not being able to get closed.

```html
 <html>
     <Global></Global>
 </html>
```
Now I'm able to set the title in the repo. Thanks for your time!
