### ISSUE TITLE
Out of bounds inflate access. Close not found.

### ISSUE THREAD

**Issue by ronnyek** [BuilderIO/qwik#1192]
### Qwik Version

0.0.107

### Operating System (or Browser)

Windows / Chrome

### Node Version (if applicable)

16.13.1

### Which component is affected?

Qwik Runtime

### Expected Behaviour

I created a qwik city basic project and added a basic component for testing called user menu. 
``` ts
//usermenu.tsx
import { component$, useStore } from "@builder.io/qwik";

export const UserMenu = component$(() => {
  const store = useStore({isOpen: false});
  return (
    <div>
      <button onClick$={() => (store.isOpen = !store.isOpen)}>
        User User
      </button>
      {store.isOpen &&
        <span>User Menu is open!</span>
      }
    </div>
  );
});
```

I then modified the layout.tsx to include that component. 
I expect the component to render, and be interactive

### Actual Behaviour

Component renders fine, but the moment I click the button, nothing happens and the javascript console has the following errors
```
Uncaught (in promise) Error: close not found
    at findClose (virtual-element.js:303:11)
    at getVirtualElement (virtual-element.js:281:23)
    at processVirtualNodes (virtual-element.js:268:25)
    at hasQId (store.js:766:18)
    at Object.acceptNode (store.js:494:20)
    at getNodesInScope (store.js:499:34)
    at resumeContainer (store.js:77:5)
    at resumeIfNeeded (props.js:18:9)
    at useLexicalScope (use-lexical-scope.public.js:31:9)
    at UserMenu_component_div_button_onClick_tlPB8QUzzQU (usermenu_component_div_button_onclick_tlpb8quzzqu.js:3:21)
    at dispatch ((index):101:33)
```

### Additional Information

This may be related to #1093

I would be willing to try work arounds, and spent some time trying to trace into it a bit, but not familiar enough with the framework to know how to go about troubleshooting further.

**Comment by ronnyek** [comment]
As requested, here is an example of the layout
``` ts
// layout.tsx in stock location for qwik city app
import { component$, Slot } from '@builder.io/qwik';
import { UserMenu } from "../components/layout/header/usermenu/usermenu";

export default component$(() => {
  return (
   <div>
     <UserMenu />
     <Slot/>
   </div>
  );
});
```

The user menu is located at /src/components/layout/header/usermenu/usermenu.tsx. I could make `usermenu.tsx` just `index.tsx` if that is expected to help at all.

**Comment by ronnyek** [comment]
Another update... 
Directly out of the box it works as expected. I chose tailwindcss in the little cli tool and after adding 
```
<link rel="stylesheet" href="http://https://rsms.me/inter/inter.css"/>
```
Between head tags in root.tsx
and
``` css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

In global.css, the problem immediately starts occuring. I can get it to work with the tailwind imports, but to get it working after linking the inter.css font, I have to remove the link tag, and restart dev.

Is there a more appropriate way to import a 3rd party css from a cdn or something?

**Comment by manucorporat** [comment]
ok, thats what i meant… this problem usually happens with a lot of things happens at the same time. I will look at it

**Comment by manucorporat** [comment]
Followed the steps, and i cant reproduce the issue

**Comment by ronnyek** [comment]
Do we currently have a place like stackblitz where I can setup a reproduction and send a link to a place here? All i had to do was create qwikcity app with tailwind, make those changes to root.tsx (adding a css link to inter.css between head tags) and the tailwind init stuff in global.css. 

It may require a restart of dev server, but thats literally all I did... and then clicking my button which changes state caused that error.

**Comment by youngboy** [comment]
@ronnyek for stackblitz reproduction, it can be setup like this https://github.com/youngboy/yb-sb-starters , or you can just use mine 😅 and update deps

**Comment by ronnyek** [comment]
https://stackblitz.com/edit/github-k7xvbn?file=src/root.tsx

I simply added my component, added the link to inter.css in the head tags in root.tsx. If you click the button, then look at errors in the js console, you should be able to see the same error

**Comment by ronnyek** [comment]
@manucorporat can you confirm this reproduction is providing enough?

**Comment by manucorporat** [comment]
yes, the problem is that <Head> does not have a Slot, so the link is projected in a weird spot inside the <html> element.

Put the <link> inside the head component in the head.tsx file, and it should work.

In the meantime, we have updated the starters to make it less error prone.

https://github.com/BuilderIO/qwik/blob/main/starters/apps/blank/src/root.tsx#L16

**Comment by ronnyek** [comment]
Hahaha my bad... I totally didn't realize that head tag was an actual component and not just plain html head tags.

I'm sorry I lead everyone on a goose chase here.
