### ISSUE TITLE
Conflicts with document title and an svg title

### ISSUE THREAD

**Issue by adamdbradley** [BuilderIO/qwik#1193]
### Qwik Version

latest

### Operating System (or Browser)

all

### Which component is affected?

Qwik Runtime

### Expected Behaviour

You can set a head title and any number of svg titles, and the browser's document title is always correct.

### Actual Behaviour

If the root.tsx JSX node has both a head title, and it has an svg with a title, it's random which title is set to the document, or it's random that the head title gets removed.

**Comment by manucorporat** [comment]
Fixed in main
