### ISSUE TITLE
The modified style cannot be hot updated. The service must be restarted

### ISSUE THREAD

**Issue by lzxb** [BuilderIO/qwik#1198]
### Qwik Version

0.0.107

### Operating System (or Browser)

Mac os chrome  104.0.5112.79 (arm64)

### Node Version (if applicable)

v16.13.2

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

The modified style should be hot updated

### Actual Behaviour

The modified style cannot be hot updated. The service must be restarted

**Comment by lzxb** [comment]
It is in [bugfix-hot-reload-style](https://github.com/lzxb/qwik-demo/tree/bugfix-hot-reload-style) branch Branch
https://github.com/lzxb/qwik-demo/blob/bugfix-hot-reload-style/src/components/app/app.tsx#L4

**Comment by manucorporat** [comment]
can you explain how to reproduce it?

**Comment by lzxb** [comment]
```bash
git clone git@github.com:lzxb/qwik-demo.git
cd qwik-demo 
git checkout bugfix-hot-reload-style
npm install
npm run dev
```
Modify the style of `src/components/app/app.tsx` file

**Comment by zanettin** [comment]
Hi @lzxb 👋 
Quickly tested it on qwik.new with latest versions and for me it looks like it is resolved now 👍 can you confirm that?

**Comment by lzxb** [comment]
i try it now, it is ok
