### ISSUE TITLE
<Resource> onPending return element attributes remain after onResolved, unless the element changed or the attributes are explicitly overwritten

### ISSUE THREAD

**Issue by jmmon** [BuilderIO/qwik#1201]
### Qwik Version

0.0.107, dev mode

### Operating System (or Browser)

Windows

### Node Version (if applicable)

v16.16.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

(Using TailwindCSS)
1. Given a <Resource> element with:
`onPending={() => <div class="text-5xl bg-yellow-400">Loading...</div>}
onResolved={() =><div>Finished</div>}`

Expected a flash of "Loading..." with large text yellow background, and then finally displays "Finished" with regular text size and no background.

2. Given a <Resource> element with:
`onPending={() => <div onClick$={() => console.log('hello loading')}>Loading...</div>}
onResolved={() =><div>Finished</div>}`

Expected a flash of "Loading..." that does a console.log when clicked, and then finally displays "Finished" and clicking should do nothing.

3. Given a <Resource> element with:
`onPending={() => <div dir="rtl">Loading...</div>}
onResolved={() =><div>Finished...</div>}`

Expected "...Loading" and then  "Finished..."

### Actual Behaviour

Actual:
1. Flash of "Loading..." with large text yellow background, and then finally displays "Finished" still with large text and yellow background.

2. Both "Loading..." and "Finished" trigger the console.log

3. Both were "rtl": "...Loading" and then "...Finished"

### Additional Information

More examples of broken and working JSX returned from the `onResolved` callback:

### Things that do NOT work (still broken):
1. `<div onClick$={() => console.log('hello finished')}>Finished...</div>`
2. `<div style="display: inline;">Finished...</div>`
3. `<div dir="rtl">Finished...</div>`
```
// 4. 
<div>Finished(1) // broken, keeps the yellow and large text styles from onPending
  <div class="bg-blue-200"> // half-broken, keeps the large text style but changes properly to blue bg
    <a href="#">Finished(2)</a>
  </div>
</div>
```

---

### Things that DO work (makes the text appear properly, without styles):
`<div class>Finished</div> // is declared even if no value`  
`<div class="">Finished</div> // class is declared as empty string`
`<div class="bg-blue-400">Finished</div> // class is declared with some class`
`<span>Finished</span> // different parent element is used`

---

### Note:
If the previous element has multiple attributes e.g.
`<div id="loading" class="bg-yellow-400" dir="rtl">Loading...</div>` 

then the new attribute must overwrite EACH of the attributes to prevent the bug e.g. 
1. `<div id>Finished...</div>` => `<div id="true" class="bg-yellow-400" dir="rtl">Finished...</div>`
2. `<div class>Finished...</div>` => `<div id="loading" class dir="rtl">Finished...</div>`
3. `<div class id dir>Finished...</div>` => `<div id="true" dir="true" class>Finished...</div>`

Number 3 is the only one that looks how it should because it overwrote ALL the old attributes 

---

Seems like, if the `onPending` and `onResolved` callbacks return JSX where the parent element types are the same, the DOM keeps all the attributes from the old element, and so the new element must define ALL of the old attributes in order to reset or revert them.

**Comment by jdgamble555** [comment]
`onPending` does not work. It is impossible currently to display a loader.

**Comment by wmertens** [comment]
@jdgamble555 
Hmm I checked and indeed it doesn't look like we have a test for it. Could you make an issue with a minimal repro ? That way we won't lose track of it. 

PRs are of course very welcome :)

**Comment by jdgamble555** [comment]
I have no understanding of the underlying code to do a PR.

Here is a REPO:

https://github.com/jdgamble555/qwik-streaming

J

**Comment by wmertens** [comment]
@jdgamble555 thanks! So I don't see client side interactivity, meaning you're getting the resource during SSR, and Qwik will wait until all resources are gotten.

During SSR, there's no onPending, only success or failure. But in the client, the onPending will show while the resource is loading.

**Comment by jdgamble555** [comment]
@wmertens - Does Qwik NOT support HTTP Streaming?

This is what other frameworks support allowing you to display a loader until the promise is resolved.

Here are working examples in SvelteKit, SolidStart, and NextJS:
- https://github.com/jdgamble555/svelte-streaming
- https://github.com/jdgamble555/solid-streaming
- https://github.com/jdgamble555/next-streaming

The data is streamed using SSR and the DOM is updated once the promise has resolved. 

I assumed this was possible using Qwik?

J

**Comment by wmertens** [comment]
@jdgamble555 no not yet, we're planning to add this after V2 release.
