### ISSUE TITLE
Feature Request: Warnings for `preventDefault` calls

### ISSUE THREAD

**Issue by dario-piotrowicz** [BuilderIO/qwik#1205]
In order to run the `preventDefault` of an event we need to add a `preventdefault` attribute (as described in the [docs](https://qwik.builder.io/docs/components/events/#prevent-default)) to the element, but possible `preventDefault` calls inside the callback can still be present even if they do nothing.

The different way to use `preventDefault` is something that developers could forget or not even be aware of (if they missed it in the docs) and currently they wouldn't get a clear indication of what is wrong with their code, so I was wondering if it would be possible to detect the use of `preventDefault` calls inside callbacks and warn the user that those will not have any effect (and pointing them to the docs).

For example, If I were to create a component like this:
```ts
const MyBtn = component$(() => {
  return (
    <button
      onClick$={(event) => {
        event.preventDefault();
        console.log('clicked');
      }}
    >
      click me
    </button>
  );
});
```

I would like to get somewhere a warning that the `event.preventDefault()` won't have any effect and that `preventdefault:click` should be used instead.

___

Some things I have in mind:
- It would be great to get the warning on the client side but I think that any sort of check would happen on the server, so the warning could potentially just be in the terminal, which could anyways still be helpful
- I get the feeling that the callbacks are generic so I am not sure if they have enough context attached to them to tell that they are callbacks, so that may be a challenge
- naturally the argument doesn't need to be called `event` it could be called `evt` instead, or destructured, etc..., so a possible solution would need to be quite robust (also based on the previous point, I could also have a function which takes an argument and calls it's `preventDefault`, being this some custom logic or even an event, so the sort of check would need to be applied specifically only on callbacks, as it would be undesirable/incorrect in other scenarios)

___

Anyways this type of warnings is not fundamental or anything, I just feel like it would help with DX and potentially avoid confusing situations, but if implementing something like this is too expensive/complex it may not be a worthwhile addition.

**Comment by nnelgxorz** [comment]
Agreed. Seems like a good use for a custom ESLint rule.

**Comment by dario-piotrowicz** [comment]
Ah yeah, sorry I missed that there is an qwik eslint plugin :see_no_evil: , yeah it definitely sounds like a good eslint rule addition :slightly_smiling_face: , I'm not the best at eslint stuff but I may try to give it a shot :slightly_smiling_face:

**Comment by manucorporat** [comment]
Now we have custom even types that signal the user about the broken preventDefault()
