### ISSUE TITLE
public files conflict with dynamic route

### ISSUE THREAD

**Issue by O-Hooman** [BuilderIO/qwik#1226]
### Qwik Version

qwik: 0.0.108, qwik-city: 0.0.108

### Operating System (or Browser)

MacOS Monterey 12.3.1 / Chrome 104.0.5112.79

### Node Version (if applicable)

14.19.1

### Which component is affected?

Qwik City

### Expected Behaviour

favicon.ico load from public/favicon.ico

### Actual Behaviour

favicon return 404, it's loaded from routes instead of public files

### Additional Information

so I make routes like this:
- src/routes/[category]/index.tsx
- src/routes/index.tsx
- src/routes/layout.tsx

and it seems favicon default loads from public/favicon.ico, because I have this route "[category]/index.tsx" it returns a 404 error because instead of load files from public/favicon.ico it hit "[category]/index.tsx" instead when the network load favicon.ico 

error image(it loads the page but shows this when loads favicon.ico):
<img width="892" alt="Screen Shot 2022-09-13 at 9 57 40 AM" src="https://user-images.githubusercontent.com/25758563/189800657-4c478894-8c64-4aca-8951-d28f8872bdad.png">

**Comment by shairez** [comment]
Thanks for the report @O-Hooman !

**Comment by adamdbradley** [comment]
This should be fixed as of https://github.com/BuilderIO/qwik/pull/2052, thanks for opening the issue
