### ISSUE TITLE
js files load slowly when dynamic route exists

### ISSUE THREAD

**Issue by O-Hooman** [BuilderIO/qwik#1227]
### Qwik Version

qwik: 0.0.108, qwik-city: 0.0.108

### Operating System (or Browser)

MacOS Monterey 12.3.1 / Chrome 104.0.5112.79

### Node Version (if applicable)

14.19.1

### Which component is affected?

Qwik City

### Expected Behaviour

js files load fast around 10ms

### Actual Behaviour

js files load slowly around 900ms

### Additional Information

so I make routes like this:
src/routes/[category]/index.tsx
src/routes/index.tsx
src/routes/layout.tsx

when i have dynamic route "[category]/index.tsx" it makes js files load slowly, maybe it hit [category]/index.tsx instead or not included to build cache control

when i remove route [category]/index.tsx:
<img width="1680" alt="Screen Shot 2022-09-13 at 10 20 18 AM" src="https://user-images.githubusercontent.com/25758563/189800421-f013b77a-1c43-4453-8df3-7d07a3e3b39b.png">

when i add route [category]/index.tsx: 
<img width="1680" alt="Screen Shot 2022-09-13 at 10 20 57 AM" src="https://user-images.githubusercontent.com/25758563/189800458-0971fbb2-afd2-4ca8-8fae-2a0aefa273a0.png">

**Comment by zanettin** [comment]
Hi @O-Hooman 👋 
Sorry to get back to you so late 🙈 do you have a sample app or a reproduction i could have a look at and try the latest state of qwik and qwik-city? thanks for creating this isse 🙏

**Comment by O-Hooman** [comment]
Hi @zanettin last time I tried it on the latest version (qwik-city 0.0.128) it was normal on the build file(js), but it still happens on the public file. Since there's a new update (qwik-city 0.1.0) and I've not tried it yet (I need to rewrite my code from onGet to loader$) and I'll let you know ASAP and create a reproduction on stack blitz if the behavior is still weird. Thanks for the response!

**Comment by zanettin** [comment]
Hi @O-Hooman 👋 Thanks again for your reply. Hope it is okay for you, when i close this issue for now. If the issue still persists after you've upgraded your app to latest, please feel free to create a new one 🙏 thanks again for your time 🙏
