### ISSUE TITLE
Request to POST endpoint crashes the server

### ISSUE THREAD

**Issue by steverandy** [BuilderIO/qwik#1228]
### Qwik Version

0.0.108

### Operating System (or Browser)

macOS

### Node Version (if applicable)

16.16.0

### Which component is affected?

Qwik City

### Expected Behaviour

Steps:

- Clone the repo (https://github.com/steverandy/qwik-app)
- Run `build` and `serve` to start the server.
- Go to `/api` page and click on "Test POST request".
- Server should not crash.

### Actual Behaviour

Server crashed with the following error:

```
file:///Users/steve/Developer/qwik-app/server/entry.express.js:851
              data.map((item) => item)
                   ^

TypeError: data.map is not a function
    at onResolved (file:///Users/steve/Developer/qwik-app/server/entry.express.js:851:20)
    at invoke (file:///Users/steve/Developer/qwik-app/node_modules/@builder.io/qwik/core.mjs:158:26)
    at file:///Users/steve/Developer/qwik-app/node_modules/@builder.io/qwik/core.mjs:150:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async renderRoot (file:///Users/steve/Developer/qwik-app/node_modules/@builder.io/qwik/core.mjs:5569:5)
    at async renderSSR (file:///Users/steve/Developer/qwik-app/node_modules/@builder.io/qwik/core.mjs:5565:5)
    at async renderToStream (file:///Users/steve/Developer/qwik-app/node_modules/@builder.io/qwik/server.mjs:585:3)
    at async file:///Users/steve/Developer/qwik-app/server/entry.express.js:1988:20
```

### Additional Information

I've also tested the flow with qwik v0.0.106 and there are no errors.

**Comment by zanettin** [comment]
Hi @steverandy 
Thanks for sharing your repo. I quickly checked it locally and can confirm the issue.
I also checked if the issue still exists after upgrading to latest qwik (`0.12.1`) using `yarn`:

```
yarn upgrade-interactive --latest // upgraded all pkgs
yarn qwik add express // to switch from the express middleware to the new introduced adaptors in v0.12.0
yarn build
yarn serve
```

![Bildschirmfoto 2022-10-30 um 20 58 31](https://user-images.githubusercontent.com/3241476/198899139-27482021-8113-47ba-b93f-129d051d6e82.png)

would you like to test this on your side as well?

**Comment by steverandy** [comment]
Thanks. I've just re-tested with qwik latest version (0.12.1) and no longer seeing the server crashed issue.

**Comment by zanettin** [comment]
very nice! thanks for your retesting🙏 since i don't have the power: would you mind to close the issue? 😄
