### ISSUE TITLE
`className`s get remove after container resume

### ISSUE THREAD

**Issue by dario-piotrowicz** [BuilderIO/qwik#1229]
### Qwik Version

0.0.108 (the issue is not present in 0.0.107)

### Operating System (or Browser)

macOS Monterey (Chrome v.105)

### Which component is affected?

Qwik Runtime

### Issue

I used to use `className` attributes in components (just a habit since that's what React does), but from 0.0.108 is seems that they are no longer being supported on resume.

I am not sure if this is a bug or if it is intended.

I've tried looking in the docs but there doesn't seem to be anything saying that `class` should be used instead of `className`

### Additional Information

I tried looking into it, but I'm not familiar with the codebase and wasn't sure how to get non-minified/sourcemapped code to debug, but by trying to figure stuff out and given that this got broken in 0.0.108, I have a strong suspicion that it was introduced in PR https://github.com/BuilderIO/qwik/pull/1195

**Comment by dario-piotrowicz** [comment]
I tried looking into it, but I'm not familiar with the codebase and wasn't sure how to get non-minified/sourcemapped code to debug, but by trying to figure stuff out and given that this got broken in 0.0.108, I have a strong suspicion that it was caused by PR #1195

**Comment by dario-piotrowicz** [comment]
Also for what it's worth, by checking things I saw that the class is not part of the `toRemove` argument of `setClasslist`, so it looks to me like qwik is not actually removing the class directly but the class gets lost in the process somehow

**Comment by shairez** [comment]
Thanks for the report @dario-piotrowicz !
