### ISSUE TITLE
Is it possible to use Qwik with NuxtJS?

### ISSUE THREAD

**Issue by quanglatte** [BuilderIO/qwik#1246]
### Is your feature request related to a problem?

I look forward to using Qwik in my NuxtJS projects to avoid the Nuxt hydrate problem.
If so, that would be great.

### Describe the solution you'd like

I look forward to using Qwik in my NuxtJS projects to avoid the Nuxt hydrate problem.
If so, that would be great.

### Describe alternatives you've considered

I look forward to using Qwik in my NuxtJS projects to avoid the Nuxt hydrate problem.
If so, that would be great.

**Comment by cayolblake** [comment]
I wanted to ask the same but for Svelte.

Is it possible?

**Comment by zanettin** [comment]
Hi @cayolblake 
Sry to get back to you so late 🙈 Qwik supports officially react. but there are several community driven project in the making 🎉 

vue: https://github.com/BuilderIO/qwik/pull/2248
preact: https://github.com/BuilderIO/qwik/pull/2742

it would be great to have more integrations 🙏

**Comment by adamdbradley** [comment]
Thanks for opening the issue, but we're narrowing the Github issues to just bug reports. 
Github issues is a place to explain a problem in detail, along with a reproduction case for maintainers. However, Github issues is not the best place to ask how-to or roadmap questions. 

I think this question is better asked in [Discord](https://qwik.builder.io/chat). Closing for now and hopefully you'll be able to get help there. Additionally, if you're able to find an answer to your question, a PR updating our docs would be appreciated. Thanks.
