### ISSUE TITLE
Feat: source maps in development

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#1251]
### Is your feature request related to a problem?

By enabling source maps in development we should be able to have stacktrades that point directly to files in your IDE. Allowing for better error messages and DX

### Describe the solution you'd like

Leverage vite tools for this

### Describe alternatives you've considered

Nop

**Comment by naorpeled** [comment]
Hey, can I be assigned to this task? :)

**Comment by shairez** [comment]
That would be awesome! Thanks @naorpeled !

Let's see if @manucorporat haven't started working on it yet
Manu, can Naor have a green light on this?

**Comment by manucorporat** [comment]
@steve8708 mentioned this: https://developer.chrome.com/blog/devtools-better-angular-debugging/

**Comment by manucorporat** [comment]
@naorpeled yeah! are you in discord? you might need some help with the qwik optimizer! happy to help

**Comment by naorpeled** [comment]
> @naorpeled yeah! are you in discord? you might need some help with the qwik optimizer! happy to help
Yeah 😎 
Alrighty, thanks!!!

Will work on it asap :)

**Comment by manucorporat** [comment]
hey @naorpeled ! what's your discord handle?

**Comment by naorpeled** [comment]
> hey @naorpeled ! what's your discord handle?

NBT#1234

**Comment by zanettin** [comment]
Hi @manucorporat 
Looks for me like this was solved in the meantime, right?

**Comment by manucorporat** [comment]
Yeah! it's solved!
