### ISSUE TITLE
Favicon re-requested when head component re-renders

### ISSUE THREAD

**Issue by adamdbradley** [BuilderIO/qwik#1254]
### Qwik Version

latest

### Operating System (or Browser)

Any

### Which component is affected?

Qwik Runtime

### Expected Behaviour

When a head component re-renders, like changing the title, the favicon.ico should not get requested again.

### Actual Behaviour

Seems like any update to the head components will cause link[href] and favicon's to request again.

**Comment by zanettin** [comment]
Hi @adamdbradley 
Just tried to reproduce this issue and i am either to dumb to achieve this or it is fixed 😆 🙈
