### ISSUE TITLE
Preview mode not working on windows

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#1296]
### Qwik Version

0.0.112

### Operating System (or Browser)

windows 11

### Node Version (if applicable)

16

### Which component is affected?

Starters / CLI

### Expected Behaviour

Preview mode should work on any operating system

### Actual Behaviour

- `npm run build.preview` generates files
- `npm run preview`  shows the following error message (in console and in browser) and the app does not start:

`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

### Additional Information

The commands were executed in the "Basic" starter app without changing anything.

Thanks

**Comment by adamdbradley** [comment]
Should be fixed in 0.0.113, thanks for opening the issue.

https://github.com/BuilderIO/qwik/pull/1298

**Comment by robisim74** [comment]
Yes, now it works. Thanks!
