### ISSUE TITLE
Library starter bugs

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#1297]
### Qwik Version

0.0.112

### Operating System (or Browser)

windows, ubuntu

### Node Version (if applicable)

16

### Which component is affected?

Starters / CLI

### Expected Behaviour

Library starter should work as before.

### Actual Behaviour

After the recent Qwik changes, the Library starter is broken:

- missing lib "WebWorker" in tsconfig (build fails)
- missing in package.json: (the whole repo ends up in the package as is with` npm pack`)
  - version
  - exports
  - files
  - main
  - module
  - types

### Additional Information

I take advantage of this issue to report other small issues of the previous versions:

Final package ended up with:
- typescript definition files for the sample app files as well
- the contents of the `public `folder

Also, since some different configuration between app and library is almost always needed, I ended up creating a different Vite file and tsconfig file:
- vite.config.ts (for app)
- ts.config.json (for app)
- vite.config.lib.ts (for library)
- ts.config.lib.json (for library)

This is because it is very bad practice to publish a package with useless files.

Greetings

**Comment by adamdbradley** [comment]
Having a different configs for app and library I think is a good idea, we'll probably try that instead. Thanks!

**Comment by manucorporat** [comment]
Thanks a lot! should be fixed in the latest release!
