### ISSUE TITLE
build.ssr failed: [commonjs--resolver] Missing "./middleware/express" export in "@builder.io/qwik-city" package

### ISSUE THREAD

**Issue by jmmon** [BuilderIO/qwik#1299]
### Qwik Version

v0.0.112 (with qwik-city v0.0.111)

### Operating System (or Browser)

Windows

### Node Version (if applicable)

16.16.0

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

Brand new qwik app, basic starter, using npm.

expected `npm run preview` to work

### Actual Behaviour

Got an error: 
```
...
dist/service-worker.js      2.13 KiB / gzip: 1.01 KiB
dist/build/q-0ea8883c.css   1.58 KiB / gzip: 0.79 KiB
dist/build/q-376e4770.js    4.03 KiB / gzip: 2.00 KiB

✓ Built client modules
✓ Built preview (ssr) modules


❌ Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: filemust be valid file:// URLs. Received protocol 'c:'
```

path to my qwik-app on my computer: `C:\Users\jmmon\Documents\VS-2019\KU\MI\Advanced Projects\dapp-project\qwik-app`

and it serves up this error on `http://127.0.0.1:4173/`

### Additional Information

adding express and then running `build` and `serve` works fine

**Comment by adamdbradley** [comment]
Should be fixed in 0.0.113, thanks for opening the issue.

https://github.com/BuilderIO/qwik/pull/1298
