### ISSUE TITLE
Tests fail for QRL functions $()

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#1302]
### Qwik Version

0.0.112

### Operating System (or Browser)

windows

### Node Version (if applicable)

16

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Tests pass as in previous versions.

### Actual Behaviour

I'm using Jest (test environment: node) to test some functions that call QRL functions $().

Tests fail with the following error:
```
    ReferenceError: document is not defined

      at emitUsedSymbol (dist-dev/tsc-out/packages/qwik/src/core/import/qrl-class.js:117:9)
```

### Additional Information

The error seems to come from the new variable `qTest `(it is `false `during test).

Thanks

**Comment by manucorporat** [comment]
Should be fixed in latest release!
