### ISSUE TITLE
[DOCS] Data Fetching

### ISSUE THREAD

**Issue by BerndWessels** [BuilderIO/qwik#1343]
**How can the documentation be improved?**
I watched a lot of Qwik presentations and read the documentation, but it is still very unclear to me how data fetching from an API fits into Qwik. Will it be server side, client side, or both, when, where and how, are there serialization issues?

Basically, an additional section in the documentation explaining how to best fetch data from any external API the Qwik way would be very helpful.

Thanks

**Comment by shairez** [comment]
@BerndWessels data fetching could be done both on the client and on the server (depending when it is running)

Take a look at `useResource$`  and `<Resource/>` I think this is what you're looking for - 

https://qwik.builder.io/docs/components/resource/

**Comment by BerndWessels** [comment]
@shairez Thanks, interesting - but what if I want the server to render everything before it gets delivered to the browser - like server fetches all the latest `products` from an API, renders everything and then delivers it to the browser?

**Comment by KenAKAFrosty** [comment]
@BerndWessels I believe `useServerMount$` is exactly what you're looking for

Very good info here as well as an interactive tutorial to play around with:
https://qwik.builder.io/tutorial/hooks/use-mount/

**Comment by shairez** [comment]
What @KenAKAFrosty said 😄
