### ISSUE TITLE
Big Qwik DX polish

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#1355]
## IDEAS

- Qwik Dev tools
- DisplayName for components
- Development source maps

**Comment by shairez** [comment]
Adding things I saw you wrote on discord - 

* Precise errors messages / indications
* JSX Debugging
* New eslint rules
* Amazing CLI

And I've got another suggestion (I mentioned in the past) -  

* Auto migration scripts (à la `ng update` or `nx migrate`) - this will prove itself useful if we'll have breaking changes / modifications before 1.0

**Comment by manucorporat** [comment]
Bad error for bath path: https://github.com/BuilderIO/qwik/issues/1402
