### ISSUE TITLE
[DOCS] docs localization ko-kr

### ISSUE THREAD

**Issue by Lutece** [BuilderIO/qwik#1357]
**How can the documentation be improved?**

it would be appreciated, if i could translate Qwik document korean.
May i start it?

**Comment by shairez** [comment]
Thanks @Lutece ! we'll greatly appreciate it

@adamdbradley is there a way to add more languages currently to the docs?

**Comment by forresst** [comment]
If I can do my small part, I would also like to do the French translation.

If you look closely, it is quite easy to duplicate the `mdx` and `md` files to translate them into another language. So the routing should allow afterwards to partition each language.

The most complex point for me is that you need a tool to translate the English texts in the `tsx` files. [qwik-speak](https://github.com/robisim74/qwik-speak) seems to be able to answer this problem, but is it mature enough? Is it the only solution? Also a solution is currently under discussion: [i18n at compile time](https://github.com/robisim74/qwik-speak/issues/9).

@robisim74 any opinion on this ?

**Comment by robisim74** [comment]
@forresst qwik-speak is an _unofficial_ project. I don't think it can be used for official Qwik documentation.

**Comment by Lutece** [comment]
@shairez Thanks a lot! :) 

Would you please let me know which repository or directory I could commence translation?

I found this one: [qwik](https://github.com/BuilderIO/qwik)/[packages](https://github.com/BuilderIO/qwik/tree/main/packages)/docs/
, tried to execute it but couldn't.

It shows error message as below.
` Cannot find module '/Users/lutece/Desktop/qwik/node_modules/@builder.io/qwik/dist/optimizer.cjs'
`

Please let me know how to solve it.
Thank you!

**Comment by Lutece** [comment]
i solve this problem. and i can start to translate this document now :) 
Thanks a lot~!

**Comment by Lutece** [comment]
@shairez 
I changed my mac machine m1 to intel chip.
this an issue with Wasm-Pack and not supporting AppleM1 chips
https://github.com/rustwasm/wasm-pack/issues/1169

**Comment by Lutece** [comment]
@shairez finally, i started to translate Qwik Document!
and i made a korean domain (qwik.kr)

if i finish to translate, i'll notify in this comment and mention you

**Comment by shairez** [comment]
Thanks a lot @Lutece ! 👏👏

I think it would be valuable to add a sub-domain / subfolder for all the translations (instead of buying a domain for each translation)

WDYT @adamdbradley ?

**Comment by f-lab-kevin** [comment]
@shairez great idea~!
Let me know when i can add the translation to the subdomain

**Comment by Lutece** [comment]
@shairez great idea~! Let me know when i can add the translation to the subdomain

**Comment by shairez** [comment]
@adamdbradley .. found this - 
https://crowdin.com/pricing#annual

looks free for public projects

**Comment by forresst** [comment]
There is currently a study to manage the localization. #1594 

For the future, this may be useful: 
- Russian:  [https://github.com/Craiqser/qwik-docs-ru](https://github.com/Craiqser/qwik-docs-ru). This is the documentation package of the qwik repository. Russian translation is done for both Qwik and QwikCity, @Craiqser synchronize it periodically.
- French:  [https://github.com/forresst/qwik-docs-fr](https://github.com/forresst/qwik-docs-fr). This is the documentation package of the qwik repository. French translation is done for Qwik, QwikCity and Tutorial. @forresst synchronize it periodically.

**Comment by kai890707** [comment]
Translation of Traditional Chinese is on its way too! 
and i made a Taiwan domain
(https://qwik.tw/)
(https://github.com/kai890707/qwik.tw)

We hope to help the QWIK Chinese community progress together!  :D

**Comment by kai890707** [comment]
Sorry , I have a question about doc index page.
I want to modify the component on the main page of the document, but I found that the html of the page is obtained by using the api and I can't modify it directly. Will this part be open for modification in the future?

**Comment by keuller** [comment]
I'm available to help to translate to Portuguese as well.

**Comment by jonsam-ng** [comment]
Is anyone preparing a translation in simplified Chinese? I would like to be involved in it.

**Comment by cunzaizhuyi** [comment]
> Is anyone preparing a translation in simplified Chinese? I would like to be involved in it.

https://github.com/cunzaizhuyi/qwik    simplified Chinese

**Comment by gioboa** [comment]
@shairez do you have any news about that?

**Comment by gioboa** [comment]
I close this issue b/c it's stale.
If we want we can continue the discussion on Discord.
