### ISSUE TITLE
QWIK WARN A unsupported value was passed to the JSX, skipping render. Value: Symbol(skip render)

### ISSUE THREAD

**Issue by Gregory-Ledray** [BuilderIO/qwik#1361]
### Qwik Version

0.9.0

### Operating System (or Browser)

Windows / Chrome

### Which component is affected?

Starters / CLI

### Expected Behaviour

I wanted to create a new component by copying an existing component.
1. Started development server with `npm start` (VSCode launch.json used to start tasks.json)
2. Navigated to src/routes/flower
3. Copied the directory and pasted as "flower2"
4. Navigated to /flower2
5. See the contents of /flower at the route /flower2

### Actual Behaviour

In step 5, I see nothing. Browser logged a console error: "Failed to load resource: the server responded with a status of 404 (Not Found)"

Terminal logged:
```
Executing task: npm run start 


> start
> vite --open --mode ssr


  VITE v3.1.1  ready in 966 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
QWIK WARN A unsupported value was passed to the JSX, skipping render. Value: Symbol(skip render)
```

### Additional Information

Workaround: Terminate the batch job and restart the development server. After doing so, navigating to /flower2 shows me the flower page.

**Comment by zanettin** [comment]
Hi @Gregory-Ledray 
Sorry for the late response 🙈  i just gave it a spin on the latest version of qwik and qwik-city and it works as expected on my end. can you confirm that?

```
pnpm create qwik@latest
-> qwik city
cd <project>
pnpm install
pnpm dev
```

- copy `flower` to `flower2`
- change url to `flower2`
