### ISSUE TITLE
Add attributes to<html>

### ISSUE THREAD

**Issue by tunailgaz** [BuilderIO/qwik#1372]
### Is your feature request related to a problem?

Sorry if feature exists, couldn't find
Some popular css frameworks such as bulma, tailwind, are using <html class> like `fixed-top` `dark` etc..
it would be nice to send editable <html> from SSR.
 

### Describe the solution you'd like

```text
./src/root.tsx
```
Maybe something like this?
```html
    <QwikCity class="dark" data-q="test">
      <head>
        <meta charSet="utf-8" data-q="test"/>
        <RouterHead />
      </head>
      <body lang="en">
        <RouterOutlet />
        <ServiceWorkerRegister />
      </body>
    </QwikCity>
```

### Describe alternatives you've considered

Add extra props to `QwikCity`

**Comment by JorgeVV** [comment]
For your specific use case, at least for tailwind, you can assign thoses classes to `body` tag.

Said that, we need to be able to set any attribute to the root `html` element. I've been using `<body lang="en">` to set the document language (and `dir='ltr'` for text's directionality when necesary) but I'm not sure how this affects SEO or auto translations.

**Comment by adamdbradley** [comment]
@JorgeVV Has a good alternative and to use `<body>` instead, which would also work for `lang`. The API to set the `<html>` attributes would not be available within the JSX at this level, since it's the highest component and doesn't have a parent. It's still possible to set the html attributes, but it's an API we're still working on so think the `<body>` tag is a good alternative for now.

**Comment by tunailgaz** [comment]
@adamdbradley thanks for the great low level information, appreciate it

**Comment by manucorporat** [comment]
There is a containerAttributes that can be passed to the `renderToStream()` too, but it's static:
```tsx
  return renderToStream(<Root />, {
    manifest,
    ...opts,
    containerAttributes: {
      lang: 'en',
    },
```

**Comment by mhevery** [comment]
https://github.com/BuilderIO/qwik/discussions/1425#discussioncomment-3766816

**Comment by mhevery** [comment]
yes, it is part of our i18n prototype
