### ISSUE TITLE
Failed to fetch dynamically imported module when accessing to the route directly

### ISSUE THREAD

**Issue by Devric** [BuilderIO/qwik#1385]
### Qwik Version

0.9.0

### Operating System (or Browser)

Mac m2, Brave / Chrome

### Which component is affected?

Qwik Runtime

### Expected Behaviour

onClick$ function to load and run the Login script

` <button onClick$={login}>Login</button>`

`function login() {
         console.log('log')
 }`
<img width="818" alt="code" src="https://user-images.githubusercontent.com/449735/191638561-a08ad495-d175-40f3-8d17-40fdb484999e.png">

### Actual Behaviour

Assume my module is under page: route/b

When access directly to a route/b, onClick$={login} will trigger the runtime error

`Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:5173/runtimeQRL`
 
<img width="782" alt="error" src="https://user-images.githubusercontent.com/449735/191638583-428df7eb-1e9e-4c6d-87e8-95fcdf7152cc.png">

### Additional Information

If i navigate from a different route i.e from route/a and click into route/b before trigger the Login button, the onClick$ works as expected

Also tried to run directly with the PREVIEW mode, and with preview mode, when navigate to the route/B page, application crashed with error: i
```

 throw new Error('Dynamic require of "' + x + '" is not supported');
        ^
Error: Dynamic require of "/inlinedQRL.js" is not supported
```
<img width="892" alt="Screen Shot 2022-09-22 at 12 20 13 pm" src="https://user-images.githubusercontent.com/449735/191644073-c4692d53-23bb-4b28-8439-1bedf5c505d8.png">

**Comment by alxndr** [comment]
I also see a 404 for `runtimeQRL`... https://jrad.today/

(Brand-new to Qwik so be gentle!)

**Comment by manucorporat** [comment]
This is one of the rules of `$`: the content needs to eb inlined:

```tsx
const login = $(() => {
  console.log('login');
});
```

Keeping this issue open, as the error should be better! do you have eslint installed?

**Comment by zanettin** [comment]
@manucorporat imo the error message looks good and is understandable:
```
10:50:32 PM [vite] Internal server error: Reference to identifier declared at the root 'foo'. It needs to be exported in order to be used inside a Qrl($) scope.
```
can we close this issue?
