### ISSUE TITLE
DocumentHead - title is not working

### ISSUE THREAD

**Issue by srinivas-dev-reddy** [BuilderIO/qwik#1389]
### Qwik Version

0.9.0

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

16.16.0

### Which component is affected?

Qwik City

### Expected Behaviour

When using DocumentHead and setting title page title should be updated to the title string

### Actual Behaviour

When using DocumentHead and setting title page is not working.

### Additional Information

`
import {
  component$,
  useClientEffect$,
  useStore,
} from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";

export default component$(() => {
  const store = useStore({
    count: 1,
    start: false,
  });

  useClientEffect$(({ track, cleanup }) => {
    track(store, "start");
    console.log("Starting clock");
    if (!store.start) return;
    const timer = setInterval(() => {
      store.count++;
    }, 400);

    cleanup(() => {
      clearInterval(timer);
    });
  });

  return (
    <div>
      <h1>Count : {store.count}</h1>
      <button
        onClick$={() => {
          store.start = true;
        }}
      >
        Start
      </button>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Welcome to Qwik",
};
`

above is the code i'm using

<img width="769" alt="Screenshot 2022-09-22 at 8 43 07 AM" src="https://user-images.githubusercontent.com/100875822/191650227-9bf6b02b-4862-48b9-b028-2cf5b5cc8acb.png">

**Comment by manucorporat** [comment]
Can you please provide a repo case? stackblitz.com link can work!

**Comment by adamdbradley** [comment]
Sorry I'm un able to reproduce this error. It may be that DocumentHead is only being used on a component, and not a qwik-city page. Closing for now, please reopen if you're still facing issues.

**Comment by d-kls** [comment]
I did run into this as well. For anyone looking at this in the future: Make sure your `RouterHead` component uses f.ex. `head.title` from the `useDocumentHead` hook.
