### ISSUE TITLE
Spread Props

### ISSUE THREAD

**Issue by anubra266** [BuilderIO/qwik#1409]
Just came across qwik
Tried this in the playground
```tsx
export const App = component$(() => {
  const props = {
    onClick$: () => alert('Hello')
  }
  return (
    <>
      <button {...props}>greet!</button>
    </>
  );
});
```
Doesn't work. How can I spread multiple attributes on an element. I'd use `v-bind` in vue since it doesn't support spread like `react` or `solid`. Is there something like that here?

**Comment by manucorporat** [comment]
I believe the problem is not really the spread but the optimizer to moving the `onClick$` from the object, i will look into it

**Comment by anubra266** [comment]
> I believe the problem is not really the spread but the optimizer to moving the `onClick$` from the object, i will look into it

Thanks @manucorporat. Got an answer on discord

<img width="950" alt="CleanShot 2022-09-23 at 13 14 04@2x" src="https://user-images.githubusercontent.com/30869823/191957786-66ac01a6-932e-4eca-9836-5f1a14fe5e35.png">
