### ISSUE TITLE
Parent component not consistently rendering children on store state changes

### ISSUE THREAD

**Issue by jackvane** [BuilderIO/qwik#1410]
### Qwik Version

0.9.0

### Operating System (or Browser)

Brave on Mac 12.5 Monterey

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Parent component (Modal) should consistently render its children (Modal content) when store state changes.

### Actual Behaviour

The first time I click to open the modal, it will display the slotted children but after closing it and reopening, it will not.

Just got started with Qwik yesterday, so maybe this is some kind of gotcha that I missed in the docs. I'm coming from react/next
<img width="833" alt="Screen Shot 2022-09-23 at 9 55 06" src="https://user-images.githubusercontent.com/101849104/191879309-69025f41-d768-4032-a201-2feeb70e169e.png">
<img width="825" alt="Screen Shot 2022-09-23 at 9 55 21" src="https://user-images.githubusercontent.com/101849104/191879313-bd2eebde-d68b-4cdf-81c2-05cd018676e8.png">

_index.tsx_
```ts
import { component$, useStore } from "@builder.io/qwik";
import { Modal, ModalStore } from "~/components/modal/Modal";

export default component$(() => {
  const store = useStore<ModalStore>({
    isOpen: false,
  });

  return (
    <div>
      <button onClick$={() => (store.isOpen = true)}>open modal</button>

      <Modal title="test-modal" store={store}>
        <div>Modal content</div>
      </Modal>
    </div>
  );
});
```

_~/components/modal/Modal.tsx_
```ts
import { component$, Slot } from "@builder.io/qwik";

export interface ModalStore {
  isOpen: boolean;
}

export interface ModalProps {
  title: string;
  store: ModalStore;
}

export const Modal = component$(({ title, store }: ModalProps) => {
  if (store.isOpen)
    return (
      <div
        className="relative z-overlay"
        aria-labelledby={title}
        role="dialog"
        aria-modal="true"
      >
        <Overlay />

        <div className="fixed inset-0 overflow-y-auto">
          <div className="flex items-end justify-center min-h-full p-4 text-center sm:items-center sm:p-0">
            <Panel>
              <button onClick$={() => (store.isOpen = false)}>
                close modal
              </button>
              <Slot />
            </Panel>
          </div>
        </div>
      </div>
    );

  return null;
});

export const Overlay = component$(() => {
  return (
    <div className="fixed inset-0 transition-opacity bg-black bg-opacity-40 backdrop-blur-sm" />
  );
});

export const Panel = component$(() => {
  return (
    <div className="relative p-8 overflow-hidden text-left transition-all transform bg-white rounded-lg shadow-xl dark:bg-slate-900 sm:my-8 sm:w-full sm:max-w-lg">
      <Slot />
    </div>
  );
});
```

### Additional Information

Uses Tailwind classes for styles

**Comment by manucorporat** [comment]
Could you please share a stackblitz? everything seems correct from the code

https://qwik.new

**Comment by jackvane** [comment]
@manucorporat 
Here you go:
https://stackblitz.com/edit/qwik-starter-4av4sk?file=src/components/modal/modal.tsx

**Comment by manucorporat** [comment]
Looking into the issue!
