### ISSUE TITLE
useClientEffect$ console.log is not printing in browser console.

### ISSUE THREAD

**Issue by srinivas-dev-reddy** [BuilderIO/qwik#1413]
### Qwik Version

0.9.0

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

16.16.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

When using useClientEffect$  i would assume that it would run in browser console as only browser needs to execute the code.

### Actual Behaviour

When using useClientEffect$ console.log is not printing in browser console.

### Additional Information

<img width="772" alt="Screenshot 2022-09-23 at 8 29 23 AM" src="https://user-images.githubusercontent.com/100875822/191884478-2d6f66ca-21a4-447d-871e-dfda6b821bfa.png">

Below is my code i am using

```tsx
## For fancy-name

import {
  component$,
  Slot,
  useClientEffect$,
} from "@builder.io/qwik";

export default component$(() => {
  console.log("Fancy Name");
  useClientEffect$(() => {
    console.log("Client effect fancy name");
  });
  return (
      <Slot />
  );
});

## For Root Route

import { component$, useClientEffect$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import AboutQwik from "~/components/about-qwik/about-qwik";
import FancyName from "~/components/fancy-name/fancy-name";

export const fancyName ="Some";

export default component$(() => {
  useClientEffect$(() => {
    console.log(fancyName);
  });
  console.log("Root route");
  return (
    <FancyName>
      <section>
        <AboutQwik />
      </section>
    </FancyName>
  );
});

export const head: DocumentHead = {
  title: "Welcome to Qwik 2",
};
```

**Comment by manucorporat** [comment]
This is technically very tricky, but I am commited to solve it, have a good idea. Problem is that <Slot/> and the components themselves do not have a DOM element, and useEffectClient() works by attaching a `qvisible` event, in your demo, there is not any element to attach it, and gets lots.

you can solve it right now by adding a `<div>`:
```tsx
  return (
  <div>
    <FancyName>
      <section>
        <AboutQwik />
      </section>
    </FancyName>
</div>
  );
```


This is not a solution, just a workaround for you.
Ideally Qwik should keep the pending events in SSR and emit it in the next available element, whenever it's in the tree

**Comment by cmbartschat** [comment]
Observing that this seems to be fixed (for my case at least) by adding `{eagerness: 'load'}`. Potentially, "invisible" components could have that behavior by default. Or maybe "load" effects should have a different hook name than "view" effects so that devs don't get get confused on this.

**Comment by meenie** [comment]
For anyone else wondering about @cmbartschat saying they needed to use `{eagerness: 'load'}` on the `useClientEffect$()` as well as adding the wrapping `<div />`, it's because either the Component was rendered off the page _or_, like me, had the browser tab occluded which means it wasn't "visible" (the default option) and wasn't firing.  That was fun lol.  So ya, if you component that has the `useClientEffect$()` is not occluded, then you don't need to use `{eagerness: 'load'}`.

![The more you know](https://media.giphy.com/media/3og0IMJcSI8p6hYQXS/giphy.gif)
