### ISSUE TITLE
No choice for quik-city on npm create

### ISSUE THREAD

**Issue by Wittner** [BuilderIO/qwik#1423]
### Qwik Version

0.9.0

### Operating System (or Browser)

Linux (Mint)

### Node Version (if applicable)

16

### Which component is affected?

Qwik City

### Expected Behaviour

I am typing the following at my terminal:

npm create qwik@latest

and expecting a choice of 'starter' which includes qwik-city

🐰 Let's create a Qwik app 🐇   v0.9.0

✔ Where would you like to create your new project? … demo

? Select a starter › (use ↓↑ arrows, hit enter)
❯   Qwik City = File based routing and MDX support
    Blank
    Library

### Actual Behaviour

🐰 Let's create a Qwik app 🐇   v0.9.0

✔ Where would you like to create your new project? … demo

? Select a starter › (use ↓↑ arrows, hit enter)
❯   Basic - Recommended for your first Qwik app
    Documentation Site
    Library

### Additional Information

![qwik_01](https://user-images.githubusercontent.com/340797/191967419-230d7c1a-24fd-47d4-bc85-b06e9913179b.png)

**Comment by manucorporat** [comment]
also the docs!

**Comment by Wittner** [comment]
Ahhh, I did wonder. That's great thanks. Now back to the tutorial. The whole qwik thing looks great :)

**Comment by Wittner** [comment]
@manucorporat. Didn't see it's inclusion by default mentioned in the docs. I did see mention of Qwik City but not that it was 'baked in'. I admit I haven't read the documentation in its entirety as I'm just 'browsing' right now but as shairez says, a mention in the install would save confusion. Thanks for your input.

**Comment by shairez** [comment]
@manucorporat other than the video on getting started, which part do you think we should update as well?
