### ISSUE TITLE
Back button does not work after refreshing the page

### ISSUE THREAD

**Issue by ChibiBlasphem** [BuilderIO/qwik#1428]
### Qwik Version

0.9.0

### Operating System (or Browser)

Brave, Chrome

### Which component is affected?

Qwik City

### Expected Behaviour

After navigating to a page on client side (with `Link`) and refreshing the page, hitting the back button should render the previous alongside the URL change

### Actual Behaviour

After navigating to a page on client side (with `Link`) and refreshing the page, hitting the back button only update the URL but does not render the previous page

### Additional Information

This issue is present in the Basic App template.

**Comment by Varixo** [comment]
probably the same issue https://github.com/BuilderIO/qwik/issues/1490
