### ISSUE TITLE
`Error: Dynamic require of "/inlinedQRL.js" is not supported` when site requested from Netlify Edge Function

### ISSUE THREAD

**Issue by philwolstenholme** [BuilderIO/qwik#1432]
### Qwik Version

Qwik: 0.9.0, Qwik City 0.0.111

### Operating System (or Browser)

Chrome, mac OS

### Which component is affected?

Qwik City

### Expected Behaviour

I see a successful deploy in Netlify and can visit my site.

### Actual Behaviour

I get an error when visiting my site and the an error in my Edge Function logs:

> This edge function has crashed
An unhandled error in the function code triggered the following message:
>
>The deployment failed while serving the request.
>Connection details
>Netlify internal ID: 01GDNNS55951CJ15AGR0JKZ73E

```
5:57:58 PM: Error: Dynamic require of "/inlinedQRL.js" is not supported
    at file:///root/netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js:4875:9
    at Object.importSymbol (file:///root/netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js:4917:22)
    at resolve (file:///root/netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js:2481:37)
    at AsyncFunction.resolveLazy [as $resolveLazy$] (file:///root/netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js:2485:53)
    at _useStyles (file:///root/netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js:3190:26)
    at useStylesScopedQrl (file:///root/netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js:3166:3)
    at file:///root/netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js:3201:3
    at invoke (file:///root/netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js:70:42)
    at file:///root/netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js:2497:59
    at then (file:///root/netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js:28:79)
```

### Additional Information

The repo is here: https://github.com/philwolstenholme/lasttramfrom-qwik

Site is here: https://silver-griffin-03ccbb.netlify.app/

<details>
<summary>Netlify build log</summary>

5:57:24 PM: Build ready to start
5:57:26 PM: build-image version: d7b3dbfb0846505993c9a131894d1858074c90b4 (focal)
5:57:26 PM: build-image tag: v4.10.1
5:57:26 PM: buildbot version: 1c362ef848ac5e35535bdb572ebca893db28c8a0
5:57:26 PM: Building without cache
5:57:26 PM: Starting to prepare the repo for build
5:57:26 PM: No cached dependencies found. Cloning fresh repo
5:57:26 PM: git clone https://github.com/philwolstenholme/lasttramfrom-qwik
5:57:26 PM: Preparing Git Reference refs/heads/main
5:57:27 PM: Parsing package.json dependencies
5:57:28 PM: Starting build script
5:57:28 PM: Installing dependencies
5:57:28 PM: Python version set to 2.7
5:57:28 PM: Attempting node version '16' from .node-version
5:57:28 PM: Downloading and installing node v16.17.1...
5:57:28 PM: Downloading https://nodejs.org/dist/v16.17.1/node-v16.17.1-linux-x64.tar.xz...
5:57:29 PM: Computing checksum with sha256sum
5:57:29 PM: Checksums matched!
5:57:30 PM: Now using node v16.17.1 (npm v8.15.0)
5:57:31 PM: Started restoring cached build plugins
5:57:31 PM: Finished restoring cached build plugins
5:57:31 PM: Attempting ruby version 2.7.2, read from environment
5:57:31 PM: Using ruby version 2.7.2
5:57:31 PM: Using PHP version 8.0
5:57:32 PM: No npm workspaces detected
5:57:32 PM: Started restoring cached node modules
5:57:32 PM: Finished restoring cached node modules
5:57:32 PM: Installing NPM modules using NPM version 8.15.0
5:57:32 PM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
5:57:32 PM: npm WARN config location in the cache, and they are managed by
5:57:32 PM: npm WARN config     [`cacache`](http://npm.im/cacache).
5:57:32 PM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
5:57:32 PM: npm WARN config location in the cache, and they are managed by
5:57:32 PM: npm WARN config     [`cacache`](http://npm.im/cacache).
5:57:35 PM: added 283 packages, and audited 284 packages in 3s
5:57:35 PM: 125 packages are looking for funding
5:57:35 PM:   run `npm fund` for details
5:57:35 PM: found 0 vulnerabilities
5:57:35 PM: NPM modules installed
5:57:36 PM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
5:57:36 PM: npm WARN config location in the cache, and they are managed by
5:57:36 PM: npm WARN config     [`cacache`](http://npm.im/cacache).
5:57:36 PM: Started restoring cached go cache
5:57:36 PM: Finished restoring cached go cache
5:57:36 PM: Installing Go version 1.17 (requested 1.17)
5:57:41 PM: unset GOOS;
5:57:41 PM: unset GOARCH;
5:57:41 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
5:57:41 PM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
5:57:41 PM: go version >&2;
5:57:41 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
5:57:41 PM: go version go1.17 linux/amd64
5:57:41 PM: Installing missing commands
5:57:41 PM: Verify run directory
5:57:42 PM: ​
5:57:42 PM: ────────────────────────────────────────────────────────────────
5:57:42 PM:   Netlify Build                                                 
5:57:42 PM: ────────────────────────────────────────────────────────────────
5:57:42 PM: ​
5:57:42 PM: ❯ Version
5:57:42 PM:   @netlify/build 27.18.4
5:57:42 PM: ​
5:57:42 PM: ❯ Flags
5:57:42 PM:   baseRelDir: true
5:57:42 PM:   buildId: 632de574b515e82dd3a32224
5:57:42 PM:   deployId: 632de574b515e82dd3a32226
5:57:42 PM: ​
5:57:42 PM: ❯ Current directory
5:57:42 PM:   /opt/build/repo
5:57:42 PM: ​
5:57:42 PM: ❯ Config file
5:57:42 PM:   /opt/build/repo/netlify.toml
5:57:42 PM: ​
5:57:42 PM: ❯ Context
5:57:42 PM:   production
5:57:42 PM: ​
5:57:42 PM: ────────────────────────────────────────────────────────────────
5:57:42 PM:   1. build.command from netlify.toml                            
5:57:42 PM: ────────────────────────────────────────────────────────────────
5:57:42 PM: ​
5:57:42 PM: $ npm run build
5:57:43 PM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
5:57:43 PM: npm WARN config location in the cache, and they are managed by
5:57:43 PM: npm WARN config     [`cacache`](http://npm.im/cacache).
5:57:43 PM: > build
5:57:43 PM: > qwik build
5:57:43 PM: tsc --incremental --noEmit
5:57:43 PM: vite build
5:57:43 PM: vite build --ssr src/entry.netlify-edge.tsx
5:57:44 PM: vite v3.1.1 building for production...
5:57:44 PM: transforming...
5:57:45 PM: ✓ 50 modules transformed.
5:57:45 PM: rendering chunks...
5:57:45 PM: dist/q-manifest.json        11.59 KiB
5:57:45 PM: dist/build/q-18dadcff.js    0.06 KiB / gzip: 0.07 KiB
5:57:45 PM: dist/build/q-66fccbab.js    0.26 KiB / gzip: 0.22 KiB
5:57:45 PM: dist/build/q-df84ea43.js    0.19 KiB / gzip: 0.17 KiB
5:57:45 PM: dist/build/q-7584bb0c.js    4.80 KiB / gzip: 2.31 KiB
5:57:45 PM: dist/build/q-78a9a428.js    0.77 KiB / gzip: 0.30 KiB
5:57:45 PM: dist/build/q-9cfd76e0.js    1.49 KiB / gzip: 0.84 KiB
5:57:45 PM: dist/build/q-a7d11805.js    0.83 KiB / gzip: 0.49 KiB
5:57:45 PM: dist/build/q-b169bcd0.js    0.89 KiB / gzip: 0.47 KiB
5:57:45 PM: dist/build/q-a3f59757.js    0.20 KiB / gzip: 0.16 KiB
5:57:45 PM: dist/build/q-d9c9934f.js    0.30 KiB / gzip: 0.22 KiB
5:57:45 PM: dist/build/q-06c44d87.js    0.25 KiB / gzip: 0.18 KiB
5:57:45 PM: dist/build/q-bc557db0.js    0.26 KiB / gzip: 0.20 KiB
5:57:45 PM: dist/build/q-ed037dc6.js    0.11 KiB / gzip: 0.11 KiB
5:57:45 PM: dist/build/q-faf6ade2.js    1.16 KiB / gzip: 0.55 KiB
5:57:45 PM: dist/build/q-6bdd8e58.js    0.87 KiB / gzip: 0.46 KiB
5:57:45 PM: dist/build/q-5700c3ab.js    0.42 KiB / gzip: 0.29 KiB
5:57:45 PM: dist/build/q-cc7cabba.js    0.41 KiB / gzip: 0.28 KiB
5:57:45 PM: dist/build/q-6fea75db.js    35.76 KiB / gzip: 14.74 KiB
5:57:45 PM: dist/build/q-0ed7aa64.js    5.17 KiB / gzip: 1.56 KiB
5:57:45 PM: dist/service-worker.js      2.13 KiB / gzip: 1.01 KiB
5:57:45 PM: dist/build/q-83b02ad9.js    0.38 KiB / gzip: 0.29 KiB
5:57:45 PM: dist/build/q-fecf0061.css   0.37 KiB / gzip: 0.23 KiB
5:57:45 PM: ✓ Built client modules
5:57:46 PM: ✓ Built server (ssr) modules
5:57:46 PM: ✓ Type checked
5:57:46 PM: ​
5:57:46 PM: (build.command completed in 3.9s)
5:57:46 PM: ​
5:57:46 PM: ────────────────────────────────────────────────────────────────
5:57:46 PM:   2. Edge Functions bundling                                    
5:57:46 PM: ────────────────────────────────────────────────────────────────
5:57:46 PM: ​
5:57:46 PM: Packaging Edge Functions from netlify/edge-functions directory:
5:57:46 PM:  - entry.netlify-edge
5:57:51 PM: ​
5:57:51 PM: (Edge Functions bundling completed in 4.3s)
5:57:51 PM: ​
5:57:51 PM: ────────────────────────────────────────────────────────────────
5:57:51 PM:   3. Deploy site                                                
5:57:51 PM: ────────────────────────────────────────────────────────────────
5:57:51 PM: ​
5:57:51 PM: Starting to deploy site from 'dist'
5:57:51 PM: Creating deploy tree 
5:57:51 PM: Creating deploy upload records
5:57:52 PM: 0 new files to upload
5:57:52 PM: 0 new functions to upload
5:57:52 PM: Site deploy was successfully initiated
5:57:52 PM: ​
5:57:52 PM: (Deploy site completed in 1.3s)
5:57:52 PM: ​
5:57:52 PM: ────────────────────────────────────────────────────────────────
5:57:52 PM:   Netlify Build Complete                                        
5:57:52 PM: ────────────────────────────────────────────────────────────────
5:57:52 PM: ​
5:57:52 PM: (Netlify Build completed in 9.6s)
5:57:52 PM: Starting post processing
5:57:52 PM: Post processing - HTML
5:57:52 PM: Caching artifacts
5:57:52 PM: Started saving node modules
5:57:52 PM: Finished saving node modules
5:57:52 PM: Started saving build plugins
5:57:52 PM: Finished saving build plugins
5:57:52 PM: Started saving pip cache
5:57:52 PM: Finished saving pip cache
5:57:52 PM: Started saving emacs cask dependencies
5:57:52 PM: Post processing - header rules
5:57:52 PM: Finished saving emacs cask dependencies
5:57:52 PM: Started saving maven dependencies
5:57:52 PM: Finished saving maven dependencies
5:57:52 PM: Started saving boot dependencies
5:57:52 PM: Finished saving boot dependencies
5:57:52 PM: Started saving rust rustup cache
5:57:52 PM: Finished saving rust rustup cache
5:57:52 PM: Started saving go dependencies
5:57:52 PM: Finished saving go dependencies
5:57:52 PM: Post processing - redirect rules
5:57:53 PM: Post processing done
5:57:54 PM: Build script success
5:57:55 PM: Uploading Cache of size 172.4MB
5:57:56 PM: Site is live ✨
5:57:56 PM: Finished processing build request in 30.457880026s
</details>

**Comment by manucorporat** [comment]
is there a repo/stackblitz i can take a look?

**Comment by philwolstenholme** [comment]
@manucorporat ah sorry, I messed up the formatting so the repo link got a bit buried. 

The repo is here: https://github.com/philwolstenholme/lasttramfrom-qwik

Site is here: https://silver-griffin-03ccbb.netlify.app/

**Comment by lfroes** [comment]
I am having the same issue, i follow the docs but when i try to run `node server/entry.static.js` i get the following:

```Generated: 1 page
Duration: 198.7 ms
Average: 198.7 ms per page

worker error: Error: Dynamic require of "/inlinedQRL.js" is not supported
````

**Node Version**: 16.17.0

**Comment by manucorporat** [comment]
This should be fixed in the latest release, we went through a big refactor of the build process!
