### ISSUE TITLE
useServerMount$ does not work with Link

### ISSUE THREAD

**Issue by Numnumberry** [BuilderIO/qwik#1449]
### Qwik Version

0.9.0

### Operating System (or Browser)

Chrome on Linux Mint

### Node Version (if applicable)

16.17.0

### Which component is affected?

Qwik City

### Expected Behaviour

When Link'ing to a route that has a useServerMount$ defined it will either
- execute useServerMount$ if not yet loaded into the browser
- ignore useServerMount$ if already in the browser

### Actual Behaviour

![qwik_error](https://user-images.githubusercontent.com/22666749/192115096-57b312c2-2bbb-4494-a913-0257954f0949.png)

An error occurs from the debugger saying
"Code(22): Components using useServerMount() can only be mounted in the server, if you need your component to be mounted in the client, use "useMount$()" instead"

### Additional Information

[https://github.com/Numnumberry/qwik-link](url)

Simply click the button to go to the flower page to replicate.

**Comment by Numnumberry** [comment]
possibly related to [https://github.com/BuilderIO/qwik/issues/1476](https://github.com/BuilderIO/qwik/issues/1476)

**Comment by manucorporat** [comment]
fixed in latest!
