### ISSUE TITLE
[BUG]: Types - Async components do go against `component$` type signature

### ISSUE THREAD

**Issue by wtho** [BuilderIO/qwik#1456]
### Qwik Version

0.9.0

### Operating System (or Browser)

Firefox 105.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

The code should not show any errors.

### Actual Behaviour

This component is showing Type errors:
```ts
import { component$ } from '@builder.io/qwik';

export const App = component$(async () => {
  return <p>Hello Qwik</p>;
});
```
```
Argument of type '() => Promise<JSX_2.Element>' is not assignable to parameter of type 'OnRenderFn<{}>'.
  Type 'Promise<Element>' is missing the following properties from type 'JSXNode<any>': type, props, key(2345)
```
See [Playground](https://qwik.builder.io/playground#version=0.9.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KGFzeW5jJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDcCUzRUhlbGxvJTIwUXdpayUzQyUyRnAlM0UlM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwQXBwJTIwJTdEJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NodG1sJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

### Additional Information

The return type of the `onMount: OnRenderFn<PROPS>` is `JSXNode<any> ` and does not have an Promise-wrapped equivalent. This is why TypeScript cannot allow the component to be `async`.

**Comment by manucorporat** [comment]
This is expected.

Returning a promise is not allowed. Not because the render can not work, but because it would affect dependency tracking. you can instead pass promises to the JSX!

```tsx
import { component$ } from '@builder.io/qwik';

export const App = component$(async () => {
  const promise = Promise.resolve('Hello Qwik');
  return <p>{promise}</p>;
});
```

**Comment by wtho** [comment]
@manucorporat 
I see, should we correct the docs then? The docs were the reason why I assumed `async`/`await` was possible.

https://github.com/BuilderIO/qwik/blob/94620a3263f93fdc860d9f3a902f9e5f02d88413/packages/docs/src/routes/docs/components/overview/index.mdx?plain=1#L23-L24
