### ISSUE TITLE
adding `useRoutingData` to Qwik City

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#1458]
### Is your feature request related to a problem?

I would like to add a list of recent blog posts to my Qwik blog

### Describe the solution you'd like

I would like to have something like this:

```ts
const routingData = useRoutingData();

routingData.routes.map(route => route.metadata.title);
```

Or even better
```ts
const last6BlogPosts = useRoutingData({
	filter(route => route.metadata.type === 'post'),
	sort((prevRoute, currentRoute) => {
		 // some soring logic based on prevRoute.metadata.date etc
	})
	page: 1, 
	limit: 6
});

routingData.routes.map(route => route.metadata.title);
```

### Describe alternatives you've considered

Develop a "blog plugin" to Qwik City

### Additional context

Not sure if this should be a built-in feature or a blog plugin

I think it'll be valuable to have access to additional metadata of other pages or at least all the possible routes to generate dynamic lists

**Comment by manucorporat** [comment]
So... some member of the community is working on some amazing APIs for content, not sure how this conflicts with that

**Comment by nnelgxorz** [comment]
This community member sounds pretty cool. Handsome, too!

Both of these are handled in my code. Just with different implementations.

**Comment by shairez** [comment]
Cool, so closing in favor of handsomeness 😘😉

Thanks @nnelgxorz ! you rock!

**Comment by josantana** [comment]
> This community member sounds pretty cool. Handsome, too!
> 
> Both of these are handled in my code. Just with different implementations.

@nnelgxorz It will be possible to add new routes and redirects programmatically (as can be done within Next.js config)? I would love a way to do so, besides the folder structure routing.

**Comment by nnelgxorz** [comment]
Hey @josantana! Nothing I'm working on makes any changes to routing. My contribution will allow you to move your content out of your routes and make it easier to work with collections of content.

I think modifying routes programmatically would be a different issue. Maybe you could open an issue here with your use case and we can figure something out.

**Comment by josantana** [comment]
> Hey @josantana! Nothing I'm working on makes any changes to routing. My contribution will allow you to move your content out of your routes and make it easier to work with collections of content.
> 
> I think modifying routes programmatically would be a different issue. Maybe you could open an issue here with your use case and we can figure something out.

Thanks for your reply @nnelgxorz. I've openned a new issue (#1518). Hope it to be considered. :)

**Comment by Hunam6** [comment]
@manucorporat @nnelgxorz What's the "community work" you're referring to? I can't find something that could replace @shairez's proposal 🤔
