### ISSUE TITLE
Props are immutable by default error using Link with dynamic class

### ISSUE THREAD

**Issue by corydeppen** [BuilderIO/qwik#1462]
### Qwik Version

0.9.0

### Operating System (or Browser)

Brave v1.43.93 (Chromium 105.0.5195.127)

### Node Version (if applicable)

16.15.0

### Which component is affected?

Qwik City

### Expected Behaviour

A `Link` component with a `class` that's set dynamically should render a link without throwing an error.

### Actual Behaviour

The following error is displayed in the browser console after clicking a link rendered by the `Link` component:

```
Code(19): Props are immutable by default. If you need to change a value of a passed in prop, please wrap the prop with "mutable()" <Link_component_mYsiJcA4IBc class={mutable(...)}> 
 - Component: Link_component_mYsiJcA4IBc 
 - Prop: class 
 - Old value: {active: false} 
 - New value: {active: true} Error: Code(19): Props are immutable by default.
```

This can be seen in the [reproduction](https://stackblitz.com/edit/qwik-link-repro?file=src/components/header/header.tsx).

**Comment by corydeppen** [comment]
Sorry, my mistake. I didn't realize I had another case where I used `Link` without wrapping a prop with `mutable`. I am curious to understand why the wrapping is necessary, though.

**Comment by wtho** [comment]
It is kind of not necessary anymore. It was necessary until Manu removed it:
https://github.com/BuilderIO/qwik/pull/1323

But that was 2 days after the current version 0.9.0 got released, which is why it's not documented anymore, but still required when you use qwik.

As soon as a new version will be released, you can drop `mutable` everywhere.

**Comment by manucorporat** [comment]
Exactly! it's because props was an area of too much dynamism, not allowing qwik to understand when components are static or not, we found another way that requires no extra work by developers!
