### ISSUE TITLE
run SSG got Invalid module "@qwik-city-plan"

### ISSUE THREAD

**Issue by psaren** [BuilderIO/qwik#1464]
### Qwik Version

0.0.108

### Operating System (or Browser)

mac

### Node Version (if applicable)

v16.16.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

I was flow this document  https://qwik.builder.io/qwikcity/static-site-generation/static-site-config  
 SSG is not work as expected

### Actual Behaviour

SSG don't work.

### Additional Information

node server/entry.static
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "@qwik-city-plan" is not a valid package name imported from /Users/mymac/Workspace/github/qwik-app/node_modules/@builder.io/qwik-city/static/node/index.mjs
    at new NodeError (node:internal/errors:372:5)
    at parsePackageName (node:internal/modules/esm/resolve:881:11)
    at packageResolve (node:internal/modules/esm/resolve:902:5)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}

**Comment by wtho** [comment]
The following works for me
**Note - I'm using the current version v0.9.0**, but SSG should be the same in v0.0.108
```
npm init qwik@latest
# select ./qwik-app
# > Basic
cd qwik-app
npm install
```
Then:
* Add `src/entry.static.tsx`
  ```tsx
  import { qwikCityGenerate } from '@builder.io/qwik-city/static/node';
  import render from './entry.ssr';
  import { fileURLToPath } from 'url';
  import { join } from 'path';
  
  qwikCityGenerate(render, {
    origin: 'https://qwik.builder.io',
    outDir: join(fileURLToPath(import.meta.url), '..', '..', 'dist'),
  });
  ```
* Modify `package.json`
  ```diff
     "build.preview": "vite build --ssr src/entry.preview.tsx",
  +  "build.ssg": "vite build --ssr src/entry.static.tsx",
     "build.types": "tsc --incremental --noEmit",
  ```

Finally
```bash
# build qwik app
npm run build
# build code generator
npm run build.ssg 
# run generator
node server/entry/static.js
```

Now e. g. `dist/index.html` is generated.

Can you give more details on which commands you ran in which order?

**Comment by psaren** [comment]
src/entry.static.tsx
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/18643034/192453752-45effee2-8e5e-442b-8f35-bfefb8f1ed68.png">
scripts
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/18643034/192453865-22868c9c-32e9-4ee7-a5d1-e559061eb615.png">
dependencies
<img width="658" alt="image" src="https://user-images.githubusercontent.com/18643034/192455045-b2c03912-a8b4-496b-89c7-05d539ba26d5.png">

**Comment by psaren** [comment]
I following the docs and append `&& npm run build.ssg` to `build` scripts.
I ran `npm run build` but dist/index.html is not generated.

**Comment by wtho** [comment]
Hmm, I tried again with v0.0.108, but I still cannot recreate your problem.
Can you share your `vite.config.ts`?

**Comment by psaren** [comment]
I  didn't change the `vite.config.ts`


I had push my project to codesandbox in https://codesandbox.io/s/nut2wf

Steps to reproduce：

1. reopen a terminal
2. run `yarn build`
3. run `node server/entry.static.js`

```
sandbox@sse-sandbox-nut2wf:/sandbox$ yarn build
yarn run v1.22.19
$ npm run typecheck && npm run build.client && npm run build.ssr && npm run build.ssg
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1664330833351-0.5800524214843212/node but npm is using /home/sandbox/.nvm/versions/node/v14.19.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> qwik-app@ typecheck /sandbox
> tsc --incremental --noEmit

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1664330833351-0.5800524214843212/node but npm is using /home/sandbox/.nvm/versions/node/v14.19.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> qwik-app@ build.client /sandbox
> vite build

vite v3.0.9 building for production...
✓ 12 modules transformed.
dist/q-manifest.json        2.51 KiB
dist/build/q-8a73667a.js    0.06 KiB / gzip: 0.07 KiB
dist/build/q-7e02d57b.js    1.87 KiB / gzip: 1.00 KiB
dist/build/q-26e92aaa.js    0.32 KiB / gzip: 0.27 KiB
dist/build/q-c9b6bbec.js    30.97 KiB / gzip: 12.90 KiB
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1664330833351-0.5800524214843212/node but npm is using /home/sandbox/.nvm/versions/node/v14.19.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> qwik-app@ build.ssr /sandbox
> vite build --ssr src/entry.express.tsx

vite v3.0.9 building SSR bundle for production...
✓ 7 modules transformed.
server/entry.express.js   6.96 KiB
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1664330833351-0.5800524214843212/node but npm is using /home/sandbox/.nvm/versions/node/v14.19.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> qwik-app@ build.ssg /sandbox
> vite build --ssr src/entry.static.tsx

vite v3.0.9 building SSR bundle for production...
✓ 7 modules transformed.
server/entry.static.js   6.57 KiB
Done in 13.49s.
sandbox@sse-sandbox-nut2wf:/sandbox$ node server/entry.static.js
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "@qwik-city-plan" is not a valid package name imported from /sandbox/node_modules/@builder.io/qwik-city/static/node/index.mjs
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:683:11)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}
```

**Comment by manucorporat** [comment]
This should be fixed if you start with a brand new starter!
