### ISSUE TITLE
Do not include default twitter meta tags in RouterHead

### ISSUE THREAD

**Issue by Morishiri** [BuilderIO/qwik#1473]
### Qwik Version

v0.9.0

### Operating System (or Browser)

N/A

### Which component is affected?

Qwik React

### Expected Behaviour

I think user should have a choice to provide this values and that it's not by default poiting to Qwik.

### Actual Behaviour

By default the following is included in `head` when using `RouterHead`:

      <meta property="og:site_name" content="Qwik" />
      <meta name="twitter:site" content="@QwikDev" />
      <meta name="twitter:title" content="Qwik" />

**Comment by manucorporat** [comment]
Makes sense, can you provide a PR?

**Comment by manucorporat** [comment]
Should be fixed in `0.11.0`!
