### ISSUE TITLE
[DOCS] solution for projection -> fallback is missing

### ISSUE THREAD

**Issue by hoersamu** [BuilderIO/qwik#1481]
The solution for projection -> fallback is the same as the problem:
[problem](https://github.com/BuilderIO/qwik/blob/3294cb95c1d079a174f80f3e23d6e9c7118a147b/packages/docs/src/routes/tutorial/projection/fallback/problem/app.tsx)
[solution](https://github.com/BuilderIO/qwik/blob/3294cb95c1d079a174f80f3e23d6e9c7118a147b/packages/docs/src/routes/tutorial/projection/fallback/solution/app.tsx)

**Comment by wmertens** [comment]
fallback seems to have been removed in https://github.com/BuilderIO/qwik/commit/3e18804db2d7937db4576023bfba594e5d6e925d#diff-f6d62b6eba45cc2846bd3c7504bc065877abc0caf5bfba427313abe491141e45

**Comment by forresst** [comment]
While waiting for a better solution, I have updated the tutorial #1817
