### ISSUE TITLE
[DOCS] Readme media should link to external resource to reflect in npmjs

### ISSUE THREAD

**Issue by ayoayco** [BuilderIO/qwik#1485]
**How can the documentation be improved?**
[npm](https://www.npmjs.com/package/@builder.io/qwik) does not show the media because it is not included in the package.json "files" array.

We can link this to an external resource, I'm willing to create a PR if you think it's a good idea. 😊

<img width="1523" alt="Screen Shot 2022-09-27 at 12 19 49 PM" src="https://user-images.githubusercontent.com/4262489/192500927-4eecb4fa-5031-43e1-9a31-f9a5b7d07d58.png">

**Comment by wtho** [comment]
@ayoayco could you also update the README image to the new logo?
![image](https://user-images.githubusercontent.com/20015207/192503101-6e7d305c-50a0-4765-aae4-99e14e8d09b0.png)

**Comment by ayoayco** [comment]
Sounds good, I'll check where this new logo image is

**Comment by wtho** [comment]
It's on the website as svg, you might have to create a png version of it

**Comment by ayoayco** [comment]
Updated PR #1486 to include the updated logo
