### ISSUE TITLE
`basePathname` and static generation not works

### ISSUE THREAD

**Issue by e-jigsaw** [BuilderIO/qwik#1488]
### Qwik Version

0.9.0

### Operating System (or Browser)

macOS 12.5.1/ Chrome 105

### Node Version (if applicable)

16.17.0

### Which component is affected?

Qwik City

### Expected Behaviour

I want to generate whole static files in directory which I set `basePathname`

### Actual Behaviour

I've tried to use static generation for GitHub Pages. I set `origin: 'https://{name}.github.io'` in `src/entry.static.tsx` and `qwikCity({basePathname: '/{repo-name}/'})` in `vite.config.ts`. So then I `run npm run build && npm run ssg` but no output any html file in dist dir. Just qwikCity() is works fine.

### Additional Information

https://discordapp.com/channels/842438759945601056/991805589623668758/1023557072312356904

**Comment by Matb85** [comment]
does not work for me as well :-(

**Comment by JeanMeche** [comment]
I'm still see this issue on 0.11.0

Thanks for the work though, keep it going 👍

**Comment by e-jigsaw** [comment]
hmm... I updated to qwik@0.12.0, qwik-city@0.0.118 and rewrite vite.config.ts, package.json but still stuck same probrem.

**Comment by JeanMeche** [comment]
@e-jigsaw He's using the future, it's not fixed yet.

**Comment by e-jigsaw** [comment]
oh sorry

**Comment by JeanMeche** [comment]
@adamdbradley This needs to be reopen. 

I'm still getting "Failed to fetch dynamically imported module: https://jeanmeche.github.io/build/q-9201ed70.js" 

The basePathname isn't used hovering the button for example : https://jeanmeche.github.io/qwik-app/

**Comment by thomaspeissl** [comment]
@JeanMeche  I guess you should reopen a new issue.
This one dealt with SSG not really working at all and your problem is about hosting the website in a subfolder.
