### ISSUE TITLE
BUG: Alignment and Padding issue on the main page of qwik.builder.io

### ISSUE THREAD

**Issue by Vasudevatirupathinaidu** [BuilderIO/qwik#1495]
Hello,
For devices like iPad Air and iPad Mini, we are facing padding and Alignment issues for the below-mentioned sections.

# Issue 1:
It's really good if we can add padding in b/w the lines.
![image](https://user-images.githubusercontent.com/33352031/192661680-5d3e653a-cfad-479d-b602-eb27d49726f5.png)

# Issue 2:
I guess in the below-mentioned issue the tailwind margin utility "mx-auto" was missing for that section element.
![image](https://user-images.githubusercontent.com/33352031/192662411-1967f6a3-4cd7-4751-bd43-a4c3b97ffdba.png)

**Comment by manucorporat** [comment]
Should be fixed already!
