### ISSUE TITLE
Examples don't load due to cert error from jsdelivr

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#1509]
### Qwik Version

web

### Operating System (or Browser)

chrome

### Which component is affected?

Qwik Runtime

### Expected Behaviour

When I go to https://qwik.builder.io/examples/introduction/hello-world/ it should show an editor 

### Actual Behaviour

but I see a loading error in my log for https://data.jsdelivr.com/v1/package/npm/@builder.io/qwik

The certificate they use is invalid.

**Comment by jimaek** [comment]
Can you please open the API and send the certificate you see? https://dl.dropboxusercontent.com/s/ezcj0nvtbhohq9t/chrome_2022-09-29_11-02-22.png

**Comment by wmertens** [comment]
Looks like it was a transient error, now it loads fine. The certificate was a generic one for (presumably) their cdn.

I suppose the lesson learnt here is that it's safer to serve your own js?

Closing since it's no longer an issue :)
