### ISSUE TITLE
The behaviour of `component$` is different for different syntax

### ISSUE THREAD

**Issue by AbhayVAshokan** [BuilderIO/qwik#1511]
### Qwik Version

v0.9.0

### Operating System (or Browser)

Chrome: Version 105.0.5195.125 (Official Build) (arm64)
macOS Monterey: v12.6

### Node Version (if applicable)

v16.5.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

The following two code snippets are virtually the same wrt. JavaScript. 

**Snippet 1**: Works as expected and renders "Hello World"
```jsx
import { component$ } from "@builder.io/qwik";

const HelloWorld = component$(() => {
  return <h1>Hello World</h1>;
});

export default HelloWorld;
```

**Snippet 2**: Throws the error shown in the below screenshot. Expected to have the same behaviour as above.
```jsx
import { component$ } from "@builder.io/qwik";

const HelloWorld = () => {
  return <h1>Hello World</h1>;
};

export default component$(HelloWorld);
```

### Actual Behaviour

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/35297280/193015502-00fa679e-f443-4209-a149-5cf1dd2237d3.png">

**Comment by manucorporat** [comment]
Not a bug, this applies to the rules of the `$`, this docs explain it:
https://qwik.builder.io/docs/advanced/optimizer/#the-meaning-of-
