### ISSUE TITLE
Add new routes and redirects programmatically

### ISSUE THREAD

**Issue by josantana** [BuilderIO/qwik#1518]
### Is your feature request related to a problem?

I'm aware QwikCity is focused on directory routing but it would be so nice if it also offers some kind of method to enable us to add new routes and redirects programmatically.

Besides the directory-based routes, I need to map a list of custom routes I'll receive from the server pointing which component should be rendered when each route is requested.

### Describe the solution you'd like

I can imagine its usage like...

```jsx
import { extendRoutes, extendRedirects } from '@builder.io/qwik-city';

extendRoutes(routes) {
  routes.push({
    path: '/some/custom/route',
    component: '~/routes/generic-route/index.tsx',
  });
}

extendRedirects(redirects) {
  redirects.push({
    from: '/old-route',
    to: '/new-route',
    permanent: true, // translated to 307 or 308
  });
}
```

...before `QwikCity` is initiated/rendered. Or something like the following, inside Vite's config:

```jsx
import { qwikCity } from '@builder.io/qwik-city/vite';
export default defineConfig(() => {
  const routeExtensions = [
    {
      path: '/some/custom/route',
      component: '~/routes/generic-route/index.tsx',
  });
  const redirectExtensions = [
    {
      from: '/old-route',
      to: '/new-route',
      permanent: true,  // translated to 307 or 308
  });
  return {
    plugins: [qwikCity({ routeExtensions, redirectExtensions }), qwikVite(), tsconfigPaths()],
  };
});
```

### Describe alternatives you've considered

I think it should be a built-in feature but a (quick and dirty) alternative I've considered was to use a generic dynamic route (aiming at least 3 levels, eg. "/:one/:two/:three"), send the data that I got from the path (delivered by `useLocation`) to the server, and based on the response, determine which component should be rendered for that specific route. Not elegant at all, I know, but it could get the job done today. A catch-all route could handle this better, but still, probably not the perfect solution.

### Additional context

Next.js tends to resolve redirects (at least) on its [config file](https://nextjs.org/docs/api-reference/next.config.js/redirects). The [extendRoutes solution](https://nuxtjs.org/pt/docs/configuration-glossary/configuration-router/) proposed above was deeply inspired by Nuxt.js.

**Comment by manucorporat** [comment]
This is already possible using the new plugin API, you can add a new `plugin.ts` file at the root of `src/routes/` and intercept any request, allowing you federate other routers!

**Comment by shairez** [comment]
@manucorporat is that documented anywhere?

if not, I'll open an issue about it
