### ISSUE TITLE
[DOCS] useStyles SSR inaccuracy?

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#1520]
I'm reading the tutorial for styles and following along in the example DOM and I see that (as I would expect) components that use `useStyles` emit their style just in front of their DOM node.

However, in [the text](https://qwik.builder.io/tutorial/style/styles/#:~:text=The%20component%20is%20rendered%20on%20the%20server%20and%20the%20styles%20are%20inserted%20into%20%3Chead%3E%20as%20part%20of%20the%20SSR.) it states that SSR puts the styles in head. This is incorrect, right?

It's only when toggling the Child component, and inserting the Child's style into HEAD, that the Sibling's style also gets moved into HEAD.

**Comment by lightersss** [comment]
Excuse me,Do you how to add style in ssr process?
like this
![image](https://user-images.githubusercontent.com/30550670/201302951-df9c3704-7746-472c-8293-8a71c939955b.png)

**Comment by wmertens** [comment]
@lightersss See https://qwik.builder.io/docs/components/styles/

**Comment by lightersss** [comment]
> @lightersss See https://qwik.builder.io/docs/components/styles/

should I use this https://qwik.builder.io/docs/components/styles/#inline-critical-styles?But it seems I can't import css file this way. And `import "./global.css?inline";`  doesn't work.

**Comment by lightersss** [comment]
> @lightersss See https://qwik.builder.io/docs/components/styles/

Oh, It just worked with `useStyles$`.Thank you so much for your help!!😘
