### ISSUE TITLE
useEndpoint onGet stays on "onPending" step

### ISSUE THREAD

**Issue by CherryNerd** [BuilderIO/qwik#1526]
### Qwik Version

0.9.0

### Operating System (or Browser)

MacOS/Chrome

### Node Version (if applicable)

16.17.0

### Which component is affected?

Qwik City

### Expected Behaviour

Promise should be resolved and "onResolved" should be rendered

### Actual Behaviour

Resource component stays on "onPending" indefinitely

### Additional Information

First tried to implement an actual API call (which works perfectly for routing purposes).
When that didn't work, I copied the code from the [documentation](https://qwik.builder.io/qwikcity/routing/data/), that also didn't work.

**Comment by zanettin** [comment]
I have that issue just on the built version using `yarn preview`. `yarn dev` works fine on my side (qwik: `0.10.0`, qwik city: `0.0.112`). thanks for having a look at it 🙏

**Comment by manucorporat** [comment]
Should be fixed in `0.11.0`!
