### ISSUE TITLE
States are changed is in an un-appropriate manner while slow internet

### ISSUE THREAD

**Issue by asif-simform** [BuilderIO/qwik#1528]
### Qwik Version

0.9.0

### Operating System (or Browser)

MAC OS - Browser (Chrome)

### Node Version (if applicable)

v16.13.1

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Need to work fine in low internet mode. e.g. fast/slow 3G.

States are changed is in an un-appropriate manner.

### Actual Behaviour

States are changed is in an appropriate manner.

### Additional Information

When I click on the increment button that time they call the network to fetch `onClick$={() => store.count++}` js chunk file. Due to slow internet is not loaded fast so when users click on the button and once js is loaded the count is increased instantly. e.g. 0 to 19

```
import { component$, useStore } from "@builder.io/qwik";

const App = component$(() => {
  const store = useStore({ count: 0 });

  return (
    <div>
      <p>Count: {store.count}</p>
      <p>
        <button onClick$={() => store.count++}>Click</button>
      </p>
    </div>
  );
});

export default App;

```

**Comment by manucorporat** [comment]
i cant reproduce this issue, can you record a video? full repo?

**Comment by asif-simform** [comment]
Good internet:
https://www.awesomescreenshot.com/video/11615724

Slow internet:
https://www.awesomescreenshot.com/video/11615776
