### ISSUE TITLE
StaticGenerate  type not being exported by definition file

### ISSUE THREAD

**Issue by mikeedwards83** [BuilderIO/qwik#1529]
### Qwik Version

0.9.0

### Operating System (or Browser)

Windows

### Which component is affected?

Qwik Runtime

### Expected Behaviour

StaticGenerate type exported from type definition

### Actual Behaviour

Type definition missing export keyword:

![image](https://user-images.githubusercontent.com/123856/193248626-4919bc34-6737-4f58-9305-070c2bbb9e8e.png)

**Comment by wtho** [comment]
Can you explain your use-case of why you need the type?

Anyhow, you can just go ahead and submit a PR for this. There's no need to keep this internallly.
