### ISSUE TITLE
[DOCS] SSG-SSR

### ISSUE THREAD

**Issue by ksuedile** [BuilderIO/qwik#1530]
Please improve documentation on SSG page.

You say that it is possible to mix SSR and SSG in a same project, but I do not understand how to flag pages that needs to be SSR and pages that needs to be SSG.

**Comment by wtho** [comment]
For now SSG builds all Routes, and there is no JS server implementation which checks each time if the html site is there, and triggers SSR if not.

I would say it highly depends on your Setup and your cloud provider. Usually you can configure in you CDN layer which routes hit a fast, static file storage and what routes call a cloud function/server to trigger SSR.

I would generally generate the whole app with SSG and then also deploy the SSR as cloud function and, as I mentioned before, configure the CDN to decide which route has to be SSR-rendered or can load the SSG html.

If you have your own server, you could configure your reverse proxy to decide which paths to load as files and which ones to proxy to a server instance.

Another possibility is to implement the initially mentioned JS server (e. g. in node) and handle all requests there, although this might be a slower (and more expensive) approach, as more layers of your server are getting activated on each request.

What did you initially have in mind, @adamdbradley ?
