### ISSUE TITLE
Adding npm run qwik add qwik-react  is breaking the app right now 

### ISSUE THREAD

**Issue by MeRahulAhire** [BuilderIO/qwik#1550]
### Qwik Version

0.9.0

### Operating System (or Browser)

Windows and Chrome

### Node Version (if applicable)

16+

### Which component is affected?

Qwik React

### Expected Behaviour

` npm run qwik add qwik-react` was working very well for me previously 

### Actual Behaviour

But now its giving the following error the moment I add this command ` npm run qwik add qwik-react` and everything crashes.
```bash
4:13:11 am [vite] Internal server error: module is not defined
      at /node_modules/react/index.js:2:0
      at instantiateModule (file:///C:/Users/rahul/OneDrive/Desktop/qwik-app/node_modules/vite/dist/node/chunks/dep-a713b95d.js:53390:15)
```

**Comment by Starnamics** [comment]
Has this been fixed yet?

**Comment by zanettin** [comment]
Hi @MeRahulAhire
Just gave it a quick run on `0.12.1` and on my end everything is working. Do you and/or @Starnamics wants to give it a spin as well? Tested `npm run build` and `npm run dev` as well 👍 

![Bildschirmfoto 2022-10-30 um 21 11 17](https://user-images.githubusercontent.com/3241476/198899611-10752f99-fdc8-4633-842a-45497aeb9321.png)

**Comment by Starnamics** [comment]
> Hi @MeRahulAhire
> Just gave it a quick run on `0.12.1` and on my end everything is working. Do you and/or @Starnamics wants to give it a spin as well? Tested `npm run build` and `npm run dev` as well 👍 
> 
> ![Bildschirmfoto 2022-10-30 um 21 11 17](https://user-images.githubusercontent.com/3241476/198899611-10752f99-fdc8-4633-842a-45497aeb9321.png)
> 

Sweet, thank you!
I'll try it out in a bit

**Comment by MeRahulAhire** [comment]
I'll try and let you know

**Comment by manucorporat** [comment]
Indeed this should be fixed in latest release!
