### ISSUE TITLE
Types not working on a simple component

### ISSUE THREAD

**Issue by CKGrafico** [BuilderIO/qwik#1558]
### Qwik Version

0.9.0

### Operating System (or Browser)

Windows

### Which component is affected?

Qwik Runtime

### Expected Behaviour

I expect to don't have errors in typings.

### Actual Behaviour

This code:
```
// GENERATED BY MITOSIS

import { component$ } from '@builder.io/qwik';
export const Button = component$((props) => {
  return <p>a</p>;
});
export default Button;

```

Has this error:
```
Argument of type '(props: {}) => Element' is not assignable to parameter of type 'OnRenderFn<{}>'.
  Type 'Element' is not assignable to type 'JSXNode<any>'.
    Type 'string' is not assignable to type 'JSXNode<any>'.ts(2345)
```

and if I put any to props, just to try what happens:
``` 
// GENERATED BY MITOSIS

import { component$ } from '@builder.io/qwik';
export const Button = component$((props: any) => {
  return <p>a</p>;
});
export default Button;

```

I've this error:
```
Argument of type '(props: any) => JSX.Element' is not assignable to parameter of type 'OnRenderFn<any>'.
  Type 'Element' is not assignable to type 'JSXNode<any>'.
    Type 'string' is not assignable to type 'JSXNode<any>'.ts(2345)
```

**Comment by brunocrosier** [comment]
Possible fix:

https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/core/component/component.public.ts#L221

change to: 

```ts
export type OnRenderFn<PROPS> = (props: PROPS) => JSXNode<any> | QwikElement | null;
```

**Comment by MasterMousa** [comment]
I don't sure, but you have to specific the props and their types (because it's TypeScript).
Personally, I recommend to specific the data types for the props (and think that there's security risks if it'll be <any> data type)

**Comment by CKGrafico** [comment]
At the end that was my fault because I have other package that conflicts with the typing, sorry!

**Comment by mhevery** [comment]
👍 Happy to help. Love what you are doing! ❤️

**Comment by CKGrafico** [comment]
> @CKGrafico What was the "other package" conflicting with the typing please?

I think was something related to react, I've some libraries in my repo

**Comment by YassienW** [comment]
Facing the same issue with a fresh Qwik starter project. All my components are spitting out the following typescript error: 
`Argument type () => JSX.Element is not assignable to parameter type OnRenderFn<unknown extends {} ? PropFunctionProps<unknown> : {}> `

Adding prop types doesn't fix it:
`Argument type ({prop}: {prop: string}) => JSX.Element is not assignable to parameter type OnRenderFn<{prop: string}> `

**Comment by YassienW** [comment]
Downgrading typescript from 5.1.6 to 4.5.4 fixes this error in all components. The starter project ships with typescript 5.1.6 though
