### ISSUE TITLE
Inline CSS on initial page load

### ISSUE THREAD

**Issue by BerndWessels** [BuilderIO/qwik#1564]
### Is your feature request related to a problem?

When loading the initial page, Qwik City sends a CSS file with the initial response, which is blocking in nature and slows down the page resulting in lower ranking.
![image](https://user-images.githubusercontent.com/1776695/193504981-be3ed8c6-dc2e-4fb6-aaba-3b5798518158.png)
![image](https://user-images.githubusercontent.com/1776695/193505073-b786dbd2-6eab-4e81-bf3d-697876265f5e.png)

### Describe the solution you'd like

If possible it would be great if the initial CSS could be included within the HTML response - which is the advice from web.dev
![image](https://user-images.githubusercontent.com/1776695/193505285-f1789885-139c-4b5d-ae47-c88aa937d7c2.png)

### Describe alternatives you've considered

maybe change the CSS to be lazy loaded? But inline with the HTML would be better to avoid layout drift.

**Comment by manucorporat** [comment]
Agreed! we will update our starters to do this

**Comment by manucorporat** [comment]
We did! new starters use `useStyles$()` which inlines the styles
