### ISSUE TITLE
Typing any keyboard button in the documentation site will remove code highlighting

### ISSUE THREAD

**Issue by ahashem95** [BuilderIO/qwik#1565]
### Qwik Version

0.9.0

### Operating System (or Browser)

All browsers

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Code highlighting should not be affected by keyboard typing.

### Actual Behaviour

Highlighting is broken once any keyboard button is pressed.

### Additional Information

After typing on the keyboard, the network tab shows that `q-58078c4c.js` is being downloaded.

<img width="681" alt="Screen Shot 2022-10-03 at 9 49 51 AM" src="https://user-images.githubusercontent.com/113237144/193517018-b5f501bc-d1ae-4803-aa22-e0d61bb36ff3.png">

But when blocking this chunk, the code highlighter is not affected anymore.

<img width="982" alt="Screen Shot 2022-10-03 at 10 07 42 AM" src="https://user-images.githubusercontent.com/113237144/193519434-78df0f47-fd72-4816-b071-529bac0cca07.png">

**Comment by Varixo** [comment]
Duplicate https://github.com/BuilderIO/qwik/issues/1421
