### ISSUE TITLE
Caching client page data prevents `onGet()` calls in unexpected ways

### ISSUE THREAD

**Issue by petebacondarwin** [BuilderIO/qwik#1582]
### Qwik Version

Qwik: 0.9.0; QwikCity: 0.0.111

### Operating System (or Browser)

Any

### Node Version (if applicable)

Any

### Which component is affected?

Qwik City

### Description

When doing client-side navigation QwikCity is expected to trigger the `onGet()` handler for the new route via a JSON request to the route endpoint (with `.json` extension).

In an attempt to help with performance (I assume) calls to these endpoints are cached for 6 seconds between requests.
This means that one cannot use `onGet()` to provide data that could change more frequently than this.

Here is the block of code that does this:

https://github.com/BuilderIO/qwik/blob/2895fd6b00fd435b54b551e4dfed5a9a0e19f07a/packages/qwik-city/runtime/src/library/use-endpoint.ts#L31-L40

A concrete use-case for us is to grab an authentication token from the cookie and return it to the route so that it can render appropriately (e.g. display the user name). Consider the following steps:

1. navigate (client-side) to the "profile page", the `onGet()` handler extracts the current user "Miško", which is displayed in on the page.
2. click a "logout" link to navigate (client-side) to the "login page"
3. login as "Manu" and be redirected (client-side) back to the "profile page"

If step 3 happens in less than 6 seconds then the profile page's `onGet()` function is not requested, so the authentication token that contains "Manu" is not extracted, and the page is rendered with the old "Miško" username.

### Expected Behaviour

I think that caching should be configurable and opt-in, ideally on a per-route basis. It took many hours of debugging and confusion to find what was causing our templates to render with what appeared to be incorrect data.

**Comment by adamdbradley** [comment]
Ok thanks for opening the issue. I think we can just get rid of the caching here and if it's an issue we can rethink it.

**Comment by petebacondarwin** [comment]
Yeah, let's not pre-optimize this for now.

**Comment by petebacondarwin** [comment]
More accurately by https://github.com/BuilderIO/qwik/pull/1588 :-D
