### ISSUE TITLE
Params get replaced by "service-worker.js"

### ISSUE THREAD

**Issue by lukemansell** [BuilderIO/qwik#1596]
### Qwik Version

0.9.0

### Operating System (or Browser)

Chrome

### Which component is affected?

Qwik City

### Expected Behaviour

When I try to get the params from a URL, I expect it to return the pages params correctly and for those params to not suddenly change.

Eg: if I am on /page and try to get the params to work out what the pages params are, I expect it to always return `page`

### Actual Behaviour

When trying to get the params, it returns correctly but is then replaced with service-worker.js a second later. 

A code example:

```
export const onGet: RequestHandler = async ({ params }) => {
    const loc = params.url;
    console.log("Params URL: " + loc);
}
```

returns in the console (when going to /page):

```
Params URL: page
Params URL: service-worker.js
Params URL: service-worker.js
```

**Comment by manucorporat** [comment]
Should be fixed!
