### ISSUE TITLE
Can't track signal inside useWatch$, useClientEffect$

### ISSUE THREAD

**Issue by langbamit** [BuilderIO/qwik#1619]
### Qwik Version

0.10.0

### Operating System (or Browser)

Brave Browser

### Node Version (if applicable)

18.8.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Run successfully

P/s: track inside useResource$ working

### Actual Behaviour

<details>
<summary>Crash client with errors</summary>

QWIK ERROR Cannot read properties of null (reading '$addSub$') TypeError: Cannot read properties of null (reading '$addSub$')
    at get value [as value] (https://qwik.builder.io/repl/1w31b6kxcgf/build/app2.js:4674:40)
    at https://qwik.builder.io/repl/1w31b6kxcgf/build/app_component_useclienteffect_3xgslpojvrc.js:6:29
    at invoke (https://qwik.builder.io/repl/1w31b6kxcgf/build/app2.js:320:26)
    at track (https://qwik.builder.io/repl/1w31b6kxcgf/build/app2.js:3302:20)
    at App_component_useClientEffect_3XgsLpOJvrc (https://qwik.builder.io/repl/1w31b6kxcgf/build/app_component_useclienteffect_3xgslpojvrc.js:6:15)
    at invoke (https://qwik.builder.io/repl/1w31b6kxcgf/build/app2.js:320:26)
    at https://qwik.builder.io/repl/1w31b6kxcgf/build/app2.js:5023:28
    at then (https://qwik.builder.io/repl/1w31b6kxcgf/build/app2.js:265:56)
    at https://qwik.builder.io/repl/1w31b6kxcgf/build/app2.js:5012:20
    at https://qwik.builder.io/repl/1w31b6kxcgf/build/app2.js:3328:27

</details>

### Additional Information

[reproduction](https://qwik.builder.io/playground#version=0.10.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU2lnbmFsJTJDJTIwdXNlQ2xpZW50RWZmZWN0JTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwcmVmJTIwJTNEJTIwdXNlU2lnbmFsJTNDSFRNTEVsZW1lbnQlM0UoKSU1Q24lMjAlMjB1c2VDbGllbnRFZmZlY3QlMjQoKCU3QnRyYWNrJTdEKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zdCUyMHAlMjAlM0QlMjB0cmFjaygoKSUyMCUzRCUzRSUyMHJlZi52YWx1ZSklNUNuJTIwJTIwJTIwJTIwaWYlMjAocCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwcC50ZXh0Q29udGVudCUyMCUzRCUyMCU1QyUyMkhpJTIwZm9yayElNUMlMjIlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCU3RCklNUNuJTIwJTIwcmV0dXJuJTIwJTNDcCUyMHJlZiUzRCU3QnJlZiU3RCUzRUhlbGxvJTIwUXdpayUzQyUyRnAlM0UlM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwQXBwJTIwJTdEJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NodG1sJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

**Comment by manucorporat** [comment]
Fixed in main! we should release soon
