### ISSUE TITLE
Hiding a default slot with a custom component sibling hides both in 0.10.0

### ISSUE THREAD

**Issue by ulic75** [BuilderIO/qwik#1630]
### Qwik Version

0.10.0

### Operating System (or Browser)

Brave & Firefox

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Using the below playground link, I would expect that when you click on the button to toggle the "Non-Slotted Content" that only the "Non-Slotted Content" would hide.

https://tinyurl.com/5byssrux

### Actual Behaviour

Instead all of the children are hidden.

### Additional Information

If you change the version to 0.9.0 it works as expected.

Also if you change from using a child component to just a standard html element it works as expected, so seems to have something to do with using a named slot on a custom component.

**Comment by manucorporat** [comment]
thanls for the repo case! working on a fix
