### ISSUE TITLE
Oficial CodeSandbox Template

### ISSUE THREAD

**Issue by CKGrafico** [BuilderIO/qwik#1644]
### Is your feature request related to a problem?

Will be nic,e to have an official and simple codesandbox template I've tried to create one super simple but is not working https://codesandbox.io/s/simple-qwik-start-22nrbw?file=/package.json

If you download the project it works in local.

### Describe the solution you'd like

To don't have only templates in stackblitz, to have also a codesandbox

### Describe alternatives you've considered

Don't have codesandbox and migrate all my examples to other platform...

### Additional context

I'm generating papanasi.js.org examples on the fly to codesandbox and qwik is the only platform that I cannot generate there

**Comment by gioboa** [comment]
Hi @CKGrafico, the official are the [Qwik playground](https://qwik.builder.io/playground) and the stackblitz one [qwik.new](https://qwik.new).
You can create your Qwik codesandbox like [this one](https://codesandbox.io/p/devbox/fragrant-cherry-nl3d87) that I took from the community.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
