### ISSUE TITLE
Context in Layouts

### ISSUE THREAD

**Issue by mastastealth** [BuilderIO/qwik#1648]
### Qwik Version

0.10.0

### Operating System (or Browser)

W10 / Firefox

### Which component is affected?

Qwik City

### Expected Behaviour

I expected the consumption of a context to work fine within a route given a layout wrapped in a provider.

### Actual Behaviour

I get the following error:
> Code(13): Actual value for useContext() can not be found, make sure some ancestor component has set a value using useContextProvider()

### Additional Information

I've pushed a fresh Qwik City install in an example repo, then [applied the simplest version](https://github.com/mastastealth/qwik-context/commit/83d16aab40a88365e34e2ca7e030e77938b3c537) of my context changes, which reproduces the error I'm seeing.

Also worth mentioning, that [using that same context](https://github.com/mastastealth/qwik-context/commit/dbd1e27ce37a99ca95f772fad1117aae7e6fb289) from the `Header` component _does_ work.

**Comment by nnelgxorz** [comment]
This was implemented previously. Appears to be a regression.

https://github.com/BuilderIO/qwik/issues/599

**Comment by jrson83** [comment]
I get the same error when I try to use `useContent()` inside the default `src/root.tsx` layout component.

**Comment by manucorporat** [comment]
I would help a lot of simple piece of code that reproduces it, maybe in the playground https://qwik.builder.io/playground/

**Comment by nnelgxorz** [comment]
Won't be able to reproduce in the playground because it needs a layout.tsx to trigger the bug.

@mastastealth has the minimal repro here https://github.com/mastastealth/qwik-context/commit/83d16aab40a88365e34e2ca7e030e77938b3c537

The important parts are src/routes/layout.tsx and src/components/provider.tsx

**Comment by mastastealth** [comment]
@manucorporat Here's the same repo example code [on Stackblitz](https://stackblitz.com/edit/qwik-starter-sraqc8?file=src/routes/index.tsx), if that is quicker.

**Comment by wmertens** [comment]
FYI I tested with 0.11.1 and 0.0.112 and the issue is still present

**Comment by NachoVazquez** [comment]
Do we now in which version is/will be released this fix?

**Comment by mingfang** [comment]
The problem still exist in 0.13.3

**Comment by NachoVazquez** [comment]
@wmertens Yes, I confirm like @mingfang that the error is still present in `0.13.3`

**Comment by NachoVazquez** [comment]
@wmertens Yes, I confirm like @mingfang that the error is still present in `0.13.3`

**Comment by nnelgxorz** [comment]
@mingfang @NachoVazquez Can one of you make a [Stackblitz reproduction](https://qwik.new/)?

**Comment by NachoVazquez** [comment]
In a second!

**Comment by NachoVazquez** [comment]
This was created by a coworker of mine. I just updated the versions.

https://stackblitz.com/edit/qwik-starter-vyaj1q?file=src/routes/flower/index.tsx

**Comment by wmertens** [comment]
@manucorporat confirmed.
routes/layout.tsx has the contextprovider, and flower/index.tsx uses the context but has no access to it.

**Comment by jwickers** [comment]
Still in latest and it only happens when using the Link and doing client-side navigation if that helps.

**Comment by T-travis** [comment]
After bringing this bug up twice in the Discord server (I'm Data in Discord), I thought I would try to find a workaround for using Link in SPAs.  

### Steps when using the Stackblitz link:

#### Context works in Named Layouts always.
- Start the app and click the *Will context work in Named Layouts?* button over and over.
#### Context won't work in normal Layouts the **first** attempt almost ever.
- Restart the app and click the *Will context work for a normal Layout?* button immediately.
#### Context will work in normal Layouts AFTER running a Named Layout first.
- Restart the app and click the *Will context work for a Named Layouts?* and then the *Will context work for a normal Layout?* button.

https://stackblitz.com/edit/qwik-starter-5xnz1q?file=src/routes/index.tsx

The workaround appears to be to use Named Layouts for now.  Hope this helps!

**Comment by Dindaleon** [comment]
Is this bug still present? Because I am having it right now on version `0.16.2`

**Comment by Dindaleon** [comment]
I found a temporal fix:

Write a component with the following:

```
import {
  component$,
  Slot,
  useClientEffect$,
  useContext,
} from '@builder.io/qwik'
import { AuthContext } from './authProvider'

export const ContextSetter = component$(() => {
  const auth = useContext(AuthContext)
  useClientEffect$(({ track }) => {
    track(auth)
  })

  return <Slot></Slot>
})
```

In root.tsx put the component inside the body tags

```
<body lang="en">
  <ContextSetter>
    <RouterOutlet />
    <ServiceWorkerRegister />
  </ContextSetter>
</body>
```

It works like a charm. Waiting for an official fix :)

**Comment by imMadsen** [comment]
I know this issue is closed but if someone comes across it. The issue seems to be able to be resolved my using the 'useContextProvider' in Layout instead of having a component that wraps around.

Like if you had 'MyContextProvider' and used it in your layout.tsx

> layout.tsx
<MyContextProvider>
</MyContextProvider>

**Comment by imMadsen** [comment]
Okay, I think I might have a good solution!

Instead of wrapping your component in a provider, simply create provider hook. Here is an example from my project

EnvironmentContext.tsx
```
export function useEnvironmentProvider() {
    const environment = useStore<EnvironmentContext>({
        state: "Loading",
        registrants: {}
    });

    // eslint-disable-next-line qwik/no-use-visible-task
    useVisibleTask$(() => {
        async function getRegistrants() {
        try {
            const snapshot = await getDocs(collection(db, "registrants"));
    
            for (const doc of snapshot.docs) {
            environment.registrants[doc.id] = doc.data() as Registrant;
            }
    
            environment.state = "Valid"
        } catch (e) {
            environment.state = "Invalid";
        }
        }
    
        getRegistrants();
    });

    useContextProvider(EnvironmentContext, environment)
}
```

Layout.tsx
```
export default component$(() => {
  useEnvironmentProvider()

  return (...);
})
```
