### ISSUE TITLE
"build.target = es2015" show "uncaught SyntaxError: Unexpected token 'export' (at service-worker.js:1:2509)"

### ISSUE THREAD

**Issue by lzxb** [BuilderIO/qwik#1649]
### Qwik Version

0.10.0

### Operating System (or Browser)

Mac os chrome  104.0.5112.79 (arm64)

### Node Version (if applicable)

v16.13.2

### Which component is affected?

Qwik City

### Expected Behaviour

No error reporting

### Actual Behaviour

Uncaught SyntaxError: Unexpected token 'export' (at service-worker.js:1:2509)__

<img width="836" alt="image" src="https://user-images.githubusercontent.com/8424643/194735211-5910af20-98ea-45dc-9115-8e1624c50945.png">

### Additional Information

```bash
git clone git@github.com:lzxb/qwik-demo.git
git checkout bugfix-service-worker
yarn
yarn preview

```

**Comment by zanettin** [comment]
Hi @lzxb 
Just cloned your example repo mentioned above to give it a spin but didn't get the error. Do you still have it?

**Comment by lzxb** [comment]
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/8424643/198915266-9c683cfd-75bd-4fd9-b6e7-278046008f5a.png">
It still exists

**Comment by zanettin** [comment]
Thanks for your reply 🙏 
Checked it again and i also have the error even on latest (0.12.1) when running the app using `yarn preview`. When i build it and run it then `yarn build && yarn start`, the SW seems to be perfect. Hope that helps for anybody to take over this task 🙏

**Comment by manucorporat** [comment]
Should be fixed!
