### ISSUE TITLE
`base` props isn't used in CSS link

### ISSUE THREAD

**Issue by gioboa** [BuilderIO/qwik#1650]
### Qwik Version

v0.10.0

### Operating System (or Browser)

macOs + Chrome

### Node Version (if applicable)

v18.10.0

### Which component is affected?

Qwik City

### Expected Behaviour

if I set the `base` parameter, it should be used in the css link

### Actual Behaviour

`return renderToStream(<Root />, {
    [...]
    base: 'http://www.whatever.com/build',
    [...]
});`

<img width="483" alt="Screenshot" src="https://user-images.githubusercontent.com/35845425/194745105-7154b791-19a6-4114-8a3d-d0d87479afd1.png">

**Comment by manucorporat** [comment]
makes sense, however `q:base` only applies to QRLs right now... the injected stylesheet is a vite feature... not sure how both can be connected

**Comment by gioboa** [comment]
I see. So Vite need to be configured to use the `base` value 🤔

**Comment by gioboa** [comment]
I solved with inline CSS
`import styles from './global.css?inline';
export default component$(() => {
	useStyles$(styles);
`

**Comment by hafeyang** [comment]
same problem for me 
q:base is my cdn domain

`import("./xxx.js)` 

does not load `[cdn]/xxx.js`
