### ISSUE TITLE
setting innerHTML

### ISSUE THREAD

**Issue by rainerhahnekamp** [BuilderIO/qwik#1651]
### Qwik Version

0.10.0

### Operating System (or Browser)

macOS 12.6

### Node Version (if applicable)

16.16.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

In my use case, I get markdown data from an endpoint and want to show it as HTML. 

Common approaches like 

```tsx
// code to fetch markdown data, transform and sanitize to HTML
// ...


return <>
  <p innerHTML={sanitzedHtml}></p>
  <p dangerouslySetInnerHTML={{__html: sanitizedHtml}}></p>
</>
```

do not work.

Is this use case supported, and if not, is there a workaround?

Thank you!

### Actual Behaviour

Couldn't find any solution in the docs. Compilation fails with `innerHTML` and `dangerouslySetInnerHTML`.

**Comment by Varixo** [comment]
```tsx
<p dangerouslySetInnerHTML={sanitzedHtml}></p>
```
should work

**Comment by manucorporat** [comment]
Surprised TS didnt helped here...

**Comment by rainerhahnekamp** [comment]
Thank you very much @manucorporat. You saved my day!

I was also hoping for more support from TypeScript. Didn't happen actually

<img width="752" alt="Screenshot 2022-10-10 at 23 02 47" src="https://user-images.githubusercontent.com/5721205/194951981-ce41e93a-9dc4-4504-9e4b-7542486a033c.png">
