### ISSUE TITLE
Child component doesn't re-render when its props change

### ISSUE THREAD

**Issue by kumarasinghe** [BuilderIO/qwik#1654]
### Qwik Version

0.10.0

### Operating System (or Browser)

Chrome / Ubuntu 22.04

### Node Version (if applicable)

16.17.1

### Which component is affected?

Qwik Runtime

### Expected Behaviour

As per the example in [documentation](https://qwik.builder.io/docs/concepts/reactivity/#invalidating-child-components) the child component should re-render when its props change.

```
const Child = component$((props: { count: number }) => {
  return <span>{props.count}</span>;
});

const MyApp = component$(() => {
  const store = useStore({ a: 0, b: 0, c: 0 });

  return (
    <>
      <button onClick$={() => store.a++}>a++</button>
      <button onClick$={() => store.b++}>b++</button>
      <button onClick$={() => store.c++}>c++</button>

      <Child count={store.a} />
      <Child count={store.b} />
    </>
  );
});
```

### Actual Behaviour

The child component doesn't re-render on prop change.
Child only re-renders only if the value passed as the prop is read somewhere in the parent component.

This could be due to the store subscription not getting activated.

### Additional Information

Please remove `{JSON.stringify(store)}` in the code to reproduce the bug

**Comment by manucorporat** [comment]
The code reports an error, no?

**Comment by manucorporat** [comment]
I cant reproduce the issue in 0.10.0
