### ISSUE TITLE
Build fails when passing manualchunks to vite

### ISSUE THREAD

**Issue by iendeavor** [BuilderIO/qwik#1659]
### Qwik Version

0.10.0

### Operating System (or Browser)

macOS Monterey 12.5

### Node Version (if applicable)

18.1.0

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

The script `npm run build.preview` should succeed.

Reproducible example: https://github.com/iendeavor/import-meta-env/tree/53fdd5232e7e8593f3a0b45310404fd47bffeaf1/packages/examples/vite-qwik-example (This application is created by `npm create qwik@latest`).

### Actual Behaviour

When running `vite build --ssr src/entry.preview.tsx`

```sh
Invalid value for option "output.inlineDynamicImports" - multiple inputs are not supported when "output.inlineDynamicImports" is true.
```

### Additional Information

Similar issue found in svelte: https://github.com/sveltejs/kit/issues/1718

**Comment by manucorporat** [comment]
Can you try again using latest Vite and Qwik (0.12.1)?

**Comment by manucorporat** [comment]
We removed this setting, so i assume this should be fixed from outside! closing, but feel free to reopen!
