### ISSUE TITLE
Correct types for event functions

### ISSUE THREAD

**Issue by GustavoMelloGit** [BuilderIO/qwik#1661]
### Is your feature request related to a problem?

It's really annoying to have to cast HTMLInputElement or something like that everytime that i have to use a value of the input, for example.
```ts
<input
      value={store.value}
      onInput$={(event) => (store.value = (event.target as HTMLInputElement).value)}
/>
```

### Describe the solution you'd like

The solution would be types being inferred automatically :

```ts
<input
      value={store.value}
      onInput$={(event) => (store.value = event.target.value)} // (e) type as HTMLInputElement
/>
```

### Describe alternatives you've considered

Didn't think any

### Additional context

I would like to solve this issue, but i am having trouble on finding where those types are

**Comment by nnelgxorz** [comment]
I think the file you're looking for is here.

https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts

**Comment by GustavoMelloGit** [comment]
@nnelgxorz haven't found anything about those events such as onInput$, am i missing something?

**Comment by nnelgxorz** [comment]
Yeah, it's a little confusing in there.

They are generated based here: 
https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts#L168 

based on this type: 
https://github.com/BuilderIO/qwik/blob/bd1b72c9397bdb7bc6f2d9e3028f4388d00560e1/packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts#L8

**Comment by GustavoMelloGit** [comment]
Thanks @nnelgxorz , this weekend i'll be looking for this

**Comment by brunocrosier** [comment]
I think this is fixed by https://github.com/BuilderIO/qwik/pull/1827

**Comment by manucorporat** [comment]
yes! fixed!
