### ISSUE TITLE
The qwik-react starter crashes with: `export named 'Fragment' doesn't exist`

### ISSUE THREAD

**Issue by ahhshm** [BuilderIO/qwik#1677]
### Qwik Version

0.10.0

### Operating System (or Browser)

Chromium

### Node Version (if applicable)

16.17.1

### Which component is affected?

Qwik React

### Expected Behaviour

The example React component should work normally.

### Actual Behaviour

I get this error on the example React component:
![Screenshot from 2022-10-10 18-23-05](https://user-images.githubusercontent.com/87268103/194896249-7439ee8d-2e1c-4c5a-8567-8b0374cdc053.png)
This is the error that I get in the console:
```
QWIK ERROR The requested module '/node_modules/react/jsx-runtime.js?v=55ba69c2' does not provide an export named 'Fragment' SyntaxError: The requested module '/node_modules/react/jsx-runtime.js?v=55ba69c2' does not provide an export named 'Fragment'
```

When I remove `client:visible` directive the error goes away.

### Additional Information

To reproduce:
```
yarn create qwik qwik-react-bug
cd qwik-react-bug
yarn qwik add qwik-react
yarn dev
```
And then open `http://localhost:5173/react` in your browser.
I'm using Yarn v1.22.9

**Comment by manucorporat** [comment]
Should be fixed in latest release!
