### ISSUE TITLE
Virtual Host Edge Case: Anchor tag inside of Link component

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#1684]
### Qwik Version

0.10.0

### Operating System (or Browser)

Debian Linux

### Node Version (if applicable)

v16.3.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Whenever the container resumes, it should do so without any errors.

### Actual Behaviour

It crashes because of a missing virtual element close.

### Additional Information

In the [minimal repro I've created here](https://github.com/nnelgxorz/virtual-host-missing-close-bug), got to src/routes/index.tsx and run the dev server. 

There is a button that need to resume onClick at line 11.

On line fifteen there is a Link component with a text node on line 17 and a commented out anchor tag on line 16.

In the browser, you can click on the button and it resumes and updates correctly.

Now, comment out at the text node on line 17 and uncomment the anchor tag. When the click the button in the browser now you should see this error:

```bash
Uncaught (in promise) Error: close not found
    findClose virtual-element.js:283
    acceptNode store.js:82
    resumeContainer store.js:106
    resumeIfNeeded props.js:15
    useLexicalScope use-lexical-scope.public.js:31
    routes_component_div_h1_button_onClick_Rfg3fL9SxOQ routes_component_div_h1_button_onclick_rfg3fl9sxoq.js:3
    dispatch (index):155
    processDocumentEvent (index):175
    addEventListener (index):203
    push (index):209
    push (index):219
    <anonymous> 
```

**Comment by manucorporat** [comment]
FIxed by https://github.com/BuilderIO/qwik/issues/1794
