### ISSUE TITLE
`useOnWindow` doesn't work in components that doesn't return a HTML element

### ISSUE THREAD

**Issue by ahhshm** [BuilderIO/qwik#1685]
### Qwik Version

0.10.0

### Operating System (or Browser)

Chromium

### Node Version (if applicable)

16.17.1

### Which component is affected?

Qwik Runtime

### Expected Behaviour

I have this component that should be shown after certain amount of scroll:
```tsx
import { $, component$, useOnWindow, useSignal } from "@builder.io/qwik";

export const ScrollToTop = component$(() => {
  const shouldShow = useSignal(false);

  useOnWindow(
    "scroll",
    $(() => {
      if (window.scrollY > 200) {
        shouldShow.value = true;
      } else {
        shouldShow.value = false;
      }
    })
  );

  return shouldShow.value ? (
    <button
      onClick$={() => {
        window.scrollTo({ top: 0, behavior: "smooth" });
      }}
      class="fixed bottom-6 right-6 z-50 flex h-6 w-6 items-center justify-center rounded-lg bg-primary-light opacity-70"
    >
        scroll to top
    </button>
  ) : (
    <div>{/* useOnWindow doesn't work without this */}</div>
  );
});
```

### Actual Behaviour

Notice the empty `<div>` that I returned if `shouldShow.value` if false. Without that (if I replace it with `null` or even an empty fragment) `useOnWindow` wouldn't work and when I scroll nothing would happen.

**Comment by manucorporat** [comment]
This should be fixed, now we inject a `script` element to be able to listen to events, even if no content was rendered
