### ISSUE TITLE
I would like to access the env property of the Cloudflare functions as part of the ResquesEvent or its RequestContext

### ISSUE THREAD

**Issue by NachoVazquez** [BuilderIO/qwik#1690]
### Is your feature request related to a problem?

I've been working on integrating Qwik + Prisma + Cloudflare Pages. To achieve this we need to use Prisma Data-Proxy and read the database URL from the Cloudflare Worker context `env` property instead that from the `process.env` as you would usually do.

See https://github.com/prisma/prisma/issues/13771#issuecomment-1204295665

### Describe the solution you'd like

I would like to either have the env property in the `RequestEvent`.

```ts
export declare interface RequestEvent {
    request: RequestContext;
    response: ResponseContext;
	env:any; // <---- this
    url: URL;
    /** URL Route params which have been parsed from the current url pathname. */
    params: RouteParams;
    /** Platform specific data and functions */
    platform: Record<string, any>;
    next: () => Promise<void>;
    abort: () => void;
}
```

Or in the `RequestContext`

```ts
export declare interface RequestContext {
    formData(): Promise<FormData>;
	env:any; // <---- this
    headers: Headers;
    json(): Promise<any>;
    method: string;
    text(): Promise<string>;
    url: string;
}
```

### Describe alternatives you've considered

I don't have any other suggestions but I would expect other platforms like Vercel that use Cloudflare Workers to need something similar.

**Comment by NachoVazquez** [comment]
I wonder if that enters in the `platform` property?

**Comment by tunnckoCore** [comment]
Interested in hearing about this too. I'm wondering how to use/access the CloudFlare KV.

**Comment by tunnckoCore** [comment]
@NachoVazquez Yes, seems like the `env` that gets passed to the CF request handlers is actually passed as-is to as `platform`.

![image](https://user-images.githubusercontent.com/5038030/197672135-73913e05-a904-42bc-846c-f77d0bb5bb3e.png)

**Comment by NachoVazquez** [comment]
Nice I was able to use it for the KV store but I wasn't sure it was also bringing the ENVIRONMENT secrets. Thanks, in that case, I can close this down!

**Comment by tunnckoCore** [comment]
@NachoVazquez awesome! :heart: Can you share me some code for the KV usage? I'm playing with it now and I think I'm almost getting it :D

**Comment by NachoVazquez** [comment]
Sure, I was planning in publishing a repo with the basic setup tomorrow, but I can show you what you need now. Give me a second I'll add the details as an update to this comment.

**Comment by tunnckoCore** [comment]
Yeah, thanks! Exactly what I did, just console logged the `platform` and it was there.

**Comment by NachoVazquez** [comment]
I added a second update with the necessary config to have access to the wrangler types.
