### ISSUE TITLE
Deep Objects Docs section doesn't include recursive option

### ISSUE THREAD

**Issue by dario-piotrowicz** [BuilderIO/qwik#1692]
The [reactivity/deep-object](https://qwik.builder.io/docs/concepts/reactivity/#deep-objects) section of the docs is missing the `recursive` option which is needed in order to have `useState()` work with deep properties.

**Comment by chanon** [comment]
You are missing the { recursive: true } option
[see fix](https://qwik.builder.io/playground#version=0.10.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzdGF0ZSUyMCUzRCUyMHVzZVN0b3JlKCU3QiU1Q24lMjAlMjAlMjAlMjBjb3VudGVyJTNBJTIwMSUyQyU1Q24lMjAlMjAlMjAlMjBkZWVwQ291bnRlciUzQSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjB2YWx1ZSUzQSUyMDElNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCU3RCUyQyUyMCUyMCU3QnJlY3Vyc2l2ZSUzQSUyMHRydWUlN0QpJTNCJTIwJTVDbiU1Q24lMjAlMjAlMkYlMkYlMjBVbmNvbW1lbnQlMjB0aGUlMjBjb25zb2xlLmxvZyUyMHRvJTIwZ2V0JTIwdGhlJTIwZGVlcCUyMGNvdW50ZXIlMjB0byUyMHVwZGF0ZSUyMG9uJTIwY291bnRlciUyMHVwZGF0ZXMlNUNuJTIwJTIwJTJGJTJGJTIwY29uc29sZS5sb2coSlNPTi5zdHJpbmdpZnkoJTdCc3RhdGUlN0QpKSUzQiU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTNFJTVDbiUyMCUyMCUyMCUyMCUzQ2J1dHRvbiUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMHN0YXRlLmNvdW50ZXIlMkIlMkIlN0QlM0Vjb3VudGVyJTNBJTIwJTdCc3RhdGUuY291bnRlciU3RCUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlMjAlMjAlM0NiciUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlM0NiciUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlM0NidXR0b24lMjBvbkNsaWNrJTI0JTNEJTdCKCklMjAlM0QlM0UlMjBzdGF0ZS5kZWVwQ291bnRlci52YWx1ZSUyQiUyQiU3RCUzRWRlZXAlMjBjb3VudGVyJTNBJTIwJTdCc3RhdGUuZGVlcENvdW50ZXIudmFsdWUlN0QlM0MlMkZidXR0b24lM0UlNUNuJTIwJTIwJTNDJTJGZGl2JTNFJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFwcCUyMCU3RCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE)

**Comment by dario-piotrowicz** [comment]
@chanon yeah, thanks a bunch I missed that one 😓

I missed this because it wasn't mentioned in the docs page I was looking at, it didn't occur to me to check the state page

I'm tempted to just close this issue, but that page is indeed outdated/misleading, so maybe I can just update the issue to indicate that? 🤔
