### ISSUE TITLE
Ternary operators break template subscriptions

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#1694]
### Qwik Version

0.10.0

### Operating System (or Browser)

Chrome 106

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Using a ternary operator in a template should conditionally show/hide content.

### Actual Behaviour

The store subscription doesn't work with ternary operators.

If you add another subscription next to the ternary operate, both continue to work.

**Comment by manucorporat** [comment]
it's not about the ternary operator, but that useStore() does not create subscriptions recusively:
```
  const store = useStore<Props['data']>(
    {
      count: 0,
      nested: {
        count: 0,
      },
    },
    { recursive: true }
  );
```
adding `{recursive: true}` allows to track subscriptions in sub objects

**Comment by DustinJSilk** [comment]
Aaah i see, thanks @manucorporat !
