### ISSUE TITLE
[DOCS] Preloading / Prefetching on Component level

### ISSUE THREAD

**Issue by zanettin** [BuilderIO/qwik#1702]
For LCP relevant images we currently push `<link rel="preload" as="image" href="xxx">` to the document head while rendering the img in the responsible component in react. Is this somehow possible with QWIK and what's the recommended way?

Good article about this topic: https://web.dev/preload-responsive-images/#preload-and-lesspicturegreater

Thanks a lot and keep up the great work 🙏

**Comment by manucorporat** [comment]
it's tricky in SSR streaming, react is actually holding all the HTML until the whole page is rendered, Qwik is pushing to network as soon as possible, that also means that a component cant easy change parts of the html that are already in the network.

However, for this optimization, you can control the headers manually in qwikcity's `export const head` at the route file

**Comment by manucorporat** [comment]
We will implement soon a <Image> component baking a lot of optimization, we will take this into account!

**Comment by zanettin** [comment]
thanks a lot for the detailed feedback 🙏  really appreciated!
