### ISSUE TITLE
Allow "scoped" styles to be inherited by Qwik Components

### ISSUE THREAD

**Issue by petebacondarwin** [BuilderIO/qwik#1710]
### Is your feature request related to a problem?

Consider the following setup:

```ts
import { component$, useStyles$, useStylesScoped$ } from '@builder.io/qwik';

export const App = component$(() => {
  useStylesScoped$(`.red-color { color: red }`);
  useStyles$(`.green-border { border: solid 1px green }`);
  return <p>Hello <Name class="red-color green-border"/> !</p>;
});

export const Name = component$((props: {class:string}) => {
  return <span class={props.class}>PETE</span>
});
```

[Playground](https://qwik.builder.io/playground#version=0.11.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3R5bGVzJTI0JTJDJTIwdXNlU3R5bGVzU2NvcGVkJTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHVzZVN0eWxlc1Njb3BlZCUyNCglNjAucmVkLWNvbG9yJTIwJTdCJTIwY29sb3IlM0ElMjByZWQlMjAlN0QlNjApJTNCJTVDbiUyMCUyMHVzZVN0eWxlcyUyNCglNjAuZ3JlZW4tYm9yZGVyJTIwJTdCJTIwYm9yZGVyJTNBJTIwc29saWQlMjAxcHglMjBncmVlbiUyMCU3RCU2MCklM0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDcCUzRUhlbGxvJTIwJTNDTmFtZSUyMGNsYXNzJTNEJTVDJTIycmVkLWNvbG9yJTIwZ3JlZW4tYm9yZGVyJTVDJTIyJTJGJTNFJTIwISUzQyUyRnAlM0UlM0IlNUNuJTdEKSUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBOYW1lJTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSUyMCU3QmNsYXNzJTNBc3RyaW5nJTdEKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAlM0NzcGFuJTIwY2xhc3MlM0QlN0Jwcm9wcy5jbGFzcyU3RCUzRVBFVEUlM0MlMkZzcGFuJTNFJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFwcCUyMCU3RCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE)

### Describe the solution you'd like

I would like that the `red-color` styles are applied to the "host" `<span>` element of the `<Name>`  component.
I understand that the styles should not leak down into the rest of the `Name` components template.
But the host element feels like it should be special.
Otherwise it is not possible to use `useStylesScoped()` to apply styles to components that live in the current template.

### Describe alternatives you've considered

You can work around this by using `useStyles()` rather than `useStylesScoped()` but then the styles become global and leak everywhere.

**Comment by petebacondarwin** [comment]
The use case I have is that I want to provide a simple `<Image>` component that can be styled by applying a CSS class from the containing template.

**Comment by petebacondarwin** [comment]
OK so I see there was related discussion about this here: https://github.com/BuilderIO/qwik/discussions/1063
And then resolved here: https://github.com/BuilderIO/qwik/commit/d214d3950ed4d4075815bb240c581d2183f3d64a

So I think that I can get around this by combining scoped and global selectors.

**Comment by manucorporat** [comment]
i imagine we could provide this as well:
```tsx
import { component$, useStyles$, useStylesScoped$ } from '@builder.io/qwik';

export const App = component$(() => {
  const {classes} = useStylesScoped$(`.redcolor { color: red }`);
  return <p>Hello <Name class={classes.redcolor} /> !</p>;
});

export const Name = component$((props: {class:string}) => {
  return <span class={props.class}>PETE</span>
});
```

**Comment by petebacondarwin** [comment]
I guess the question is whether one should special case `class` or whether Qwik should provide a mechanism for specifying what attributes should be assigned to the host element in general?

**Comment by manucorporat** [comment]
there is no host element

**Comment by petebacondarwin** [comment]
> i imagine we could provide this as well:
> 
> ```tsx
> import { component$, useStyles$, useStylesScoped$ } from '@builder.io/qwik';
> 
> export const App = component$(() => {
>   const {classes} = useStylesScoped$(`.redcolor { color: red }`);
>   return <p>Hello <Name class={classes.redcolor} /> !</p>;
> });
> 
> export const Name = component$((props: {class:string}) => {
>   return <span class={props.class}>PETE</span>
> });
> ```

Oh I misunderstood your suggestion. This is using CSS modules to pass the style in?

**Comment by literalpie** [comment]
May I suggest renaming the issue to something like "allow including style scope when passing class to child component"?

**Comment by anasalaqeel** [comment]
wow 1year and this issue is still not resolved!! I will re-think again about using Qwik

**Comment by wmertens** [comment]
Hmm, here's [an updated playground](https://qwik.builder.io/playground/#v=1.2.14&f=Q0o0JubG2BKNDlJdhcSG1lU6YHd5AiM9M684M9k1JxVSMBOR0iAh45kHrClT4WFjA2oNAN1HVHLEqDgT9IpSU3ST83Pyi8B%2BANJWwKBOUahNAHoXSQNIaXpRamqeLrDEAFVF1QoQhpUCsLTNTFEwLACWiSAFMK3oSd8G4nB9Oxs%2FUEkLbgXZKiGsRzZdSd9OQRGRT1ADAKzdFsmDNlhDNFodFDLqsXYa4HYXeo4EN6Kq9fT0wLK1dgGuIa42%2BiBRu9G8OUTzJgA). When you inspect the HTML output, you can see that the `<p>` and `<Inline />` components got the extra class but the `<Name/>` didn't.

```html
  <body>
    <!--qv q:sstyle=⭐️olukuv-0 q:id=0 q:key=Ncbm:0t_0--><style
      q:style="olukuv-0"
      hidden
    >
      .red-color.⭐️olukuv-0 { color: red }</style
    ><style q:style="o74rpj-1" hidden>
      .green-border { border: solid 1px green }
    </style>
    <p class="⭐️olukuv-0" q:key="4e_3">
      Hello
      <!--qv q:key=4e_1--><span class="⭐️olukuv-0" q:key="4e_0"></span
      ><!--/qv--><!--qv q:id=1 q:key=jGuP:4e_2--><span
        class="red-color green-border"
        q:key="4e_4"
        >PETE</span
      ><!--/qv-->
      !
    </p>
    <!--/qv-->
  </body>
```

The difference is that `Name` is a Qwik component, which is rendered slightly differently, in a new qwikContext, and it's not inheriting the `⭐️olukuv-0` class. I'm not sure if this is intentional or a bug.

Current behavior is as follows:
1. generate scopeId
2. convert the given css so each selector requires scopeId class
3. give all plain elements the scopeId as a class. Qwik components don't get the class, they start a new scope

The behavior you would like changes step 3 to pass the scopeId as a class _to the entire subtree_. So if you use scoped styles in root, every dom element under root will have the extra class of root's scopeId.

Is that good or bad? I'm not sure, but it "feels" like that's not a great idea.

Anyway, I'm personally not a fan of scoped styles, I think modular or atomic styles are better. For modular styles you can use `.module.css` imports or use Vanilla Extract, and for atomic styles you can use Tailwind CSS, UnoCSS, or PandaCSS.

**Comment by genki** [comment]
Now we can do like this:

```ts
export default component$(() => {
  const {scopeId} = useStylesScoped(styles);
  //...
  return (
    <SomeComponent class={scopeId} />
  );
});
```

**Comment by wmertens** [comment]
@genki so basically, this is the situation, right?

@petebacondarwin does that work for you?

**Comment by petebacondarwin** [comment]
So the idea is that you get get something back from the call to `useStyledScoped$()` that can be used to get access to those styles elsewhere? If so, then I think that is good enough for my case.

**Comment by wmertens** [comment]
@petebacondarwin ok when you verified that it works for you, can you close the issue? You can try it in the playground.

**Comment by petebacondarwin** [comment]
Sadly this doesn't seem to be enough. The `scopeId` is just a string that can be used to compute the "scope" of the styles of a component. I can't work out how to use this id to apply styles to a child component.

**Comment by wmertens** [comment]
@petebacondarwin seems to work for me?

**Comment by petebacondarwin** [comment]
Fair enough. Thank you for bearing with me. Happy to close this.
