### ISSUE TITLE
Stackblitz CodeflowApp Bot

### ISSUE THREAD

**Issue by reemardelarosa** [BuilderIO/qwik#1711]
### Is your feature request related to a problem?

This will improve DX Workflow.

https://www.youtube.com/watch?v=Ea1zJD5uQRg
https://stackblitz.com/codeflow

### Describe the solution you'd like

CodeflowApp is a friendly bot, which provides a one-click link that spins up the whole environment for pull requests and issues. No more context-switching or branch-checkouts, just a new browser tab with a full IDE and a dev server running.

![image](https://user-images.githubusercontent.com/4918140/195581745-8dfca1f9-2dcd-4f6a-b7aa-705f3627f8fa.png)

To integrate the bot, please follow the instructions on [Integrating CodeflowApp bot](https://developer.stackblitz.com/codeflow/integrating-codeflowapp-bot).

### Describe alternatives you've considered

Install the [CodeflowApp](https://stackblitz.com/install-github-app?installation_id=30172759&setup_action=install) bot to Github

**Comment by shairez** [comment]
Thanks @reemardelarosa 

Great minds...  I already integrated the bot with the repo, just waiting for @mhevery 's approval in the settings

**Comment by mhevery** [comment]
I think I pushed the right buttons.

**Comment by sylwiavargas** [comment]
Just popping in to say "hi" 💙 Thank you for considering CodeflowApp bot. If you have any feedback, ideas, frustrations, or wishes - my team and I would love to hear them all!

Feel free to reach out [on Twitter](www.twitter.com/sylwiavargas), too!

**Comment by reemardelarosa** [comment]
@sylwiavargas we are having an issue running the qwik repo. Please check https://github.com/stackblitz/webcontainer-core/issues/839.

**Comment by sylwiavargas** [comment]
Right - I noticed it after I commented and wanted to run the repo myself.
I've already pinged the team. I'll provide you with an update or an ETA tomorrow.

Thank you for creating the issue too!

**Comment by sylwiavargas** [comment]
Hello everyone! Happy Monday! ✨
I checked in with our team and we identified the problem and a solution. 

Your repository uses Yarn Berry which is not supported by WebContainers. A solution to consider would be to switch to npm or pnpm (which would also bring the benefit of [speed](https://pnpm.io/benchmarks) ⚡️ If you’d like to consider this switch, there are two steps you’d need to take:

1. remove `workspaces` from `package.json` and put that into a `pnpm-workspace.yaml`
2. configure node-linker in a `.npmrc` and set it to `hoisted` (that should be equal to their current linker they use for Yarn Berry)

I see more and more frameworks switching to pnpm - as an example, Nuxt did so recently (https://github.com/nuxt/framework/discussions/939).

I also want to be perfectly transparent about that the Rust parts of your repo won’t run but you could still use Codeflow to run anything JS / WASM based and review PRs, code, or inspect issues 🙂

Meanwhile, **please reach out whenever there’s something I can help you with**! I know that Dominic Elm is about to respond on the issue so please feel free to ask him about anything technical, too 🙂
