### ISSUE TITLE
useClientEffect$ in custom hook breaks

### ISSUE THREAD

**Issue by ryanhair** [BuilderIO/qwik#1717]
### Qwik Version

0.10.0

### Operating System (or Browser)

MacOS 12.6 - Chrome 106.0.5249.103

### Node Version (if applicable)

v16.13.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Using a custom hook that wraps `useClientEffect$` multiple times would each work independently

In the below example:

1) I expect the first "false" to change to "true" after .5 seconds
2) I expect the second "false" to change to "true" after 1 second

```jsx
import { component$, useClientEffect$, useSignal } from "@builder.io/qwik";

export function wait(duration: number) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(null);
    }, duration);
  });
}

export function useDelay(duration: number) {
  const ready = useSignal(false);
  useClientEffect$(async () => {
    console.log(`delaying for ${duration}`);
    wait(duration).then(() => (ready.value = true));
  });
  return ready;
}

export default component$(() => {
  const val1 = useDelay(500);
  const val2 = useDelay(1000);

  return (
    <>
      <div>{val1.value}</div>
      <div>{val2.value}</div>
    </>
  );
});
```

### Actual Behaviour

The two uses of the custom hook end up conflated, and the behavior isn't correct.

1) The first does _not_ change after .5 seconds
2) The second changes after 1 second

```jsx
import { component$, useClientEffect$, useSignal } from "@builder.io/qwik";

export function wait(duration: number) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(null);
    }, duration);
  });
}

export function useDelay(duration: number) {
  const ready = useSignal(false);
  useClientEffect$(async () => {
    console.log(`delaying for ${duration}`);
    wait(duration).then(() => (ready.value = true));
  });
  return ready;
}

export default component$(() => {
  const val1 = useDelay(500);
  const val2 = useDelay(1000);

  return (
    <>
      <div>{val1.value}</div>
      <div>{val2.value}</div>
    </>
  );
});
```

### Additional Information

Using two separate `useClientEffect$`s in the component directly works as expected, as does having a single `useClientEffect$` that does the work of changing both values

**Comment by ryanhair** [comment]
Got the qwik version wrong 🤦. Just updated it

**Comment by JorgeVV** [comment]
Same bug in version 0.11.0. [Playground](https://qwik.builder.io/playground#version=0.11.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlQ2xpZW50RWZmZWN0JTI0JTJDJTIwdXNlU2lnbmFsJTIwJTdEJTIwZnJvbSUyMCU1QyUyMiU0MGJ1aWxkZXIuaW8lMkZxd2lrJTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMHdhaXQoZHVyYXRpb24lM0ElMjBudW1iZXIpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMG5ldyUyMFByb21pc2UoKHJlc29sdmUpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHNldFRpbWVvdXQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmVzb2x2ZShudWxsKSUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlMkMlMjBkdXJhdGlvbiklM0IlNUNuJTIwJTIwJTdEKSUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwdXNlRGVsYXkoZHVyYXRpb24lM0ElMjBudW1iZXIpJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwcmVhZHklMjAlM0QlMjB1c2VTaWduYWwoZmFsc2UpJTNCJTVDbiUyMCUyMHVzZUNsaWVudEVmZmVjdCUyNChhc3luYyUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCU2MGRlbGF5aW5nJTIwZm9yJTIwJTI0JTdCZHVyYXRpb24lN0QlNjApJTNCJTVDbiUyMCUyMCUyMCUyMHdhaXQoZHVyYXRpb24pLnRoZW4oKCklMjAlM0QlM0UlMjAocmVhZHkudmFsdWUlMjAlM0QlMjB0cnVlKSklM0IlNUNuJTIwJTIwJTdEKSUzQiU1Q24lMjAlMjByZXR1cm4lMjByZWFkeSUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwdmFsMSUyMCUzRCUyMHVzZURlbGF5KDUwMCklM0IlNUNuJTIwJTIwY29uc3QlMjB2YWwyJTIwJTNEJTIwdXNlRGVsYXkoMTAwMCklM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2RpdiUzRSU3QnZhbDEudmFsdWUlN0QlM0MlMkZkaXYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDZGl2JTNFJTdCdmFsMi52YWx1ZSU3RCUzQyUyRmRpdiUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkYlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QpJTNCJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFwcCUyMCU3RCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE)
