### ISSUE TITLE
useSignal does not seem to work for nested objects and arrays (unlike useStore with `{recursive: true}`)

### ISSUE THREAD

**Issue by ramkumarkb** [BuilderIO/qwik#1729]
### Qwik Version

0.11.0

### Operating System (or Browser)

Mac OS 10.15.7 (Catalina) 

### Node Version (if applicable)

16.13.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

`useSignal` does not seem to work for Arrays and nested Objects. However, `useStore` works as it has the `{recursive: true}` and it able to track changes across nested objects and arrays.

### Actual Behaviour

`useSignal` seems to work only for simple values. 

### Additional Information

Gist (with `useStore`)  that works vs  Gist (with `useSignal`) that does not seem work - 

https://gist.github.com/ramkumarkb/d02ee17d559cffe948d8e61b4879733b

**Comment by manucorporat** [comment]
useSignal() is not recursive, and it wont be, only track if signal.value changes, not a tested properties. Use `useStore() + recursive`

**Comment by shairez** [comment]
TODO: add this to the docs
