### ISSUE TITLE
useOn() multi-string conditional parameters?

### ISSUE THREAD

**Issue by neuro-bro** [BuilderIO/qwik#1731]
The following appears to not work. 

It would be good to allow this functionality to reduce boilerplate (multiple useOn's)

```
  useOn(
    "mouseenter" || "mouseleave",
    $((event) => handleNavbarHovered(event))
  );
```

**Comment by manucorporat** [comment]
```tsx
  useOn(
    ["mouseenter", "mouseleave"],
    $((event) => handleNavbarHovered(event))
  );
```

using the OR operator would never work, but it could be implemented with an array

**Comment by mmarkelov** [comment]
> ```tsx
>   useOn(
>     ["mouseenter", "mouseleave"],
>     $((event) => handleNavbarHovered(event))
>   );
> ```
> 
> using the OR operator would never work, but it could be implemented with an array

I can implement this, but is this is really needed one? I'm not sure that there are much cases for this thing

**Comment by manucorporat** [comment]
This was recently implemented in the latest release of Qwik!
