### ISSUE TITLE
[DOCS] Example monaco editor suggestion is weird

### ISSUE THREAD

**Issue by JiaWei-Hong** [BuilderIO/qwik#1732]
I found in [docs](https://qwik.builder.io/examples/introduction/hello-world/) Monaco Editor suggestion position is weird and in the small window, it cannot show suggestions.

Like this:
![image](https://user-images.githubusercontent.com/32186630/195914838-036fb638-571b-49ef-97cc-a6f745834abd.png)
![image](https://user-images.githubusercontent.com/32186630/195914479-29a6192f-e36a-46d0-9256-e870122b9f24.png)

Refer to the playground Behavior:
![image](https://user-images.githubusercontent.com/32186630/195914928-6d113398-13aa-4579-9283-aa06ba1e57be.png)
![image](https://user-images.githubusercontent.com/32186630/195914962-5cd201cb-747e-4bfa-bc80-dac5424cfcd3.png)

# Solution
I think it can remove [File](https://github.com/BuilderIO/qwik/blob/main/packages/docs/src/repl/monaco.tsx#L307) L307 to reach fix Monaco Editor suggestion position.

**Comment by shairez** [comment]
Thanks @JiaWei-Hong !

Can you please try it and if it works issue a PR?

**Comment by JiaWei-Hong** [comment]
> Thanks @JiaWei-Hong !
> 
> Can you please try it and if it works issue a PR?

Sure!
I will fix on this
