### ISSUE TITLE
Store in Context is not working as expected..

### ISSUE THREAD

**Issue by gomolsoft** [BuilderIO/qwik#1742]
### Qwik Version

0.11.0

### Operating System (or Browser)

Chrome/Safari/Firefox

### Node Version (if applicable)

16.x.x

### Which component is affected?

Qwik Runtime

### Expected Behaviour

When I press the "Increment" button, the increment should be displayed everywhere.

https://stackblitz.com/edit/qwik-starter-c9e4mb?file=src/components/router-head/router-head.tsx

### Actual Behaviour

The app returns an error "**Uncaught (in promise) Error: close not found**". 

### Additional Information

However, if I comment out the < div > in line 49 in the module "router-head", then the app works as intended.

**Comment by manucorporat** [comment]
It's not possible to render a `<div>` inside a `<head>`, it's impossible to render that in HTML. Agreed the error is confusing, we will work on it, but it's hard to detect before it happens!
