### ISSUE TITLE
Understanding dynamic tree shaking

### ISSUE THREAD

**Issue by GuyDev1** [BuilderIO/qwik#1743]
Hey,
I just finished going over the tutorial - https://github.com/BuilderIO/qwik/tree/main/packages/docs/src/routes/tutorial/understanding/treeshaking 

I fail to see a difference in the HTML/Symbols/client bundles when removing the reference to the store in the child component.
Am I missing something? are there other ways to really see the benefit of dynamic tree shaking in that example?

Thank you :)

**Comment by wmertens** [comment]
seems ok now
