### ISSUE TITLE
Have a `useUnmount` hook 

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#1752]
### Is your feature request related to a problem?

I would like to start listening on server-side changes (websocket) when a component is mounted and stop listening when the component is unmounted : 
```typescript
export const default component$(() => {
  const state = useStore({ data: undefined });
  useMount$(() => {
    addServerEventListener('event', (data) => state.data = data); // event listener won't be removed
  });
  if (!state.data) return <p>Loading</p>
  return <p>{data.whatever}</p>
})
```

### Describe the solution you'd like

create a useUnmount$ hook :
```typescript
export const default component$(() => {
  const state = useStore({ data: undefined });
  const listener = noSerialize((data) => state.data = data);
  useMount$(() => {
    addServerEventListener('event', listener);
  });
  useUnmount$(() => {
    removeServerEventListener('event', listener);
  })
  if (!state.data) return <p>Loading</p>
  return <p>{data.whatever}</p>
})
```

### Describe alternatives you've considered

Provide a callback in the `useMount` that would be trigger on unmount:
```typescript
export const default component$(() => {
  const state = useStore({ data: undefined });
  useMount$(() => {
    const listener = (data) => state.data = data;
    addServerEventListener('event', listener );
    return () => removeServerEventListener('event', listener);
  });
  if (!state.data) return <p>Loading</p>
  return <p>{data.whatever}</p>
})
```

### Additional context

This feature could also be used to keep count of all the listeners with an app-wide context: 
```typescript
export const default component$(() => {
  // State is in sync with server while there is at least one listener
  const { state, addListener, removeListener } = useContext(AppState);
  useMount$(() => {
    addListener('event');  // Increment appstate counter
    return () => removeListener('event'); // decrement appstate counter
  });
  if (!state.data) return <p>Loading</p>
  return <p>{data.whatever}</p>
})
```

**Comment by manucorporat** [comment]
I would use `useWatch`:

```tsx
  useWatch$(() => {
    addListener('event'); 
    return () => removeListener('event');
  });
```

**Comment by manucorporat** [comment]
but in order to add events, you can use `useOn()` method

**Comment by GrandSchtroumpf** [comment]
@manucorporat `useWatch$` without tracking any store works perfectly thanks. Reading the doc I thought `useWatch` was only used to cleanup after store changes, I didn't realize it would also trigger when component unmount.
Thanks !

**Comment by barbalex** [comment]
> I would use useWatch

Where is that documented? And how can it be imported?

**Comment by GrandSchtroumpf** [comment]
@barbalex useWatch has been deprecated: https://qwik.builder.io/docs/deprecated-features/
You can use `useTask$` or `useVisibleTask$` depending on your usecase

**Comment by barbalex** [comment]
The use case is: If the user forgets to save a dirty form and navigates away, I wan't to detect the unmount and then programmatically save the form data. Seems to me that useTask and useVisibleTask can not detect unmounting?

**Comment by GrandSchtroumpf** [comment]
You can use useTask$ like that then:
```jsx
useTask$(() => {
  return () => saveForm();
})
```
Or alternatively with the [cleanup function](https://qwik.builder.io/docs/components/tasks/#cleanup) : 
```jsx
useTask$(({ cleanup }) => {
  cleanup(() => saveForm());
})
```
As far as I understand, it's the same

**Comment by barbalex** [comment]
When I do:

```js
useTask$(({ cleanup }) => {
    cleanup(() => console.log('unmounting event form'))
  })
```

it only logs on mounting.

**Comment by barbalex** [comment]
o.k., seems that my dev setup does not update correctly.
After manually re-starting it works.

@GrandSchtroumpf  Thanks a lot!
