### ISSUE TITLE
Implement early detection of invalid HTML

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#1794]
### Is your feature request related to a problem?

yes! many times developers write invalid HTML, like including a `<div>` inside a `<p>`, it would be nice to describe this rules in the SSR render, so when we walk the JSX tree we can error early explaning where the issue belong.

### Describe the solution you'd like

- Collect all the HTML rules relevant
- Encode the rules in a way we can query during SSR (in dev mode)
- Print errors

### Describe alternatives you've considered

- Eslint rule that detect this at compiler time
- Add this rules to the qwik optimizer (possible but out of scope)

**Comment by manucorporat** [comment]
Basically the problem to solve is while walking the JSX tree:
detect invalid conditions like:
`div` contained inside a `p`

**Comment by wmertens** [comment]
In the case when Qwik is expecting an element that's missing, that could be a quick check plus an error like "Expected element missing, you probably have invalid HTML, see some_url"

**Comment by wmertens** [comment]
For eslint, there's a plugin that calls markuplint, which does check permitted content https://github.com/un-ts/eslint/tree/main/packages/markup

**Comment by wmertens** [comment]
For eslint, there's a plugin that calls markuplint, which does check permitted content https://github.com/un-ts/eslint/tree/main/packages/markup

**Comment by manucorporat** [comment]
Tried to use eslint-markup but doesnt seem to do anything or detect anything...

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/issues/1794
