### ISSUE TITLE
Todo app is broken

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [BuilderIO/qwik#18]
Great work on this new framework!
As mentioned on discord, i've experienced the buggy active state as well:

When you use the `Clear completed` button in the qwik-todo-demo on Stackblitz, i'm getting the following behaviour: 
- the active item(s) are cleared (good, as expected)
- whenever an active item _position_ remains in the list, the checkbox remains checked
- in the latter case, when you deactivate/activate the item, the `Clear completed` button is not showing up
- only if you add more new items than the previous cleared list the `Clear completed` button returns

After setting up locally and playing a bit more, i'm experiencing more issues with the todo app:
- the items left count is messed up after you've cleared the list. The counter increases when you try to deactivate the magically activated item (see above), which increases the count for no good reason. 
- the `Active` and `Completed` buttons no longer work and result in an console error: `qwikloader.ts:62 Uncaught (in promise) TypeError: Failed to resolve module specifier 'qwik.js' at HTMLDocument.processEvent`.
- Actually, the `Active` and `Completed` buttons  do not seem to work either way.

**Comment by nartc** [comment]
Here's the GIF of the issue 
![qwik-todo-bug](https://user-images.githubusercontent.com/25516557/123271374-60592480-d4c6-11eb-86d6-8a35c443fd71.gif)

**Comment by mhevery** [comment]
Thanks for the nice write up. We will get to it soon.
