### ISSUE TITLE
<svg> import from /public

### ISSUE THREAD

**Issue by neuro-bro** [BuilderIO/qwik#1806]
### Is your feature request related to a problem?

Is there a good way to import SVG from public folder and render as svg element? 

### Describe the solution you'd like

Don't want to use and wrap a react library with qwik-react. 

Don't want to have to create an exported function like the Qwik starter project <Logo> example.

Need to be able to access the actual svg.class directly to add things like tailwind classes so cant use img.src or object, etc.

### Describe alternatives you've considered

img.src 

object

vite plugins but most use React stuff which I don't want due to additional bloat/wrappers

**Comment by BerndWessels** [comment]
In React you can do this
```jsx
import React from 'react';
import {ReactComponent as Icons} from './icons.svg';

const App = () => {
  return (
    <div className="App">
      <Icons>
        <use href="#users"></use>
      </Icons>
    </div>
  );
}
export default App;
```

But I can't figure out how to make it work in Qwik.

**Comment by jawkob** [comment]
A bit late to the party, but how about using `?jsx` postfix on import path?
For example:
```
import Icon from "/public/icons/icon.svg?jsx";
```

Then use the imported svg directly as a component in code:
```
<Icon />
```
and apply classes directly to this component:
```
<Icon class="color-red-700" />
```

**Comment by gioboa** [comment]
[Responsive Image feature](https://qwik.builder.io/docs/integrations/image-optimization/#responsive-images) solved this specific issue.
