### ISSUE TITLE
Variables are not correctly hoisted in Qwik's lexical scope

### ISSUE THREAD

**Issue by dario-piotrowicz** [BuilderIO/qwik#1807]
### Qwik Version
0.11.1

### Which component is affected?

Qwik Optimizer (rust) (I think)

### Expected Behaviour

In javascripts variables get hoisted, so in my components I would expect to be able to access variables in any part of the code as long as they belong to the same scope, see this [simple react example](https://stackblitz.com/edit/react-ts-aeqrcb?file=App.tsx).

There the `decreaseCounter` function can access the `counter` (and also the `setCounter`) variable because it is being hoisted.

### Actual Behaviour

It seems like Qwik doesn't apply such hoisting causing runtime errors, for example see this analogous [qwik example](https://qwik.builder.io/playground#version=0.11.1&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwJTI0JTJDJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTVDbiUyMCUyMGNvbnN0JTIwZGVjcmVhc2VDb3VudGVyJTIwJTNEJTIwJTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHN0YXRlLmNvdW50ZXItLSUzQiU1Q24lMjAlMjAlN0QpJTVDbiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCJTVDbiUyMCUyMCUyMCUyMGNvdW50ZXIlM0ElMjAwJTVDbiUyMCUyMCU3RCklM0IlNUNuJTVDbiUyMCUyMGNvbnN0JTIwaW5jcmVhc2VDb3VudGVyJTIwJTNEJTIwJTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHN0YXRlLmNvdW50ZXIlMkIlMkIlM0IlNUNuJTIwJTIwJTdEKSU1Q24lNUNuJTVDbiUyMCUyMHJldHVybiUyMCUzQ2RpdiUzRSU1Q24lMjAlMjAlM0NidXR0b24lMjBvbkNsaWNrJTI0JTNEJTdCZGVjcmVhc2VDb3VudGVyJTdEJTNFLSUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlM0NzcGFuJTNFJTIwJTdCc3RhdGUuY291bnRlciU3RCUyMCUzQyUyRnNwYW4lM0UlNUNuJTIwJTIwJTNDYnV0dG9uJTIwb25DbGljayUyNCUzRCU3QmluY3JlYXNlQ291bnRlciU3RCUzRSUyQiUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlM0MlMkZkaXYlM0UlM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwQXBwJTIwJTdEJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NodG1sJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

Here the `decreaseCounter` function fails to recognize the `state` reference causing a runtime error:
![Screenshot 2022-10-19 at 22 11 12](https://user-images.githubusercontent.com/61631103/196805175-8e820f8d-375f-48d9-9934-64825a2564bb.png)

### Additional Information

I am not sure if this is a bug or a feature request, sorry if I picked the wrong option for the issue

Anyways I think that javascript developers are very used and familiar with the hoisting of variables and that if possible Qwik should provide the same sort of behaviour.

This also generates contraints/hinderances to the developers which are forced to order their code in a particular way in order to have it correctly working.

**Comment by manucorporat** [comment]
The code you passes it is using the variable before it's declared

**Comment by dario-piotrowicz** [comment]
Hi @manucorporat , the variable is being referenced before it's declaration/initialization, but it is not being used right away (so it's not in the temporal dead zone) so I would expect it to being hoisted in the same way standard javascript does.

Please check out the react example to see what I mean, there the `counter` variable is also being referenced before it's declaration, but there everything works totally fine.

And I find this a to be a valuable behaviour which allows me to order my code in any logical way I want instead of having to carefully move code around so that the order follows the various code dependencies.

**Comment by dario-piotrowicz** [comment]
I see, that's too bad 😢

Thank you very much for the explanation 🙂 

Let me know if we should just close this issue, keep it for reference or also add something regarding this in the docs.

**Comment by manucorporat** [comment]
yeah, i will keep it open, i think it's good to document this

**Comment by petebacondarwin** [comment]
@manucorporat - one option would be to move the dependency array into a function that is called later.
I.e. instead of:

```ts
const increaseCounter = qrlDEV(
  () => import('./app_component_increasecounter_ho3zdspwjzs.js'),
  "App_component_increaseCounter_Ho3zDspwJzs",
  {...},
  [ state ]
);```

it could be 

```ts
const increaseCounter = qrlDEV(
  () => import('./app_component_increasecounter_ho3zdspwjzs.js'),
  "App_component_increaseCounter_Ho3zDspwJzs",
  {...},
  () => [ state ]
);
```

Note the last parameter.

**Comment by manucorporat** [comment]
we will

**Comment by petebacondarwin** [comment]
@manucorporat - was this closed as resolved or not planned?
