### ISSUE TITLE
[DOCS/BUG] '/' should not open the search whilst editing the code in the playground

### ISSUE THREAD

**Issue by dario-piotrowicz** [BuilderIO/qwik#1829]
In the docs if you press the `/` key the search modal opens, but I think this shouldn't happen in the playground since it make closing jsx tags a real chore:
![Kapture 2022-10-21 at 10 47 59](https://user-images.githubusercontent.com/61631103/197167621-693c902b-967a-42d4-85ab-8e25f079efbb.gif)

**Comment by ptu14** [comment]
fixed in #1921
