### ISSUE TITLE
Support for third party or inbuilt State sharing between components like global state like redux or sharing state like zustand

### ISSUE THREAD

**Issue by Suryasai130499** [BuilderIO/qwik#1834]
## Feature Request

I'm frustrated to send the state as the props to the children and sometimes the parent needs to be updated by the changes in children, then we need to create a context in children and pass it to parent. **This is too hectic.**

## Something similar to Redux or Zustand

global state like redux
sharing state like zustand

### Describe alternatives you've considered

Redux and Zustand as the examples

**Comment by tuurbo** [comment]
Sounds like your looking for https://qwik.builder.io/docs/components/context/

**Comment by LoKy-dev** [comment]
Yes, but it could be really nice to support implementations of third party state managers.
Also to take advantage of libraries features, for example, I heavily rely on @rtk/query for data fetching.

If this will be implemented in qwik with hook like features like it is for React, qwik will become a no-brainer.

Yes, i know that you can use the qwickcity [integration](https://qwik.builder.io/qwikcity/integrations/react/) to run react code but it feels wrong 😬

**Comment by sakulstra** [comment]
Can't you in theory just inject https://github.com/pmndrs/zustand#using-zustand-without-react into a qwik context?

**Comment by shairez** [comment]
Currently the only way to share state globally is to use context on the root level like @tuurbo mentioned 

The constraint is that it needs to be attached to the DOM, so context on the root component is the way to set up dependency injection that can be shared between all components. 

In the next few months we'll try to discover patterns of state management that are no-brainer in terms of DX
Redux etc could be integrated via context as @sakulstra mentioned, but IMO not necessary in a reactive framework like Qwik. 

I'm closing this for now, if you have a suggestion about how to do it in a different solution, please re-open

Thanks again for the issue @Suryasai130499 !

**Comment by wmertens** [comment]
BTW, since this was written, the easy way to do writeable state sharing between parent and child is to pass signals. Convention is to name those props `bind:x`.

for example:

```tsx
import { component$, useSignal, Slot, type Signal } from '@builder.io/qwik';

const Child = component$<{ "bind:count": Signal<number> }>(({ "bind:count": count }) =>
  <button onClick$={() => count.value++}>
    Click me! Slot: <Slot />
  </button>
)

const Parent = component$(() => {
  const count = useSignal(0)
  return <Child bind:count={count}>Count is {count.value}</Child>
})

export default () => <Parent />
```

https://qwik.dev/playground/#f=Q0o0JsDow5JodBC1r44CKElDYw0ihDdJQfwOKTptkYy0qVZQSgImeitwaa5kBTXLBlJj2CnU2mlooCuBFPy1oAAEOt4G0ghB1L3VkKAFq9IDZs3SVG3tWoh3wSoUclMVwa63UrABUZCQgTdmuDRhrg1IBKYCUFxhzQAQNRC32CICRsNAEyl3QDyMcL1tNZiqtXMG6wOWdRABiDtrbfTBGuyAeQgj7UJstoE6Cujm0Tw29PIYAA
