### ISSUE TITLE
Always get 404 Not Found when request to the page using curl

### ISSUE THREAD

**Issue by doggy8088** [BuilderIO/qwik#1842]
### Qwik Version

0.11.1

### Operating System (or Browser)

Windows 10

### Node Version (if applicable)

v16.18.0

### Which component is affected?

Starters / CLI

### Expected Behaviour

It should return HTML by default.

### Actual Behaviour

It return HTTP 404.

### Additional Information

This is confusing. By default, curl should get HTML page successfully by default.

![image](https://user-images.githubusercontent.com/88981/197334153-fe3d722f-8882-4709-901d-e4393fbc2748.png)

Qwik starter's node server handle `Accept: */*` incorrectly.

![image](https://user-images.githubusercontent.com/88981/197334204-9d0fe929-5064-43d7-b75e-1380c5bed136.png)

Qwik starter's node server handle `Accept: text/html` correctly.

![image](https://user-images.githubusercontent.com/88981/197334210-9387b855-ca26-462b-899d-25a8480bc61c.png)

**Comment by zanettin** [comment]
confirmed on `0.19.2` / `0.4.0`

**Comment by gioboa** [comment]
With `1.2.9` works with `Accept: */*` 
I tested:
- `preview` mode with Vite
- express adapter

With `dev mode` is not working but you know, dev mode is a special mode for development only.
