### ISSUE TITLE
[DOCS] Typo in qwik/packages/docs/src/routes/docs/components/lifecycle/diagram2.svg

### ISSUE THREAD

**Issue by Oskar-Nilsen-Roos** [BuilderIO/qwik#1850]
**How can the documentation be improved?**

In use-cases box bottom left:
* Read DOM ~necesary~ -> Read DOM necessary
* Perform computation ~eagarly~ in the ~broswe~ -> Perform computation eagerly in the browser

Would make a pull request with changed SVG but seemed difficult when you don't have the file it was generated from

**Comment by shairez** [comment]
Thanks for the report @Oskar-Nilsen-Roos !

I think @manucorporat or @mhevery have the source
