### ISSUE TITLE
Sass attribute selctor does not compile

### ISSUE THREAD

**Issue by danielcasler** [BuilderIO/qwik#1858]
### Qwik Version

0.11.1

### Operating System (or Browser)

Firefox/Chrome

### Node Version (if applicable)

18.11.0

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behavior

I installed Sass using the following instructions. https://vitejs.dev/guide/features.html#css-pre-processors 

Everything has been working fine up until today when I created a simple attribute selector written in scss. The attribute selector is completely ignored.

```
[class^='col-'] {
    float: left;

    &:not(:last-child) {
        margin-right: $gutter-horizontal;
    }
}
```

I would have expected an output such as: 

```.row {
  max-width: 114rem;
  margin: 0 auto; }
  .row:not(:last-child) {
    margin-bottom: 8rem; }
  .row::after {
    content: "";
    display: table;
    clear: both; }
  .row [class^="col-"] {
    float: left; }
    .row [class^="col-"]:not(:last-child) {
      margin-right: 6rem; }
  .row .col-1-of-2 {
    width: calc((100% - 6rem) / 2); }
  .row .col-1-of-3 {
    width: calc((100% - 2 * 6rem) / 3); }
  .row .col-2-of-3 {
    width: calc(2 * ((100% - 2 * 6rem) / 3) + 6rem); }
  .row .col-1-of-4 {
    width: calc((100% - 3 * 6rem) / 4); }
  .row .col-2-of-4 {
    width: calc(2 * ((100% - 3 * 6rem) / 4) + 6rem); }
  .row .col-3-of-4 {
    width: calc(3 * ((100% - 3 * 6rem) / 4) + 2 * 6rem); }
```

As indicated above, it seems that attribute selectors are being ignored entirely.

### Actual Behavior

The actual output is:

```
.row .col-1-of-2 {
    width: calc((100% - 6rem) / 2);
}
```

### Additional Information

I used the exact same steps to add Sass to a SvelteKit project and the attribute selector worked fine. Same code.

**Comment by manucorporat** [comment]
We have a fix for sass in main, not an user of Sass, but i think it should fix it. We will release likely today, so hold on!

**Comment by danielcasler** [comment]
Cheers, thanks!
