### ISSUE TITLE
MDX / SSR can't load a component?

### ISSUE THREAD

**Issue by reggi** [BuilderIO/qwik#1859]
### Qwik Version

0.11.1

### Operating System (or Browser)

Mac / Chrome

### Node Version (if applicable)

16.15.0

### Which component is affected?

Qwik City

### Expected Behaviour

I'd expect a component that uses a `useResource$` to be able to be rendered in MDX and use SSR.

I took this example from the docs: https://qwik.builder.io/tutorial/reactivity/resource/
I created a `widgets` called `github` and tried to use it in an MDX file.

```mdx
import Github from '../../widgets/github'

Hello world! 

The goal of this doc is for it to have a component that uses `useResource$` to fetch some data.

<Github/>
```

### Actual Behaviour

```
failed to load module for ssr: ../../widgets/github
    at instantiateModule (file:///Users/thomasreggi/Desktop/widget-qwik/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:53365:15
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

<img width="1003" alt="Screen Shot 2022-10-24 at 12 55 19 AM" src="https://user-images.githubusercontent.com/296798/197451685-10bed599-1ab1-4c9e-be15-ff16221e26b9.png">

**Comment by reggi** [comment]
I actually have trouble getting any component to work inside MDX 🤔

**Comment by manucorporat** [comment]
maybe the path is incorrect? i cant help without seeing the repo case

**Comment by nnelgxorz** [comment]
Does your .tsconfig have a path alias set up for src? Something like 

```typescript
{
 // Other stuff...
  "paths": {
      "~/*": [
        "./src/*"
      ]
}
```
If so, try changing your import to `~/widgets/github`. That will make it easier to see if it's a path issue.

**Comment by reggi** [comment]
Yep was a path issue, thanks for the help.
