### ISSUE TITLE
Add the first Youtube Tutorial in Portuguese about Qwik

### ISSUE THREAD

**Issue by LuisFilipePedroso** [BuilderIO/qwik#1870]
Hey folks, to help grow the Qwik community, I recorded a video tutorial for my Youtube Channel and would like to add it to the media page.
The PR is:  #1862

**Comment by shairez** [comment]
Thanks @LuisFilipePedroso !

I replied on that PR so I'm closing this issue and we can continue the discussion there

Thanks again and keep up the great work!
