### ISSUE TITLE
[DOCS] Translate Doc to  Traditional Chinese 

### ISSUE THREAD

**Issue by kai890707** [BuilderIO/qwik#1879]
Hi , Qwik !
I want to translate the document into Traditional Chinese .  
Can I send a PR ?

**Comment by zanettin** [comment]
thanks a lot 🙏 maybe you can join this discussion over [here](https://github.com/BuilderIO/qwik/issues/1357)

**Comment by kai890707** [comment]
Thanks , I will start doing  :D

**Comment by nsdonato** [comment]
@zanettin @zanettin are these problems related?  https://github.com/BuilderIO/qwik/issues/1523 I ask in case they are duplicated to keep only one 😊

**Comment by zanettin** [comment]
yes looks like the same offer 🙏 the docs still don't provide a way to be translated atm 😢 will ping u when something changes in that regard

**Comment by nsdonato** [comment]
@zanettin Since they are duplicated, couldn't one be closed?  😇
