### ISSUE TITLE
Build TS typing error with partytown

### ISSUE THREAD

**Issue by cptflammin** [BuilderIO/qwik#1881]
### Qwik Version

0.11.1

### Operating System (or Browser)

Mac OS

### Node Version (if applicable)

16.14.2

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Build successful

### Actual Behaviour

TS typing error when building frontend

```
✓ Built client modules

src/components/partytown/partytown.tsx:18:18 - error TS2322: Type 'boolean' is not assignable to type 'string'.

18   return <script dangerouslySetInnerHTML>{innerHTML}</script>;
                    ~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@builder.io/qwik/jsx-runtime.d.ts:1147:5
    1147     dangerouslySetInnerHTML?: string;
             ~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'dangerouslySetInnerHTML' which is declared here on type 'QwikScriptHTMLAttributes<HTMLScriptElement>'


Found 1 error in src/components/partytown/partytown.tsx:18

frontend build command exited with code 1
```

### Additional Information

DevDependencies:

"@builder.io/partytown": "^0.7.0",
    "@builder.io/qwik": "^0.11.1",
    "@builder.io/qwik-city": "^0.0.117",
    "@types/eslint": "^8.4.8",
    "@types/express": "^4.17.14",
    "@types/node": "latest",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^5.41.0",
    "@typescript-eslint/parser": "^5.41.0",
    "autoprefixer": "^10.4.12",
    "eslint": "^8.26.0",
    "eslint-plugin-qwik": "^0.11.1",
    "express": "^4.18.2",
    "node-fetch": "3.2.10",
    "npm-check": "^6.0.1",
    "postcss": "^8.4.18",
    "prettier": "2.7.1",
    "tailwindcss": "^3.2.1",
    "typescript": "^4.8.4",
    "vite": "^3.1.8",
    "vite-tsconfig-paths": "^3.5.2"

**Comment by langbamit** [comment]
Fixed in main #1841

**Comment by cptflammin** [comment]
@manucorporat thx, do you have an estimation when a fix could be available as I cannot build the app due to this error ? is there a workaround in the meantime ?

**Comment by mj6uc** [comment]
Hi @cptflammin A workaround (hacky) is to just edit the node_modules/@builder.io/qwik/jsx-runtime.d.ts
Line 1239 (for later versions, 1147 for you)

change type to any from string
  dangerouslySetInnerHTML?: any;
