### ISSUE TITLE
How to prevent texts hydration?

### ISSUE THREAD

**Issue by polRk** [BuilderIO/qwik#1883]
### Is your feature request related to a problem?

I have a proxy, that translate all texts in output (from ssr server) html. 
```
client (browser) -> proxy (translate output) -> ssr qwik server.
```

I wana to prevent hydrate translated texts (After state changes for example). 
How can I do this?

```ts
Example:
import { component$, useStore } from '@builder.io/qwik';

export const App = component$(() => {
  const store = useStore({ count: 0 });

  return (
    <div>
      <p>Count: {store.count}</p>
      <p>
        <button onClick$={() => store.count++}>Click</button>
      </p>
    </div>
  );
});

```

If i translate `Count: ` in output html, after click, the translated text will disappear.

### Describe the solution you'd like

I think, qwik should provide an hoc that blocks hydration for everything inside.

### Describe alternatives you've considered

https://github.com/maoberlehner/vue-lazy-hydration?ysclid=l9pp22gxzx261692481

**Comment by manucorporat** [comment]
This is possible with RenderOnce!

```
import { component$, useStore } from '@builder.io/qwik';

export const App = component$(() => {
  const store = useStore({ count: 0 });

  return (
    <div>
      <RenderOnce>
      <p>Count: {store.count}</p>
      </RenderOnce>
      <p>

        <button onClick$={() => store.count++}>Click</button>
      </p>
    </div>
  );
});
