### ISSUE TITLE
State is not reactive when compared

### ISSUE THREAD

**Issue by jweb89** [BuilderIO/qwik#1884]
### Qwik Version

0.12.0-dev20221024094026

### Operating System (or Browser)

All

### Node Version (if applicable)

v16.14.2

### Which component is affected?

Qwik Runtime

### Expected Behaviour

State should be reactive even when compared against a string or used in a ternary expression

### Actual Behaviour

State is not reactive when compared against a string or used in a ternary. Probably some other comparison operators as well

### Additional Information

Reproduction:
https://stackblitz.com/edit/qwik-starter-zoe7dt?file=src%2Fcomponents%2Ftest%2Findex.jsx

**Comment by manucorporat** [comment]
Got a fix! thanks a lot for catching this one, added a new e2e test too!

**Comment by jweb89** [comment]
Awesome, thanks!
