### ISSUE TITLE
[DOCS] add spanish translation

### ISSUE THREAD

**Issue by devagja** [BuilderIO/qwik#1891]
Hello everyone,

I would be happy to contribute and start with the translation of the documentation into Spanish.

What steps should I follow to collaborate?

Thank you very much for all your effort

**Comment by zanettin** [comment]
thanks a lot 🙏 maybe you can join this discussion over [here](https://github.com/BuilderIO/qwik/issues/1357)

**Comment by manucorporat** [comment]
Hola @devagja ! estas en discord?

**Comment by devagja** [comment]
Hola @manucorporat, sii, mi cuenta es joshxy#4535

**Comment by gioboa** [comment]
I close this one b/c the discussion is [here](https://github.com/BuilderIO/qwik/issues/1357)
