### ISSUE TITLE
Adaptors: "Error during build: On Windows, absolute paths must be valid file"

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#1892]
### Qwik Version

0.12.0

### Operating System (or Browser)

Windows

### Node Version (if applicable)

16

### Which component is affected?

Qwik City

### Expected Behaviour

Build the app on Windows

### Actual Behaviour

Create a fresh app & add an adaptor like `express `or `static`. 

On Windows, when I do `npm run build`, I get the following error:

```
error during build:
Error [PLUGIN_ERROR]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:372:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
    at defaultResolve (node:internal/modules/esm/resolve:1200:3)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ESMLoader.import (node:internal/modules/esm/loader:380:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at mainThread (file:///C:/Users/simon/Documents/Code/qwik-app/node_modules/@builder.io/qwik-city/static/node.mjs:359:43)
    at async Module.generate (file:///C:/Users/simon/Documents/Code/qwik-app/node_modules/@builder.io/qwik-city/static/node.mjs:1268:20)
```

### Additional Information

The error started from v0.12.0.

Thanks

**Comment by tidiview** [comment]
in `package.json`, you could change line:
`"build.server": "vite build -c adaptors/cloudflare-pages/vite.config.ts",`
![OIP](https://user-images.githubusercontent.com/14911996/199030675-1777b20d-1365-4c5c-b180-a6b9a63b81f8.jpg)
for line:
`"build.server": "vite build --ssr src/entry.cloudflare-pages.tsx",`
![OIP2](https://user-images.githubusercontent.com/14911996/199030741-3264f049-2334-4de5-82b1-1033f7caa1c5.jpg)

but after that uploading to `cloudflare` gives a no CSS result: please see [Issue#1928](https://github.com/BuilderIO/qwik/issues/1928) for more information.

**Comment by tuurbo** [comment]
For me i was able to temporarily bypass the error by setting `staticGenerate` to undefined in file `adaptors/express/vite.config.ts`
```ts
import { expressAdaptor } from '@builder.io/qwik-city/adaptors/express/vite';
import { extendConfig } from '@builder.io/qwik-city/vite';
import baseConfig from '../../vite.config';

export default extendConfig(baseConfig, () => {
  return {
    build: {
      ssr: true,
      rollupOptions: {
        input: ['src/entry.express.tsx', '@qwik-city-plan'],
      },
    },
    plugins: [
      expressAdaptor({
        staticGenerate: undefined, // <-----------
      }),
    ],
  };
});
```

**Comment by robisim74** [comment]
@adamdbradley  From v0.12, Windows users cannot build any adaptors.

The problem is that imports with absolute paths don't work on Windows without path normalization:

https://github.com/BuilderIO/qwik/blob/6c68c5b1341df76f5b4342e1767292807beb1b8f/packages/qwik-city/static/main-thread.ts#L17
https://github.com/BuilderIO/qwik/blob/6c68c5b1341df76f5b4342e1767292807beb1b8f/packages/qwik-city/static/worker-thread.ts#L18-L19

The fix is simple, just use `pathToFileURL` for those paths.

I could do a pr, but I need to know if you prefer to solve in the files that consume the paths (`qwik-city\static\main-thread.ts` and `qwik-city\static\worker-thread.ts`), or in each adaptor itself (any side effects?)

**Comment by jrson83** [comment]
I have the same error when trying to build a static site `npm run qwik add static`, `npm run build` throws the same error. If you could do a PR would be great!
