### ISSUE TITLE
[DOCS] Typo in FAQ page

### ISSUE THREAD

**Issue by amittri1025** [BuilderIO/qwik#1893]
There's a typo , I detected on FAQ page https://qwik.builder.io/docs/faq/

The correct spelling is "surprisingly" 
![image](https://user-images.githubusercontent.com/74503582/198387880-9a645f3c-3654-4abb-9ad6-f2a1d697d276.png)

Kindly assign, this issue to me.

**Comment by zanettin** [comment]
thx for reporting this 🙏  fixed in #1904
