### ISSUE TITLE
Please remove the need for an outer fragment

### ISSUE THREAD

**Issue by intervalia** [BuilderIO/qwik#1894]
### Is your feature request related to a problem?

Forcing everyone to create an outer fragment in their return is wasteful.

### Describe the solution you'd like

With a VERY small code change to Qwik you can remove the need for an outer fragment by always having the return always us a fragment around everything that is returned.

It does not make sense for everyone to have to create an outer fragment when the framework can just do it automatically.

Please set Qwik apart as the smart framework by doing the common things internally.

You can either always create a template `document.createElement('template')` or a fragment `new DocumentFragment();` and then place everything from the return into it.

### Describe alternatives you've considered

None

**Comment by manucorporat** [comment]
can you share the code that is erroring for you?

**Comment by intervalia** [comment]
@manucorporat

To your first post: Yes, I am aware that the fragment is needed to have a single root. That is EXACTLY why I am asking for this.
Why can't the framework always create the single root? Instead of forcing everyone to create a fragment, if they need a single root, just let the framework always create one and then no one has to worry about it any more. And we are talking about a very small amount of code that should be required by the framework to save countless developer grief for having forgotten to add the top level fragment.

To your second: This is a feature request, not a bug.

**Comment by manucorporat** [comment]
I think we are not in the same page.

```tsx
render() {
  return <div></div>
}
```
is perfectly valid code.

this problem is:
```tsx
render() {
  const anotherRoot = <div />;
  return <div></div>
}
```

**Comment by manucorporat** [comment]
I would love to see the code that was erroring for you, because i am sure we can provide a better warning. This warning is about the optimizer being able to statically analyze the template, so we can know more efficiently if it contains branches or not. It's a performance warning.

**Comment by intervalia** [comment]
I'll give some code and what I assume your compiled code is giving both for a single element return and a multi element return

```jsx
render() {
    return <div></div>
}
```

I would assume that the transpiled code would be something like this: (This is pseudo code but it should be a good example)
```JS
render() {
  return qwik.createComponent('div');
}
```

and this:
```jsx
render() {
    return <><div></div><p></p></>
}
```

I would assume that the transpiled code would be something like this:
```JS
render() {
  return qwik.createFragment([qwik.createComponent('div'), qwik.createComponent(p));
}
```

What I am asking is that the `qwik.createFragment()` always happen so that I can write this:
```jsx
render() {
    return <div></div><p></p>
}
```
and not have to worry about creating the outer fragment myself.

With my suggestion this:
```jsx
render() {
    return <div></div>
}
```

would would generate this:
```JS
render() {
  return qwik.createFragment([qwik.createComponent('div')]);
}
```

**Comment by manucorporat** [comment]
This is outside the scope of Qwik. The described syntax is not part of the JSX spec:
https://facebook.github.io/jsx/

```tsx
render() {
    return <div></div><p></p>
}
``` 
^ this is not valid JSX, optimizer, typescript, and all tooling would fail to understand it.

Unfortunately this is not something we can solve, other than adding alternative template system instead of JSX.
