### ISSUE TITLE
qwik: core runtime size increase

### ISSUE THREAD

**Issue by zanettin** [BuilderIO/qwik#1906]
### Qwik Version

0.12.0

### Operating System (or Browser)

OSX 12.6 / any browser

### Node Version (if applicable)

16.13.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

maybe you see a way to reduce the runtime code anyhow

### Actual Behaviour

qwik core runtime size measured on cloudfront pages (br compressed):

| 0.11.1 | 0.12.0
| -- | -- |
| 14.4kb | 25.5kb |

![Bildschirmfoto_2022-10-28_um_22_43_09](https://user-images.githubusercontent.com/3241476/198729408-9c11fa80-6a9d-4aa7-8fd3-1bb2e4c7c1c3.png)

**Comment by manucorporat** [comment]
Interesting! could you attach both versions? in 0.11.1 and 0.12.0, it will help me debug a lot!

**Comment by zanettin** [comment]
Hi @manucorporat 
Sure 👍  does not seem app related. just did these steps:
```
pnpm create qwik@0.11.1
basic app
pnpm build
```

and 

```
pnpm create qwik@latest
basic app
pnpm build
```

then you see the diff already on the vite build outputs.
left screen is `0.11.1` and right `0.12.0`. hope this already helps?
![Bildschirmfoto 2022-10-29 um 13 29 14](https://user-images.githubusercontent.com/3241476/198829066-3eff9396-c2a7-4473-8755-9ae13498ee8b.png)
