### ISSUE TITLE
The style bug of the official website

### ISSUE THREAD

**Issue by JeromeD3** [BuilderIO/qwik#1916]
### Qwik Version

0.0.0

### Operating System (or Browser)

macbook air 13 m1 inch

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Neat style planning

### Actual Behaviour

Irregular style planning

### Additional Information

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/67688096/198833601-86bc08b0-aa6e-4dc8-9a9b-db3459e63eeb.png">

**Comment by ptu14** [comment]
looks like someone added overflow hidden unnecessarily, I did a PR to remove it.
