### ISSUE TITLE
problem with Eslint upgrading to 0.12.1 on Windows

### ISSUE THREAD

**Issue by tidiview** [BuilderIO/qwik#1922]
### Qwik Version

0.12.1

### Operating System (or Browser)

Windows

### Node Version (if applicable)

16

### Which component is affected?

Qwik City

### Expected Behaviour

regular upgrade process to 0.12.1.

### Actual Behaviour

error
![eslint-problem-on-windows](https://user-images.githubusercontent.com/14911996/198895648-17304ac4-0efd-4470-a014-1db858f05627.jpg)

### Additional Information

I had the same problem when upgrading with 0.12.0.
Thought this would get solved with 0.12.1 but it didn't, so I thought it was worth writing this issue...
Got the same problem when uploading file to Cloudflare Pages: the built has been also failing with 0.12.0.
I haven't yet tried with 0.12.1 but presume that it'll be same.

**Comment by manucorporat** [comment]
Remove the quotes in the npm script “lint”, it should do the trick!
keeping this issue open as we can improve the qwik cli to handle it

**Comment by tidiview** [comment]
thanks!
That is how it finally worked for others... :
`"lint": "eslint src/**/*.ts*",`

![eslint-problem-on-windows](https://user-images.githubusercontent.com/14911996/198900701-87ed48a7-128d-4871-9589-ab787ef69b58.jpg)

I'm sorry because I couldn't figure out that the problem was coming from `package.json` line `lint` from the initial `eslint ` error message: it was finally trivial, I should have figured out myself easily!
