### ISSUE TITLE
Qwik City:  QWIK ERROR Cannot read `map` (Link with Resource Component )

### ISSUE THREAD

**Issue by kicut** [BuilderIO/qwik#1927]
### Qwik Version

0.12.1

### Operating System (or Browser)

Windows 11 WSL2 (Google Chrome)

### Node Version (if applicable)

v16.17.0

### Which component is affected?

Qwik City

### Expected Behaviour

Should be able to switch pages and not return an error.

### Actual Behaviour

Unable to switch to page (stuck) and returns error message in console: `QWIK ERROR Cannot read properties of undefined (reading 'map') TypeError: Cannot read properties of undefined (reading 'map')`

### Additional Information

The Resource component has a problem mapping an array in onResolved, this problem occurs only when I switch between pages via a link using the Link component.

**routes/posts/index.tsx**

```typescript
import { component$, Resource } from "@builder.io/qwik";
import { RequestHandler, useEndpoint } from "@builder.io/qwik-city";

interface Post {
  id: number;
  title: string;
}

type Posts = Post[];

export const onGet: RequestHandler<Posts> = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  return res.json();
};

export default component$(() => {
  const posts = useEndpoint<Posts>();

  return (
    <div>
      <Resource
        value={posts}
        onPending={() => <p>Pending...</p>}
        onRejected={() => <p>Rejected</p>}
        onResolved={(posts) => (
          <div>
            {posts.map((post) => (
              <div>{post.title}</div>
            ))}
          </div>
        )}
      />
    </div>
  );
});

```

**routes/layout.tsx**

```typescript
import { component$, Slot } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";

export default component$(() => {
  return (
    <>
      <ul class="flex border-b gap-4">
        <li>
          <Link href="/">Home</Link>
        </li>
        <li>
          <Link href="/posts">Posts</Link>
        </li>
      </ul>
      <Slot />
    </>
  );
});

```

The video below may be able to clarify.

https://user-images.githubusercontent.com/25601335/198931813-14388312-ef12-4a65-8ebb-f9439d55af08.mp4

**Comment by manucorporat** [comment]
I cant reproduce the issue. I tried what described, building an app and switching pages with Link, and it's working for me. Can you provide a repo case with clear steps to reproduce it and code? 

My suggestion is to use: https://qwik.new

**Comment by kicut** [comment]
@manucorporat  Okay, here it is: https://stackblitz.com/edit/qwik-starter-wm8fda?file=src/routes/posts/index.tsx

**Comment by skuridin** [comment]
I have the same issue. Looks like when navigating from page A to B `<Resource onResolved={...}/>` of page A is triggered again but with no data.
When I'm navigating from page B to page A I get `QWIK WARN JSX components can not return a promise.` in browser console.

**Comment by manucorporat** [comment]
Updating to 0.14.1 seems to fix the issue in the stackblitz! we shipped a lot of improvements around resources and link!

**Comment by DeVoresyah** [comment]
Hi,
I faced this kind of issue behavior, I'm using:
```
"@builder.io/qwik": "0.15.0",
"@builder.io/qwik-city": "0.0.128",
```

and already used qwik.new boilerplate, here's what I got from my browser console:

![Screen Shot 2022-12-21 at 19 38 54](https://user-images.githubusercontent.com/8052370/208907090-28ffb964-82e6-4a9b-8623-69f056a27bdb.png)
