### ISSUE TITLE
Netlify GitGateway 404

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [BuilderIO/qwik#1929]
I am using qwik with the Netlify adapter, and am trying to use Netlify's GitGateway feature with the NetlifyCMS. NetlifyCMS uses GitGateway through the route `/.netlify/git/<git provider>`. Because qwik captures all of the routes, this route gives a 404. Is there a way to tell qwik to ignore certain routes to allow Netlify to handle them instead?

**Comment by HeyITGuyFixIt** [comment]
@nnelgxorz Netlify sets up the dynamic route `/.netlify/`. I don't know what all it uses that route for other than Git Gateway. I just turn on a setting in Netlify to enable Git Gateway. All other routes are simply files in the routes folder or in the public folder.

**Comment by nnelgxorz** [comment]
Got it. Seems like we could catch that in the Netlify adaptor/middleware. I'll try to take a look later if Adam doesn't get to it first.
