### ISSUE TITLE
[DOCS] Frontmatter

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [BuilderIO/qwik#1930]
**How can the documentation be improved?**
There is zero documentation on how to utilize frontmatter from mdx files. I specifically want to learn how to use frontmatter from subfiles in layout files.

**Comment by frammiie** [comment]
frontmatter is included in the export, and can be retrieved via the
`useDocumentHead()` hook under the `frontmatter` key.

Including for clarification, still needs documentation since
https://qwik.builder.io/qwikcity/api/#usedocumenthead
does not mention it yet.

**Comment by zanettin** [comment]
Hi @HeyITGuyFixIt  und thanks @frammiie 🙏 
The core team is currently working on re-write the qwik-city docs (https://discord.com/channels/842438759945601056/843151429479956510/1068291958176485428). Hope it will be included then. Otherwise we can patch the missing part after the big refactoring 👍
