### ISSUE TITLE
[Tutorial/Playground] REPL 404 - service worker unable to get the response of the online interpreter

### ISSUE THREAD

**Issue by KentC93** [BuilderIO/qwik#1931]
I'm working through the tutorial and it appears that the worker responsible for getting the result of the online interpreter available on the website can't get the response from the server. It either hangs indefinitely or returns 404.
Doesn't seem to be browser, system or ISP related (tried a few browsers, Windows and Linux, through wired and mobile network *[different carriers not sharing infrastructure]*).
![Screenshot from 2022-10-31 14-19-03](https://user-images.githubusercontent.com/90339417/199017226-4cf067f5-941c-47ae-a093-7b76bec97203.png)
![Screenshot from 2022-10-31 14-22-41](https://user-images.githubusercontent.com/90339417/199017899-1ffc13ae-32be-46b6-b24b-b07c125ce15a.png)
![Screenshot from 2022-10-31 14-23-57](https://user-images.githubusercontent.com/90339417/199018130-4d0a667e-38d9-4150-9555-1bdb66c841a4.png)

**Comment by Nosherwan** [comment]
I can confirm the same thing is happening for me in all tutorials & the playground:
The diagnostic tab shows the error below:
```
TypeError: Cannot read properties of undefined (reading 'Root') at entry_server (eval at K (https://qwik.builder.io/repl/repl-sw.js:4:3856), <anonymous>:12:53) at K (https://qwik.builder.io/repl/repl-sw.js:4:4731) at J (https://qwik.builder.io/repl/repl-sw.js:4:5588)
```
while the app window shows:
```
404 - https://qwik.builder.io/repl/1f40o7uhga7/
```

**Comment by hydrati** [comment]
The same.
![image](https://user-images.githubusercontent.com/29159838/199169319-1c5a3e4e-2712-48cc-99da-82fda1055c97.png)
![image](https://user-images.githubusercontent.com/29159838/199169350-b81ca5f1-f547-46c4-9d44-3ec69709acc5.png)

**Comment by Spasfonx** [comment]
Yep, same here

<img width="808" alt="image" src="https://user-images.githubusercontent.com/5750273/199309764-d4957634-c179-49ba-8bb8-3bb613f53cdc.png">

**Comment by manucorporat** [comment]
Fixed in https://github.com/BuilderIO/qwik/pull/1962
