### ISSUE TITLE
Css duplication

### ISSUE THREAD

**Issue by Johann-Goncalves-Pereira** [BuilderIO/qwik#1932]
### Qwik Version

qwik: ^0.12.1 - qwik-city: ^0.0.118

### Operating System (or Browser)

Linux>Kubuntu>VSCode>Vivaldi

### Node Version (if applicable)

16.18.0

### Which component is affected?

Qwik Runtime

## Context:
I update my qwik version, and the css of my application started to duplicate. I think is something related to the sass compilation been split in the qwik run time.

I was remove the postcss, tailwind. But nothing resolves, I change the version of qwik to a older one no css duplication.

### Project description
```
"devDependencies": {
    "@builder.io/qwik": "^0.12.1",
    "@builder.io/qwik-city": "^0.0.118",
    "@netlify/vite-plugin-netlify-edge": "^1.1.1",
    "@types/eslint": "^8.4.8",
    "@types/node": "latest",
    "@typescript-eslint/eslint-plugin": "^5.41.0",
    "@typescript-eslint/parser": "^5.41.0",
    "autoprefixer": "^10.4.12",
    "cssnano": "^5.1.14",
    "eslint": "^8.26.0",
    "eslint-plugin-qwik": "^0.12.1",
    "node-fetch": "^3.2.10",
    "postcss": "^8.4.16",
    "postcss-nesting": "^10.2.0",
    "postcss-preset-env": "^7.8.2",
    "prettier": "^2.7.1",
    "prettier-plugin-tailwindcss": "^0.1.13",
    "sass": "^1.55.0",
    "tailwindcss": "^3.1.8",
    "typescript": "^4.8.4",
    "vite": "^3.2.0",
    "vite-tsconfig-paths": "^3.5.0"
  }
 ```

I don't use `@import` I use `@foword` for sass.
My sass is in a structure l is like this;

```
src/styles
       └── config/ 
       │  ├──── _index.scss  
       │  ├──── _reset.scss  
       │  └──── _tailwind.scss  
       └── tokens/ 
       │  ├──── _index.scss  
       │  └──── _media.scss  
       └── _index.scss  
```

And I put the css in my project this way:
![image](https://user-images.githubusercontent.com/62612685/199040605-5212dea6-f2e4-4ddd-a183-57c5db439ff9.png)

### Expected behavior
In the browser:

![image](https://user-images.githubusercontent.com/62612685/199042436-ad0f853b-a3ec-49cf-ba6e-72b11470314e.png)

### Actual Behaviour

On the browser the result is this one
![image](https://user-images.githubusercontent.com/62612685/199042688-05b6ab9b-35f9-44d5-a284-9771d0df1e63.png)

I this that the scss is been imported again in chuncks because is not recognizing the `@foword`

### Additional Information

If you guy have difficult to replicate the error this is my repository that has the error: 
https://github.com/Johann-Goncalves-Pereira/spotify-Qwik

**Comment by manucorporat** [comment]
This is because of how Vite works, I am in talk with their team to solve this issues, I agree it's very confusing but Vite is adding a side effect to load the styles as an external .css file.

the solution would be:
```tsx
import styles from '@styles/_index.scss?inline`
```

**Comment by Johann-Goncalves-Pereira** [comment]
I changed my code to:

```jsx
import styles from '@styles/_index.scss?inline`
```

but the error persist;
