### ISSUE TITLE
No netlify edge function deployed with default project

### ISSUE THREAD

**Issue by gkatsanos** [BuilderIO/qwik#1933]
### Qwik Version

0.12.1

### Operating System (or Browser)

chrome

### Which component is affected?

Qwik City

### Expected Behaviour

a netlify edge function is deployed

### Actual Behaviour

![image](https://user-images.githubusercontent.com/1768834/199070054-38bf12b5-cd62-4058-8412-c14ca4203796.png)

### Additional Information

There's no endpoint accessible/available after netlify deploy - adapter is installed

**Comment by zanettin** [comment]
Hi @gkatsanos 
Thanks for raising this issue 🙏 

I just gave it a try on my side doing these steps:
```
yarn create qwik
cd <app dir>
yarn qwik add netlify-edge
git ....
```

selected the repo on netlify and published it successfully to the edge.
fn: https://warm-dasik-ac2b35.netlify.app/
repo: https://github.com/zanettin/qwik-netlify

would you mind to give it another try on your side?
cc: @adamdbradley @manucorporat

**Comment by gkatsanos** [comment]
@zanettin try to create an endpoint and access it through your app..

**Comment by zanettin** [comment]
oh sorry! sure will test that as well. thought you mean with endpoint any route 👍

**Comment by zanettin** [comment]
hello again

can confirm the endpoint issue on netlify 👍  
also tested cloudflare to see if it is a general issue with edge functions which is not the case: https://qwik-netlify.pages.dev/api

thanks again for reporting and sorry for the initial misunderstanding. hope @adamdbradley has an idea 🙏
