### ISSUE TITLE
No File Endpoints are generated when `qwik build`

### ISSUE THREAD

**Issue by kwaa** [BuilderIO/qwik#1934]
### Qwik Version

v0.12.1

### Operating System (or Browser)

Arch Linux

### Node Version (if applicable)

v19.0.0

### Which component is affected?

Qwik City

### Expected Behaviour

`qwik build` should generate file endpoints.

(Added ssg via `qwik add`)

### Actual Behaviour

No endpoint file generated, otherwise normal.

Currently, `test.json` is only accessible in dev mode.

### Additional Information

- qwik-city@0.0.118 (adaptor) reproduction: https://stackblitz.com/edit/qwik-starter-vrgmlz?file=src/routes/test.json/index.ts
- qwik-city@0.0.112 (entry) reproduction: https://stackblitz.com/edit/qwik-starter-dy1knd?file=src/routes/test.json/index.ts

**Comment by kwaa** [comment]
Updated for reproduction.
Is there any new information? In 0.0.118, it shows "Not Found" in dev mode.

**Comment by adamdbradley** [comment]
This should be fixed in the latest release. If it's still an issue please reopen with a repo case. Thanks!
