### ISSUE TITLE
Dynamic route abc.dev goes to 404

### ISSUE THREAD

**Issue by AllStackDev1** [BuilderIO/qwik#1940]
### Qwik Version

0.11.1

### Operating System (or Browser)

Mac

### Node Version (if applicable)

v16.14.2

### Which component is affected?

Qwik City

### Expected Behaviour

When I click on a dynamic link it routes to the page.

### Actual Behaviour

Dynamic route "abc.dev" returns 404 when clicked locally, on https://qwik.new/? it routes the user to the page but on refresh, it return 404.

2 bugs:
- on SSR, /abc.dev does not work
- when you go back with browser back, the 404 page sticks around

### Additional Information

https://stackblitz.com/edit/qwik-starter-ggvxr2?file=src%2Froutes%2F[...dynamic]%2Findex.tsx

**Comment by adamdbradley** [comment]
This should be fixed in the latest release. Thanks for opening the issue.
