### ISSUE TITLE
[DOCS] Add link from Qwik City Endpoints docs to Qwik Resource docs

### ISSUE THREAD

**Issue by gederer** [BuilderIO/qwik#1944]
**How can the documentation be improved?**
It might be helpful to add a link from:

https://qwik.builder.io/qwikcity/data/endpoints/

To:

https://qwik.builder.io/docs/components/resource/

The latter shows how to get data from an endpoint without using `<Resource/>`. So, something along the lines of:

```
Want to use data from an Endpoint without <Resource/>? Take a look at the <a href="https://qwik.builder.io/docs/components/resource/">Resource docs</a>.
```

**Comment by zanettin** [comment]
Thx for the input @gederer.
Added the requested line to the docs 👍

**Comment by gederer** [comment]
Grear! Thanks.
