### ISSUE TITLE
`useClientEffect$()` code is not triggered when loading fragments dynamically

### ISSUE THREAD

**Issue by petebacondarwin** [BuilderIO/qwik#1947]
### Qwik Version

0.11.1

### Operating System (or Browser)

Any

### Node Version (if applicable)

Any

### Which component is affected?

Qwik Runtime

### Expected Behaviour

At Cloudflare we are developing an approach where we load new Qwik applications (fragments) into the browser at runtime.
When the new fragment is loaded after the qwik-loader has already completed, we still expect code that is marked as `eagerness: "visible"` (the default) to have an intersection observer attached and therefore run when the component is visible.

### Actual Behaviour

The qwik-loader only runs and finds code that is marked as `eagerness: "visible"` when the document `readystatechange` event is triggered and not when subsequent qwik applications are added to the DOM dynamically.

### Additional Information

The workaround is to mark such code with `eagerness: "load"` and then dispatch a `q:init` event onto the document, which triggers these code blocks to run. (It probably causes a bunch of other blocks to run a second time, which is unfortunate.)

Ideally there should be a way to tell the qwik-loader that more qwik code has been added to the DOM that needs to be initialized and wired up.

**Comment by manucorporat** [comment]
Is it ok to be a manual thing? it could be solved adding a mutationobserver, but I am afraid of it's perf impact

**Comment by petebacondarwin** [comment]
In our case, we know when we have finished fetching the HTML so we could call it manually, yes.

**Comment by manucorporat** [comment]
ok! going to prioritize this issue, this week we should have a solution! thanks for the issue Pete!

**Comment by shairez** [comment]
@petebacondarwin @manucorporat is this still an issue?
