### ISSUE TITLE
Add qwik add command for tRPC

### ISSUE THREAD

**Issue by gioboa** [BuilderIO/qwik#1948]
### Is your feature request related to a problem?

Currently tRPC is an interesting library that use TypeScript inference and boost productivity while building your next full-stack application.

### Describe the solution you'd like

Describe the solution you'd like
Have the possibility to use `qwik add tRPC` command to add [tRPC](https://trpc.io/) can be awesome.

### Describe alternatives you've considered

You can add the library by yourself

### Additional context

I would like to work on this integration 🚀

**Comment by nnelgxorz** [comment]
Knock it out of the park, @gioboa!

**Comment by manucorporat** [comment]
yes please!! I think we are reaching some good critical mass to start adding some hierarchy to the integrations haha

**Comment by gioboa** [comment]
I will create a new PR for that. I close it for the moment.
