### ISSUE TITLE
useClientEffect$ doesn't get triggered with projection component as root

### ISSUE THREAD

**Issue by obipawan** [BuilderIO/qwik#1955]
### Qwik Version

0.12.1

### Operating System (or Browser)

any

### Node Version (if applicable)

any

### Which component is affected?

Qwik Runtime

### Expected Behaviour

`component$`s that have implemented `useClientEffect$` should be triggered even when the root of the containing component holds a projection `<Slot />`

```
const ComponentA = component$((props) => {
    return (
        <div>
            <Slot />
       </div>
    )
})

const Main = component$((props) => {
    useClientEffect$(() => {
         //should be triggered
         console.log('some code to be resumed on browser')
    })
    return (
          <ComponentA>hello world</ComponentA>
    )
}
```

### Actual Behaviour

The `useClientEffect$` is not triggered when the root of that containing component has a projection.

```
const ComponentA = component$((props) => {
    return (
        <div>
            <Slot />
       </div>
    )
})

const Main = component$((props) => {
    useClientEffect$(() => {
         //not triggered
         console.log('some code to be resumed on browser')
    })
    return (
          <ComponentA>hello world</ComponentA>
    )
}
```
Repro https://stackblitz.com/edit/qwik-starter-jq3bna?file=src/app/index.tsx

### Additional Information

One workaround for this to work is to wrap it with a `div`

```
const Main = component$((props) => {
    useClientEffect$(() => {
         console.log('some code to be resumed on browser')
    })
    return (
          <div> {/*this workaround triggeres the useClientEffect*/}
               <ComponentA>hello world</ComponentA>
          </div>
    )
}
```

**Comment by hayley** [comment]
I just ran into this issue. No errors; just the JS in `useClientEffect$` never ran. And it took me a long to realize that it was even happening since it was data that doesn't update frequently and loads first on the server.

Wrapping the component in a `<div>` worked so thanks for mentioning that workaround!

**Comment by Varixo** [comment]
looks related https://github.com/BuilderIO/qwik/issues/1413?
