### ISSUE TITLE
React Components and React Libraries doesn't work as expected sometimes

### ISSUE THREAD

**Issue by akshitdandyan** [BuilderIO/qwik#1968]
### Qwik Version

0.0.111

### Operating System (or Browser)

Edge

### Which component is affected?

Qwik React

### Expected Behaviour

When using a simple component like Material UI Button, it's visible and clickable. But on click, it doesn't give any effect like it usually gives.

### Actual Behaviour

On click, it doesn't give any effect. Also tried ```: client``` option, but still, UI doesn't update accordingly on :hover and :active events.

**Comment by zanettin** [comment]
Hi @akshitdandyan 
Could you try to upgrade qwik to latest (`0.12.1`). On this version many react relevant improvements have been shipped 🙏 Otherwise it would be great if you could create a reproduction over here: https://qwik.new . Thanks a lot

**Comment by akshitdandyan** [comment]
@zanettin Thanks for the quick reply. Would you please help on using react-apexcharts. Created a small sample application here:
[https://stackblitz.com/edit/qwik-starter-ohxd5k?file=src/integrations/react/apexCharts.tsx](url)

**Comment by manucorporat** [comment]
@akshitdandyan i am confused, is the comment a question about a different issue?

**Comment by akshitdandyan** [comment]
Thanks @manucorporat ! Waiting for the PR to be merged :)
