### ISSUE TITLE
Using the static adaptor AND setting a `basePathname` in qwik city does not generate .html files

### ISSUE THREAD

**Issue by kinuris** [BuilderIO/qwik#1980]
### Qwik Version

0.12.1

### Operating System (or Browser)

Ubuntu 20.04 (WSL 2)

### Node Version (if applicable)

18.7.0

### Which component is affected?

Qwik City

### Expected Behaviour

The command "npm run build" should produce `.html` files in the dist directory with the `basePathname` prefixed to the paths within said `.html` files.

### Actual Behaviour

No `.html` files are generated in the dist folder.
![image](https://user-images.githubusercontent.com/44602733/199887050-e4551d8f-82e9-4694-ab8a-d2a8a163831e.png)

### Additional Information

It works as expected if `basePathname` in `qwikCity` is not set.

**Comment by yeyon** [comment]
After running `npm run build` you must run the newly added script to `package.json` by the static adaptator installation, which is `npm run build.server`. After that you will see the `.html` files in `dist` path.

**Comment by kinuris** [comment]
This works only if I don't set a `basePathname`, I should have been more specific on the **Expected Behavior.**

**Comment by kinuris** [comment]
Fixed as of qwik 0.13.3
