### ISSUE TITLE
[DOCS] `useSignal` is undocumented

### ISSUE THREAD

**Issue by washanhanzi** [BuilderIO/qwik#1981]
1. `useSignal` should be documented, remember to check #1729
2. when fully documented, the tutorial should update to use `useSignal` #1810
 including:

- [useRef](https://qwik.builder.io/tutorial/hooks/use-ref/)
- [synchronous events](https://qwik.builder.io/tutorial/events/synchronous/)

**Comment by washanhanzi** [comment]
[synchronous events tutorial](https://qwik.builder.io/tutorial/events/synchronous/) is updated #2112

**Comment by washanhanzi** [comment]
All tutorials have been updated. Only missing documentation.

**Comment by manucorporat** [comment]
We have useSignal() docs now!
