### ISSUE TITLE
[DOCS] A demo based on webpack

### ISSUE THREAD

**Issue by wenxiayili** [BuilderIO/qwik#1982]
Could you please come up with a document that integrates with webpack? Thank you!

**Comment by manucorporat** [comment]
It's not a priority of us to support Webpack, but it's technically possible, we have focused in Rollup / esbuild and Vite, which we have official plugins to support this.

**Comment by wenxiayili** [comment]
> It's not a priority of us to support Webpack, but it's technically possible, we have focused in Rollup / esbuild and Vite, which we have official plugins to support this.

Anyway, thank you for your team!

**Comment by ScriptedAlchemy** [comment]
My group is going to start looking at this for module federation support with qwik
