### ISSUE TITLE
Cookies not deleted properly

### ISSUE THREAD

**Issue by ramsaylanier** [BuilderIO/qwik#1990]
### Qwik Version

0.12.1

### Operating System (or Browser)

Mac OS. Chrome. 

### Node Version (if applicable)

16.14.2

### Which component is affected?

Qwik City

### Expected Behaviour

`cookie.delete(name)` should delete cookie.

### Actual Behaviour

If the cookie was created with a domain and path, the cookie isn't deleted. The `delete` method of `Cookie` doesn't take into account domain/path when setting the cookie to 'deleted'.

**Comment by nnelgxorz** [comment]
Great catch! Thanks!
