### ISSUE TITLE
import error on static generation 

### ISSUE THREAD

**Issue by gmadar** [BuilderIO/qwik#1998]
### Qwik Version

0.12.1

### Operating System (or Browser)

Ubuntu

### Node Version (if applicable)

16.16.0

### Which component is affected?

Qwik City

### Expected Behaviour

```
import { qwikCityGenerate } from '@builder.io/qwik-city/static/node';
```
should work according to [documentation](https://qwik.builder.io/qwikcity/static-site-generation/static-site-config/).

### Actual Behaviour

getting a
```
Cannot find module '@builder.io/qwik-city/static/node' or its corresponding type declarations.
```
error

### Additional Information

qwik-city version: `0.0.118`

**Comment by strowk** [comment]
I also attempted to ignore this and went ahead with adding `  "build.ssg": "vite build --ssr src/entry.static.tsx",`
and running `npm run build.ssg` , which gives a tad more detailed error: 

Missing "./static/node" export in "@builder.io/qwik-city" package. 
So I supposed exports are somehow not done right.

**Comment by gmadar** [comment]
if it's worth something:
I have a local version installed that **is working**:

- `@builder.io/qwik-city` version is `0.0.112`
- `@builder.io/qwik` version is `0.11.1`

**Comment by gmadar** [comment]
I've just read the [change log](https://github.com/BuilderIO/qwik/releases/tag/v0.12.0) - the problem is that the docs are not up-to-date.

to create an SSG, after the initial installment

- run `npm run qwik add`
- select `Adaptor: Static site (.html files)`
- Thats it, to build the server run `npm run build.server`
- to actually build the artifacts `node server/enty.ssr.js`

**Comment by gmadar** [comment]
fixed in https://github.com/BuilderIO/qwik/pull/2058 closing
