### ISSUE TITLE
textarea render wrong content

### ISSUE THREAD

**Issue by langbamit** [BuilderIO/qwik#2000]
### Qwik Version

0.12.1

### Operating System (or Browser)

Brave Browser

### Which component is affected?

Qwik Runtime

### Expected Behaviour

```jsx
import { component$, useStore } from '@builder.io/qwik';

export const App = component$(() => {
  const state = useStore({
	content: "Hello World"
  })
  return <textarea>{state.content}</textarea>
});
```
should render correctly.

```
Hello World
```

### Actual Behaviour

```
<!--t=1-->Hello World<!---->
```

### Additional Information

[Playground link](https://qwik.builder.io/playground#version=0.12.1&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBkYXRhJTIwJTNEJTIwJTdCJTVDbiU1Q3QlMjAlMjBjb250ZW50JTNBJTIwJTVDJTIySGVsbG8lMjBXb3JsZCU1QyUyMiU1Q24lMjAlMjAlN0QlM0IlNUNuJTIwJTIwY29uc3QlMjBzdGF0ZSUyMCUzRCUyMHVzZVN0b3JlKGRhdGEpJTVDbiUyMCUyMHJldHVybiUyMCUzQ2RpdiUzRSU1Q24lMjAlMjAlMjAlMjAlM0N0ZXh0YXJlYSUzRSU3QnN0YXRlLmNvbnRlbnQlN0QlM0MlMkZ0ZXh0YXJlYSUzRSU1Q24lMjAlMjAlMjAlMjAlM0NiciUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlM0NiciUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlM0N0ZXh0YXJlYSUzRSU3QmRhdGEuY29udGVudCU3RCUzQyUyRnRleHRhcmVhJTNFJTVDbiUyMCUyMCUzQyUyRmRpdiUzRSU1Q24lN0QpJTNCJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlbmRlclRvU3RyaW5nJTJDJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBBcHAlMjAlN0QlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D)

**Comment by nnelgxorz** [comment]
Hey @langbamit! There's a fix/workaround for this. Set the textarea content using `dangerouslySetInnerHTML`.

[Updated playground here](https://qwik.builder.io/playground#version=0.12.1&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBkYXRhJTIwJTNEJTIwJTdCJTVDbiU1Q3QlMjAlMjBjb250ZW50JTNBJTIwJTVDJTIySGVsbG8lMjBXb3JsZCU1QyUyMiU1Q24lMjAlMjAlN0QlM0IlNUNuJTIwJTIwY29uc3QlMjBzdGF0ZSUyMCUzRCUyMHVzZVN0b3JlKGRhdGEpJTVDbiUyMCUyMHJldHVybiUyMCUzQ2RpdiUzRSU1Q24lMjAlMjAlMjAlMjAlM0N0ZXh0YXJlYSUyMGRhbmdlcm91c2x5U2V0SW5uZXJIVE1MJTNEJTdCc3RhdGUuY29udGVudCU3RCUzRSUzQyUyRnRleHRhcmVhJTNFJTVDbiUyMCUyMCUyMCUyMCUzQ2JyJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUzQ2JyJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUzQ3RleHRhcmVhJTNFJTdCZGF0YS5jb250ZW50JTdEJTNDJTJGdGV4dGFyZWElM0UlNUNuJTIwJTIwJTNDJTJGZGl2JTNFJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFwcCUyMCU3RCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE)
