### ISSUE TITLE
First async `useClientWatch$` blocks the remaining `useClientWatch$`s

### ISSUE THREAD

**Issue by jessezhang91** [BuilderIO/qwik#2015]
### Qwik Version

0.12.1

### Operating System (or Browser)

OSX

### Which component is affected?

Qwik Runtime

### Expected Behaviour

I expect all `useClientWatch$(async () => ...)` to execute immediately when activated.

### Actual Behaviour

The first `useClientWatch$(async () => ...)` executes immediately. All subsequent `useClientWatch$(async () => ...)` waits until the first one is complete before executing.

### Additional Information

Here's a repro of the issue:
https://stackblitz.com/edit/qwik-starter-cnatu6?file=src%2Froutes%2Findex.tsx,node_modules%2F%40builder.io%2Fqwik%2Fcore.d.ts

Here're the console logs:
```
start 1 Mon Nov 07 2022 00:28:48 GMT-0500 (Eastern Standard Time)
finish 1 Mon Nov 07 2022 00:28:53 GMT-0500 (Eastern Standard Time)
start 2 Mon Nov 07 2022 00:28:53 GMT-0500 (Eastern Standard Time)
start 3 Mon Nov 07 2022 00:28:53 GMT-0500 (Eastern Standard Time)
start 4 Mon Nov 07 2022 00:28:53 GMT-0500 (Eastern Standard Time)
start 5 Mon Nov 07 2022 00:28:53 GMT-0500 (Eastern Standard Time)
finish 2 Mon Nov 07 2022 00:28:58 GMT-0500 (Eastern Standard Time)
finish 3 Mon Nov 07 2022 00:28:58 GMT-0500 (Eastern Standard Time)
finish 4 Mon Nov 07 2022 00:28:58 GMT-0500 (Eastern Standard Time)
finish 5 Mon Nov 07 2022 00:28:58 GMT-0500 (Eastern Standard Time)
```

Here's an example where making the `useClientWatch$` functions not return a promise (remove async/await) has all of them running immediately:
https://stackblitz.com/edit/qwik-starter-yq1ysz?file=src%2Froutes%2Findex.tsx

Here're the console logs for this second case:
```
start 1 Mon Nov 07 2022 00:28:39 GMT-0500 (Eastern Standard Time)
start 2 Mon Nov 07 2022 00:28:39 GMT-0500 (Eastern Standard Time)
start 3 Mon Nov 07 2022 00:28:39 GMT-0500 (Eastern Standard Time)
start 4 Mon Nov 07 2022 00:28:39 GMT-0500 (Eastern Standard Time)
start 5 Mon Nov 07 2022 00:28:39 GMT-0500 (Eastern Standard Time)
finish 1 Mon Nov 07 2022 00:28:44 GMT-0500 (Eastern Standard Time)
finish 2 Mon Nov 07 2022 00:28:44 GMT-0500 (Eastern Standard Time)
finish 3 Mon Nov 07 2022 00:28:45 GMT-0500 (Eastern Standard Time)
finish 4 Mon Nov 07 2022 00:28:45 GMT-0500 (Eastern Standard Time)
finish 5 Mon Nov 07 2022 00:28:45 GMT-0500 (Eastern Standard Time)
```

**Comment by manucorporat** [comment]
This is by design, don't return a promise. Returning a promise, instructs the system to wait for completion.

Change this:
```tsx
  useClientEffect$(async () => {
    console.log('start 1', new Date());
    await wait(5000);
    console.log('finish 1', new Date());
  });
```

to this:
```tsx
  useClientEffect$(() => {
    function run() {
      console.log('start 1', new Date());
      await wait(5000);
      console.log('finish 1', new Date());
    }
    run();
  });
```

**Comment by manucorporat** [comment]
ahh wait! i am rereading the issue, there might be an issue for real, looking into it with more detail! Thanks for the issue!

**Comment by manucorporat** [comment]
Fixed! now all clientEffects will execute in serie:
```
start 1
finish 1
start 2
finish 2
start 3
finish 3
start 4
finish 4
start 5
finish 5
```

**Comment by jessezhang91** [comment]
@manucorporat my expectation is that they should all execute in parallel not in series.

The actual use case I have is I have two API endpoints that I need to call based on a tracked value. Currently it waits until the first API is finished before it calls the second API. The first API call (the one written in my code first) uses `useWatch$` and the second one uses `useClientEffect$`. Unfortunately the solution to not have async/await for the `useWatch$` leads to an `abort`ed fetch call on the server.

I can try to create a StackBlitz that fully captures this case if needed. I just also realized `useClientEffect$` with async/await was exhibiting the same behavior and reported it in this simpler case.

**Comment by jessezhang91** [comment]
@manucorporat here's a repro of `useWatch$` and `useClientEffect$` together:
https://stackblitz.com/edit/qwik-starter-zmgooj?file=src%2Froutes%2Findex.tsx

Logs:
```
start watch on server, delta: 11
finish watch on server, delta: 1012
trigger client, delta: 1793
start watch on browser, delta: 1857
finish watch on browser, delta: 2863
start client effect 1, delta: 2878
start client effect 2, delta: 2878
start client effect 3, delta: 2879
finish client effect 1, delta: 3887
finish client effect 2, delta: 3887
finish client effect 3, delta: 3887
```

The client effects all fire in parallel but waits for the watch to finish first. I expect the watch and client effects to all be executed in parallel when triggered.

**Comment by jessezhang91** [comment]
I think for now my workaround will be to have the server use `useServerMount$` and the rest use `useClientEffect$` with the previous `useWatch$` being split into server and client but with similar functions underneath.
