### ISSUE TITLE
qwik-city uses node-fetch when fetch is missing, not undici

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#2016]
### Qwik Version

0.12.1

### Operating System (or Browser)

any

### Which component is affected?

Qwik City

### Problem

I noticed that Qwik-city [adds node-fetch as a global](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/middleware/node/node-fetch.ts) if it's missing, which is fine.

However, in Node 18, global fetch is implemented by [undici](https://github.com/nodejs/undici), which is a little different, mostly around streams: It uses web streams (just like browsers) instead of node streams, and that means that if you get a stream from undici fetch you might have to transform it to a node stream (using [stream.Readable.fromWeb](https://nodejs.org/api/stream.html#streamreadablefromwebreadablestream-options)).

So, to prevent issues between code running on Node 16 vs Node 18, I propose that qwik-city instead uses undici to set as global fetch.

**Comment by manucorporat** [comment]
sounds fair!! could try adding a PR!?

**Comment by shairez** [comment]
@wmertens do you need help with the PR?

**Comment by forresst** [comment]
Unless I am mistaken, I think we can close this issue.
The PR #2394 has added `undici`

**Comment by shairez** [comment]
nice catch @forresst !

Thanks!
