### ISSUE TITLE
qwik-city: page routes & page endpoints don't operate correctly, and also should work like / double as data endpoints w/ pages

### ISSUE THREAD

**Issue by jordanw66** [BuilderIO/qwik#2018]
### Qwik Version

latest

### Operating System (or Browser)

browser

### Which component is affected?

Qwik City

### Current Behavior
Currently in production (npm run preview) page routes will generate a page when navigated to directly or via SPA. When implementing methods inside the page route (onGet, onPost, onPut, onDelete, etc.) it can double as a data endpoint and you can `useEndpoint()` in the page itself to fetch from these endpoints which will differ depending on client or server. On the client `useEndpoint` uses a `fetch()` to the page route itself for JSON data much like you would to a data endpoint.

However, all data requests to page routes (`accept: application/json`) automatically return extra JSON in the form of:
```
{
  isStatic: boolean,
  prefetch: string[],
  body: <JSON returned from implemented handlers>
}
```
This is returned on ANY requests ( w/ `accept: application/json`) even to HTTP methods that aren't implemented, just without the body field, along with a `200 OK` status code; whereas data endpoints return a `405 Method Not Allowed`.

I am not entirely sure what the `isStatic` and `prefetch` fields are for but I assume it's SPA or component related or something? However, the `useEndpoint` functionality when making a client-side `fetch()` it prepares the URL as `location.href + '/q-data.json'`, this could be useful below?

Another issue is pages will also return `200 OK` as HTML when requested with any HTTP method (without `accept: application/json`), such as POST or with CURL for methods that aren't browser navigable (PUT, DELETE, etc), even when those other HTTP methods aren't implemented.

### Proposed Behavior

- Pages should act like data endpoints when `accept: application/json` is part of the request headers and return data as returned by handler implementations directly without extra stuff.
- Requests to `pageRoute + '/q-data.json'` could maintain the current behavior with extra `isStatic` and `prefetch` as needed. Same for all HTTP methods? TBD
- All data requests to methods on page endpoints (`accept: application/json`) with HTTP methods that aren't implemented or valid should return `405 Method Not Allowed` and either an error page or error JSON (or nothing). Along with an `allow: <METHODS>` header.
- Pages requested WITHOUT `accept: application/json` should ALSO return a `405` w/ an error page instead when requested with an unimplemented method (like POST, DELETE, etc) or invalid methods, and `allow: <METHODS>` header instead. (this is how www.google.com works as an example)
- Methods that aren't browser navigable (DELETE, PUT, PATCH, etc.) that ARE implemented but requested WITHOUT `accept: application/json` should be thought about how to handle. Return JSON anyway? or potentially you could return HTML on these for usecases outside direct browser navigation, but it might not be the same HTML you would want to return via GET or POST. TBD?

### Usecase Example
Simple usecase for using page routes as data endpoints. You have a page route `/products` which produces a page that lists products and you can click-through to view product details on a page route `/products/[skuId]`. Both of these page routes would have internal endpoints to fetch their respective data, however delete buttons on the `/products` page would send a DELETE request to `/products/[skuId]` which would implement the `onDelete` handler and return JSON data indicating success or failure, etc. As a further example, another page could GET `/products` or `/products/[skuId]` for JSON data to display some data on a product elsewhere, etc.

### Actual Behaviour

n/a

**Comment by ramsaylanier** [comment]
I think named endpoints, something like `useEndpoint('/products')` would solve a lot of the data fetching problems.

**Comment by ramsaylanier** [comment]
My experience is that you'll get a 404 on the client. Maybe I'm mis-understanding the issue, but here is a reproduction as I see it:

https://stackblitz.com/edit/qwik-starter-bgt8fn?file=src/routes/page/[slug]/index.tsx

**Comment by ramsaylanier** [comment]
Oh yeah, duh, I forgot the headers and see what you're saying. I've never noticed this issue because I setup endpoint routes.
