### ISSUE TITLE
qwik add command for i18n

### ISSUE THREAD

**Issue by gioboa** [BuilderIO/qwik#2019]
### Is your feature request related to a problem?

Internationalization is the process of designing a software application so that it can be adapted to various languages and regions.
This project enable i18n inside Qwik https://github.com/mhevery/qwik-i18n
I would like to create the command to integrate it in a Qwik project

### Describe the solution you'd like

Have the possibility to add i18n with a command could be awesome.

### Describe alternatives you've considered

You can add the library by yourself

### Additional context

I would like to work on this integration 🚀

**Comment by frederikstonge** [comment]
There's also qwik-speak that does the same : https://github.com/robisim74/qwik-speak
