### ISSUE TITLE
qwik city: refresh after SPA navigation breaks history

### ISSUE THREAD

**Issue by jordanw66** [BuilderIO/qwik#2022]
### Qwik Version

latest

### Operating System (or Browser)

firefox and chromium

### Which component is affected?

Qwik City

### Expected Behaviour

When navigating pages in SPA mode using `<Link>`, history navigation should still work after refreshing a page.

### Actual Behaviour

After you do an SPA navigation, if you refresh the page, history navigation (back button) no longer works.

### Additional Information

Steps to reproduce:
1. Use the Qwik starter.
2. Click the purple button at the bottom, SPA to the `/flower` page.
3. Refresh the page.
4. Press the back button.
5. URL will change to the historical value but page will stay the same.

**Comment by Varixo** [comment]
this is the same issue https://github.com/BuilderIO/qwik/issues/1490
