### ISSUE TITLE
Playground gets into infinite refresh loop

### ISSUE THREAD

**Issue by Evertt** [BuilderIO/qwik#2041]
### Qwik Version

0.12.1

### Operating System (or Browser)

Chrome v107 on macOS Ventura

### Which component is affected?

Qwik Runtime

### Expected Behaviour

I selected Qwik Runtime, I honestly have no idea which component is causing the problem.

The expected behavior would of course be that the playground does *not* get into an infinite refresh loop.

### Actual Behaviour

It infinitely refreshes

### Additional Information

Here's a screen recording of just the first refresh:

![Screen Recording 2022-11-08 at 10 00 47 (1)](https://user-images.githubusercontent.com/1267282/200457683-4048a4f2-b08a-43ad-b8b6-504f0c45a399.gif)

## Edit

It seems like the tutorial, which of course uses the same playground, has the same issue. Oh and I turned of my adblock, just in case that was causing any trouble, but the problem persisted after that.

**Comment by chanced** [comment]
This can be reproduced by opening any page in the tutorial in two tabs. It happens on both Chrome and Firefox.
