### ISSUE TITLE
Cookie property doesn't exist in RequestEvent

### ISSUE THREAD

**Issue by reidark** [BuilderIO/qwik#2042]
### Qwik Version

0.12.1

### Operating System (or Browser)

Windows, Chrome Version 107.0.5304.88 (64 bits)

### Node Version (if applicable)

v16.14.2

### Which component is affected?

Qwik City

### Expected Behaviour

Based on the docs from Qwik City, the `RequestHandler` function has to export a `cookie` property in his `RequestEvent` parameter.

Ref: https://qwik.builder.io/qwikcity/data/overview/#request-event

### Actual Behaviour

After check the interface from `RequestEvent` I can't find any `cookie` property. I can only get the cookies from `request` headers, which is fine, but I think the `cookie` interface let things more easier to handle.

**Comment by nnelgxorz** [comment]
This might be a case of the docs getting ahead of the releases. I added the cookie support in a PR that's merged into main, but I don't think there's been a release since then. Hopefully in the next few days it will be out!
