### ISSUE TITLE
Add a bare-bones starter to qwik cli

### ISSUE THREAD

**Issue by Anticom** [BuilderIO/qwik#2043]
### Is your feature request related to a problem?

I'd like to showcase the most basic qwik app to spread the word similar to what you did with your [online hello-world](https://qwik.builder.io/examples/introduction/hello-world/), especially excluding QwikCity.
I am well aware that routing support could be considered an essential, however both the "Basic App" as well as "Documentation site" starters come with QwikCity included.

I've tried removing it, but without any luck. (I gave up when I removed the vite plugin and got some JSX errors in core.js)

### Describe the solution you'd like

IMHO it would be great to have a **very** basic starter just including the minimum bare-bones dependencies and config to get a single page to render similar to your online examples.

### Describe alternatives you've considered

As mentioned already I've tried removing QwikCity from the "Basic App" starter but without any success.

### Additional context

I noticed that the online playground / examples add some extra javascript that's necessary to post some messages to the parent frame etc.

Since I'd like to showcase / investigate myself _how little_ javascript is actually shipped and used during the initial payload, I'd like to eliminate as much as possible and that includes QwikCity. Additionally looking at the current zoo of tooling I find it hard to keep up. If we got a more basic starter it could not only be used for evaluating and investigating the capabilities of Qwik but also learn about how to do some basic setup by looking at that starter.

Can you please add a "Bare Bones" etc. starter shipping only the most basic setup possible?

**Comment by gioboa** [comment]
I close this issue because now Qwik CLI has the basic starter, a simple SSR app without anything, but you can spin up a basic [Qwik SPA](https://vitejs.dev/guide/) with the Vite CLI too.
