### ISSUE TITLE
Getting an error upgrading to Qwik-city 0.0.119

### ISSUE THREAD

**Issue by tidiview** [BuilderIO/qwik#2045]
### Qwik Version

0.0.119

### Operating System (or Browser)

Windows

### Which component is affected?

Qwik City

### Expected Behaviour

functionnal

### Actual Behaviour

this:
![capture](https://user-images.githubusercontent.com/14911996/200520516-5e78f08f-d04e-469b-92d3-c06840b48276.jpg)

### Additional Information

seems related to the new withLocale trying to include i18n functionnalities to Qwik-city recently...

**Comment by manucorporat** [comment]
Dont upgrade! we need a release of Qwik, we will release soon, we need to improve the release process. Please go back to the previous release :)
