### ISSUE TITLE
Three.js canvas blank on demo with no error message

### ISSUE THREAD

**Issue by NikitaPoly** [BuilderIO/qwik#2054]
### Qwik Version

0.12.1

### Operating System (or Browser)

chrome

### Node Version (if applicable)

18.9.0

### Which component is affected?

Qwik React

### Expected Behaviour

The demo page for qwik/react mother of all demos does not render any three.js components. 

### Actual Behaviour

Qwik should render and show the three js component

### Additional Information

In my project I attempted to convert a react three fiber project to qwik. I was un successful because I would only get a blank canvas. I ran this demo and still get a white blank canvas:
https://github.com/manucorporat/qwik-conference-app/tree/b52b484162e5ae799a096c225e36b6ea41e3368e

**Comment by GolfredoPerezFernandez** [comment]
same here

**Comment by wmertens** [comment]
That repo is very outdated. It should be quite straightforward to use three.js. Try it and if you run into trouble you can get help on the discord.
