### ISSUE TITLE
Extending HTMLAttributes with a non-standard property results in TypeScript error

### ISSUE THREAD

**Issue by shiroinegai** [BuilderIO/qwik#2056]
### Qwik Version

0.12.1

### Operating System (or Browser)

Windows 10 Pro 21H2 Firefox 106.0.5

### Node Version (if applicable)

18.11.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

The `xyz` property introduced in order to use AnimXYZ should not trigger a TypeScript error given the following module augmentation declaration:

```ts
// declaration.d.ts
import { AriaAttributes, DOMAttributes } from "@builder.io/qwik";

declare module '@builder.io/qwik' {
  interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
    xyz?: string | undefined;
  }
}
```

### Actual Behaviour

The following TypeScript error is produced when the `xyz` property is used on any HTML element (the ellipsis represents the respective element used):
`Property 'xyz' does not exist on type 'HTMLAttributes<[...]>'.`

### Additional Information

Minimal reproduction: 
https://stackblitz.com/edit/qwik-starter-mozaqt?file=src/routes/index.tsx

AnimXYZ still functions as expected, only that TypeScript still throws an error.

Consulted articles:

- https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation
- https://react-typescript-cheatsheet.netlify.app/docs/advanced/types_react_api/#adding-non-standard-attributes

**Comment by shairez** [comment]
I'm guessing this is solved by merging with QwikIntrinsicAttributes right?
So I'm closing this

But if it's unrelated, please feel free to re-open
