### ISSUE TITLE
Make qwik to accept another port

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#2061]
### Is your feature request related to a problem?

We use a reverse proxy to run our websites.

This means on each of our servers, we might host 10 to 50 websites. And for each website, we need to have a different port.

Also during the development, our developers develop multiple sites together and we have an infrastructure for local development too. Thus we need to be able to run qwik in dev mode using different ports.

### Describe the solution you'd like

    npm start -p port_number

### Describe alternatives you've considered

There is no alternative for us, specially for the deployment of multiple websites on a single server

**Comment by langbamit** [comment]
```
npm run start -- --port 3000
```
work for me

**Comment by Nefcanto** [comment]
@langbamit thank you. So I guess it should be added to the docs. I could not find it, and I didn't find it through google either.

**Comment by manucorporat** [comment]
Qwik uses vitejs! https://vitejs.dev/config/server-options.html#server-port
It's already in our todo list to add references to their docs.
