### ISSUE TITLE
Add templates for JavaScript

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#2062]
### Is your feature request related to a problem?

We do not work with TypeScript in our company. We literally have zero projects in TypeScript.

However, as I looked at all starter templates, they all work with TypeScript.

Please add JS templates for those who do not use TypeScript.

### Describe the solution you'd like

I think providing a flag for the CLI should do the trick.

    npm create qwik@latest --use-js

### Describe alternatives you've considered

No alternative exists. We need to test with TypeScript. But if we decide to use Qwik, we need to wait until you support JS. Because we do not use TypeScript in our company at all.

**Comment by Nefcanto** [comment]
Any comments about this?

**Comment by coolaj86** [comment]
@Nefcanto: See <https://twitter.com/mhevery/status/1603468277945991168>.

@mhevery says to just rename the couple of files to `.js` and `.jsx`. If that doesn't work, it's a bug.

Copy pasta:

```sh
find . -type f -name '*.ts' -exec sh -c '
    my_file={}
    my_file="$(dirname "${my_file}")"/"$(basename "${my_file}" .ts)"
    mv "${my_file}.ts" "${my_file}.js"
' \;

find . -type f -name '*.tsx' -exec sh -c '
    my_file={}
    my_file="$(dirname "${my_file}")"/"$(basename "${my_file}" .tsx)"
    mv "${my_file}.tsx" "${my_file}.jsx"
' \;
```

**Comment by Nefcanto** [comment]
@coolaj86 it's more than that.

For example adding integrations needs `vite.config.ts`

**Comment by mhevery** [comment]
> For example adding integrations needs `vite.config.ts`

Can't you rename that to `vite.config.js`?

Or is what you are after to have a non-build step project. If the no-build step is what you are after then Qwik may not be for you.

**Comment by Nefcanto** [comment]
@mhevery when we use `add` commands while we have renamed `vite.config.ts` to `vite.config.js`, we encounter an error.

It seems that `vite.config.ts` or `.ts` and `.tsx` in general are in some places over Qwik's codebase.

Of course, Qwik is for us :)

We're building an internal layer over Qwik to be able to completely migrate from Next.js to Qwik.

We're a website design agency and we're suffering from pagespeed scores.

We're stuck at some places and we're R&Ding to solve them. 

- Having separate `onGet` for layouts and pages.
- Figuring out how to use middleware
- Figuring out how to incorporate i18n and l10n in our sites

As soon as we solve these problems internally, we migrate 100% to Qwik. And thank you so much for this valuable framework.

**Comment by mhevery** [comment]
Ohh I see.

May I ask why not use TS? There are many benefits to it with few downsides.

**Comment by Nefcanto** [comment]
It's a team decision. Many times we tried it, and we never felt good using it.

We're very happy without it and our projects are not complex in nature. We just deliver many projects and moat of them are simple and vanilla JS works just fine foe us.

I truely wanted to help. But TBH, I could not understand the codebase.

I forked and cloned and created the image. But understanding the code was not easy for me.

Do you have any idea about that? I can put 2 hours per day, if I understand the codebase.

**Comment by mhevery** [comment]
Yes it is a complex project so it takes a while to get into the codebase.
Not sure we can offer help at this point as it is not something which is on
our roadmap and we already have the roadmap full with what we consider high
priority items.
