### ISSUE TITLE
Error: spawn xdg-open ENOENT

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#2063]
### Qwik Version

0.12.1

### Operating System (or Browser)

Debian GNU/Linux 11 (bullseye)

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

`npm run dev` or `npm start` should work

### Actual Behaviour

running `npm run dev` or `npm start` causes this error:

```
> start
> vite --open --mode ssr

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:5173/' ]
}
```

### Additional Information

Steps for reproduction:

1- Create a docker image using this code:

```
FROM node:lts-bullseye-slim

RUN apt update \
    && npm install --location=global npm -y

WORKDIR /site
```

2- Save in `Dockerfile`
3- Build using `docker build -t qwik/image .`
4- Create a container using `docker run -it qwik/image`
5- Get the list of containers using `docker container ls`
6- Enter into the container using `docker exec -it container_name bash`
7- Once inside the container, run `npm create qwik@latest`
8- Choose `app` for the project name
9- Choose basic starter template
10- Choose installing dependencies
11- Go into the `/site/app`
12- Run `npm start`

**Comment by manucorporat** [comment]
When this happens, i think it's better to remove the `--open` flag, seems like a bug in Vite

**Comment by Nefcanto** [comment]
@manucorporat, yeah that solved the problem. But don't you think that this should be solved by the Qwik team?

Developers should be able to create a Qwik app and run it out of the box.

**Comment by manucorporat** [comment]
i cant think other than removing the `--open` flag, but it's nice for the rest of the developers, since it automatically opens the browser!
