### ISSUE TITLE
Offer a public API for library developers to add a serializer for the objects that their libraries create / work with.

### ISSUE THREAD

**Issue by Evertt** [BuilderIO/qwik#2070]
### Is your feature request related to a problem?

Currently it seems to be close to impossible to use or port certain libraries to Qwik, because of the need for things to be serializable in order to make use of Qwik's awesome optimizer. I'm thinking of RxJS and react-query for example.

But maybe, if the authors of such libraries, had the ability to "install" their libraries in Qwik, like a sort of Qwik Plugin. By providing Qwik with a custom serializer for the library's specialized objects, and whatever else Qwik might need in order to integrate the library with Qwik's optimizer, this problem could be solvable for a lot of potential plugins for Qwik.

### Describe the solution you'd like

Offer a plugin API, maybe something like this maybe:

```ts
import Root from './root';
import { QwikQueryPlugin } from 'qwik-query';

Root.usePlugin(QwikQueryPlugin, /* optionally a config object here */);

// or
Root.usePlugin(QwikQueryPlugin(/* optionally a config object here */));

// or if installing globally is more preferable:
import { usePlugin } from '@builder.io/qwik';

usePlugin(QwikQueryPlugin(/* optionally a config object here */));
```

And inside `usePlugin()` Qwik would then get the custom serializer from the plugin and whatever else it needs in order for that library to be fully compatible with Qwik.

### Describe alternatives you've considered

Developers of such libraries could submit a PR to Qwik for every custom serializer they need Qwik to have in order for their library to work in Qwik. But that seems like a very bad option, because that will make Qwik's code very bloated of course.

**Comment by wmertens** [comment]
I'm going to close this because custom serializers have been rejected a few times. The workaround is to add QRL functions in the store that can act as methods, as described in [#self](https://github.com/BuilderIO/qwik/issues/5087#issuecomment-1707185010)
