### ISSUE TITLE
__vite_ssr_import_1__.getLocale is not a function

### ISSUE THREAD

**Issue by Emt-tz** [BuilderIO/qwik#2084]
### Qwik Version

0.12.1

### Operating System (or Browser)

Chrome(Mac OS Ventura)

### Which component is affected?

Qwik Runtime

### Expected Behaviour

i expect the app to run

### Actual Behaviour

the app cant launch it directly says  [vite] Internal server error: __vite_ssr_import_1__.getLocale is not a function

**Comment by manucorporat** [comment]
Most likely you update qwik-city, please can you make sure you are using `"@builder.io/qwik-city": "0.0.17"` We will release soon qwik 0.13.0 soon, and you should be able to use latest qwik-city!
