### ISSUE TITLE
Can I or Do I need to specify the order of prefetch or which bundle to prefetch?

### ISSUE THREAD

**Issue by lightersss** [BuilderIO/qwik#2086]
### Is your feature request related to a problem?

prefetch
I saw this on the website.
> The ideal solution is to only prefetch the smallest amount of code that is highly likely to be executed from a user's interaction, but avoiding any JavaScript that's couldn't be used.

### Describe the solution you'd like

I just start to use qwik. I run some examples with _npm run preview_ and I didn't see any prefetch behaviour, like this example https://qwik.builder.io/tutorial/events/basic/, even though there is only one clickable button in the page. I just wonder if I need to specify whether this click event needs to be prefetched or not, like use q:prefetch.

### Describe alternatives you've considered

I have no idea. Maybe I miss something in the network?

**Comment by nnelgxorz** [comment]
Prefetch should be happening via a service worker. When JS loads, does it show it coming from the service worker in the network tab?

**Comment by hamatoyogi** [comment]
This seems to be working as expected.
