### ISSUE TITLE
Add option to supply "url" to static adaptor

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#2091]
### Is your feature request related to a problem?

yes.
When using `qwik add` to add 'static html" option, one needs to know to change the following:

```
plugins: [
      staticAdaptor({
        origin: 'https://yoursite.qwik.dev',
      }),
    ],
```

To make all the "meta" links work

### Describe the solution you'd like

Add an option to the CLI that asks the developer about the url of the website

### Describe alternatives you've considered

adding it to the output log after generating (I'll do that anyway as it's an easier fix for now)

**Comment by adamdbradley** [comment]
Going to hold off on this for now since we're instead printing out the message. If it continues to be a problem we can address this again.
