### ISSUE TITLE
404 Static Routes

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [BuilderIO/qwik#2097]
### Qwik Version

0.13.2

### Operating System (or Browser)

Brave

### Node Version (if applicable)

16.18.1

### Which component is affected?

Qwik City
0.0.122

### Expected Behaviour

Resources in `/public` should be served.

### Actual Behaviour

Receive 404 when trying to access resources in `/public`. See the results [here](https://636f9c0895f012000a7b5fcf--thejrny.netlify.app/). For example, there should be an image at https://636f9c0895f012000a7b5fcf--thejrny.netlify.app/imgs/long-logo-transparent.webp.

### Additional Information

I am using Netlify Edge function. This previously worked in 0.12.1. I rolled back to 0.12.1 and it still worked.

<details><summary>Netlify build log:</summary>
<pre>
8:13:44 AM: Build ready to start
8:13:57 AM: build-image version: d7b3813f01c06610bc1723ff1b22446513ee7941 (focal)
8:13:57 AM: build-image tag: v4.14.3
8:13:57 AM: buildbot version: be0925a1b4e8f8d2c5a767f3e0decf8856cad273
8:13:57 AM: Fetching cached dependencies
8:13:57 AM: Starting to download cache of 139.8MB
8:13:58 AM: Finished downloading cache in 404.332487ms
8:13:58 AM: Starting to extract cache
8:13:59 AM: Finished extracting cache in 1.00151842s
8:13:59 AM: Finished fetching cache in 1.474471478s
8:13:59 AM: Starting to prepare the repo for build
8:13:59 AM: Preparing Git Reference refs/heads/main
8:14:00 AM: Parsing package.json dependencies
8:14:01 AM: Starting build script
8:14:01 AM: Installing dependencies
8:14:01 AM: Python version set to 2.7
8:14:01 AM: Started restoring cached node version
8:14:03 AM: Finished restoring cached node version
8:14:03 AM: Attempting node version '16' from .node-version
8:14:03 AM: v16.18.1 is already installed.
8:14:04 AM: Now using node v16.18.1 (npm v8.19.2)
8:14:04 AM: Enabling node corepack
8:14:04 AM: Started restoring cached build plugins
8:14:04 AM: Finished restoring cached build plugins
8:14:04 AM: Attempting ruby version 2.7.2, read from environment
8:14:04 AM: Using ruby version 2.7.2
8:14:04 AM: Using PHP version 8.0
8:14:05 AM: No npm workspaces detected
8:14:05 AM: Started restoring cached node modules
8:14:05 AM: Finished restoring cached node modules
8:14:05 AM: Installing NPM modules using NPM version 8.19.2
8:14:07 AM: changed 1 package, and audited 287 packages in 1s
8:14:07 AM: 126 packages are looking for funding
8:14:07 AM:   run `npm fund` for details
8:14:07 AM: found 0 vulnerabilities
8:14:07 AM: NPM modules installed
8:14:07 AM: Creating package sha
8:14:07 AM: Started restoring cached go cache
8:14:07 AM: Finished restoring cached go cache
8:14:07 AM: Installing Go version 1.17 (requested 1.17)
8:14:11 AM: unset GOOS;
8:14:11 AM: unset GOARCH;
8:14:11 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
8:14:11 AM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
8:14:11 AM: go version >&2;
8:14:11 AM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
8:14:11 AM: go version go1.17 linux/amd64
8:14:11 AM: Detected 1 framework(s)
8:14:11 AM: "qwik" at version "0.13.3"
8:14:11 AM: Installing missing commands
8:14:11 AM: Verify run directory
8:14:13 AM: ​
8:14:13 AM: ────────────────────────────────────────────────────────────────
8:14:13 AM:   Netlify Build                                                 
8:14:13 AM: ────────────────────────────────────────────────────────────────
8:14:13 AM: ​
8:14:13 AM: ❯ Version
8:14:13 AM:   @netlify/build 28.1.13
8:14:13 AM: ​
8:14:13 AM: ❯ Flags
8:14:13 AM:   baseRelDir: true
8:14:13 AM:   buildId: 636f9c0895f012000a7b5fcd
8:14:13 AM:   deployId: 636f9c0895f012000a7b5fcf
8:14:13 AM: ​
8:14:13 AM: ❯ Current directory
8:14:13 AM:   /opt/build/repo
8:14:13 AM: ​
8:14:13 AM: ❯ Config file
8:14:13 AM:   /opt/build/repo/netlify.toml
8:14:13 AM: ​
8:14:13 AM: ❯ Context
8:14:13 AM:   production
8:14:13 AM: ​
8:14:13 AM: ────────────────────────────────────────────────────────────────
8:14:13 AM:   1. build.command from netlify.toml                            
8:14:13 AM: ────────────────────────────────────────────────────────────────
8:14:13 AM: ​
8:14:13 AM: $ npm run build
8:14:13 AM: > build
8:14:13 AM: > qwik build
8:14:13 AM: tsc --incremental --noEmit
8:14:13 AM: vite build
8:14:13 AM: vite build --ssr src/entry.netlify-edge.tsx
8:14:14 AM: vite v3.2.3 building for production...
8:14:15 AM: transforming...
8:14:15 AM: ✓ 71 modules transformed.
8:14:16 AM: rendering chunks...
8:14:16 AM: dist/q-manifest.json        18.03 KiB
8:14:16 AM: dist/build/q-a95a3e9b.js    0.06 KiB / gzip: 0.07 KiB
8:14:16 AM: dist/build/q-f19d8cb8.js    0.26 KiB / gzip: 0.22 KiB
8:14:16 AM: dist/build/q-12eb4edf.js    4.25 KiB / gzip: 2.13 KiB
8:14:16 AM: dist/build/q-259e5e78.js    1.51 KiB / gzip: 0.85 KiB
8:14:16 AM: dist/build/q-23e3859f.js    0.83 KiB / gzip: 0.49 KiB
8:14:16 AM: dist/build/q-4451ff66.js    1.10 KiB / gzip: 0.51 KiB
8:14:16 AM: dist/build/q-9eedcfb1.js    2.78 KiB / gzip: 0.71 KiB
8:14:16 AM: dist/build/q-bdb28a9d.js    0.20 KiB / gzip: 0.16 KiB
8:14:16 AM: dist/build/q-dc77b230.js    0.20 KiB / gzip: 0.16 KiB
8:14:16 AM: dist/build/q-015768d5.js    0.21 KiB / gzip: 0.17 KiB
8:14:16 AM: dist/build/q-9fef2d36.js    0.21 KiB / gzip: 0.18 KiB
8:14:16 AM: dist/build/q-b9e660d2.js    0.21 KiB / gzip: 0.18 KiB
8:14:16 AM: dist/build/q-cc624084.js    0.21 KiB / gzip: 0.17 KiB
8:14:16 AM: dist/build/q-67e9949c.js    0.55 KiB / gzip: 0.34 KiB
8:14:16 AM: dist/build/q-fd17ec76.js    0.22 KiB / gzip: 0.18 KiB
8:14:16 AM: dist/build/q-c65e242a.js    10.22 KiB / gzip: 4.27 KiB
8:14:16 AM: dist/build/q-78be733e.js    39.35 KiB / gzip: 15.84 KiB
8:14:16 AM: dist/build/q-d4d7d3ee.js    9.52 KiB / gzip: 4.03 KiB
8:14:16 AM: dist/build/q-5d7a1043.js    12.10 KiB / gzip: 5.00 KiB
8:14:16 AM: dist/build/q-bc1d4182.js    11.63 KiB / gzip: 4.76 KiB
8:14:16 AM: dist/build/q-840b7842.js    12.61 KiB / gzip: 4.96 KiB
8:14:16 AM: dist/build/q-5147b4fc.js    3.30 KiB / gzip: 1.58 KiB
8:14:16 AM: dist/build/q-be822fe1.js    0.63 KiB / gzip: 0.25 KiB
8:14:16 AM: dist/build/q-515fb689.js    13.45 KiB / gzip: 5.33 KiB
8:14:16 AM: dist/build/q-b7d88156.js    0.11 KiB / gzip: 0.11 KiB
8:14:16 AM: dist/build/q-039404f4.js    23.07 KiB / gzip: 8.66 KiB
8:14:16 AM: dist/build/q-b5b55731.js    11.52 KiB / gzip: 4.69 KiB
8:14:16 AM: dist/build/q-ee7e16be.js    0.73 KiB / gzip: 0.44 KiB
8:14:16 AM: dist/build/q-395b67b2.js    5.23 KiB / gzip: 2.38 KiB
8:14:16 AM: dist/build/q-130679d5.js    0.35 KiB / gzip: 0.26 KiB
8:14:16 AM: dist/build/q-4bae8249.js    0.09 KiB / gzip: 0.10 KiB
8:14:16 AM: dist/build/q-7a2092dd.js    0.89 KiB / gzip: 0.54 KiB
8:14:16 AM: dist/build/q-e990c14c.js    0.21 KiB / gzip: 0.17 KiB
8:14:16 AM: dist/build/q-92da58b3.js    3.78 KiB / gzip: 1.62 KiB
8:14:16 AM: dist/build/q-cbf41300.js    2.11 KiB / gzip: 1.00 KiB
8:14:16 AM: dist/service-worker.js      2.48 KiB / gzip: 1.18 KiB
8:14:16 AM: dist/build/q-a33a7dd9.css   1.35 KiB / gzip: 0.62 KiB
8:14:16 AM: dist/build/q-710e3026.js    14.91 KiB / gzip: 6.03 KiB
8:14:16 AM: ✓ Built client modules
8:14:18 AM: vite v3.2.3 building SSR bundle for production...
8:14:18 AM: transforming...
8:14:18 AM: ✓ 38 modules transformed.
8:14:18 AM: rendering chunks...
8:14:18 AM: netlify/edge-functions/entry.netlify-edge/entry.netlify-edge.js   252.12 KiB
8:14:18 AM: netlify/edge-functions/entry.netlify-edge/build/q-a33a7dd9.css    1.35 KiB
8:14:18 AM: ✓ Built server (ssr) modules
8:14:18 AM: ✓ Type checked
8:14:18 AM: ​
8:14:18 AM: (build.command completed in 5s)
8:14:18 AM: ​
8:14:18 AM: Creating deploy upload records
8:14:18 AM: ────────────────────────────────────────────────────────────────
8:14:18 AM:   2. Edge Functions bundling                                    
8:14:18 AM: ────────────────────────────────────────────────────────────────
8:14:18 AM: ​
8:14:18 AM: Packaging Edge Functions from netlify/edge-functions directory:
8:14:18 AM:  - entry.netlify-edge
8:14:18 AM: ​
8:14:18 AM: (Edge Functions bundling completed in 308ms)
8:14:18 AM: ​
8:14:18 AM: ────────────────────────────────────────────────────────────────
8:14:18 AM:   3. Deploy site                                                
8:14:18 AM: ────────────────────────────────────────────────────────────────
8:14:18 AM: ​
8:14:18 AM: Starting to deploy site from 'dist'
8:14:18 AM: Creating deploy tree 
8:14:18 AM: 39 new files to upload
8:14:18 AM: 0 new functions to upload
8:14:19 AM: Site deploy was successfully initiated
8:14:19 AM: ​
8:14:19 AM: (Deploy site completed in 789ms)
8:14:19 AM: ​
8:14:19 AM: Starting post processing
8:14:19 AM: ────────────────────────────────────────────────────────────────
8:14:19 AM:   Netlify Build Complete                                        
8:14:19 AM: ────────────────────────────────────────────────────────────────
8:14:19 AM: Post processing - HTML
8:14:19 AM: ​
8:14:19 AM: (Netlify Build completed in 6.1s)
8:14:19 AM: Caching artifacts
8:14:19 AM: Processing form - contact
8:14:19 AM: Started saving node modules
8:14:19 AM: Finished saving node modules
8:14:19 AM: Started saving build plugins
8:14:19 AM: Finished saving build plugins
8:14:19 AM: Started saving pip cache
8:14:19 AM: Finished saving pip cache
8:14:19 AM: Started saving emacs cask dependencies
8:14:19 AM: Finished saving emacs cask dependencies
8:14:19 AM: Started saving maven dependencies
8:14:19 AM: Finished saving maven dependencies
8:14:19 AM: Detected form fields: - name - email - message
8:14:19 AM: Started saving boot dependencies
8:14:19 AM: Finished saving boot dependencies
8:14:19 AM: Started saving rust rustup cache
8:14:19 AM: Finished saving rust rustup cache
8:14:19 AM: Started saving go dependencies
8:14:20 AM: Post processing - header rules
8:14:19 AM: Finished saving go dependencies
8:14:19 AM: Build script success
8:14:20 AM: Uploading Cache of size 139.7MB
8:14:20 AM: Post processing - redirect rules
8:14:20 AM: Post processing done
8:14:21 AM: Finished processing build request in 23.698757983s
8:14:24 AM: Site is live ✨
</pre>
</details>

**Comment by HeyITGuyFixIt** [comment]
Any thoughts on this @adamdbradley?

**Comment by HeyITGuyFixIt** [comment]
Just discovered that I need to [migrate](https://qwik.builder.io/qwikcity/adaptors/netlify-edge/#migration). After migrating (including deleting the `netlify` directory), it now works as expected.

**Comment by zanettin** [comment]
Hi @HeyITGuyFixIt  👋 
Great to read that 🎉  would you mind to close the issue then?
