### ISSUE TITLE
error when upgrading to qwik 0.13.1

### ISSUE THREAD

**Issue by tidiview** [BuilderIO/qwik#2100]
### Qwik Version

0.13.1

### Operating System (or Browser)

Windows

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

regular

### Actual Behaviour

this:
![capture](https://user-images.githubusercontent.com/14911996/201406687-9aff33a8-88e8-45c4-a71a-119247a4654a.jpg)

### Additional Information

error at first on docs/layout.tsx
then
the rest of modules building process is stopped in the middle for some reason.

**Comment by manucorporat** [comment]
Most likely you have a deprecation error saying that add `?inline` to the css import!
```
import styles from './styles.css?inline'
```
should fix it!

Right now your app is loading styles twice! this new error helps prevent that

**Comment by tidiview** [comment]
Thank you so much @manucorporat for taking of your precious time to answer this bug.
I confirm that the problem has been fixed.
I also had a problem with building on Cloudflare's Pages: CSS was left aside.
I confirm that this has also been fixed.
So, I'm happy!
Thank you very much.
Qwik is very VERY  V E R Y  impressive!
Thank you for such a great tool.

**Comment by tidiview** [comment]
Thank you so much @manucorporat for taking of your precious time to answer this bug.
I confirm that the problem has been fixed.
I also had a problem with building on Cloudflare's Pages: CSS was left aside.
I confirm that this has also been fixed.
So, I'm happy!
Thank you very much.
Qwik is very VERY  V E R Y  impressive!
Thank you for such a great tool.
As a bonus, please find here below the test of the qwik site:
![capture](https://user-images.githubusercontent.com/14911996/201429562-bf5b168b-de7f-4a30-ae87-e2b8067cbc2d.jpg)
It is close to ideal!

**Comment by tidiview** [comment]
@manucorporat 
Thank you for the upgrade to 0.13.3.
As a comparison with previous comment:
![capture](https://user-images.githubusercontent.com/14911996/201488432-9744687a-36ed-4ef1-880c-733c199d971e.jpg)
