### ISSUE TITLE
useHook is not working in arrow function context

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#2117]
### Qwik Version

0.13.3

### Operating System (or Browser)

Edge Windows

### Node Version (if applicable)

16

### Which component is affected?

Qwik Runtime

### Expected Behaviour

According to the [documentation](https://qwik.builder.io/docs/components/lifecycle/#rules), any `useHook` should be able to run in a arrow function context inside a component.

### Actual Behaviour

When using a hook inside an arrow function context I get the error: 
```
Code(20): use- method must be called only at the root level of a component$()
```
Here is a simple reproduction: https://stackblitz.com/edit/qwik-starter-jzvqxa?file=src/routes/index.tsx

**Comment by manucorporat** [comment]
The docs are very wrong, i am so surprised and i am sorry about the confusion! Going to fix asap!

**Comment by GrandSchtroumpf** [comment]
Ah, too bad. This would have been very convenient.

**Comment by manucorporat** [comment]
what do you try to do?

**Comment by GrandSchtroumpf** [comment]
I'm creating a wrapper around the firebase sdk with qwik to lazy load firebase instanciation and reduce bundle size.
The `firestore` object is globally configured, so I use a Context. But I only need it when I actually do an operation:

With hook inside function context
```typescript
import { addDoc } from 'firebase/firestore';
export default component$(() => {
  const add$ = $((data) => {
    const firestore = useContext(FIRESTORE);
    addDoc(firestore, data);
  });
  return (...);
})
```

With the hook at the root of the component:
```typescript
import { addDoc } from 'firebase/firestore';
export default component$(() => {
  const firestore = useContext(FIRESTORE);
  const add = (data) => addDoc(firestore, data);
  return (...);
})
```

As `firestore` is not serializable I cannot pass it inside a `$` callback.
Also the `addDoc` is included in the component bundle event if it might not be used.

**Comment by manucorporat** [comment]
if it's not serializable likely you cant pass it in a context either, the idea here is: do you want to run firebase in the server and pass it? probably not

it's a client only thing, think of context as a way to pass data, not functionality. can't this be implemented with some sort of useFirebase() what will load it in client mode?

**Comment by GrandSchtroumpf** [comment]
Ah sorry I thought Context was used to managed global variable, like dependency injection in Angular.
So I can use a top level variable that I would pass around ? This is not an anti-pattern ?

`firestore.ts`
```typescript
import { initializeFirestore } from 'firebase/firestore';
let _firestore;
export function getFirestore() {
  if (!_firestore) {
    _firestore = initializeFirestore();
  }
  return _firestore;
}
```

`index.ts`
```typescript
import { addDoc } from 'firebase/firestore';
import { getFirestore } from '../firestore';
export default component$(() => {
  const add$ = $((data) => {
    const firestore = getFirestore();
    addDoc(firestore, data);
  });
  return (...);
})
```
