### ISSUE TITLE
Conditional rendering with React integration components not working

### ISSUE THREAD

**Issue by daniellmiranda** [BuilderIO/qwik#2121]
### Qwik Version

0.13.3

### Operating System (or Browser)

Arch Linux, Firefox, Brave

### Node Version (if applicable)

18.2.0

### Which component is affected?

Qwik React

### Expected Behaviour

When using a React Component created with the `qwikify$()` function and conditionally rendering this component, different components should render based on a change of state.

```typescript
/** @jsxImportSource react */

import { qwikify$ } from '@builder.io/qwik-react';
import { DotsThree, DotsThreeVertical } from 'phosphor-react';

export const DotsThreeIcon = qwikify$(DotsThree);
export const DotsThreeVerticalIcon = qwikify$(DotsThreeVertical);
```

```typescript
export default component$(() => {
  const isMenuOpen = useSignal(false);

  return (
    <header className="bg-slate-800 text-gray-100 p-4">
      <button onClick$={() => (isMenuOpen.value = !isMenuOpen.value)}>
        {isMenuOpen ? <DotsThreeIcon /> : <DotsThreeVerticalIcon />}
      </button>
    </header>
  );
});
```

### Actual Behaviour

The state changes (using `useSignal` or `useStore`) but the component rendered on the screen doesn't change with the state. The same doesn't happen when I use a common HTML tag or text.

Using the code provided as an example:
1 - The `<DotsThreeVerticalIcon />` is rendered by default since the `isMenuOpen` state is initialized with `false`
2 - When the button is clicked the state changes to `true`
3 - The component that should be rendered is `<DotsThreeIcon />` but `<DotsThreeVerticalIcon />` is still on the screen

### Additional Information

I tested conditionally rendering the MUIButton that comes with the Qwik React Integration just in case it's something with the Phosphor React lib, but the same problem happens.

**Comment by manucorporat** [comment]
the expresion is always true, you need to consume the value of the signal, otherwise it's an object which is always `true`
```
        {isMenuOpen.value ? <DotsThreeIcon /> : <DotsThreeVerticalIcon />}
```

**Comment by daniellmiranda** [comment]
> the expresion is always true, you need to consume the value of the signal, otherwise it's an object which is always `true`
> 
> ```
>         {isMenuOpen.value ? <DotsThreeIcon /> : <DotsThreeVerticalIcon />}
> ```

Hi @manucorporat . Sorry, my example here on the issue was indeed wrong but I tested with the `.value` and with the `useStore` hook as mentioned earlier and the problem persists.

If I use a string for example, everything works fine, but if I use a React component it doesn't change.

**Comment by daniellmiranda** [comment]
I made a qwik demonstration:
[Qwik React Bug.webm](https://user-images.githubusercontent.com/55032792/201650846-3c4bef83-056f-4a16-a5b3-3b0179d1aa5e.webm)
