### ISSUE TITLE
Passing part of a context into a provider does not work

### ISSUE THREAD

**Issue by jweb89** [BuilderIO/qwik#2134]
### Qwik Version

0.12.1

### Operating System (or Browser)

Stackblitz

### Node Version (if applicable)

16

### Which component is affected?

Qwik Runtime

### Expected Behaviour

The lower context should have the data that's passed in from the higher context in the provider

### Actual Behaviour

The lower context does not have the value passed in from the provider

### Additional Information

Repo with example:
https://stackblitz.com/edit/qwik-starter-rber6b?file=src%2Fcomponents%2Ftest%2Findex.jsx

**Comment by manucorporat** [comment]
The issue reported is not related to context or qwik, but evaluation order.

In the example provided:

```tsx

  // Fetching data and updating the higher context
  useMount$(async () => {
    const data = await fetch('https://jsonplaceholder.typicode.com/posts/1');
    const json = await data.json();
    rootContext.data = json;
    console.log('useMount json', json);
    console.log('useMount data', rootContext.data);
    console.log('useMount userId', rootContext.data?.userId);
  });
  console.log('beforeProvider', rootContext.data);
  console.log('beforeProvider userId', rootContext.data?.userId);

  // Lower context
  useContextProvider(context, {
    test: rootContext.data,
    id: rootContext?.data?.userId,
    nonMount: true,
  });
```

how would you expect to lower context to have the data from useMount()?
```
  useContextProvider(context, {
    test: rootContext.data,
    id: rootContext?.data?.userId,
    nonMount: true,
  });
```
the value undefined is assigned before it's changed after the fetch, instead:


```tsx

   const newContext = {
    test: rootContext.data,
    id: rootContext?.data?.userId,
    nonMount: true,
  };
  useMount$(async () => {
    const data = await fetch('https://jsonplaceholder.typicode.com/posts/1');
    const json = await data.json();
    newContext.data = json;
    console.log('useMount json', json);
    console.log('useMount data', rootContext.data);
    console.log('useMount userId', rootContext.data?.userId);
  });
  useContextProvider(context, newContext);
```

**Comment by jweb89** [comment]
Based on the documentation of useMount it blocks rendering. So I was assuming that the useContextProvider would not be executed until after the useMount had resolved and the rootContext.data had been updated by the useMount. Is this assumption incorrect? Does it only block the jsx from being evaluated not the rest of the component?
