### ISSUE TITLE
style attribute should not kebab-case variable names

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#2142]
### Qwik Version

0.13.3

### Operating System (or Browser)

any

### Which component is affected?

Qwik Runtime

### Expected Behaviour

If you put this in playground, you should get a red text twice:

```js
import { component$, useStyles$ } from '@builder.io/qwik';

export default component$(() => {
  useStyles$(`
    .foo { color: var(--myColor); }
  `)
  return <>
  <p class="foo" style={{'--myColor': 'red'}}>Not red</p>
  <p class="foo" style={'--myColor: red'}>Red!</p>
  </> 
});
```

### Actual Behaviour

you get black text for the first p because the variable name gets changed to `--my-color`

**Comment by n8sabes** [comment]
Until this is fixed, a simple workaround is to use `snake_case` for variables.

**Comment by n8sabes** [comment]
This has come up a few times in the Discord related to vanilla-extract variables, so adding [Stackblitz](https://stackblitz.com/edit/qwik-ve-css-export-qfyphx?file=src%2Froutes%2Fdynamic%2Findex.tsx) and screenshot here for faster reference. *You will need to manually run `pnpm dev` in stackblitz*.

This does not occur in production mode as the variable name is reduced to the hash only.

<img width="765" alt="ve_qwik_invalid_dynaimc_var" src="https://user-images.githubusercontent.com/10445528/202589410-9313a4ca-113b-487c-bea6-8f4591157699.png">
