### ISSUE TITLE
qwik-city 0.0.119 broke stackblitz reloading

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#2143]
### Qwik Version

qwik-city 0.0.119

### Operating System (or Browser)

stackblitz

### Which component is affected?

Qwik City

### Expected Behaviour

When you run the default stackblitz and you reload the mini browser, you get the page again. 

### Actual Behaviour

When you upgrade qwik-city from 0.0.118 to 0.0.119, it can no longer reload, the port is no longer available somehow but there are no errors in the console

**Comment by manucorporat** [comment]
i dont know what happened here...

**Comment by manucorporat** [comment]
What's the bisect of this issue, from 0.0.118 to 0.0.119?
