### ISSUE TITLE
How to development or debug with express middleware?

### ISSUE THREAD

**Issue by chendong-xie** [BuilderIO/qwik#2160]
### Qwik Version

^0.13.3

### Operating System (or Browser)

Chrome

### Which component is affected?

Qwik City

### Expected Behaviour

Can development or debug with express middleware?

### Actual Behaviour

![image](https://user-images.githubusercontent.com/82069123/202152459-8bb9b41c-4b95-4138-a2c5-17d1fcdbb61d.png)
I can not see the logs from anywhere

**Comment by manucorporat** [comment]
The production server runs when you first build in production,
```
npm run build
``` 
then you serve:
```
npm run serve
``` 

check out the scripts in your `package.json`
