### ISSUE TITLE
Adding and removing query params from url with useNavigate scrolls to top

### ISSUE THREAD

**Issue by jweb89** [BuilderIO/qwik#2162]
### Qwik Version

qwik-city:0.0.122 qwik:0.13.3 stackblitz is different version due to stackblitz reloading issues

### Operating System (or Browser)

Browser chrome

### Node Version (if applicable)

16

### Which component is affected?

Qwik City

### Expected Behaviour

When adding or removing query params with ? using useNavigate the page gets scrolled to top

### Actual Behaviour

When adding or removing query params with ? using useNavigate the page should not scrollToTop

### Additional Information

https://stackblitz.com/edit/qwik-starter-ps4otn?file=src%2Fcomponents%2Ftest%2Findex.jsx

To test this it's probably easier to copy the stackblitz url in a new window. The qwik and qwik-city versions are a little older but I had issue with the server reloading in stackblitz on the latest. In my local environment the issue still exists with the latest versions qwik-0.13.3 and qwik-city:0.0.122

**Comment by the-zimmermann** [comment]
@manucorporat this is fixed in 0.18.1.
