### ISSUE TITLE
Internal server error: failed to load module for ssr: /src/root_component_3sccycdd1z0.js

### ISSUE THREAD

**Issue by ManeMaria** [BuilderIO/qwik#2163]
### Qwik Version

0.13.3

### Operating System (or Browser)

Edição	Windows 10 Home Single Language
Versão	21H2
Instalado em	‎21/‎08/‎2021
Compilação do SO	19044.2251
Experiência	Windows Feature Experience Pack 120.2212.4180.0

### Node Version (if applicable)

16.14.1

### Which component is affected?

Starters / CLI

### Expected Behaviour

run the build

### Actual Behaviour

When starting the project, after the build this happens.

**Comment by manucorporat** [comment]
Unfortunatelly, we cant reproduce the issue without a repo case :(
