### ISSUE TITLE
Inconsistent reactivity using SIgnal vs Store

### ISSUE THREAD

**Issue by jwickers** [BuilderIO/qwik#2176]
### Qwik Version

0.13.3

### Operating System (or Browser)

Playground

### Which component is affected?

Qwik Runtime

### Expected Behaviour

See the linked playground, all examples should react the same way to the data change and show the same string.

### Actual Behaviour

1. boolean props do not appear to react to change when coming from an object property when the object is in a signal
2. string props passed as JS interpolated string do not react, although the same interpolated string do react in a child component if it is built from values passed as props.

### Additional Information

See this playground:

https://qwik.builder.io/playground#version=0.13.3&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU2lnbmFsJTJDJTIwdXNlU3RvcmUlMkMlMjBTaWduYWwlMkMlMjBTbG90JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwVGVzdCUyMCUzRCUyMGNvbXBvbmVudCUyNCgocHJvcHMlM0ElN0J0ZXh0JTNBc3RyaW5nJTJDJTIwZmxhZyUzQWJvb2xlYW4lMkMlMjBudW0lM0FudW1iZXIlN0QpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCUzQ3AlM0UlM0NTbG90JTJGJTNFJTIwJTdCcHJvcHMudGV4dCU3RCUyMGZsYWclM0QlN0Jwcm9wcy5mbGFnJTIwJTNGJTIwJ1QnJTIwJTNBJTIwJ0YnJTdEJTIwbnVtJTNEJTdCcHJvcHMubnVtJTdEJTNDJTJGcCUzRSUzQiU1Q24lN0QpJTNCJTVDbmV4cG9ydCUyMGNvbnN0JTIwVGVzdFNpZyUyMCUzRCUyMGNvbXBvbmVudCUyNCgocHJvcHMlM0ElN0JzaWclM0ElMjBTaWduYWwlN0QpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCUzQ3AlM0UlM0NTbG90JTJGJTNFJTIwJTdCcHJvcHMuc2lnLnZhbHVlLnRleHQlN0QlMjBmbGFnJTNEJTdCcHJvcHMuc2lnLnZhbHVlLmZsYWclMjAlM0YlMjAnVCclMjAlM0ElMjAnRiclN0QlMjBudW0lM0QlN0Jwcm9wcy5zaWcudmFsdWUubnVtJTdEJTNDJTJGcCUzRSUzQiU1Q24lN0QpJTNCJTVDbmV4cG9ydCUyMGNvbnN0JTIwVGVzdFN0b3JlJTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSU3QnN0b3JlJTNBJTIwYW55JTdEKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAlM0NwJTNFJTNDU2xvdCUyRiUzRSUyMCU3QnByb3BzLnN0b3JlLnRleHQlN0QlMjBmbGFnJTNEJTdCcHJvcHMuc3RvcmUuZmxhZyUyMCUzRiUyMCdUJyUyMCUzQSUyMCdGJyU3RCUyMG51bSUzRCU3QnByb3BzLnN0b3JlLm51bSU3RCUzQyUyRnAlM0UlM0IlNUNuJTdEKSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMFRlc3QyJTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSU3QnRleHQlM0FzdHJpbmclN0QpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCUzQ3AlM0UlM0NTbG90JTJGJTNFJTIwJTdCcHJvcHMudGV4dCU3RCUzQyUyRnAlM0UlM0IlNUNuJTdEKSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMFRlc3QyU2lnJTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSU3QnNpZyUzQSUyMFNpZ25hbCU3RCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDcCUzRSUzQ1Nsb3QlMkYlM0UlMjAlN0IlNjAlMjQlN0Jwcm9wcy5zaWcudmFsdWUudGV4dCU3RCUyMGZsYWclM0QlMjQlN0Jwcm9wcy5zaWcudmFsdWUuZmxhZyUyMCUzRiUyMCdUJyUyMCUzQSUyMCdGJyU3RCUyMG51bSUzRCUyNCU3QnByb3BzLnNpZy52YWx1ZS5udW0lN0QlNjAlN0QlM0MlMkZwJTNFJTNCJTVDbiU3RCklM0IlNUNuZXhwb3J0JTIwY29uc3QlMjBUZXN0MlN0b3JlJTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSU3QnN0b3JlJTNBJTIwYW55JTdEKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAlM0NwJTNFJTNDU2xvdCUyRiUzRSUyMCU3QiU2MCUyNCU3QnByb3BzLnN0b3JlLnRleHQlN0QlMjBmbGFnJTNEJTI0JTdCcHJvcHMuc3RvcmUuZmxhZyUyMCUzRiUyMCdUJyUyMCUzQSUyMCdGJyU3RCUyMG51bSUzRCUyNCU3QnByb3BzLnN0b3JlLm51bSU3RCU2MCU3RCUzQyUyRnAlM0UlM0IlNUNuJTdEKSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMFRlc3QyQ2hpbGQlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDcCUzRSUzQ1Nsb3QlMkYlM0UlM0MlMkZwJTNFJTNCJTVDbiU3RCklM0IlNUNuJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwZGF0YSUyMCUzRCUyMHVzZVNpZ25hbCglN0J0ZXh0JTNBJ3Rlc3RpbmcnJTJDJTIwZmxhZyUzQSUyMGZhbHNlJTJDJTIwbnVtJTNBJTIwMSU3RCklNUNuJTIwJTIwY29uc3QlMjBzdG9yZSUyMCUzRCUyMHVzZVN0b3JlKCU3QnRleHQlM0EndGVzdGluZyclMkMlMjBmbGFnJTNBJTIwZmFsc2UlMkMlMjBudW0lM0ElMjAxJTdEKSU1Q24lMjAlMjByZXR1cm4lMjAlM0NkaXYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYnV0dG9uJTIwb25DbGljayUyNCUzRCU3QigpJTNEJTNFJTdCJTIwJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGNvbnN0JTIwdGV4dCUyMCUzRCUyMG5ldyUyMERhdGUoKS50b1N0cmluZygpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGRhdGEudmFsdWUlMjAlM0QlMjAlN0IlMjB0ZXh0JTJDJTIwZmxhZyUzQSUyMCFkYXRhLnZhbHVlLmZsYWclMkMlMjBudW0lM0ElMjBkYXRhLnZhbHVlLm51bSUyQjElMjAlN0QlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwc3RvcmUudGV4dCUyMCUzRCUyMHRleHQlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwc3RvcmUuZmxhZyUyMCUzRCUyMCFzdG9yZS5mbGFnJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHN0b3JlLm51bSUyQiUyQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0QlN0QlM0VDbGljayUyMG1lJTIwdG8lMjBjaGFuZ2UlMjB0aGUlMjBkYXRhJTNDJTJGYnV0dG9uJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2NvZGUlM0UlN0JKU09OLnN0cmluZ2lmeShkYXRhLnZhbHVlKSU3RCUzQyUyRmNvZGUlM0UlNUNuJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2gyJTNFU2lnbmFsJTNDJTJGaDIlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDVGVzdCUyMHRleHQlM0QlN0JkYXRhLnZhbHVlLnRleHQlN0QlMjBmbGFnJTNEJTdCZGF0YS52YWx1ZS5mbGFnJTdEJTIwbnVtJTNEJTdCZGF0YS52YWx1ZS5udW0lN0QlM0UxKSUyMFRleHQlMjB1cGRhdGVzJTJDJTIwYnV0JTIwJTNDYiUzRWZsYWclMjBvbmx5JTIwdXBkYXRlcyUyMHdoZW4lMjBzZXQlMjB0byUyMHRydWUlM0YlM0MlMkZiJTNFJTNDJTJGVGVzdCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NUZXN0U2lnJTIwc2lnJTNEJTdCZGF0YSU3RCUzRTFzaWcpJTIwV29ya3MuJTIwJTNDJTJGVGVzdFNpZyUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NUZXN0MiUyMHRleHQlM0QlN0IlNjAlMjQlN0JkYXRhLnZhbHVlLnRleHQlN0QlMjBmbGFnJTNEJTI0JTdCZGF0YS52YWx1ZS5mbGFnJTIwJTNGJTIwJ1QnJTIwJTNBJTIwJ0YnJTdEJTIwbnVtJTNEJTI0JTdCZGF0YS52YWx1ZS5udW0lN0QlNjAlN0QlM0UyKSUyMCUzQ2IlM0VOZXZlciUyMHVwZGF0ZXMlM0YlM0MlMkZiJTNFJTNDJTJGVGVzdDIlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDVGVzdDJTaWclMjBzaWclM0QlN0JkYXRhJTdEJTNFMnNpZyklMjBXb3Jrcy4lM0MlMkZUZXN0MlNpZyUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NUZXN0MkNoaWxkJTNFMmNoaWxkKSUyMFdvcmtzLiUyMCU3QmRhdGEudmFsdWUudGV4dCU3RCUyMGZsYWclM0QlN0JkYXRhLnZhbHVlLmZsYWclMjAlM0YlMjAnVCclMjAlM0ElMjAnRiclN0QlMjBudW0lM0QlN0JkYXRhLnZhbHVlLm51bSU3RCUzQyUyRlRlc3QyQ2hpbGQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDVGVzdDJDaGlsZCUzRTJjaGlsZCUyRmpzLXN0cmluZyklMjBXb3Jrcy4lMjAlN0IlNjAlMjQlN0JkYXRhLnZhbHVlLnRleHQlN0QlMjBmbGFnJTNEJTI0JTdCZGF0YS52YWx1ZS5mbGFnJTIwJTNGJTIwJ1QnJTIwJTNBJTIwJ0YnJTdEJTIwbnVtJTNEJTI0JTdCZGF0YS52YWx1ZS5udW0lN0QlNjAlN0QlM0MlMkZUZXN0MkNoaWxkJTNFJTVDbiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoMiUzRVN0b3JlJTNDJTJGaDIlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDVGVzdCUyMHRleHQlM0QlN0JzdG9yZS50ZXh0JTdEJTIwZmxhZyUzRCU3QnN0b3JlLmZsYWclN0QlMjBudW0lM0QlN0JzdG9yZS5udW0lN0QlM0UxKSUyMFdvcmtzLiUzQyUyRlRlc3QlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDVGVzdFN0b3JlJTIwc3RvcmUlM0QlN0JzdG9yZSU3RCUzRTFzdG9yZSklMjBXb3Jrcy4lMjAlM0MlMkZUZXN0U3RvcmUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDVGVzdDIlMjB0ZXh0JTNEJTdCJTYwJTI0JTdCc3RvcmUudGV4dCU3RCUyMGZsYWclM0QlMjQlN0JzdG9yZS5mbGFnJTIwJTNGJTIwJ1QnJTIwJTNBJTIwJ0YnJTdEJTIwbnVtJTNEJTI0JTdCc3RvcmUubnVtJTdEJTYwJTdEJTNFMiklMjAlM0NiJTNFTmV2ZXIlMjB1cGRhdGVzJTNGJTNDJTJGYiUzRSUzQyUyRlRlc3QyJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ1Rlc3QyU3RvcmUlMjBzdG9yZSUzRCU3QnN0b3JlJTdEJTNFMnNpZyklMjBXb3Jrcy4lM0MlMkZUZXN0MlN0b3JlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ1Rlc3QyQ2hpbGQlM0UyY2hpbGQpJTIwV29ya3MuJTIwJTdCc3RvcmUudGV4dCU3RCUyMGZsYWclM0QlN0JzdG9yZS5mbGFnJTIwJTNGJTIwJ1QnJTIwJTNBJTIwJ0YnJTdEJTIwbnVtJTNEJTdCc3RvcmUubnVtJTdEJTNDJTJGVGVzdDJDaGlsZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NUZXN0MkNoaWxkJTNFMmNoaWxkJTJGanMtc3RyaW5nKSUyMFdvcmtzLiUyMCU3QiU2MCUyNCU3QnN0b3JlLnRleHQlN0QlMjBmbGFnJTNEJTI0JTdCc3RvcmUuZmxhZyUyMCUzRiUyMCdUJyUyMCUzQSUyMCdGJyU3RCUyMG51bSUzRCUyNCU3QnN0b3JlLm51bSU3RCU2MCU3RCUzQyUyRlRlc3QyQ2hpbGQlM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGZGl2JTNFJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE

**Comment by manucorporat** [comment]
This is an amazing issue! I will work on it asap!

**Comment by manucorporat** [comment]
looking into the issue!
