### ISSUE TITLE
singleJSXRoot rule does not catch violations with <></> fragments

### ISSUE THREAD

**Issue by literalpie** [BuilderIO/qwik#2177]
### Qwik Version

0.13.3

### Operating System (or Browser)

macOS

### Which component is affected?

Starters / CLI

### Expected Behaviour

These two cases should have the same outcome - Either both violate the rule, or neither do (unless there's a specific technical reason)
Case 1:
`return isLoading ? <>Loading...</> : <div>The value is loaded</div>`
Case 2:
`return isLoading ? <div>Loading...</div> : <div>The value is loaded</div>`

### Actual Behaviour

Case 1 does not display an eslint warning, but case 2 does.

**Comment by manucorporat** [comment]
Agreed, both should violate or not, going to look into it.
