### ISSUE TITLE
[DOCS] Homepage Menu Button Does Not Work On IOS

### ISSUE THREAD

**Issue by tomzacchia** [BuilderIO/qwik#2178]
- Expected: menu button at https://qwik.builder.io/ works and shows “Docs, Qwik City, etc…”

- Actual: menu button does nothing. It only works on non-homepage routes

**Comment by manucorporat** [comment]
Should be fixed now! thanks for the issue

**Comment by tomzacchia** [comment]
@manucorporat TYVM!
