### ISSUE TITLE
[DOCS] Replace Netlify with Cloudflare on documentation page about the Cloudflare pages adaptor

### ISSUE THREAD

**Issue by Procee** [BuilderIO/qwik#2179]
**How can the documentation be improved?**

The page https://qwik.builder.io/qwikcity/adaptors/cloudflare-pages/ 

The pages contains texts like: 
```
Notice that you might need a [Netlify account](https://docs.netlify.com/get-started/) in order to complete this step!
```

And another one
```
Please refer to the Netlify docs for more information on how to deploy your site: [Netlify docs](https://docs.netlify.com/site-deploys/create-deploys/)
```

**Comment by manucorporat** [comment]
would you be so kind to open a PR with a change?
<img width="1461" alt="Screenshot 2022-11-19 at 10 12 54" src="https://user-images.githubusercontent.com/127379/202843801-4c3f46f0-3462-43de-862b-84ee76e42204.png">

**Comment by Procee** [comment]
[Sure](https://github.com/BuilderIO/qwik/pull/2186)
