### ISSUE TITLE
TodoMVC Express Starter appears to be broken

### ISSUE THREAD

**Issue by ryansolid** [BuilderIO/qwik#218]
A fresh install of the TodoMVC example doesn't appear to be working properly. The header doesn't render and I get the following error in dev:

```
Error: failed to load module for ssr: /src/components/header/h_header_header.js
    at instantiateModule (/Users/ryancarniato/Development/examples/qwik-todomvc/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60025:15)
Error: failed to load module for ssr: /src/components/footer/h_footer_footer.js
    at instantiateModule (/Users/ryancarniato/Development/examples/qwik-todomvc/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60025:15)
```
    
Steps to Reproduce:
1. `npm init qwik@latest`
2.  > ✔ Select a starter › Todo
✔ Select a server › Express
3. > npm i
npm run dev

Also appears `npm run build` fails as well:

```
vite v2.7.13 building for production...
✓ 2 modules transformed.
[vite:build-import-analysis] Parse error @:24:17
file: /Users/ryancarniato/Development/examples/qwik-todomvc/src/components/app/app.tsx:24:16
22:         <Main todos={props.todos} />
23:         <Footer todos={props.todos} />
24:       </section>
                    ^
25:     );
26:   });
error during build:
Error: Parse error @:24:17
    at parse$f (/Users/ryancarniato/Development/examples/qwik-todomvc/node_modules/vite/dist/node/chunks/dep-f5552faa.js:20847:353)
    at Object.transform (/Users/ryancarniato/Development/examples/qwik-todomvc/node_modules/vite/dist/node/chunks/dep-f5552faa.js:21106:27)
[!] Error: unfinished hook action(s) on exit:
(vite:load-fallback) load "/Users/ryancarniato/Development/examples/qwik-todomvc/node_modules/@builder.io/qwik/qwikloader.js"
(vite:load-fallback) load "/Users/ryancarniato/Development/examples/qwik-todomvc/node_modules/@builder.io/qwik/core.mjs"
```

**Comment by natebowang** [comment]
So does the starter partytown.

**Comment by manucorporat** [comment]
There been a lot of moving parts in the last days! can you try again!?

**Comment by ZeAmanuel28** [comment]
Yes it does not work at all. I tried the party town, starter express, starter cloudflare. in dev mode, vite server starts but can't render any thing to the screen. in prod build, the server build fails pointing to closing jsx tag. Please fix the problems. We need to try Qwik Quicker.

![Screenshot (1)](https://user-images.githubusercontent.com/96905008/154219632-40f327d5-65a7-4032-afc5-5cd69e352a05.png)

![Screenshot (2)](https://user-images.githubusercontent.com/96905008/154219682-0df0eeba-e2db-48d5-8c29-d8d541db1b3a.png)

**Comment by david-camdzic-gh** [comment]
Working fine now :) Thank you, @manucorporat

**Comment by david-camdzic** [comment]
Working fine now :) Thank you, @manucorporat

**Comment by ZeAmanuel28** [comment]
Sorry, but I am not seeing any change it is broken & I can't get a working dev or prod build. Is there any issue with windows PCs or node.js versions (I am using node 17) or with vite & compilation steps?

**Comment by david-camdzic** [comment]
@ZeAmanuel28 I am on latest fedora and npm init qwik@latest seems to be working for me. Will check windows in a bit.

**Comment by ZeAmanuel28** [comment]
No, the project creation is working but the build fails on the server build & the dev shows only white page without no content.

**Comment by joranbeasley** [comment]
I have this same issue running basic starter template just following quickstart guide :(   I just retried it today and the issue remains

this is on windows 10 with node 17.3.0

```bash
C:\qwik-test> npm init qwik@latest
C:\qwik-test> cd qwik-app && npm install && npm start

added 75 packages, and audited 76 packages in 8s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> qwik-app@0.0.0 start
> npm run dev


> qwik-app@0.0.0 dev
> vite

Pre-bundling dependencies:
  @builder.io/qwik/qwikloader.js
  @builder.io/qwik
  @builder.io/qwik/jsx-runtime
(this will be run only when your dependencies or config have changed)

  vite v2.8.0 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 924ms.
  ```
  Every thing looks fine but as soon as i go to the server i get a blank page and the following error in the console
  
  ```
  Error: failed to load module for ssr: /src/h_main_app_onmount.js
    at instantiateModule (C:\test-qwik\qwik-app\node_modules\vite\dist\node\chunks\dep-c9c9d3e5.js:56042:15)
 ```

**Comment by nilsriga** [comment]
Same

```
Error: failed to load module for ssr: /src/h_main_app_onmount.js
  at instantiateModule (C:\test-qwik\qwik-app\node_modules\vite\dist\node\chunks\dep-c9c9d3e5.js:56042:15)
```
