### ISSUE TITLE
Array change in store does not cause re-render

### ISSUE THREAD

**Issue by literalpie** [BuilderIO/qwik#2188]
### Qwik Version

0.13.3

### Operating System (or Browser)

Safari and Chrome

### Which component is affected?

Qwik Runtime

### Expected Behaviour

If a store is initialized with 'recursive', and you update an array of objects with a new array that has completely different items, that change should be reflected.

### Actual Behaviour

Changes are not reflected in child components, but they are reflected in the parent component.

### Additional Information

I tried setting the array by spreading `state.someArray = [...newValues];`, but that didn't work.
My current workaround is to loop through each item in the array and set the values. 

[Reproduction StackBlitz](https://stackblitz.com/edit/qwik-array-state-changes?file=src%2Froutes%2Fservice-worker.ts,src%2Froot.tsx,src%2Froutes%2Findex.tsx)

**Comment by gothammm** [comment]
Interesting bug.

I was trying it out, and noticed its more about the order of accessing the state itself.

Example: https://stackblitz.com/edit/qwik-array-state-changes-vbn3od?file=src%2Froutes%2Fservice-worker.ts,src%2Froot.tsx,src%2Froutes%2Findex.tsx

If you flip the lists the other way around, it works, seems like only the "first" accessor is reactive?
```
<h3>Other Component</h3>
    (these do not change, but the new item is shown)
    <ul>
      {state.someArray.map((v) => (
        <OtherComponent name={v.name}></OtherComponent>
      ))}
    </ul>
    <h3>In Same Component </h3>
    (this changes as expected)
    <ul>
      {state.someArray.map((v) => (
        <li>{v.name}</li>
      ))}
    </ul>
```

**Comment by gothammm** [comment]
https://stackblitz.com/edit/qwik-array-state-changes-rjebnj?file=src%2Froutes%2Findex.tsx&issueNumber=2188&issueRepo=BuilderIO/qwik I added `key` to when rendering `OtherComponent` and it works.
