### ISSUE TITLE
Drop Event Files List is always empty after optimized

### ISSUE THREAD

**Issue by tuoitrevohoc** [BuilderIO/qwik#2190]
### Qwik Version

0.13.3

### Operating System (or Browser)

Chrome / Safari (Mac)

### Which component is affected?

Qwik Runtime

### Expected Behaviour

On drop event, the `event.dataTransfer.files` should contain list of dropped files.

Code:
```javascript
import { component$ } from '@builder.io/qwik';

export default component$(() => {
  return <div
    preventdefault:dragover
    preventdefault:drop
    onDrop$={event => console.log(event.dataTransfer.files.length)}
  >Drop File Here</div>;
});

```

### Actual Behaviour

The list is always empty (size = 0) 

### Additional Information

Link to example with vanilla JS on code pen https://codepen.io/banhtieu/pen/OJEOaYj

```html
<script>
function onDragOver(event) {
  event.preventDefault();
}

function onDrop(event) {
  event.preventDefault();
  console.log(event.dataTransfer.files.length);
}

</script>
<div onDragOver="onDragOver(event)" onDrop="onDrop(event)">
  Drop File Here
</div>
```

**Comment by manucorporat** [comment]
Seems like this is the problem: https://stackoverflow.com/questions/55658851/javascript-datatransfer-items-not-persisting-through-async-calls

Tricky! need to check with the team how to solve this

**Comment by wahyufeb** [comment]
Same with me, the first time I tried dropped files and got 0 lengths of Files.
<img width="478" alt="Screen Shot 2023-02-14 at 9 27 40 AM" src="https://user-images.githubusercontent.com/38874570/218623304-3b88e3e6-c2cf-400e-bc41-289c768e9fba.png">

But the second time I dropped files it worked.
<img width="479" alt="Screen Shot 2023-02-14 at 9 27 58 AM" src="https://user-images.githubusercontent.com/38874570/218623440-0f013e11-bb12-4aab-8cd2-dbf630fa153c.png">

**Comment by manucorporat** [comment]
We added new docs in the site to explain how to handle events that MUST be syncrhonous!

**Comment by AnnMkrtchyan** [comment]
При перетаскивании того же файла на то же место у меня files массив иногда пустой, с чем это может быть связано?
