### ISSUE TITLE
useServerMount is executed on the client side after navigation

### ISSUE THREAD

**Issue by 4c656f** [BuilderIO/qwik#2196]
### Qwik Version

0.13.3

### Operating System (or Browser)

Mac OS 12.6.1 google chrome 104.0.5112.101

### Which component is affected?

Qwik Runtime

### Expected Behaviour

useSrverMount is executed only on the server and is not sent to the client side, after navigating from another page, useServerMount is executed only on the server

### Actual Behaviour

at the first request of the page on which the useServerMount is used, everything works correctly. however, if we use the link component leading to another page and also return to the page using useServerMount via Link, an error occurs
`Components using useServerMount() can only be mounted in the server, if you need your component to be mounted in the client, use "useMount$()" instead`

### Additional Information
reproduce: https://github.com/4c656f/qwikTry/tree/useServerMountError

_No response_

**Comment by manucorporat** [comment]
This PR should fix your issue:
https://github.com/BuilderIO/qwik/pull/2195

since we removed the exception, but notice that the useServerMount$() will still not run

**Comment by manucorporat** [comment]
We will release a new version tomorrow with this fix! in the meantime, you can use `useMount$()` and depend on:
```
import {isServer} from '@builder.io/qwik/build':
```
