### ISSUE TITLE
after link navigation useResource cause an error Invoking 'use*()' method outside of invocation context

### ISSUE THREAD

**Issue by 4c656f** [BuilderIO/qwik#2200]
### Qwik Version

0.13.3

### Operating System (or Browser)

Mac OS 12.6.1 google chrome 104.0.5112.101

### Which component is affected?

Qwik Runtime

### Expected Behaviour

executing useResource on the server or on client

### Actual Behaviour

at the first request of the page on which the useResource is used, everything works correctly, but if we go to a page that uses useResource from another page by Link it will cause an error:
```console
Code(14): Invoking 'use*()' method outside of invocation context. Error: Code(14): Invoking 'use*()' method outside of invocation context.
```

### Additional Information

reproduce: https://github.com/4c656f/qwikTry/tree/useResourceError

**Comment by manucorporat** [comment]
Not sure how to reproduce:
https://stackblitz.com/github/4c656f/qwikTry/tree/useResourceError?file=src%2Froutes%2Fproduct%2Findex.tsx

**Comment by 4c656f** [comment]
in fact, I restarted the local server and the error disappeared, I'm not sure if it's worth closing the issue or if the problem really exists

**Comment by 4c656f** [comment]
the error was caused by incorrect use of axios in useResource and most likely cached by the vite, I close the issue
