### ISSUE TITLE
Support for vite.config.js

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#2212]
### Is your feature request related to a problem?

Some developers do not use TypeScript.
And some developers develop on their laptops but run inside containers.

We are a team of developers (a company) that do not use TypeScript and we do not have Node.js installed on our machines.

We develop using VS Code, but we run inside containers.

For us, `vite.config.ts` is full of errors. If we change it to `vite.config.js` as we do for our React projects, errors would disappear, but then we get this error:

```
container | > start
container | > vite --mode ssr
container | 
container | ✘ [ERROR] Could not resolve "/Projects/SiteQwik/vite.config.ts"
container | 
container | failed to load config from /Projects/SiteQwik/vite.config.ts
container | error when starting dev server:
container | Error: Build failed with 1 error:
container | error: Could not resolve "/Projects/SiteQwik/vite.config.ts"
container |     at failureErrorWithLog (/Base/Qwik/node_modules/esbuild/lib/main.js:1566:15)
container |     at /Base/Qwik/node_modules/esbuild/lib/main.js:1024:28
container |     at runOnEndCallbacks (/Base/Qwik/node_modules/esbuild/lib/main.js:1438:61)
container |     at buildResponseToResult (/Base/Qwik/node_modules/esbuild/lib/main.js:1022:7)
container |     at /Base/Qwik/node_modules/esbuild/lib/main.js:1134:14
container |     at responseCallbacks.<computed> (/Base/Qwik/node_modules/esbuild/lib/main.js:671:9)
container |     at handleIncomingPacket (/Base/Qwik/node_modules/esbuild/lib/main.js:726:9)
container |     at Socket.readFromStdout (/Base/Qwik/node_modules/esbuild/lib/main.js:647:7)
container |     at Socket.emit (node:events:513:28)
container |     at addChunk (node:internal/streams/readable:324:12)
```

### Describe the solution you'd like

No solution yet. We just tolerate a lot of red squiggly lines.

### Describe alternatives you've considered

We should be able to not use TypeScript at all.

We should be able to have `vite.config.js` instead of `vite.config.ts`

**Comment by manucorporat** [comment]
The `package.json` is pointing to `vite.config.ts` if you change the filename, update package.json scripts to point to the different file!
