### ISSUE TITLE
qwik-city: Add a client side onFetch/onRequest page handler

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#2216]
### Is your feature request related to a problem?

To improve static builds and the migration process from a traditional SPA, it would be helpful to have a method similar to `onGet` that fires on both the server during SSR and loads+fires on the client during subsequent route changes. Much like a standard QRL.

This can then allow static sites and more SPAs to:

- Prefetch route data with Link components
- Throw redirects on the client, not just server side `onGet`
- Update the document head on the client
- Store data in localstorage
- Maintain existing frontend caching libraries
- Quicker client side route guards with redirects

### Describe the solution you'd like

I'd like to have a similar function to the `onGet` functions that will run on both the client and the server.
It should run during link prefetching.

If possible, the data returned could be added to the scope of the `DocumentHead` function.

I'd say `onFetch` would be the best solution. This is how I'd make this work:
- Add a `onFetch` prop to the `<Link />` component that takes in a QRL
- Call the onFetch callback if it exists with the `prefetchLinkResources `
- At build time, check if any route exports an `onFetch` function and update any corresponding Link components to add their respective QRLs as onPrefetch props.
  - This actually doesnt seem entirely possible. hrefs can be dynamic, so how do we know what route is being request? We can try a best effort check and ignore if it cant be determined but that leaves extra work for the user to then manually set the prefetch
  - We could instead save the onFetch on the component as a property. Then preload the component file and call onFetch if it exists

**ISSUES**
- Could this create circular references?
- How does this get back to the document head function?

Possible names could be:
- `onFetch`
- `onRequest`
- `onPrefetch`
- `onClientGet` which could be client side only for complete separation

### Describe alternatives you've considered

I've considered creating my own link component. But the document head problem still exists.

### Additional context

I'd be more than happy to submit a PR if this gets a green light!

**Comment by manucorporat** [comment]
You can do this already using useResource(): https://qwik.builder.io/docs/components/resource/

during ssr it will be executed in the server and if changes in client, it will run in the browser

**Comment by DustinJSilk** [comment]
@manucorporat but a useResource doesn't get prefetched when hovering on links, nor will the data returned be added to the (dynamic document head)[https://qwik.builder.io/qwikcity/content/head/#dynamic-document-head] function. 

Unless I've missed something?

**Comment by DustinJSilk** [comment]
@manucorporat friendly nudge, if you have a moment to give this some thought.
I'm happy to work on a PR.
