### ISSUE TITLE
Slot content projection doesn't load mdx components

### ISSUE THREAD

**Issue by adamdbradley** [BuilderIO/qwik#222]
In the docs site, when the Layout components wraps a content component (built from mdx), the content does render, but if the content has a child component it doesn't render.

Main component: https://github.com/BuilderIO/qwik/blob/844a1b2c03bdb685dfb4e11cc7e48c83e1e170a1/docs/site/src/main.tsx#L18-L20

Layout component w/ Slot:
https://github.com/BuilderIO/qwik/blob/844a1b2c03bdb685dfb4e11cc7e48c83e1e170a1/docs/site/src/layouts/docs/docs.tsx#L25

The bootstrap.mdx file has a `<Counter/>` component: https://github.com/BuilderIO/qwik/blob/844a1b2c03bdb685dfb4e11cc7e48c83e1e170a1/docs/guide/bootstrap.mdx

The counter component works when not using slot and wiring up the bootstrap component directly.

**Comment by mhevery** [comment]
Add this to `render.unit.ts`
```typescript
    it.only('should render nested component when it is projected by parent', async () => {
      const Layout = component$(
        () => {
          return $(() => (
            <div>
              <Slot />
            </div>
          ));
        },
        { tagName: 'layout' }
      );
      const Content = component$(
        () => {
          return $(() => (
            <span>
              <Slot />
            </span>
          ));
        },
        { tagName: `content` }
      );
      await render(
        fixture.host,
        <Layout>
          <Content>projection</Content>
        </Layout>
      );
      console.log(prettyHtml(fixture.host));
      expectRendered(
        <layout>
          <template />
          <div>
            <q:slot>
              <content>
                <template />
                <span>
                  <q:slot>projection</q:slot>
                </span>
              </content>
            </q:slot>
          </div>
        </layout>
      );
    });
```

**Comment by manucorporat** [comment]
Fixed https://github.com/BuilderIO/qwik/commit/7fadd186e2358c95cd5902a800c24b448e6d19c5
