### ISSUE TITLE
[DOCS] Fix dark mode styling

### ISSUE THREAD

**Issue by xyntechx** [BuilderIO/qwik#2220]
**How can the documentation be improved?**
Currently, some text is still coloured black instead of white despite the website being in dark mode. I'd love to fix that, but I'm not sure which file in this repo corresponds to the homepage of https://qwik.builder.io/. I'd appreciate your help in directing me to the right file/folder/repo 😁

**Comment by Varixo** [comment]
It is not that easy because the homepage is actually a builder resource (so there are no files in repo). This should be fixed soon I believe.

**Comment by xyntechx** [comment]
Ah I see! If we were to change up the file you linked, how would we see the preview of the website?

**Comment by Varixo** [comment]
I think just run docs locally (as I did before :D). There is a workspace called docs and script start inside:
https://github.com/BuilderIO/qwik/blob/ed49559661c9ed1c2ee11bbb34366eb7b8321753/packages/docs/package.json#L19

**Comment by xyntechx** [comment]
Cool! They seem to have fixed it, so I'll have to put your advice to good use some other time. Thanks a ton :D
