### ISSUE TITLE
IMG Models is launching their new (non-qwik) full site, retiring the page (not a repudiation)

### ISSUE THREAD

**Issue by VinSpee** [BuilderIO/qwik#2223]
https://github.com/BuilderIO/qwik/blob/34daedbb0bb6217052e0e6d74244542ea0c751e7/packages/docs/src/routes/showcase/generated-pages.json#L52

IMG Models is launching their new non-qwik full site. This landing page was a stop-gap for them between the previous site and the next.

I will keep it accessible at https://img-models.vercel.app if you want to update the link!

**Comment by mhevery** [comment]
Can you provide some feedback as to why Qwik was not the right fit for you?

**Comment by VinSpee** [comment]
> Can you provide some feedback as to why Qwik was not the right fit for you?

This is absolutely _not_ the case – We were happy with Qwik and I am still eyeing it for any project we take on in the future.

This interim landing page was build in a hurry by my team as a favor to another team which contracts with other teams to maintain and build the entire site. I'm happy to discuss the details on discord with you @mhevery if they'd help, but essentially, two separate teams were responsible with two different expertises and skillsets.

**Comment by mhevery** [comment]
OK, I will reach out on Discord. Thanks for the details.
