### ISSUE TITLE
Static files cannot be generated using useEndpoint

### ISSUE THREAD

**Issue by sanqi** [BuilderIO/qwik#2234]
### Qwik Version

0.14.0

### Operating System (or Browser)

chrome

### Node Version (if applicable)

Node.js v17.6.0

### Which component is affected?

Qwik City

### Expected Behaviour

After upgrading qwik-city 0.0.122 to 0.0.124

### Actual Behaviour

0.0.124 cloudflare-pages cannot generate static files using useEndpoint

**Comment by sanqi** [comment]
For versions after qwik-city 0.0.122, the cloudflare-pages adapter cannot generate correct static files, If I use the `useEndpoint ` function in a route file.
new version breaks  cloudflare-pages adapter's function of generating static files, which was not the case before.

**Comment by manucorporat** [comment]
would you expect to generate a static page instead of SSR?

**Comment by sanqi** [comment]
I configured cloudflarePagesAdaptor with `staticGenerate: true`,  so I want to keep generating static files even with `useEndpoint`.

If I want to use SSR, I just need to remove staticGenerate, this is easy to do in old version to control SSR or SSG switching, current new version breaks this

In the new version, even if I configure the Dynamic SSG Routes function, I cannot turn on SSG to generate static files.

**Comment by manucorporat** [comment]
now it's doing both SSR + SSG, dynamic paths use SSR, but i see the confusion

**Comment by adamdbradley** [comment]
So when you do have `staticGenerate: true`, any dynamic pages you'd like to SSR instead of SSG are not working. Would you be able to create a minimal example showing the issue? Thanks

**Comment by adnanebrahimi** [comment]
For example, I have Ghost as headless CMS, I like to fetch articles during the build and generate static files.

**Comment by adnanebrahimi** [comment]
@adamdbradley 
I created an example:
https://github.com/adnanebrahimi/qwik-ssg-cloudflare-adaptor
