### ISSUE TITLE
[📖] Why 3 pages don't have a menu on the right ?

### ISSUE THREAD

**Issue by forresst** [BuilderIO/qwik#2238]
### Suggestion

In the documentation, the following 3 pages do not have a menu on the right (ON THIS PAGE, MORE, Edit this page, etc):
- [Guides -> Overwiew](https://qwik.builder.io/docs/overview/)
- [Guides -> Getting Started](https://qwik.builder.io/docs/getting-started/)
- [Guides -> Think Qwik](https://qwik.builder.io/docs/think-qwik/)

On closer inspection, the file [layout!.tsx  on line 12](https://github.com/BuilderIO/qwik/blob/main/packages/docs/src/routes/docs/layout!.tsx#L12) contains a feature to remove the menu on the right for these 3 pages.

Is this intentional and why?

I can make a PR so that these 3 pages display the menu on the right while keeping the `noRightMenu` functionality by making the following change in line 12:

```diff
- const noRightMenu = ['/docs/getting-started/', '/docs/overview/', '/docs/think-qwik/'].includes(
+ const noRightMenu = [''].includes(
```

**Comment by manucorporat** [comment]
Designers!

**Comment by manucorporat** [comment]
honeslty i still like the idea of hiding the right menu for the override page, little value, content is king.
Maybe for getting-starter and think-qwik we can show the menu
