### ISSUE TITLE
[✨] Integration with Fastify

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#2240]
### Is your feature request related to a problem?

We are support already netlify, vercel and cloudflare! we want more deployment integrations. In order to add a new one folder needs to be created here, with the necesary configuration for Fastify:
https://github.com/BuilderIO/qwik/tree/main/starters/adaptors

### Describe the solution you'd like

Nop

### Describe alternatives you've considered

Nop

### Additional context

Join the discord and text in the #contributions channel! the core team will be happy to guide you make the PR!

**Comment by git-anurag-hub** [comment]
Hey! Love the project will love to contribute to this issue! (Just needed a follow up).

**Comment by manucorporat** [comment]
please!! I would try to get fastify working locally in an app then hack the rest!

**Comment by git-anurag-hub** [comment]
Hey @manucorporat, thanks for the help! 
I tried making the demo qwik-app work with fastify but while doing so I have a doubt about how will I test the app with my own version of the qwik-city? Sorry about the newbie question.
