### ISSUE TITLE
[✨] Qwik + Vue

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#2241]
### Is your feature request related to a problem?

Qwik can partial hydrate other frameworks, that means you can have React components inside your Qwik app already!
https://qwik.builder.io/qwikcity/integrations/react/

We want to extend this effort to other frameworks like Vue, Svelte, Solid, Lit...

Check out how we hack together Vue + Qwik
https://www.youtube.com/watch?v=XEaSmlUiubs

### Describe the solution you'd like

Nop

### Describe alternatives you've considered

Nop

### Additional context

Join the discord and text in the #contributions channel! the core team will be happy to guide you make the PR!

**Comment by lzxb** [comment]
I want to use it with Vue2 SSR now, and migrate to qwik gradually later

**Comment by zanettin** [comment]
WIP PR can be found here https://github.com/BuilderIO/qwik/pull/2248

**Comment by BingoTrush** [comment]
I also try to find the guide for hack together Vue + Qwik. Can you share the source code, thanks.

**Comment by gioboa** [comment]
As explained in the PR we closed, these types of integrations will not be part of the core code base, but instead an external integration.
So I close this issue. Thanks.
