### ISSUE TITLE
[✨] Qwik + Solid

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#2242]
### Is your feature request related to a problem?

Qwik can partial hydrate other frameworks, that means you can have React components inside your Qwik app already!
https://qwik.builder.io/qwikcity/integrations/react/

We want to extend this effort to other frameworks like Solid!

Check out how we hack together Vue + Qwik
https://www.youtube.com/watch?v=XEaSmlUiubs

### Describe the solution you'd like

Nope

### Describe alternatives you've considered

Nope

### Additional context

Join the discord and text in the #contributions channel! the core team will be happy to guide you make the PR!

**Comment by voluntadpear** [comment]
I'm working actively in the Qwik + Solid integration!

I'll show additional advances soon. Right now I shared a little bit in [a message in the Discord channel](https://discord.com/channels/842438759945601056/942509201425575986/1043189049239814245) but more to come.

**Comment by B-R-P** [comment]
> I'm working actively in the Qwik + Solid integration!
> 
> I'll show additional advances soon. Right now I shared a little bit in [a message in the Discord channel](https://discord.com/channels/842438759945601056/942509201425575986/1043189049239814245) but more to come.

Is there any advances? How can I use Qwik and Solid JS together?

**Comment by voluntadpear** [comment]
@B-R-P Yes, there's https://github.com/BuilderIO/qwik/pull/2291 that works quite well! The API is the same as `qwikify$` for React and so far it works for my test use cases.
However, more testing is necessary to find edge cases.
Unfortunately, I haven't worked on the README yet so you'll need to get a bit comfortable with the Qwik repo to run it.

**Comment by Dindaleon** [comment]
I am starting a new project and can't decide whether to use qwik or solid so I am wondering if we mix qwik with solid, Do we get the routing and loading advantages from qwik and the rendering advantages from solid? If am not mistaken, solid is very fast at rendering (reactivity)

**Comment by gioboa** [comment]
As explained in the PR we closed #2291, these types of integrations will not be part of the core code base, but instead an external integration.
So I close this issue. Thanks.
