### ISSUE TITLE
[🐞] Inconsistent reactivity with class / className

### ISSUE THREAD

**Issue by jwickers** [BuilderIO/qwik#2245]
### Which component is affected?

Qwik Runtime

### Describe the bug

Setting a class directly from a signal or store does not appear to react to changes, though wrapping it in an array or string template seems to do the trick.

### Reproduction

https://stackblitz.com/edit/qwik-starter-bmqdha

### Steps to reproduce

The stackblitz page has 3 links
- the first is the original issue
- the second shows a runtime error when assigning to a component class from a boolean ternary test
- the third shows that className from a boolean ternary test works, and the extra assignment seems to have the side effect of fixing the className value when directly from a store or signal as well

### System Info

```shell
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.14.0 => 0.14.0 
    @builder.io/qwik-city: 0.0.118 => 0.0.118 
    vite: 3.2.1 => 3.2.1 
```

### Additional Information

Qwik City was intentionally downgraded to 0.0.118 for stackblitz to work properly.

**Comment by wmertens** [comment]
Possibly fixed by #2230 @manucorporat ?

**Comment by manucorporat** [comment]
Please fill the issue template :) run:
```
npx envinfo --system --npmPackages '{vite,@builder.io/*}' --binaries --browsers
``` in stackblitz

**Comment by jwickers** [comment]
> Please fill the issue template :) run:
> 
> ```
> npx envinfo --system --npmPackages '{vite,@builder.io/*}' --binaries --browsers
> ```
> 
> in stackblitz

Added the info, also fixed the stackblitz thanks to [wmertens](https://github.com/wmertens) by downgrading Qwik City.

**Comment by jwickers** [comment]
> Possibly fixed by #2230 @manucorporat ?

Hopefully, anyway this issue can be an interesting test case for it.

**Comment by manucorporat** [comment]
lets test again with:
```
    "@builder.io/qwik": "latest",
    "@builder.io/qwik-city": "0.0.127",
```

**Comment by jwickers** [comment]
Yes, I have the same issue on 0.14.1 and latest, can't update QC from 118 as it breaks stackblitz but the issue should be in qwik runtime.

**Comment by manucorporat** [comment]
WOW! The repo case is amazing @jwickers! i will be working on it today!
Thanks a lot for your effort to put it together!
