### ISSUE TITLE
[✨] useEndpoint should handle query (search) params when reacting to location href changes

### ISSUE THREAD

**Issue by jwickers** [BuilderIO/qwik#2250]
### Is your feature request related to a problem?

The `useEndpoint` hook is tracking location href allowing a page to refetch its resource on the client but the `loadClientData` implementation only considers the pathname when fetching the page data.

So for example a page could display a list that could be optionally sorted, filtered etc ... where query params like `/users/?sortBy=name` where `sortBy` is handled in the `onGet` method.

### Describe the solution you'd like

It looks like the `/q-data.json` work when called manually with query params, so fetching the data from the endpoint could just forward the query params to `/q-data.json` as `/q-data.json?sortBy=name`.

### Describe alternatives you've considered

Not using location.href makes client side refresh of `useEndpoint` impossible so instead one would have to have a separate resource to handle extra params making the page very complicated.

**Comment by manucorporat** [comment]
almost feel like a bug it's not doing it today!

**Comment by jwickers** [comment]
I'm making a PR so it's definitely not a bug ;)

**Comment by jwickers** [comment]
Change is extremely simple though, hopefully there are no particular issue to this change. It would make my current page hacking window.pushstate and having different nsested resource simpler.

**Comment by manucorporat** [comment]
Closing issue! since we are releasing now! Thanks a lot for the fix :)
