### ISSUE TITLE
[✨] Easily find JSX node while debugging

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#2252]
### Is your feature request related to a problem?

When building an app it's usually a common workflow to open the site, design and then go back to the source code to change the template, aka the JSX. Today we already serialize the relevant information of were each DOM node correspond to the exact location of the JSX in the source code.

It should be trivial to implement something like this: https://www.locatorjs.com/

In fact i would argue that Qwik need to overachieve in terms of DX, and this should be included by default in all starters.

I am suggesting to have this funcionality built-in, not support for locatorjs in specific!

### Describe the solution you'd like

Similar to https://www.locatorjs.com/

### Describe alternatives you've considered

Full devtools, but i think this feature is better scoped and faster to implement, full devtools can come later

**Comment by zanettin** [comment]
@manucorporat can we close this one? it's already in place ❤️

**Comment by manucorporat** [comment]
Good point! Yes it's done!
