### ISSUE TITLE
[🐞] css is not loaded in unit tests using vitest

### ISSUE THREAD

**Issue by 111Rick111** [BuilderIO/qwik#2261]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

Cannot run tests for styled components: styles are not imported and causing unit tests to fail.

### Steps to reproduce

Create a new app, add vitest and css file:
- npm create qwik@0.13.3
- npm run qwik add vitest
- echo ".smth { color: red } " > src/components/example/example.css

After that open the new `example.tsx` component and add import
```
import styles from './example.css?inline';
console.log('imported styles: ', styles); 
```

when running `npx vitest --run`, this console log will print `imported styles: undefined`.
If this further used with `useStylesScoped$(styles);`, the test will fail

### System Info

```shell
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 452.06 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 96.0.3
    Safari: 14.0
  npmPackages:
    @builder.io/qwik: ^0.13.3 => 0.13.3 
    @builder.io/qwik-city: 0.0.123 => 0.0.123 
    vite: 3.2.3 => 3.2.3
```

**Comment by leifermendez** [comment]
HI @111Rick111 let'me check it

**Comment by dmitry-stepanenko** [comment]
Update on this one: looks like with `vitest >= 0.27` inline imports are resolved to an empty string instead of `undefined`. This prevents qwik from failing in unit tests, however it might still be an issue related to dimensions of html elements or their visibility (`display: none`) in unit tests.

**Comment by manucorporat** [comment]
Vitest does not use a real browser, styling does not apply! This should be good enough, closing unless there is some use case for actual CSS!
