### ISSUE TITLE
[✨] Project templates should call `useStylesScoped$` by default

### ISSUE THREAD

**Issue by dzearing** [BuilderIO/qwik#2272]
### Is your feature request related to a problem?

I think there are 2 problems here:

* When generating the docsite project template, I believe component styles should be scoped per component by default, and global styles should be reserved for resets only. This helps lead devs to good practices.
  * What: Instead of  `useStyles$` in components, `useStylesScoped$`
  * Why: always unique, resilient to load order issues, allows for less specificity, semantic, scales better over time/number of devs working on projects that don't carry over tribal knowledge.
* Without knowing about `useStyledScope$`, devs might expect css modules to work, and rename the files to *.module.css. (This is what I did.) When changing it to use css modules, there are rough edges and you start fighting typing issues. There is probably an opportunity here to deprecate `*.module.{s?css}` imports and direct them to `useStylesScoped$`.
  * server-modules.d.ts deprecates css imports without `?inline` - even for `*.module.css`, but this changes the default import typing result to return a string, rather than a class map.
  * It is very unclear how to get css modules working with `useStyles$` at this point. Even changing that to with `useStylesScoped$` wouldn't work, since it expects a css string as input. (Deprecating module.{s?css} might allow for a link describing a better approach.

CSS is a complex topic; rules are prone to specificity concerns, and this becomes exacerbated by the asynchronous nature of Qwik. Highly recommend to avoid some of the race conditions by encouraging scoped css by default.

### Describe the solution you'd like

Update project templates to use `useStylesScoped` for components and avoid global selectors for anything other than the reset css.

### Describe alternatives you've considered

Tried changing things to css modules, but the support doesn't seem to be there any more (I believe this once worked.)

**Comment by manucorporat** [comment]
We are actually very unsure useStyleScoped is the right solution, compared to CSS modules, vanilla extract or new ideas we want to try in the future, it's unlikely we will make this the default option in starters!
