### ISSUE TITLE
[🐞] client navigation and useResource has side effects that can cause Qwik runtime errors

### ISSUE THREAD

**Issue by jwickers** [BuilderIO/qwik#2276]
### Which component is affected?

Qwik City (routing)

### Describe the bug

The stackblitz example illustrates it better can be explained, but AFAICT the `useResource` `onReolved` data seems to reset to undefined when the page goes away from a SSR state to a client navigation (either via `Link` or `useNavigate`) which causes the current page component to first be loaded client side in order to re-render with this **new** state before rendering the target page component.

This has some side effects as some guards are then required for cases that normally cannot happen, like this data being `undefined`.

Sometimes a guard on the resource resolved data is not enough and on one of my pages I had to do something like that to avoid this error:
```js
onResolved={(categoryData) => (
	<>
		{categoryData ? (
			<>
				{categoryData.breadcrumbs || categoryData.category ? (
					<Breadcrumbs
						breadcrumbs={categoryData.breadcrumbs}
						category={categoryData.category}
					/>
				) : (
					<></>
				)}
			</>
		 ) : (
			<></>
		)}
	</>
)}
```

Ideally, it should not have to re-render the current page component, only the target page.

### Reproduction

https://stackblitz.com/edit/qwik-starter-ahyevv

### Steps to reproduce

- run `npm install` and `npm start`
- make sure you have the Dev Tools open as the Qwik error will log in the console and cause the debugger to activate

### System Info

```shell
In stackblitz:
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.14.1 => 0.14.1 
    @builder.io/qwik-city: 0.0.118 => 0.0.118 
    vite: 3.2.1 => 3.2.1 

On dev machine:
  System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 7.22 GB / 64.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
  npmPackages:
    @builder.io/partytown: ^0.7.2 => 0.7.2
    @builder.io/qwik: 0.14.1 => 0.14.1
    @builder.io/qwik-city: 0.0.127 => 0.0.127
    vite: 3.2.4 => 3.2.4

Note: stackblitz Qwik City intentionally at 0.0.118 to have navigation working there, but both versions are affected.
```

**Comment by manucorporat** [comment]
I believe this is not longer an issue since we removed useEndpoint() in favor of loader!
