### ISSUE TITLE
[🐞] Static tree-shaking: unreachable code not removed

### ISSUE THREAD

**Issue by utherpally** [BuilderIO/qwik#2278]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

```ts
// src/routes/dev.ts
export const inDev = import.meta.env.DEV; // will replace by false when run production build

// src/routes/index.ts
import { component$ } from '@builder.io/qwik';
import { inDev } from '../dev';

// This block should be remove in production
if (inDev) {
  console.log('GLOBAL FAILED');
}

function test() {
 // This block should be remove in production
  if (inDev) {
    console.log('INSIDE FUNCTION FAILED');
  }
  console.log('');
}

test();

export default component$(() => {

  // This block should be remove in production
  if (inDev) {
    console.log('INSIDE COMPONENT FAILED');
  }

  return (
    <h1>
      Welcome to Qwik <span class="lightning">⚡️</span>
    </h1>
  );
});

```
Run `npm run build` and search `FAILED` inside dist,server folders

Expect: No results
Actually:

<table>
<tr>
	<td>Folder
	<td>Result count
<tr>
	<td>dist
	<td>3
<tr>
	<td>server
	<td>1
</table>

Note: change condiitons to `import.meta.env.DEV` directly, everything work as expected

### Reproduction

https://stackblitz.com/edit/qwik-starter-ifskcz?file=src%2Froutes%2Findex.tsx,package.json,src%2Fdev.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.14.1 => 0.14.1 
    @builder.io/qwik-city: 0.0.126 => 0.0.126 
    vite: 3.2.4 => 3.2.4
```

### Additional Information

Test with some other vite based frameworks/libs like vanilla typescript, vue, svelte work as expected.

**Comment by manucorporat** [comment]
interesting... we are using the same vite... wondering why it's not working in qwik, this code elimitation is done by vite/rollup/esbuild

**Comment by langbamit** [comment]
@manucorporat If I replace all `moduleSideEffects: false` => `moduleSideEffects: true` inside `@builder.io/qwik/optimizer.{mjs/cjs}` before run, its resolved <b>this</b> issue but maybe fire another bunch of issues

**Comment by manucorporat** [comment]
This should be fixed! also even better now:
```
import {isDev} from '@builder.io/qwik/build`
```
will evne work in library mode!
