### ISSUE TITLE
Implement reactive useLocation()

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#228]
createStore() backed useLocation()

**Comment by manucorporat** [comment]
Done! as part of qwikcity

**Comment by iamriajul** [comment]
@manucorporat How does the reactivity work? does it reconcile with the client/browser? For example in cases where server response is cached without `searchParams` does it recheck on the browser if the URL has changed after resuming the qwik component?

Thanks.

**Comment by wmertens** [comment]
@iamriajul I had a look but it's a bit complex. I'd assume that it only reacts to events, so when the page history API says the URL changes. Best to just try it out.

**Comment by iamriajul** [comment]
Tried with a SSG page, they didn't work. 

I think this should be supported. 

Current workaround can be using visibleTask$ with combined window.location.

**Comment by wmertens** [comment]
The problem with this use case is that it requires walking up the framework just to check if the url changed. I think it's a pretty rare case too, so the workaround seems like the best approach.
