### ISSUE TITLE
[🐞] Returning non-primitive data from RequestHandler crashes dev server

### ISSUE THREAD

**Issue by mlynch** [BuilderIO/qwik#2281]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When returning non-primitive or object data from a `RequestHandler` (such as `onGet`), the dev server will crash with the error

```
QWIK ERROR Code(3): Only primitive and object literals can be serialized [Function: entries] Error: Code(3): Only primitive and object literals can be serialized
    at logError (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:73:58)
    at logErrorAndStop (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:79:21)
    at qError (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:143:16)
    at _verifySerializable (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:5948:19)
    at _verifySerializable (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:5938:29)
    at verifySerializable (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:5907:16)
    at ReadWriteProxyHandler.set (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:1105:17)
    at setState (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:5149:40)
    at E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:5179:13
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Code(3): Only primitive and object literals can be serialized
    at logError (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:73:58)
    at logErrorAndStop (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:79:21)
    at qError (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:143:16)
    at _verifySerializable (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:5948:19)
    at _verifySerializable (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:5938:29)
    at verifySerializable (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:5907:16)
    at ReadWriteProxyHandler.set (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:1105:17)
    at setState (E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:5149:40)
    at E:\GitHub\qwik-demo\node_modules\@builder.io\qwik\core.cjs:5179:13
```

Example that triggers this:

```typescript
export const onGet: RequestHandler<{ items: any }> = async ({ params }) => {
  return {
    items: new Map()
  };
};
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-lpe3ap?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

`npm run dev` and return non-primitive or object data from RequestHandler, notice the dev server crashes. Tested and reproduced on Windows 11 and stackblitz web container

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 15.88 GB / 31.93 GB
  Binaries:
    Node: 16.15.1 - ~\AppData\Local\Volta\tools\image\node\16.15.1\node.EXE
    npm: 8.11.0 - ~\AppData\Local\Volta\tools\image\node\16.15.1\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @builder.io/qwik: 0.14.1 => 0.14.1
    @builder.io/qwik-city: 0.0.127 => 0.0.127
    vite: 3.2.4 => 3.2.4
```

### Additional Information

This is definitely an error case but shouldn't crash the dev server and require the server to be restarted

**Comment by manucorporat** [comment]
Max! happy to see you here, reason for this is that onGet might be requested from client side too through a fetch if SPA, thinking how we either: support more complex types, or state that things need to be JSON serializable 

cc @adamdbradley

**Comment by mlynch** [comment]
🤓 it’s been fun!

to be clear the issue is only that the dev server fully crashes and the process exits. It’s understandable that there’s a limit to types here (Capacitor has the same limitation)

**Comment by adamdbradley** [comment]
Actually what if it was restricted by types, instead of a runtime check? Following this example: https://dev.to/ankittanna/how-to-create-a-type-for-complex-json-object-in-typescript-d81

So we'd use: 

```typescript
type JSONValue =
    | string
    | number
    | boolean
    | { [x: string]: JSONValue }
    | Array<JSONValue>;
```

And the `RequestHandler` would default `BODY` to `JSONValue`.

```typescript
export type RequestHandler<BODY = JSONValue, PLATFORM = unknown> = (
  ev: RequestEvent<PLATFORM>
) => RequestHandlerResult<BODY>;
```

One question though, if someone provided their own type, and it wasn't valid, how could we still have type errors?

So if they had

```typescript
interface MyInvalidJSONValue {
  value: Set<string>;
}

export const onGet: RequestHandler<MyInvalidJSONValue> = ({ request }) => {
  return {
    value: new Set()
  };
};
```

What's the best way to say `MyInvalidJSONValue` is invalid.

**Comment by nnelgxorz** [comment]
Wouldn't you want BODY to extend JSONValue?

**Comment by nnelgxorz** [comment]
So, BODY can be anything that's assignable to JSONValue.

**Comment by adamdbradley** [comment]
So we're close I think with:

```typescript
export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;

export type RequestHandler<BODY extends JSONValue = JSONValue, PLATFORM = unknown> = (
  ev: RequestEvent<PLATFORM>
) => RequestHandlerResult<BODY>;
```

And it'd correctly have a type error with something like:

```typescript
export const onPut: RequestHandler = ( ) => {
  return {
    test: new Set()
  };
};
```

And would correctly not have any type errors for:

```typescript
export const onPut: RequestHandler = ( ) => {
  return {
    test: 'foo'
  };
};
```

But haven't figure out how to have a custom interface apply as a generic if the custom interface doesn't have an index type. For example, this correctly does not have errors because `MyData` has the `[key: string]: string;`:

```typescript
interface MyData {
  test: string;
  [key: string]: string;
}

export const onPut: RequestHandler<MyData> = () => {
  return {
    test: 'foo',
  };
};
```

However, if it doesn't have the index, it has a typescript error:

```
Type 'MyData' does not satisfy the constraint 'JSONValue'.
  Type 'MyData' is not assignable to type '{ [x: string]: JSONValue; }'.
    Index signature for type 'string' is missing in type 'MyData'.
```

Any ideas?

**Comment by mhevery** [comment]
I don't think that is possible. see [Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAUgygeQHIDUCGAbArtAvAKCiKgB8oBnYAJwEsA7Ac0OLLqwFsAjCK5oszgHtBGCGjp9SUAApoqwGpgA8AbygBtAB4AuCtXoMAurvjJ02aAF8AfJLIBBKlTQglp1JhzWA3Pj8RNMEF5KHpgHgAzNABjaABZEAARNGA0KBVJCOFdSlpGfEs-AHoiqABJKAATQToAcmAoAGs6QQB3KAALNqhgQSh2NEboYA7oOgCGjHoxwQbyLvbxKB4qYIA6fACgkOiayigAK3Iak0QPCyhcKDYMDABCKDRyKATk1N8gA)

**Comment by nnelgxorz** [comment]
I'll play around with it later. 👍

**Comment by manucorporat** [comment]
Opened this issue in typescript! https://github.com/microsoft/TypeScript/issues/51679

**Comment by KenParsons** [comment]
With this helper we can know if a given type OR interface  is valid json. Then use conditionally as needed. Thoughts?
[Playground with examples and testing](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgSwLYOAgbtAvFAzsRAOwHMoAfKQgVyQCMI5ypaB7FgGwgENCAoXgPQCoAYTjdg0LlFCQoAMxaMAUgGUA8gDk8DBF3YIAXl1qco6fVQi5es6Gq0A1S9l5R3TeMlQYIbjxQA3lAA2gDWECAAXHgECCQAujEOms7sVlAAvv7uFACCcHBcIAA8KWlWAHwA3PxCmiwA7lCN0ADGPFAAFlyYUCxUjF0Q7JCMdjIsUNy4COwgUGGETTJwVgLy+rjQCPJQqADkuOb6CAAmUABWuCx8EwCSuGnnyjeEJTlQACrgEOpw90IkjgmzaEAANFBPgBpSLHHAREAsPY-SD-QHA0EQqEeKAVaxQHCov4AoEMLHhSLI76-dFkkFcMEJXiVQk0tGkzGM6AQAAekkIZ2OXhQaD6AH5VhkYrCQMc+QKhVByi4oJL8fL+RBBccVeloJKCNKFFtoDFNuxtrV+IJhA1mpxgEcoGcpjckO1hm0wvFSIpGGA4CwxlKIBtTf0qMA2iwPVFeHywEpgPt6VioABZEAAES4wC4zwugU+ihYMXwRGIvGyMcI+BOBjOGPJ3Jij0Lr1uJSzufzhdZOCNEGtCd5SbgKfiXLBmZzea4gIsjagxdxpZivb82SEqgAEuoAKoAGWzzB5hSUvvjtfr8SX52bDLBbaepzOnfePfni7fA9DI6nFsZy-Ps3wAJhXfxJHwcs4hIWp3EpaJYkrJIUN9Woa1uet7ybNNuTAl8Ozebs51AxswL-IdrUAp9oBAgs3wAZkgxDEVg1COIw6teBvFNcMfLEmKIt8P1I3tGMbJiqLWYcbVtPJBSuKh62kXAeFQBY2i9MIFCUKBA28MVrF47CU0M0VfFUODiBExsxIrX0ZKsWo+IMxBLMwTQaHoOA7JeEjqDoBhnLktyLJ8TAACE2E4Hh-PfEjWA4bhCFChCbSEKAD1mEg8C4D08B6ORqTOecoC4Y5gGGCrWD6WisWOWgowqqrfmOZZGlHccUwmBjC2JNlVw8dd0JIHi3Nw4kErE-q32JdKbUTZMZF+WcJJ-RtBpwYb3FGzceJ3fdj1PehpgvStrzM1Mpt+GaSIYzbzgWtlqN4IA)

**Comment by KenAKAFrosty** [comment]
With this helper we can know if a given type OR interface  is valid json. Then use conditionally as needed. Thoughts?
[Playground with examples and testing](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgSwLYOAgbtAvFAzsRAOwHMoAfKQgVyQCMI5ypaB7FgGwgENCAoXgPQCoAYTjdg0LlFCQoAMxaMAUgGUA8gDk8DBF3YIAXl1qco6fVQi5es6Gq0A1S9l5R3TeMlQYIbjxQA3lAA2gDWECAAXHgECCQAujEOms7sVlAAvv7uFACCcHBcIAA8KWlWAHwA3PxCmiwA7lCN0ADGPFAAFlyYUCxUjF0Q7JCMdjIsUNy4COwgUGGETTJwVgLy+rjQCPJQqADkuOb6CAAmUABWuCx8EwCSuGnnyjeEJTlQACrgEOpw90IkjgmzaEAANFBPgBpSLHHAREAsPY-SD-QHA0EQqEeKAVaxQHCov4AoEMLHhSLI76-dFkkFcMEJXiVQk0tGkzGM6AQAAekkIZ2OXhQaD6AH5VhkYrCQMc+QKhVByi4oJL8fL+RBBccVeloJKCNKFFtoDFNuxtrV+IJhA1mpxgEcoGcpjckO1hm0wvFSIpGGA4CwxlKIBtTf0qMA2iwPVFeHywEpgPt6VioABZEAAES4wC4zwugU+ihYMXwRGIvGyMcI+BOBjOGPJ3Jij0Lr1uJSzufzhdZOCNEGtCd5SbgKfiXLBmZzea4gIsjagxdxpZivb82SEqgAEuoAKoAGWzzB5hSUvvjtfr8SX52bDLBbaepzOnfePfni7fA9DI6nFsZy-Ps3wAJhXfxJHwcs4hIWp3EpaJYkrJIUN9Woa1uet7ybNNuTAl8Ozebs51AxswL-IdrUAp9oBAgs3wAZkgxDEVg1COIw6teBvFNcMfLEmKIt8P1I3tGMbJiqLWYcbVtPJBSuKh62kXAeFQBY2i9MIFCUKBA28MVrF47CU0M0VfFUODiBExsxIrX0ZKsWo+IMxBLMwTQaHoOA7JeEjqDoBhnLktyLJ8TAACE2E4Hh-PfEjWA4bhCFChCbSEKAD1mEg8C4D08B6ORqTOecoC4Y5gGGCrWD6WisWOWgowqqrfmOZZGlHccUwmBjC2JNlVw8dd0JIHi3Nw4kErE-q32JdKbUTZMZF+WcJJ-RtBpwYb3FGzceJ3fdj1PehpgvStrzM1Mpt+GaSIYzbzgWtlqN4IA)

**Comment by KenAKAFrosty** [comment]
Ignore the above. 
Bad news: It doesn't work well with nesting so it's useless.

Good news: Looking at the actual use case here I think I have the working solution. Seeing that this was for the RequestHandler, here's how we can accomplish this:

1) Leave the BODY generic argument untouched
2) Implement the JSONValue type mentioned above
```
type JSONValue =
    | string
    | number
    | boolean
    | { [x: string]: JSONValue }
    | Array<JSONValue>;
```
3) Request Handler return type looks like `(ev: RequestEvent) => RequestHandlerResult<BODY> extends JSONValue | Promise<JSONValue> ? RequestHandlerResult<BODY> : Promise<JSONValue> | JSONValue;`

Preserves the K:V pairs when proper, but the function errors when not. 
![image](https://user-images.githubusercontent.com/90424167/204630415-fc0db323-a525-4eef-90b2-4a61daf7702b.png)

![image](https://user-images.githubusercontent.com/90424167/204630565-b47e4c9d-23c6-4754-8a6a-ee8bf6941e3e.png)

And it works just fine with nesting:
![image](https://user-images.githubusercontent.com/90424167/204630715-a6401eed-6c80-45e2-847f-1c3b3a14efeb.png)
