### ISSUE TITLE
[🐞] Prefetch doesn't work in production!

### ISSUE THREAD

**Issue by hyunjunian** [BuilderIO/qwik#2289]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I build my qwik app with SSG adapter and deployed it to the cloudflare pages.

I expected the next page will be prefetched when I hover the "Link". But it wasn't prefetched at all.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/14211558/204092582-1f4d3d40-cfc0-43cb-b316-1735effa798b.png">

However, in development environment(`npm run dev`), it was prefetched well.

### Reproduction

https://qwik-ssg.pages.dev/

### Steps to reproduce

1. Open the chrome dev tool network tab.
2. Hover the link.
3. Check the network tab.

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 10.83 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.14.1 => 0.14.1 
    @builder.io/qwik-city: 0.0.127 => 0.0.127 
    vite: 3.2.4 => 3.2.4 
```

**Comment by EamonHeffernan** [comment]
> ### Which component is affected?
> 
> Qwik City (routing)
> ### Describe the bug
> 
> I build my qwik app with SSG adapter and deployed it to the cloudflare pages.
> 
> I expected the next page will be prefetched when I hover the "Link". But it wasn't prefetched at all.
> 
> <img alt="image" width="1171" src="https://user-images.githubusercontent.com/14211558/204092582-1f4d3d40-cfc0-43cb-b316-1735effa798b.png">
> 
> However, in development environment(`npm run dev`), it was prefetched well.
> ### Reproduction
> 
> https://qwik-ssg.pages.dev/
> ### Steps to reproduce
> 
>     1. Open the chrome dev tool network tab.
> 
>     2. Hover the link.
> 
>     3. Check the network tab.
> 
> 
> ### System Info
> 
> ```shell
> Cloudflare pages
> ```
> 
> ### Additional Information
> 
> _No response_

This is happening to me too. It was completely working in v0.0.122, but all the q-data.json files seem to not be getting rendered, and the _routes.json file is not getting populated.

**Comment by EamonHeffernan** [comment]
Ok, I built from scratch and the q-data.json files are getting generated. I'll attempt to find out why when I wake up.

**Comment by manucorporat** [comment]
Please can you still run the command to get the System Info? it's relevant to know which qwik version you are using

**Comment by EamonHeffernan** [comment]
To update my comment from earlier, my issues are unrelated to this issue, I've opened #2306 instead.

**Comment by hyunjunian** [comment]
> Please can you still run the command to get the System Info? it's relevant to know which qwik version you are using

Thank you for your attention! I updated the system info. Please check.

```plain
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 10.83 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.14.1 => 0.14.1 
    @builder.io/qwik-city: 0.0.127 => 0.0.127 
    vite: 3.2.4 => 3.2.4 
```

**Comment by adamdbradley** [comment]
Thanks for opening the issue. Previously `prefetch` was an opt-in prop for `<Link/>`. However, this issue helped expose a few more issues, and helped us get to a point where we can make it the default. You'll also be able to opt-out of prefetching by setting it to false:

```tsx
<Link href="/flower/" prefetch={false}>
  Flower
</Link>
```

Also, it looks like SSG is generating the q-data.json files: https://qwik-ssg.pages.dev/flower/q-data.json

However, this issue did help expose an issue with SSG and full href urls so thanks for opening it.

Hope that helps and thanks for opening the issue.
