### ISSUE TITLE
[✨] Parse query params in RequestEvent

### ISSUE THREAD

**Issue by mlynch** [BuilderIO/qwik#2290]
### Is your feature request related to a problem?

For API handlers, `GET` query parameters aren't parsed and provided on the `RequestEvent` argument.

### Describe the solution you'd like

Would be really nice to have those parsed like `req.query` in Express.js

### Describe alternatives you've considered

Parsing URL manually

**Comment by adamdbradley** [comment]
Related https://github.com/BuilderIO/qwik/pull/2352
