### ISSUE TITLE
[🐞] CloudFlare minimization eats qwik comments

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#2294]
### Which component is affected?

Qwik Runtime

### Describe the bug

CloudFlare deploys can turn on HTML minification quite easily and this strips the qwik comments, leading to weird errors.

### Reproduction

https://discord.com/channels/842438759945601056/1046189275366035536

### Steps to reproduce

Deploy to CF. Follow the wizard. Accept the proposed speedups.

### System Info

```shell
any
```

### Additional Information

I think it would be possible to fix this by keeping the information aside during SSR until a DOM node is emitted.

E.g. given this playground:

```tsx
import { component$ } from '@builder.io/qwik';

export const P = component$(({deep}) => {
  return <>
  {deep&&<P/>}
  <p>Hello Qwik</p>
  </>;
});

export default component$(()=> <><P deep/><P/></>)
```

Normally results in
```html
<!DOCTYPE html>
<html
  q:container="paused"
  q:version="0.14.1"
  q:render="ssr"
  q:base="/repl/a35vnoaq2e/build/"
>
  <html>
    <head q:head>
      <title q:head>Hello Qwik</title>
    </head>
    <body>
      <!--qv q:id=0 q:key=Ncbm0Trxwgc:--><!--qv q:id=1 q:key=75645rWLwCk:--><!--qv q:id=2 q:key=75645rWLwCk:-->
      <p>Hello Qwik</p>
      <!--/qv-->
      <p>Hello Qwik</p>
      <!--/qv--><!--qv q:id=3 q:key=75645rWLwCk:-->
      <p>Hello Qwik</p>
      <!--/qv--><!--/qv-->
    </body>
  </html>
  <script type="qwik/json">
    {"refs":{},"ctx":{},"objs":[],"subs":[]}
  </script>
</html>
```

but it could also be represented like
```html
<!DOCTYPE html>
<html
  q:container="paused"
  q:version="0.14.1"
  q:render="ssr"
  q:base="/repl/a35vnoaq2e/build/"
>
  <html>
    <head q:head>
      <title q:head>Hello Qwik</title>
    </head>
    <body>
      <p q:v="(0,Ncbm0Trxwgc:,(1,75645rWLwCk:,(2,75645rWLwCk:">Hello Qwik</p>
      <p q:v=")">Hello Qwik</p>
      <p q:v="))(3,75645rWLwCk:">Hello Qwik</p>
    </body>
  </html>
  <script type="qwik/json">
    {"refs":{},"ctx":{},"objs":[],"subs":[]}
  </script>
</html>
```
Note the missing closing tags, the convention would be that the end of a parent closes all open qv.

This is robust against minification, saves some bytes, and looks like it can be optimized some more?

**Comment by manucorporat** [comment]
This is hard for so many reasons, the proposed solution requires a ton of new coordination to merge things that might render in isolation, also does not recognize the fact that sometimes there is not actual element to back it

And ultimately, that's this is an issue with cloudflare breaking valid HTML, this is an issue to be solved by cloudflare.

I will reach them out to know if there is anything thing that we can put in the comments that prevents them for removing it, otherwise, we should just document this in the cloudflare docs.

**Comment by wmertens** [comment]
@manucorporat ah yes for the "no actual element" I was thinking to just add a real `<qv ...data></qv>` which will be invisible and would probably be in a place that doesn't impact CSS.

But yes if it's harder than e.g. the scoped styles tracking it's probably not worth it.

**Comment by manucorporat** [comment]
it's super hard, months hard... and many frameworks use similar approached, vue, svelte, solid...

**Comment by manucorporat** [comment]
I will close... reached cloudflare... but this is extremely unlikely to happen in the short term, closing :)

**Comment by wmertens** [comment]
@hyunjunian If you can get cloudflare to not minimize any `q:` attributes and `<!--qv` or <!--/qv` comments, that'd be great
