### ISSUE TITLE
[🐞] Inconsistent handling of some (pseudo)boolean attributes like draggable in SSR vs CSR

### ISSUE THREAD

**Issue by jwickers** [BuilderIO/qwik#2296]
### Which component is affected?

Qwik Runtime

### Describe the bug

A link with `draggable="false"` correctly renders with `draggable="false"` in SSR but renders as `draggable="true"` in CSR.
A link with `draggable={false}` incorrectly renders with no `draggable` attribute in SSR but renders correctly as `draggable="false"` in CSR.

Not only is this confusing behavior, as a result there is no way to render consistently in both SSR and CSR.

I understand that boolean attributes usually render with "truthy" values, however in this case the issue is that `draggable` is not actually a boolean attribute, but an enumerated one (see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable)

This bug might affect other attributes?

### Reproduction

https://stackblitz.com/edit/qwik-starter-rb5cxd

### Steps to reproduce

Run `npm install` then `npm start`.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.14.1 => 0.14.1 
    @builder.io/qwik-city: 0.0.127 => 0.0.127 
    vite: 3.2.4 => 3.2.4
```

**Comment by manucorporat** [comment]
Feels like a type issue! no? the values it should accept should be `"true"` or `"false"` as string, not boolean

**Comment by jwickers** [comment]
Never mind I think I found it, will make a PR for this one line fix.

**Comment by jwickers** [comment]
That fixes the CSR case for me which was the most annoying. 
I don't know if you want to look at the type issue here so that this only accepts `string`?

**Comment by jwickers** [comment]
Awesome, if yours gets released soon I'll test it in my project.
