### ISSUE TITLE
[🐞] Assets in qwik city are loaded from a page's folder name instead of public

### ISSUE THREAD

**Issue by raphael-arce** [BuilderIO/qwik#2303]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When I use an asset from the public folder in a page, e. g.: `<img src="favicon.svg" />` in the flower page from the qwik starter script, I get an error in the browser, that the resource was not found in that directory: `GET http://localhost:5173/flower/favicon.svg 404 (Not Found)`

I'm using qwik 0.14.1 and and qwik-city 0.0.127

### Reproduction

https://stackblitz.com/edit/qwik-starter-apamp4?file=src/routes/flower/index.tsx

### Steps to reproduce

I used the starter script: `npm create qwik@latest` and added in the flower page an image element, so the flower page looks like this:
```html
<>
      <img src="favicon.svg" /> <!-- <- this line was added -->
      <input
        type="range"
        value={state.number}
        max={50}
        onInput$={(ev) => {
          state.number = (ev.target as HTMLInputElement).valueAsNumber;
        }}
      />
      <div
        style={{
          '--state': `${state.count * 0.1}`,
        }}
        class={{
          host: true,
          pride: loc.query['pride'] === 'true',
        }}
      >
        {Array.from({ length: state.number }, (_, i) => (
          <div
            key={i}
            class={{
              square: true,
              odd: i % 2 === 0,
            }}
            style={{ '--index': `${i + 1}` }}
          />
        )).reverse()}
      </div>
    </>
```
<img width="1374" alt="Screenshot 2022-11-28 at 23 28 29" src="https://user-images.githubusercontent.com/8709861/204394448-b6877ce0-61fb-48b6-94a0-86d1ce54e6cd.png">

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 67.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 107.0
    Safari: 16.1
```

### Hower!
When i add the folder `flower` in the `public` folder and copy the asset inside, it works, the asset can be found. Is this intended this way?

**Comment by EamonHeffernan** [comment]
Use "/favicon.svg" urls prefixed with / link to the root of the site, whereas if you don't it is relative to the current page.

**Comment by raphael-arce** [comment]
Ah! It works! Thank you so much!
