### ISSUE TITLE
[🐞] Cloudflare Pages - Delay between Link click and transition.

### ISSUE THREAD

**Issue by EamonHeffernan** [BuilderIO/qwik#2306]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When a Link component is pressed, the server fetches the corresponding q-data file, this works as intended, prefetching the q-data file on hover. However on click, the server then re-validates that the q-data file is fresh before continuing with the request. This leads to a slight delay with minimal latency, to a very large delay on connections with high latency.

There is also different behavior between the fetches for /q-data.json and other files. The q-data.json file in the root directory is fetched new each time, whereas the others are re-validated each time. These both however lead to a delay in link click to page transition.

### Reproduction

https://github.com/EamonHeffernan/QwikBug

### Steps to reproduce

Run 'pnpm install' then 'pnpm build' then 'pnpm run deploy'.
Clicking on the links with real or artificial latency results in a delay between click and page transition due to re-validating the q-data.json file.

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 46.20 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - ~/.nvm/versions/node/v19.0.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.0.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v19.0.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 107.0
    Firefox Developer Edition: 108.0
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.14.1 => 0.14.1 
    @builder.io/qwik-city: 0.0.127 => 0.0.127 
    vite: 3.2.2 => 3.2.2
```

**Comment by adamdbradley** [comment]
Great issue! This helped us pin-point some issues and fixed them in #2289. In the next release, please give it another thorough test and let us know if there's any other issues. Thanks!
