### ISSUE TITLE
[🐞] Vitest Integration Error

### ISSUE THREAD

**Issue by T-travis** [BuilderIO/qwik#2316]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When running `npm run qwik add vitest`, I get the following error:

```
❌ Error: Invalid integration: vitest
```

### Reproduction

https://stackblitz.com/edit/qwik-starter?file=package.json

### Steps to reproduce

Stackblitz run in terminal: `npm run qwik add -- vitest`

Local run in terminal: `npm run qwik add vitest`

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 74.63 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.09.19.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 107.1.45.133
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.14.1 => 0.14.1 
    @builder.io/qwik-city: 0.0.127 => 0.0.127 
    vite: 3.2.4 => 3.2.4
```

**Comment by DustinStaze** [comment]
@leifermendez maybe you can help with this?

In the meantime you should be able to just install vite and start testing:

`pnpm add -D vitest `

And start with a unit test like this (`my-component.spec.tsx`):

```TypeScript
test(`[MyComponent]: Should render child`, async () => {
  const { screen, render } = await createDOM();
  await render(
    <MyComponent>
      <div>Success</div>
    </MyComponent>
  );
  expect(screen.outerHTML).toContain('Success');
});
```

**Comment by leifermendez** [comment]
Hi, ok let'me check
