### ISSUE TITLE
[✨] Make components able to inherit parent's styling scope

### ISSUE THREAD

**Issue by EamonHeffernan** [BuilderIO/qwik#2318]
### Is your feature request related to a problem?

It is very difficult to pass classes down to child components while still using scoped styles. Each component has their own scope, which is intended, but doesn't allow components to be styled differently based on their parents.

### Describe the solution you'd like

The ability to mark a component as inheriting the style scope of the parent. Therefore, the elements in the child component get prepended with the same scope id as the parent. This could be done in the component$ function, or possibly by wrapping the child elements or the component itself in an "inherit styles" tag.

### Describe alternatives you've considered

It is possible to work around this by passing the scope id down to the children and prepending each element manually with the scope id class.

**Comment by wmertens** [comment]
`useStylesScoped$` returns `{scopeId: string}` which is the classname you can add to all components that you want to give the scoped style to.
