### ISSUE TITLE
[✨] Support for Qwik + Preact

### ISSUE THREAD

**Issue by Ritvik-UX** [BuilderIO/qwik#2328]
### Is your feature request related to a problem?

Qwik already supports React integration. 
Adding support with Preact will reduce the bundle size significantly.
( [https://preactjs.com/](https://preactjs.com/) )

### Describe the solution you'd like

Nope!

### Describe alternatives you've considered

Nope!

**Comment by heinthanth** [comment]
Hi @Ritvik-UX, we have a release in https://github.com/QwikDev/qwik-preact now!
