### ISSUE TITLE
[🐞] Only primitive and object literals can be serialized

### ISSUE THREAD

**Issue by homzmart-alan** [BuilderIO/qwik#2339]
### Which component is affected?

Qwik Runtime

### Describe the bug

I started getting this error after upgrading to version 0.15.0.

```
Code(3): Only primitive and object literals can be serialized
20 |   `;
21 |  
22 |    const getProductResult = $(async () => {
   |       ^
23 |      const response = await getProduct();
24 |      store.res = JSON.stringify(response, undefined, 2);
```

### Reproduction

0.15.0

### System Info

```shell
macOS
```

**Comment by zanettin** [comment]
Hi @homzmart-alan 
Thank you for creating this issue 🙏  are you able to create a reproduction on https://qwik.new? That would help us a lot to dig into this 🙏

**Comment by homzmart-alan** [comment]
https://stackblitz.com/edit/qwik-starter-jrih4f?file=src/routes/index.tsx

**Comment by zanettin** [comment]
Thanks once again @homzmart-alan 🙏 
Had a look into the reproduction on it works as it should on `0.14.1` as well as on `0.15.0`.
I've upgraded your example just by changing the version on the package.json as follow:
```
"@builder.io/qwik": "0.15.0",
"@builder.io/qwik-city": "0.0.128",
```

and run: `npm install`

### visual output of your example
![Bildschirmfoto 2022-12-01 um 23 18 24](https://user-images.githubusercontent.com/3241476/205171568-9ee9c059-55dd-42b9-86e9-2e80f43cb773.png)
 and i don't get the serialization error. please let me know how i could reproduce the issue 🙏

**Comment by homzmart-alan** [comment]
Hello @zanettin, I'm starting to get this now 
<img width="373" alt="Screen Shot 2022-12-03 at 20 29 31" src="https://user-images.githubusercontent.com/98848260/205453913-a691291e-bae3-4f6d-b569-e5a746ba126b.png">

**Comment by homzmart-alan** [comment]
solved.
