### ISSUE TITLE
[🐞] Textarea value

### ISSUE THREAD

**Issue by langbamit** [BuilderIO/qwik#2344]
### Which component is affected?

Qwik Runtime

### Describe the bug

Click the button, textarea value immediately clear, this occur when we has `[signal.value]` inside JSX template
```jsx
export default component$(() => {
  const classSig = useSignal("abc")
  return <>
    <textarea class={classSig.value} value="This value is empty when click button below"></textarea>
    {[classSig.value]} {/* Without this line or try wrap this line inside a div, no error occurs*/}
    <p>
     <button onClick$={() => {classSig.value = "bar"}}>Trigger error</button>
    </p>
  </>;
});
```

### Reproduction

https://qwik.builder.io/playground#version=0.15.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU2lnbmFsJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBjbGFzc1NpZyUyMCUzRCUyMHVzZVNpZ25hbCglNUMlMjJhYmMlNUMlMjIpJTVDbiUyMCUyMHJldHVybiUyMCUzQyUzRSU1Q24lMjAlMjAlMjAlMjAlM0N0ZXh0YXJlYSUyMHZhbHVlJTNEJTVDJTIyVGhpcyUyMHZhbHVlJTIwd2lsbCUyMGVtcHR5JTIwd2hlbiUyMGNsaWNrJTIwdGhlJTIwYnV0dG9uJTIwYmVsb3clNUMlMjIlMjByb3dzJTNEJTdCNSU3RCUzRSUzQyUyRnRleHRhcmVhJTNFJTVDbiUyMCUyMCUyMCUyMCU3QiU1QmNsYXNzU2lnLnZhbHVlJTVEJTdEJTIwJTdCJTJGKiUyMFdpdGhvdXQlMjB0aGlzJTIwbGluZSUyMG9yJTIwdHJ5JTIwd3JhcCUyMHRoaXMlMjBsaW5lJTIwaW5zaWRlJTIwYSUyMGRpdiUyQyUyMG5vJTIwZXJyb3IlMjBvY2N1cnMqJTJGJTdEJTVDbiUyMCUyMCUyMCUyMCUzQ3AlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTNDYnV0dG9uJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwJTdCY2xhc3NTaWcudmFsdWUlMjAlM0QlMjAlNUMlMjJiYXIlNUMlMjIlN0QlN0QlM0VUcmlnZ2VyJTIwZXJyb3IlM0MlMkZidXR0b24lM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGcCUzRSU1Q24lMjAlMjAlM0MlMkYlM0UlM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQXBwJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NodG1sJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D

### System Info

```shell
qwik@0.15.0
```

**Comment by n8sabes** [comment]
Same issue with `useStore`. Interesting that the issue only occurs when rendered from within an array.

```
const classSig = useStore({value: "abc"});
```
