### ISSUE TITLE
[✨] Allow throwing raw response HTML from request handlers

### ISSUE THREAD

**Issue by alfredsgenkins** [BuilderIO/qwik#2347]
### Is your feature request related to a problem?

To redirect, we throw `response.redirect` in the request handlers (i.e. `onGet`). But, I would like to return raw HTML (in my case, to proxy the response). I can not do this, if I have the component exported by default.

### Describe the solution you'd like

I would like to add a new throwable, like `response.redirect()` but `response.sendRaw()` to respond from handlers even if component is declared.

### Describe alternatives you've considered

I tried returning raw response from proxy from `onGet` but that response is catched by the components `Resource`.

**Comment by zanettin** [comment]
Hi @alfredsgenkins 
Thanks for creating this feature request 🙏 
To kick off a discussion about this: what would be the use-case from your pov? 

I had a similar scenario where i wanted to return a "blocked for your region" error (451). I solved it by switching the response in the `<Resource>` components `onResolved` param based on the status code which my `onGet` returned. 

smth like:

```
<Resource
  value={data}
  onPending={...}
  onRejected={...}
  onResolved={(data) => {
    switch(data.status) {
       case '451': return <h1>geo blocked</h1>
       default: return ...
    }
  }}
/>
```

**Comment by alfredsgenkins** [comment]
Sure @zanettin, here is what I intend to do:
1. I have a main website, in my case, a e-commerce store, configured to use domain: `real.com`, but actually hosted at `hidden.com`
2. I have a Qwik app with the `/routes/[...route]/index.tsx` routing all requests coming to `real.com` url
3. I want my Qwik app to take partial responsibility for rendering some page types of the application
  3.1 I implement a `onGet` in my route, where I fetch page type for current page
  3.2 Based on a page type, I kick off rendering (aka Resource is successfully resolved), or...
  3.3 ...Or I would like to proxy the request down to the original e-commerce store (hosted on `hidden.com`)

Right now, on step 3.3 I use `response.redirect`. But to me, that is an issue, I redirect to a different domain, which looses me cookies. I can not persist cart across websites and exposes the `hidden.com`, which I do not want customers to see.

I could use suggestion your provided, fetching the HTML of the `hidden.com` and then returning only `<body>` element contents (as my `root.tsx` declares head and body), I would also need to parse html to retrieve and set correct headers.

I hope this makes a little bit of sense :)
