### ISSUE TITLE
[🐞] Array Empty Index Resume Error

### ISSUE THREAD

**Issue by jweb89** [BuilderIO/qwik#2350]
### Which component is affected?

Qwik Runtime

### Describe the bug

When there is an empty index in an array the container throws an error when trying to resume.

![Screen Shot 2022-12-02 at 9 47 45 AM](https://user-images.githubusercontent.com/62513031/205319284-73ddb02f-c29d-40b6-975c-42c1c93e2a9e.png)

### Reproduction

https://stackblitz.com/edit/qwik-starter-jywvpm?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Run the stackblitz repo
2.  Open the container in a new window with dev console
3. Try to click the button
4. Should open debugger, you can skip the debugging and should see error in the console regarding the resume id

I realize this is a weird case, and actually pointed to more of a bug in our code that react could handle that qwik could not. However, I think there is a bigger issue here. The error message was not at all helpful in finding the bug in our code or the bug in qwik. I imagine this is something that's being worked on but I had to go through and comment out code line by line to figure out what was causing this.

### System Info

```shell
 System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.14.1 => 0.14.1 
    @builder.io/qwik-city: 0.0.127 => 0.0.127 
    vite: 3.2.4 => 3.2.4 
```

**Comment by manucorporat** [comment]
The system info is still relevent for us, since it includes the vite/qwik version

**Comment by jweb89** [comment]
> The system info is still relevent for us, since it includes the vite/qwik version

Fixed, sorry about that. Stackblitz has the 14.1 version but I also tested this on the latest qwik(0.15.0) and qwik-city(0.0.128)
