### ISSUE TITLE
[🐞] trailing slash added to route params

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#2351]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When you have a parameter in the root, not followed by other segments, a trailing slash is added to the parameter:

`{ params: { id: '1234/' } }`

### Reproduction

https://stackblitz.com/edit/qwik-starter-zgnacc

### Steps to reproduce

After the app has started, click on `Go to id 1234` and look in the Terminal (Ok, just hover the mouse pointer over the button without pressing it... what an amazing improvement is this?!)

Thanks

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.15.0 => 0.15.0 
    @builder.io/qwik-city: 0.0.128 => 0.0.128 
    vite: 3.2.4 => 3.2.4
```

**Comment by adamdbradley** [comment]
Related https://github.com/BuilderIO/qwik/pull/2352

**Comment by adamdbradley** [comment]
Fixed in https://github.com/BuilderIO/qwik/pull/2385
