### ISSUE TITLE
[🐞] [plugin:vite:css] [sass] This file is already being loaded.

### ISSUE THREAD

**Issue by homzmart-alan** [BuilderIO/qwik#2368]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

When I made the project responsive, I always started getting this error after I upgraded the version.
I using scss in the project.

**The error i got**
<img width="468" alt="Screen Shot 2022-12-04 at 16 37 36" src="https://user-images.githubusercontent.com/98848260/205493850-72b5e3ee-f795-4ffa-bfaf-c18aeaaa0035.png">

**package.json**
<img width="372" alt="Screen Shot 2022-12-04 at 16 42 02" src="https://user-images.githubusercontent.com/98848260/205493913-42e6ad51-b034-4fbc-8253-aa03bc78c887.png">

**vite.config.ts**
<img width="636" alt="Screen Shot 2022-12-04 at 16 45 27" src="https://user-images.githubusercontent.com/98848260/205494091-34c2901f-a986-4133-8841-0332f1bdb62d.png">

### Reproduction

Error vite

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 1.25 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Safari: 16.0
```

**Comment by manucorporat** [comment]
can you please provide a repo case that reproduces the issue?

**Comment by homzmart-alan** [comment]
> can you please provide a repo case that reproduces the issue?
Yes I will add you to the repo

**Comment by manucorporat** [comment]
This is likely an issue with Vite or sass itself, qwik does not modify sass file at all:

https://github.com/vitejs/vite/issues/3283
https://github.com/nuxt/vite/issues/117

Hope this can help unblock u, i would try opening an issue in the vite repo :)
