### ISSUE TITLE
[🐞] Context values are just partially updated

### ISSUE THREAD

**Issue by zanettin** [BuilderIO/qwik#2388]
### Which component is affected?

Qwik Runtime

### Describe the bug

Updating a context value does not re-render all places where it is used.

**Use Case**
Have a use-case where i want to update a context based on an API response. Therefore i'd expected that values are updated/re-rendered on all places. But as shown in the repro the value gets updated on the context but just re-rendered on the child component. By setting a new random value, it gets correctly re-rendered on all places.

### Reproduction

https://stackblitz.com/edit/qwik-starter-uerlkp?file=src/routes/index.tsx

### Steps to reproduce

- open repro
- see values `context values 1` and `context values 2`
- they should be in sync but are not
- hitting the `force` button with a random value will update both context outputs as expected

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 304.00 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/34/mgxs4kqs24s8kl0jfxg9jng00000gn/T/fnm_multishells/1593_1670193819142/bin/node
    Yarn: 1.22.18 - /var/folders/34/mgxs4kqs24s8kl0jfxg9jng00000gn/T/fnm_multishells/1593_1670193819142/bin/yarn
    npm: 8.1.0 - /var/folders/34/mgxs4kqs24s8kl0jfxg9jng00000gn/T/fnm_multishells/1593_1670193819142/bin/npm
  Browsers:
    Brave Browser: 104.1.42.88
    Chrome: 108.0.5359.94
    Chrome Canary: 110.0.5462.2
    Firefox: 107.0.1
    Safari: 16.0
    Safari Technology Preview: 16.4
```

**Comment by zanettin** [comment]
updated the reproduction to use currently lasted versions:
- `qwik@0.16.2`
- `qwik-city@0.1.0-beta9`

**Comment by manucorporat** [comment]
still a problem?

**Comment by manucorporat** [comment]
Seems to be fixed!
