### ISSUE TITLE
Server Only useResource

### ISSUE THREAD

**Issue by Abiti-936** [BuilderIO/qwik#2397]
### Is your feature request related to a problem?

I have liked Qwik's HTML Streaming Rendering, but to stream components that will produce HTML at the end, I have to use useResource and useResource is Just an isomorphic primitive (that runs on both a server and a client), so it's bundling code that should not be shown & execute on the Client.

### Describe the solution you'd like

I think there should be useServerResource that only runs on a server & the client will make a fetch request to get the server resource.

### Describe alternatives you've considered

Also we can have a serverOnly option in useResource.

### Additional context

I think useResource is great because we can put as many useResources in our Components & it works, so it's not like onGet method that's just a one & only thing per route.

**Comment by manucorporat** [comment]
It's very unlikely `useServerResource` will be a thing, in fact we are looking so simplify the number of hooks since they cause so much confusion, i would suggest you to use the build conditional exported in `@builder.io/qwik/build`;
```
import { isServer } from '@builder.io/qwik/build'
```

**Comment by Abiti-936** [comment]
Ok, Great. I will follow server actions PR. I think it's good to have server only primitives. also it's going to work with Qwik's HTML Streaming?

**Comment by manucorporat** [comment]
Yes of course! In the meantime could you elaborate what you trying to do? What’s you use case?

**Comment by Abiti-936** [comment]
Ok, I am using HyGraph CMS with URQL GraphQL Client and I have to send API token on every request to the CMS, so if I use useResource, it's going to bring all GraphQL queries to the client & if I use onGet I can't stream HTML. I think if there should be some kind of thing like server$ function like solid.js. For Now, I have created a Cloudflare Page Functions API.

**Comment by elyobo** [comment]
Similar use case here; I want a resource that loads data from the DB when used server side, and from the qwik city endpoint (which is not the current page, so can't use `useEndpoint`) when used client side, but all of the DB handling code is bundled - which is redundant, and also doesn't work. Worked around with dynamic `import()` to pull in the server code when `isServer` is true instead.
