### ISSUE TITLE
[🐞] A empty index.ts file will introduce bug

### ISSUE THREAD

**Issue by cunzaizhuyi** [BuilderIO/qwik#2399]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Everything is right until you create a empty index.tx file in the src/routes dir.
if you can't reproduction, you can restart project by ctrl + c and npm start.  

### Reproduction

no

### Steps to reproduce

create a empty index.tx file in the src/routes dir.

error info:

Code(25): Invalid JSXNode type. It must be either a function or a string. Found:
/Users/xxxxxx/WebstormProjects/qwik_demo/node_modules/@builder.io/qwik-city/index.qwik.mjs:16:12.
`let cmp = null;
15 |      for (let i = contentsLen - 1; i >= 0; i--)
16 |        cmp = jsx(contents[i].default, {
   |              ^
17 |          children: cmp
18 |        });`

### System Info

```shell
> node 16
```

**Comment by manucorporat** [comment]
Hi! It’s unlikely we will prioritise a issue if there is no a fast way for us to reproduce it, and the system info is not filled
