### ISSUE TITLE
[📖]Add Documentation - How to Call a Child Component Function

### ISSUE THREAD

**Issue by n8sabes** [BuilderIO/qwik#2405]
### Suggestion

Add documentation how to call child function.

Below is an example how to call a child to trigger self-validation.

**[Live Example Here](https://stackblitz.com/edit/qwik-starter-qsbuby?file=README.md,src%2Froutes%2Findex.tsx)**

```
// index.tsx

import { component$, useSignal, $, PropFunction, Signal, useServerMount$ } from '@builder.io/qwik';

/**
 * PARENT
 */
export default component$(() => {
    const validate = useSignal<PropFunction<() => void> | undefined>();

    return (<div style={{ border: "2px solid blue", padding: "20px" }}>
        <button style={{ padding: "10px" }} onClick$={$(() => validate.value?.())}>Call child to self-validate</button>
        <Child validate={validate} />
    </div>);
});

/**
 * CHILD
 */
export const Child = component$((props: { validate?: Signal<PropFunction<() => void> | undefined>; }) => {
    const isValid = useSignal(false);

    const validate$ = $(() => {
        isValid.value = !isValid.value;
    });

    useServerMount$(() => {
        if (props.validate) {
            props.validate.value = validate$;
        }
    });

    return (
        <div style={{ border: "2px dashed orange", padding: "20px" }}>
            Child is {isValid.value && <span style={{ color: "red" }}>NOT </span>}valid
        </div>
    );
});
```

**Comment by zanettin** [comment]
Hi @n8sabes
Thanks for sharing this idea incl. a snippet 🙏 Thought quickly about it and i am not sure if i would expect smth like this in a framework documentation or not. i mean it's not different from how you would do it in react for example, right? so it is not a speciality from the framework but more like a pattern (pass a ref into a child which then alters the value). but these are just my two cents 🤣 
@shairez is currently redefining the docs so maybe he can tell more about his feelings about that? 👼

**Comment by n8sabes** [comment]
Hi @zanettin, thanks for fleshing out thoughts on this. IMHO, Yes and no; While this resembles a known react-like pattern, there are a few things to consider:

1. Calling a child function requires wrapping the function in `$( )` and if reverenced in an interface, an unfamiliar type definition. So it’s not immediately intuitive based on previous React knowledge.
2. Qwik is just different enough with QRLs that even a skilled developer sometimes scratches their head. Making how-to patterns / examples easy to find is critical, albeit to your point, ….. a pattern.
3. The objective of documentation, patterns, and examples are to onboard new people as quickly as possible and serve as a deep knowledge reference repository. If devs must leave the docs to search out in react-land, stackoverflow, discord or numerous other possible places, this does not serve objective of education and onboarding with practices most appropriate for Qwik and its community.

This is just my opinion on lowering the barrier to adoption. Indeed, something for @shairez and others focusing on docs, pattern repo, and examples to decide.

**Comment by shairez** [comment]
@n8sabes thanks for this!

I'm confused - why can't we just declare the function with `$()` ?  why do we need to wrap it in a signal?

**Comment by n8sabes** [comment]
@shairez Wow, this is an old issue and likely suggested at a time new to qwik. From looking back at the snippet, it appewrs to provide the parent with access to the validate function after the child renders. The signal in the child is only a flag example and unrelated. Whatever the best way is to enable the parent to call a child function seems like a good example to include somewhere. I have no attachment to my or someone else’s more efficient solution.

**Comment by shairez** [comment]
Yeah it just popped back in my inbox again :)

OK so in that case I think it's already covered here -

https://qwik.builder.io/docs/components/events/#events-and-components

If that doesn't solve this issue feel free to reopen it or add a PR and we'll get that done together.

Thanks 🙏

**Comment by n8sabes** [comment]
@shairez Isn’t the example you gave the opposite direction; child component calling the parent — which is easy. The example here is the parent calling the child’s function. — I may be wrong as I’m looking at this on my phone right now (before coffee), but that’s what I think I’m seeing.

**Comment by shairez** [comment]
@n8sabes yeah I missed that it's the other way around, you're right

I'm still thinking whether a signal the right way to go about it.

Here are my thoughts:

1. I expect to use signals when I need something reactive, not just as a container of other functions. 
(IMO it's less readable to use a signal here (value?.() is more cryptic than `something.validate?)

2. The wrapping of the extra `$()` is not necessary inside the `onClick$` closure.

Here's an alternative way to achieve it (which is showing the intent as well) 

[Here's a link to the repo](https://stackblitz.com/edit/qwik-starter-flajy6?file=src%2Froutes%2Findex.tsx)

```

interface FnContainer{
    validate$: PropFunction<() => void> | undefined;
  }

export default component$(() => {

  const fnContainer: FnContainer = {
    validate$: $(() => {})
  }

    return (<div style={{ border: "2px solid blue", padding: "20px" }}>
        <button style={{ padding: "10px" }} onClick$={() => fnContainer.validate$?.()}>Call child to self-validate</button>
        <Child fnContainer={fnContainer} />
    </div>);
});

export const Child = component$((props: { fnContainer: FnContainer }) => {
    const isValid = useSignal(false);

    const validate$ = $(() => {
        isValid.value = !isValid.value;
    });

    useTask$(() => {
        if (props.fnContainer) {
            props.fnContainer.validate$ = validate$;
        }
    });

    return (
        <div style={{ border: "2px dashed orange", padding: "20px" }}>
            Child is {isValid.value && <span style={{ color: "red" }}>NOT </span>}valid
        </div>
    );
});


```
