### ISSUE TITLE
[🐞] array of items displayed in wrong order

### ISSUE THREAD

**Issue by literalpie** [BuilderIO/qwik#2414]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am trying to change the order of rows in a table. It works fine on initial render, but when the order is changed, the value rendered does not get correctly updated.

### Reproduction

https://stackblitz.com/edit/qwik-tanstack-table-solution-g4yez1?file=src/routes/index.tsx

### Steps to reproduce

See instruction in stackblitz page contents

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 22.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.2.2 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 108.0.5359.98
    Chrome Canary: 110.0.5468.0
    Safari: 16.1
    Safari Technology Preview: 16.4
  npmPackages:
    @builder.io/qwik: ^0.12.0 => 0.12.0 
    @builder.io/qwik-city: ^0.0.118 => 0.0.118 
    vite: 3.1.1 => 3.1.1 
```

### Additional Information

Feels a little similar to #2188, but I made sure I have keys on all list elements this time.

**Comment by zanettin** [comment]
Hi @literalpie 

Thanks for creating this issue and the well described reproduction 🙏 

I played around with it and for me it looks like that the `key` attributes causing the issue (+ the `localeCompare` against strings with numeric values). after removing the keys, everything is working as i would expect it.
I've created a pure numeric table over [here](https://stackblitz.com/edit/qwik-tanstack-table-solution-fk1byf?file=src/routes/index.tsx) just to demonstrate the sorting of plain numbers.

tbh i am not sure why the keys are creating this issue but maybe somebody else can help us with this question 😄 (@shairez maybe? 👼 )

**Comment by manucorporat** [comment]
Seems like it's using an old version of Qwik!
```
    @builder.io/qwik: ^0.12.0 => 0.12.0 
```
Please update and see if the problem still persiste!

**Comment by literalpie** [comment]
Oops! The stackblitz is on 0.15.0 though

**Comment by literalpie** [comment]
This is still an issue in 0.16.2.

It is true that removing `key` seems to fix the issue. That's really strange though. Isn't this a case where key would be needed since I'm iterating over an array?

**Comment by literalpie** [comment]
Seems better now. Thank you!
