### ISSUE TITLE
[🐞]onInput$ event type should be consistent with other Qwik events 

### ISSUE THREAD

**Issue by n8sabes** [BuilderIO/qwik#2415]
### Which component is affected?

Qwik Runtime

### Describe the bug

`onChange$` event type is: `QwikChangeEvent<HTMLInputElement>`

However, `onInput$` event type is: `Event` which requires an extra step (`evt.target as HTMLInputElement`) to access the value without a type error.

Shouldn't `onInput$` event type be `QwikInputEvent<HTMLInputElement>`, or even `QwikChangeEvent<HTMLInputElement>`?

*Just a suggestion as I found myself working around this event handler differently than the others.*

### Reproduction

n/a

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 73.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - ~/.nvm/versions/node/v19.0.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v19.0.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox Developer Edition: 108.0
    Safari: 16.1
```

**Comment by manucorporat** [comment]
SHould be fixed!
