### ISSUE TITLE
[🐞] When I build code with cloudflare adapter, `platform.env` is undefined.

### ISSUE THREAD

**Issue by hyunjunian** [BuilderIO/qwik#2417]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

# my code

```
export const onGet: RequestHandlerCloudflarePages<{food: string}> = async ({platform}) => {
    const foodKV = platform.env["FOOD"]
    const food = await foodKV.get("foods")
    return {
        food: food || "no food",
    }
};
```

# error logs when building

12:37:58.947 | ERROR: SSG failed for path: /about/
12:37:58.947 | TypeError: Cannot read properties of undefined (reading 'FOOD')
12:37:58.947 | at f (file:///opt/buildhome/repo/server/@qwik-city-plan.js:1:651)
12:37:58.947 | at next (file:///opt/buildhome/repo/node_modules/@builder.io/qwik-city/static/node.mjs:962:26)
12:37:58.947 | at loadUserResponse (file:///opt/buildhome/repo/node_modules/@builder.io/qwik-city/static/node.mjs:992:9)
12:37:58.947 | at requestHandler (file:///opt/buildhome/repo/node_modules/@builder.io/qwik-city/static/node.mjs:1300:34)

### Reproduction

https://github.com/hyunjunian/qwik-bug-report

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 50.92 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - /usr/local/bin/node
    npm: 9.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.15.2 => 0.15.2 
    @builder.io/qwik-city: 0.0.128 => 0.0.128 
    vite: 4.0.0 => 4.0.0
```

**Comment by zanettin** [comment]
Hi @hyunjunian 
Thanks for opening this issue. Wanted to have a look at the demo repo, but looks like the public does not have access or the url is invalid 😄 hope you can adjust that 🙏

**Comment by hyunjunian** [comment]
> Hi @hyunjunian Thanks for opening this issue. Wanted to have a look at the demo repo, but looks like the public does not have access or the url is invalid 😄 hope you can adjust that 🙏

Sorry for inconvenience, here is a public repository reproduction example.

https://github.com/hyunjunian/qwik-bug-report

**Comment by hyunjunian** [comment]
@zanettin Thank you very much!
