### ISSUE TITLE
[🐞] typed context - using same name for interface and variable causes "not serializable" error

### ISSUE THREAD

**Issue by ibrahimduran** [BuilderIO/qwik#2418]
### Which component is affected?

Starters / CLI

### Describe the bug

This occurred when defining typed context and using same name for the variable and interface. Using type variable instead of interfaces seems to bypass the issue.

### Reproduction

https://github.com/ibrahimduran/qwik-eslint-bug-repro/blob/main/src/routes/index.tsx

### Steps to reproduce

Define a typed context with same variable and interface name:

```typescript
export interface MyContext {}
const MyContext = createContext<MyContext>('my-context');
```

Reference context in onClick$:

```typescript
const state = useContext(MyContext);
return <button onClick$={() => state}>click me</button>
```

Run eslint:

```
$ npm run lint

> lint
> eslint "src/**/*.ts*"


/home/iduran/qwik-repro/src/routes/index.tsx
  33:31  error  Identifier ("state") can not be captured inside the scope (onClick$) because it is an instance of the "MyContext" class, which is not serializable. Check out https://qwik.builder.io/docs/advanced/optimizer for more details  qwik/valid-lexical-scope

✖ 1 problem (1 error, 0 warnings)
```

### System Info

```shell
Binaries:
  Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v18.10.0/bin/yarn
  npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
npmPackages:
  @builder.io/qwik: 0.15.2 => 0.15.2 
  @builder.io/qwik-city: 0.0.128 => 0.0.128 
  vite: 3.2.4 => 3.2.4

typescript: 4.9.3
```

**Comment by ints-hiro** [comment]
Please fix this issue in `plugin:qwik/recommended`. Currently,  in file `.eslinttrc.cjs`, off this rule to bypass

` "qwik/valid-lexical-scope": "off"`

**Comment by hamatoyogi** [comment]
This is no longer relevant as the API has changed.
See: https://qwik.builder.io/docs/components/context/#context
