### ISSUE TITLE
[✨] Slots can not be accessible by parent scope 

### ISSUE THREAD

**Issue by saeedhbi** [BuilderIO/qwik#2429]
### Is your feature request related to a problem?

First of all, thank you for this framework and your work. It's quite what I needed.

I want to create a modular template that needs passing some slots to the mainstream to handle it in a single approach.

Currently, the slots only will be handled if they are wrapped by their component, not in nested.

I'm not sure if we are supporting it or not, But, if it is not, is it possible to make it?

### Describe the solution you'd like

Imagine you have 3 columns and the left and right sides will be handled in one scope, but the main column will be different in nested routes. **Also, I want to have availability replace the content of left or right by nested routes too.**

I think it can be handled if the slot searches the nearest wrapped component or in layouts.

### Describe alternatives you've considered

I don't have any while I'm using the base component in any of the routes I want. It would be great if the layout to be responsible for it if there is no slot handler in the parent scope.

**Comment by wmertens** [comment]
I believe this is fixed in current Qwik. If not, please reopen and provide a repro via the playground
