### ISSUE TITLE
[🐞] No way to easily access unknown cookie names SSR for parsing

### ISSUE THREAD

**Issue by n8sabes** [BuilderIO/qwik#2451]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Currently, there does not appear to be an easy way to get **ALL** cookies from the request event. This is required if the server does not know the exact names of cookies and needs to parse through them.

There is no documentation how to access all cookies. The obvious approach (`const requestCookies = event.cookie[Symbol('request-cookies')];`) does not seem to work, and further is likely to break with future changes to core.

The best alternative seems to be overly complex and not straight forward. Here is my workaround:

```typescript
/**
 * Get all the cookies from the event
 * @param event RequestEvent
 * @returns object with all cookies
 */
const getCookies = (event: RequestEvent) => {
  const requestCookiesSymbol = Object.getOwnPropertySymbols(event.cookie).find(
    symbol => symbol.toString() === 'Symbol(request-cookies)'
  );
  const requestCookies = requestCookiesSymbol && event.cookie[requestCookiesSymbol];
  return requestCookies;
}
```

### Reproduction

n/a

### Steps to reproduce

`const requestCookies = event.cookie[Symbol('request-cookies')];` // Does not work and risky of breakage

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 805.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - ~/.nvm/versions/node/v19.0.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v19.0.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox Developer Edition: 109.0
    Safari: 16.1
```

### Additional Information

[Discord help conversation](https://discord.com/channels/842438759945601056/1053110355322212402)

**Comment by manucorporat** [comment]
We are releasing a new API with server actions soon! would you be happy to start a PR to add this?
let me know if you need any guidance! :)

**Comment by n8sabes** [comment]
@manucorporat, **DONE!** Created PR #2477 to resolve this. LMK if this is the right approach, or if a better naming convention is preferred. `getAll()` seemed like an obvious name. *Alternatively, I'd considered enhancing `get` take no arguments to return all cookies, but that got way to confusing/complex for the caller and would be a breaking change.*

**Comment by n8sabes** [comment]
Housekeeping -- Closing Issue.

Implemented by @nnelgxorz and @adamdbradley in https://github.com/BuilderIO/qwik/pull/2482. Closing issue.
