### ISSUE TITLE
[🐞] useTask$ + isServer doesn't strip/noop like useServerMount$  

### ISSUE THREAD

**Issue by jordanw66** [BuilderIO/qwik#2461]
### Which component is affected?

Qwik Runtime

### Describe the bug

Currently `useTask$` is slated to replace the other lifecycle hooks including `useServerMount$`. However, `useServerMount$` currently strips/noops from the client bundles so server-side code is not sent to the client or available to the public in general.

However, `useTask$` + `isServer` does not, as in the following code:
```tsx
useTask$(() => {
  if (isServer) {
    // this is included in the client bundles
    console.log("SUPERSECRET123");
  }
});
```
The contents of the above `if` statement are included in the client bundles and ideally should not be.

As a bonus, it would also be nice for code aesthetic and reducing indentation if the inverted early return case could be stripped as well, nice DX though not required if it poses too much extra work:
```tsx
useTask$(() => {
  if (!isServer) return;
  // everything in this block would be stripped
  console.log("SUPERSECRET123");
});
```

### Reproduction

https://github.com/jordanw66/usetask-noop

### Steps to reproduce

1. Clone repo.
2. Note respective strings inside `src/routes/index.tsx`.
3. Build.
4. Search on `dist` folder for strings.
5. The `useServerMount$` string is correctly stripped, but the other one is present.

### System Info

```shell
System:
    OS: Linux 6.1 Gentoo Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 41.24 GB / 62.73 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.volta/tools/image/node/16.17.1/bin/node
    npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
  npmPackages:
    @builder.io/qwik: 0.16.1 => 0.16.1 
    @builder.io/qwik-city: 0.0.128 => 0.0.128
```

**Comment by manucorporat** [comment]
`useServerMount$()` is deprecated in theory, but not in practice, it should still be there! agreed on this problem is very important. going to look with highest priority.

However what's your use case for `useServerMount$()` today?

**Comment by obipawan** [comment]
@manucorporat if `useServerMount$()` is deprecated but still available, doesn't that mean at some point in later releases it would be removed? If not what's the plan for `useServerMount$()`

**Comment by manucorporat** [comment]
Fixed! https://github.com/BuilderIO/qwik/pull/2527
