### ISSUE TITLE
[✨]Deploy the application under a sub-path of a domain

### ISSUE THREAD

**Issue by jasonc08** [BuilderIO/qwik#2462]
### Is your feature request related to a problem?

How to deploy the application under a sub-path of a domain? 
e.g. http:/localhost:3000/mysubpath/xxxxxx

### Describe the solution you'd like

Could qwik provide a configuration to setup the basepath just like nextjs config? 
e.g. https://nextjs.org/docs/api-reference/next.config.js/basepath

### Describe alternatives you've considered

no idea

**Comment by zanettin** [comment]
Hi @jasonc08 👋 
Thanks for proposing this feature. As far as i am aware of, this is already possible by setting a defining the `base` option on your `entry.ssr.tsx` file like:

```
export default function (opts: RenderToStreamOptions) {
  return renderToStream(<Root />, {
    manifest,
    ...opts,
    base: "/subdomain/",
    containerAttributes: {
      lang: "de",
    },
    prefetchStrategy: {
      implementation: {
        linkInsert: null,
        workerFetchInsert: null,
        prefetchEvent: "always",
      },
    },
  });
}
```
The value is then rendered as `q:base` on the generated HTML and picked up by the qwik loader.
Is this what you expect?

**Comment by jasonc08** [comment]
It does not work. The path of static photos , pages and service-worker.js remain the same.

**Comment by zanettin** [comment]
thanks for your feedback. i will have a look at it later this week 👍

**Comment by JeanMeche** [comment]
+1, to me #1488 wasn't fixed.

**Comment by JeanMeche** [comment]
I was able to deploy a working demo app [here](https://jeanmeche.github.io/qwik-app/flower/) ([repo](https://github.com/JeanMeche/qwik-app)). 

I had to tweak `entry.ssr.tsx` by setting : `base: '/qwik-app/build',` where `qwik-app` is the pathname where the app is located. 

How dirty is that and are there any downsides ?

**Comment by brianbento** [comment]
This does work for the javascript but any CSS that's linked doesn't include the pathname.

**Comment by brianbento** [comment]
As a use case, this comes in handy when an organization wants to transition slowly page by page. So the pages can be hosted on a sub-path an reverse proxied.

**Comment by sebbalex** [comment]
any updates on this?

**Comment by adamdbradley** [comment]
This should be fixed using the `base` vite config with the latest release. Please let us know if this is still an issue, thanks.

**Comment by revintec** [comment]
@adamdbradley it seems not working, I'm using qwik 0.24.0, latest version as of writting

entry.ssr.tsx
<img width="698" alt="image" src="https://user-images.githubusercontent.com/8952734/228847951-30cef368-0023-429d-a134-9337f46a353e.png">

then I run `npm run preview`

files(q-xxx.js) are still generated to `dist/build` instead of `dist/build2`
<img width="453" alt="image" src="https://user-images.githubusercontent.com/8952734/228848385-f29387ad-8186-43fe-a99b-4a277ad52bf1.png">

and of course the page won't load these q-xxx.js files
![image](https://user-images.githubusercontent.com/8952734/228848551-6f8929ab-32e1-4d81-98f1-20e8cd1d2601.png)

**Comment by brianbento** [comment]
The early days of Gatsby had similar issues. There was the need to deploy to a subpath, as well as placing files in a different location. So the URL could be `https://example.com/sub/path/here/` and place all the files into a different location such as a CDN, eg. `https://cdn.example.com/files/go/here`

Gatsby added both an `assetPrefix` and `pathPrefix` configuration.

Asset Prefix Docs
https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/asset-prefix/

Path Prefix Docs
https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/path-prefix/

**Comment by manucorporat** [comment]
Since 1.0.0 base path deplpying should work much better, out e2e test themselves are deployed with a custom base path! if issue persist, let's open a new issue!

**Comment by JeanMeche** [comment]
@manucorporat what should the plugin config be  ?

In my case I have :

```
      staticAdapter({
        origin: 'https://jeanmeche.github.io',
        base: 'qwik-city',
      })
```

But files are still pulled from the origin `https://jeanmeche.github.io`.

**Comment by wmertens** [comment]
@JeanMeche you need to pass `base: '/qwik-city/'` to vite in your vite.config

**Comment by GerardStelt** [comment]
The issue still remains. I tried about everything mentioned here and in similar issues but without any luck.

I am trying to host on GitHub pages but only the main page is loaded. All others are pulled from the GitHub root instead of the subpath of the repo.

**Comment by wmertens** [comment]
@GerardStelt can you post the link? You're using latest qwik, right?

**Comment by GerardStelt** [comment]
This is crazy, more than a year later and I am still facing the same issue...

The base path does not work properly. When set in the vite.config.ts file in the root of my project things actually do seem to work properly. The only thing is that my routes (eg. <Link href="/myroute") does not get replaced during build time with the base path. So, no matter what I try, there is always something that breaks.

Why is this so hard, it is quite a common use case right?

Github repo: https://github.com/GerardStelt/vloer-expert

**Comment by gioboa** [comment]
> The only thing is that my routes (eg. <Link href="/myroute") does not get replaced during build time with the base path.

The Vite base config set the output path to that direction. Qwik build process is not changing the link paths for you.
this could be a possible improvement though.

**Comment by loganpowell** [comment]
Though many of the answers here were helpful, I found it difficult to use just the configs to get a working app up. The issues I ran into were:

fetching resources from the public directory [broken]

correct linking between pages [broken]

I worked with co-pilot through all the debugging and had to do some surgery in order to get all the issues resolved. 

[Here is a working example](https://loganpowell.github.io/qwik-lens/) 

and the repo with [a document detailing the fixes needed to make this work](https://github.com/loganpowell/qwik-lens/blob/main/GITHUB_PAGES.md)
