### ISSUE TITLE
[📖] Add useId() reference to docs for SSR id generation

### ISSUE THREAD

**Issue by n8sabes** [BuilderIO/qwik#2468]
### Suggestion

`useId()` generates `id`s during SSR and includes microfrontend differentiation to prevent collisions. `useId()` enables animation engines, accessibility APIs, etc. to access elements by `id`, reducing client-side execution time.

[useId PR](https://github.com/BuilderIO/qwik/pull/2466)

**Comment by manucorporat** [comment]
Done!
