### ISSUE TITLE
RFC: New rendering async pipeline

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#247]
WORK IN PROGRESS

## Constrains

- State change need to produce a synchnous DOM manipulations even if affected host elements are disjoint parts of the DOM
- We need to reliably now when a component is fully rendered (including all parents) including on updates
- All DOM writes happen synchronously within a requestAnimationFrame
- Disjoint dom trees can update concurrently
- JSX factory render() can be async at all levels (loading, generation, mounting)

## Open questions

- Fine grained state transactions? is it possible to reliably group diferent state changes into a single sync DOM operation
- Can a component skip a re-render?
- Should we provide an API to signal when a component is actively rendering (updating)

https://www.figma.com/file/YN6x7gTCkmzQe2W5xRVcM4/JSX-rendering?node-id=0%3A1

**Comment by mhevery** [comment]
Per our discussion:
- Components can skip re-render.
- Very important that all callbacks get always called in a consistent/predictable order. The implication of this is that you can only be running one render process at a time AND we need to process the dom events sequentially after the render has completed.
   - later we can introduce API to explicitly allow for rendering concurrently, but the default should be sequential

**Comment by manucorporat** [comment]
Fixed https://github.com/BuilderIO/qwik/commit/7fadd186e2358c95cd5902a800c24b448e6d19c5
