### ISSUE TITLE
[📖] Invalid link on QwikCity doc

### ISSUE THREAD

**Issue by bacher** [BuilderIO/qwik#2473]
### Suggestion

You do very important thing, I appreciate QWIK a lot, but I've founded the problem in docs here: [https://qwik.builder.io/qwikcity/layout/nested/](https://qwik.builder.io/qwikcity/layout/nested/)

"top layout" link here leads to 404 page.

<img width="977" alt="image" src="https://user-images.githubusercontent.com/2598671/208486506-926940be-74a6-4cb7-a946-cbf86ea74d32.png">

**Comment by zanettin** [comment]
Hi @bacher 
Thanks for pointing that out and the kind words 🙏  i've created a PR to solve this (#2474) .
Seems to be a left-over from #2472 .

**Comment by shairez** [comment]
thanks @bacher for the report and @zanettin for the awesome work!

merged
