### ISSUE TITLE
[🐞] useOnDocument not notifying event, if the component is inside a secondary route (not inside root url)

### ISSUE THREAD

**Issue by omarbelkhodja** [BuilderIO/qwik#2487]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm using the API `useOnDocument` to register a click event over the document. I noticed that the click event doesn't always fire. I think the failure scenario is the following : 

- if the component that contains the `useOnDocument` is generated on server side, the event is fired (Correct behaviour)
- if the component that contains the `useOnDocument` is generated on client side, the event is not fired (Wrong behaviour)

### Reproduction

https://stackblitz.com/edit/qwik-starter-dcbd1c?file=src/routes/flower/index.tsx

### Steps to reproduce

I've inserted the following code inside the flower component, and added a `<Link>` to the flower route.
```javascript
const onDocumentClick$ = $(async (e: Event) => {
    alert('Document click detected from flower component !');
  });
  useOnDocument('click', onDocumentClick$);
```
1. Click on the flower link in the header to load the flower route
2. Click anywhere in the document. I'm expecting an alert to show up, but it doesn't

### System Info

```shell
Chrome on Windows 11
```

**Comment by mhevery** [comment]
@manucorporat 

Had a quick look and the `on-document:click` attribute is never rendered. So there is something weird going on.

Also in the case of the flower component it `return <>...</>` so there is no root element to attach the `on-document:click` to.

**Comment by billykwok** [comment]
Any update on the investigation? I experienced the same issue and was trying to fix it by myself. But after looking into the source code, I still have no idea what causes Qwik to skip appending `<script />`-based listeners when rendering DOM-less components on the browser side. If someone can pinpoint the underlying issue, I might be able to help create a PR to fix it.

**Comment by manucorporat** [comment]
I cant reproduce this error anymore in latest release! please open a new issue if still can be reproduced with a different repo case!
