### ISSUE TITLE
[✨] qwikVite should allow passing tsconfig

### ISSUE THREAD

**Issue by gmfun** [BuilderIO/qwik#2491]
### Is your feature request related to a problem?

Currently `qwikVite` method does not accept `tsconfig.json` path. It is hardcoded to `tsconfig.json`. Its a problem when Qwik is used inside nx workspace. 

### Describe the solution you'd like

`qwikVite` should accept `tsconfig` file name

### Describe alternatives you've considered

No alternative

### Additional context

I can add this feature if that is acceptable

**Comment by shairez** [comment]
thanks for the report @gmfun 

can you share what is your specific problem?

Plus, please try [qwik-nx](https://github.com/qwikifiers/qwik-nx) and see if the problem persists
