### ISSUE TITLE
[🐞] Tracked properties do not trigger updates for useResource$

### ISSUE THREAD

**Issue by Carson-Fricke** [BuilderIO/qwik#2496]
### Which component is affected?

Qwik Runtime

### Describe the bug

``` Typescript

Components that take props in the form below do not trigger a re-run of useResource$ when their arguments change

export default component$(({ arg=0 }: CompProps) => {

  const resource: ResourceReturn<number> = useResource$(async (ctx) => {
    ctx.track(() => arg);

    console.log("Comp2 use resource run");

    return await some_function(arg);

  });
```

### Reproduction

https://github.com/Carson-Fricke/qwik-bug-demonstration---tracked-props-do-not-cause-an-update

### Steps to reproduce

Clone the github repo and npm run dev, or visit a playground demonstration below.
[Playground Instance](https://qwik.builder.io/playground#version=0.16.1&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwUmVzb3VyY2UlMkMlMjB1c2VSZXNvdXJjZSUyNCUyQyUyMHVzZVN0b3JlJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbiU1Q25leHBvcnQlMjBpbnRlcmZhY2UlMjBDb21wUHJvcHMlMjAlN0IlNUNuJTVDbiUyMCUyMGElM0YlM0ElMjBudW1iZXIlM0IlNUNuJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwYXN5bmMlMjBmdW5jdGlvbiUyMGRvdWJsZV9pdChhcmclM0ElMjBudW1iZXIpJTIwJTNBJTIwUHJvbWlzZSUzQ251bWJlciUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjBhcmclMjAqJTIwMiUzQiU1Q24lN0QlNUNuJTVDbiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBDb21wMSUyMCUzRCUyMGNvbXBvbmVudCUyNCgocHJvcHMlM0ElMjBDb21wUHJvcHMpJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q24lMjAlMjBjb25zdCUyMHJlc291cmNlMSUyMCUzRCUyMHVzZVJlc291cmNlJTI0KGFzeW5jJTIwKGN0eCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY3R4LnRyYWNrKCgpJTIwJTNEJTNFJTIwcHJvcHMuYSklM0IlNUNuJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKCU1QyUyMkNvbXAxJTIwdXNlJTIwcmVzb3VyY2UlMjBydW4lNUMlMjIpJTNCJTVDbiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjBhd2FpdCUyMGRvdWJsZV9pdChwcm9wcy5hKSUzQiU1Q24lNUNuJTIwJTIwJTdEKSUzQiU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NSZXNvdXJjZSU1Q24lMjAlMjAlMjAlMjAlMjAlMjB2YWx1ZSUzRCU3QnJlc291cmNlMSU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjBvblBlbmRpbmclM0QlN0IoKSUyMCUzRCUzRSUyMCUzQyUzRXBlbmRpbmclM0MlMkYlM0UlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwb25SZWplY3RlZCUzRCU3QigpJTIwJTNEJTNFJTIwJTNDJTNFcmVqZWN0ZWQlM0MlMkYlM0UlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwb25SZXNvbHZlZCUzRCU3QihhYSUzQSUyMG51bWJlciklMjAlM0QlM0UlMjAlM0MlM0UlN0JhYSU3RCUzQyUyRiUzRSU3RCU1Q24lMjAlMjAlMjAlMjAlMkYlM0UpJTNCJTVDbiU3RCklM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQ29tcDIlMjAlM0QlMjBjb21wb25lbnQlMjQoKCU3QiUyMGElM0QwJTIwJTdEJTNBJTIwQ29tcFByb3BzKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUNuJTIwJTIwY29uc3QlMjByZXNvdXJjZTElMjAlM0QlMjB1c2VSZXNvdXJjZSUyNChhc3luYyUyMChjdHgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGN0eC50cmFjaygoKSUyMCUzRCUzRSUyMGEpJTNCJTVDbiU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZyglNUMlMjJDb21wMiUyMHVzZSUyMHJlc291cmNlJTIwcnVuJTVDJTIyKSUzQiU1Q24lNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwYXdhaXQlMjBkb3VibGVfaXQoYSklM0IlNUNuJTVDbiUyMCUyMCU3RCklM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDUmVzb3VyY2UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwdmFsdWUlM0QlN0JyZXNvdXJjZTElN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwb25QZW5kaW5nJTNEJTdCKCklMjAlM0QlM0UlMjAlM0MlM0VwZW5kaW5nLi4uJTNDJTJGJTNFJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG9uUmVqZWN0ZWQlM0QlN0IoKSUyMCUzRCUzRSUyMCUzQyUzRXJlamVjdGVkJTNDJTJGJTNFJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG9uUmVzb2x2ZWQlM0QlN0IoYWElM0ElMjBudW1iZXIpJTIwJTNEJTNFJTIwJTNDJTNFJTdCYWElN0QlM0MlMkYlM0UlN0QlNUNuJTIwJTIwJTIwJTIwJTJGJTNFKSUzQiU1Q24lN0QpJTNCJTVDbiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUNuJTIwJTIwbGV0JTIwc3RvcmUxJTIwJTNEJTIwdXNlU3RvcmUoJTdCJTVDbiUyMCUyMCUyMCUyMHMxJTNBJTIwMTAlNUNuJTIwJTIwJTdEKSUzQiU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUzQ2lucHV0JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0QncmFuZ2UnJTIwJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG1pbiUzRCcwJyUyMG1heCUzRCcxMDAnJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHZhbHVlJTNEJTdCc3RvcmUxLnMxJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG9uSW5wdXQlMjQlM0QlN0IoZXYpJTIwJTNEJTNFJTIwKHN0b3JlMS5zMSUyMCUzRCUyMHBhcnNlSW50KChldi50YXJnZXQlMjBhcyUyMEhUTUxJbnB1dEVsZW1lbnQpLnZhbHVlKSklN0QlMjAlMjAlMjAlMjAlMjAlMjAlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUzQ2JyJTJGJTNFJTIwQ29tcG9uZW50JTIwd2l0aG91dCUyMGRlZmF1bHQlMjBwcm9wcyUzQSU1Q24lMjAlMjAlMjAlMjAlM0NDb21wMSUyMGElM0QlN0JzdG9yZTEuczElN0QlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTNDYnIlMkYlM0VDb21wb25lbnQlMjB3aXRoJTIwZGVmYXVsdCUyMHByb3BzJTNBJTVDbiUyMCUyMCUyMCUyMCUzQ0NvbXAyJTIwYSUzRCU3QnN0b3JlMS5zMSU3RCUyRiUzRSU1Q24lMjAlMjAlM0MlMkYlM0UlM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQXBwJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NodG1sJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics        
    Memory: 5.65 GB / 15.40 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)    
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/qwik: 0.16.1 => 0.16.1
    @builder.io/qwik-city: 0.0.128 => 0.0.128
    vite: 4.0.1 => 4.0.1
```

**Comment by manucorporat** [comment]
you have to track the property, not the value:

```tsx
export default component$((props: CompProps) => {

  const resource: ResourceReturn<number> = useResource$(async (ctx) => {
    ctx.track(() => props.arg);

    console.log("Comp2 use resource run");

    return await some_function(props.arg ?? 0);

  });
```

**Comment by manucorporat** [comment]
We should look into adding a eslint rule, or some sort of warning during development for this.

**Comment by Carson-Fricke** [comment]
@manucorporat Slightly unrelated, but is there a canonical way to set default properties for a component?
