### ISSUE TITLE
[🐞] no secondary navbar on docs on mobile

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#2499]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Now there's no way to get to the second menu navbar to navigate with on mobile devices

### Reproduction

https://qwik.builder.io/docs/overview/

### Steps to reproduce

open link and use mobile emulation 

### System Info

```shell
not relevant
```

### Additional Information

![image](https://user-images.githubusercontent.com/1430726/209077760-aea27aee-1dd0-4ed2-af24-60d114c09493.png)

**Comment by zanettin** [comment]
on it 👍

**Comment by shairez** [comment]
thanks a lot @zanettin ! 🙏
