### ISSUE TITLE
[📖] [🐞]  Resource Not Found - Docs 

### ISSUE THREAD

**Issue by geongeorge** [BuilderIO/qwik#2505]
### Suggestion

Hi, Awesome work with the framework. I was trying to learn qwik, but I'm seeing many links in the docs lead to a 404. I added the bug emoji because I think this is a bug with the docs website

eg:

- https://qwik.builder.io/qwikcity/adaptors/node/
- https://qwik.builder.io/qwikcity/adaptors/overview/

The source of these links is the [FAQ Page](https://qwik.builder.io/docs/faq/)

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/29296982/209232014-d835e943-3adf-4bf1-a7d0-f4231b2e6d37.png">

**Comment by zanettin** [comment]
Hi @geongeorge 
Thanks for creating this issue 🙏  Part of this is already tackled on the above linked PR. Hope to fix all of them soon. Happy testing and let us know about any further issues/problem 🙏

**Comment by zanettin** [comment]
PR was merged and links should work as expected 👍

**Comment by geongeorge** [comment]
Thank you for fixing this so fast

**Comment by zanettin** [comment]
@geongeorge thank you for mentioning it 🙏

**Comment by RinkAttendant6** [comment]
I still get this error when navigating from the home page of the site. The URL goes to https://qwik.builder.io/docs/overview/ which responds with a 404.

**Comment by zanettin** [comment]
Hi @RinkAttendant6 
Thanks for mentioning this 🙏 There was a new issue for that problem opened over here #2583.
