### ISSUE TITLE
[🐞] Vercel Edge Adapter breaks build - Cannot bundle Node.js built-in "events" imported by Nodemailer

### ISSUE THREAD

**Issue by ahashem95** [BuilderIO/qwik#2524]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

- I'm trying to build my locally with Vercel Edge adapter installed and `nodemailer` dependency installed which is used only within `onPost` but receiving the following error:
```
[commonjs--resolver] Cannot bundle Node.js built-in "events" imported from "node_modules/nodemailer/lib/smtp-transport/index.js". Consider disabling ssr.noExternal or remove the built-in dependency.
``` 

I tried to set `ssr.noExternal` in `vite.config.ts` but didn't work.

### Reproduction

https://stackblitz.com/edit/qwik-starter-d9bi9m?file=.eslintignore

### Steps to reproduce

Run `npm install` followed by `npm run build`

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 148.23 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2022.09.19.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 105.0.3
    Safari: 16.1
  npmPackages:
    @builder.io/partytown: ^0.7.0 => 0.7.2 
    @builder.io/qwik: 0.16.1 => 0.16.1 
    @builder.io/qwik-city: 0.1.0-beta6 => 0.1.0-beta6 
    vite: 3.1.7 => 3.1.7
```

**Comment by manucorporat** [comment]
The vercel edge does not support node apis, i would open an issue in nodemailer or use a different package that is not node dependant. This is not an issue with Qwik, it will happen in any framework deploying to Vercel!
