### ISSUE TITLE
[🐞] Invalid Discord invite link on docs website

### ISSUE THREAD

**Issue by shaunchander** [BuilderIO/qwik#2533]
### Which component is affected?

Qwik Runtime

### Describe the bug

The Discord invite link on https://qwik.builder.io/ is invalid.

### Reproduction

https://qwik.builder.io/

### System Info

```shell
n/a
```

**Comment by zanettin** [comment]
Hi @shaunchander 
Thanks for creating this issue 🙏 Wanted to dbl check it and for me it looks good when I click on the discord icon on the top-right icon set. Where did you click and what was the target page for you? I am landing on the "👋 -welcome" channel within the "Builder.io" space 👍
