### ISSUE TITLE
[🐞] Cloud run adaptor is not available in `qwik-city/adaptors`

### ISSUE THREAD

**Issue by ahnpnl** [BuilderIO/qwik#2535]
### Which component is affected?

Starters / CLI

### Describe the bug

When adding Google Cloud Run adaptor with `yarn` following the doc https://qwik.builder.io/integrations/deployments/gcp-cloud-run/#google-cloud-run-middleware, the generated file `vite.config.ts` complains that `import { cloudRunAdaptor } from '@builder.io/qwik-city/adaptors/cloud-run';` doesn't exist which leads to build failure.

Here is the screenshot of my `node_modules`
<img width="361" alt="image" src="https://user-images.githubusercontent.com/27772165/210135244-e21ffb67-48c7-44dd-97b8-3178a732c478.png">

This error occurs from the `latest` tag to `beta` tag of `qwik-city`

### Reproduction

https://stackblitz.com/edit/qwik-starter-ml3s8p?file=README.md

### Steps to reproduce

Run `npm run qwik add cloud-run` and observe errors.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 215.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0
    Safari: 16.2
```

### Additional Information

The codes for Cloud Run is available at https://github.com/BuilderIO/qwik/tree/main/packages/qwik-city/adaptors/cloud-run but I don't know why the npm packages don't have them.

**Comment by DustinJSilk** [comment]
This will be fixed when this PR is merged and released https://github.com/BuilderIO/qwik/pull/2613
