### ISSUE TITLE
[🐞] function, which is not serializable

### ISSUE THREAD

**Issue by strowk** [BuilderIO/qwik#2539]
### Which component is affected?

Qwik Runtime

### Describe the bug

I pass down function onSaved from parent component to child, which is pretty standard in frontend frameworks (like f.e React). It works on in dev mode, but when I try to build I get this error:
```
Identifier ("onSaved") can not be captured inside the scope ($) because it is a function, which is not serializable.
```

I don't get what is wrong there. It points me to this page:
https://qwik.builder.io/docs/advanced/optimizer/
, which does not explain what I have to do at all. 

I have to use `$()`, because otherwise qwik fails in dev mode with this error "Invalid JSXNode type. It must be either a function or a string" 

### Reproduction

I dont have it

### Steps to reproduce

This is a code that fails
```
({ details, onSaved }: MyProperties) => {
    const state = useStore({
      x: details.x,
      y: details.y,
    });

    const save = $(async () => {
      await saving(state.x, state.y);
      onSaved && onSaved();
    });

```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: 0.16.1 => 0.16.1 
    @builder.io/qwik-city: 0.0.128 => 0.0.128 
    vite: 4.0.1 => 4.0.1
```

**Comment by manucorporat** [comment]
Please refer to:
https://qwik.builder.io/docs/advanced/dollar/

and https://qwik.builder.io/docs/components/events/#events-and-components

I cant help without you sharing a full reproduction, but the issue is most likely caused because you have a custom event with the wrong type.
