### ISSUE TITLE
[🐞] onChange events in inputs don't actually update state on change

### ISSUE THREAD

**Issue by shaunchander** [BuilderIO/qwik#2549]
### Which component is affected?

Qwik React

### Describe the bug

When using `onChange$` event handler on an `input` coupled with a signal in Qwik, the signal's value does not get updated while the user is typing in the form. This creates issues with form submissions as potential `null` values can be passed to a `onSubmit` handler.

I found that clicking away from the input field will update the signal's value, however, the correct behavior should be that the signal's value is updated as the input is being changed. 

### Reproduction

tbd

### Steps to reproduce

1. Create an input and signal
2. Use `onChange$()` to capture the change event and update the signal's value by setting `signal.value = e.target.value`
3. Consume `signal.value` in a `onSubmit` handler

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 1.06 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.133
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.16.1 => 0.16.1 
    @builder.io/qwik-city: 0.0.128 => 0.0.128 
    vite: 4.0.3 => 4.0.3
```

**Comment by manucorporat** [comment]
This is how HTML works:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event

>When the element loses focus after its value was changed: for elements where the user's interaction is typing rather than selection, such as a [<textarea>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) or the [text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text), [search](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search), [url](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url), [tel](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel), [email](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email), or [password](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password) types of the [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element.

What you need is `onInput$`!
