### ISSUE TITLE
[✨] do not rely on "name" property from package json to scope the q-manifest.json file in tmp directory

### ISSUE THREAD

**Issue by dmitry-stepanenko** [BuilderIO/qwik#2551]
### Is your feature request related to a problem?

As part of this fix https://github.com/BuilderIO/qwik/pull/2398 there was added the logic to rely on the name property from `package.json` for the temporary manifest file. It appears to be not really convenient in project setups w\o package.json, for example in an Nx repo. 

Moreover, "name" property is optional in package.json, so it's still possible to encounter the issue with parallel builds if it's not specified

### Describe the solution you'd like

Instead of relying on the name property from package.json it might be reasonable to use something more generic, maybe the hash of the project root path of a certain app or something like that

**Comment by manucorporat** [comment]
we cant delegate on the absolute of the root, because it would not be stable

**Comment by gioboa** [comment]
We have a response and the issue is stale. I close it.
