### ISSUE TITLE
[✨] docs notes for `loader$` and `onGet` changes on 0.1.0-beta8+

### ISSUE THREAD

**Issue by zanettin** [BuilderIO/qwik#2560]
Wanted to start with some docs change proposals to bring `loader$` and `action$` in and remove the usage of `useEndpoint` where listed. While playing around with them and checking the existing code snippets, i've recognized that  some things are no longer working as expected and/or we no longer have straight access to them. below a list which is aimed to act as storybook for the new docs.

# `loader$`
## basic usage
To fetch data and make them available on your component you can define several `loader$` functions like this:
```
const getColor = loader$(() => {
  return ['blue', 'red', 'yellow'];
});

const getNumber = loader$(() => {
  return [1,2,3,4,5]
});

const getPerson = loader$(() => {
  return {
    firstName: 'John',
    lastName: 'Doe',
    age: 38
  };
});

export const component$(() => {
  const color = getColor.use();
  const number = getNumber.use();
  const person = getPerson.use();
  
 return (
   <span>{color.value} | {number.value} | {person.value.firstName}</span>
 );
});
```

There is no longer any need to use `useEndpoint()` to get access to the fetched values. 

## Use on `head` functions
To use the data on the document head as well, you can make use of the `getData` helper function on the `head` function like this:

**example code**
```
export const head: DocumentHead = ({getData}) => {
  const color = getData(getColor);
  const number = getData(getNumber);
  const person = getData(getPerson);

  return {
    title: `${color} ${number} - ${person.firstName}`
  }
}
```

# params
Available params on `onGet` and `loader$` functions.

## param `response`
both `onGet` and `loader$` do **no longer** have access to the final response object. instead there are `cacheControl`, `headers` and `redirect`.

## param `headers`
Till now we could set headers which then were applied to the final HTML response sent to the client using the `response` object. New there is a `header` map instead.

**0.0.128**
```
export const onGet: RequestHandler = ({response}) => {
  response.headers.set('x-custom-header','custom value');
}
```

**0.1.0-beta8**
```
export const onGet: RequestHandler = ({headers}) => {
  headers.set('x-custom-header','custom value');
}
```
🚨 does not work on dev server but is testable when running `pnpm preview` 👍 

## param `cacheControl`
**0.0.128**
```
export const onGet: RequestHandler = ({ response }) => {
  response.headers.set(
    'Cache-Control',
    'public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400'
  );
};
```

**0.1.0-beta8**
```
export const onGet: RequestHandler = ({ cacheControl }) => {
  cacheControl({
    public: true,
    maxAge: 3600,
    sMaxAge: 3600,
    staleWhileRevalidate: 86400,
  });
};
```
🚨 does not work on dev server but is testable when running `pnpm preview` 👍 

## param `redirect`
changed order of params for redirect.

**0.0.128**
```
export const onGet: RequestHandler = ({response}) => {
  throw response.redirect("/", 302);
}
```

**0.1.0-beta8**
```
export const onGet: RequestHandler = ({redirect}) => {
  throw redirect(302, "/");
}
```

## param `exit`
renamed `abort` to `exit` which prevents other middlewares of being called.

**0.0.128**
```
export const onGet: RequestHandler = ({abort}) => {
  abort();
}
```

**0.1.0-beta8**
```
export const onGet: RequestHandler = ({exit}) => {
  exit();
}
```

## param `json`
Convenience method to JSON stringify the data and send it in the response. The response will be automatically set the `Content-Type` header to `application/json; charset=utf-8`.

## param `html`
Convenience method to send an HTML body response. The response will be automatically set the `Content-Type` header to`text/html; charset=utf-8`.

## parm `text`
Convenience method to send an text body response. The response will be automatically set the `Content-Type` header to`text/plain; charset=utf-8`.

## param `error`
When called, the response will immediately end with the given status code. This could be useful to end a response with `404`, and use the 404 handler in the routes directory.

## param `send`
Method to send a body response. The `Content-Type` response header is not automatically set when using `send()` and must be set manually. 

```
const onGet: RequestHandler = ({send}) => {
   send(418, 'I am a teapot');
}
```

**Comment by tuurbo** [comment]
To get data in the head
```
export const head: DocumentHead = ({ getData }) => {
  const data = getData(productLoader);

  return {
    title: data.title,
  }
}
```

**Comment by zanettin** [comment]
thanks a lot @tuurbo 🙏

**Comment by VinSpee** [comment]
> ## param `response`
> both `onGet` and `loader$` do **no longer** have access to the final response object. instead there are `cacheControl`, `headers` and `redirect`.

This is an interesting change. What’s the rationale behind it?

**Comment by zanettin** [comment]
> > ## param `response`
> 
> > both `onGet` and `loader$` do **no longer** have access to the final response object. instead there are `cacheControl`, `headers` and `redirect`.
> 
> 
> 
> This is an interesting change. What’s the rationale behind it?

good question. just had a look at https://github.com/BuilderIO/qwik/blob/cbbe79a534c660ce2ec153832a928f3d7d275a39/packages/qwik-city/middleware/request-handler/request-event.ts where the params are defined and for me it looks like a needed step to create this abstraction because of the new ability to have multiple loader$ fns instead of just a single onGet.

**Comment by VinSpee** [comment]
> for me it looks like a needed step to create this abstraction because of the new ability to have multiple loader$ fns instead of just a single onGet.

That totally makes sense. Thanks!

**Comment by zanettin** [comment]
will all be covered in #2722 🙏

**Comment by Nefcanto** [comment]
When would it be published? Do we have this in `0.16.2`? Or should we wait for `0.16.3`?

**Comment by zanettin** [comment]
not sure @Nefcanto. as far as i can see the core team is finalizing everything now for the release. guess it depends on new bugs that gets mentioned 😂

**Comment by Nefcanto** [comment]
Qwik is awesome. We're just so hungry we wanna eat it completely :D.

We can't wait to move our entire company to Qwik and get speedy websites. Thank you @zanettin.

**Comment by zanettin** [comment]
totally feel with you 🥳🎉

**Comment by felixsanz** [comment]
@zanettin how to 404 in `[products]/index.tsx` when doing this?

```js
export function onGet({ params, error }: RequestEvent): null | void {
  const product = products.find(........)

  if (!product) {
    error(404, 'Not found')
  }
}
```

This example kinda works but not the way is supposed. head() and component$() for that route is still called. A redirection to /404 is a very bad practice. How to do 404 in a collection page?

Docs are outdated and reflect the old API, which is not used anymore and still had the same problems

**Comment by zanettin** [comment]
Hi @felixsanz 👋
just had a look at the latest doc chances for the qwik-city 0.1.0 release and it seams to be the way to go: https://github.com/BuilderIO/qwik/pull/2722/files#diff-301e4735e348b976f16b3be332ec584ba84339ea38a3d30b10e59a5f434c02f9R17

imo it makes sense this way so you can decide on component level what you want to render in the 404 case.

hope i understod your question correctly.

**Comment by felixsanz** [comment]
> Hi @felixsanz wave just had a look at the latest doc chances for the qwik-city 0.1.0 release and it seams to be the way to go: https://github.com/BuilderIO/qwik/pull/2722/files#diff-301e4735e348b976f16b3be332ec584ba84339ea38a3d30b10e59a5f434c02f9R17
> 
> imo it makes sense this way so you can decide on component level what you want to render in the 404 case.
> 
> hope i understod your question correctly.

Hey! i've seen that already because it's the same as the outdated docs that are online. That documentation uses `response` parameter inside `onGet`. This PR got rid of that. That whole documentation fragment is useless now

**Comment by zanettin** [comment]
you're right. manu is still on them to finalize. and i've picked the lagecy one. sry for that! on the advance routing section is an example as well which looks updated for me. feel free to comment things on manu's PR so he can male the changes right away 🙏

**Comment by zanettin** [comment]
that's how i've implemented it on a demo app:
**loader$**
```
// validate data
    if (!result.data?.environment?.routeByPath?.object?.id) {
      error(404, "page not found");
      return { data: null };
    }
```

**component**
```
return (
    <Resource
      value={data}
      onPending={() => <div>Loading...</div>}
      onRejected={() => <div>Error</div>}
      onResolved={(item: any) =>
        (item?.data &&
          renderContentTypeByTypename(
            item?.data?.environment?.routeByPath?.object
          )) || <p>not found</p>
      }
    />
  );
```

**Comment by felixsanz** [comment]
@zanettin Thanks for the help! You inspired me to come with a solution based on yours.

I finally got it like this:

1. Settting 404 status code inside `onGet` handler:

```js
export const onGet: RequestHandler = async ({ params, error }) => {
  const post = posts.find(({ metadata }) => (metadata.slug === params.post))

  if (!post) {
    error(404, 'Not found')
  }
}
```

2. Having a `loader$` that gives me `post` or `undefined` (if post is missing).

```js
export const getPost = loader$(({ params }) => {
  return posts.find(({ metadata }) => (metadata.slug === params.post))
}
```

3. I consume that loader inside `head()` and `component$`, like this:

```js
  const post = getPost.use().value

  return ((post)
    ? <PostLayout metadata={post.metadata} headings={post.headings}>.....</PostLayout>
    : <ErrorLayout status={404} />
  )
```

_1 and 2 can be mixed into one (ie: have `error()` inside `loader$`), but I prefer it like this._

**Comment by zanettin** [comment]
@felixsanz great to hear! and happy coding 🎉
