### ISSUE TITLE
[✨] Remove`loader$` data from `qwik/json`

### ISSUE THREAD

**Issue by zanettin** [BuilderIO/qwik#2572]
### Is your feature request related to a problem?

At the moment all data returned from an `onGet` / `loader$` function usage, are included in the `qwik/json` data, even if the data are no longer used on the client. in cases where a lot of data are aggregated for creating the initial HTML on the server this could lead to heavy HTML files. Streaming helps of corse but as a further optimization we should also consider reducing the `qwik/json` size where possible.

### Describe the solution you'd like

If the data are just need on the server, they should no longer be part of the `qwik/json` and be removed like it is the case on other frameworks (astro).

### Describe alternatives you've considered

Instead of automatically remove this data we could mybe add a config option/reducer fn to limit the data somehow.

**Comment by manucorporat** [comment]
fixed! https://github.com/BuilderIO/qwik/commit/aa20aa769fb1c09d4608eb86fedd76fd5fc47a33
