### ISSUE TITLE
[🐞] Issue with new loader$ and $action API

### ISSUE THREAD

**Issue by adam-r-kowalski** [BuilderIO/qwik#2582]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I'm testing out the new server actions API with `loader$` and `action$` but ran into some strange behavior.

I created a very simple example here https://stackblitz.com/edit/qwik-starter-lssxx4?file=src/routes/layout.tsx

To set the context

There is a list of items
A form with an input and button which adds your item to the list of items
If you click an item it takes you to the page for that item
There you can either clear your selection or delete the item

This seems to work on first glance however if you perform the following steps you get a bug.

1. Click bob
2. Click delete (this deletes bob as expected)
3. Click sally (this deletes sally?)

It seems as if the action repeats from that point on until you refresh the page.

To make the example as simple as possible only 3 files contain relevant code

- routes/index.tsx
- routes/layout.tsx
- routes/[id]/index.tsx

### Reproduction

https://stackblitz.com/edit/qwik-starter-lssxx4?file=src/routes/layout.tsx

### Steps to reproduce

1. Click bob
2. Click delete (this deletes bob as expected)
3. Click sally (this deletes sally?)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh

  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm

  npmPackages:
    @builder.io/qwik: ^0.16.1 => 0.16.2 
    @builder.io/qwik-city: ^0.1.0-beta6 => 0.1.0-beta8 
    undici: 5.14.0 => 5.14.0 
    vite: 3.2.4 => 3.2.4
```

**Comment by manucorporat** [comment]
Fixed in https://github.com/BuilderIO/qwik/commit/4a9f4cdcb5e9b8efeb5a9252330eda3c197159ac
