### ISSUE TITLE
[🐞] Qwik DOCS page is 404

### ISSUE THREAD

**Issue by lukonik** [BuilderIO/qwik#2583]
### Which component is affected?

Qwik Runtime

### Describe the bug

- go to https://qwik.builder.io/
- click Docs link
- you will be navigated to 404 instead of doc page

### Reproduction

https://qwik.builder.io/docs/overview/

### System Info

```shell
No info
```

**Comment by zanettin** [comment]
Thanks @lukonik for mentioning this 🙏  Just had a look and FMPOV locally the files are there and routing is working. So i would assume that something failed during the last deployment of the docs. Hope anybody with write permissions can have a look at it as well 😄 @shairez @adamdbradley @manucorporat @mhevery 🙏

**Comment by lukonik** [comment]
Meanwhile this link works so you can navigate to docs from here https://qwik.builder.io/docs/getting-started/ :)

**Comment by zanettin** [comment]
Thanks @lukonik 🙏 looks like the docs are now fully back. Can you confirm that?

**Comment by lukonik** [comment]
Yeap It works indeed, thank you!. I'll close the issue
