### ISSUE TITLE
Change toUppercase() to toUpperCase() - Vercel Build Error

### ISSUE THREAD

**Issue by jimmyjamieson** [BuilderIO/qwik#2597]
https://github.com/BuilderIO/qwik/blob/1f5d1b6cdeb60cf582244e0f8d6e5a928148eaf1/packages/qwik-city/adaptors/shared/vite/post-build.ts#L114

**Comment by jimmyjamieson** [comment]
https://github.com/BuilderIO/qwik/commit/b83cad8dd29b7b9f8d64f31d2e09bd6257a8cea3

**Comment by adamdbradley** [comment]
Thanks for pointing this out. Should be fixed soon: https://github.com/BuilderIO/qwik/pull/2554/commits/62f2c22fc9f96da1cf10f0b515cc63f73d6215b1

**Comment by DustinJSilk** [comment]
If anyone needs a quick workaround until this is released:
`(String as any).prototype.toUppercase = String.prototype.toUpperCase;`
