### ISSUE TITLE
[✨] `logError` prevents proper Sentry error capturing

### ISSUE THREAD

**Issue by jessezhang91** [BuilderIO/qwik#2618]
### Is your feature request related to a problem?

I have hooked up Sentry alert monitoring on top of my Qwik app. As part of that, I needed to use their `CaptureConsole` integration because of the `logError` implementation here: https://github.com/BuilderIO/qwik/blob/70880b71995361202ae0b4725454cb2bd008ab2d/packages/qwik/src/core/util/log.ts#L10-L16

Because of this, I can't pass the raw error to Sentry and we can't get niceties like stack trace remapping via sourcemap.

### Describe the solution you'd like

I would like a configuration for production builds to either tap into `logError` (e.g. a callback) or for production builds to just re-throw errors in `logError` (which Sentry will catch).

### Describe alternatives you've considered

n/a

**Comment by DustinJSilk** [comment]
@jessezhang91 did you find a solution to this and manage to get sentry working properly?

**Comment by Kocal** [comment]
I'm also interested with a good way to setup Sentry on the browser-side (and maybe on the server side?)

**Comment by jessezhang91** [comment]
@DustinJSilk @Kocal we hacked around it by modifying something like: https://github.com/getsentry/sentry-javascript/blob/master/packages/integrations/src/captureconsole.ts

```
class CaptureQwikError implements Integration {
  static id = 'CaptureQwikError';
  name = CaptureQwikError.id;

  setupOnce(_: unknown, getCurrentHub: () => Hub): void {
    fill(GLOBAL_OBJ.console, 'error', (originalConsoleMethod: Console['error']) => (...args: any[]) => {
      if (args[0] === '%cQWIK ERROR') {
        const hub = getCurrentHub();

        if (hub.getIntegration(CaptureQwikError)) {
          hub.withScope((scope) => {
            scope.setLevel('error');
            scope.addEventProcessor((event) => {
              event.logger = 'qwik-error';
              return event;
            });
            hub.captureException(args[2], { originalException: args[2] });
          });
        }
      }

      if (originalConsoleMethod) {
        originalConsoleMethod.apply(GLOBAL_OBJ.console, args);
      }
    });
  }
}
```

it gets us close enough but it's definitely missing stacktrace/etc.

i'm happy to attempt a PR but not sure if the core team has any thoughts on how to tackle this already. my thought is to expose some global qwik configuration options that the `logError` can call but that would definitely introduce new concepts/conventions that i'm not sure if the core team wants/etc.

**Comment by Kocal** [comment]
Thanks for sharing your code @jessezhang91 :) 

Indeed that's not perfect, but that's better than nothing
