### ISSUE TITLE
[🐞] Cannot deploy to Vercel or Netlify with qwik-city 0.1.0-beta9

### ISSUE THREAD

**Issue by adam-r-kowalski** [BuilderIO/qwik#2619]
### Which component is affected?

Qwik City (routing)

### Describe the bug

If you do a pnpm create qwik@latest fill out the prompts cd into the directory and then do pnpm qwik add and select netlify (or vecel) then deploy, everything works fine.

However if you go to your package.json and bump to "@builder.io/qwik-city": "0.1.0-beta9" do a pnpm install and then redeploy things fail.

You see TypeError: method.toUppercase is not a function using Netlify

and TypeError: e.toUppercase is not a function using Vercel

### Reproduction

https://stackblitz.com/edit/qwik-starter?file=README.md

### Steps to reproduce

1. `pnpm create qwik@latest`
2. `cd project_name`
3. `pnpm install`
4. `pnpm qwik add`
5. Select either Vercel or Netlify (bug appears in both)
6.  Deploy your project through Vercel or Netlify
7.  You see `TypeError: method.toUppercase is not a function` on deployed app

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 210.11 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 106.0.2
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2 
    @builder.io/qwik-city: 0.1.0-beta9 => 0.1.0-beta9 
    undici: 5.14.0 => 5.14.0 
    vite: 4.0.3 => 4.0.3
```

**Comment by zanettin** [comment]
Hi @adam-r-kowalski 
Thanks for mentioning this. Sounds for me like [this one](https://github.com/BuilderIO/qwik/issues/2597). Hope the fix will be released soon.

**Comment by adam-r-kowalski** [comment]
Perfect, anything more I can do on my end to help reproduce or explain more context?

**Comment by zanettin** [comment]
@adam-r-kowalski the PR was merged so i guess we just have to wait for the latest release of qwik-city 👍

**Comment by adam-r-kowalski** [comment]
Great to hear, thanks for the quick turnaround time!

**Comment by hyunjunian** [comment]
When does it release?
