### ISSUE TITLE
[🐞]Export more types for typing `loader$` and `action$`

### ISSUE THREAD

**Issue by zhuhaow** [BuilderIO/qwik#2623]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm not exactly sure how `loader$` is designed to be used since there is no doc yet.

As I'm trying it out, I'm using it like this,

```ts
export const loadData = loader$(async ({platform}) => {
  return loadDataFromSomewhere(platform);
});
```

The problem is type inference. The `loader$` is typed `export declare const loader$: <PLATFORM, B>(first: (event: RequestEventLoader<PLATFORM>) => B) => ServerLoader<B>;`. Since I want to let ts infer `B` and ts doesn't support partial inference, I need to somehow let it also infer `PLATFORM`. 

But `RequestEventLoader<PLATFORM>` is not exported so I cannot write 

```ts
export const loadData = loader$(async ({platform}: RequestEventLoader<SOMETYPE>) => {
  return loadDataFromSomewhere(platform);
});
```

And I cannot write 

```ts
export const loadData = loader$(async ({platform}: {platform: SOMETYPE}) => {
  return loadDataFromSomewhere(platform);
});
```

as that would require me to define all types in `RequestEventLoader` if I want to use anything from there.

`action$` has the similar problem and the type def is missing platform (`(form: FormData, event: RequestEventLoader) => ValueOrPromise<B>`)

Export `RequestEventLoader` would fix this problem.

### Reproduction

N/A

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 537.19 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2
    @builder.io/qwik-city: 0.1.0-beta9 => 0.1.0-beta9
    vite: 4.0.4 => 4.0.4
```

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/commit/95aaa78a8de18fd40e5f70f71ef2d9e60eff0be7

Thanks a lot for the testing!
