### ISSUE TITLE
[🐞] unresolved type QwikManifest in Basic app

### ISSUE THREAD

**Issue by await-ovo** [BuilderIO/qwik#2625]
### Which component is affected?

Qwik Runtime

### Describe the bug

![image](https://user-images.githubusercontent.com/41503212/212068992-952b1246-a820-446e-9093-1c24c49d4ee7.png)
![image](https://user-images.githubusercontent.com/41503212/212069064-13eb70b5-14ae-4528-a0b0-5b59751bdfc5.png)

### Reproduction

https://stackblitz.com/edit/qwik-starter?file=src%2Fentry.ssr.tsx

### Steps to reproduce

1. `pnpm create qwik@latest`

```
🐰 Let's create a Qwik app 🐇   v0.16.2

✔ Where would you like to create your new project? … npm-demo

✔ Select a starter › Basic App (QwikCity)

✔ Would you like to install pnpm dependencies? … no

```

2.  `cd npm-demo && npm install`

3. You can see that  `manifest` in `entry.ssr.tsx` resolved to  type any

### System Info

```shell
System:
    OS: macOS 11.6.8
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 752.60 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2
    @builder.io/qwik-city: 0.0.128 => 0.0.128
    undici: 5.14.0 => 5.14.0
    vite: 4.0.3 => 4.0.3
```

**Comment by zanettin** [comment]
Hi @await-ovo 👋 
Thanks for mentioning this 🙏  The mentioned issue is also present on `qwik@0.19.0` and `qwik-city@0.3.0`.
