### ISSUE TITLE
[🐞]Issue with qwik city 0.1.0-beta9 action$

### ISSUE THREAD

**Issue by adam-r-kowalski** [BuilderIO/qwik#2644]
### Which component is affected?

Qwik City (routing)

### Describe the bug

THE CONTEXT

There are two routes, the root route, and the other route.
There is "database" which is just an array of strings inside of src/data.ts

On the root route there is a form which if you type into it and submit, it adds the text to the "database" and then redirects you to the other route.

On the other route it shows you each item in the "database" as well as a form which you can use to add text to the "database".

THE PROBLEM

From the root route you can successfully use the form and get redirected to the other route.

However, from the other route if you use the form, instead of adding to the database it redirects you back to the root route, and never triggers the action. You can verify this by looking at the console logs.

### Reproduction

https://stackblitz.com/edit/qwik-starter-ybxjwc?file=src%2Froutes%2Findex.tsx,src%2Froutes%2Fother%2Findex.tsx

### Steps to reproduce

1. In the root route type anything in the form and press enter
2. You should get redirected to the other route which should show the text you typed previously as well as a form
3. Type something into that form and press enter
4. [BUG] Instead of seeing that item get added to the list, you get redirected to root route

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^0.16.2 => 0.16.2 
    @builder.io/qwik-city: 0.1.0-beta9 => 0.1.0-beta9 
    undici: 5.14.0 => 5.14.0 
    vite: 3.2.4 => 3.2.4
```

**Comment by adam-r-kowalski** [comment]
Follow up with this, if you disable javascript and run through this example locally it works fine.

**Comment by manucorporat** [comment]
great issue report! i am looking into it

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/commit/71b252f817bcba3342c6e49b9f905cf440948391

**Comment by adam-r-kowalski** [comment]
Awesome, thanks! Is there any way to play around with that today or do I need to wait till `0.1.0-beta10` is released?

**Comment by zanettin** [comment]
@adam-r-kowalski there is a [repo](https://github.com/BuilderIO/qwik-city-build) with the latest build assets and imo you should be able to install that directly.

**Comment by adam-r-kowalski** [comment]
Awesome, thanks!
