### ISSUE TITLE
Qwik City feature: To be able to get the IP address of the initial client's request[✨]

### ISSUE THREAD

**Issue by alf5** [BuilderIO/qwik#2648]
### Is your feature request related to a problem?

Be good to be able to add logic to the app that is based on the IP address of the incoming request.

### Describe the solution you'd like

Be able to query the request's IP address (the originating client's IP address, using Headers from proxys, etc...)

### Describe alternatives you've considered

N/A

### Additional context

svelte kit: https://github.com/sveltejs/kit/pull/4289

**Comment by samyosm** [comment]
Yeah, that would be awesome. A trick I found is to get the ip from the client and send it to the back-end.
