### ISSUE TITLE
[✨] Compress SVG nodes with svgo

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#2649]
### Is your feature request related to a problem?

SVG can be compressed and optimised a lot. By using a tool like (svgo)[https://github.com/svg/svgo], developers won't need to manually copy/paste their SVG files into (OMGSVG)[https://jakearchibald.github.io/svgomg/] or similar to improves the size and performance.

### Describe the solution you'd like

- Automatically detect SVG nodes in a component and run it against svgos optimiser at build time.
- Allow using a svgo.config.js file to fine tune the optimisations and results

### Describe alternatives you've considered

I've looked at the current svg output by qwik which looks minified, not optimised. But i could be wrong.
I also didnt see svgo in the qwik repo

**Comment by wmertens** [comment]
To me, this seems like something that should be done in a plugin. Not everyone would want this and not everyone would want it with the same settings...

**Comment by DustinJSilk** [comment]
Thanks for the response @wmertens!

I'd be surprised if people don't want to optimise their SVGs.
I think it could be a great selling point to have immediate, native support, since this is a performance based framework it fits right in.

It could be provided with settings to give freedom to the user to decided if/how to use it, with some standard settings by default for immediate access. As with anything, we can make it opt in or out.

**Comment by manucorporat** [comment]
New image optiization uses svgo!
