### ISSUE TITLE
[🐞] Custom route - 404 not found 

### ISSUE THREAD

**Issue by terza98** [BuilderIO/qwik#2654]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am trying to simply send an email using a custom endpoint. As explained in documentation - I should be able to do so by creating a file inside routes directory with the .ts extension instead of .tsx

That's what I've done by implementing a simple route handler as explained here: https://qwik.builder.io/qwikcity/data/endpoints/

My route handler resides in `/contact/send-email.ts` file.

Later I am trying to fetch this route like this:
` await fetch("/contact/send-email", {
      method: "POST",
      body: data,
    });`

But this gives me 404 error. 

### Reproduction

https://stackblitz.com/edit/qwik-starter-9spyjw?file=src/routes/index.tsx

### Steps to reproduce

Run `npm install` followed by `npm start`

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 139.31 MB / 8.00 GB
    Shell: 3.4.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 15.6.1
  npmPackages:
    @builder.io/partytown: ^0.7.1 => 0.7.1
```

**Comment by manucorporat** [comment]
Qwik is directory based: https://qwik.builder.io/qwikcity/routing/overview/

it should be:
```
routes/send-email/index.ts
```

:)

**Comment by terza98** [comment]
Ah shoot, thanks
