### ISSUE TITLE
[🐞] Importing an image with vite-imagetools vars causes an error

### ISSUE THREAD

**Issue by jimjamdev** [BuilderIO/qwik#2655]
### Which component is affected?

Qwik Runtime

### Describe the bug

When  importing an image into the app and using vite-imagetools i.e

```import TestImage from '/images/image.jpg?w=400&h=300&webp';```

Qwik throws an "Input file is missing error"

It works without the params ```import TestImage from '/images/image.jpg';```

---

It seems it's looking for the params as part of the image name instead of parsing via imagetools

### Reproduction

https://github.com/jimmyjamieson/qwik-starter/blob/vite-imagetools/src/routes/%5B...locale%5D/index.tsx

### Steps to reproduce

Update your vite config with vite-imagetools

```
export default defineConfig(() => {
  return {
    plugins: [
      qwikCity(),
      qwikVite(),
      tsconfigPaths(),
      imagetools(),
    ],
  };
});
```

Import an image somewhere 

```
import TestImage from '/images/image.jpg?w=400&h=300&webp'; 
```

See the error.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.76 GB / 15.70 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/partytown: ^0.7.4 => 0.7.4
    @builder.io/qwik: ^0.16.2 => 0.16.2
    @builder.io/qwik-city: ^0.1.0-beta9 => 0.1.0-beta9
    undici: ^5.15.0 => 5.15.0
    vite: ^4.0.4 => 4.0.4
```

**Comment by manucorporat** [comment]
New image optimization in 1.2.0 is the way to go!
