### ISSUE TITLE
[🐞]  Qwik homepage styling

### ISSUE THREAD

**Issue by martuico** [BuilderIO/qwik#2656]
### Which component is affected?

Starters / CLI

### Describe the bug

Styling issue on homepage
<img width="1792" alt="Screenshot 2023-01-17 at 5 43 30 PM" src="https://user-images.githubusercontent.com/2949921/212864122-17cac362-71b1-4c93-b6f4-033bd8e30c83.png">

### Reproduction

https://qwik.builder.io/

### System Info

```shell
N/A
```

**Comment by hamatoyogi** [comment]
@martuico try clearing your browser's cache. That's what worked for me.
closing as this seems not to reproduce.
