### ISSUE TITLE
[🐞] Code(14): Invoking 'use*()' method outside of invocation context. onGet

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#2658]
### Which component is affected?

Qwik Runtime

### Describe the bug

I want to clean and reuse my code. Consider this data fetching code:
```
export const onGet = async ({ params, url }) => {

    const localeJson = await(await fetch(`${import.meta.env.VITE_API_URL}/locale/data`).response).json()
    const { locale, translations } = localeJson

    const pageJson =  await(await fetch(`${import.meta.env.VITE_API_URL}/page/data?key=home`).response).json()
    const { sections } = pageJson
    const hero = sections.find(i => i.key === 'hero')
    const services = sections.find(i => i.key === 'services')
    const skills = sections.find(i => i.key === 'skills')
    const pageSections = { hero, services, skills }

    const layoutJson = await(await fetch(`${import.meta.env.VITE_API_URL}/layout/data?key=main`).response).json()
    const { sections: layoutSections } = layoutJson
    const branding = layoutSections.find(i => i.key === 'branding')
    const footerLinks = layoutSections.find(i => i.key === 'footerLinks')
    const layoutSections = { branding, footerLinks }

    var totalData = {
        ...localeData,
        ...pageSections,
        ...layoutSections,
    }
    return totalData
}
```

Now I want to clean those fetchings and reuse code across many projects. In Next.js we use Hooks. This is the code we want to be able to do:

```
export const onGet = async ({ params, url }) => {

    const localeData = await useLocale()

    const pageSections = await usePageSections('home')

    const layoutSections = await useLayoutSections('main')

    var totalData = {
        ...localeData,
        ...pageSections,
        ...layoutSections,
    }
    return totalData
}
```

So, `useLocale` and `usePageSection` etc. are our internal hooks. For example this is the code of `usePageSection`:

```
const usePageSections = (key) => {
        const pageJson =  await(await fetch(`${import.meta.env.VITE_API_URL}/page/data?key=${key}`).response).json()
        const { sections } = pageJson
        const result = {}
        for (const section in sections) {
            const { key, ...rest } = sections[section]
            result[key] = rest
        }
        return result
}
```

But now I get this error:

> Code(14): Invoking 'use*()' method outside of invocation context.

### Reproduction

I will provide it, if necessary since it's really easy to understand

### Steps to reproduce

- Extract a method from the complex logic of `onGet`
- Move that method to an external file and create a hook from it
- Reuse that hook inside `onGet`
- You should see `Code(14): Invoking 'use*()' method outside of invocation context.`

### System Info

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 6.81 GB / 15.52 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/partytown: ^0.7.0 => 0.7.3 
    @builder.io/qwik: ^0.16.2 => 0.16.2 
    @builder.io/qwik-city: ^0.0.128 => 0.0.128 
    @builder.io/qwik-react: ^0.2.1 => 0.2.1 
    vite: ^4.0.4 => 4.0.4
```

**Comment by VinSpee** [comment]
is this only because you're using the token `use` in the name, denoting that it's a hook?

**Comment by Nefcanto** [comment]
@VinSpee  then what should I do? It's a hook. I'm OK with renaming it to anything else.

**Comment by VinSpee** [comment]
It looks like (from your example) it's just a function, so you can name it anything which doesn't have `use` as a prefix

**Comment by manucorporat** [comment]
I think it's a runtime error

**Comment by Nefcanto** [comment]
Well, after hours of painful debugging and creating many examples, I realized where is the problem. The problem is **misleading messages**.

This is our `useLocale` for example:

```
import { useLocation } from '@builder.io/qwik-city'
import { getFromCacheOrApi } from 'Base'

const useLocale = async () => {
    const { locale } = useLocation()
    const localeData = await getFromCacheOrApi(`/locale/data?locale=${locale}`)
    return localeData
}

export default useLocale
```

As soon as I comment out the `useLocation` from imports and from the hook body, it works.

But when I uncomment it back, it fails with that message, saying:

> Code(14): Invoking 'use*()' method outside of invocation context.

This means that I should use something for my hook, just the way we use `component$` to define our components which use Qwik's internal stuff.

I don't know what should I use there. But the bigger problem is the *bug communication*. That message is not helpful at all.

Had the message been something like `A custom hook that uses Qwik should be create using qwikHook$` then the debugging time would have been less than a minute. But with the current message, it takes at least days from teams.

**Comment by manucorporat** [comment]
agree with the confusing message, how about:
```
Invoking 'use*()' method outside component$().
'use*()' methods can only be called synchronously within the component$ main function 
```

**Comment by VinSpee** [comment]
> agree with the confusing message, how about:
> 
> ```
> 
> Invoking 'use*()' method outside component$().
> 
> 'use*()' methods can only be called synchronously within the component$ main function 
> 
> ```

@manucorporat does this mean you can't call a hook from within another hook?

**Comment by Nefcanto** [comment]
@manucorporat but that's not a component. I'm not returning JSX. That's a hook (a side effect I guess in the terminology of functional programming). I just return data. By the way, how should I define that `useLocale` hook to be able to use `useLocation` inside it?

**Comment by manucorporat** [comment]
Yes! the can be called inside another hook, but at the root it needs to be a component$()

```
component$
  --> useMyCustomHook()
       --> useDelay()
           --> useStore()
```

Going to try to reflect this better in the error message and docs

**Comment by manucorporat** [comment]
A hook is not a side effect, it's a hook to the component model, use methods does not make sense outside a qwik component, same applies to react. use methods in react can only be called within a react component.

For the requests, the handler includes a `locale` function you can use:

```tsx
export const onRequest = (ev) => {
ev.locale()
```

**Comment by Nefcanto** [comment]
> Yes! the can be called inside another hook, but at the root it needs to be a component$()
> 
> ```
> component$
>   --> useMyCustomHook()
>        --> useDelay()
>            --> useStore()
> ```
> 
> Going to try to reflect this better in the error message and docs

@manucorporat  in my case it was being called from withing a component that used `component$`. Both my `index.jsx` and my `layout.jsx` were using that `component$`. So, this must be another error.

**Comment by Nefcanto** [comment]
> 

Excellent message. Very clear, informative, and truly guiding. Thank you.
