### ISSUE TITLE
[🐞] getLocale always throws an error: Reading `locale` outside of context.

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#2662]
### Which component is affected?

Qwik Runtime

### Describe the bug

Localization doesn't work because `getLocale` always throws an error. It seems that `$locale$` is always empty.

Passing a default locale to getLocale will stop the error but will only ever return the default, it won’t return the actual locale expect by the request

### Reproduction

https://github.com/mhevery/qwik-i18n

### Steps to reproduce

https://github.com/DustinJSilk/qwik-i18n

- Pulling the i18n repository
- Updating the qwik packages in package.json
- Run `npm run dev`

Or call getLocale in a route component in a new project

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 469.59 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.2
    Safari: 15.1
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2 
    @builder.io/qwik-city: 0.1.0-beta9 => 0.1.0-beta9 
    vite: 3.1.7 => 3.1.7
```

**Comment by zanettin** [comment]
Hi @DustinJSilk 
Just started to play around with the translations as well. Here is an example repo with latest qwik pkgs https://github.com/zanettin/qwik-i18n.

I've just touched the `onRequest` logic on `routes/layout.tsx`. The issue i currently have is, that sub-locals like `en-US` are not mapped to my `en` translation file. If i set my browser language to  `fr` or `en` it works as expected.

btw: `?lang` seems to have no affect but `?locoale` does 👍 [code](https://github.com/zanettin/qwik-i18n/blob/main/src/i18n.ts#L68) 

example output for `Accept-Language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7`:
```
22:31:33 [vite] page reload src/i18n.ts (x5)
Loading translations...
en-US
No translation found for "8399228546444251220" ("Counter Example").
No translation found for "8399228546444251220" ("Counter Example").
No translation found for "4608414764123111425" ("count: {$PH}").
No translation found for "2954233255021387859" ("increment").
```

`Accept-Language: fr,en-US;q=0.9,en;q=0.8,de-DE;q=0.7,de;q=0.6` works as expected on my side 👍

**Comment by DustinJSilk** [comment]
Thank you @zanettin!!
I was missing the onRequest handler to set the locale. I thought it happened under the hood.

**Comment by mhevery** [comment]
LOL, I was about to write the same exact thing. you are missing `onRequest` handler in the layout.

You are missing this: https://github.com/mhevery/qwik-i18n/blob/main/src/routes/layout.tsx#L6-L8 without this the system does not know what locale there is.


I have update to the latest here: https://github.com/mhevery/qwik-i18n/commit/a26a8d29781d912d0c34a06bc8911a81b9222a89
