### ISSUE TITLE
[✨] Support a `nonce` argument and add it to Qwiks inlined scripts

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#2663]
### Is your feature request related to a problem?

Qwik adds inline scripts to the html page which is not allowed under strict CSP policies.
The only way to work around this is to add `'unsafe-inline'` to the `script-src` / `style-src` CSP policies.

### Describe the solution you'd like

Qwik server should accept a nonce value that is added to all script/style tags on the initial render.
The node middleware would also need to accept the nonce value and pass it down to the renderer.

Users can then create a nonce value, add it to their CSP policy, and pass it down to Qwik on each request.

### Describe alternatives you've considered

Adding `unsafe-inline` to the CSP policy is a security risk.
We could add a hash of the scripts to the CSP policy, however, the `qwik/json` changes on each page which would then need to be exposed somehow. I dont see how this could feasibly work.

**Comment by manucorporat** [comment]
for reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce

**Comment by manucorporat** [comment]
We can always generate one, that gets passed down?

**Comment by DustinJSilk** [comment]
Could the node router be a function that returns the router middleware. So an `entry.preview.ts` file [similar to this would work](https://gist.github.com/DustinJSilk/6b33af9b4cbe262fe49a6d8bb8b9b424). See line 59

**Comment by DustinJSilk** [comment]
FYI - the nonce would need to be added to the Qwik City env data so that it can be injected into inline script tags in the router-head component

**Comment by solomancode** [comment]
@DustinJSilk @manucorporat 

I'm getting the same issue when I deploy my app to Google Cloud Run
![image](https://github.com/BuilderIO/qwik/assets/7840989/b34394ba-714f-448c-a891-844d35f7be9a)

How to enable 'nonce' setting ?
