### ISSUE TITLE
[🐞] [plugin:vite:import-analysis] Failed to resolve import "@qwik-city-sw-register" from "node_modules/@builder.io/qwik-city/index.qwik.mjs?v=01f6ba50". Does the file exist?

### ISSUE THREAD

**Issue by markshenouda** [BuilderIO/qwik#2669]
### Which component is affected?

Qwik City (routing)

### Describe the bug

We are getting this error while using Qwik in Storybook, it seems that this `@qwik-city-sw-register` isn't a package in the node_modules! This error happens with every component that uses Qwik city in the storybook. Any thoughts?
![image](https://user-images.githubusercontent.com/49324987/213254816-d99b86d5-9508-418b-a7e5-f11cd4fe183e.png)

### Reproduction

https://github.com/thisdot/starter.dev-github-showcases/tree/qwik-fix/storybook

### Steps to reproduce

- Clone the repo https://github.com/thisdot/starter.dev-github-showcases
- Go to the Qwik directory `qwik-graphql-tailwind`
- Run `yarn` to install the packages
- Run `yarn storybook`
- Go to any story that uses Qwik city like `Header` or `Issues Tab View`

![image](https://user-images.githubusercontent.com/49324987/213258617-c9cfaab4-feee-42aa-a61a-f59a2216fd08.png)

Let me know if you wanna a simpler code sandbox to reproduce the problem

### System Info

```shell
MacOS 13, Chrome 109.0.5414.87
```

**Comment by zanettin** [comment]
Hi @markshenouda 
Thanks for creating this issue 🙏 
Have you tried to implement what @DustinJSilk and @literalpie doing over [here](https://github.com/BuilderIO/qwik/pull/2381). At least they had the same issue back in December as mentioned [here](https://github.com/BuilderIO/qwik/pull/2381#issuecomment-1339520040). Maybe you find smth in the diff or by using the plugin 👍

**Comment by literalpie** [comment]
I think the problem is that you are not including the QwikCity Vite plugin in storybook. SB 7.0+ will automatically include config from Vite.config.ts, but you are using SB 6.5.

After adding the QwikCity plugin in that branch, I'm seeing different errors, but I think it fixes the question you are asking about.

**Comment by gioboa** [comment]
Hi @markshenouda, with the latest version of Qwik is it still a valid issue?

**Comment by markshenouda** [comment]
@gioboa it has been solved, thanks 🙌
