### ISSUE TITLE
[🐞] custom slot props not working on production

### ISSUE THREAD

**Issue by O-Hooman** [BuilderIO/qwik#2671]
### Which component is affected?

Qwik Runtime

### Describe the bug

When I tried to make a custom slot by passing it as props it's works on dev but when run preview it doesn't work

Run preview/build:
<img width="489" alt="Screenshot 2023-01-19 at 2 18 49 PM" src="https://user-images.githubusercontent.com/25758563/213382221-043f6224-d787-4151-8cce-8a238528aa57.png">

Run dev: 
<img width="488" alt="Screenshot 2023-01-19 at 2 18 20 PM" src="https://user-images.githubusercontent.com/25758563/213382203-3b1dd90b-43aa-4935-90b3-96ea02490cb0.png">

Notes: it was working before I upgrade to version 0.16.2 (before the upgrade I'm using 0.12.1)

### Reproduction

https://stackblitz.com/edit/qwik-starter-a4rsbf

### Steps to reproduce

npm run preview / npm run build

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 94.38 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2 
    @builder.io/qwik-city: 0.0.128 => 0.0.128 
    undici: 5.14.0 => 5.14.0 
    vite: 4.0.4 => 4.0.4
```

**Comment by manucorporat** [comment]
Looking!

**Comment by O-Hooman** [comment]
> Looking!

Thanks! Let me know if you need more example for reproduction, the current one is just simple one

**Comment by manucorporat** [comment]
Should be working already!
