### ISSUE TITLE
[🐞] Qwik serializes <style> tag string contents, breaking `>` characters

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#2677]
### Which component is affected?

Qwik Runtime

### Describe the bug

```tsx
export default component$(() => {
  const styleProps = `
    div > span {
      color: red;
    }`;

  return (
    <>
      <style>{styleProps}</style>
      <div>
        <span>This text should be red</span>
      </div>
    </>
  );
});
```

The resulting style tag in the browser looks like:

```html
<style>
    div &gt; span {
      color: red;
    }</style>
```

The `>` gets encoded into `&gt;`, causing the styles to break.

### Reproduction

https://qwik.builder.io/playground#version=0.16.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzdHlsZVByb3BzJTIwJTNEJTIwJTYwJTVDbiUyMCUyMCUyMCUyMGRpdiUyMCUzRSUyMHNwYW4lMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29sb3IlM0ElMjByZWQlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTYwJTVDbiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQyUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NzdHlsZSUzRSU3QnN0eWxlUHJvcHMlN0QlM0MlMkZzdHlsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NkaXYlM0UlM0NzcGFuJTNFJTIwSGV5JTIwdGhlcmUlM0MlMkZzcGFuJTNFJTNDJTJGZGl2JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCklM0IlMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTVDbmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFVHV0b3JpYWwlM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlMkMlMjJoaWRkZW4lMjIlM0F0cnVlJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTVDbmltcG9ydCUyMCU3QiUyMHJlbmRlclRvU3RyaW5nJTJDJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiUyQyUyMmhpZGRlbiUyMiUzQXRydWUlN0QlNUQ%3D

### System Info

```shell
latest Qwik version (try in playground)
```

**Comment by mhevery** [comment]
But a prefferd solution is:
```typescript
import { component$, useStyles$ } from '@builder.io/qwik';

export default component$(() => {
  useStyles$(`
    div > span {
      color: red;
    }`)
  return (
    <>
      <div><span> Hey there</span></div>
    </>
  );
});
```

**Comment by manucorporat** [comment]
What @mhevery said! `useStyles$()` will make it even better, since Qwik will only inject ONE style! in the whole document, even if you have 100 instances of the same component.

Thinking we should have a warning to detect this

**Comment by manucorporat** [comment]
Improved the warning in main!
