### ISSUE TITLE
[🐞] singleJsxRoot eslint-rule: false positive for `conditon ? <A /> : <B />` render body

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#2685]
### Which component is affected?

Qwik Runtime

### Describe the bug

```tsx
export const K = component$((props: {x: boolean}) => {
  return props.x ? <div>123</div> : <div>foo</div>
})
```

will trigger the `qwik/single-jsx-root` warning

### Reproduction

[playground link](https://qwik.builder.io/playground#version=0.16.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwSyUyMCUzRCUyMGNvbXBvbmVudCUyNCgocHJvcHMlM0ElMjAlN0J4JTNBJTIwYm9vbGVhbiU3RCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcHJvcHMueCUyMCUzRiUyMCUzQ2RpdiUzRTEyMyUzQyUyRmRpdiUzRSUyMCUzQSUyMCUzQ2RpdiUzRWZvbyUzQyUyRmRpdiUzRSU1Q24lN0QpJTVDbiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAlM0NLJTIweCUzRCU3QmZhbHNlJTdEJTJGJTNFJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE)

### System Info

```shell
n/a
```

**Comment by tuurbo** [comment]
Someone can correct me if I'm wrong, but I'm pretty sure what your writing is equivalent to...
```tsx
export const K = component$((props: { x: boolean }) => {
  if (props.x) {
    return <div>123</div>;
  } else {
    return <div>foo</div>;
  }
});
```
which causes deoptimization in Qwik. 

Try this instead
```tsx
export const K = component$((props: { x: boolean }) => {
  return <>{props.x ? <div>123</div> : <div>foo</div>}</>;
});
```

**Comment by tjclifton** [comment]
Does this mean that the documentation on this page is incorrect for having a conditional return?

https://qwik.builder.io/qwikcity/advanced/routing/#dynamic-404-page

**Comment by zanettin** [comment]
Hi @samijaber , @tuurbo and @tjclifton 👋 

Just saw this issue and wanted to let you know, that Manu removed the mentioned eslint rule and made the rendering of multiple root elements w/o performance drops possible. (PR: https://github.com/BuilderIO/qwik/pull/3034) 🎉 

Hope it's okay for all, if i close this issue now since the rule is gone with the next release 👼
