### ISSUE TITLE
[🐞] Node.insertBefore: Child to insert before is not a child of this node

### ISSUE THREAD

**Issue by cmbartschat** [BuilderIO/qwik#2688]
### Which component is affected?

Qwik Runtime

### Describe the bug

Something weird happens when passing a prop to use as the slot name, where the second time it changes, there's an error.

I was playing around with conditional components along the lines of: https://github.com/BuilderIO/qwik/issues/2678

But came across a weird crash.

**Firefox**
![image](https://user-images.githubusercontent.com/22112134/213844752-2df2d455-e9de-4725-889e-43760be970cf.png)

**Chrome**
![image](https://user-images.githubusercontent.com/22112134/213844199-043c846b-b044-4c36-a333-6d9f0585dc2b.png)

This is not specific to the playground, it also happens on Stackblitz using `npm run preview`.

### Reproduction

[Playground](https://qwik.builder.io/playground#version=0.16.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCdXNlU3RvcmUlMkMlMjBjb21wb25lbnQlMjQlMkMlMjBTbG90JTJDJTIwdXNlQ2xpZW50RWZmZWN0JTI0JTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNyJTVDbiU1Q3IlNUNuZXhwb3J0JTIwY29uc3QlMjBTd2l0Y2glMjAlM0QlMjBjb21wb25lbnQlMjQoKHByb3BzJTNBJTIwJTdCJTIwbmFtZSUzQSUyMHN0cmluZyUyMCU3RCklMjAlM0QlM0UlMjAlN0IlNUNyJTVDbiUyMCUyMHJldHVybiUyMCUzQ1Nsb3QlMjBuYW1lJTNEJTdCcHJvcHMubmFtZSU3RCUyMCUyRiUzRSU1Q3IlNUNuJTdEKSUzQiU1Q3IlNUNuJTVDciU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDciU1Q24lMjAlMjBjb25zdCUyMHN0b3JlJTIwJTNEJTIwdXNlU3RvcmUoJTdCZmxpcCUzQSUyMGZhbHNlJTdEKSU1Q3IlNUNuJTVDciU1Q24lMjAlMjB1c2VDbGllbnRFZmZlY3QlMjQoKGN0eCklMjAlM0QlM0UlMjAlN0IlNUNyJTVDbiUyMCUyMCUyMCUyMGNvbnN0JTIwaW50ZXJ2YWwlMjAlM0QlMjBzZXRJbnRlcnZhbCgoKSUyMCUzRCUzRSUyMCU3QiU1Q3IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwc3RvcmUuZmxpcCUyMCUzRCUyMCFzdG9yZS5mbGlwJTVDciU1Q24lMjAlMjAlMjAlMjAlN0QlMkMlMjAxMDAwKSU1Q3IlNUNuJTIwJTIwJTIwJTIwY3R4LmNsZWFudXAoKCklMjAlM0QlM0UlMjBjbGVhckludGVydmFsKGludGVydmFsKSklNUNyJTVDbiUyMCUyMCU3RCklNUNyJTVDbiU1Q3IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q3IlNUNuJTIwJTIwJTIwJTIwJTNDU3dpdGNoJTIwbmFtZSUzRCU3QnN0b3JlLmZsaXAlMjAlM0YlMjAnYiclMjAlM0ElMjAnYSclN0QlM0UlNUNyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2RpdiUyMHElM0FzbG90JTNEJ2EnJTNFQWxwaGElM0MlMkZkaXYlM0UlNUNyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2RpdiUyMHElM0FzbG90JTNEJ2InJTNFQnJhdm8lM0MlMkZkaXYlM0UlNUNyJTVDbiUyMCUyMCUyMCUyMCUzQyUyRlN3aXRjaCUzRSU1Q3IlNUNuJTIwJTIwKSUzQiU1Q3IlNUNuJTdEKSUzQiU1Q3IlNUNuJTVDciU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQXBwJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NodG1sJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

### Steps to reproduce

- Open the playground
- Open the developer console
- You should see "Alpha" switch to "Bravo", but then instead of switching back, there is an uncaught error logged to the console.

### System Info

```shell
Playground/Firefox/Windows
```

**Comment by Dindaleon** [comment]
A quick solution I found for this is:
```
insertBefore<T extends Node>(node: T, ref: Node | null): T {
    const parent = this.parentElement;
    if (parent) {
      const ref2 = ref ? ref : this.close;
      try {
                parent.insertBefore(node, ref2);
        } catch(_){
                directAppendChild(parent, node)
       }
    } else {
      this.$template$.insertBefore(node, ref);
    }
    return node;
  }
```

For sure, there must be a better solution but it's working for me so far.
