### ISSUE TITLE
[🐞] Cannot use bootstrap css/sass

### ISSUE THREAD

**Issue by axelthat** [BuilderIO/qwik#2690]
### Which component is affected?

Starters / CLI

### Describe the bug

I can't use bootstrap sass. I get the following error,
```
[plugin:vite:css] [sass] Undefined variable.
  ╷
2 │ @each $breakpoint in map-keys($grid-breakpoints) {
  │                               ^^^^^^^^^^^^^^^^^
  ╵
  node_modules/bootstrap/scss/utilities/_api.scss 2:31  root stylesheet
```

### Reproduction

https://github.com/axelthat/qwik-bug

### Steps to reproduce

Run
```
npm install
npm run dev
```

### System Info

```shell
System:
  OS: macOS 13.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 92.16 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.18.0 - /opt/homebrew/opt/node@16/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
Browsers:
  Chrome: 109.0.5414.87
  Firefox: 104.0.2
  Safari: 16.2
npmPackages:
  @builder.io/qwik: 0.16.2 => 0.16.2 
  @builder.io/qwik-city: 0.0.128 => 0.0.128 
  undici: 5.14.0 => 5.14.0 
  vite: 4.0.3 => 4.0.3
```

### Additional Information

The same sass code works on Astro & Vue.

**Comment by zanettin** [comment]
Hi @axelthat 
Thanks for creating this issue 🙏  Looks like your repro repo is private so i can't have a look at it atm. Do you want to adjust that? Thanks

**Comment by axelthat** [comment]
@zanettin So sorry. It should be public now.

**Comment by zanettin** [comment]
Thanks had a look at it. Looks like it happens on the `dev` server "only", right? `npm run preview` looks good on my end and also the very first load of the page after changing smth on the node modules. 

not sure if i can help you with this or smb from the core team can take that over.

**Comment by charl-kruger** [comment]
also ran into this and preview works, might be worth adding it to the docs.

I actually started playing around with tailwind because there was easy integration, but then I dont want to invest in some freemium component lib so back to good old bootstrap

**Comment by bpmccurdy** [comment]
I also ran into this. Following.

**Comment by markuslaubscher** [comment]
I am also trying to get scss to work in Qwik City. I have added postCSS as described by the docs and have installed sass as dev dependency. 

It throws an error in development but compiles correctly during preview. The error occurs when variables are imported from another file. You can declare and use variables if it is inside the same script that references them. And you can import those files into an entry.scss and it works without error.

So it seems that the sass compilation during HMR does not correctly import variables across files.

**Comment by AesthetiCoder** [comment]
it is a problem in the way qwik compile the code of boostrap and sass in dev mode

**Comment by gioboa** [comment]
hi @axelthat
with the latest version of Qwik is it still a valid issue?

**Comment by gioboa** [comment]
I will look at it

**Comment by gioboa** [comment]
@axelthat Thanks for opening this issue, this is a Bootstrap+Vite issue, anyway I decided to solve it.
[This PR](https://github.com/axelthat/qwik-bug/pull/1) solves the problem.
`preview` and `dev` mode are working fine.
So I'm closing this issue, feel free to re-open it if it's still an issue for you.

**Comment by AesthetiCoder** [comment]
Yes this solve the issue thanks a lot

**Comment by JohnPremKumar** [comment]
The above suggested solution make bootstrap work but our custom scss style files no longer working after adding the above. The one which resolved the issue for me is changing the above like below:

```js
css: {
  preprocessorOptions: {
    scss: {
      additionalData: (source, id) => !id.includes("node_modules/bootstrap/scss/") ? source : "";
    },
  },
},```

Hope this helps anyone facing this issue with bootstrap

**Comment by gioboa** [comment]
Thanks @JohnPremKumar 👍
