### ISSUE TITLE
[🐞] ESLint Components in Qwik must have a single JSX

### ISSUE THREAD

**Issue by GregOnNet** [BuilderIO/qwik#2701]
### Which component is affected?

Qwik Runtime

### Describe the bug

Hey there,

I write a component that renders different JSX depending on a value.

When I use ternary operator, to create the respective JSX, ESLint complaints that I might have multiple root elements.

I think this is not correct, since there is only one root-Element.
In other words, each branch of the ternary, defines another root-Element.

## Code 
```ts
export const Header = component$((props: HeaderProps) => {
  const header =
    props.type === 'landing-page' ? (
      <HeaderLandingPage {...props.configuration} />
    ) : props.type === 'content-page' ? (
      <HeaderContentPage {...props.configuration} />
    ) : (
      <div>unknown header type</div>
    );

  return header;
});
```

## ESLint

![image](https://user-images.githubusercontent.com/444278/214048298-615c7fe8-0aad-4dc1-be5a-07049600b7a9.png)

### Reproduction

https://stackblitz.com/edit/qwik-starter-fnnemm?file=src/components/header/header.tsx

### Steps to reproduce

In StackBlitz:
- Open `/components/header/header.tsx` for reference.
- Execute `npm run lint` in the terminal.
- A lint error occurs
  ![image](https://user-images.githubusercontent.com/444278/214050097-a3f12761-5d42-4c6f-8f06-835d39a09dca.png)

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 16.44 GB / 24.98 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.3/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2
    @builder.io/qwik-city: 0.0.128 => 0.0.128
    undici: 5.14.0 => 5.14.0
    vite: 4.0.3 => 4.0.3
```

**Comment by tuurbo** [comment]
See https://github.com/BuilderIO/qwik/issues/2685#issuecomment-1399092053

**Comment by GregOnNet** [comment]
Thanks @tuurbo ,

do you know why deoptimization is caused in Qwik when the wrapping `<></>` is missing?


closing this issue...

**Comment by tuurbo** [comment]
Manu has discussed the reason why on discord but I couldn't find the conversion

**Comment by felixsanz** [comment]
> Manu has discussed the reas

if you're curious: https://discord.com/channels/842438759945601056/1042118392708087989/1042403559842517012
