### ISSUE TITLE
[✨] allow qwik to reference closures and call functions in module level code

### ISSUE THREAD

**Issue by revintec** [BuilderIO/qwik#2704]
### Is your feature request related to a problem?

see `https://qwik.builder.io/tutorial/composing/use/`
`https://github.com/BuilderIO/qwik/blob/4a4f60d2a916b3e9667b72626231f500a4b2d808/packages/docs/src/routes/tutorial/composing/use/solution/app.tsx`

I think that code seems inefficient as it would create multiple stores using `useStore(...)` if multiple components are using the `useMousePosition()`(am I correct?

I've rewritten the code but it seems ugly now, see the following section `Describe the solution you'd like` for more
```
import { useOnDocument, useStore, $ } from '@builder.io/qwik';

let _mousePosition;
export function useMousePosition() {
  if(!_mousePosition){
    console.log(new Date() + " allocating mousePosition")
    _mousePosition = useStore({ x: 0, y: 0 });
  }
  const mousePosition = _mousePosition; // why do I have to capture this...
  useOnDocument(
    'mousemove',
    $((event: Event) => {
      mousePosition.x = (event as MouseEvent).clientX;
      mousePosition.y = (event as MouseEvent).clientY;
    })
  );
  return mousePosition;
}
```

### Describe the solution you'd like

the following code is what I want but won't work
qwik can't reference `mousePosition` but I think it should, it seems just like another level of closure, why ask the user to manually capture it into another name?
```
import { useOnDocument, useStore, $ } from '@builder.io/qwik';

let mousePosition;
export function useMousePosition() {
  if(!mousePosition){
    console.log(new Date() + " allocating mousePosition")
    mousePosition = useStore({ x: 0, y: 0 });
  }
  // const mousePosition = _mousePosition;
  useOnDocument(
    'mousemove',
    $((event: Event) => {
      mousePosition.x = (event as MouseEvent).clientX;
      mousePosition.y = (event as MouseEvent).clientY;
    })
  );
  return mousePosition;
}

```

`Reference to identifier declared at the root 'mousePosition'. It needs to be exported in order to be used inside a Qrl($) scope.`

### Describe alternatives you've considered

the following code is also acceptable, but it won't work neither
I think the code is inferior compared to the one in `Describe the solution you'd like` because it created the store eagerly which is kinda waste of memory(if the feature is not used
can qwik creates a `moduleEvaluationScope` for `getInvokeContext`?
<img width="622" alt="image" src="https://user-images.githubusercontent.com/8952734/214259550-41d84cab-2b4b-4e8a-aab4-fbf3ed99c0a8.png">

```
import { useOnDocument, useStore, $ } from '@builder.io/qwik';

export let mousePosition = useStore({ x: 0, y: 0 });
export function useMousePosition() {
//   if(!mousePosition){
//     console.log(new Date() + " allocating mousePosition")
//     mousePosition = useStore({ x: 0, y: 0 });
//   }
//   const mousePosition = _mousePosition;
  useOnDocument(
    'mousemove',
    $((event: Event) => {
      mousePosition.x = (event as MouseEvent).clientX;
      mousePosition.y = (event as MouseEvent).clientY;
    })
  );
  return mousePosition;
}

```

`Code(14): Invoking 'use*()' method outside of invocation context.`

**Comment by manucorporat** [comment]
State cant be stored in global variables, instead if you want to make sure there is only one mouse state, i would do something like this:

```
export const MouseContext = createContext('mouse-position');
export function useInitMouse() {
  const mousePosition = useStore({ x: 0, y: 0 });
  useOnDocument(
    'mousemove',
    $((event: Event) => {
      mousePosition.x = (event as MouseEvent).clientX;
      mousePosition.y = (event as MouseEvent).clientY;
    })
  );
  useContextProvider(MouseContext, mousePosition);
  return mousePosition;
}
```
and call `useInitMouse()` at the root component: in `root.tsx`

then, in your components you call:
```tsx
export function useMousePosition() {
  return useContext(MouseContext);
}
```


https://qwik.builder.io/docs/components/context/

**Comment by revintec** [comment]
@manucorporat Hi, thanks for the swift and detailed response, great community! but isn't that code verbose?
yes I've read the documentation for `context`, but it seems just like a name aliased global variable?
and in your code, the users would have to make sure
1. the root component, which may or may not be under their control, to have called `useInitMouse()`
2. depends on several different classes and names instead of just one `useMousePosition()`
3. not to mention more concepts and code are involved

no offence but can I know why qwik is refusing to capture the module local variable?
I've seen code generated using `const mousePosition = _mousePosition`, it seems perfect
