### ISSUE TITLE
Cache old vnodes in the host element context

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#271]
## What?

- [ ] Store old vdom tree in the host element context
- [ ] Implement methods to recover the old vdom from HTML
- [ ] Refactor cursor.ts to use the old vnodes instead of DOM nodes
- [ ] Use old vnode / new vnode to implement class and style

## Why?
- Solve host/parent conflict
- Remove dom operations completely from vdom walking, making it easy to execute in a worker
- Solve class/style rendering and conflicts
- Solve property removing problem

**Comment by mhevery** [comment]
Is this still relevant?
