### ISSUE TITLE
[✨] Enhanced Error Overlay [DX]

### ISSUE THREAD

**Issue by zanettin** [BuilderIO/qwik#2710]
### Is your feature request related to a problem?

Enhance the current error overlay to increase DX

### Describe the solution you'd like

Astro v2 just launched a [new error overlay](https://github.com/withastro/astro/pull/5495) which provides additional informationen and a cleaner overview. To implement a custom overlay we would need to "opt-out" of the vite provided web component (`vite-error-overlay`) and create a custom solution.

things we could included if we want to implement this:
- qwikified look and feel (use qwik colors, fonts ,etc)
- show more lines of code in the trace
- highlight the row that contains the error
- reference the docs for certain issues
- "open in editor" link instead of the current file path link

### Describe alternatives you've considered

Keep the existing one and lower the maintenance work 😄

**Comment by manucorporat** [comment]
Imo the error overlay is pretty good, astro 2 is a nice CSS, but the heavy work is in improving the error itself, not the overlay.

Vite overlay can be styled! 
https://github.com/vitejs/vite/pull/10234
PR welcome!

**Comment by zanettin** [comment]
@manucorporat still WIP and guess i'd need more exposures from the vite side, but do you have already some feedback?

# current
![Bildschirmfoto 2023-01-26 um 23 51 37](https://user-images.githubusercontent.com/3241476/214968617-4ccf7be5-aa7b-409c-bef5-cce558e9f6b8.png)


# wip
![Bildschirmfoto 2023-01-26 um 23 50 02](https://user-images.githubusercontent.com/3241476/214968473-5d67ba08-f739-4261-bab9-7c399f0f0d1d.png)

**Comment by zanettin** [comment]
@manucorporat can you maybe point out how i would be able to add the new css on ssr error pages? as far as i can see it is all vite internal. the `errorMiddleware()` gets called which generates the html incl. a script tag which then instanciates the `ErrorOverlay`. I don't see any options to overwrite the middleware or load a "global" css file to apply the style changes. hope you have an idea for that 🙏 

markup received from the server on an ssr error case:
```
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <title>Error</title>
            <script type="module">
              import { ErrorOverlay } from '/@vite/client'
              document.body.appendChild(new ErrorOverlay({"message":"Unexpected token `div`. xxxxxxx"}))
            </script>
          </head>
          <body>
          </body>
        </html>
```
