### ISSUE TITLE
[🐞] Local development is painfully slow on Apple Silicon / M1 Max

### ISSUE THREAD

**Issue by RaeesBhatti** [BuilderIO/qwik#2724]
### Which component is affected?

Qwik Runtime

### Describe the bug

Running any Qwik project via `npm run dev` and browsing the website is extremely slow when not using `<Link>` or refreshing the page. The time-to-first-bye increases with the complexity of the page. The TTFB while in dev mode is > 40 seconds for a website I'm building.
I tried the default "Qwik Docs Starter" website on both my M1 Max and Core i9 Macs, and on the Intel processor with the same NodeJS version (18) had a TTFB of `49ms` vs `731ms` on the M1 Max. That's a ~15x difference in performance.

This make is pretty much impossible to build using Qwik on Apple Silicon because every code change triggers a refresh.

### Reproduction

https://github.com/RaeesBhatti/qwik-ttfb-bug

### Steps to reproduce

- `npm run dev` (on Intel Mac)
- Open the site in a browser
- Open the Network tab in the dev tools
- Refresh and observe the TTFB

Repeat the same on a M1 Mac.

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 926.31 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2 
    @builder.io/qwik-city: 0.0.128 => 0.0.128 
    undici: 5.14.0 => 5.14.0 
    vite: 4.0.3 => 4.0.3
```

**Comment by adam-r-kowalski** [comment]
I've been on a Macbook Air M1 (lowest spec) and have no issues like this. Not sure if that helps or makes it more complicated. I'm wondering if there is something else wrong with your environment?

**Comment by RaeesBhatti** [comment]
Hmm... That's weird. I tried restarting my computer a couple of times and even with no background tasks, the problem remains. Do you see anything in my "System Info" above that might be causing it?

**Comment by adam-r-kowalski** [comment]
Not really, I will say my node version is 19 so you're quite a few behind

**Comment by RaeesBhatti** [comment]
I just tried it with NodeJS v19, and TTFB is still the same. But I just tried to run the "Documentation site" example inside Docker for Mac, which didn't have this problem. The TTFB for requests being served from inside the docker was the expected ~40ms.
So, it's something about the Apple Silicon Rust binaries or some other native module that's causing this issue probably.

**Comment by zanettin** [comment]
Hi @RaeesBhatti 
I am also on an m1/max w/o the mentioned issues. but i am on 12.6 not yet upgraded to 13.x. will give you an update as soon as i upgraded my machine 👍

**Comment by RaeesBhatti** [comment]
Not seeing this issue anymore on Qwik v1.1.0

**Comment by RaeesBhatti** [comment]
I just noticed that the problem still exists on NodeJS v18.13.0. I also tried NodeJS v19.5.0 which also seems to have this problem.
Surprisingly, NodeJS v16.15.1 doesn't have this issue.
And yes, I did do a clean NPM install each time.
