### ISSUE TITLE
[📖] Add anchors for headings

### ISSUE THREAD

**Issue by zanettin** [BuilderIO/qwik#2729]
### Suggestion

All headings should get an anchor and on hover a copy icon to be able to share a specific section of the docs.
examples are:
https://docs.astro.build/en/getting-started/
https://beta.reactjs.org/#how-much-content-is-ready

**Comment by manucorporat** [comment]
we used to have them, something broke along the way!

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/commit/d61174a9b694df3b231f3aba48b5cb421b077185

**Comment by zanettin** [comment]
thanks @manucorporat 🙏 🔥
