### ISSUE TITLE
[🐞] SSG/UseClientEffect$ crash

### ISSUE THREAD

**Issue by felixsanz** [BuilderIO/qwik#2758]
### Which component is affected?

Qwik Runtime

### Describe the bug

Having this component:

```js
import { component$, useClientEffect$ } from '@builder.io/qwik'

export default component$(() => {
  useClientEffect$(() => { console.log('foo') })
  return (<></>)
})
```

and trying to use it inside a markdown file like:

```markdown
import MyComponent from '$components/MyComponent'

<MyComponent />

## Bla bla...
```

When you try to build SSG it crash. It works fine with `npm run dev` and `npm run preview`, but with `npm run build.server` it crash with this non-sense error:

```
QWIK ERROR Error: Code(31)
    at Array.map (<anonymous>) _hW
```

If you remove `useClientEffect$` from the component it builds fine. :/

### Reproduction

See below

### System Info

```shell
"@builder.io/qwik": "0.16.2",
    "@builder.io/qwik-city": "0.1.0-beta6",
```

**Comment by felixsanz** [comment]
Reproducible with this commands:

```
mkdir qwiktest; cd qwiktest

# press enter all the time
npm create qwik@latest 

cd qwik-app

npm install

# install static integration
npm run qwik add

rm -f src/routes/index.tsx

curl -s "https://gist.githubusercontent.com/felixsanz/0d17857c6baa8b6d17388b5e81c5a74f/raw/c6a9887615596d33c458999972a50694ad41d640/index.mdx" > src/routes/index.mdx

mdkir src/components/Example

curl -s "https://gist.githubusercontent.com/felixsanz/0d17857c6baa8b6d17388b5e81c5a74f/raw/c6a9887615596d33c458999972a50694ad41d640/index.tsx" > src/components/Example/index.tsx

mkdir dist

npm run build.server
```

**Comment by dieguezz** [comment]
Happens to me too:

![image](https://user-images.githubusercontent.com/1161455/215495157-17c7803f-f121-4e6f-a04e-2e90fa8262d7.png)

**Comment by felixsanz** [comment]
Wow! I didn't get that `Missing client manifest` error that says `Please ensure the client build has run... blab bla`.

I didn't know there was a `npm run build.client` script and that I had to run it before.

Running it and then running `build.server` script fixes it!

It is normal that i have to run this script manually? Why i'm not getting this error message? 

Also documentation doesn't say anything about this! https://qwik.builder.io/qwikcity/static-site-generation/static-site-config/#changes

**Comment by dieguezz** [comment]
Yes, the error appears here:

![image](https://user-images.githubusercontent.com/1161455/215497660-de14fb5f-583a-4e88-af1e-bbd9bba51173.png)

**Comment by felixsanz** [comment]
Wow! I didn't get that `Missing client manifest` error that says `Please ensure the client build has run... blab bla`.

I didn't know there was a `npm run build.client` script and that I had to run it before.

Running it and then running `build.server` script fixes it!

It is normal that i have to run this script manually? Why i'm not getting this error message? 

Also documentation doesn't say anything about this! https://qwik.builder.io/qwikcity/static-site-generation/static-site-config/#changes

Here is my output:

![1675087295](https://user-images.githubusercontent.com/6182099/215498068-83bd8483-4f39-4210-9530-cbc3f7a303aa.png)

See? No Missing client manifest error

**Comment by felixsanz** [comment]
So, the issue is that i've been running `npm run build.server` manually when I just had to run `npm run build` (which executes `build.client` and `build.server`.

This is not stated on documentation. In fact documentation only talks about the added `build.server` script, which is confusing.
