### ISSUE TITLE
[🐞] `import.meta.env.DEV` doesn't treeshake imports

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#2759]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

`import.meta.env.DEV` will successfully treeshake code, however, it will still leave unused imports.
This will cause an error if those imports arent included in the production dependencies, which means we need to necessarily include dev dependencies.

For example, adding the following to the `entry.ssr.tsx` file will require `dotenv` to be a production dependency

```ts
import { config } from 'dotenv'

if (import.meta.env.DEV) {
  config()
}
```

### Reproduction

.

### Steps to reproduce

Add the following code to the `entry.ssr.ts` file, and run `pnpm build`. You will see the `dotenv` import in the production build file.

```ts
import { config } from 'dotenv'

if (import.meta.env.DEV) {
  config()
}
```

### System Info

```shell
This exists on local machine and a linux CI/CD machine
```

**Comment by gioboa** [comment]
@DustinJSilk I tried with the last Qwik version and I can't reproduce the issue with `npm run build`

**Comment by DustinJSilk** [comment]
This may be fixed as i havent experienced an issue like this in a while.

**Comment by gioboa** [comment]
Thanks for the response @DustinJSilk
