### ISSUE TITLE
[🐞] context using

### ISSUE THREAD

**Issue by SvetlanaMuravlova** [BuilderIO/qwik#2760]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am creating library with demo in one app. I need to update library store from demo component. I tried to implement it with context. I export it with lib elements and i tried to use it with useContext. I tried to import this context in root file and in needed file also (i tried it not at the same time, i tried to resolve it in different ways).  In all ways i got error 
I created a schematic example in repo. In this example useContext is commented, if my way of resolving such task is incorrect i am open for new suggestions

[vite] Internal server error: Code(13): Actual value for useContext() can not be found, make sure some ancestor component has set a value using useContextProvider() 

### Reproduction

https://github.com/SvetlanaMuravlova/mini-example-qwik

### Steps to reproduce

As the best way it need be available to update tabs state from button component 
here https://github.com/SvetlanaMuravlova/mini-example-qwik/blob/master/packages/library-demo/src/components/button-component/index.tsx

### System Info

```shell
"@builder.io/qwik": "0.16.1",
    "@builder.io/qwik-city": "0.0.128",
```

**Comment by shairez** [comment]
thanks for the report @SvetlanaMuravlova !

Can you please create a [stackblitz](https://qwik.new) that reproduces the issue with what are the repro steps
it'll make it easier for us to debug it

Thanks!

**Comment by SvetlanaMuravlova** [comment]
@shairez of course, here you are) I am really interested in your framework and creating library with your framework) thank you) https://stackblitz.com/edit/qwik-starter-3fngeq?file=package.json

**Comment by shairez** [comment]
thanks @SvetlanaMuravlova 

What are the steps to reproduce the error? (I played around with it and couldn't reproduce it)

**Comment by SvetlanaMuravlova** [comment]
@shairez 
i would like to know is there some possibility to update tabs store https://stackblitz.com/edit/qwik-starter-3fngeq?file=package.json,packages%2Flibrary%2Fsrc%2Fcomponents%2Ftabs%2Ftabs.tsx.   from some component of demo app

i tried use context for in root file https://stackblitz.com/edit/qwik-starter-3fngeq?file=package.json,packages%2Flibrary-demo%2Fsrc%2Froot.tsx

and. button component https://stackblitz.com/edit/qwik-starter-3fngeq?file=package.json,packages%2Flibrary-demo%2Fsrc%2Fcomponents%2Fbutton-component%2Findex.tsx

but i get the error  [vite] Internal server error: Code(13): Actual value for useContext() can not be found, make sure some ancestor component has set a value using useContextProvider()


so is it possible or not yet?)
