### ISSUE TITLE
[🐞] Vitest UI says 404 not found

### ISSUE THREAD

**Issue by spdiswal** [BuilderIO/qwik#2764]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When I open the [Vitest UI](https://vitest.dev/guide/ui.html) at http://localhost:51204/__vitest__/, it says '404 not found' in the browser. I suspect that the Qwik City router is shadowing the Vitest UI dev server.

I created the reproduction repository as follows:

1. `npm create qwik@latest`
2. `npm run qwik add vitest`
3. `npm install --save-dev @vitest/ui`
4. `npm install --save-dev vitest@latest`
5. Add the `"test.ui": "vitest --ui"` script to `package.json`.

### Reproduction

https://github.com/spdiswal/qwik-city-vitest-ui

### Steps to reproduce

1. `git clone https://github.com/spdiswal/qwik-city-vitest-ui`
2. `npm install`
3. `npm run test.ui`

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 10.90 GB / 23.11 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2 
    @builder.io/qwik-city: 0.0.128 => 0.0.128 
    undici: 5.14.0 => 5.14.0 
    vite: 4.0.3 => 4.0.3
```

**Comment by manucorporat** [comment]
Should be fixed in main!
