### ISSUE TITLE
[🐞] Date()'s are not serializable in loader$

### ISSUE THREAD

**Issue by ulic75** [BuilderIO/qwik#2766]
### Which component is affected?

Qwik Runtime

### Describe the bug

When using a loader$ as simple as `export const dateLoader = loader$(() => new Date());` in either a layout or index file an error is thrown.
```
[vite] Internal server error: Unable to serialize value.
  File: DEV_SERIALIZE
```
From my understanding Dates should be serializable by Qwik.

### Reproduction

https://stackblitz.com/edit/qwik-starter-df4wqn?file=src/routes/layout.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^0.16.2 => 0.16.2 
    @builder.io/qwik-city: ^0.1.0-beta9 => 0.1.0-beta9 
    undici: ^5.16.0 => 5.16.0 
    vite: ^4.0.4 => 4.0.4
```

**Comment by manucorporat** [comment]
Fixed in latest Qwik City beta!

**Comment by ulic75** [comment]
Unfortunately I still seems to be experiencing the issue with 0.17.2 and beta11.
