### ISSUE TITLE
[🐞] Error when exporting dist and server when building using express adapter.

### ISSUE THREAD

**Issue by H31t0rGamer** [BuilderIO/qwik#2769]
### Which component is affected?

Qwik Runtime

### Describe the bug

When i put dist/ and server/ in another directory and try to run, this happens:

node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-fetch' imported from C:\Users\PC\Desktop\server\entry.express.mjs
←[90m    at new NodeError (node:internal/errors:393:5)←[39m
←[90m    at packageResolve (node:internal/modules/esm/resolve:860:9)←[39m
←[90m    at moduleResolve (node:internal/modules/esm/resolve:909:20)←[39m
←[90m    at defaultResolve (node:internal/modules/esm/resolve:1124:11)←[39m
←[90m    at nextResolve (node:internal/modules/esm/loader:163:28)←[39m
←[90m    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)←[39m
←[90m    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)←[39m
←[90m    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)←[39m
←[90m    at link (node:internal/modules/esm/module_job:75:36)←[39m {
  code: ←[32m'ERR_MODULE_NOT_FOUND'←[39m
}

Node.js v18.12.1

### Reproduction

https://stackblitz.com/edit/qwik-starter?file=README.md

### Steps to reproduce

Open a new qwik app

run npm run qwik add express

run npm build

put dist/ and server/ in another directory

try to run entry.express.js and get the error.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
    Memory: 2.68 GB / 7.92 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.2.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.70)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2
    @builder.io/qwik-city: 0.0.128 => 0.0.128
    undici: 5.14.0 => 5.14.0
    vite: 4.0.3 => 4.0.3
```

### Additional Information

;-;

**Comment by genki** [comment]
Lacking `npm install --production`?

**Comment by gioboa** [comment]
I built the starter with Qwik 1.2.10 and the express adapter.
I moved `dist` and `server` folders, I moved also the required npm packages.
I close this issue because now it works like a charm.
Here is my folder structure
```
➜  test_qwik_express ls -l
- dist
- node_modules
- server
➜  test_qwik_express cd node_modules 
➜  node_modules ls -l
- express -> .pnpm/express@4.18.2/node_modules/express
- undici -> .pnpm/undici@5.22.1/node_modules/undici
```
