### ISSUE TITLE
[✨] Automatic unwrap template binding variables which use `useSignal`

### ISSUE THREAD

**Issue by ahnpnl** [BuilderIO/qwik#2770]
### Is your feature request related to a problem?

It'd be more convenient to have automatic unwrap variables which use `useSignal` just like Vue `ref` when using a reactive variable in JSX template.

### Describe the solution you'd like

Just like Vue where we can use directly `inputRef` in JSX template without explicitly `.value`
```
import { component$, useSignal } from "@builder.io/qwik";

interface MyComponentPropsInterface {
  showInput: boolean;
}

export const MyComponentLite = component$(
  (props: MyComponentPropsInterface) => {
    const inputRef = useSignal<HTMLInputElement>();

    return (
      <div>
        {props.showInput ? <input ref={inputRef} onChange$={() => inputRef.focus()}></input> : null}
        Hello
      </div>
    );
  }
);
```

In this example, `inputRef` is used in JSX template without `.value`, which is the ideal way to go IMO.

See Vue example at https://vuejs.org/guide/essentials/template-refs.html#accessing-the-refs

### Describe alternatives you've considered

I don't have any alternatives.

**Comment by manucorporat** [comment]
I dont understand what it's being proposed in Vue you do this:
```
onMounted(() => {
  input.value.focus()
})
```

**Comment by ahnpnl** [comment]
Hi, I've edited the example codes by adding `onChange$` listener. Would you please take a look? The proposal is developers don't have to do `inputRef.value.focus()` when using the reactive variable in JSX template.

**Comment by manucorporat** [comment]
I am not sure how this proposal could be implemented, the problem is that primitive values cant not be dynamic, a signal is basically a pointer to a value, whenever the pointer changes to a different value the reactivity happens.

I understand that `.value` is a bit extra work, but i am not sure how it could be done otherwise.
