### ISSUE TITLE
[✨] Make Qwik-related package.json script names configurable

### ISSUE THREAD

**Issue by ondratra** [BuilderIO/qwik#2776]
### Is your feature request related to a problem?

Currently, Qwik requires a couple of scripts with fixed names in `package.json` to exist. For example, running `yarn qwik build` (same as `yarn build` in newly generated Qwik project) needs script `build.client` to exist. There are two problems with that.

1) It is unclear what the required script names are without examining the Qwik source code (see https://github.com/BuilderIO/qwik/blob/7d6c810b695e564dc6171bbeba29ecd409cc92dc/packages/qwik/src/cli/build/run-build-command.ts). Because of that, you can't easily delete any script in `package.json` even if you are not actively using them because you can't be sure if they are required or not.

2) There is no way to tide up the `package.json`'s `scripts` section. For example, this is how the `scripts` sections looks like now:
    ```
    "scripts": {
        "build": "qwik build",
        "build.client": "vite build",
        "build.preview": "vite build --ssr src/entry.preview.tsx",
        "build.types": "tsc --incremental --noEmit",
        "dev": "vite --mode ssr",
        "dev.debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
        "preview": "qwik build preview && vite preview --open",
        "start": "vite --open --mode ssr",
        "qwik": "qwik"
        ...
    }
    ```
    But I would like to improve the structure of the commands:
    a) to distinguish Qwik's scripts from my own scripts by prefixing the names with `qwik.`
    ```
    "scripts": {
        "qwik.build": "qwik build",
        "qwik.build.client": "vite build",
        "qwik.build.preview": "vite build --ssr src/entry.preview.tsx",
        "qwik.build.types": "tsc --incremental --noEmit",
        "qwik.dev": "vite --mode ssr",
        "qwik.dev.debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
        "qwik.preview": "qwik build preview && vite preview --open",
        "qwik.start": "vite --open --mode ssr",
        "qwik": "qwik"
        ...
        "do_something_relevant_to_my_project_only": "compile_my_dependencies_or_whatever"
        ...
    }
    ```

    b) couple production, preview, and dev scripts together
    ```
    "scripts": {
        "build": "qwik build",

        "prod.build.client": "vite build",
        "prod.build.types": "tsc --incremental --noEmit",
        "prod.start": "vite --open --mode ssr",

        "preview": "qwik build preview && vite preview --open",
        "preview.build": "vite build --ssr src/entry.preview.tsx",

        "dev": "vite --mode ssr",
        "dev.debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
        ...
    }
    ```
    c) some projects use double colon `:` or underscore `_` as a script name delimiter instead of Qwik's dot `.`
    ```
    "scripts": {
        "build": "qwik build",
        "build:client": "vite build",
        "build:preview": "vite build --ssr src/entry.preview.tsx",
        "build:types": "tsc --incremental --noEmit",
        "dev": "vite --mode ssr",
        "dev:debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
        "preview": "qwik build preview && vite preview --open",
        "start": "vite --open --mode ssr",
        "qwik": "qwik"
        ...
    }
    ```
    Preferably I want to use a combination of a), b), and c).

### Describe the solution you'd like

Don't depend on hardcoded script names. This can be solved by introducing a new config file, `qwik.config.ts`, that could specify the names of essential scripts. It would also bring more clarity for developers by exposing configuration TS types that describe Qwik configuration and scripts it relies on.

Example `qwik.config.ts`:
```
import type { QwikConfig } from '@builder.io/qwik'

export default defineQwikConfig((): Partial<QwikConfig> => {
  essentialScriptNames: {
    'build.client': 'qwik:build:client',
    // ...
  }
})
```

### Describe alternatives you've considered

I don't see any alternative solutions at the moment.

**Comment by gioboa** [comment]
I understand your concern, but honestly nothing prevents you from customising the commands to identify them as related to the framework. In addition I can say that the other frameworks also use a cleaner syntax eg. dev/start to refer to their scripts.
Changing all Qwik-related tutorials, demos, videos, and other resources right now would be a footgun.
