### ISSUE TITLE
[✨] Router Lifecycle Events

### ISSUE THREAD

**Issue by blove** [BuilderIO/qwik#2781]
### Is your feature request related to a problem?

I'd like to be able to add an event listener for router lifecycle events exposed by Qwik City.

My use case is to send pageviews to Fathom analytics for SPA navigation. Next.js provides a solution using the `router.events` module. You can [read their documentation on integrating Fathom with Next.js](https://vercel.com/guides/deploying-nextjs-using-fathom-analytics-with-vercel).

### Describe the solution you'd like

Exposing an API for router lifecycle events would enable developers to implement event listeners for the router events.

```
import { useClientEffect$ } from '@builder.io/qwik';
import { useRouter, NavigationEnd } from '@builder.io/qwik-city';

export default component$(() => {
  const { events } = useRouter();

  function track() {
    Fathom.trackPageview();
  }

  useClientEffect$(() => {
    events.on(NavigationEnd, track);
    return () => events.off(NavigationEnd, track);
  }, { eagerness: 'idle' });
});
```

### Describe alternatives you've considered

Based on reading the documentation thoroughly and asking on Discord it appears that routing events are not currently a public API that is exposed to the developer.

For the use case, a workaround would be to use the Fathom tracking script with Partytown. However, based on my understanding, this would not send page views for client-side SPA navigations.

**Comment by gioboa** [comment]
@blove Qwik changed a lot in this months.
Now you can track the url changes with this code in your main Layout component.
You need to use `useVisibleTask` because with [Link component](https://qwik.builder.io/docs/api/#link) you have a navigation like a SPA so client side.
```
[...]
const location = useLocation();
useVisibleTask$(({ track }) => {
  track(() => location.url.href);
  // here your code, the href is changed
});
[...]
```
