### ISSUE TITLE
[🐞] loader$ yields TS4023: Exported variable has or is using name 'ServerLoader' from external module

### ISSUE THREAD

**Issue by adaliszk** [BuilderIO/qwik#2783]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When using the new `loader$` like:
```typescript
import { loader$ } from '@builder.io/qwik-city'

export const myContent = loader$(() => myData)
```

The exported data loader is yielding a typescript warning:
```
TS4023: Exported variable 'myContent' has or is using name 'ServerLoader' from external module
```

The cure for this is usually straightforward; it just needs the type declared:
```typescript
export const myContent: ServerLoader<MyType> = loader$(() => myData)
```

However, this is impossible because `ServerLoader` is not exported out.

### Reproduction

https://stackblitz.com/edit/qwik-starter-5zm2al?file=src/routes/index.tsx

### Steps to reproduce

To see the error, you need to enable declarations in your tsconfig.

### System Info

```shell
System (WSL):
- OS: Linux 5.15 Alpine Linux
- CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
- Memory: 12.72 GB / 15.57 GB
- Container: Yes
- Shell: 5.9 - /bin/zsh

Binaries:
- Node: 18.12.1 - /usr/bin/node
- Yarn: 3.3.1 - /usr/bin/yarn
- npm: 9.1.2 - /usr/bin/npm
```

### Additional Information

The missing type does not break the build but is reported as an error in Jetbrains and Vscode. A quick solution for this would be to export out the ServerLoader so that it is available to be used as a type.

**Comment by adaliszk** [comment]
For a potential use-case, with the declarations, one could create or potentially generate the `loader$`'s as a client and share it as a package with types pre-compiled to minimise the compilation burden.

**Comment by manucorporat** [comment]
Fixed in latest QwikCity beta!
