### ISSUE TITLE
[🐞]build with 'ssr: { format: 'cjs' }' option, throw error utils.inherits is not a function

### ISSUE THREAD

**Issue by cunzaizhuyi** [BuilderIO/qwik#2784]
### Which component is affected?

Qwik Runtime

### Describe the bug

when you build with 'ssr: { format: 'cjs' }' option, qwik will throw an error of utils.inherits is not a function.  how to solve ? anybody can help?

### Reproduction

https://github.com/cunzaizhuyi/awesome-fe-sites

### System Info

```shell
all
```

**Comment by gioboa** [comment]
I close this issue because in the current version of Qwik I can't set this option anymore.
If you find the issue again please fell free to open a new one.
