### ISSUE TITLE
[🐞] Qwik CLI creates a project with blank pages

### ISSUE THREAD

**Issue by spdiswal** [BuilderIO/qwik#2791]
### Which component is affected?

Starters / CLI

### Describe the bug

The home page (http://localhost:5173) and flower page (http://localhost:5173/flower) in the basic app starter template are blank in Qwik v0.17.0.

It prints a warning in the console as well:
```
$ npm start

> start
> vite --open --mode ssr

  VITE v4.1.0  ready in 588 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
QWIK WARN Duplicate implementations of "JSXNode" found
```

### Reproduction

npm create qwik@latest

### Steps to reproduce

1. `npm create qwik@latest` (v0.17.0)
2. Select the Basic App starter template and install the dependencies.
3. `npm start` or `npm run dev`.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 8.19 GB / 23.11 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.3.1 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
```

**Comment by ElyseGiroux** [comment]
Oh wow, just trying Qwik and my first impression was, well, the basics doesn't even work, but seeing there's already a response here and it's been 25mins make me happy. Guess my timing was just terrible to try it.

**Comment by manucorporat** [comment]
it was a bad timing! it should be fixed already :)

**Comment by kushalmahajan** [comment]
I am coming from the command `npm create qwik@0.16.2` and it doesn't shows anything on the screen for qwik city app.  

Also, I have tried Getting started from the docs and some or the other errors are there. Check my issue opened for the details on that. 

Could you please suggest one solid repo which works as per Frontendmasters workshop conducted by Misko?
