### ISSUE TITLE
[🐞] Cross-site form submission incorrect origin match error

### ISSUE THREAD

**Issue by tuurbo** [BuilderIO/qwik#2797]
### Which component is affected?

Qwik Runtime/city

### Describe the bug

On my local dev environment (eg: https://beta.mysite.loc/) when I submit a form using `action$` I get error "Cross-site POST form submissions are forbidden". If I console log `request.headers.get('origin')` and `url.origin` within the `securityMiddleware` function https://github.com/BuilderIO/qwik/blob/v0.17.2/packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts#L274...
`request.headers.get('origin')` returns the correct https url https://beta.mysite.loc and 
`url.origin` returns incorrect http url http://beta.mysite.loc

Example component
```tsx
import { component$ } from '@builder.io/qwik';
import { action$ } from '@builder.io/qwik-city';

export const signinAction = action$(async () => {
  console.log('this is never called!');
});

export default component$(() => {
  const signIn = signinAction.use();

  return (
    <>
      <form
        action={signIn.actionPath}
        method="POST"
      >
        <label>
          <span>Email</span>
          <input
            name="email"
            type="text"
          />
        </label>

        <label>
          <span>Password</span>
          <input
            name="password"
            type="password"
          />
        </label>

        <button>Login</button>
      </form>
    </>
  );
});
```

![qwik-error](https://user-images.githubusercontent.com/996899/216439877-3ea9dd2a-42bd-4ddb-90fd-a481c69ff168.png)

### Reproduction

I dont think you can replicate on stackblitz but here is a link anyways https://stackblitz.com/edit/qwik-starter-uyvonq?file=src%2Froutes%2Findex.tsx

### System Info

```shell
 System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 12.93 GB / 31.68 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.69)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/partytown: ^0.7.5 => 0.7.5
    @builder.io/qwik: 0.17.2 => 0.17.2
    @builder.io/qwik-city: 0.1.0-beta11 => 0.1.0-beta11
    vite: 4.0.4 => 4.0.4
```

**Comment by DustinJSilk** [comment]
I think this might be the same issue for me - the url provided by my onGet gives me http when i'm running the website in https.

**Comment by manucorporat** [comment]
I need some details, does this happen in express?

**Comment by manucorporat** [comment]
how are you achieving the https connection? do you have a proxy in the middle? there are important details missing here

**Comment by manucorporat** [comment]
```tsx
export function getUrl(req: IncomingMessage) {
  const protocol =
    (req.socket as any).encrypted || (req.connection as any).encrypted ? 'https' : 'http';
  return new URL(req.url || '/', `${protocol}://${req.headers.host}`);
}
```

**Comment by DustinJSilk** [comment]
Hmm i see, that should work! I wonder if GCPs load balancers are giving me the protocol in http, as they're managing my encryption. I'll need to upload a few tests in an hour or 2.
(Hope i havent hijacked the original issue)

Im using a vanilla node server, and the only middleware i have is compression and helmet

**Comment by manucorporat** [comment]
Working on a fix!

**Comment by manucorporat** [comment]
https://github.com/BuilderIO/qwik/pull/2807

**Comment by DustinJSilk** [comment]
That was fast!! Thanks @manucorporat!

**Comment by tuurbo** [comment]
@manucorporat Your merge didn't fix my original issue. 

I can make `yarn preview` work by setting https in vite.config.ts
```ts
export default defineConfig(() => {
  return {
    plugins: [qwikCity(), qwikVite(), tsconfigPaths()],
    preview: {
      headers: {
        'Cache-Control': 'public, max-age=600',
      },
      port: 5173,
      https: {
        key: fs.readFileSync('C:/_work/server/ssl/mysite.key'),
        cert: fs.readFileSync('C:/_work/server/ssl/mysite.crt'),
      },
    },
  };
});
```

I can make express work by using https in entry.express.tsx
```ts
https.createServer({
  key: fs.readFileSync('C:/_work/server/ssl/mysite.key'),
  cert: fs.readFileSync('C:/_work/server/ssl/mysite.crt'),
}, app).listen(PORT, () => {
  console.log(`express server: http://localhost:${PORT}/`);
});
```

but i cant get `yarn dev` to work. I tried this in vite.config.ts
```ts
export default defineConfig(() => {
  return {
    server: {
      port: 5173,
      https: {
        key: fs.readFileSync('C:/_work/server/ssl/mysite.key'),
        cert: fs.readFileSync('C:/_work/server/ssl/mysite.crt'),
      },
    },
    plugins: [qwikCity(), qwikVite(), tsconfigPaths()],
  };
});

```


Do you want me to open a new issue?

**Comment by tuurbo** [comment]
@manucorporat I believe I found the culprit.
https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/buildtime/vite/dev-server.ts#L217
https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/buildtime/vite/dev-server.ts#L52

"http://" is hard coded in the base url. If I remove base url `http://${req.headers.host}`, it works as I expect it too. I'm not if there are any other negative effects from removing it.

**Comment by genki** [comment]
@tuurbo I sent PR #2864 to solve remaining issue.

**Comment by tuurbo** [comment]
fixed as of https://github.com/BuilderIO/qwik/pull/2864
