### ISSUE TITLE
[🐞] Render is not reactive to new keys appearing on stores

### ISSUE THREAD

**Issue by cmbartschat** [BuilderIO/qwik#2800]
### Which component is affected?

Qwik Runtime

### Describe the bug

We expect that accessing a store in render will subscribe the component to that store, so that changes to the store will re-render the component. 

We don't see this when the change to the store is the addition of a new key.

This occurs for both recursive and non-recursive stores.

### Reproduction

[Playground: Recursive store](https://qwik.builder.io/playground#version=0.17.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0b3JlJTIwJTNEJTIwdXNlU3RvcmUlM0MlN0J2YWx1ZXMlM0ElMjBSZWNvcmQlM0NzdHJpbmclMkMlMjBudW1iZXIlM0UlN0QlM0UoJTdCdmFsdWVzJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGFscGhhJTNBJTIwMSUyQyUyMCU1Q24lMjAlMjAlMjAlMjBicmF2byUzQSUyMDIlMkMlMjAlNUNuJTIwJTIwJTIwJTIwY2hhcmxpZSUzQSUyMDMlNUNuJTIwJTIwJTdEJTdEJTJDJTIwJTdCcmVjdXJzaXZlJTNBJTIwdHJ1ZSU3RCklNUNuJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDZGl2JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2J1dHRvbiUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMCU3QnN0b3JlLnZhbHVlcyU1Qk1hdGgucmFuZG9tKCklNUQlMjAlM0QlMjAxJTdEJTdEJTNFQWRkJTIwa2V5JTNDJTJGYnV0dG9uJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2J1dHRvbiUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMCU3QnN0b3JlLnZhbHVlcy5hbHBoYSUyQiUyQiU3RCU3RCUzRUZvcmNlJTIwcmVmcmVzaCUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0N1bCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0JPYmplY3QuZW50cmllcyhzdG9yZS52YWx1ZXMpLm1hcCgoJTVCa2V5JTJDJTIwdmFsdWUlNUQpJTIwJTNEJTNFJTIwJTNDbGklM0UlN0JrZXklN0QlMjAtJTIwJTdCdmFsdWUlN0QlM0MlMkZsaSUzRSklN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGdWwlM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGZGl2JTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEKSU1Q24lNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE)

[Playground: Non-recursive store](https://qwik.builder.io/playground#version=0.17.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0b3JlJTIwJTNEJTIwdXNlU3RvcmUlM0NSZWNvcmQlM0NzdHJpbmclMkMlMjBudW1iZXIlM0UlM0UoJTdCJTVDbiUyMCUyMCUyMCUyMGFscGhhJTNBJTIwMSUyQyUyMCU1Q24lMjAlMjAlMjAlMjBicmF2byUzQSUyMDIlMkMlMjAlNUNuJTIwJTIwJTIwJTIwY2hhcmxpZSUzQSUyMDMlNUNuJTIwJTIwJTdEKSU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NkaXYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYnV0dG9uJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwJTdCc3RvcmUlNUJNYXRoLnJhbmRvbSgpJTVEJTIwJTNEJTIwMSU3RCU3RCUzRUFkZCUyMGtleSUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NidXR0b24lMjBvbkNsaWNrJTI0JTNEJTdCKCklMjAlM0QlM0UlMjAlN0JzdG9yZS5hbHBoYSUyQiUyQiU3RCU3RCUzRUZvcmNlJTIwcmVmcmVzaCUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0N1bCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0JPYmplY3QuZW50cmllcyhzdG9yZSkubWFwKCglNUJrZXklMkMlMjB2YWx1ZSU1RCklMjAlM0QlM0UlMjAlM0NsaSUzRSU3QmtleSU3RCUyMC0lMjAlN0J2YWx1ZSU3RCUzQyUyRmxpJTNFKSU3RCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZ1bCUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZkaXYlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QpJTVDbiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQXBwJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NodG1sJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

### Steps to reproduce

1. Click "Add key"
2. There isn't a re-render
3. Click "Force refresh"
4. There is a re-render, which now shows the new keys.

### System Info

```shell
Playground/Firefox/Windows
```

**Comment by manucorporat** [comment]
This is a bug, and we can easily fix, however:
>We expect that accessing a store in render will subscribe the component to that store, so that changes to the store will re-render the component.

This is not how it works, we subscribe to individual props! when you access the a single prop

**Comment by cmbartschat** [comment]
The non-recursive example I posted is attempting to subscribe to the entire store I'd think.

Actually [here's another playground](https://qwik.builder.io/playground#version=0.17.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0b3JlJTIwJTNEJTIwdXNlU3RvcmUlM0NSZWNvcmQlM0NzdHJpbmclMkMlMjBudW1iZXIlM0UlM0UoJTdCJTVDbiUyMCUyMCUyMCUyMGFscGhhJTNBJTIwMSUyQyUyMCU1Q24lMjAlMjAlMjAlMjBicmF2byUzQSUyMDIlMkMlMjAlNUNuJTIwJTIwJTIwJTIwY2hhcmxpZSUzQSUyMDMlNUNuJTIwJTIwJTdEKSU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NkaXYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYnV0dG9uJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwJTdCc3RvcmUlNUJNYXRoLnJhbmRvbSgpJTVEJTIwJTNEJTIwMSU3RCU3RCUzRUFkZCUyMGtleSUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NidXR0b24lMjBvbkNsaWNrJTI0JTNEJTdCKCklMjAlM0QlM0UlMjAlN0JzdG9yZS5hbHBoYSUyQiUyQiU3RCU3RCUzRUZvcmNlJTIwcmVmcmVzaCUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NwcmUlM0UlM0Njb2RlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3QkpTT04uc3RyaW5naWZ5KHN0b3JlJTJDJTIwbnVsbCUyQyUyMDIpJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmNvZGUlM0UlM0MlMkZwcmUlM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGZGl2JTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEKSU1Q24lNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE) using `JSON.stringify`, is this the same issue?

If accessing the store as a whole, not just single property, is unintended, it'd be best if it was an eslint error at minimum, or a compiler/runtime error.
