### ISSUE TITLE
[🐞] Index route `/` 404s on 0.17.3 when installed with Qwik City

### ISSUE THREAD

**Issue by taylor-smith** [BuilderIO/qwik#2817]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I am following the Qwik "Getting Started" documentation.

I follow the standard installation flow, i.e.

```shell
npm create qwik@latest
...
Select a starter > Basic App (QwikCity)
...
```

and execute `npm run start` after dependencies are installed.

I expect to see the "Welcome to Qwik" screen when viewing `locahost:5173`.

Instead, I see a 404 page.

Repeating the above steps, subbing `npm create qwik@0.17.2` for `...@latest`, results in my expected outcome.

### Reproduction

https://stackblitz.com/edit/qwik-starter-9bdzzv

### Steps to reproduce

Run `npm create qwik@latest`, choosing QwikCity as an installation option, then run `npm run start`.

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.32 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    npm: 8.12.1 - /usr/local/bin/npm
  Browsers:
    Firefox: 108.0.2
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.17.2 => 0.17.2
    @builder.io/qwik-city: 0.0.128 => 0.0.128
    undici: 5.16.0 => 5.16.0
    vite: 4.0.4 => 4.0.4
```

**Comment by hayley** [comment]
I'm seeing 404s too on an old project I'm trying to upgrade from 0.14 to the latest 0.17. I get 404s on every route on 0.17.3 but a different issue (which is likely not relevant to this particular ticket) if I use 0.17.2 instead.

**Comment by timothyhoover** [comment]
Yep, I just attempted to boot up a Qwik project just now and got 404 instead of the welcome page. Interestingly, `npm run build` `npm run start` works.

**Comment by manucorporat** [comment]
Sorry for the bad release! we are supporting two very different versions of QwikCity! please update to `0.17.3`
