### ISSUE TITLE
[🐞] `GetSyncData` has wrong type signature

### ISSUE THREAD

**Issue by zhuhaow** [BuilderIO/qwik#2820]
### Which component is affected?

Qwik City (routing)

### Describe the bug

With type definition

```ts
export declare interface GetSyncData {
    <T>(loader: Loader<T>): T;
    <T>(loader: Action<T>): T | undefined;
}
```

And since a loader could return a `Promise`,

```ts
export const head: DocumentHead = ({getData}) => {
  const data = getData(someLoader); // data would have type Promise<T> instead of T
};
```

The type def should be

```ts
export declare interface GetSyncData {
    <T>(loader: Loader<T>): Awaited<T>;
    <T>(loader: Action<T>): Awaited<T> | undefined;
}
```

### Reproduction

N/A

### System Info

```shell
N/A
```

**Comment by manucorporat** [comment]
The type is correct, is it returning a Promise? it should return the already awaited value

**Comment by zhuhaow** [comment]
It returns the return value of the function we passed in the loader$
function. If that function is async, then the inferred type of the return
value of getData is a promise, while it's actually the awaited value.

**Comment by manucorporat** [comment]
ok! so the way it should work in head is that it should always return the awaited value! internally, we need to await before calling head! gonna add some tests to make sure it's working as expected, but we cant return promise in head cuz head need to resolved syncronously

**Comment by manucorporat** [comment]
ahhhh! i misunderstood completely!

**Comment by manucorporat** [comment]
you are right!

**Comment by manucorporat** [comment]
Should be fixed in the last release!

**Comment by zhuhaow** [comment]
Thank you. Verified. Closing this.
