### ISSUE TITLE
[📖] Adding loader$ to the data fetching for Qwik-City

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#2821]
### Suggestion

Now that Qwik 0.17.x is out, I want to test `loader$`. But I have to run through so many issues to learn how to use it.

I can't find it on the docs related to the Qwik-City. I think it's a good idea that you document the new `loader$` method.

Thank you.

**Comment by shairez** [comment]
Thanks for the suggestion @Nefcanto 


There is a PR opened with the new docs including the ones for server functions
It should get merged soon

**Comment by Nefcanto** [comment]
@shairez awesome. Thank you.
