### ISSUE TITLE
[✨] Middleware support for dev server

### ISSUE THREAD

**Issue by zhuhaow** [BuilderIO/qwik#2822]
### Is your feature request related to a problem?

Currently, when we are building for production, it's quite easy to add our own middleware. 

But it's not possible to do it with the dev server since we can only export a render function. This makes it (almost) impossible to modify the request for things like A/B testing, different layouts for mobile/desktop, etc.

### Describe the solution you'd like

Export a middleware function from `entry.ssr.tsx` so when we do `server.ssrLoadModule` we can pass the request to it before we send it to render function

We can easily plug this middleware function before the adapters for production.

### Describe alternatives you've considered

N/A

**Comment by manucorporat** [comment]
QwikCity has a middleware system, that will work across any deployment. What do you want to do?

**Comment by zhuhaow** [comment]
I thought that's mainly designed for adapting to different platform in
production. Can we use that with the vite dev server? How can we modify the
request in the dev server before it hits router?

**Comment by genki** [comment]
@zhuhaow 
How about to use Vite plugin in front of Qwik's at your `vite.config.ts`?

```ts
export default defineConfig(() => {
  return {
    plugins: [yourPlugins(), qwikCity(), qwikVite(), tsconfigPaths()],
```

You can install middleware at the `configureServer(server)`.

**Comment by zhuhaow** [comment]
Wow, perfect solution! Thank you @genki

**Comment by zhuhaow** [comment]
I did a little investigation, and supporting middleware is harder than I thought. 

The problem is we have two sets of APIs, node API (IncomingMessage, OutgoingMessage, where the object is mutable) and Web API (Request, Response, where the object is immutable). 

The [connect middleware API](https://github.com/senchalabs/connect), which vite is using, is designed for node API. I'm deploying on Cloudflare workers, which will use Web API.

I want to share the middleware code for dev and prod. However, that's impossible without a compatible layer, which is what qwik city is doing (that's why you don't have raw request and response access in the handlers).

I think the problem still needs to be solved within qwik city, so that we can have a way to work with the `RequestEvent` before it hit the router.

**Comment by gioboa** [comment]
This is an old issue and it's a very specific problem for your domain.
If you haven't already found the solution that's right for you, please post your question on the [Discord help chat](https://discord.com/channels/842438759945601056/1046929728948408370) Thanks
