### ISSUE TITLE
[🐞] env arg of loader$ is lacking .env variables at the first time after run dev server

### ISSUE THREAD

**Issue by genki** [BuilderIO/qwik#2834]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When the first access to dev server, `env` of `loader$(({env}) => { ... }` is not filled with values of `.env`.
After the second time the `env` is filled expectedly.

### Reproduction

https://stackblitz.com/edit/qwik-starter-4gsffl?file=src/routes/index.tsx

### Steps to reproduce

I am sorry the reproduction code above is not working because the environment is old then there's no `env` arg.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 63.28 MB / 24.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: file:../clone/qwik/packages/qwik => 0.17.4 
    @builder.io/qwik-city: file:../clone/qwik/packages/qwik-city => 0.1.0-beta13 
    undici: 5.14.0 => 5.14.0 
    vite: 4.0.4 => 4.0.4
```

**Comment by genki** [comment]
Updated description.
`env` is filled with `process.env` but not filled with `.env`
It might that `dotenv` didn't work before the first access to dev-server.

**Comment by genki** [comment]
This could be the reason?
https://github.com/BuilderIO/qwik/blob/14f3256dab95ae8f5ab336826cff28f6995e8225/packages/qwik-city/buildtime/vite/plugin.ts#L111-L114

**Comment by genki** [comment]
The qwikCity plugin is loaded [here](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/config.ts#L448-L450) before the `loadEnv` of Vite.

```ts
  // run config hooks
  const userPlugins = [...prePlugins, ...normalPlugins, ...postPlugins]
  config = await runConfigHook(config, userPlugins, configEnv)  // <- here
...
  // load .env files
  const envDir = config.envDir
    ? normalizePath(path.resolve(resolvedRoot, config.envDir))
    : resolvedRoot
  const userEnv =
    inlineConfig.envFile !== false &&
    loadEnv(mode, envDir, resolveEnvPrefix(config))
```

So the first access to the dev server is not configured with `dotenv` and `dotenv-expand`.
It causes that `process.env` lacks variables in `.env` files.

**Comment by genki** [comment]
I have found a work around. Edit the `vite.config.ts` like this,

```ts
import { defineConfig, loadEnv } from 'vite';                 // <= modified
import { qwikVite } from '@builder.io/qwik/optimizer';             
import { qwikCity } from '@builder.io/qwik-city/vite';                  
import tsconfigPaths from 'vite-tsconfig-paths';                                                      
                                                                        
export default defineConfig(({mode}) => { 
  Object.assign(process.env, loadEnv(mode, process.cwd(), ''));     // added
```

See https://vitejs.dev/config/#using-environment-variables-in-config

The solution I came up with:

1. Change the template of `vite.config.ts` in @create-qwik
2. Do it in the `qwikCity` plugin.

**Comment by manucorporat** [comment]
can anybody prepare a PR that fixes it?

**Comment by genki** [comment]
@manucorporat Yes, I will :)
