### ISSUE TITLE
[🐞] Out of bounds inflalate access

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#2837]
### Which component is affected?

Qwik Runtime

### Describe the bug

```typescript
      <table>
        {items.map((key) => (
          <Row key={key} />
        ))}
      </table>

```

The above generates:
```html
<table>
  <!-- qv ... -->
   <tr>....</tr>
  <!-- qv ... -->
</table>
```

But that is incorrect because `<table>` must have `<tbody>` so the browser does this:

```html
<table>
  <!-- qv ... -->
  <tbody>
    <tr>....</tr>
    <!-- qv ... -->
  </tbody>
</table>
```

the above now breaks the code.

The SSR should warn about this situation but it does not.

### Reproduction

https://stackblitz.com/edit/qwik-starter-q9cak5?file=src%2Froutes%2Findex.tsx

### System Info

```shell
n/a
```

**Comment by manucorporat** [comment]
Fixed!
