### ISSUE TITLE
[🐞] Cookie headers don't set if the page reloaded on dev-server

### ISSUE THREAD

**Issue by genki** [BuilderIO/qwik#2839]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Cookies set in server side such as `loader$` or  `onGet` never set if using dev-server.
Looking into the source code, it seemed that the headers from cookies are ignored from response header generation.

https://github.com/BuilderIO/qwik/blob/14f3256dab95ae8f5ab336826cff28f6995e8225/packages/qwik-city/buildtime/vite/dev-server.ts#L100-L109

I've sent a PR (https://github.com/BuilderIO/qwik/pull/2835) to solve it.

### Reproduction

https://stackblitz.com/edit/qwik-starter-k8umdt?file=src/routes/index.tsx

### Steps to reproduce

Please check above link.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 83.48 MB / 24.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: file:../clone/qwik/packages/qwik => 0.17.4 
    @builder.io/qwik-city: file:../clone/qwik/packages/qwik-city => 0.1.0-beta13 
    undici: 5.14.0 => 5.14.0 
    vite: 4.0.4 => 4.0.4
```

**Comment by genki** [comment]
I have confirmed this issue is happening conditionally.
If a page that is rendered after navigation such as clicking `<Link>` properly set cookie headers,
but the page is reloaded by browser or HMR then the headers never set.
I guess `getWritableStream` in `fromNodeHttp` is not called in the second situation.

**Comment by manucorporat** [comment]
We have e2e tests including the dev server and the cookies are getting set, how can we reproduce exactly?

**Comment by genki** [comment]
I see, the qwik-starter seemed not permit us to access `document.cookie`.
I will made an simple app that reproduces it.

**Comment by genki** [comment]
@manucorporat I've made it :)
https://github.com/genki/qwik-test/tree/cookie-test

This app supposes to use with `qwik-0.17.5-dev20230207033045` installed at `~/project/clone/qwik`.
Please rewrite `package.json` for your env.

My env is:
```
  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 84.09 MB / 24.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: file:~/project/clone/qwik/packages/qwik => 0.17.5 
    @builder.io/qwik-city: file:~/project/clone/qwik/packages/qwik-city => 0.1.0-beta14 
    undici: 5.16.0 => 5.16.0 
    vite: 4.0.4 => 4.0.4 
```

You can reproduce the issue `npm run dev` and open  browser.

**Comment by dmitry-stepanenko** [comment]
+1, facing the same issue

**Comment by adamdbradley** [comment]
This has been fixed in the most recent release, thanks for opening the issue.
