### ISSUE TITLE
[🐞] npm run dev uses dist files!

### ISSUE THREAD

**Issue by felixsanz** [BuilderIO/qwik#2841]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

If you have some files inside `dist`, like CSS files that you have created with previously `npm run build` command, when you run `npm run dev` the `public/` files are ignored and instead it's loading the ones inside `dist/` !

## Browser / curl

![1675695192](https://user-images.githubusercontent.com/6182099/217012685-4694d1a8-0fc5-4322-b417-db871ff6cbad.png)
![1675695362](https://user-images.githubusercontent.com/6182099/217012796-4ee6d6ed-aaaa-4927-b422-8dd7516ca621.png)

## But file is red!

![1675695198](https://user-images.githubusercontent.com/6182099/217012706-4c043da8-3715-4f45-ae6f-a5f548bdedf9.png)

## Once you delete the dist file...

![1675696176](https://user-images.githubusercontent.com/6182099/217012985-a0c96784-2ff7-4c9f-a51d-1f9b8d291dc2.png)

## Now is red!

![1675696170](https://user-images.githubusercontent.com/6182099/217013012-1f1006d9-ae0c-4f13-a132-b408f3cb222a.png)

### Reproduction

No need

### Steps to reproduce

See above

### System Info

```shell
"@builder.io/qwik": "0.16.2",
    "@builder.io/qwik-city": "0.1.0-beta6",
    "vite": "4.0.4",
```

**Comment by manucorporat** [comment]
Dont think this is longer the case!
