### ISSUE TITLE
[✨] Qwik component -> Image

### ISSUE THREAD

**Issue by gioboa** [BuilderIO/qwik#2849]
### Is your feature request related to a problem?

Not really 

### Describe the solution you'd like

The goal is a component to support performant images on the web and automatic image optimization.
That will be built as a pluggable component so devs could connect different image loaders to it (like Cloudinary, or builder)

### Additional context

I would like to work on it 😊

**Comment by shairez** [comment]
thanks @gioboa !

**Comment by thealanreis** [comment]
That would be awesome.

**Comment by gioboa** [comment]
@DustinJSilk have you got a GitHub repo for this?

**Comment by DustinJSilk** [comment]
I’m away this week but I can share where I got to next week

**Comment by manucorporat** [comment]
https://twitter.com/ascorbic/status/1624459615122468864?s=61&t=2B2d4fWKU-9bEm4CR4MzsQ

**Comment by DustinJSilk** [comment]
Amazing! I haven’t given it a try yet but looks like they import all CDN transformers and lookup which one to use based on the URL. That may be a bit limiting for using self hosted CDNs and also includes some bloat when rendering on the client.

I would be keen on writing a more Qwik friendly and flexible component with that as a starting point

**Comment by gioboa** [comment]
Thanks for sharing @manucorporat I will look at it 😸

**Comment by zanettin** [comment]
Just recognized that [here](https://github.com/BuilderIO/qwik/issues/1460) is another issue which covers this topic. can we move the discussions into the older one @gioboa ? 🧹 😄

**Comment by gioboa** [comment]
Yep, sure. There are a lot of good thoughts in the older one

**Comment by zanettin** [comment]
closing in favor of https://github.com/BuilderIO/qwik/issues/1460 🙏
