### ISSUE TITLE
[✨] Make a central folder for build output

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#2855]
### Is your feature request related to a problem?

Currently when we build for production, the files are scattered in differnet folders (`dist`, `server` etc)

### Describe the solution you'd like

Put all build output under 1 folder like `dist` or  `.qwik-output` 

**For example:**

```
dist/ 
|-- static/    <-- this is where the q-manifest.json, static html files and public assets go
|----- build/   <-- this is where the js chunks go 
|-- server/      <-- this is where 
|-- functions/ <-- for example for cloudflare specfic things

```

### Describe alternatives you've considered

manually configuring the plugins

**Comment by shairez** [comment]
@adamdbradley @manucorporat WDYT? 👆

**Comment by manucorporat** [comment]
This is not a easy problem, every platform specs files to be in well defined locations, like dist, server, .netlify, .vercel, not easy to come up with a single way fits all use cases

**Comment by shairez** [comment]
OK thanks, closing for now
