### ISSUE TITLE
[🐞] loader$ can't be used inside 404.tsx

### ISSUE THREAD

**Issue by felixsanz** [BuilderIO/qwik#2865]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When trying to use loaders inside 404.tsx you get `error  loader$() can only be declared in layout.tsx, index.tsx and plugin.tsx inside the src/routes directory`.

### Reproduction

N/A

### System Info

```shell
"@builder.io/qwik": "0.17.4",
"@builder.io/qwik-city": "0.1.0-beta14",
```

**Comment by georgeiliadis91** [comment]
Afaik I can tell this is intentional? I can see that this was implmeneted not long ago by #2777 ?

**Comment by felixsanz** [comment]
intentional why?

**Comment by georgeiliadis91** [comment]
Well, it is documented as such in the docs.  https://qwik.builder.io/qwikcity/loader/

If this is something that the maintainers believe should be added. If it is a low priority issue I would like to attempt to have a go at it over the weekend.

**Comment by felixsanz** [comment]
It's a low priority one, but 404.tsx is a qwik component just as index.tsx, so I don't get why we can't get loaders there, it makes no sense imo.

**Comment by gioboa** [comment]
404 pages are statically generated at build time.
Here is the [404 explanation](https://qwik.builder.io/docs/advanced/routing/#custom-404-page)

Extract from the doc
> It's worth noting that custom 404 pages are statically generated at build time, resulting in a static 404.html file, rather than individually server-side rendered pages. This strategy reduces the load on your HTTP server, avoiding server-side rendering of 404 pages, and thus preserving resources.

Anyway you can declare a routeLoader$ in 404.tsx file and you will get a warning.
Of course this specific routeLoader$ will run during the build time.

**Comment by georgeiliadis91** [comment]
I can actually think of a couple of scenarios where you might want to use a routeLoader on a 404 page. I get the whole static thing, but having the option to do is something that I would expect you are able to do so. 

Even if it is an opt-in type of thing.
