### ISSUE TITLE
[🐞] Light mode code blocks

### ISSUE THREAD

**Issue by jweb89** [BuilderIO/qwik#2871]
### Which component is affected?

Starters / CLI

### Describe the bug

![Screen Shot 2023-02-07 at 9 14 12 PM](https://user-images.githubusercontent.com/62513031/217411253-57d9be56-bc4a-4222-95bf-9dd1ac9094eb.png)

### Reproduction

https://qwik.builder.io/qwikcity/action/

### Steps to reproduce

Use light mode and look at code block in the docs

### System Info

```shell
Mac M1 in Chrome browser
```

**Comment by zanettin** [comment]
Thanks for mentioning @jweb89 🙏 i have it also on dark mode on all browser also on OSX / iOS.

**Comment by vladinator1000** [comment]
Same on firefox

**Comment by zanettin** [comment]
@vladinator1000 @jweb89 : can you please try this URL and tell me if the situation keeps the same on your end pls?
https://qwik.builder.io/qwikcity/api?t=82304505305

@manucorporat : this is what i had on my end before using the cache buster:
![Bildschirmfoto 2023-02-08 um 19 59 25](https://user-images.githubusercontent.com/3241476/217633617-181b2057-93c2-447b-afec-27e4740a5c1d.png)
(left = local docs | right = prod docs)
you see that the correct color was overwritten by a darker blue coming from the same file.

**Comment by jweb89** [comment]
> @vladinator1000 @jweb89 : can you please try this URL and tell me if the situation keeps the same on your end pls? https://qwik.builder.io/qwikcity/api?t=82304505305
> 
> @manucorporat : this is what i had on my end before using the cache buster: ![Bildschirmfoto 2023-02-08 um 19 59 25](https://user-images.githubusercontent.com/3241476/217633617-181b2057-93c2-447b-afec-27e4740a5c1d.png) (left = local docs | right = prod docs) you see that the correct color was overwritten by a darker blue coming from the same file.

That does seem to work now. Although it does seem a little weird that the font size of the code changes when switching from light mode to dark mode

**Comment by manucorporat** [comment]
Should be fixed already! thanks for all the help!
