### ISSUE TITLE
[🐞] useResource$ fails with relative paths -- Failed to parse URL

### ISSUE THREAD

**Issue by n8sabes** [BuilderIO/qwik#2873]
### Which component is affected?

Qwik City (routing)

### Describe the bug

@shairez brought this to my attention.

 After debugging it appears: `useResource$` fails with relative paths -- Please see attached repo.

ERROR: `Failed to parse URL`

WORKS:
1. `useResource$` works with absolute paths
2. initial `<Link>` to relative path

**DOES NOT WORK WITH RELATIVE PATHS:**
1. Reload
2. `window.location` navigation
3. First nav to route from browser

### Reproduction

https://github.com/n8sabes/qwik_broken_route_lab

### Steps to reproduce

~3mins to reproduce with attached [repo](https://github.com/n8sabes/qwik_broken_route_lab).

1. `git clone https://github.com/n8sabes/qwik_broken_route_lab.git`
2. `cd qwik_broken_route_lab`
3. `pnpm i`
4. `pnpm dev`
5. Lunch browser and click red buttons

Could [undici.setGlobalOrigin(origin)](https://github.com/nodejs/undici#undicisetglobaloriginorigin) not be set on initial load?

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 137.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
    npm: 9.2.0 - ~/.nvm/versions/node/v19.4.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox Developer Edition: 110.0
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: github:builderio/qwik-build => 0.17.2
    @builder.io/qwik-city: github:builderio/qwik-city-build => 0.1.0-beta11
    undici: 5.16.0 => 5.16.0
    vite: 4.0.4 => 4.0.4
```

### Additional Information

Cc: @manucorporat

**Comment by n8sabes** [comment]
The local repo is better to reproduce the issue, but provided a StackBlitz for convenience, [HERE](https://stackblitz.com/edit/qwik-starter-fku325?file=README.md).

**Comment by manucorporat** [comment]
I dont think this is solvable, without patching fetch which is not something i want to do.
fetch() will run in the server, if you want to do something different i recommend to use `isServer` from `@builder.io/qwik/build` or use absolute paths.

**Comment by shairez** [comment]
thanks @n8sabes and @manucorporat 

I feel this is a very common pattern that develoeprs are already used to requesting something from `/api/` rather than supplying the entire url every time (and it's confusing when it fails randomly depending on the environment)

So either a lint rule is required to prevent this mistake, or some wrapper that allows devs to configure a baseUrl that will work on the server

@manucorporat can you please elaborate on how `isServer` can help with this issue?

**Comment by manucorporat** [comment]
I dont think fetch() in the server will ever support absolute paths. what is the baseURL running outside the browser?

becuase in isServer developers can resolve their relative paths manually to the absolute path they desire to hit with fetch

**Comment by manucorporat** [comment]
> Could [undici.setGlobalOrigin(origin)](https://github.com/nodejs/undici#undicisetglobaloriginorigin) not be set on initial load?

no, we cant rely on undici, since Node 18, we use the native fetch() built into node, not undici.

**Comment by n8sabes** [comment]
@shairez, I used axios but use `baseurl` from the request in my `onRequest`. But, build the repo for fetch.

@manucorporat, unlike `onRequest` `useResource$` does not provide request context. If the `host` is accessible it can be solved on the server. Between `isServer` and `host` depends up on if `host` can be injected with fetch.

**Comment by manucorporat** [comment]
The problem here is that fetch() is running in a node instance, of deno, or other platforms that are not browser. Fixing this is fixing `fetch()` not a qwikcity issue. Relative paths in a server make little sense, this is not about `useResource`, it's about fetch() implementation in Node, which is outside the scope of qwik.

**Comment by manucorporat** [comment]
Fixing this also means a bit API work, it's not a bug, but a big feature request, like fetch-interception, which requires to monkey-patch fetch

**Comment by n8sabes** [comment]
@manucorporat, Would it be possible to pass `ctx` containing `request` to `useResource$` **ONLY** on the server-side? This would enable SSR logic to provide an absolute path, and just the presence of `ctx` validates it's server-side execution.

**Comment by n8sabes** [comment]
Good point. So you don't have to strip out the `pathname` from `href`, what about including a few other essential / convenience fields, such as `protocol`, `host`, `port`, etc.?

```typescript
url: URL {
    href: 'http://localhost:5173/resourceRelativePath/',
    origin: 'http://localhost:5173',
    protocol: 'http:',
    username: '',
    password: '',
    host: 'localhost:5173',
    hostname: 'localhost',
    port: '5173',
    pathname: '/resourceRelativePath/',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
```

**Comment by shairez** [comment]
@n8sabes you mean adding it to the `routeLocation` object? 

at any case we'll need to probably create a helper function that uses fetch behind the scenes with the route data, maybe it should be done in user land?

**Comment by srapport** [comment]
Yes, it requires a little bit of helper code. Adding these fields makes it possible and easy. Otherwise to @manucorporat’s point, it requires something like SveltKit did / monkey-patch. I am all for an easy solution for developers that reduces work, despite my minimalistic biases.

**Comment by n8sabes** [comment]
@shairez, I created a [Pull Request](https://github.com/BuilderIO/qwik/pull/2924) that adds the missing essential fields to the `RouteLocation` object.

_As a coincidental benefit, the PR enables the above workaround to construct an absolute path._

**Comment by n8sabes** [comment]
@shairez, With PR #2924 now merged, the code below will load data from a relative path within a `useResource$`.

```typescript
  const location = useLocation();

  const todoItems = useResource$(async () => {
    const url = '/mock';

    // Function to make an aboluste path using the location.origin
    const makeAbsolutePath = (path: string) => (path.charAt(0) === "/" && location.url.origin) ? `${location.url.origin}${path}` : path;

    // Load the data using either fetch or axios
    try {
      if (useAxiosSignal.value) {
        //
        // USING AXIOS
        //
        const config: AxiosRequestConfig = {
          method: 'get',
          url,
          headers: {
            "Content-Type": "application/json"
          },
        };
        if (isServer && location.url.origin) config.baseURL = location.url.origin;
        console.log(`config`, config);
        const axiosResult: AxiosResponse<any> = await axios(config);
        return axiosResult.data;
      } else {
        //
        // USING FETCH
        //
        const config: RequestInit = {
          method: 'get',
          headers: {
            "Content-Type": "application/json"
          },
        }
        const _url = isServer ? makeAbsolutePath(url) : url;
        const fetchResult = await fetch(_url, config);
        const items = await fetchResult.json();
        return items;
      }
    } catch (error: any) {
      console.log(`fetch error`, error);
      throw error;
    }
  });
```

Thanks @manucorporat for the help and merging the PR. We should probably keep this Issue open, or create another Issue to create a more robust `fetch` as discussed for post-v1.0. Thoughts?

**Comment by shairez** [comment]
Looks great @n8sabes !

I think we should have a `useFetch` or something alike that hides away the absolute logic and the need to convert to json every time

Maybe it could be done in user land (I could create a prototype of what I'm thinking if you want)

**Comment by n8sabes** [comment]
@shairez, Axios and other libs needs special handling too.

Maybe a more generic helper function in Qwik-city that prepares a `url`. Client-side the helper does nothing, but server-side it applies the origin to resolve relative paths. 🤔

@manucorporat, any thoughts?

**Comment by n8sabes** [comment]
@gioboa -- Following up on your Discord inquiry, I cloned the repo in the OP and verified this is still broken. My confusion was a different PR #2934 I'd posted that's already merged which enables dynamically generating an absolute url, but does not fix the root issue here. Not sure if we want to fix this, or generate documentation how to work around relative urls.

**THIS DOES NOT WORK**
```ts
  const todoItems = useResource$(async () => {
    const todos = await getTodoItems('/mock'); // <------- DOES NOT WORK
    return todos;
  });
```

**THIS DOES WORK**
```ts
  const todoItems = useResource$(async () => {
    const todos = await getTodoItems('http://localhost:5173/mock');
    return todos;
  });
```

**Comment by n8sabes** [comment]
@manucorporat / @mhevery -- Please check out the last few posts in this thread. We left this unresolved with:

1. Monkey Patch like SveltKit
2. `makeAbsoluteUrl` Helper Function
3. Document using How-To w/ the `useLocation()` enhancement provided by #2934.

I'm good with documenting and closing this issue with any of the above.

Thoughts?

**Comment by mhevery** [comment]
I think this should be documented and left as won't solve.

Going down the monkey patch is a whole lot of work, and it will be a constant set of bugs that the patching does not work in some weird case ex.

Creating helper functions needs a lot of documentation and increases the API surface. We should build primitives, not helping functions.

**Comment by gioboa** [comment]
@n8sabes can you create a PR for this please? Thanks in advance ❤️

**Comment by gioboa** [comment]
@n8sabes you rock 💪
