### ISSUE TITLE
[🐞] Pages like rss.xml are not generated in SSG

### ISSUE THREAD

**Issue by felixsanz** [BuilderIO/qwik#2877]
### Which component is affected?

Qwik Runtime

### Describe the bug

Some pages like index.html, the `route` variable (`inside loadStaticRoute()`) outputs this:

```js
[
  /^\/$/,
  [ [Function (anonymous)] ],
  undefined,
  '/',
  [ 'q-ae15263a.js' ]
]
```

but others like rss.xml, sitemap.xml, manifest.webmanifest, etc, outputs this:

```js
[
  /^\/manifest\.webmanifest$/,
  [ [Function (anonymous)] ],
  undefined,
  '/manifest.webmanifest',
  []
]
```

Because the last part, the symbol `q-thing` is empty, the page is not included in SSG.

### Reproduction

https://stackblitz.com/edit/qwik-starter-ufxofd?file=src/routes/manifest.webmanifest/index.tsx

### Steps to reproduce

npm run build

### System Info

```shell
"@builder.io/qwik": "0.17.4",
"@builder.io/qwik-city": "0.1.0-beta14",
```

**Comment by felixsanz** [comment]
This seems to be broken here: https://github.com/BuilderIO/qwik/blob/76d973469025199bd868f4b86b9b0e4306683fbc/packages/qwik-city/static/main-thread.ts#L177-L178

And also looks intended!

**Comment by adamdbradley** [comment]
Yeah good catch, will write up some tests and make sure this works. One thing however, if this endpoint is being used in an ssr edge function like netlify, you'll also have to include the path as a static one. But in you case with SSG agree we should get this fixed up. Thanks for opening the issue and creating a repo case.
