### ISSUE TITLE
Remove `qrlImport` and replace with `qrl.resolve()`

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#289]
# Problem

Currently `qrlImport<T>(element: Element, qrl: QRL<T>): Promise<T>` takes `element`. This is a problem because once we have a `QRL` it is hard to pass it around. There is secondary information which is the `q:base` of the `element` which can affect the behavior of `QRL`. To be safe one has to pass `QRL` and `element` always together to ensure that the `QRL` correctly serializes.

# Goal

We would like to serialize and pass `QRL` around. This means that the `QRL` needs to have all of its state with it. This means that the `QRL` either needs to store `element` or it should eagerly resolve the chunk name so that the `element` is not necessary for the correct resolution of the `QRL`.

Once the `QRL` becomes fully self-contained, it begs the question of why `qrlImport` event exists? Why not just have a method on the `QRL` which does the same thing `await qrl.resolve()` (or similar).

The advantage of this is that now the `QRL` has full context and we can easily pass it around in code and it can be serialized in the application. The developer could write:

```typescript
myFn($(() => {do something})); // <-- this reference can now be serializable

async function myFn(fn: QRL<() => void>) {
  if (something) {
    await fn.resolve()();
    await fn.invoke(); // better API which internally calls `fn.resolve()()`
  }
}
```

## Proposed solution

Store the `chunk` always resolved format. (Fully qualified form).

```typescript
class QRL<TYPE = any> implements IQRL<TYPE> {
  __brand__QRL__!: TYPE;
  canonicalChunk: string;
  constructor(
    public chunk: string, // <<== Make sure that is fully qalified
    public symbol: string,
    public symbolRef: null | ValueOrPromise<TYPE>,
    public symbolFn: null | (() => Promise<Record<string, any>>),
    public capture: null | number[],
    public captureRef: null | any[],
    public guard: null | Map<string, string[]>
  ) {
    this.canonicalChunk = chunk.replace(FIND_EXT, '');
  }
}
```

The second is to add these methods:

```typescrit
class QRL<TYPE = any> implements IQRL<TYPE> {
  resolve(): Promise<TYPE> {...}

  async invoke<ARGS>(..args: ARGS): Promise<ReturnValue<TYPE>> {
    return (await this.resolve)(...args);
  }
}
```

**Comment by manucorporat** [comment]
Fixed!
