### ISSUE TITLE
[🐞] Question: Page back/forward does not refresh the page

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#2897]
### Which component is affected?

Qwik City (routing)

### Describe the bug

The bug was reported and fixed through the issue #2378. _But with release of the beta version of QwikCity 0.1.*, the bug reappeared._

As an example, I have simple counter: when the user increment it, I update the counter and a param in URL to make the state consistent:

```typescript
  const loc = useLocation();
  const nav = useNavigate();

  const state = useStore({ count: loc.params['count'] ? parseInt(loc.params['count']) : 0 });

  const update$ = $(() => {
    state.count++;
    nav(`/${state.count}`);
  });
```

After a few increments, the user hits the back key: _the URL is updated, but the page is not_.

### Reproduction

https://stackblitz.com/edit/qwik-starter-9zkxjo?file=src%2Froutes%2F[...count]%2Findex.tsx

### Steps to reproduce

- In StackBlitz repo, press `Open in New Tab`
- Press `Increment `a few time
- Press page back in the browser

The URL is updated, but not the page

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.17.5 => 0.17.5 
    @builder.io/qwik-city: 0.1.1 => 0.1.1 
    undici: 5.18.0 => 5.18.0 
    vite: 4.1.1 => 4.1.1
```

**Comment by manucorporat** [comment]
Looked into this app, there is no regression here, it works as expected, you are rendering the value of a store

**Comment by manucorporat** [comment]
```
  const state = useStore({ count: loc.params['count'] ? parseInt(loc.params['count']) : 0 });

  const update$ = $(() => {
    state.count++;
    nav(`/${state.count}`);
  });
```

**Comment by robisim74** [comment]
Yes, but after each increment the url is updated: I expect that if the user makes a page back, the value contained in the url is reloaded, and not that the state is maintained (it's a navigation, the page should be re-rendered).

At the moment, I have to do this manually:

```
  useClientEffect$(() => {
    window.onpopstate = (event) => {
      if (event) window.location.reload();
    };
  });
```

You closed #2378 as fixed, and if I remember correctly, I had tested your commit, and it worked...

**Comment by manucorporat** [comment]
The app is working as expected because it's rendering the store, not the param:
https://stackblitz.com/edit/qwik-starter-y5qtet?file=src%2Froutes%2F[...count]%2Findex.tsx
```
export default component$(() => {
  const loc = useLocation();
  const nav = useNavigate();

  const update$ = $(() => {
    const count = parseInt(loc.params['count'] || '0') + 1;
    nav(`/${count}`);
  });

  // Workaround: reload the page on back or forward
  /* useClientEffect$(() => {
    window.onpopstate = (event) => {
      if (event) window.location.reload();
    };
  }); */

  return (
    <div>
      <h1>
        Welcome to Qwik <span class="lightning">⚡️</span>
      </h1>
      <button onClick$={update$}>Increment</button>
      Count: {loc.params.count}
    </div>
  );
});
```
^ this works

**Comment by manucorporat** [comment]
Notice that:
```
useStore(initialValue);
```

**Comment by manucorporat** [comment]
Also, if you need to create a event listener dont do useClientEffect:

use:
```
useOnWindow('popstate', $(() => {
      if (event) window.location.reload();
});
```

**Comment by manucorporat** [comment]
`useClientEffect` is already creating a IntersectionObserver event, that it's being used to listen for another event

**Comment by robisim74** [comment]
In your example, you are transforming the app to work without the store... but in more complex apps it's not so simple: updating the url is important to keep the state consistent (think of the basket of an e-commerce for example, you have to handle user actions such as page back).

This is ok:
```
useOnWindow('popstate', $((event) => {
    if (event) window.location.reload();
  }));
```
but as suggested [here](https://github.com/BuilderIO/qwik/issues/2378#issuecomment-1399174376), I think it should be added in `QwikCityProvider`

**Comment by manucorporat** [comment]
but you are deciding to copy the state into a store, we cant proactively update the state back, it's impossible to know that
if you want to keep the state syncronized, you have to use a useTask

```tsx
useTask$(({track}) => {
  track(() => loc.params);
  store.count = parseInt(loc.params.count, 10);
});
```

**Comment by manucorporat** [comment]
What i mean is that you are creating new state, independant of nav state

**Comment by manucorporat** [comment]
If you are `window.location.reload()` i would recommend to not use a `<Link>` but a simple `<a>`

**Comment by robisim74** [comment]
After some tests, I have to admit that the on `useTask$` solution works well and avoids reloading the page. I understand that in this case it must be done from the app, and not from Qwik City.

Just for professional curiosity, I also added this solution in Qwik Speak sample app for localized router: https://github.com/robisim74/qwik-speak/blob/main/src/components/header/change-locale.tsx#L15

Thanks for your time and advice.

Greetings
