### ISSUE TITLE
Implement Isolate concept to allow multiple Qwik apps to coexist on same page (support lazy loading / routing)

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#290]
# Isolate

The working name for the feature: `Isolate` (Open to discussion)

# Mental Model

- Isolate creates an island where serialization (`<script type="qwik/json">...</script>`) is independent from other Isolates on the page
- When Isolates serialize/deserialize they do so independently from other Isolates 
   - Caveat: In some cases, the parent isolate may be forced to deserialize in order to share object references

# Serialization format

```html
<html>
  <body>
    <button q:obj="myState" on:click="./chunk-a#click[0]">click me!</button>
    <div q:isolate>
      <button q:obj="otherState" on:click="./chunk-b#click[0]">inner click</button>
      <script type="qwik/json">
        {
          "otherState": {...} 
        }
      </script>
    </div>
    <script type="qwik/json">
      {
        "myState": {...} 
      }
    </script>
  </body>
</html>
```

In the above case the `<html>` is implied Isolate, therefore there are two isolates on the page. calling `deserialize(document)` should deserialize both the root isolate as well as the `<div q:isolate>`

# Deserialization

When the user clicks on a `<button>` the corresponding `<script type="qwik/json">...</script>` gets deserialized. 

# Future work

Work which we can add in the future, but is not covered by this proposal

- Sharing objects between isolates
- Having server render isolates separate from the parent isolate
- Having programmatic access to isolates from thee DX experience.

**Comment by manucorporat** [comment]
- [ ] Remove some of the global state in document
- [ ] Connect root with qwik/json state
- [ ] Be able to hydrate multiple times

**Comment by manucorporat** [comment]
Fixed!
