### ISSUE TITLE
[✨] Cookie for client side

### ISSUE THREAD

**Issue by genki** [BuilderIO/qwik#2927]
### Is your feature request related to a problem?

Currently the interface to cookies are provided for server side but not yet for client side.
Of course I can access to the raw cookies via `document.cookie` but it is better if there is the interface same to the server side.

### Describe the solution you'd like

Some thing like this:

```tsx
export default component$(() => {
  const nav = useNavigate();
  const cookie:Cookie = useCookie();
  return (
    <button onClick$={() => {
      cookie.delete("session");
      nav("/");
    }}>
      Sign out
    </button>
  )
}
```

### Describe alternatives you've considered

Copy the code of `parseCookieString()` in `qwik-city/middleware/request-handler/cookie.ts` and store the cookie string manually into the document.

**Comment by mhevery** [comment]
I don't think that Qwik should be in the business of handling cookies on clients. There are existing libraries out there, such as https://github.com/js-cookie/js-cookie

**Comment by genki** [comment]
I agree ;)
