### ISSUE TITLE
[🐞] POSSIBLE BUG `useLocation().params` is missing `decodeURIComponent(...)`

### ISSUE THREAD

**Issue by revintec** [BuilderIO/qwik#2948]
### Which component is affected?

Qwik Runtime

### Describe the bug

route `/[param]/index.tsx`, url `/a%20b/`
`useLocation().params.param` should be `a b` but it's currently `a%20b`

it should be reproducible using the latest qwik version as of writing

### Reproduction

https://stackblitz.com/edit/qwik-starter-5hjrar?file=src/routes/[param]/index.tsx

### System Info

```shell
Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2
    @builder.io/qwik-city: 0.0.128 => 0.0.128
    undici: 5.14.0 => 5.14.0
    vite: 4.0.3 => 4.0.3
```

**Comment by manucorporat** [comment]
willing to give a try to submit a PR? should be easy to pull this one out!
https://github.com/BuilderIO/qwik/blob/d786b860957d53e9232ef5cfdfa972f896b0e8e6/packages/qwik-city/runtime/src/routing.ts#L107

**Comment by revintec** [comment]
@manucorporat Great! count on me, I'll send a PR later

**Comment by revintec** [comment]
@manucorporat Hi, according to `CONTRIBUTION.md` I should add tests, but I don't know where to add them 😢 
and `First-time contributors need a maintainer to approve running workflows.`, please approve, thanks
