### ISSUE TITLE
[🐞] useOnWindow / useOnDocument doesn't work inside layout component

### ISSUE THREAD

**Issue by ItayElgazar** [BuilderIO/qwik#2950]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am trying to use the `useOnDocument` hook inside my Header component, which is inside a layout route, and the callback event doesn't fire. Basically nothing happens.

If I remove it from the layout and put it somewhere else, it works.

### Reproduction

https://stackblitz.com/edit/qwik-starter-j7rm8h?file=src/routes/layout.tsx

### Steps to reproduce

1. Go to the reproduction URL
2. Click anywhere on the screen

Expected:
a console message
Actual:
nothing happens

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^0.16.2 => 0.16.2 
    @builder.io/qwik-city: ^0.1.0-beta9 => 0.1.0-beta9 
    undici: ^5.16.0 => 5.16.0 
    vite: ^4.0.4 => 4.0.4
```

**Comment by genki** [comment]
Currently this is not happened to me (at 0c7f8d7a50dbd74f83f8225aab334c7d67caf91e) but instead a similar issue is happening for the `useBrowserVisibleTask$`.
A JavaScript error is thrown in the qwikloader like this:
```
Uncaught (in promise) TypeError: handler is not a function
    at dispatch (（インデックス）:1093:78)
```

**Comment by rohan-kadkol** [comment]
I don't know if this is related, but when upgrading my `qwik` and `qwik-city` versions and without making any changes in my code, I get a similar error.

```diff
- "@builder.io/qwik": "0.16.2",
- "@builder.io/qwik-city": "0.0.128",
+ "@builder.io/qwik": "0.18.1",
+ "@builder.io/qwik-city": "0.2.1", 
```

![image](https://user-images.githubusercontent.com/45748283/219874695-f3d6c018-0f34-4a8e-a6a1-58ecb23e918e.png)

@ItayElgazar Also, when trying to run the attached StackBlitz link, it worked for me. Clicking anywhere on the document showed the `console.log` message.

![image](https://user-images.githubusercontent.com/45748283/219875030-6b93451f-daaf-4160-87e7-faac034139c1.png)

**Comment by rohan-kadkol** [comment]
@ItayElgazar When trying to run the attached StackBlitz link, it worked for me. Clicking anywhere on the document showed the `console.log` message.

![image](https://user-images.githubusercontent.com/45748283/219875030-6b93451f-daaf-4160-87e7-faac034139c1.png)

**Comment by gioboa** [comment]
Hey @ItayElgazar, thanks for opening this issue, I saw that this feature works Qwik 1.2.10 a lot of things happened during this months. 🚀
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
