### ISSUE TITLE
[✨] Make getData available in RequestHandler and StaticGenerateHandler 

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#2960]
### Is your feature request related to a problem?

Now that we have the awesome loader API, I think it makes sense to have access to loader data in RequestHandlers and StaticGenerateHandlers.

Consider fetching data from a CMS and using that to generate static route paths. RequestHandlers should also have access to getData, if possible, if only for API consistency.

### Describe the solution you'd like

Pass a `getData()` to the handlers like in `DocumentHead`.

### Describe alternatives you've considered

Pouting?

**Comment by manucorporat** [comment]
Technically impossible to have it in RequestHandler as it happens AFTER, unsolvable.
for StaticGenerateHandlers should be easy!

**Comment by manucorporat** [comment]
This is not the right use case for onRequest those handler happen before loaders...
