### ISSUE TITLE
[🐞] Uncaught (in promise) Error: Dynamic require of "/src/_system__component_div_button_onclick_1_klwtplosxd8.js" is not supported

### ISSUE THREAD

**Issue by revintec** [BuilderIO/qwik#2965]
### Which component is affected?

Qwik Runtime

### Describe the bug

the BUG is not 100% reproducible, keep the server running and edit the code then let vite auto refresh the page increases the likelihood of the BUG, I attached the stackblitz link but I can't reliably reproduce it there

`npx envinfo --system --npmPackages '{vite,undici,@builder.io/*}' --binaries --browsers` shows that I should be using the same environment with stackblitz, which also should be the latest version as of writing

![image](https://user-images.githubusercontent.com/8952734/218708619-542c0ff1-182b-4a1e-92be-033686d577e6.png)

the BUG happens when I click the buttons, then the lambda in `onClick$={...}` should be executed,
but before that qwik have to asynchronously load the lambda itself, however it fails to do so as shown in the screenshot

it seems qwik has entered the wrong code path(`getPlatform()` returning the wrong one, see the 2nd last and 3rd last screenshot), on normal execution(the button works), it won't enter `Object.importSymbol(...)`

after the initial error, all later clicks of the same button, as well as other buttons(which may have been working previously), will yield the same error. I'm using Chrome Version 108.0.5359.124 (Official Build) (arm64), the latest version as of writing, and when the error happens, the breakpoint(of uncaught exception, or line break) sometimes won't work, but new error logs are still printed to the console

the last frame is here, line 7, and `require` is undefined
the lambda's code, as seen from the devTools' network panel, is successfully loaded(the last screenshot), maybe qwik fails to store it?

![image](https://user-images.githubusercontent.com/8952734/218714506-84f83a47-8fdc-42ba-ae76-ca5ab6579ba9.png)

![image](https://user-images.githubusercontent.com/8952734/218715130-3e49e471-0e23-4a6d-a5fc-2afcd32c6cc6.png)

![image](https://user-images.githubusercontent.com/8952734/218720064-57eb738b-64ac-4e0e-831b-809ed97d4f89.png)

![image](https://user-images.githubusercontent.com/8952734/218715307-2ef6d1ee-af38-4da1-a57f-1b49fb66b6d8.png)

### Reproduction

https://stackblitz.com/edit/qwik-starter-gf6oqb?file=src/routes/index.tsx

### System Info

```shell
System:
    OS: Linux 4.4 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: (48) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    Memory: 14.66 GB / 251.18 GB
    Container: Yes
    Shell: 5.8.0.2 - .../zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  npmPackages:
    @builder.io/qwik: 0.16.2 => 0.16.2
    @builder.io/qwik-city: 0.0.128 => 0.0.128
    undici: 5.14.0 => 5.14.0
    vite: 4.0.3 => 4.0.3
```

**Comment by manucorporat** [comment]
We have changed a lot how this works in the latest release! Please update to latest qwik and qwik-city! it should be fixed, if not. I will reopen!
