### ISSUE TITLE
[🐞] action$ value only displays after submitting form more than once (dev mode only)

### ISSUE THREAD

**Issue by tuurbo** [BuilderIO/qwik#2986]
### Which component is affected?

Qwik City (routing)

### Describe the bug

The first time you submit a form in dev mode with `<Form />` or `run();`, it doesn't display the value returned by the action$. If you submit the form again (without reloading the page) it will display the value. 

If you submit an action$ with a standard html `<form>`, it works fine.

video: https://www.loom.com/share/8446e6112bfb42e3b50e2e044b167042

I couldn't figure out how to submit forms with stackblitz but I included it for the example code I made.

### Reproduction

https://stackblitz.com/edit/qwik-starter-dvqv72?file=src%2Froutes%2Findex.tsx

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 12.35 GB / 31.68 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/partytown: ^0.7.5 => 0.7.5
    @builder.io/qwik: 0.18.1 => 0.18.1
    @builder.io/qwik-city: 0.2.1 => 0.2.1
    vite: 4.1.1 => 4.1.1
```

**Comment by manucorporat** [comment]
I just tested the repo case, and it works correctly for me, can you double check? make sure you `npm install` and use the latest version of qwik and qwik-city

**Comment by tuurbo** [comment]
I'm unable to reproduce the issue again. Sorry about that!
