### ISSUE TITLE
[🐞] Deprecated useClientEffect$ not working, but useBrowserVisibleTask$ does work

### ISSUE THREAD

**Issue by n8sabes** [BuilderIO/qwik#2988]
### Which component is affected?

Qwik Runtime

### Describe the bug

Deprecated useClientEffect$ not working, but useBrowserVisibleTask$ does work.

Please see loom of issue: [HERE](https://www.loom.com/share/548766301dd64117b657e583a191cb5c)

https://stackblitz.com/edit/qwik-starter-s9qfnw?file=README.md
https://github.com/n8sabes/qwik-useClientEffect-Issue

### Reproduction

https://stackblitz.com/edit/qwik-starter-s9qfnw?file=README.md

### Steps to reproduce

Run the stackBlitz or repo locally.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 90.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
    npm: 9.2.0 - ~/.nvm/versions/node/v19.4.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox Developer Edition: 110.0
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: 0.18.1 => 0.18.1
    @builder.io/qwik-city: 0.2.1 => 0.2.1
    undici: 5.19.1 => 5.19.1
    vite: 4.1.1 => 4.1.1
```

**Comment by devagja** [comment]
Hi, 
you can check this pr to see the reason of the rename -> https://github.com/BuilderIO/qwik/pull/2939

I hope I have been of help, regards
