### ISSUE TITLE
[🐞] Unwanted JS loaded when using Link

### ISSUE THREAD

**Issue by Dindaleon** [BuilderIO/qwik#2998]
### Which component is affected?

Qwik Runtime

### Describe the bug

[Copy paste from discussion]
When using version 0.16.x I could achieve this with no problem; however, now that I am using version 0.18.1 all my pages load with three q-* files for a total of 53.6 kB. I am running my app on localhost with npm run preview

The code I have for my page is:

import { component$ } from '@builder.io/qwik'

```
export default component$(() => {
  return <div>Profile page</div>
})
```

This is a fresh install of version 0.18.1 (added tailwind) so all other files are untouched

EDIT: I just realized that I did change the header to include a Link to the profile page. This is what added the JS. I believe this is not the desired outcome.

By just adding
```
<li>
   <Link></Link>
</li>
```
The loaded JS goes from 0 to 53.6 kB. Is this a known bug?

EDIT 2: Trying out useNavigate instead of Link fixes the issue but it brakes the browser navigation history after reloading the page (if I try to go back, it won't go to the previous visited page).

### Reproduction

https://stackblitz.com/edit/qwik-starter-dnqkxw?file=src/components/header/header.tsx

### Steps to reproduce

Run `npm run preview` 
Go to profile page (/profile)
Reload the page 
Check the network tab.

Three `q-*` files will be loaded instead of 0.

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 248.69 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 110.0.5481.100
    Edge: 110.0.1587.41
    Safari: 16.1
  npmPackages:
    @builder.io/partytown: ^0.7.0 => 0.7.5
    @builder.io/qwik: 0.18.1 => 0.18.1
    @builder.io/qwik-city: 0.2.1 => 0.2.1
    undici: 5.18.0 => 5.18.0
    vite: 4.1.1 => 4.1.1
```

### Additional Information

https://github.com/BuilderIO/qwik/discussions/2996

**Comment by manucorporat** [comment]
Looking!

**Comment by Dindaleon** [comment]
> Looking!

Did you find anything? I can provide more detail if needed.
