### ISSUE TITLE
[🐞] ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by brobles82** [BuilderIO/qwik#3022]
### Which component is affected?

Qwik Runtime

### Describe the bug

Im getting sometimes a never-ending loop on loading a qwik page without any more help related to the error. At some point when the timeout is done this error appears on the console. `ERR_INCOMPLETE_CHUNKED_ENCODING`

I really need to understand what is causing this never-ending loops on qwik pages

### Reproduction

no url

### System Info

```shell
no idea what is triggering this
```

**Comment by manucorporat** [comment]
We cant help without a way for us to reproduce the issue

**Comment by manucorporat** [comment]
Should be fixed!
