### ISSUE TITLE
[📖] Deprecated useClientEffect on Ref section. 

### ISSUE THREAD

**Issue by Aetherovox** [BuilderIO/qwik#3045]
### Suggestion

Deprecated use of useClientEffect$ on the section explaining the handling of refs. Although it seems useBrowserfDisplayEffect is desirable in this situation, I'm new to Qwik and won't be able to edit the docs with any sort of authority.

**Comment by georgeiliadis91** [comment]
Should there be a change also on the LifeCycles section as well?? 
@zanettin 

https://qwik.builder.io/docs/components/overview/#lifecycles

**Comment by georgeiliadis91** [comment]
Also while looking at this the useTask link seems to be broken instead of redirecting you to the specific section it takes you beginning of the lifecycles general section.

**Comment by zanettin** [comment]
good points @georgeiliadis91 🙏 yes all of them should be adjusted 👍 thanks for asking 🙏
