### ISSUE TITLE
[🐞] docs: repl isn't loading anymore

### ISSUE THREAD

**Issue by zanettin** [BuilderIO/qwik#3052]
### Which component is affected?

Qwik Playground

### Describe the bug

Repl stays in an infinite loading state (tutorial and example sections)

### Reproduction

https://qwik.builder.io/tutorial/welcome/overview/

### Steps to reproduce

- open https://qwik.builder.io/tutorial/welcome/overview/ or https://qwik.builder.io/examples/introduction/hello-world/
- check the results section

Console Error:
`~repl-server-host:27          GET https://qwik.builder.io/repl/~repl-server-host.js net::ERR_ABORTED 404`

### System Info

```shell
not relevant
```

**Comment by y471n** [comment]
Can we re-open this? It again stopped working but for some other reason this time. See screenshot:

![Screenshot 2023-03-02 at 17 39 12](https://user-images.githubusercontent.com/2056046/222424781-62de1050-f95d-4a4d-9c7a-4fcf3540245c.png)

**Comment by zanettin** [comment]
Thx @y471n for the ping 🙏 
there is already a new one open in that regard 👍
