### ISSUE TITLE
Component events

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#306]
What is the syntax for components to accept events and to fire these events?

# Browser events

Our current syntax is:

```html
<button on$:click={alert('clicked')}>click me</button>
```

## Component

Following the above syntax it would stand to reason that the syntax for listening for component events would be:

```html
<MyComponent on$:myEvent={() => alert('my component event', useEvent())}/>
```

The question is how does the component fire the event?

Our current proposal is:
```typescript
bubble('myEvent', {payload: 123});
```

The above has many problems mainly:
- Lack of type safety
- Cumbersome syntax for initiating the events. 

The reason for this is that functions were originally not serializable and hence there was no easy way to pass a function to the child component, and hence we have relied on custom events. With the advent of `$` this constraint is no longer has to be true, and so a better syntax would be:

```typescript
const MyComponent((props: {onMyEvent: QRL<(payload: string) => number>}) => {
  return $(() => (
    <button on$:click={() => { const value: number = await props.onMyEvent.invoke('payload') }>
  ));
});
```

the above is fully typesafe and does not require any special syntax for firing the events. 

It does require that QRLs can become fully serializable. See https://github.com/BuilderIO/qwik/issues/289

Because `:` is not a valid property name, the consequence of the above is that the way the event registration would need to happen is as shown:
```html
<MyComponent onMyEvent$={(payload: string): number => payload.length}>
```

## HTML

If registering components is:
```html
<MyComponent onEvent$={...}/>
```
then why is it different for HTML?
```html
<button on:click$={...}/>
```
Should it not be 
```html
<button onClick$={...}/>
```
If that is the case then `document` / `window` would become:
```html
<button onDocumentClick$={...}/>
```

Consider adding both an event and browser event to the host element:
```html
<MyComponent onEvent$={...} h:onDocumentClick$={...}/>
```

# Naming consequences:

As of right now `__$(x)` is same as `__FromQrl($(x))`. But this makes for weird syntax

```typescript
const MyComponent((props: {onMyEventFromQrl: QRL<(payload: string) => number>}) => {
  return $(() => (
    <button on$:click={() => { const value: number = await props.onMyEventFromQrl.invoke('payload') }>
  ));
});
```

So as part of this change I think we should go back to `__$(x)` is same as `__($(x))` so that we can have this syntax:

```typescript
const MyComponent((props: {onMyEvent: QRL<(payload: string) => number>}) => {
  return $(() => (
    <button on$:click={() => { const value: number = await props.onMyEvent.invoke('payload') }>
  ));
});
```

ADDENDUM:
Not sure if `__$(x)` => `__($(x))` is possible from type system. It may be to make the types work we may have to keep it as is. If that is the case than we should from `From` and just have `__$(x)` => `__Qrl($(x))`. The special suffix would allow TypeScript to catch on to something to translate the type.

**Comment by mhevery** [comment]
Type experimentation: https://www.typescriptlang.org/play?#code/C4TwDgpgBA6glsAFgEgDwBUB8UC8UDeAUFCVAPRlQDaACgE4D2kdoUcAdlANYQgMBmUdAF0AXFABGDBgBsIAQ3YBuYqQrV6TCCxBtOPPoPTho8gM5QABgHMIwZPgDC8sAnky4ALwiozwOhzWUABkUJrMoJgAvpZiUAAUAJS42MaQtIwRIMKqJBlaOnrcvAJCUOZWDn4B7EGh4dqgUQA6yLHi6PlZwlAQAB7AEOwAJhYAigBKADKoHPzaQtgA-GUdXY3ZhFGEhByDdPzyAMbQkzPovQNDowkAdPfydNZm4oogVMKJONhv2ESkegAbgwePF7rdHs9xDRHvIALZ2bRmDCYRLiCZ2ACudHYaR8WC2O1AkDCsLhAHl+GM6DJUGNLoMRuNpqhftg8PT+oybmdZux5nRFisLuJ2BBAdoVLt2PtDicwpkLP9SHCQABRCUy8S8+JgeQgGQMeTDUWYuESbTJb5QaqBTAAGlyUHY8Ig4lttUJhCODHYfigYEV0MVuGdmJkMgAhFKfX7gAHFQAmcTwJBocJmdlhiPRnax-19UOBphmRO3VUaob2JRAA

**Comment by manucorporat** [comment]
Fixed!
