### ISSUE TITLE
[🐞] new project creation fails if suggested project name is left blank

### ISSUE THREAD

**Issue by elylucas** [BuilderIO/qwik#3066]
### Which component is affected?

Starters / CLI

### Describe the bug

When running `npm create qwik@latest` to create a new qwik project, if you don't enter a value for the project name and just hit enter, you will get an error saying "Cannot read properties of undefined (reading 'trim')". The CLI presents "./qwik-app" as a placeholder, making the user feel like this is the default value, when if left blank the value becomes undefined as it goes through the rest of the CLI flow.

### Reproduction

none - cli issue

### Steps to reproduce

Run `npm create qwik@latest`
leave project name blank
see the error

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 228.90 MB / 32.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Chrome Canary: 112.0.5609.0
    Firefox: 106.0.3
    Safari: 16.0
  npmPackages:
    @builder.io/qwik: 0.19.0 => 0.19.0
    @builder.io/qwik-city: 0.3.0 => 0.3.0
    undici: 5.20.0 => 5.20.0
    vite: 4.1.2 => 4.1.2
```

### Additional Information

This looks like a relatively easy fix and I'll submit a PR for it shortly for review.

**Comment by zanettin** [comment]
Hi @elylucas 👋 
Thanks for mentioning this 🙏  i'll take care of it

**Comment by elylucas** [comment]
> Hi @elylucas 👋 Thanks for mentioning this 🙏 i'll take care of it

@zanettin ahh, i just opened a PR before seeing this. Feel free to use or close: https://github.com/BuilderIO/qwik/pull/3067
