### ISSUE TITLE
[✨] Synchronous onClick events

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#3081]
### Is your feature request related to a problem?

Currently, iOS does not allow JavaScript to `focus()` on an input element after an asynchronous function.
The only way to focus on an input is **synchronously after a click event.**

Using Qwiks `onClick$` event first fetches the QRL, making it impossible to focus on an input on iOS.

### Describe the solution you'd like

Could something like this register a native, synchronous click event?

`<button q:onclick={() => ref.value.focus() }>Focus on input<button>`

### Describe alternatives you've considered

Ive tried every hack possible, nothing can make this work.

**Comment by wmertens** [comment]
This is now supported using `sync$()` functions https://qwik.builder.io/docs/cookbook/sync-events/#sync-synchronous-events-beta
