### ISSUE TITLE
[🐞] Link component not working in the layouts

### ISSUE THREAD

**Issue by ndungtse** [BuilderIO/qwik#3102]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to put link to navigate back to home by passing link component to the layout as it will be the same for whole app but I'm getting this error.

`
Code(27): Missing Object ID for captured object
    at createError (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:68:17)
    at logError (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:62:54)
    at logErrorAndStop (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:72:17)
    at qError (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:135:12)
    at mustGetObjId (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:4112:19)
    at Array.map (<anonymous>)
    at serializeQRL (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:516:40)
    at Object.serialize (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:6118:16)
    at serializeValue (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:6279:28)
    at file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:4195:23
    at Array.map (<anonymous>)
    at _pauseFromContexts (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:4178:32)
    at beforeClose (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/server.mjs:658:30)
    at file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:7968:28
    at file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:8405:25
    at async renderRoot (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:7966:5)
    at async _renderSSR (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/core.mjs:7962:5)
    at async Proxy.renderToStream (file:///D:/Coding/Frameworks/qwik/newTube/node_modules/@builder.io/qwik/server.mjs:647:3)
    at async D:\Coding\Frameworks\qwik\newTube\node_modules\@builder.io\qwik\optimizer.cjs:1840:28
`

My layout looks like this

```javascript
import { component$, Slot } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import Header from "../components/header/header";
import { useApp } from "../contexts/AppProvider";

export default component$(() => {
  const { isDark } = useApp();

  return (
    <>
      <main
        class={`flex flex-col w-full ${
          isDark ? " bg-darkb text-white" : "bg-trueWhite"
        } h-screen overflow-hidden`}
      >
        <Link href="/">
          Home
        </Link>
        <Header />
        <section class={`flex flex-col w-full h-full px-2 overflow-y-auto`}>
          <Slot />
        </section>
      </main>
    </>
  );
});
```

### Reproduction

https://github.com/NdungutseCharles103/newTube

### Steps to reproduce

Clone the repo, run `yarn install` and then run `yarn run start`

### System Info

```shell
 System:
    OS: Windows 10 10.0.22623
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 6.36 GB / 15.73 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1325.0), Chromium (110.0.1587.50)
    Internet Explorer: 11.0.22621.1
```

**Comment by manucorporat** [comment]
can you please run:
```
npx envinfo --system --npmPackages '{vite,undici,@builder.io/*}' --binaries --browsers
``` and report the system info?

**Comment by NdungutseCharles103** [comment]
It looks like the link in the layout might not be only the problem but also in the my app provider while trying to fetch data to be used by whole application is causing this problem. I don't if it is because I'm using the same logic as I used to in react. 
here is my app provider

``` javascript
import {
  component$,
  createContextId,
  Slot,
  useContext,
  useContextProvider,
  useStore,
  useTask$,
} from "@builder.io/qwik";
import { isServer } from "@builder.io/qwik/build";
import { fetcRelatedVideos } from "~/utils/fetch";
import type { IPlayerState, VideoResponse } from "~/utils/types";

interface AppStore {
  isDark: boolean;
  playerState: IPlayerState;
  videos: VideoResponse["contents"];
}

export const AppContext = createContextId<AppStore>("App");

export const useApp = () => useContext(AppContext);

export const AppProvider = component$(() => {
  const appState = useStore<AppStore>({
    isDark: false,
    playerState: {
      progress: 0,
      isFullScreen: false,
      isMuted: false,
      isPicInPic: false,
      isPlaying: false,
      volume: 1,
      loop: "false",
      speed: 1,
      shuffle: false,
    },
    videos: [],
  });
  
  useTask$(async () => {
    if (isServer) {
      const data: VideoResponse = (await fetcRelatedVideos(
        "kJQP7kiw5Fk"
      )) as VideoResponse;
      appState.videos = data?.contents;
    }
  });

  // useBrowserVisibleTask$(() => {
  //   const sysTheme =
  //     window.matchMedia &&
  //     window.matchMedia("(prefers-color-scheme: dark)").matches;
  //   if (sysTheme) {
  //     // console.log("dark mode", appState);
  //     // appState.isDark = true;
  //   }
  // });

  useContextProvider(AppContext, appState);
  return (
    <div class="provider">
      <Slot />
    </div>
  );
});
```
the link to repo
https://github.com/NdungutseCharles103/newTube/blob/main/src/contexts/AppProvider.tsx

**Comment by manucorporat** [comment]
Can you test with latest?
 0.19.2 and 0.4.0?

can you run `npx envinfo --system --npmPackages '{vite,undici,@builder.io/*}' --binaries --browsers` in the project directory? the info does not include anything about deps

**Comment by NdungutseCharles103** [comment]
I upgraded qiwk and qwik-city but still giving me that vite error
my system info and  dependences
`
System:
    OS: Windows 10 10.0.22623
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 4.93 GB / 15.73 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1325.0), Chromium (110.0.1587.56)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: 0.19.2 => 0.19.2
    @builder.io/qwik-city: 0.4.0 => 0.4.0
    @builder.io/qwik-react: 0.3.0 => 0.3.0
    @emotion/react: 11.10.6 => 11.10.6
    @emotion/styled: 11.10.6 => 11.10.6
    @mui/material: 5.11.9 => 5.11.9
    @mui/x-data-grid: 5.17.24 => 5.17.24
    @types/eslint: 8.21.1 => 8.21.1
    @types/node: ^18.14.0 => 18.14.1
    @types/node-fetch: latest => 2.6.2
    @types/react: 18.0.28 => 18.0.28
    @types/react-dom: 18.0.11 => 18.0.11
    @typescript-eslint/eslint-plugin: 5.52.0 => 5.52.0
    @typescript-eslint/parser: 5.52.0 => 5.52.0
    autoprefixer: ^10.4.13 => 10.4.13
    axios: ^1.3.3 => 1.3.4
    eslint: 8.34.0 => 8.34.0
    eslint-plugin-qwik: 0.19.2 => 0.19.2
    node-fetch: 3.3.0 => 3.3.0
    postcss: ^8.4.16 => 8.4.21
    prettier: 2.8.4 => 2.8.4
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-icons: ^4.7.1 => 4.7.1
    tailwindcss: ^3.1.8 => 3.2.7
    typescript: 4.9.5 => 4.9.5
    undici: 5.20.0 => 5.20.0
    vercel: ^28.4.17 => 28.16.7
    vite: 4.1.2 => 4.1.2
    vite-tsconfig-paths: 3.5.0 => 3.5.0
`

**Comment by NdungutseCharles103** [comment]
Commenting useTask in AppProvider and removing Link in the layout>Header seems fix the problem but I want them to be there as I want to share state and component to the entire application

**Comment by gioboa** [comment]
Hi @NdungutseCharles103, with the latest version of Qwik is it still a valid issue?

**Comment by NdungutseCharles103** [comment]
> Hi @NdungutseCharles103, with the latest version of Qwik is it still a valid issue?

I haven't checked yet. I'll try the latest version and update you

**Comment by gioboa** [comment]
Hey @ndungtse, thanks for opening this issue, I saw that this works with the latest version of Qwik 1.3.1, btw a lot of things happened during this months. 🚀
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
