### ISSUE TITLE
[🐞] App doesn't work after upgrading to 0.19.0

### ISSUE THREAD

**Issue by saeedhbi** [BuilderIO/qwik#3104]
### Which component is affected?

Qwik Runtime

### Describe the bug

I developed my app until 0.16.1 and didn't have any problems. But, after upgrading to 0.19.0, I can't run app in production mode and this is what I have:

`file://www-app/src/server/index.qwik-2c3104a0.mjs:1512
}, ar = (e) => rr(e), jt = as(/* @__PURE__ */ o(ar, "s_NEDgV3rXVRc")), lr = (e) => {`
                           ^

`ReferenceError: Cannot access 'as' before initialization
    at file://www-app/src/server/index.qwik-2c3104a0.mjs:1512:28
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
`

And the `as` refers to `loader$` method. Before upgrading, I was using `useEndpoint` but now, since it's removed, I have to use `loader$` instead of it. I should return JSON data so I can't use endpoints since they work with responses.

First of all, since `useEndpoint` was a central concept in previous versions, I couldn't find related references and documentation to move on!

But, I reviewed the documentation and there is no concern. Because the `loader$` method is on `layouts` file.

By the way, since I can not reproduce this problem in the pure installation version, I can't understand what is the problem.

### Reproduction

https://stackblitz.com/edit/qwik-starter-mt6b85?file=src/routes/layout.tsx

### System Info

```shell
System:
    OS: Linux 5.13 elementary OS 6.1 Jólnir
    CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
    Memory: 831.14 MB / 15.52 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Brave Browser: 100.1.37.113
    Chrome: 110.0.5481.100
  npmPackages:
    @builder.io/partytown: ^0.7.5 => 0.7.5 
    @builder.io/qwik: 0.19.0 => 0.19.0 
    @builder.io/qwik-city: 0.3.0 => 0.3.0 
    undici: ^5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

**Comment by manucorporat** [comment]
I cant reproduce any issues in the stackblitz you submitted!

**Comment by saeedhbi** [comment]
> I cant reproduce any issues in the stackblitz you submitted!

Yes. As I mentioned in my description, I can't reproduce it in a pure version. But, I'm stuck now in my app and can't detect the problem.

**Comment by manucorporat** [comment]
Gotcha! let me know if you got some piece of code that reproduces it and i am happy to look into it!
just to make sure! I released a new version just now
```
"@builder.io/qwik": "0.19.1",
"@builder.io/qwik-city": "0.4.0",
```
maybe worth give it a try!

**Comment by saeedhbi** [comment]
> Gotcha! let me know if you got some piece of code that reproduces it and i am happy to look into it! just to make sure! I released a new version just now
> 
> ```
> "@builder.io/qwik": "0.19.1",
> "@builder.io/qwik-city": "0.4.0",
> ```
> 
> maybe worth give it a try!

Unfortunately, it's there again!

**Comment by saeedhbi** [comment]
**UPDATE:**

I'm using `qwik-speak` as translating service and it seems the problem in the dev environment is for fetching translating files. They are in the public directory but the express can not serve them.

`{
  url: 'http://localhost:5173/i18n/en/runtime.json/',
  headers: {
    accept: '*/*',
    'accept-encoding': 'gzip, deflate',
    'accept-language': '*',
    connection: 'keep-alive',
    host: 'localhost:5173',
    'sec-fetch-mode': 'cors',
    'user-agent': 'undici'
  }
}
`

@manucorporat Is there anything that I should follow? I didn't change vite configs.

**Comment by manucorporat** [comment]
I cant help much without a repo case, try creating a repo or a stackblitz: https://stackblitz.com/edit/qwik-starter
and I will make sure it ends up solved!
Without a full repo i cant know what is happening

**Comment by saeedhbi** [comment]
I will recreate the whole from scratch to find out the problem.
