### ISSUE TITLE
[🐞] DOM Manipulation / Editing by Drag and Drop are crashing reactivity

### ISSUE THREAD

**Issue by Alx90s** [BuilderIO/qwik#3112]
### Which component is affected?

Qwik Runtime

### Describe the bug

Hey there, I know the issue. A little bit. I have a drag and drop which is built by a useStore. 
When I add a item to the drag and drop, the useBrowserVisibleTask is processing some dom "manipulation" do some changes on some html element to reorder the drag and drop. 

Created a repo here: https://github.com/Alx90s/ambitive-qwik-reactivity-bug

QwikJS Version:
"@builder.io/qwik": "0.19.1",
"@builder.io/qwik-city": "0.4.0",

### Reproduction

https://stackblitz.com/~/github.com/Alx90s/ambitive-qwik-reactivity-bug
In your stackblitz browser, enter this url **domain.de/admin/seiten/bearbeiten/1/**

### Steps to reproduce

npm run install 
npm run dev

Add an item through the plus button the list. 
Probably you need to clone this repo and run it on your browser. 
In the stackblitz demo the drag and drop is not working fine. Maybe a stackblitz bug. 
im not sure.  

### System Info

```shell
OS:MacOS (latest) 
Model: Apple M1 Pro Silicon
Browser: Chrome (latest)

QwikJS Version:
"@builder.io/qwik": "0.19.1",
"@builder.io/qwik-city": "0.4.0",
```

### Additional Information

I know that the issue come from this useBrowserVisibleTask. 
More detailed: if you commenting out its working. Comments are shown in the code block beneath 
`useBrowserVisibleTask$(({ track }) => {
    function handleDragStart(e) {
      source.value = parseInt(this.getAttribute("data-attr-key"));
      e.dataTransfer.effectAllowed = "move";
      e.dataTransfer.setData("text/html", this.outerHTML);
      this.classList.add("dragElem");
    }

    function handleDragOver(e) {
      if (e.preventDefault) {
        e.preventDefault();
      }
      this.classList.add("over");
      e.dataTransfer.dropEffect = "move";
      return false;
    }

    function handleDragLeave() {
      this.classList.remove("over");
    }

    
    async function processReorder() {
      /* BUG STARTS */
      if (source.value < destination.value)
        await moveArray$(
          pageD.data.Components,
          source.value,
          destination.value - 1
        );

      if (source.value > destination.value)
        await moveArray$(
          pageD.data.Components,
          source.value,
          destination.value
        );
   /* BUG ENDS */
    }

    function handleDrop(e) {
      if (e.stopPropagation) {
        e.stopPropagation();
      }
      destination.value = parseInt(this.getAttribute("data-attr-key"));
      processReorder();
      this.classList.remove("over");
      return false;
    }

    function addDnDHandlers(elem) {
      elem.addEventListener("dragstart", handleDragStart, false);
      elem.addEventListener("dragover", handleDragOver, false);
      elem.addEventListener("dragleave", handleDragLeave, false);
      elem.addEventListener("drop", handleDrop, false);
      elem.setAttribute("data-attr-handler-done", true);
    }

    const val = track(() => pageD.data.Components.length);
       /* BUG STARTS */
    if (val) {
      var cols = document.querySelectorAll(
        'li[data-attr-handler-done="false"]'
      );
      [].forEach.call(cols, addDnDHandlers);
    }
       /* BUG ENDS */
  });`

**Comment by ElectroluxV2** [comment]
Qwik should introduce way to synchronously handle events, or gave us some example how they want us to to do using existing handlers. My use case is setting `dataTransfer` on drag start event which cannot be done asynchronously.

**Comment by gioboa** [comment]
Hi @Alx90s, thanks for sharing details, with the latest version of Qwik is it still a valid issue?

**Comment by gioboa** [comment]
Thanks @Alx90s this is an old stale issue and it's a very specific problem for your domain.
A lot of things happened during this months and Qwik APIs changed a lot.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
