### ISSUE TITLE
[🐞] prop render function is not working as expected

### ISSUE THREAD

**Issue by tzdesign** [BuilderIO/qwik#3116]
### Which component is affected?

Qwik Runtime

### Describe the bug

We need to render something conditionally, or in another component we want to connect a conditionally rendered jsx node to a resource.

In a previous version (0.18) this worked.

Not sure if this is a problem, but from the documentation it looks like you can just add PropFunction type and a dollar and it should be resolved by the Optimizer.

It looks like its leaking somehow and in production it fails to find the right chunk.

### Reproduction

https://stackblitz.com/edit/qwik-starter-neiv59?file=src/routes/index.tsx

### Steps to reproduce

Just open the stackblitz and take a look on:

```tsx
export const RelayWithFunction = component$((props: RelayWithFunctionProps) => {
  const resource = useResource$(() => {
    return 'hallo';
  });

  return (
    <Resource
      onResolved={(product) => <>{props.render$(product)}</>}
      value={resource}
    />
  );
});

export type RelayWithFunctionProps = {
  render$: PropFunction<(product: string) => JSXNode>;
};
```

We have an alternative in the stackblitz as well, and passing it wrapped in $ solves the problem, but then you need to explain in the docs when a function with $ as a prop function works out of the box and when it doesn't.

### System Info

```shell
See Stackblitz:
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^0.19.1 => 0.19.1 
    @builder.io/qwik-city: ^0.3.0 => 0.3.0 
    undici: ^5.16.0 => 5.16.0 
    vite: ^4.0.4 => 4.0.4
```

**Comment by tzdesign** [comment]
@shairez like I promised 😉

**Comment by shairez** [comment]
thanks @tzdesign ! 🙏

**Comment by manucorporat** [comment]
Gonna look into this one on monday!

**Comment by manucorporat** [comment]
habemus fix
