### ISSUE TITLE
[🐞] Mutating arrays within signals or stores does not trigger render on map

### ISSUE THREAD

**Issue by bayssmekanique** [BuilderIO/qwik#3130]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am not certain if this bug is specific to events that don't have UI originating events or occur for all array related rendering. I first noticed it while implementing a websocket subscription that would not update when tuples were added to the array from the subscription call. A primitive number signal called from the same location causes the correct rendering change on the display so I don't believe it's an issue with the location of the call.

For the purpose of reproduction, I used a `setInterval` call which has the same effect and reproduces the issue with the map not updating. I've noticed that both the `map` call and call to `value.length` fail to cause a rendering call.

```ts
export default component$(() => {
  const comments = useSignal<string[]>(['Comment #1', 'Comment #2']);
  const commentsLength = useSignal<number>(comments.value.length);

  useBrowserVisibleTask$(() => {
    setInterval(() => {
      comments.value.push(`Comment #${comments.value.length + 1}`);
      commentsLength.value = comments.value.length;
      console.log(`Comment added. New length is ${commentsLength}`);
    }, 1000);
  });

  return (
    <div>
      <h1>This list should grow every second.</h1>
      <h3>The current length is {commentsLength.value}. (Should work)</h3>
      <h3>The current length is {comments.value.length}. (Doesn't work)</h3>

      <ul>
        {comments.value.map((comment) => (
          <li>{comment}</li>
        ))}
      </ul>
    </div>
  );
});
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-i1h2ja?file=src/routes/index.tsx

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 37.71 GB / 63.92 GB
  Binaries:
    Node: 19.6.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.50)
    Internet Explorer: 11.0.19041.1566
```
```


### Additional Information

_No response_

**Comment by manucorporat** [comment]
This is not an issue, signals does not watch for nested reactivity. Nested reactivity is actually extremely costly in terms of cpu and memory usage.

```
comments.value = [comments.value, `Comment #${comments.value.length + 1}`];
```

Should work, we could introduce a way to manually force a change too, without forced copy

**Comment by bayssmekanique** [comment]
To confirm for future user's stumbling across this, using a store with deep tracking does resolve this issue (though at a performance cost as pointed out above).

```
export default component$(() => {
  const comments = useStore({value:['Comment #1', 'Comment #2']}, {deep:true});
  const commentsLength = useSignal<number>(comments.value.length);

  useBrowserVisibleTask$(() => {
    setInterval(() => {
      comments.value.push(`Comment #${comments.value.length + 1}`);
      commentsLength.value = comments.value.length;
      console.log(`Comment added. New length is ${commentsLength}`);
    }, 1000);
  });

  return (
    <div>
      <h1>This list should grow every second.</h1>
      <h3>The current length is {commentsLength.value}. (Should work)</h3>
      <h3>The current length is {comments.value.length}. (Doesn't work)</h3>

      <ul>
        {comments.value.map((comment) => (
          <li>{comment}</li>
        ))}
      </ul>
    </div>
  );
});

```
