### ISSUE TITLE
[🐞] actions from the Form are vanished in the history.

### ISSUE THREAD

**Issue by genki** [BuilderIO/qwik#3149]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When to make a search form with the form component, it seemed there is no way to record the action in the browser history.
Suppose a man has searched words "Foo", "Bar" and then "Baz" and wanted to back to the result of "Foo".
But if he clicked the back button then the browser shows the page everything has not happened yet.
I am wondering on it is designed behavior or a bug.

### Reproduction

https://stackblitz.com/edit/qwik-starter-ry1wpp?file=src/routes/index.tsx

### Steps to reproduce

Please go to the reproduction link and click the `Open in New Tab` button at the top rigth corner.
And then type some words and click "submit" button. You can find no history has made.
This is not depending on if `reloadDocument` is set or not.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 77.92 MB / 24.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 110.0
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: file:../clone/qwik/packages/qwik => 0.19.2 
    @builder.io/qwik-city: file:../clone/qwik/packages/qwik-city => 0.4.0 
    undici: ^5.20.0 => 5.20.0
```

**Comment by genki** [comment]
I think it is best if there can be a way to store the states made by `useStore` or `useSignal` and viewing parameters such as the scroll position in the history and restore it when the browser goes back.

**Comment by gioboa** [comment]
Hi @genki, thanks for opening this issue.
A lot of things happened during this months, with the latest version of Qwik is it still a valid issue?

**Comment by gioboa** [comment]
@genki you can use [useNavigate](https://qwik.builder.io/docs/api/#usenavigate) to add your query strings to the history.
with routeAction$ I didn't find the way to redirect to the same path + query strings
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
