### ISSUE TITLE
[✨] Let us know if the current page being rendered is an MDX page or a regular JSX page

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#3150]
### Is your feature request related to a problem?

Since you have made writing MDX much easier than other frameworks (it works out of the box, and it works pretty well), we decided to use it.

However, we now have this problem. Let's say in `layout.jsx` we have this layout:

```
<Header>
<main>
    <Slot />
</main>
<Footer />
```

And we also have these pages:

```
- about
    - index.mdx
- contact
    - index.jsx
```

We now want to centralize styling `<main>` element in our `layout.jsx` based on the file being rendered. If it's an MDX file, we would apply a different style (for example `prose` from Tailwind Typography).

Of course in this example, we can check the routes and apply styles conditionally. But in a real-world app with more than 50 routes, it's not efficient.

### Describe the solution you'd like

It would be awesome if we can get a flag in our layouts, telling us whether the current route belongs to an MDX file or not.

For example:

```
const layout = component$({ isMdx }) => {
}
```

### Describe alternatives you've considered

Right now, I can only think about checking routes.

**Comment by bhajneet** [comment]
Have you looked into [named layouts](https://qwik.builder.io/qwikcity/advanced/routing/#named-layout) and [grouped layouts](https://qwik.builder.io/qwikcity/advanced/routing/#grouped-layouts)?

For example you could have:

```
- (mdx)
    - about
        - index.mdx
    - team
        - index.mdx
    - layout.jsx
- contact
    - index.jsx
```

`(mdx)/layout.jsx` could have a wrapper for your class, and links stay the same as `/about/` or `/team/`

**Comment by gioboa** [comment]
Hey @Nefcanto, thanks for opening this issue, did you solve this issue?

**Comment by Nefcanto** [comment]
@gioboa, thanks for following up. No, we had to change our way. At that time we could not make it work for us. But I guess it's worth being implemented.

**Comment by gioboa** [comment]
You could use named layout to achieve this functionality.

**Comment by shairez** [comment]
@gioboa is right, named layouts seems like a good solution for wrapping with the `prose` class

Thanks for reporting the issue, closing it for now, feel free to re-open if the suggested solutions do not solve the issue
