### ISSUE TITLE
[🐞] After the deployment on the Cloudflare Page with custom domain, 'nodeType' Error occured

### ISSUE THREAD

**Issue by DongwonTTuna** [BuilderIO/qwik#3161]
### Which component is affected?

Qwik Runtime

### Describe the bug

![スクリーンショット 2023-02-26 12 22 03](https://user-images.githubusercontent.com/38794795/221390697-a265ebc9-65cd-4fd8-875c-a455c5456770.png)

The error occured when I deployed on Cloudflare with the custom domain.

### Reproduction

https://dongwontuna.net/

### System Info

```shell
In cloudflare page deployment
```

**Comment by DongwonTTuna** [comment]
ok, I figured out how can I fix it.

Just turn off the Proxy to DNS only likes the photo.

![Uploading スクリーンショット 2023-02-26 12.28.09.png…]()

**Comment by DeVoresyah** [comment]
hmmm, I just confused why it can affect yah
