### ISSUE TITLE
[📖]: Community Menu options (Media, Showcase) showing 404 error

### ISSUE THREAD

**Issue by praveeno** [BuilderIO/qwik#3162]
below mentioned urls in https://qwik.builder.io/community/groups/ under menu section showing 404 error, 
https://qwik.builder.io/community/showcase/index.tsx (Showcase)
https://qwik.builder.io/community/media/index.tsx (Media)

https://github.com/BuilderIO/qwik/blob/5eb7e33759188e725b212213de134e296756322a/packages/docs/src/routes/community/menu.md?plain=1#L8

**Comment by zanettin** [comment]
Hi @praveeno 👋 
thanks a lot for the hint! 🙏

**Comment by praveeno** [comment]
I'm new to community, if you can point me to right direction, i can raise PR to fix this

**Comment by zanettin** [comment]
Thx @praveeno 🙏 and welcome 🥳 just checking internally what the goal is with this pages and come back to you 👍

**Comment by zanettin** [comment]
Hi @praveeno 👋 

So got all the needed info 😄  if you still like to help on this, this would be the expected goal:
- remove `showcase` and `media` from the top nav
- add content in the `community` section
- add redirects from the legacy path to the new ones [in this file](https://github.com/BuilderIO/qwik/blob/main/packages/docs/public/_redirects).

if you don't have time, let me know 👍 then i'll take over 🤓 😄 
thanks again 🙏

**Comment by kemilbeltre** [comment]
Hi @zanettin 😄

I would like to work on this if possible. 

Thanks!

**Comment by kemilbeltre** [comment]
Hi @zanettin 

Adding `showcase` and `media` to the `community` layout will cause problems with styles.

IDK if it is better idea to remove those links from the community menu. 🤔

Thanks

**Comment by zanettin** [comment]
Hi @kemilbeltre 👋 
thanks for taking this task 🙏 
can you share a printscreen or create a draft PR so that i can have an eye on the mentioned issue? thanks once again 🙏

**Comment by zanettin** [comment]
ah there is a config where u can set, that it shouldn't show the right navigation 👍  it's also in use on this page here https://qwik.builder.io/docs/overview/. hope this helps to find the right config file 🙏

**Comment by kemilbeltre** [comment]
Hi @zanettin

It works, thanks. But there is another problem:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/20250204/221564983-712c766f-015a-49a1-b9f2-51fc08a28d57.png">

It seems that `media` is not getting the styles right.

Do you have any idea?

Thanks

**Comment by kemilbeltre** [comment]
@zanettin now fixed. thanks

**Comment by zanettin** [comment]
the menupoints are removed by now. thanks again for creating this issue and giving hands 🙏
