### ISSUE TITLE
[🐞] Partytown Integration is broken

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#3191]
### Which component is affected?

Starters / CLI

### Describe the bug

When adding Partytown through the CLI, it will add the `partytownVite` plugin to `vite.config.ts`. This is setup to copy the Partytown script files to the project's `public` directory.

However, the `partytownVite` plugin is added at the end of the plugins array, so these files are not copied until **after** the project has been built. Therefore, the files **never** make it into the `dist` folder.

### Reproduction

https://github.com/BuilderIO/qwik/tree/main/starters/features/partytown

### Steps to reproduce

`npm create qwik@latest`
`npm run qwik add partytown`
`npm run build`

Observe that there is a `~partytown` directory in the `public` folder, but not in `dist`

### System Info

```shell
System:
    OS: Linux 6.0 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 57.10 GB / 62.65 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.volta/tools/image/node/16.18.0/bin/node
    npm: 8.19.2 - ~/.volta/tools/image/node/16.18.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 110.0
  npmPackages:
    @builder.io/partytown: ^0.7.0 => 0.7.5
    @builder.io/qwik: 0.19.2 => 0.19.2
    @builder.io/qwik-city: 0.4.0 => 0.4.0
    undici: 5.20.0 => 5.20.0
    vite: 4.1.4 => 4.1.4
```

### Additional Information

Discord thread: https://discord.com/channels/842438759945601056/1080022962503163924

**Comment by manucorporat** [comment]
Any easy solution? :/

**Comment by nnelgxorz** [comment]
I'm going to look into seeing if we can just change the integration to copy the files directly into dist. I'm not sure if that breaks dev or not. Will investigate.
