### ISSUE TITLE
[🐞] Service worker is not prefetching bundles

### ISSUE THREAD

**Issue by jweb89** [BuilderIO/qwik#3203]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I believe qwik should be eagerly fetching javascript via the service worker for visible things but it doesn't seem to be doing so.

### Reproduction

https://www.loom.com/share/ca64ccce86054d50862e1e56f493ee3c

### Steps to reproduce

Use the docs on your own browser. None of the js bundles seem to be getting prefetched the first time.

### System Info

```shell
Docs currently using
"@builder.io/qwik": "BuilderIO/qwik-build#8db8f9a63f9738c1d175a6341e4519605f5f2439",
"@builder.io/qwik-city": "0.4.0",

Our site currently using:
"@builder.io/qwik": "0.19.2",
"@builder.io/qwik-city": "0.4.0",

 System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 79.94 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 15.6

But have tried with latest v20 as well and same results
```

**Comment by manucorporat** [comment]
Please update to latest! 0.20.0 and 0.5.2!

**Comment by jweb89** [comment]
> Please update to latest! 0.20.0 and 0.5.2!

https://www.loom.com/share/baf558e2e7cb4d33b0116ea9b08d3e8a
I'm still seeing the same behavior on the latest of both

**Comment by EamonHeffernan** [comment]
Having this issue as well on latest. Cloudflare workers adapter.

**Comment by adamdbradley** [comment]
Should also point out, to ensure you're not using a service worker on first load, go to the "Application" tab in Dev tools, and click "Service Workers" in the left menu. Then click "Unregister" for your site's installed service worker:
![image](https://user-images.githubusercontent.com/452425/231260225-ae60433e-fe93-4356-bae3-80932b40cbe9.png)

And again, also make sure the "QwikBuild" cache is deleted too. With both the SW and cache storage cleared, it'll then be like a first load.

**Comment by hamatoyogi** [comment]
Is there still an issue with latest version?

**Comment by markkkkas** [comment]
@hamatoyogi I'm using qwik and Astro and i can see this issue on my end too.

```json
"@builder.io/qwik": "^1.4.3",
"@qwikdev/astro": "^0.5.2",
"astro": "^4.3.1"
```

**Comment by shairez** [comment]
@thejackshelton did you experience it as well?

**Comment by thejackshelton** [comment]
> @thejackshelton did you experience it as well?

Nope, using the latest version in production and it's prefetching fine. That is, with the core service worker at least.

**Comment by shairez** [comment]
Thanks @thejackshelton 

So I'm closing for now
Feel free to re-open if the problem still happenning
