### ISSUE TITLE
[🐞] repl returns 404

### ISSUE THREAD

**Issue by zanettin** [BuilderIO/qwik#3206]
### Which component is affected?

Qwik Playground

### Describe the bug

All tutorials and example previews return a 404
eg. https://qwik.builder.io/tutorial/welcome/overview/

### Reproduction

https://qwik.builder.io/tutorial/welcome/overview/

### System Info

```shell
general
```

**Comment by bsljth** [comment]
Any update on this?

🙂

**Comment by zanettin** [comment]
hi @bsljth 
i didn't have time so far to look into this and guess thats the case for the core-team as well. will try to have a lookt at it later unless smb else is "qwiker" 😃

**Comment by bsljth** [comment]
Oh, okay.

**Comment by zanettin** [comment]
imo there is an issue on the docs build itself. i am getting this error:
```
error during build:
TypeError [PLUGIN_ERROR]: Unknown file extension ".ts" for <path>/qwik/packages/qwik/src/build/index.ts
```
when running `pnpm build.server`.

tried to upgrade to latest version of `cloudflare-pages` adapter, which didn't change the result but added `manifest` to then `createQwikCity` fn.

@adamdbradley @manucorporat any hints/ideas?

**Comment by forresst** [comment]
For your information, it seems to be working again

**Comment by duongphuhiep** [comment]
playground + tutorial is broken for me: Linux Mint Firefox & Chrome

![image](https://user-images.githubusercontent.com/1638594/232636309-a737ff55-5a4b-4989-b224-46b28aec8ad2.png)

![image](https://user-images.githubusercontent.com/1638594/232636511-27848ebb-8617-4ad1-b08c-b5a8ddec860c.png)

**Comment by AmirSa12** [comment]
Still not working?
It's not working for me

**Comment by mustansirgodhrawala** [comment]
Not working for me in India!

**Comment by nicholaslyon** [comment]
Not working for me either. Getting this error on the sandbox and tutorial pages:
<img width="975" alt="Screenshot 2023-07-19 at 5 12 54 PM" src="https://github.com/BuilderIO/qwik/assets/22888816/d94c78a1-4d17-4268-a24a-1aa4e40e6059">
