### ISSUE TITLE
[🐞] Custom onClick$, onMouseOver$, etc. do not work with <Link /> component

### ISSUE THREAD

**Issue by fabian-hiller** [BuilderIO/qwik#3223]
### Which component is affected?

Qwik City (routing)

### Describe the bug

If a custom `onClick$` event is added, it will be ingnored as it will be overridden by the current [`<Link />`](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/runtime/src/link-component.tsx#L23-L31) implementation. The same is probably true for `onMouseOver$`, `onFocus$` and `onQVisible$`.

### Reproduction

https://stackblitz.com/edit/qwik-starter-z7z6jj?file=src%2Froutes%2Findex.tsx%3AL8

### Steps to reproduce

Click on the `<Link />` and `<button />` and check the logs.

### System Info

```shell
I think that this information is not relevant here.
```

**Comment by mrhoodz** [comment]
I also bumbed into this

**Comment by wmertens** [comment]
Is this fixed? Looking at the code, I think so?

https://github.com/BuilderIO/qwik/blob/2e96ae030a299e66191627352cb9252057064409/packages/qwik-city/runtime/src/link-component.tsx#L42C41-L42C41

BTW this is weird @manucorporat :sweat_smile:. Is this a way to destructure while keeping signals?
`const { onClick$, reload, replaceState, scroll, ...linkProps } = (() => props)();`

**Comment by fabian-hiller** [comment]
I think that it is not yet completely solved, eg. for `onMouseOver$` and `onFocus$`.

**Comment by shairez** [comment]
@fabian-hiller is this fixed already?

**Comment by fabian-hiller** [comment]
I haven't tested it, but it seems to be fixed in the source.

**Comment by shairez** [comment]
Awesome, thanks @fabian-hiller 

So I'm closing for now, feel free to re-open if it still happens
