### ISSUE TITLE
[🐞] Regression: 'locale' function does not set the locale

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#3228]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Until v0.19.2, the `locale` function could be used to set the locale, for example:

```
export const onRequest: RequestHandler = ({ locale }) => {
  // Set Qwik locale
  locale('en-US');
};
```

See https://github.com/mhevery/qwik-i18n/blob/main/src/routes/layout.tsx by Miško and https://github.com/robisim74/qwik-speak/blob/main/src/routes/layout.tsx (disclaimer, it's mine)

Now the locale is not set: 
- `q:locale` in html tag is empty:
- `useServerData<string>('locale')` returns an empty value
- `getLocale` throws: `Reading locale outside of context`

### Reproduction

https://stackblitz.com/edit/qwik-starter-rbt6dx?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

See in console

### System Info

```shell
Stackblitz
```

**Comment by ahnpnl** [comment]
there is an extra question I want to bring up is: how do we set `lang` attribute for `<html>`? Should we do it via `locale` function or is there another way?

**Comment by robisim74** [comment]
@ahnpnl you can set the `lang `attribute in `entry.ssr.tsx` file:

```
containerAttributes: {
      lang: opts.serverData?.locale
      ...opts.containerAttributes,
    },
```
This example use `locale` by Qwik (but not working in v.0.20.*), but you can check for other properties in `opts`: cookies, headers, params...

However this issue is for a bug in `locale `function.

**Comment by saeedhbi** [comment]
I do have this problem too.

**Comment by zanettin** [comment]
@robisim74 just did a short debugging session on this:
```
// entry.ssr.tsx

return renderToStream(<Root />, {
    manifest,
    ...opts,
    containerAttributes: {
      lang: "de", // <= sets HTML language
    },
    serverData: {
      ...opts.serverData,
      locale: "en", // <= sets q:locale
    },
}
```

i am not sure at all, if this is the right way to go and if the change made on `0.19.3` was by purpose. hope @manucorporat can give us a quick hint in which direction the fix should go 👼 🙏

**Comment by mahmoudajawad** [comment]
I confirm upgrading to `0.20` caused the issue, downgrading to `0.19.1` while keeping City at `0.5` still didn't fix it, however, dowgrading City as well to `0.4` fixed the issue and `locale` is back to work as expected.
