### ISSUE TITLE
[🐞] The tutorial and Qwik Playground no longer work on the website Qwik

### ISSUE THREAD

**Issue by forresst** [BuilderIO/qwik#3233]
### Which component is affected?

Qwik Playground

### Describe the bug

The view at the bottom right no longer works (App tab). It displays `404 - https://qwik.builder.io/repl/1lck5qn7h0l/`. If we look at the Diagnostics tab, we can see the following error:

```shell
Error: Unable to require() path "@builder.io/qwik/build" from a browser environment. at globalThis.qwikServer.globalThis.require (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:33:11) at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:164:20) at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:783:26) at g (https://qwik.builder.io/repl/repl-sw.js:1:377) at async B (https://qwik.builder.io/repl/repl-sw.js:1:1357) at async F (https://qwik.builder.io/repl/repl-sw.js:12:5469)
```

### Reproduction

https://qwik.builder.io/tutorial/welcome/overview/

### Steps to reproduce

Navigate to this URL Navigate to this URL [https://qwik.builder.io/tutorial/welcome/overview/](https://qwik.builder.io/tutorial/welcome/overview/)

### System Info

```shell
Website
```

**Comment by zanettin** [comment]
Hi @forresst 👋 
Thanks for mentioning this 🙏  there is already a [issue open](https://github.com/BuilderIO/qwik/issues/3206) in that regard 👍  hope it's okay, that i close this one 👼
