### ISSUE TITLE
[🐞] CLI 

### ISSUE THREAD

**Issue by allenli178** [BuilderIO/qwik#3236]
### Which component is affected?

Qwik Runtime

### Describe the bug

![image](https://user-images.githubusercontent.com/53218750/222424747-7d8facef-33e1-41d4-b131-d718e2224544.png)

### Reproduction

I cant find the cli repo

### Steps to reproduce

This error occurs when I choose up and down.

### System Info

```shell
no erro info
```

**Comment by zanettin** [comment]
Hi @allenli178 👋 
Thanks for your info. It seams to be related to this issue https://github.com/natemoo-re/clack/issues/87. Will upgrade the library as soon as possible. Sorry for the inconvenience 🙏
