### ISSUE TITLE
[🐞] UseResource throwing error on SSR for Qwik Endpoint (Relative Endpoint Only)

### ISSUE THREAD

**Issue by y471n** [BuilderIO/qwik#3243]
### Which component is affected?

Qwik City (routing)

### Describe the bug

**Scenario:**
Use `useResource` to fetch data with all the states and use Qwik endpoints as well.

**Relative URLs:**
If I query using: `/api/products` on the client end it works. 
On SSR (first-time load) it throws the error `Failed to parse URL...`

**Absolute URLs:** 
If I use the API URL as: `http://localhost:5173/api/products` it's working on both the client and server.

### Reproduction

https://stackblitz.com/edit/qwik-starter-yxboch?file=src%2Froutes%2Fapi%2Fproducts.ts,src%2Froutes%2Findex.tsx

### Steps to reproduce

As above

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 107.91 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: 0.20.1 => 0.20.1 
    @builder.io/qwik-city: 0.5.2 => 0.5.2 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4 

```
```


### Additional Information

_No response_

**Comment by hafeyang** [comment]
same problem for me ,  it is mandatory `useResources$` fetch should have complete url

```
const resource = useResource$(async ({ }) => {
    const res = await fetch("/echo/get?foo=1&bar=2") // error  Failed to parse URL...
      .then(res => res.json());
    return res;
  });
```
is it possible to fetch just passing relative path ?  I just want to run fetch on the client side

**Comment by gioboa** [comment]
Thanks @y471n and @hafeyang for the discussion and for sharing details, we recently added this specific scenario in the docs because of this issue #2873
I close this one because it's solved.
