### ISSUE TITLE
[🐞] useNavigate / SPA with Link and context inside of conditional rendered components

### ISSUE THREAD

**Issue by tzdesign** [BuilderIO/qwik#3245]
### Which component is affected?

Qwik Runtime

### Describe the bug

This is hard to get around, maybe someone has time for a call, but I will try to write it down.

In our large e-commerce application, we have something similar to builder.io that dynamically renders some registered components.
Our idea was not only to pass specific props to them, but also to use a context from the campaign page.

The route is a catch all route that creates a big result context with campaign products, list etc.

This is passed into a listContext and renders the campaign page conditionally, which then renders the components conditionally based on type.

I have simplified it here:

![image](https://user-images.githubusercontent.com/3037096/222711668-835b02eb-2460-4cf7-a568-f6c416eab84a.png)

In our app we run into the error:
> Qwik ERROR: Error: element must be connected to the dom

I tried to get the same error on stackblitz, but not sure why this is not possible. While doing this I actually discovered that the context is not changing for the conditionally rendered component, but within the route. I think it's leaking somewhere so the rendering process gets confused and this ends up in the error above.

I have rewritten this to multiple setups passing the components straight to the jsx on the bottom, populating them in an array.
Similar like this one: https://discord.com/channels/842438759945601056/842438761287254019/1063834705012719646

Maybe you check out this odd issue with the context out first.

[The stackblitz](https://stackblitz.com/edit/qwik-starter-sgxwr4?file=src/routes/index.tsx)

### Reproduction

https://stackblitz.com/edit/qwik-starter-sgxwr4?file=src/routes/index.tsx

### Steps to reproduce

Click the button inside the button.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^0.21.1 => 0.21.1 
    @builder.io/qwik-city: ^0.5.3 => 0.5.3
    undici: ^5.16.0 => 5.16.0 
    vite: ^4.0.4 => 4.0.4
```

**Comment by tzdesign** [comment]
Even if I struggle with our project, I can close it. The track function wasn't able to track the location as an object, because it might stay the same all the time.

I added a fork:
https://stackblitz.com/edit/qwik-starter-rf8yts?file=src%2Froutes%2F[...path]%2Findex.tsx,src%2Fcomponents%2FFactory.tsx

**Comment by shairez** [comment]
wait @tzdesign 
why did you close it? is it resolved?

**Comment by tzdesign** [comment]
@shairez I overcomplicated the issue and fucked it up with using **track** wrong. Changing it in the fork made it work for the stackblitz. So it's not an issue I can actually point out or reproduce. I found out just now, that it's working in preview and only fails in dev mode. But I have absolute no idea to debug this error.

It's definitely the product list rendered conditionally by our ListPage consuming the same context like the parent one.

**Comment by tzdesign** [comment]
@shairez @manucorporat with the help of a colleague I figured a way to reproduce it.

Of course it's hacky, but it will show what happens rendering something conditionally which asynchronosly changes consumed context.

I updated the stackblitz to that one:
https://stackblitz.com/edit/qwik-starter-sgxwr4?file=src/routes/index.tsx

**Comment by manucorporat** [comment]
I will look into it!

**Comment by tzdesign** [comment]
@manucorporat I think your perf PR fixed it somehow. Did you also rearrange the context revalidation after the render?
This would close this.

**Comment by manucorporat** [comment]
not directly, but fixed issues around element not connected! glad this got fixed!
