### ISSUE TITLE
[📖] change useBrowserVisibleTask$ to useVisibleTask$

### ISSUE THREAD

**Issue by devagja** [BuilderIO/qwik#3247]
### Suggestion

vestiges of useBrowserVisibleTask$ still exist in the documentation

I am going to try to point all the places where it is incorrect

- [ ] https://qwik.builder.io/docs/cheat/qwik-react/
- [ ] https://qwik.builder.io/docs/cheat/best-practices/

https://github.com/BuilderIO/qwik/pull/3215

**Comment by shairez** [comment]
thanks @devagja !

Can you please open a PR with a fix anywhere you find traces?

Thanks!

**Comment by devagja** [comment]
Sure!

**Comment by zanettin** [comment]
already closed by https://github.com/BuilderIO/qwik/pull/3267 🎉  thanks again for offering your help @devagja 🙏
