### ISSUE TITLE
[📖] Unclear instructions when it comes to testing/running your SSG'd site

### ISSUE THREAD

**Issue by qq99** [BuilderIO/qwik#3250]
### Suggestion

![image](https://user-images.githubusercontent.com/150352/222796631-a9ab1a38-d8eb-4577-9a5a-e46eaf0eb515.png)

`node server/entry.ssr.js` just returns instantly (verified I ran `yarn build.server` before), so it's not clear if this is old documentation for an older version

**Comment by nnelgxorz** [comment]
I think you'd need something like `npx http-server dist/` after running build, but that's npm specific. 

What's the cool kid way to run a simple http server locally these days?
