### ISSUE TITLE
[✨] Sending signals from backend to frontend

### ISSUE THREAD

**Issue by Dindaleon** [BuilderIO/qwik#3254]
### Is your feature request related to a problem?

Yes, when using a graphql subscription, I would like to be able to wake the client side from the server instead of a user interaction.

### Describe the solution you'd like

Whenever I receive data from my graphql subscription in qwik's backend send a signal to qwik's frontend so I can process and render the data.

### Describe alternatives you've considered

Using `useBrowserVisibleTask$` is not ideal because adds javascript to the initial render of the page. I want to have an initial load with 0kB JS load

**Comment by manucorporat** [comment]
Can you think of a way this could work without Qwik? just using some http trick? of dom events?

**Comment by Dindaleon** [comment]
I don't know any http tricks to do that. I did try with DOM event which worked but loaded a ton of JavaScript files which is not desired.

**Comment by gioboa** [comment]
hi @Dindaleon, thanks for opening this issue, did you find a solution for that?

**Comment by mhevery** [comment]
I don think this is something which we would like signals to be able to do as it would require keeping the server connection alive.

I think the way to solve it is to create a connection from the client to server on client boot and than listen to changes. 

Marking as Won't fix for now...
