### ISSUE TITLE
[🐞] Server function in useTask$ causes error

### ISSUE THREAD

**Issue by literalpie** [BuilderIO/qwik#3255]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I'm trying to use a server function in a `useTask$` hook. I get this error:
> Error: Dynamic require of "null.js" is not supported

### Reproduction

https://stackblitz.com/edit/qwik-starter-mvyrlt?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

uncomment the useTask$ hook and notice the build error.

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 160.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 3.3.1 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @builder.io/qwik: ~0.20.1 => 0.20.1 
    @builder.io/qwik-city: 0.5.1 => 0.5.1 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

### Additional Information

I'm honestly not sure what the expected behavior is. It would be sweet if server functions during the initial render got treated as `routeLoader$`s but I understand if that kind of magic isn't possible. Otherwise, it would be nice to run the server function somehow. If this isn't something that's intended to be supported, a better error message would be good.

**Comment by manucorporat** [comment]
This should be possible! In fact i think it's fixed in main
