### ISSUE TITLE
[✨] useContext returns 'undefined' if no context instead of printing error

### ISSUE THREAD

**Issue by jdgamble555** [BuilderIO/qwik#3256]
### Is your feature request related to a problem?

If I run a `useContext` when a context id does not exist, I get an unrecoverable error. When I put it in a try / catch block, it sill prints error to server console, although it runs.  It would be nice to just not return a context if it doesn't exist.

### Describe the solution you'd like

It would be cool to check if a context exists with `useContext`. 

```ts
const x = useContext(createContextId('io.builder.qwik.DNE'));
if (x) {
 // do something
}
```

### Describe alternatives you've considered

A function like `contextExists`:

```ts
if (contextExists(createContextId('io.builder.qwik.DNE')) {
  // do something
}
```
Or, just allow try / catch blocks to not throw errors even when you catch them.

```ts
try {
  const x = useContext(createContextId('io.builder.qwik.DNE'));
  if (x) {
    return x;
  }
} catch(e) {
  // console.error(e);
  // still prints error to server console, even with these comments
}
```
Currently, the above code still prints an error to the server console, although the try / catch does allow the code to run.  Error code 13, i.e., should not print to console if I catch it.

### Additional context

Here is an example of why this is important. You could create a universal store that could be placed anywhere (or any universal custom hook store you could use anywhere):

**universal-store.ts**
```ts
export const UniversalContext = (name: string) => createContextId('io.builder.qwik.' + name);

export const useUniversalStore = (initial_state = {}, name?: string) => {

  if (name) {
    const _store = useContext(UniversalContext(name));
    if (store) {
      // return context if exists, so must be child
      return _store;
    }

  const store = useStore(initial_state);
  
  if (name) {
    // parent, so make context reusable
    useContextProvider(UniversalContext(name), store);
  }

  return store;
};
```

This would allow a store to be used anywhere without having to think about context (just like Svelte).

**any-component.ts**
```ts
// for one time use
const newStore = useUniversalStore({ loading: true });
```

**any-child-or-parent.ts**
```ts
// same code in parent or child
const newStore = useUniversalStore({ loading: true }, 'my-store');
```

J

**Note:** I would use better typing with generics in a real app. :)

**Comment by jdgamble555** [comment]
Ok, so it looks like I can do this with just adding null to the second parameter and it won't error out!

```ts
const x = useContext(createContextId('io.builder.qwik.DNE'), null);
if (x) {
  return x;
}
```

J

**Comment by manucorporat** [comment]
Exactly! this can be already done by providing a default value in useContext() it will return the default value instead!

**Comment by manucorporat** [comment]
On a side note:
```
export const useUniversalStore = (initial_state = {}, name?: string) => {

  if (name) {
    const _store = useContext(UniversalContext(name));
    if (store) {
      // return context if exists, so must be child
      return _store;
    }

  const store = useStore(initial_state);
  
  if (name) {
    // parent, so make context reusable
    useContextProvider(UniversalContext(name), store);
  }

  return store;
};
```
This might be a bad idea, and can likely break. Use methods (like in react) can not be executed conditionally, new lint rules will error with it.

**Comment by jdgamble555** [comment]
Ok, so I should be able to do this instead then:

```ts
export const UniversalContext = (name: string) => createContextId('io.builder.qwik.' + name);

export const useUniversalStore = (initial_state = {}, name = '') => {

  const _store = useContext(UniversalContext(name));
  if (store) {
    // return context if exists, so must be child
    return _store;
  }

  const store = useStore(initial_state);
  
  // parent, so make context reusable
  useContextProvider(UniversalContext(name), store);

  return store;
};
```

J
