### ISSUE TITLE
[🐞] [vite]: Rollup failed to resolve import "NonExistingPath" from ...

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#3264]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I'm using `try/catch` to import a component.

This component might exist or might not exist in the specified path.

It works in the development environment. But when I want to build it, the `try/catch` is not respected.

```

    let dynamicComponent = null
    try {
        import('NonExistingPath')
            .then(x => dynamicComponent = x)
            .catch(error => console.log(error))
    } catch (error) {
        console.log(error)
    }

```

### Reproduction

https://github.com/Nefcanto/ViteRollUpTryCatch

### Steps to reproduce

- Clone
- `npm run dev`
- Home page can be seen
- `npm run build`
- Build fails

### System Info

```shell
System:
    OS: Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 6.17 GB / 15.52 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  npmPackages:
    @builder.io/partytown: ^0.7.5 => 0.7.5 
    @builder.io/qwik: ^0.20.1 => 0.20.1 
    @builder.io/qwik-city: ^0.5.2 => 0.5.2 
    @builder.io/qwik-react: ^0.4.2 => 0.4.2 
    vite: ^4.1.4 => 4.1.4
```

### Additional Information

I reported this error to [Vite](https://github.com/vitejs/vite/issues/12296) too.

Also I reported this to [Rollup](https://github.com/rollup/rollup/issues/4893) and [it seems that](https://rollupjs.org/repl/?version=3.18.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmxldCUyMGR5bmFtaWNDb21wb25lbnQlMjAlM0QlMjBudWxsJTVDbiUyMCUyMCUyMCUyMHRyeSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBpbXBvcnQoJ05vbkV4aXN0aW5nUGF0aCcpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMC50aGVuKHglMjAlM0QlM0UlMjBkeW5hbWljQ29tcG9uZW50JTIwJTNEJTIweCklNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwLmNhdGNoKGVycm9yJTIwJTNEJTNFJTIwY29uc29sZS5sb2coZXJyb3IpKSU1Q24lMjAlMjAlMjAlMjAlN0QlMjBjYXRjaCUyMChlcnJvciklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwY29uc29sZS5sb2coZXJyb3IpJTVDbiUyMCUyMCUyMCUyMCU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlN0QlN0Q=) this is not related to Rollup

**Comment by gioboa** [comment]
Hi @Nefcanto thanks for opening this issue, I saw the discussions in Vite and Rollup repo, can I close this issue? This is not related to Qwik.

**Comment by mhevery** [comment]
Yes, this is vite specific, so I will close this issue since there is nothing for us to do here.
