### ISSUE TITLE
[✨] Automatically reset the app, after changed in the tsconfig.json

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#3270]
### Is your feature request related to a problem?

One of the best features of Vite is that it automatically reloads itself even when files like `.env` or `vite.config.js` are changed.

Next.js does not do that. This means that anytime a developer changes those files, he needs to stop the app manually and start it again. This becomes even worse if the development is inside a container and sometimes the entire container needs to be stopped and started again (based on the complexity of some other parameters).

Qwik + Vite does a good job of reloading for changes in those files.

However, when we change the `tsconfig.json`, it does not automatically reload the app.

### Describe the solution you'd like

It would be awesome if we see Qwik + Vite reload automatically when we change the content of `tsconfig.json` file.

### Describe alternatives you've considered

Right now we have to stop and start again, manually.

**Comment by gioboa** [comment]
You can solve this issue with a custom Vite plugin.

```
const CustomHmr = () => {
  return {
    name: 'custom-hmr',
    enforce: 'post',
    // HMR
    handleHotUpdate({ file, server }: HmrContext) {
      if (file.endsWith('tsconfig.json')) { // <-- check filename here
        console.log('Reloading file...');
        server.hot.send({ type: 'full-reload', path: '*' });
      }
    },
  }
}

export default defineConfig((): UserConfig => {
 ...
 return {
   ...
   plugins: [..., CustomHmr()],
   ...
 }
});
```

So I'm closing this issue for now, feel free to re-open it if it's still an issue for you. Thanks.
