### ISSUE TITLE
[✨] tailwind starter should also install `prettier-plugin-tailwindcss`

### ISSUE THREAD

**Issue by rolanday** [BuilderIO/qwik#3283]
### Which component is affected?

Starters / CLI

### Describe the bug

Since Qwik includes prettier in scaffolding created using `npm create qwik@latest`, when adding tailwinds using `npm run qwik add`, `prettier-plugin-tailwindcss` should also be installed.

Not a big deal (fit-n-finish), but should get fixed at some point IMO.

Edit: For completeness, prettier.config should also be created/updated to reference `prettier-plugin-tailwindcss`. For example:

```
/** @type {import("prettier").Config} */
module.exports = {
	singleQuote: false,
	trailingComma: "none",
	printWidth: 100,
	useTabs: true,
	pluginSearchDirs: false,
	tailwindConfig: "./tailwind.config.cjs",
	plugins: [require("prettier-plugin-tailwindcss")]
};
```

### Reproduction

N/A

### Steps to reproduce

Run `npm create qwik@latest` to create a new project.
Add tailwinds integration using `npm run qwik add`
Open `project.json` and note that `prettier-plugin-tailwindcss` was not installed.

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (48) x64 Intel(R) Xeon(R) W-3265M CPU @ 2.70GHz
    Memory: 99.52 GB / 192.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox Developer Edition: 111.0
    Safari: 16.0
  npmPackages:
    undici: ^5.15.1 => 5.20.0
```

### Additional Information

N/A

**Comment by kerron** [comment]
@manucorporat would this be considered a "good first issue"? I'm looking for something to pick up and start contributing.

**Comment by gioboa** [comment]
Hi @rolanday thanks for opening this. @kerron this could be a perfect "good first issue", please create a PR if you want.
