### ISSUE TITLE
[🐞] Invalid module "@qwik-city-plan" error when previewing with qwik-auth

### ISSUE THREAD

**Issue by ulic75** [BuilderIO/qwik#3297]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

When running `pnpm preview` when using qwik-auth I receive the following error when the server tries to run.

```
❌ TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "@qwik-city-plan" is not a valid package name imported from D:\Users\user\Documents\VCS\Local\qwik-test\node_module
s\.pnpm\@builder.io+qwik-city@0.5.3_@builder.io+qwik@0.21.0\node_modules\@builder.io\qwik-city\index.qwik.mjs
```

### Reproduction

https://github.com/ulic75/test-qwik-auth

### Steps to reproduce

1. npm install
1. npm run preview, see error
1. stop preview
1. change `plugin@auth.ts` to import from local file (`~/lib/auth`) instead of library (`@builder.io/qwik-auth`), see commented out import
1. Do step 2 again, success!

So the issue has something to do with the package/library itself since using it locally works as expected.

### System Info

```shell
System:
    OS: Windows Server 2016 10.0.14393
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Memory: 3.53 GB / 16.00 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 110.0.5481.178
    Internet Explorer: 11.0.14393.2007
  npmPackages:
    @builder.io/qwik: 0.21.0 => 0.21.0
    @builder.io/qwik-auth: 0.0.4 => 0.0.4
    @builder.io/qwik-city: 0.5.3 => 0.5.3
    undici: 5.20.0 => 5.20.0
    vite: 4.1.4 => 4.1.4
```

**Comment by rolanday** [comment]
+1, can confirm the same.

**Comment by n8sabes** [comment]
Ditto -- seeing the same.

**Comment by as-ksavier** [comment]
the same with me

**Comment by bbigras** [comment]
Any progress on this? :pray:

I can't wait to switch works projects to qwik!

**Comment by lbensaad** [comment]
I am getting the same error with `pnpm build` and I am not using `qwik-auth`

**Comment by rolanday** [comment]
+1, same error. using qwik-auth as well.

```
TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "@qwik-city-plan" is not a valid package name imported from /Users/roland/GitHub/appyture/mkeg-web-app.qwik/node_modules/.pnpm/@builder.io+qwik-city@0.7.0_@builder.io+qwik@0.24.0/node_modules/@builder.io/qwik-city/index.qwik.mjs
```

**Comment by jdgamble555** [comment]
I have a feeling this is related to my issue:

https://github.com/BuilderIO/qwik/issues/3487

J

**Comment by Alounv** [comment]
I have the same issue.

As a workaround, I just :
- manually copied the content of the `node_modules/@builder.io/qwik-auth/index.mjs` into `src/server/auth/index.mjs`
- removed `@qwik-auth` from `package.json` and added `@auth-core` instead.

Then it worked **locally** (I'm using the Github provider).

But then I stumbled into another issue when deploying with Fastify on Fly.io: `segfault` when I get inside the `await Auth(..., options)` (and I'm unable to log anything inside the Auth function from `@auth-core`).

**Comment by manucorporat** [comment]
Alright! this is my priority now!

**Comment by oqx** [comment]
> I have same error when try to [intergrate](https://qwik.builder.io/docs/integrations/modular-forms)with modular-forms

If you're using `NX`, make sure you've installed this dependency in workspace root, removing it from your app/package's `package.json`.

This solved it for me.
