### ISSUE TITLE
[🐞] Error on running the application in `deploy` mode

### ISSUE THREAD

**Issue by saeedhbi** [BuilderIO/qwik#3309]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to move some components to separate component libraries outside of the main src directory. The goal is to create an application by micro frontend structure.

The problem is under building in SSR mode for production and running the application in `deploy` mode on  the express adapter. Everything is running when the application is running by `vite` but when it comes to running by `node` with `npm run deploy` command, there is an error:

`Error: Optimizer should replace all usages of $() with some special syntax. If you need to create a QRL manually, use inlinedQrl() instead.
    at async ESMLoader.import (https://qwikstarternby82h-em22.w-credentialless.staticblitz.com/blitz.d4a32cb71496f1cb7595ed7c8471aaa3b79d22fc.js:6:1209137)
    at async i.loadESM (https://qwikstarternby82h-em22.w-credentialless.staticblitz.com/blitz.d4a32cb71496f1cb7595ed7c8471aaa3b79d22fc.js:6:246622)
    at async handleMainPromise (https://qwikstarternby82h-em22.w-credentialless.staticblitz.com/blitz.d4a32cb71496f1cb7595ed7c8471aaa3b79d22fc.js:6:989144)`

I can't figure out what is the problem. I checked all built assets and the component with qrl instance is created. But can't understand what is the solution for solving this.

Thanks for your collaboration.

### Reproduction

https://stackblitz.com/edit/qwik-starter-nby82h

### Steps to reproduce

The flow for creating steps are these:
- `npm create qwik@latest` to create a new application
- cd to application, make `packages` directory and cd into it
-  `npm create qwik@latest` to create a pure resumable component library
- Add `@packages/logo` to `tsconfig.json` paths for importing path
- Add `<Logo />` to layout of main application
- `npm run build`
- `npm run deploy`

The application in the reproduction URL is built by the above steps and you can see the error by running these:
- `npm run build`
- `npm run deploy`

### System Info

```shell
System:
    OS: Linux 5.13 elementary OS 6.1 Jólnir
    CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
    Memory: 6.63 GB / 15.52 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Brave Browser: 100.1.37.113
    Chrome: 110.0.5481.100
  npmPackages:
    @builder.io/partytown: ^0.7.0 => 0.7.5 
    @builder.io/qwik: 0.20.1 => 0.20.1 
    @builder.io/qwik-city: 0.5.2 => 0.5.2 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

**Comment by saeedhbi** [comment]
@robisim74 I think there is a problem regarding resolve `tsconfigPaths()` because it's responsibility is handling paths. But it's wired that we should handle two separated sources for a simple issue.

**Comment by saeedhbi** [comment]
I'm closing this since the core problem is about vite configuration. But would be appreciated if qwik consider this in any way. 

Thanks.

**Comment by robisim74** [comment]
@saeedhbi I'm sorry, the solution I provided only works if your package is in `src`, or if you import functions that don't use Qwik. Maybe you should reconsider keeping this issue open, because:
- QwikVite has only one `srcDir`
- `vendorRoots` seems not working
- `tsconfigPaths` `projects` option is not enough
- Vite config is not enough

**Comment by saeedhbi** [comment]
@robisim74 I wanted to walk through the idea later. Thanks for informing me.

I will open the issue again since the idea will not resolve my problem.

**Comment by saeedhbi** [comment]
> @saeedhbi I found that `vendorRoots` wasn't working on my Windows machine for the usual path normalization problem... this should be the solution across systems (tested in Windows & Ubuntu):
> 
> ```
>      qwikVite({
>       vendorRoots: [
>         fileURLToPath(new URL('./packages/logo/src', import.meta.url))
>       ]
>     }), 
> ```
> 
> https://stackblitz.com/edit/qwik-starter-kuzkre?file=vite.config.ts

Yes, It's working. Thanks. It saved me a lot of time.
