### ISSUE TITLE
[🐞] routeLoader$ is not allowed to be exported from plugin files

### ISSUE THREAD

**Issue by ulic75** [BuilderIO/qwik#3320]
### Which component is affected?

Qwik ESLint

### Describe the bug

```
`routeLoader$()` can only be declared in `layout.tsx`, `index.tsx` and `plugin.tsx` inside the `src/routes` directory, instead it was declared in "/Users/ulic/qwik-routerLoader-error/src/routes/plugin@test.ts".
Please check the docs: https://qwik.builder.io/qwikcity/loadereslint[qwik/loader-location](https://github.com/BuilderIO/qwik)
```

### Steps to reproduce

create a `plugin@test.ts` file in `src/routes` with the content of
```ts
export const useMockData = routeLoader$(() => ({
  mock: 'value',
}));
```

### System Info

```shell
vscode
```

### Additional Information

I'm sure it just needs to be included in a list someplace, but I'm uncertain as to where that is.

**Comment by manucorporat** [comment]
How can i reproduce? can you share some source code that reproduces this issue?

**Comment by ulic75** [comment]
> 

Sorry Manu, I should know better.  I was getting an actual console error, but can't seem to reproduce that.  I am getting a linting warning though.  I've updated the issue.

**Comment by manucorporat** [comment]
ahhh!
