### ISSUE TITLE
[🐞] getting CORS while using express adapter with server$ in production build

### ISSUE THREAD

**Issue by spiritbroski** [BuilderIO/qwik#3325]
### Which component is affected?

Qwik City (routing)

### Describe the bug

im trying to use server$ with express adapter then it always getting CORS error it probably because whenever securityMiddleware method https://github.com/BuilderIO/qwik/blob/14f3256dab95ae8f5ab336826cff28f6995e8225/packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts#L266 checking it returns http instead of https some user also get this error in discord [here](https://discord.com/channels/842438759945601056/1072020093665562634), i've also saw in express  adapter vite config you can basically set origin url but i trying to add environment variable URL with no luck https://github.com/BuilderIO/qwik/blob/34ad7788ee257bcdd35245dc5e23396f84875d0f/packages/qwik-city/adapters/express/vite/index.ts#L10 because with cloudflare pages its all fine using server$ in the cloudflare adapter that are also has origin url setting here: 
https://github.com/BuilderIO/qwik/blob/34ad7788ee257bcdd35245dc5e23396f84875d0f/packages/qwik-city/adapters/cloudflare-pages/vite/index.ts#L12 this is only my guess because hopefully you guys can fix this

### Reproduction

https://stackblitz.com/edit/qwik-starter-9qfjat?file=src/routes/index.tsx

### Steps to reproduce

- click on `server only` button here:

![image](https://user-images.githubusercontent.com/62529025/224325620-a7192815-6163-4bbe-9a9c-e8ea14d218da.png)

- and you will see CORS issue in the terminal like this:

![image](https://user-images.githubusercontent.com/62529025/224325829-367c6308-c389-4ebc-bcc9-22a93e2d3cf6.png)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^0.20.1 => 0.20.1 
    @builder.io/qwik-city: ^0.5.2 => 0.5.2 
    undici: ^5.16.0 => 5.20.0 
    vite: ^4.0.4 => 4.1.4
```

**Comment by origranot** [comment]
Same here, happens with globalAction$.

**Comment by genki** [comment]
#3333 may share the same reason.

**Comment by origranot** [comment]
Is someone working on a PR?

**Comment by manucorporat** [comment]
Removing this check completely can be a security risk! but happy to spend some time on this, since it's affecting so many people

**Comment by spiritbroski** [comment]
hello @manucorporat i've tried the latest one 0.22.0 qwik and 0.6.2 qwik-city using express adapter and i still got cors error, is it because i need to set environment variable somewhere to set the origin.url? if yes, could you please tell me how to set that i have tried to use it like this `URL=https://dadsad.hop.sh qwik build` with no luck, also i tried to add environment variable URL also with no luck

**Comment by manucorporat** [comment]
Can you try setting the `ORIGIN` environment variable?

What's still not clear to me is why it's not working for you?
how are you deploying?

**Comment by spiritbroski** [comment]
> how are you deploying?
so i deploy to https://hop.io/ the command to deploy is as follow:

- npm build
- npm start

basically its the same way it run in stackblitz here in reproduction link i gave you earlier in the issue https://stackblitz.com/edit/qwik-starter-9qfjat?file=src/routes/index.tsx but this is still using the earlier version of qwik and qwik city i notice now when im using the latest one

```
"@builder.io/qwik": "^0.23.0",
    "@builder.io/qwik-city": "^0.6.5",
```

i get this error now 

```
Value at index 0 does not have a transferable type.

```
im using `server$` like this:

```
   <button
        onClick$={server$(() => {
          console.log('haha');
        })}
      >
        SERVER ONLY
      </button>
```

the stackblitz reproduction link if you want to try here https://stackblitz.com/edit/qwik-starter-9qfjat?file=src/routes/index.tsx

**Comment by Alx90s** [comment]
For me its still not working either: 

Version: 
 "@builder.io/qwik": "0.23.0",
 "@builder.io/qwik-city": "0.6.5",

My .env in my project:
ORIGIN=https://demo.ambitive.de

My domain I try to login: 
https://demo.ambitive.de/admin/

**Comment by spiritbroski** [comment]
solve using this:
```
"start": "ORIGIN=<your server name like https://panda.com> node server/entry.express",
```

**Comment by Klerith** [comment]
> ORIGIN=<

I can confirm, this worked for me
