### ISSUE TITLE
[✨] RequestEvent argument for server$

### ISSUE THREAD

**Issue by genki** [BuilderIO/qwik#3335]
### Is your feature request related to a problem?

Currently the `server$` has no argument from `RequestEvent` so that the function can't used being related with session information.

### Describe the solution you'd like

How about some of the `RequestEvent` into the last argument as like as `globalAction$`?

### Describe alternatives you've considered

`routeLoader$` can have option to act as lazy to dynamically load when the document ready.

**Comment by tuurbo** [comment]
You can with "this". And you can't use the arrow function shorthand.
```tsx
server$(function(){
   this.request
})
```

**Comment by genki** [comment]
@tuurbo Oh, that!
Thanks a lot :)
