### ISSUE TITLE
[🐞] useComputed$ order matters in render body, but TS/linter does not complain

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#3347]
### Which component is affected?

Qwik Runtime

### Describe the bug

```
import { component$, useSignal, useComputed$ } from '@builder.io/qwik';

export default component$(() => {
  const y = useComputed$(() => x.value + 10)

  const x = useSignal(2)

  return <p>{x}, {y}</p>;
});
```

`y` needs to be defined after `x`, to avoid a `ReferenceError: Cannot access 'x' before initialization`. However, there is no indication at compile time that this might be an issue.

### Reproduction

[link](https://qwik.builder.io/playground#version=0.21.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU2lnbmFsJTJDJTIwdXNlQ29tcHV0ZWQlMjQlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHklMjAlM0QlMjB1c2VDb21wdXRlZCUyNCgoKSUyMCUzRCUzRSUyMHgudmFsdWUlMjAlMkIlMjAxMCklNUNuJTVDbiUyMCUyMGNvbnN0JTIweCUyMCUzRCUyMHVzZVNpZ25hbCgyKSU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwJTNDcCUzRSU3QnglN0QlMkMlMjAlN0J5JTdEJTNDJTJGcCUzRSUzQiU1Q24lN0QpJTNCJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlbmRlclRvU3RyaW5nJTJDJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBBcHAlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D)

### System Info

```shell
playground/latest
```

**Comment by manucorporat** [comment]
This is a problem with all `$()`, it's been reported before, but we can't do much about it, cuz it needs to get a hold of the lexical scoped stuff. and this code could likely crash at runtime too if useComputed executes eagarley, which it could

**Comment by samijaber** [comment]
I see!

> but we can't do much about it

Is there a future where the compiler could draw the relationship graph between every `$` variable inside a component's render body, and re-order them so they execute in the correct order according to the graph? 🤔

**Comment by ahnpnl** [comment]
This rule  https://typescript-eslint.io/rules/no-use-before-define/ can help in this case
