### ISSUE TITLE
[✨] starters/basic: add fingerprinted assets

### ISSUE THREAD

**Issue by jamesarosen** [BuilderIO/qwik#3349]
## Why does fingerprinting matter?

Asset fingerprinting is important for website performance. Without fingerprinting, the website has to use no HTTP caching or HTTP caching with `must-revalidate`. In either case, the browser must make a request all the way to the origin server to ensure each asset it fresh. This is because any new version of the application might have updated the file.

With fingerprinting, each asset's URL changes as its contents change. That means that each unique URL can be cached _indefinitely_ in both the browser and the CDN. This greatly improves performance, especially for key assets like CSS, hero images, and fonts.

## Current state

Qwik (via Vite) automatically fingerprints its compiled CSS and JS assets. This is great!

In addition to those, this template currently has a few static-asset-like files:

* `src/components/icons/qwik.tsx` -- this is an SVG file wrapped in a JSX component that `src/components/header/header.tsx` imports and uses. Because this is a JSX component, it gets included in the various `q-abc123.js` bundles.
* `public/favicon.svg` -- this is an SVG file that gets referenced in `router-head.tsx`. Because this is in `public/` Vite doesn't fingerprint it

## How can this improve?

The Qwik docs don't talk about asset fingerprinting at all. Indeed, Qwik doesn't do anything special for asset fingerprinting. It simply defers to the [standard Vite behavior](https://vitejs.dev/guide/assets.html).

Still, because this template plays such an important part in setting developers up for success, I think they should see how to import static assets and refer to them. Many folks coming to Qwik don't have a background in Vite. If they simply follow the pattern of putting assets in `public/`, they'll end up with worse site performance, lower Lighthouse scores, and worse SEO.

## Some ideas

The simplest change would be to move `public/favicon.svg` to `src/images/favicon.svg` and change `router-head.tsx` as follows:
```tsx
import favicon from '~/images/favicon.svg'
…
<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
```

Alternatively, we could add a new image or font to the template and reference that.

My instinct is to leave the `src/components/icons/qwik.tsx` file in-place because it demonstrates how to use SVG as a component, which can be quite useful.

This helps set developers up for success by pushing them towards better patterns and away from worse ones -- especially on topics like performance, accessibility, and security, where new developers may not have much expertise.

**Comment by gioboa** [comment]
Thanks @jamesarosen, thanks for opening this issue.
A lot of things happened during this months, this amazing feature [responsive-images](https://qwik.builder.io/docs/integrations/image-optimization/#responsive-images) was recently released.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
