### ISSUE TITLE
[🐞] npm create qwik@latest todolist doesn't work

### ISSUE THREAD

**Issue by TheodorGauguin** [BuilderIO/qwik#3355]
### Which component is affected?

Starters/CLI

### Describe the bug

I initialize the project with `npm create qwik@latest` and install tailwind, netlify edge via `npm run qwik add` and install daisyui via `npm i daisyui` and add the plugin to the tailwind.config.js. 
When starting the project and navigating to the todo app, it doesnt add todos when writing text and adding them. 
Also tested this exact process with 0.20.1 and it works there.

### Reproduction

https://github.com/TheodorGauguin/qwik-latest-test

### Steps to reproduce

I initialize the project with `npm create qwik@latest` and install tailwind, netlify edge via `npm run qwik add` and install daisyui via `npm i daisyui` and add the plugin to the tailwind.config.js. 

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 120.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.6.1 - /usr/local/bin/npm
  Browsers:
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.21.0 => 0.21.0 
    @builder.io/qwik-city: 0.5.3 => 0.5.3 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

**Comment by corscheid** [comment]
I noticed this as well, and discovered an open thread about it on the Builder.io Discord.

Here's a helpful post I found there:

<img width="784" alt="Screen Shot 2023-03-14 at 02 16 56" src="https://user-images.githubusercontent.com/6957624/224924180-74ad1dc4-b94b-4018-b9ae-1af455147975.png">

I confirmed that this works for me as well. I'm not sure if it's a mistake in the starter template, a bug in `routeAction$`, or something else.
