### ISSUE TITLE
[🐞] Cannot redirect from a `server$` function

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#3364]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Throwing a redirect from a `server$` function doesn't work, yet the redirect method is available on the functions `this`.

For example, this will give an error:

```tsx
const redirect = server$(function () {
  throw this.redirect(302, "/");
});

export default component$(() => {
  return (
    <>
      <button onClick$={() => redirect()}>Try redirect me</button>
    </>
  );
});
```

### Reproduction

https://github.com/DustinJSilk/qwik-issue-server-redirect

### Steps to reproduce

View the reproduction repo

### System Info

```shell
N/A
```

**Comment by manucorporat** [comment]
Does it make sense to redirect from a `server$()`? we should remove this APIs from server, right?

**Comment by DustinJSilk** [comment]
Hmm i think you're right actually.
Returning a 3xx on an ajax request would tell the browser to redirect the request, not the page.
It might make sense to remove this API from the server$
