### ISSUE TITLE
[🐞] Cannot create new project with Node 18

### ISSUE THREAD

**Issue by ahnpnl** [BuilderIO/qwik#3365]
### Which component is affected?

Starters / CLI

### Describe the bug

I tried to create a new project with `yarn create qwik@latest` and I ran into error
```
➜  ~ yarn create qwik@latest
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error expo-cli@5.3.1: The engine "node" is incompatible with this module. Expected version ">=12 <=16". Got "18.15.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

### Reproduction

N.A.

### Steps to reproduce

- Install Node 18 with `Homebrew`
- Run `yarn create qwik@latest`

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 129.80 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 108.0.2
    Safari: 16.3
```

### Additional Information

This occurs on MacOS M1, I'm not sure about Linux or Windows

**Comment by forresst** [comment]
Can you try the following command `yarn create qwik` instead of `yarn create qwik@latest`.
The documentation [was changed two weeks ago](https://qwik.builder.io/docs/getting-started/#run-the-qwik-cli-in-your-shell) to remove `latest` in the case of yarn.

This may solve the problem. Thanks for your feedback

**Comment by ahnpnl** [comment]
I just tried out and `yarn create qwik` still prints out the same error

**Comment by forresst** [comment]
NOTE: this works on Windows

```shell  
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 6.94 GB / 15.86 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.23.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 107.0.5304.88
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.69)
    Internet Explorer: 11.0.19041.1566
```

**Comment by manucorporat** [comment]
what is expo-cli?

**Comment by ahnpnl** [comment]
I think it was installed by accident, I diid `yarn global remove expo-cli` and then generate project it works again. Thanks for your support:)
