### ISSUE TITLE
[🐞] 'Client-only' code is imported in entry.express

### ISSUE THREAD

**Issue by Wimpert** [BuilderIO/qwik#3385]
### Which component is affected?

Qwik Optimizer (rust)

### Describe the bug

In one of our components, we are showing a map to the user.  The functionality of the map used to be wrapped in a `useClientEffect$` .

```ts
 useClientEffect$(async ({ track }) => {
    track(() => props.mapVisible);
    if (props.mapVisible) {
     // do some map related stuff
    }
  });
```
However we upgrade from:
```json
 "@builder.io/qwik": "0.16.2",
 "@builder.io/qwik-city": "0.0.128", 
```
to 
```json
  "@builder.io/qwik": "0.21.0",
  "@builder.io/qwik-city": "0.5.3",
```
This forced us to replace `useClientEffect$` by `useVisibleTask$`.

```ts
 useVisibleTask$(async ({ track }) => {
    track(() => props.mapVisible);
    if (props.mapVisible) {
     // do some map related stuff
    }
  });
```
## Actual behaviour:

After building the application we see that the import of leaflet is added to `entry.express.mjs`. This is causing the application to crash at startup:
```
ReferenceError: window is not defined
    at eval (file:///home/projects/qwik-starter-vtm9gw/node_modules/leaflet/dist/leaflet-src.js:230:19)
    at eval (file:///home/projects/qwik-starter-vtm9gw/node_modules/leaflet/dist/leaflet-src.js:7:66)
    at Object.eval (file:///home/projects/qwik-starter-vtm9gw/node_modules/leaflet/dist/leaflet-src.js:10:3)
    at Object.function (https://qwikstartervtm9gw-mylu.w-credentialless.staticblitz.com/blitz.6df6cd42ba0b81666017ec43c5c96e159ca2f943.js:15:141457)
```
We where able to work around this by using a lazy loaded import `const { getMapUtils : _getMapUtils} = await import('./add-features');`

## Expected Behaviour
This import should not be bundled in the `entry.express.mjs' if the code is wrapped in a `useVisibleTask$` hook

### Reproduction

https://stackblitz.com/edit/qwik-starter-vtm9gw

### Steps to reproduce

Open the url.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.21.0 => 0.21.0 
    @builder.io/qwik-city: 0.5.3 => 0.5.3 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

**Comment by manucorporat** [comment]
Why is the lib files outside the src directory?

The issue is not related to useClientEffect or useVisibleTask, now both behave the same, the problem started with a change to make serverQrl work, which involved emiting a side effect import to local files referenced.

In this case, it fails because:
- it's a relative import, but outside the src directory
- the dependency has side effects


A work around you can do is to:

1. move the function inside the src directory
2. use isBrowser to wrap the usage of leaflet


Need to fix how to solve this issue

**Comment by manucorporat** [comment]
Some mitigations:
- resolve relative imports, to figure out if they point to a file outside the src directory and treat them like external imports
- mark external deps has sideEffect free (could be problematic)

**Comment by Wimpert** [comment]
@manucorporat 

> A work around you can do is to:
>
> 1. move the function inside the src directory
> 2. use isBrowser to wrap the usage of leaflet

Indeed the first solution seems to work. Thx for the hint. However, we are building in the context of an NX monorepo and this code is situated in a lib (obviously outside of the `src` folder).
