### ISSUE TITLE
[🐞] useVisibleTask$() maybe the cause of flickering (dark mode) after the first render

### ISSUE THREAD

**Issue by un33k** [BuilderIO/qwik#3391]
### Which component is affected?

Qwik Runtime

### Describe the bug

Upon page load, the code checks localStorage for a dark mode flag. This check must be executed in the browser. If the flag is not set, the system theme mode is evaluated and the flag is set accordingly for the next time.

As the default mode is the light mode, the useVisibleTask$() function only runs after the page has rendered with a white background. This function then switches the theme to dark, resulting in a flicker on the initial load.

The following code block shows the implementation of the useVisibleTask$() function in root.tsx, which sets the appropriate dark class on the html element based on the localStorage and system theme mode:

```tsx
  // in root.tsx
  useVisibleTask$(
    () => {
      console.log("Hello from QwikCity! (visible)");
      const colorTheme = localStorage.getItem("color-theme");
      if (colorTheme === "dark") {
        document.documentElement.classList.add("dark");
      } else if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
        document.documentElement.classList.add("dark");
      } else {
        document.documentElement.classList.remove("dark");
      }
    }
    { strategy: "document-ready" } // document-idle or none for default behave the same here
  );
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-usevisibletask?file=src%2Froot.tsx

### Steps to reproduce

To observe the flicker effect more clearly, click on the reproduction link above and once loaded, continue clicking on the reload ⟳ button within StackBlitz. This will cause the white background to flicker and transition into a black background. It's recommended to use this method instead of performing a full browser reload to better observe the effect.

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 79.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Safari: 16.3
  npmPackages:
    @builder.io/partytown: ^0.7.5 => 0.7.5 
    @builder.io/qwik: ^0.21.0 => 0.21.0 
    @builder.io/qwik-city: ^0.5.3 => 0.5.3 
    @builder.io/qwik-react: ^0.4.2 => 0.4.2 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

### Additional Information

A minor flicker may be acceptable, but that's not the focus here. A useful addition would be to include a new `strategy` so we get to add a `dark` class to the html or body element before the initial rendering, as an alternative approach.

**Comment by zanettin** [comment]
Hi @un33k 👋  thanks for creating this issue. For me it looks identical to what is discussed [here](https://github.com/BuilderIO/qwik/issues/2926), right?

**Comment by manucorporat** [comment]
Qwik does not make it easy to add blocking scripts, the work around for now is to inline a script in the root.tsx
that runs the logic you described.

**Comment by un33k** [comment]
@zanettin I've raised a PR to help with the issues such as the flicker.  I noticed that the `docs` app was actually using the same pattern.  Have a look and take it for a spin.  Its biggest value proposition is that the serializable code remains in typescript, under eslint, prettier, and IDE control, yet gets serialized just in time for injection into the header script tag.

**Comment by icarus-sullivan** [comment]
@un33k I ran into the same issue as you. I solved it by adding a script to initialize the theme within the head element of root.tsx. 

_root.tsx_
```typescript
import { component$ } from '@builder.io/qwik';
import { QwikCityProvider, RouterOutlet, ServiceWorkerRegister } from '@builder.io/qwik-city';
import { RouterHead } from './components/router-head/router-head';
import { useThemeProvider } from './context/theme';

import './global.css';

export default component$(() => {
  /**
   * The root of a QwikCity site always start with the <QwikCityProvider> component,
   * immediately followed by the document's <head> and <body>.
   *
   * Dont remove the `<head>` and `<body>` elements.
   */
  
  useThemeProvider()

  return (
    <QwikCityProvider>
      <head>
        <meta charSet="utf-8" />
        <link rel="manifest" href="/manifest.json" />
        <RouterHead />
        <script dangerouslySetInnerHTML={`
          if (window.matchMedia("(prefers-color-scheme: dark)").matches &&
            localStorage.theme !== 'light') {
            localStorage.theme = 'dark';
          }
        
          document.documentElement.className = localStorage.theme || 'dark';
        `} />
      </head>
      <body lang="en" class='bg-white dark:bg-dark text-black dark:text-white' >
        <RouterOutlet />
        <ServiceWorkerRegister />
      </body>
    </QwikCityProvider>
  );
});
```

Then within my theme provider I have the following:

_theme.tsx_
```typescript
import { createContextId, useContext, useContextProvider, useStore, useVisibleTask$ } from '@builder.io/qwik';

interface Theme {
  theme: string
}

export const ThemeContext = createContextId<Theme>('theme');

export const useThemeProvider = () => {
  const store = useStore<{ theme: string }>({
    theme: ''
  })

  useContextProvider(
    ThemeContext,
    store
  );

  useVisibleTask$(({ track }) => {
    const change = track(() => store.theme)

    /**
     * We set theme to an '' when initialized, make sure we grab the actual
     * value
     */
    if (!store.theme) {
      store.theme = localStorage.theme || 'dark'
    }

    /**
     * Ignore non-initialized value
     */
    if (!change) return
    
    /**
     * Make sure we are only updating the html class if we have to to avoid
     * uneccesary paint calls 
     */
    if (document.documentElement.className !== change) {
      document.documentElement.className = change
    }

    /**
     * Update our local storage if a change has occurred
     */
    localStorage.theme = change
  });
}

export const useTheme = () => useContext(ThemeContext)
```

**Comment by Nedimko123** [comment]
@icar

> @un33k I ran into the same issue as you. I solved it by adding a script to initialize the theme within the head element of root.tsx.
> 
> _root.tsx_
> 
> ```ts
> import { component$ } from '@builder.io/qwik';
> import { QwikCityProvider, RouterOutlet, ServiceWorkerRegister } from '@builder.io/qwik-city';
> import { RouterHead } from './components/router-head/router-head';
> import { useThemeProvider } from './context/theme';
> 
> import './global.css';
> 
> export default component$(() => {
>   /**
>    * The root of a QwikCity site always start with the <QwikCityProvider> component,
>    * immediately followed by the document's <head> and <body>.
>    *
>    * Dont remove the `<head>` and `<body>` elements.
>    */
>   
>   useThemeProvider()
> 
>   return (
>     <QwikCityProvider>
>       <head>
>         <meta charSet="utf-8" />
>         <link rel="manifest" href="/manifest.json" />
>         <RouterHead />
>         <script dangerouslySetInnerHTML={`
>           if (window.matchMedia("(prefers-color-scheme: dark)").matches &&
>             localStorage.theme !== 'light') {
>             localStorage.theme = 'dark';
>           }
>         
>           document.documentElement.className = localStorage.theme || 'dark';
>         `} />
>       </head>
>       <body lang="en" class='bg-white dark:bg-dark text-black dark:text-white' >
>         <RouterOutlet />
>         <ServiceWorkerRegister />
>       </body>
>     </QwikCityProvider>
>   );
> });
> ```
> 
> Then within my theme provider I have the following:
> 
> _theme.tsx_
> 
> ```ts
> import { createContextId, useContext, useContextProvider, useStore, useVisibleTask$ } from '@builder.io/qwik';
> 
> interface Theme {
>   theme: string
> }
> 
> export const ThemeContext = createContextId<Theme>('theme');
> 
> export const useThemeProvider = () => {
>   const store = useStore<{ theme: string }>({
>     theme: ''
>   })
> 
>   useContextProvider(
>     ThemeContext,
>     store
>   );
> 
>   useVisibleTask$(({ track }) => {
>     const change = track(() => store.theme)
> 
>     /**
>      * We set theme to an '' when initialized, make sure we grab the actual
>      * value
>      */
>     if (!store.theme) {
>       store.theme = localStorage.theme || 'dark'
>     }
> 
>     /**
>      * Ignore non-initialized value
>      */
>     if (!change) return
>     
>     /**
>      * Make sure we are only updating the html class if we have to to avoid
>      * uneccesary paint calls 
>      */
>     if (document.documentElement.className !== change) {
>       document.documentElement.className = change
>     }
> 
>     /**
>      * Update our local storage if a change has occurred
>      */
>     localStorage.theme = change
>   });
> }
> 
> export const useTheme = () => useContext(ThemeContext)
> ```

Thanks, it worked!!

**Comment by eustachi0** [comment]
> @un33k I ran into the same issue as you. I solved it by adding a script to initialize the theme within the head element of root.tsx.
> 
> _root.tsx_
> 
> ```ts
> import { component$ } from '@builder.io/qwik';
> import { QwikCityProvider, RouterOutlet, ServiceWorkerRegister } from '@builder.io/qwik-city';
> import { RouterHead } from './components/router-head/router-head';
> import { useThemeProvider } from './context/theme';
> 
> import './global.css';
> 
> export default component$(() => {
>   /**
>    * The root of a QwikCity site always start with the <QwikCityProvider> component,
>    * immediately followed by the document's <head> and <body>.
>    *
>    * Dont remove the `<head>` and `<body>` elements.
>    */
>   
>   useThemeProvider()
> 
>   return (
>     <QwikCityProvider>
>       <head>
>         <meta charSet="utf-8" />
>         <link rel="manifest" href="/manifest.json" />
>         <RouterHead />
>         <script dangerouslySetInnerHTML={`
>           if (window.matchMedia("(prefers-color-scheme: dark)").matches &&
>             localStorage.theme !== 'light') {
>             localStorage.theme = 'dark';
>           }
>         
>           document.documentElement.className = localStorage.theme || 'dark';
>         `} />
>       </head>
>       <body lang="en" class='bg-white dark:bg-dark text-black dark:text-white' >
>         <RouterOutlet />
>         <ServiceWorkerRegister />
>       </body>
>     </QwikCityProvider>
>   );
> });
> ```
> 
> Then within my theme provider I have the following:
> 
> _theme.tsx_
> 
> ```ts
> import { createContextId, useContext, useContextProvider, useStore, useVisibleTask$ } from '@builder.io/qwik';
> 
> interface Theme {
>   theme: string
> }
> 
> export const ThemeContext = createContextId<Theme>('theme');
> 
> export const useThemeProvider = () => {
>   const store = useStore<{ theme: string }>({
>     theme: ''
>   })
> 
>   useContextProvider(
>     ThemeContext,
>     store
>   );
> 
>   useVisibleTask$(({ track }) => {
>     const change = track(() => store.theme)
> 
>     /**
>      * We set theme to an '' when initialized, make sure we grab the actual
>      * value
>      */
>     if (!store.theme) {
>       store.theme = localStorage.theme || 'dark'
>     }
> 
>     /**
>      * Ignore non-initialized value
>      */
>     if (!change) return
>     
>     /**
>      * Make sure we are only updating the html class if we have to to avoid
>      * uneccesary paint calls 
>      */
>     if (document.documentElement.className !== change) {
>       document.documentElement.className = change
>     }
> 
>     /**
>      * Update our local storage if a change has occurred
>      */
>     localStorage.theme = change
>   });
> }
> 
> export const useTheme = () => useContext(ThemeContext)
> ```

Thank you!. It works. I was a bit frustrated finding out how to prevent the flashings on page reload/refresh. I wish there was a sort of dynamic html container that we can import to the root and append dynamic data. Or that the html tag is exposed in the root like the head and the body are. I'm sure the guys at Qwik will come up with something clever for this.

**Comment by eustachi0** [comment]
From the help above, I created a reusable component that can be added in the main layout.tsx without using context. I am implementing a multi-theme web app, some of the styles will be set by an api as the user will have some control over i.e which color they would like the web app to look. I am also using isomorphic-dompurify (this one runs on the server and the client) to sanitize the script, so you need to install `npm i isomorphic-dompurify`.

An opinion here, I find themes that auto set themselves according to user preferences a bit too much, so I added a defaultTheme argument to pass, if you set it to i.e 'light' it will set the theme to 'light' for the first time, but it the user changes to 'dark' and close the browser, the next time the user comes back it will be set to 'dark'

```tsx
// theme-mode.tsx
import { component$ } from '@builder.io/qwik';
import DOMPurify from 'isomorphic-dompurify';

interface ThemeModeProps {
    defaultTheme?: string;
    themeStyle?: string;
    themeColor?: string;
    themeCorners?: string;
}

export const ThemeMode = component$(({ defaultTheme, themeStyle, themeColor, themeCorners }: ThemeModeProps) => {
    const scriptToInject = () => {
        const script =
            `
            document.documentElement.setAttribute('data-theme-style', '${themeStyle}');
            document.documentElement.setAttribute('data-theme-color', '${themeColor}');
            document.documentElement.setAttribute('data-theme-corners', '${themeCorners}');

            if ('${defaultTheme}' !== 'undefined' && localStorage.getItem('theme') === null) {
                    if ('${defaultTheme}' === 'light') {
                        localStorage.setItem('theme', 'light');
                        document.documentElement.className = 'light';
                    }
                    if ('${defaultTheme}' === 'dark') {
                        localStorage.setItem('theme', 'dark');
                        document.documentElement.className = 'dark';
                    }
            }
            if ('${defaultTheme}' === 'undefined') {
                if (window.matchMedia('(prefers-color-scheme: dark)').matches && localStorage.getItem('theme') !== 'light') {
                    localStorage.setItem('theme', 'dark');
                }
            }
            document.documentElement.className = localStorage.theme || 'dark';
            `
            ;

        return script;
    }

    const purifiedScript = DOMPurify.sanitize(scriptToInject());

    return <script dangerouslySetInnerHTML={`{ __html: ${purifiedScript}}`} />
})
```

Then, import it in the layout.tsx
```tsx
...
import { ThemeMode } from "~/components/theme-mode/theme-mode";

// this will be fetch from an api
export const useGetThemes = routeLoader$(() => {
    const themesData = {
        defaultTheme: "light",
        themeStyle: "modern",
        themeColor: "green",
        themeCorners: "squared",
    }

    return themesData
});

export default component$(() => {
    const themeVariants = useGetThemes();
    return (
        <>
            <ThemeMode
                defaultTheme='light'
                themeStyle={themeVariants.value.themeStyle}
                themeColor={themeVariants.value.themeColor}
                themeCorners={themeVariants.value.themeCorners}
            />
            <div
            >
                <DarkModeToggle />
                <Slot />
            </div>
        </>
    );
});
```

I wish that in the future we can create a more Qwik native solution without using dangerouslySetInnerHTML. Are we risking our apps by using dangerouslySetInnerHTML just for the sake of avoiding flashings on page refresh?

Btw, I'm using PandaCss which makes so easy to implement a multi-theme app.

**Comment by eustachi0** [comment]
I have kept digging into this topic as I wanted to find a way to avoid using `dangerouslySetInnerHTML`

And, there is a way to achieve setting theme modes entirely server-side using cookies, but it will only work by setting a default theme as initial state or theme. For my case, this is actually what I wanted. 

1. We can access the `serverData` directly from the `src/entry.ssr.tsx` file. This `serverData` is full of goodies and you can access cookies from it. The `entry.ssr.tsx` file, for what I understand, our app starts outside the browser, so here it is a common point to where our app starts? I don't if this makes sense. Anyway, this file contains a `renderToStream qwik container` like a portal in which we can add classes and/or data attributes to the <html> element, hence we can easily add a class for our theme modes, so every time the app starts or is reloaded this class will be added at the start of our app, so no flashings. We can then add a toggle button in our 'layout.tsx' or any route to switch theme modes on the client side and we can store a theme state on the browser's local storage, but once the app is reloaded or we close the browser and come back later, the class within the container in the `entry.ssr.tsx` won't be able to read local storage so this class 'hard coded' will start as its initial value, meaning that it won't be dinamic and it won't remember its last state.

2. But, instead of using local storage we can use cookies Yay! to store the state of our theme modes. Cookies can be accessed server side as well as client side. We can access cookies within the `src/entry.ssr.tsx` using the `serverData`, here is how:
```tsx
// src/entry.ssr.tsx

export default function (opts: RenderToStreamOptions) {
    // here we access the server data
    const { serverData } = opts;
    // create a variable to be used to create a class based on the cookie value
    let themeClass;

    // if the theme cookie exists, we get its value and set the themeClass variable 
    if ((serverData as any).qwikcity?.ev?.cookie?.get('theme')?.value !== undefined) {
        themeClass = (serverData as any).qwikcity.ev.cookie.get('theme').value;
    } else {
        // if it does not exist we set a default theme, I am choosing light here
        themeClass = 'light';
    }

    return renderToStream(<Root />, {
        manifest,
        ...opts,
        // Use container attributes to set attributes on the html tag.
        containerAttributes: {
            lang: 'en-us',
            'data-theme': `${themeClass}`, // if you are using data attributes. We pass here our themeClass variable and now, our class or data attribute will be dynamic
            class: `${themeClass}`, // if you want to use class
            ...opts.containerAttributes,
        },
    });
}
Please note that no theme cookie is created or set at this point. This process will only read the value of the theme cookie (if it exists) to only create or update the class or data attribute within the <html> element.
```

3. Where to create or set the theme cookie? We can use and onGet request and set the cookie within the `layout.tsx` or we can set it conditionally on the toggle component that will be in charge of switching theme modes using server$ functions.
An example of setting the theme cookie in the layout.tsx
```tsx
// src/routes/layout.tsx

export const onGet: RequestHandler = async ({ cookie }) => {
        // it will only set the cookie once if it doesn't exist with the value of the default theme we choose (I chose light)
        if (cookie.get('theme') === null) {
        cookie.set('theme', 'light', { secure: true, httpOnly: true, sameSite: 'strict', maxAge: 2592000 }); // maxAge is 30 days, you use any period of time you want
    }
}
```
However, I did not use the step above, instead I am using a toggle component to set/update the theme cookie on click.

Here is the toggle component which you can import inside the main layout or a route
```
// src/components/theme-toggle.tsx
...
import { server$ } from '@builder.io/qwik-city';

// get the theme cookie
export const getCookie = server$(function () {
    const storedThemeValue = this.cookie?.get('theme')?.value;
    return storedThemeValue
})

// set the theme cookie
export const setCookie = server$(function (themeMode: string) {
    this.cookie?.set('theme', themeMode, { secure: true, httpOnly: true, sameSite: 'strict', maxAge: 2592000 });
})

export const ThemeToggle = component$(() => {

    return (
        <>
            <button
                onClick$={async () => {
                    const themeModeValue = await getCookie();
                    // if the theme cookie doesn't exist getCookie() will be undefined, but we know that our default theme is light
                    if (themeModeValue === undefined) {
                        setCookie('dark');
                        document.documentElement.setAttribute('data-theme', 'dark');
                    } else {
                        if (themeModeValue === 'dark') {
                            setCookie('light');
                            document.documentElement.setAttribute('data-theme', 'light');
                        } else {
                            setCookie('dark');
                            document.documentElement.setAttribute('data-theme', 'dark');
                        }
                    }
                }}
            >
                Toggle
            </button>
        </>
    );
})
```

And, this is it... Now, theme modes will reload without flashings using the last theme state. It will be great if somehow within the `serverData` there would be the user's preferred color scheme (a built-in one by qwik).

I check page perf score and it is 99%.

Please feel free to add ideas that can improve this solution.
Cheers

**Comment by lieranderl** [comment]
Expanding on the information shared by @eustachi0, incorporate **Auto/Light/Dark** modes and exclusively employ server-side cookies.

```
import {
  component$,
  useSignal,
  useVisibleTask$,
  $,
  useTask$,
} from "@builder.io/qwik";
import { ThemeIconTooltip } from "./ThemeToggleIcons";  // change icons on the button logic, not shown in this example
import { server$ } from "@builder.io/qwik-city";

interface ThemeToggleBtnProps {
  size?: "xs" | "sm" | "md" | "lg";
}

// get the theme cookie
export const getThemeCookie = server$(function () {
  const storedThemeValue = this.cookie.get("theme")?.value;
  return storedThemeValue;
});

// set the theme cookie
export const setThemeCookie = server$(function (themeMode: string) {
  this.cookie.set("theme", themeMode, {
    secure: true,
    httpOnly: true,
    sameSite: "lax",
    maxAge: 2592000,
    path: "/",
  });
});

export const ThemeToggleBtn = component$<ThemeToggleBtnProps>(({ size }) => {
  const THEME_MODES = { LIGHT: "light", DARK: "dark", AUTO: "auto" };
  const selectedIcon = useSignal(THEME_MODES.AUTO);

  // handling cookies server side
  const handleCookieServerSide = $(async () => {
    let dataTheme;
    const themeModeValue = await getThemeCookie();
    if (themeModeValue !== undefined) {
      if (themeModeValue === THEME_MODES.AUTO) {
        dataTheme = THEME_MODES.DARK;
        selectedIcon.value = THEME_MODES.DARK;
      } else if (themeModeValue === THEME_MODES.DARK) {
        dataTheme = THEME_MODES.LIGHT;
        selectedIcon.value = THEME_MODES.LIGHT;
      } else if (themeModeValue === THEME_MODES.LIGHT) {
        selectedIcon.value = THEME_MODES.AUTO;
        if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
          dataTheme = THEME_MODES.DARK;
        } else {
          dataTheme = THEME_MODES.LIGHT;
        }
      }
    }
    setThemeCookie(selectedIcon.value as string);
    document.documentElement.setAttribute("data-theme", `${dataTheme}`);
  });

  useTask$(async () => {
    const themeModeValue = await getThemeCookie();
    if (themeModeValue !== undefined) {
      if (themeModeValue === THEME_MODES.AUTO) {
        selectedIcon.value = THEME_MODES.AUTO;
      } else if (themeModeValue === THEME_MODES.DARK) {
        selectedIcon.value = THEME_MODES.DARK;
      } else if (themeModeValue === THEME_MODES.LIGHT) {
        selectedIcon.value = THEME_MODES.LIGHT;
      }
    } else {
      selectedIcon.value = THEME_MODES.AUTO;
    }
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(async () => {
    window
      .matchMedia("(prefers-color-scheme: dark)")
      .addEventListener("change", (e) => {
        if (selectedIcon.value === THEME_MODES.AUTO) {
          if (e.matches) {
            document.documentElement.setAttribute(
              "data-theme",
              `${THEME_MODES.DARK}`,
            );
          } else {
            document.documentElement.setAttribute(
              "data-theme",
              `${THEME_MODES.LIGHT}`,
            );
          }
        }
      });
  });

  return (
    <div onClick$={() => handleCookieServerSide()}>
      <ThemeIconTooltip
        selector={selectedIcon.value}
        size={size}
      ></ThemeIconTooltip>
    </div>
  );
});
```

**Comment by gioboa** [comment]
@un33k can we close this issue? is it still a problem?

**Comment by un33k** [comment]
I didn't see a PR to address this issue.  Qwik folks can close this at will.

**Comment by wmertens** [comment]
I think this can be done without server intervention all you need to do is run a script in head that looks at a cookie and adds a class name to the HTML tag.

**Comment by wmertens** [comment]
That's indeed the way it's implemented in the qwik site: https://github.com/BuilderIO/qwik/blob/66b823bbb8801238d7ad47dd6ea0c7aa3c200f7b/packages/docs/src/components/router-head/theme-script.tsx#L4

**Comment by lieranderl** [comment]
I have created a Qwik-Theme-Toggle Library that utilizes only localStorage, as recommended by @wmertens  It is compatible with Tailwind (using the "dark" class) and also supports DaisyUI (via the data-theme attribute).
[qwik-theme-toggle](https://www.npmjs.com/package/qwik-theme-toggle)
[Demo video](https://www.youtube.com/watch?v=51iWIiZFCQY)
