### ISSUE TITLE
[🐞] Tutorial site REPL is throwing error

### ISSUE THREAD

**Issue by jerimiahwelch** [BuilderIO/qwik#3412]
### Which component is affected?

Qwik Playground

### Describe the bug

In an incognito Chrome session on this page:

https://qwik.builder.io/tutorial/props/basic/

I am seeing this error:

ReferenceError: process is not defined at globalThis.qwikOptimizer.module.exports.exports (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:1752:86) at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:2382:2) at g (https://qwik.builder.io/repl/repl-sw.js:1:377) at async B (https://qwik.builder.io/repl/repl-sw.js:1:1086) at async F (https://qwik.builder.io/repl/repl-sw.js:12:5469)

<img width="1114" alt="Screenshot 2023-03-17 at 7 22 20 AM" src="https://user-images.githubusercontent.com/1224514/225933798-9873a0bf-2c95-4165-b714-934659773e8d.png">

### Reproduction

https://qwik.builder.io/tutorial/props/basic/

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 166.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Chrome Canary: 113.0.5657.0
    Firefox: 92.0.1
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @builder.io/qwik: 0.21.0 => 0.21.0 
    @builder.io/qwik-city: 0.5.3 => 0.5.3 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

**Comment by manucorporat** [comment]
Should be fixed already!
