### ISSUE TITLE
[📖] Discord invitation is expired

### ISSUE THREAD

**Issue by tinkerbaj** [BuilderIO/qwik#3430]
### Suggestion

Just qwik notice the discord link on the website is expired.

**Comment by zanettin** [comment]
Hi @tinkerbaj 👋 
Thanks for the info 🙏  what is the info you get when using the link?
I am still landing on the #welcome channel on discord

**Comment by tinkerbaj** [comment]
I was getting that is expired, now it is ok :smiley:
