### ISSUE TITLE
[📖] Documentation on qwik.builder.io is out of sync?

### ISSUE THREAD

**Issue by michaelwu0505** [BuilderIO/qwik#3434]
### Suggestion

I can find "useEndpoint" from search button, but the resulting documentation url does not have information regarding "useEndpoint".

Steps to reproduce:

1. Goto https://qwik.builder.io/qwikcity/api/, click search button and search for "useEndpoint".

2. The first result is a link to the API reference "\#useEndpoint()", which is the following link:
https://qwik.builder.io/qwikcity/api/#useendpoint

3. However, there is no "useendpoint" entry on https://qwik.builder.io/qwikcity/api

**Comment by zanettin** [comment]
Hi @michaelwu0505 👋 
Thanks for letting us know about this! looks for me like the index no longer gets updated properly.

**Comment by michaelwu0505** [comment]
For anyone who is curious, I stumble upon "useEndpoint" in the following youtube video:

"[Exploring Qwik City w/ Adam Bradley & Manu Martínez-Almeida](https://youtube.com/live/XoeJisRJjlo?si=EnSIkaIECMiOmarE&t=3947)"

From my research, I believe that beginning from qwik v0.22.0, we should be using routeLoader$().
https://qwik.builder.io/docs/route-loader/

**Comment by zanettin** [comment]
Thanks again @michaelwu0505 🙏  since qwik was under heave development with many API changes, some recordings are out-of-date now. but imo still worth to watch it, since they explain the philosophy pretty well.
BTW: i am no longer able to find `useEndpoint` in the search so i'll close this issue 🎉
