### ISSUE TITLE
[🐞] useContextProvider does not support normal functions

### ISSUE THREAD

**Issue by mailok** [BuilderIO/qwik#3437]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am trying to pass a function to the `useContextProvider` hook but it throws an error saying that the function is not serializable.

```
Value cannot be serialized because it's a function named "foo". You might need to convert it to a QRL using $(fn):
const foo = $(function foo() {});
```

Maybe the error is in the documentation, when it says this: `"you can provide any data type like Qwik's useSignal, useStore, Array, Objects."` 

If it is indeed a limitation, it would be helpful to have it clearly stated in the documentation. However, I strongly believe that having this feature would be highly beneficial.

### Reproduction

https://stackblitz.com/edit/qwik-starter-pqyuao?file=package.json

### Steps to reproduce

I got the same error with these 3 ways of using `useContextProvider`:

1:
```
function foo() {
  console.log('lorem ipsum');
}

 useContextProvider(MyContext, {
    someFn: foo,
  });
```

2:
```
 useContextProvider(MyContext, {
    someFn: () => {
      console.log('lorem ipsum');
    },
  });
```

3:

```
function foo() {
  console.log('lorem ipsum');
}
 useContextProvider(MyContext, foo);
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.23.0 => 0.23.0 
    @builder.io/qwik-city: 0.6.5 => 0.6.5 
    undici: ^5.15.2 => 5.21.0 
    vite: 4.2.0 => 4.2.0
```

**Comment by manucorporat** [comment]
It's not about useContextProvider(), it's about a function can not be serialized, however the error, tells you to wrap it with `$()`

```tsx
  useContextProvider(MediaPlayerContext, {
    someFn: $(foo),
  });
```
this works!

**Comment by mailok** [comment]
@manucorporat I understand. Thank you very much for the clarification.
