### ISSUE TITLE
[🐞] Routes with Arabic letters report 404 Not Found error

### ISSUE THREAD

**Issue by mahmoudajawad** [BuilderIO/qwik#3438]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Using Arabic (I'm assuming any non-latin) letters as route name results in 404 Not Found error.

### Reproduction

https://stackblitz.com/edit/qwik-starter-vahxlv?file=src/routes/عربي/index.mdx

### Steps to reproduce

- Run the webcontainer.
- Navigate to `/عربي`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^0.22.1 => 0.22.1 
    @builder.io/qwik-city: ^0.6.2 => 0.6.5 
    undici: ^5.16.0 => 5.20.0 
    vite: ^4.0.4 => 4.1.4
```

### Additional Information

I've not needed this before so I don't know if this is a long-standing issue or a recently introduced bug, however I tested it across two environments (Qwik v0.19, 0.22) and all reported same. I'm also not sure if Qwik City is not intended to deal with non-latin letters in routes, or whether this is a Vite behaviour (I've never used Vite before Qwik so I don't understand its limitations).

**Comment by manucorporat** [comment]
Wanna try making a PR solving the issue? can help u!

**Comment by mahmoudajawad** [comment]
Definitely, @manucorporat, just point me to the area of the codebase I need to look at, please.

**Comment by manucorporat** [comment]
Might be related with https://github.com/BuilderIO/qwik/issues/1999

**Comment by manucorporat** [comment]
Might be related: https://github.com/BuilderIO/qwik/issues/2441

**Comment by mahmoudajawad** [comment]
@manucorporat I assume it is. I've been digging hard to figure out which part of qwik-city is responsible for processing requested URI and translate it into a static path, and if what I am seeing is true it is that qwik-city generates route ahead-of-time, and doesn't do a per-request check? I've been trying to figure out what the file `https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/buildtime/runtime-generation/generate-routes.ts` does.

Then there's `https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/buildtime/routing/parse-pathname.ts` which seems to have the patterns to match URI, however, they are fine. Finally, there's `https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/buildtime/routing/resolve-source-file.ts` which seems to figure out how to build the final output by figuring out all related layouts. 

At this point I'm trying to understand what first file is doing, and then move to last to see whether any of the loops or the function invoked are the reasons for non-latin characters failing to be understood.

I would appreciate any pointers that might help me fix this.
