### ISSUE TITLE
[🐞] Tutorial site is throwing error

### ISSUE THREAD

**Issue by jerimiahwelch** [BuilderIO/qwik#3442]
### Which component is affected?

Qwik Playground

### Describe the bug

We are seeing this 404 and this REPL error on the tutorial site.

https://qwik.builder.io/tutorial/welcome/overview/

<img width="1679" alt="Screenshot 2023-03-20 at 7 04 41 AM" src="https://user-images.githubusercontent.com/1224514/226364348-91d25f07-54f6-4508-b8db-6147245bea8e.png">

<img width="1680" alt="Screenshot 2023-03-20 at 7 04 48 AM" src="https://user-images.githubusercontent.com/1224514/226364396-7f0a3674-eb99-4e62-b20b-784f829e1dea.png">

### Reproduction

https://qwik.builder.io/tutorial/welcome/overview/

### Steps to reproduce

Visit https://qwik.builder.io/tutorial/welcome/overview/ 

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 166.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Chrome Canary: 113.0.5657.0
    Firefox: 92.0.1
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @builder.io/qwik: 0.21.0 => 0.21.0 
    @builder.io/qwik-city: 0.5.3 => 0.5.3 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

**Comment by manucorporat** [comment]
Shoudl be fixed soon!
