### ISSUE TITLE
[🐞] JavaScript chunks from third party package cannot be referenced

### ISSUE THREAD

**Issue by fabian-hiller** [BuilderIO/qwik#3471]
### Which component is affected?

Qwik Runtime

### Describe the bug

When I install my package `@modular-forms/qwik`, import it and start the dev server, the chunks referenced in HTML at SSR cannot be loaded. If I navigate client-side, the error does not occur anymore.

<img width="861" src="https://user-images.githubusercontent.com/35291865/226761431-7ec863bd-76ea-45ab-94c1-4431c49a101f.png">

Furthermore I noticed that if I edit the code in the `node_modules` directory of another package, e.g. `@qwik-ui/headless`, and insert for example the following code, it can be loaded after restarting the server via the following URL. However, the same does not work for my package. 

```js
const Button2 = /* @__PURE__ */ componentQrl(inlinedQrl((props) => {
  return /* @__PURE__ */ jsx("button", {
    ...props,
    children: /* @__PURE__ */ jsx(Slot, {}, "NG_0")
  }, "NG_1");
}, "Button2_component_DXPsA0vE3k4"));
```

```txt
http://localhost:5173/src/button2_component_dxpsa0ve3k4.js
```

Currently I have no idea where the error is. Is it a bug in Qwik or is it the build step or the `package.json` of my package?

### Reproduction

https://stackblitz.com/edit/modular-forms-qwik-y4a6ir?file=package.json,src%2Froutes%2Flogin%2Findex.tsx

### Steps to reproduce

Open the StackBlitz link. After the login form is displayed on the right side, check the logs in the browser console. Now click on the "Submit" button to see that nothing happens because the appropriate JavaScript chunks cannot be loaded. Then navigate to the payment form and then back again and repeat the process.

### System Info

```shell
I think that this information is not relevant here.
```

**Comment by manucorporat** [comment]
In order to make a qwik library you need to follow a set of rules, our fault, that we havent documented this! i will work on it.
But we have a library starter
https://github.com/BuilderIO/qwik/blob/main/starters/apps/library/package.json

Please follow the same, including naming it `index.qwik.mjs` it will work that way:
```
  "main": "./lib/index.qwik.mjs",
  "qwik": "./lib/index.qwik.mjs",
  "types": "./lib-types/index.d.ts",
  "type": "module",
  "exports": {
    ".": {
      "import": "./lib/index.qwik.mjs",
      "require": "./lib/index.qwik.cjs",
      "types": "./lib-types/index.d.ts"
    }
  },
```
dont add more fields, it will just confuse the bundlers, this is the recommended setup!

**Comment by fabian-hiller** [comment]
Thanks a lot for your quick help! I'll test it right away.

**Comment by NiklasPor** [comment]
I'm stumbling over the same issue. Any insights on how you'd set it up to support multiple entrypoints @manucorporat ?
I really don't want to stuff all of the code into a single entrypoint 🥲

**Comment by NiklasPor** [comment]
FYI for anyone stumbling over this with multiple entrypoints, it seems like updating all of them to be in the format `*.qwik.(mjs|cjs)` is enough 👋
