### ISSUE TITLE
Prefetching of dependencies

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#348]
Just noticed that there is a small lag on [qwik.builder.io](http://qwik.builder.io/) because we don’t do any prefetching. I think we need to start doing pre-fetching. Just like we have <Qwikloader>  component we should have <Qwikfetch> component which will start doing prefetching. Then each `q:container` publishes the set of resources which it would like to have prefetched through `q:prefetch` which the <Qwikfetch> processes in a web-worker. (we already have parts of it here: https://github.com/BuilderIO/qwik/blob/main/src/prefetch-worker.ts we just need to clean it up.
The container can then publish a set of resources that it wants the <Qwikfetch> to load, and the <Qwikfetch> can do it’s magic.

The alternative is to bake this into `<Qwikloader>` at the cost of size...

**Comment by manucorporat** [comment]
- Good default, prefetch all chunks
- Include prefetch metadata in q-symbols.json (bundle size, bundle type)

**Comment by kylecordes** [comment]
I noticed the dev-time HTML output includes this construct:

```
<link rel="modulepreload" href="/q-4fe4b1ee.js">
```

Maybe the production output could do the same, for the set of JS resources deemed most likely to be needed? Less complexity/codesize than even a pretty simple web worker?

(I have not tested whether LightHouse or similar tools correctly ignore rel=modulepreload requests when computing whether the page is read.)

**Comment by mhevery** [comment]
This is now working.
