### ISSUE TITLE
[🐞] Qwik City build error when using Modular Forms

### ISSUE THREAD

**Issue by fabian-hiller** [BuilderIO/qwik#3483]
### Which component is affected?

Qwik Runtime

### Describe the bug

When I run `npm run preview`, I get the following error: TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "@qwik-city-plan" is not a valid package name imported from /Users/…/qwik-app/node_modules/@builder.io/qwik-city/index.qwik.mjs

The problem occurs only when I import my package `@modular-forms/qwik`. However, I suspect that the problem is more on the part of Qwik.

https://github.com/fabian-hiller/modular-forms/issues/28

### Reproduction

https://stackblitz.com/edit/modular-forms-qwik

### Steps to reproduce

Open the StackBlitz link and run `npm run preview`. The error should now be displayed in the console.

### System Info

```shell
I think that this information is not relevant here.
```

**Comment by RBleyenberg** [comment]
I think i have somewhat the same issue atm when trying out either preview build or build

`Oops! Something went wrong! :(

ESLint: 8.36.0

TypeError: Cannot read properties of undefined (reading 'name')
Occurred while linting C:\Users\Bleyenberg\IdeaProjects\dare-qwik-2\src\routes\auth\login\index.tsx:56
Rule: "qwik/valid-lexical-scope"`

and line 56 is     

`<Form id="login-form" onSubmit$={loginSubmit}>`

hope it help abit more with debugging

**Comment by fabian-hiller** [comment]
I believe that your error @RBleyenberg is related to Modular Forms and not Qwik. Can you create an issue on Modular Forms and share more of your code so I can investigate the problem? https://github.com/fabian-hiller/modular-forms/issues/new

**Comment by ulic75** [comment]
Possibly related to #3297

**Comment by lbensaad** [comment]
Any fix for this error. I am using modular-forms and  get this error with `pnpm build`

**Comment by fabian-hiller** [comment]
The error seems to be fixed. However, I now get a different error when I enter `pnpm preview`:

```bash
TypeError: Cannot read properties of undefined (reading 'object')
```

Since Qwik unfortunately gives me no further information. I can not say at the moment what the origin is.

**Comment by lbensaad** [comment]
I am still getting the same error with both pnpm build and pnpm preview.
@fabian-hiller how did you fix it?

**Comment by fabian-hiller** [comment]
I have updated Qwik and Qwik City to v0.100.0

**Comment by lbensaad** [comment]
yes I also updated to version 0.100.0 but I still get this error:
```
error during build:
TypeError [PLUGIN_ERROR]: Invalid module "@qwik-city-plan" is not a valid package name imported from node_modules/.pnpm/@builder.io+qwik-city@0.100.0_@builder.io+qwik@0.100.0/node_modules/@builder.io/qwik-city/index.qwik.mjs
    at new NodeError (node:internal/errors:399:5)
    at parsePackageName (node:internal/modules/esm/resolve:722:11)
    at packageResolve (node:internal/modules/esm/resolve:745:5)
    at moduleResolve (node:internal/modules/esm/resolve:843:20)
    at defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:416:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by fabian-hiller** [comment]
Thank you @manucorporat

**Comment by lbensaad** [comment]
I am still getting the error using qwik 0.101.0 and modular forms 0.8.0 when building
@fabian-hiller and @manucorporat: Could you please help me with it, I am not able to build sine two weeks now.
```
error during build:
TypeError [PLUGIN_ERROR]: Invalid module "@qwik-city-plan" is not a valid package name imported from /home/bml/dev/bladidev/web/node_modules/.pnpm/@builder.io+qwik-city@0.101.0_@builder.io+qwik@0.101.0/node_modules/@builder.io/qwik-city/index.qwik.mjs
    at new NodeError (node:internal/errors:399:5)
    at parsePackageName (node:internal/modules/esm/resolve:722:11)
    at packageResolve (node:internal/modules/esm/resolve:745:5)
    at moduleResolve (node:internal/modules/esm/resolve:843:20)
    at defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:416:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)

 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by fabian-hiller** [comment]
I have no control over this and the most I can do is update the Qwik and Qwik City version at Modular Forms and release a new build version on npm. Can you provide a minimal reproduction via StackBlitz or GitHub? And if @manucorporat doesn't respond you might have to create a new issue.

**Comment by fabian-hiller** [comment]
@lbensaad I believe the problem has been fixed but no new Qwik version has been released yet. Probably the problem will be fixed in the next Qwik version.

**Comment by bbigras** [comment]
Is there an easy way for us mortal to try the unreleased version?

**Comment by lbensaad** [comment]
@fabian-hiller please try this at [StackBlitz](https://stackblitz.com/edit/qwik-starter-wuycwb?file=src/routes/index.tsx)
```pnpm start``` works fine  but ```pnpm build``` fails with that error
Please check the form and the InputField components and tell me what i am doing wrong!

**Comment by fabian-hiller** [comment]
I have the same problem with StackBlitz. I recommend to wait for the next version of Qwik.

**Comment by lbensaad** [comment]
So I hope that @manucorporat  will have a look at it

**Comment by ulic75** [comment]
I'm pretty certain it's because the fix isn't part of a released version yet. Just have to have patience.

**Comment by rherwig** [comment]
I am experiencing that same issue now, using qwik 1.26.0 and modular forms 0.20.0.
Why is this closed? Seems like, the issue never resolved.

**Comment by fabian-hiller** [comment]
@rherwig should be solved. Please read through these comments:

- https://github.com/BuilderIO/qwik/issues/4789#issuecomment-1658536062
- https://github.com/fabian-hiller/modular-forms/issues/115#issuecomment-1658839684
