### ISSUE TITLE
[🐞] onInput$ event listener is added several times

### ISSUE THREAD

**Issue by fabian-hiller** [BuilderIO/qwik#3493]
### Which component is affected?

Qwik Runtime

### Describe the bug

When a component is re-rendered, the `onInput$` event listener is added each time without overwriting or removing the old one. This results in the event listener being executed 6 times after the component has been re-rendered 5 times.

### Reproduction

https://stackblitz.com/edit/qwik-starter-gps1aj?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Open StackBlitz link and wait until preview is displayed
2. Enter something in the input element
3. Check the `onInput$` counter

Normally, the counter should be at 5 after 5 inputs. However, the counter is at 15.

### System Info

```shell
I think that this information is not relevant here.
```

**Comment by manucorporat** [comment]
SHould be fixed in main already!
