### ISSUE TITLE
[✨] Support "NaN" for value of <input />

### ISSUE THREAD

**Issue by fabian-hiller** [BuilderIO/qwik#3502]
### Is your feature request related to a problem?

According to TypeScript, the `value` attribute of the `<input />` element supports the `number` data type. However, the following warning is displayed when passing `NaN`: "The specified value "NaN" cannot be parsed, or is out of range."

### Describe the solution you'd like

Support parsing `NaN` to an empty string.

### Describe alternatives you've considered

Leave it to the user to "parse" `NaN`:

```tsx
<input type="number" value={isNaN(value) ? "" : value} />
```

**Comment by manucorporat** [comment]
This is outside the scope of qwik to solve, thgis warning is coming directly from the browser.
<img width="770" alt="Screenshot 2023-03-24 at 14 47 34" src="https://user-images.githubusercontent.com/127379/227538585-afcc9095-6191-4f69-9c8b-4e209b189f8d.png">

I think we should default to whatever the browser does when it gets this value.
