### ISSUE TITLE
[🐞] Lite components don't have key in types

### ISSUE THREAD

**Issue by jweb89** [BuilderIO/qwik#3506]
### Which component is affected?

Qwik Runtime

### Describe the bug

When using a lite component typescript throws an error if trying to pass key when mapping over an array.

### Reproduction

https://stackblitz.com/edit/qwik-starter-mwjway?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Open stackblitz and view router/index.tsx in editor

### System Info

```shell
 System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: latest => 0.23.0 
    @builder.io/qwik-city: latest => 0.6.6 
    undici: ^5.16.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

### Additional Information

I tried to make the change necessary for this but was having trouble about where to put the type and it was causing other build errors so opening an issue for someone more familiar with the jsx types to fix

**Comment by phcoliveira** [comment]
@jweb89, perhaps this is not a bug. Lite components do not have a [host element](https://qwik.builder.io/docs/components/lite-components/) (whatever that is). So this might be by design.
