### ISSUE TITLE
[✨] Add a hook that runs on the client and before rendering

### ISSUE THREAD

**Issue by lbensaad** [BuilderIO/qwik#3519]
### Is your feature request related to a problem?

I am using Qwik to develop SPA, so most of my routes are basically templates that needs to be filled with data based on the current logged in user. In the first page load I have to fetch the current user from the server. If no user found I redirect to the login route. 
The problem is that there is no way to do the fetch before the rendering in the client. There is only 'useVisibleTask$' so the user will see the component and if he is not logged in will be redirected to login. this is not user friendly.

### Describe the solution you'd like

It will be better if we have a hook like `useTask$` named for example `useClientTask$` that will run on the client before the render of the component.

### Describe alternatives you've considered

I am using `useVisibleTask$` but it is not user friendly to show the user empty components then redirect him if he is not logged in.
I also tried `useTask$` but it is not useful because it does not run on the client.

### Additional context

The documentation for Lifecycles [here](https://qwik.builder.io/docs/components/lifecycle/#usetask) says:
```
Notice that useTask$() runs BEFORE the actual rendering and in the server, 
so if you need to do any DOM manipulation, use useVisibleTask$() instead, 
which runs on the client after rendering.
```
So there is no hook on the client before rendering.

**Comment by shairez** [comment]
adding to what @jordanw66 said - the boolean variable `isBrowser` together with `useTask$` achieves running client specific code just before rendering.

But yeah, if you need to fetch data at a root level - loaders should be your solution

**Comment by lbensaad** [comment]
Thanks @jordanw66 and @shairez. 
I understand that `routeLoader` is executed on the server, so can not use it in my case because my web app is SSG SPA that fetches data from a go service.
I am building a SAAS, most pages are private except for /login and /register. When there is a page load I fetch user data from server and if the user is logged in and he is vising /login or /register then he will be redirected to /dash, if he is not logged in and visiting /dash he will be redirected to /login

What is the best way to achieve this?

**Comment by lbensaad** [comment]
Ok, thanks @jordanw66
