### ISSUE TITLE
[🐞] npm create qwik@latest freezes for 1 minute without any UI update

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#3521]
### Which component is affected?

Starters / CLI

### Describe the bug

After the "Happy Coding" message, the CLI froze for 55 seconds without any indication as to what is going on.

<img width="504" alt="CleanShot 2023-03-25 at 13 29 12@2x" src="https://user-images.githubusercontent.com/1393142/227729752-95ce992a-dbf1-4a4c-9ac0-41f3c06034c7.png">

### Reproduction

N/A

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 823.56 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.asdf/installs/nodejs/17.4.0/bin/node
    Yarn: 1.22.15 - ~/.asdf/installs/nodejs/17.4.0/bin/yarn
    npm: 8.3.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.110
    Firefox: 109.0.1
    Safari: 15.2
```
```


### Additional Information

_No response_

**Comment by manucorporat** [comment]
it was running `npm install`, but it does show a message showing "Installing"

**Comment by samijaber** [comment]
I selected "no" for "would you like to install npm dependencies"

**Comment by zanettin** [comment]
thanks for reporting this 🙏  PR is created to solve this.
