### ISSUE TITLE
[🐞] Fresh repo with "npm create qwik@latest" crashes on `pnpm build` 

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#3522]
### Which component is affected?

Starters / CLI

### Describe the bug

- run `npm create qwik@latest`
- cd to directory
- `pnpm install`
- `pnpm build`

I get an `exit code 1` without any details:

<img width="364" alt="CleanShot 2023-03-25 at 13 43 14@2x" src="https://user-images.githubusercontent.com/1393142/227730421-5492a640-c782-4675-b079-3aa1cdc99018.png">

Note that `pnpm dev`, and all other `pnpm build.*` commands seem to work fine

### Reproduction

https://github.com/samijaber/qwik-pnpm-bug

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 79.20 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.asdf/installs/nodejs/17.4.0/bin/node
    Yarn: 1.22.15 - ~/.asdf/installs/nodejs/17.4.0/bin/yarn
    npm: 8.3.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.110
    Firefox: 109.0.1
    Safari: 15.2
  npmPackages:
    @builder.io/qwik: 0.24.0 => 0.24.0
    @builder.io/qwik-city: ~0.7.0 => 0.7.0
    undici: 5.21.0 => 5.21.0
    vite: 4.2.1 => 4.2.1
```
```


### Additional Information

_No response_

**Comment by samijaber** [comment]
I fixed this by upgrading

- from NodeJS `v17.4` and pnpm `6.11.0` 
- to NodeJS `v18.13.0` and pnpm `7.26.2`

So I guess it works on latest version of pnpm + NodeJS! Not sure if it's worth keeping this open, will leave it up to you :)

**Comment by datner** [comment]
@zanettin 
This exact issue keeps happening to me with versions newer than both node 18.13 and pnpm 7.26.

Specifically
node: 18.16.0
pnpm: 8.5.1

This is consistently reproducible
