### ISSUE TITLE
[🐞] Missing attributes for event handlers in some elements

### ISSUE THREAD

**Issue by astraldev** [BuilderIO/qwik#3525]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am using mitosis as a build tool to get an output for qwik and it seems to compile with one issue, there is no `onClick$` available for the div element and I cant seem to pass a normal event using onClick because it wouldn't be serialized

### Reproduction

https://stackblitz.com/edit/qwik-starter-4gwtot?file=src%2Froutes%2Findex.tsx

### System Info

```shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
    Memory: 510.73 MB / 5.74 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Firefox: 111.0
```

### Additional Information

Div element or other display elements should have | support the onClick$ attribute

**Comment by manucorporat** [comment]
This line is invocating the console log directly:
```tsx
    <div onClick$={console.log('Hello, the main div has been clicked')}>
```
instead, it needs to be wrapped in an arrow function:
```tsx
    <div onClick$={() => console.log('Hello, the main div has been clicked')}>
```

Typescript is even complaining about it:
<img width="608" alt="Screenshot 2023-03-26 at 11 24 02" src="https://user-images.githubusercontent.com/127379/227766670-e7514293-bceb-4b68-bf2d-ca789d5ee71f.png">

**Comment by astraldev** [comment]
Oh thank you very much
