### ISSUE TITLE
[🐞] useComputed returns Signal<Promise<string>> while it should return Signal<string>

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#3528]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm creating an autocomplete component with a custom `display$` function to display the selected value as a string. I use `useComputed$` to trigger the `display$` function when the form's value has changed (when the option has been clicked.

The issue is that `useComputed$` returns `Readonly<Signal<Promise<string>>>` instead of `Readonly<Signal<string>>`
```jsx
interface AutocompleteProps<T = any> {
  display$: QRL<(value: T) => string>;
}
export const Autocomplete = component$((props: AutocompleteProps) => {
  const value = useSignal();
  const inputValue = useComputed$(() => props.display$(value)); <-- Whould be Signal<string>
  return <>
    <input type="search" bind:value={inputValue} /> <-- This is not working as expected Signal<string>
    // options here
  </>
})

```

### Reproduction

https://stackblitz.com/edit/qwik-starter-cx8rdk?file=src/routes/index.tsx

### System Info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 18.86 GB / 31.71 GB
  Binaries:
    Node: 16.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1095.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^0.24.0 => 0.24.0
    @builder.io/qwik-city: ^0.7.0 => 0.7.0
    undici: 5.21.0 => 5.21.0
    vite: 4.2.0 => 4.2.0
```

**Comment by the-r3aper7** [comment]
Hi @GrandSchtroumpf, currently `useComputed$` is not documented in docs, Qwik Team is working on it. Meanwhile it is suggested that you should try `useTask$` to achieve the same. If there is any mutation inside the `useComputed$` it is considered as anti-pattern in definition of Qwik Core. So, it is suggested to use `useTask$`

here is the working solution for the above code:

```tsx
export default component$(() => {
  const display$ = $((value: string) => `Hello World ${value}`);
  const valueSignal = useSignal<string>("");

  useTask$(async ({ track }) => {
    track(() => valueSignal.value)
    const data = await display$(valueSignal.value);
    console.log(data);
  })

  return <>
    <input type="search" bind:value={valueSignal} />;
    <p>{valueSignal}</p>
  </>
});
```

Hope its work for you😊.

**Comment by GrandSchtroumpf** [comment]
Thx @the-r3aper7 for the answer. I think my comment was not clear enough. The `display$` is not a mutation, it's a pure function that would transform the input into a string. 
It's only a type issue actually, the code is working fine if I do `as any` after calling `display$`.

**Comment by GrandSchtroumpf** [comment]
Hi @jordanw66 thx for the answer. Maybe my example with `bind:value` is not good but it doesn't change the type issue.
The useComputed$ returns a `Signal<T>`, event if it's filled after some time it should still return a `Signal<T>` not `Signal<Promis<T>>`, the code is working like that.
I've updated my example to use a simple setTimeout wrapped in a Promise so you can see it's working: 
https://stackblitz.com/edit/qwik-starter-cx8rdk?file=src/routes/index.tsx

```jsx
const origin = useSignal('Hello');
const inputValue = useComputed$(() => {
  return new Promise((res) => {
    setTimeout(() => res(origin.value + ' World'), 2000);
  }) as any;  // If you remove this any there is a type issue while there is no javascript error
});
return <p>{inputValue.value}</p>;
```

**Comment by GrandSchtroumpf** [comment]
I think this is the same behavior as the `routerLoader$`. When you do a query to the database to access a route you'll do a Promise in the `routerLoader$` and the SSR will wait until this is done to display the HTML. 
There is a video about [streaming html](https://www.youtube.com/watch?v=yVOI81GKZBo), that show a similar behavior also.

In my case I want to let a user select any type of object in an autocomplete (let's say a `Movie`) and provide a custom transform function to display it as a string in an input. This is similar to the `displayWith` in the angular material's [autocomplete component](https://material.angular.io/components/autocomplete/overview#setting-separate-control-and-display-values).
```jsx
interface Movie {
  id: string;
  title: string;
  boxOffice: number;
  ...
}
export default component$(() => {
  return <Autocomplete>
    <SearchInput display$={(movie) => movie.title} onSeach$={(search) => filterOptions(search)} />
    <Listbox>
      <Option value={movie1} key={movie1.id}>{movie1.title}</Option>
    </Listbox>
  </Autocomplete>
})
```
When I click on the `Option` I want to keep the `movie1` as a value, but as it's an object, I want to display only the title in the `SearchInput`, so I use `display$` for that : 
```jsx
export const SearchInput = component$(({ display$, onSearch$ }: SearchInputProps) => {
  const { value } = useContext(AutocompleteContext); // <- the value here would be the movie1
  const inputValue = useComputed$(() => display$(value)); // <- I transform the value into a string
  return <input type="search" value={inputValue} onInput={(_, el) => onSearch$(el.value)} ... />
})
```
I need `display$` to be a `QRL<(value: T) => string>` function else I wouldn't be able to put it inside `useComputed$` as function are not serializable. But even if I used `NoSerialized`, I still think the `useComputed$` should manage Promises as every operation in Qwik is a Promise and Signal are reactive. 

Maybe a better solution would be : 
- If `useComponented$` callback is synchrone return `Signal<T>`
- If `useComponented$` callback is asynchrone return `Signal<T | undefined>` like that by default it's undefined and when the promise resolved it's T.

@manucorporat jordan suggested me to tag you on this issue, do you have an opinion ?

**Comment by GrandSchtroumpf** [comment]
Thx for the feedback on my example, but as you can see in it the value of an option can be anything (not only a string), and therefore I need a way to transform the selected value into a string: the `display$` function.

But let's keep this example aside as I feel it brings more confusion than anything. From what I understand, `useComputed$` is a way to react to a change of a signal to transform it i to something else, like `map` or `swithMap` in rxjs. So to me it makes sense to support `Promise` as an output because :
- this is a behavior we can already see in other part of the lib (`routerLoader$` for example)
- it is already working except for the lack of string typing
- as `useComputed$` requires a QRL callback, if we want it use any transformation function from the outside it has to be a QRL wrapped function which return a Promise.
- it enables great behavior like debouncing or throttling in a very elegant way.

**Comment by Campalo** [comment]
Hello, I'm also using the `useComputed` function in my project to filter a list dynamically:
```jsx
const filters = useContext(FilterContext);
const list = useComputed$(() => queryList$(filters) as any);
if (!list.value) return <p>Loading</p>;
if (!list.value.length) return <p>Empty</p>;
return <ul>
  {list.value.map(item => <Item key={item.id} item{item}/>)}
</ul>
```
The code works well, except that I have to use `as any` which is always annoying^^ It would be great to update the type to reflect the behavior :)
