### ISSUE TITLE
[🐞] Can't store JSX in Signal

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#3530]
### Which component is affected?

Qwik Runtime

### Describe the bug

I expect this to work:
```typescript
import { component$, useSignal } from '@builder.io/qwik';

export default component$(() => {
  const jsx = useSignal(<div>hello</div>);
  return <div>{jsx.value}</div>;
});
```

Bet I get `[object Object]` when rendered.

### Reproduction

stackblitz.com/edit/qwik-starter-58wnjg

### System Info

```shell
na
```

**Comment by rjsdnql123** [comment]
@mhevery  Do you mind if I take care of this?

**Comment by mhevery** [comment]
Go for it!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gioboa** [comment]
> @mhevery Do you mind if I take care of this?

Hi @rjsdnql123 do you have any news on this?
