### ISSUE TITLE
[🐞] useNavigate not functioning well on production

### ISSUE THREAD

**Issue by astraldev** [BuilderIO/qwik#3537]
### Which component is affected?

Qwik Runtime

### Describe the bug

Whenever I try to programmatically navigate to the same route with parameters e.g  from `site-name.com/login` to `site-name.com/login?id=xxx`, the navigation works but the location doesn't change. Also, It works when I try it locally but doesn't when I'm serving on the cloud. Any thoughts?? 

### Reproduction

https://stackblitz.com/edit/qwik-starter-dkhr7z?file=src%2Froutes%2Fdemo%2Fflower%2Fflower.css,src%2Froutes%2Fdemo%2Fflower%2Findex.tsx

### Steps to reproduce

happens after deploying with express `npm run build && node server/entry.express`

### System Info

```shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
    Memory: 1.49 GB / 5.74 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Firefox: 111.0
  npmPackages:
    @builder.io/eslint-plugin-mitosis: ^0.0.14 => 0.0.14 
    @builder.io/qwik: ~0.24.0 => 0.24.0 
    @builder.io/qwik-city: 0.7.0 => 0.7.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

### Additional Information

Any workaround on changing the browser url or so???....

**Comment by jessezhang91** [comment]
I'm also seeing this with the `Link` component which uses `useNavigate` underlying.

**Comment by adamdbradley** [comment]
This fix should address the problem: https://github.com/BuilderIO/qwik/pull/3810 Thanks for opening the issue.
