### ISSUE TITLE
[🐞] hash URL in anchor tag reload the page

### ISSUE THREAD

**Issue by O-Hooman** [BuilderIO/qwik#3541]
### Which component is affected?

Qwik Runtime

### Describe the bug

So when I create an anchor tag with hash href instead goto id or change the URL with hash it change the URL and reload the page

### Reproduction

https://stackblitz.com/edit/qwik-starter-42bkde

### Steps to reproduce

it happens in run dev and build when I click URL with href hash

### System Info

```shell
OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 80.38 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.24.0 => 0.24.0 
    @builder.io/qwik-city: ~0.7.0 => 0.7.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

### Additional Information

it happens after upgrade to qwik 0.21.0 (it still happen on 0.24.0), last version before I'm using 0.24.0 or 0.21.0 is 0.17.4
it's working normally when I disabled the javascript on chrome

**Comment by O-Hooman** [comment]
04/06/2023 - tried it on 0.100.0 and it still happen

**Comment by awesome31** [comment]
Having a similar problem. Please fix it asap :(

**Comment by gioboa** [comment]
This is fixed, I close it. Thanks @O-Hooman for opening this issue.
