### ISSUE TITLE
[🐞] useSignal update within useResource$ causes serialize/DOM mismatch

### ISSUE THREAD

**Issue by intellix** [BuilderIO/qwik#3544]
### Which component is affected?

Qwik Runtime

### Describe the bug

If you update the value of a signal inside useResource$, the new value will be serialised with the DOM, but the DOM isn't actually updated. 

This is a fairly minimal example to show the problem which I'm seeing inside useResource$. 

I've also got another problem with useTask$ updating a signal and not seeing it update within the DOM from the browser side.

### Reproduction

https://stackblitz.com/edit/qwik-starter-z9sqrq

### System Info

```shell
Browser: Chrome v111
```

### Additional Information

I notice the same thing with useVisibleTask$ when using async/await. Not sure if it's meant to work but if not, it would be a nice addition to the docs

**Comment by intellix** [comment]
Clip showing second problem (loading useSignal boolean not updating in DOM from an async useTask):  

https://user-images.githubusercontent.com/1162531/228691711-01caf8cf-3674-4e70-b20f-727902f79565.mov

**Comment by ahnpnl** [comment]
I see from https://qwik.builder.io/tutorial/hooks/use-task/ mentioned about `so if [useTask$()](https://qwik.builder.io/docs/components/lifecycle/#usetask) is asynchronous, the rendering will happen before the [useTask$()](https://qwik.builder.io/docs/components/lifecycle/#usetask) is fully executed.` so that might be the issue you saw

**Comment by intellix** [comment]
My use-case is for infinite loading (or a button to load more), so ignoring the fact I need to merge lists, instead of this:

```ts
const variables = useStore({ count: 1 });
const loading = useSignal(false);
const people = useStore<{ items: Person[] }>({ items: [] });

useTask$(async ({ track }) => {
  track(variables);
  loading.value = true;
  people.items = await getPeople(variables.count);
  loading.value = false;
});
```

```jsx
<button onClick$={() => {
  variables.count = variables.count + 1;
}}>{loading ? 'Loading...' : 'Load more'}</button>
```

I guess it would need to look like this:
```ts
const variables = useStore({ count: 1 });
const loading = useSignal(false);
const people = useStore<{ items: Person[] }>({ items: [] });

useTask$(async ({ track }) => {
  people.items = await getPeople(variables.count);
});
```

```jsx
<button onClick$={() => {
  variables.count = variables.count + 1;
  loading.value = true;
  people.items = await getPeople(variables.count);
  loading.value = false;
}}>{loading ? 'Loading...' : 'Load more'}</button>
```

I just lose seamless server/browser and reactivity that's all

**Comment by intellix** [comment]
the qwik-virtual-scroll only works because:
- it fetches the initial state with routeLoader$ (you require Qwik City on top of Qwik to have seamless server/browser switching), so that's the mechanism for awaiting server data first: https://github.com/literalpie/qwik-virtual-scroll/blob/main/src/routes/index.tsx#LL31C40-L31C40
- the useTask$ wraps it with isBrowser and doesn't use async/await (can't re-use the same code between server/browser): https://github.com/literalpie/qwik-virtual-scroll/blob/main/src/components/virtual-scroll/virtual-scroll.tsx#L105

Don't really want to useResource$ because I don't want to replace the entire DOM with a "Loading" element but change the state of a button and show skeleton loaders additionally to the items already on the page as you're scrolling. I can pass in the current array of items to the load function and append new items to the current array and then return that, but so far I've just found it awkward aside from pagination.

I believe I have enough to work around it but found it confusing, not the path of least resistance, not seamless and foresee many developers falling into the same pit of snakes :)

**Comment by intellix** [comment]
I suppose I'm to blame for shoving so much into a single issue but there's a few items here that I don't think are completed/fixed. Still having issues with signals within useTask$ but will check it out tomorrow and open a separate issue in that case
