### ISSUE TITLE
[📖] "Edit this Page" on all documentation pages doesn't work - leads to a "this page doesn't exist"

### ISSUE THREAD

**Issue by yasserlens** [BuilderIO/qwik#3546]
### Suggestion

As the title suggests - clicking on "Edit this Page" in Qwik's documentation doesn't leads to a 404 page on Github. See image below
 
<img width="1711" alt="Screenshot 2023-03-29 at 4 15 30 p m" src="https://user-images.githubusercontent.com/2945770/228586713-4a8700d4-3304-4b3a-bd93-7cf537786daf.png">

**Comment by the-r3aper7** [comment]
working on it 😊
