### ISSUE TITLE
[📖] Clarify example

### ISSUE THREAD

**Issue by yasserlens** [BuilderIO/qwik#3548]
### Suggestion

The first example here:
https://qwik.builder.io/docs/advanced/dollar/#1-literals-without-local-identifiers

says 
'''
const foo = 'foo';
foo$({ value: foo }); // it contains a local identifier "foo"
'''

As far as I understand, the constant foo and the function foo$ aren't the same thing. However, to new comers, the example could allude to some similarity or hint that there's some error here due to the constant name being similar to the function name? At least that's how I view it.

I suggest changing the constant name to anything else - since that's not really the point of the example. e.g.
'''
const bar = 'bar';
foo$({ value: bar }); // it contains a local identifier "bar"
'''

**Comment by zanettin** [comment]
thx for mentioning this 🙏  pr is created to adjust it 👍
