### ISSUE TITLE
[🐞] Child elements of disabled buttons still fire click events

### ISSUE THREAD

**Issue by sslotsky** [BuilderIO/qwik#3554]
### Which component is affected?

Qwik Runtime

### Describe the bug

Disabled button click handlers still fire when clicking on child elements.

### Reproduction

https://stackblitz.com/edit/qwik-starter-dx6xcy?file=package.json,src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Go to the [StackBlitz example](https://stackblitz.com/edit/qwik-starter-dx6xcy?file=package.json,src%2Froutes%2Findex.tsx)
2. Observe that the button is disabled
3. Click on the button text, observe that nothing happens
4. Click on the svg icon, observe the JavaScript alert indicating the button was clicked

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 103.05 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/58096_1680113977254/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/58096_1680113977254/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @builder.io/qwik: 0.24.0 => 0.24.0
    @builder.io/qwik-city: ~0.7.0 => 0.7.0
    undici: 5.21.0 => 5.21.0
    vite: 4.2.1 => 4.2.1
```

**Comment by swwind** [comment]
It seems my Firefox does not fire the alert but Chrome does.
