### ISSUE TITLE
[🐞] Smooth Scroll to on a native a-tag to a section via id is not working

### ISSUE THREAD

**Issue by Alx90s** [BuilderIO/qwik#3599]
### Which component is affected?

Qwik Runtime

### Describe the bug

I have a simple a-tag with a href="#contact"
Additionally, I have a CSS property which says that the (scroll-behavior: smooth) should be smooth
When I click on it, I expect that the scroll will be smooth to the given section with the id="contact"
It's scroll maybe 1px down and then the page is reloading. 

I reproduced it in this repo: https://github.com/Alx90s/scroll-smooth-link-bug

### Reproduction

https://github.com/Alx90s/scroll-smooth-link-bug

### Steps to reproduce

npm i
npm run dev

### System Info

```shell
MacOS Sillicon
Latest Chrome Browser 
Latest Qwik Version
```

**Comment by gioboa** [comment]
Hey @Alx90s, thanks for opening this issue, I saw that this feature works with the last version of Qwik, btw a lot of things happened during this months. 🚀
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
