### ISSUE TITLE
[🐞] Tracker issue with `useVisibleTask$(({ track }) => {})` when navigating between routes

### ISSUE THREAD

**Issue by denisyilmaz** [BuilderIO/qwik#3600]
### Which component is affected?

Qwik City (routing)

### Describe the bug

In a project component that uses a "slug" parameter to render different projects, I need to run a client-side function for analytics purposes each time the component is navigated to. I have implemented this using `useVisibleTask$()` with the `track()` feature to allow repetitive calls when the location or project data changes. This works as intended, but there's an issue where the tracker doesn't seem to be destroyed when leaving the project route or navigating between routes. As a result, the console logs multiply each time the route is navigated.

Here's the component code:
```tsx
export default component$(() => {
   const location = useLocation();
   const project = useProjectLoader();
   const show = useSignal(false);

   useVisibleTask$(({ track }) => {
        track(location);
        console.log("Track LOCATION");
    });
   useVisibleTask$(({ track }) => {
        track(project);
        console.log("Track PROJECT");
    });
   useVisibleTask$(({ track }) => {
        track(show);
        console.log("Track SHOW", show.value);
    });

    useVisibleTask$(() => {
        show.value = false;
        setTimeout(() => {
            show.value = true;
        }, 50);
    });
   return <div>Hello Route</div>;
})
```

When navigating back and forth between the project route and the homepage multiple times, the console logs multiply, indicating that the tracker is not being destroyed correctly.

## First time navigating to the route
<img width="188" alt="image" src="https://user-images.githubusercontent.com/4189607/229054866-ce286820-9ec8-482f-ba2c-9d9f563ddf9f.png">

## Navigating to a second project
<img width="211" alt="image" src="https://user-images.githubusercontent.com/4189607/229055104-3abe5af9-b740-4231-a859-c85037c4f1c5.png">

The "Track SHOW" is correctly printed twice again (once for `false`, once for `true`), but the other logs are multiplied. 

## After multiple navigations
<img width="300" alt="image" src="https://user-images.githubusercontent.com/4189607/229056324-a37dbb03-9529-4929-9b76-b5623263aad5.png">

### Reproduction

https://stackblitz.com/edit/qwik-starter-n1w5yi?file=src/routes/projects/[slug]/index.tsx

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 196.47 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.15.1 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: 111.0.1661.62
    Safari: 16.3
  npmPackages:
    @builder.io/qwik: 0.24.0 => 0.24.0 
    @builder.io/qwik-city: 0.7.0 => 0.7.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

**Comment by swwind** [comment]
what about changing to `track(() => location.url)`, `track(() => project.value)` and `track(() => show.value)`?

I don't think `track` function supports signals without a callback function. (?)

**Comment by denisyilmaz** [comment]
I changed the stackblitz to your suggestion, but the result stays the same. Tracking is not destroyed for location/show signals when navigating from/to project component: https://stackblitz.com/edit/qwik-starter-n1w5yi?file=src/routes/projects/[slug]/index.tsx

**Comment by gioboa** [comment]
Hey @denisyilmaz, thanks for opening this issue, I saw that this works with the last version of Qwik, btw a lot of things happened during this months. 🚀
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
