### ISSUE TITLE
[🐞] loop with component inside not updated correctly with store

### ISSUE THREAD

**Issue by derkoe** [BuilderIO/qwik#3605]
### Which component is affected?

Qwik Runtime

### Describe the bug

I have created an implementation of the JS framework benchmark in Qwik. 

When I use a separate component (`Row`) for the rows in the table then the "Swap Rows" does not work correctly. 

After swapping the rows, the version with the `Row` component is not updated correctly (the wrong entry is swapped). After another swap the whole loop seems to be broken. You cannot even clear the table anymore (one entry keeps displaying even though the array behind is empty).

https://user-images.githubusercontent.com/123199/229104207-7f486b62-c99e-468c-a66b-96576753985d.mp4

### Reproduction

https://stackblitz.com/edit/qwik-starter-u3ir9f

### Steps to reproduce

- Open https://stackblitz.com/edit/qwik-starter-u3ir9f
- Run `npm install && npm start` (usually done automatically)
- Click "Create 1000 rows"
- Click ""Swap Rows"
- Click ""Swap Rows" again
- Click "Clear"

You will see that the first swap rows has different results in the two tables.

The second swap rows will also look different

After clicking "Clear" the left table has still one item left (which you cannot get rid of)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.100.0 => 0.100.0 
    @builder.io/qwik-city: 0.100.0 => 0.100.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

**Comment by gioboa** [comment]
Hey @derkoe, thanks for opening this issue, I saw that this feature works with the last version of Qwik, btw a lot of things happened during this months. 🚀
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
