### ISSUE TITLE
[🐞] HTML nesting error should not crash server

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#3610]
### Which component is affected?

Qwik Runtime

### Describe the bug

![image](https://user-images.githubusercontent.com/111951/229222514-202e4422-c7ee-4da6-9d26-2a4dd5671fdf.png)

### Reproduction

n/a

### Steps to reproduce

creat invalid HTML (like `<p><div/></p>`)

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
It will crash most likely in the browser later, in a almost impossible to debug way.

**Comment by mhevery** [comment]
I think the exception is fine. I think the issue is that the server quits and now the Dev has to restart it. So I think what we are looking for is the exception as above, but without the need to have to restart the server.
