### ISSUE TITLE
[🐞] Component Library starter's `dev` and `start` servers don't work

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#3615]
### Which component is affected?

Starters / CLI

### Describe the bug

- `npm create qwik@latest`
- choose `Component library`
- try to run the `dev` command, or `build` followed by `start`

Both show this:

<img width="776" alt="CleanShot 2023-03-31 at 19 41 48@2x" src="https://user-images.githubusercontent.com/1393142/229250727-2caf1c05-7fd2-464f-8aac-52d72e8865d1.png">

### Reproduction

N/A

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 131.91 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.asdf/installs/nodejs/16.14.0/bin/node
    Yarn: 3.4.1 - ~/.asdf/installs/nodejs/16.14.0/bin/yarn
    npm: 8.3.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 111.1.49.128
    Chrome: 111.0.5563.146
    Firefox: 109.0.1
    Safari: 15.2
  npmPackages:
    vite: 4.2.1 => 4.2.1
```

**Comment by bjonesy** [comment]
I can confirm this. Looks like this breaks in create-qwik 0.17.5

Steps to reproduce:

-  Check out 0.17.5 `npm create qwik@0.17.5` 
- Install dependencies
- run `npm run dev` 
- page 404 not found

- Check out 0.17.0
- Install dependencies
- run `npm run dev` 
- dev mode works as expected
