### ISSUE TITLE
[🐞] bind:value doesn't work with useTask$ on the same signal

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#3635]
### Which component is affected?

Qwik Runtime

### Describe the bug

**2-way binding seems to not work correctly**

Changing the value of a signal in a `useTask$` that is used with`bind:value`, doesn't work.
A common use case is clamping a number between a maximum and minimum value.

For example, the useTask$ below won't run at all when editing the input value:

```tsx
export default component$(() => {
  const signal = useSignal<string | undefined>();

  useTask$(({ track }) => {
    // this doesn't run when editing the input
    track(signal);
    signal.value = "A";
  });

  return (
    <>
      {signal.value}
      <input type="text" bind:value={signal} />
    </>
  );
});
```

However, in the next example, the useTask$ does run, but the value in the input doesn't equal what the value is being set to in the useTask:

```tsx
export default component$(() => {
  const signal = useSignal<string | undefined>();

  useTask$(({ track }) => {
    track(signal);

    if (!isServer) {
      console.log("useTask runs");

      // useTask$ runs but the value in the input doesn't equal the value being set. Only the text node is set to 'A'
      signal.value = "A";
    }
  });

  return (
    <>
      {signal.value}
      <input type="text" bind:value={signal} />
    </>
  );
});
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-agp3bo?file=src/routes/index.tsx

### Steps to reproduce

- Run app
- Type something in the input
- Expect the input value and the text node to only show 'A'

### System Info

```shell
N/A
```

**Comment by DustinJSilk** [comment]
Hey @jordanw66 ! Thanks for helping out!

Do you know how to make it working when tracking the binded value?
I need to limit the value in the input as it changes.

To avoid an infinite loop, we could check if the value is different, however, even this doesn't work:

```tsx
useTask$(({ track }) => {
    track(signal);

    // useTask$ only runs with this if statment but doesn't update the value in the input
    // Removing the if statements breaks the useTask$ completely
    if (!isServer) {
      console.log('useTask runs');

      if (signal.value !== 'A') {
        signal.value = 'A';
      }
    }
  });
```

**Comment by DustinJSilk** [comment]
@manucorporat should it be possible to change a signals value that is being tracked in a `useTask$`?

**Comment by devcaeg** [comment]
Could someone provide me with a solution for the following scenario? I am currently working with an input field that has a value defined as {username.value}, where 'username' is a Signal object. In turn, this input field triggers a function through the "onInput$" event, which is responsible for obtaining 'event.target.value'. This function performs a series of transformations to the obtained value and then assigns the transformed value to 'username.value' with 'username.value = transformedValue'. However, I face a problem: the input field does not reflect this new assignment, that is, it does not display the newly transformed value. Any suggestions on how to address this issue?

**Comment by wmertens** [comment]
@devcaeg this works for me: https://qwik.builder.io/playground/#v=1.4.0&f=Q0o0xiZIEYWIfh1E7Utx%2BoEEBqgCBBdPtgijNdTVgQ5CChgbO3COz8%2FLqYTWJMVWNklFMB%2FZZIKreFD6sVUC5QAlUIYsBdbcMNP1wPxaoAng1oCKbbVGapmOQmoO3DUgAKyMQmHOyUgsRrEPqiQ1B2IU0Lkwpl5RakEOsFZ1zMnR0I9x0QemZLD7QcprayFuBIYyKIhH88WQzBcA

Closing this old issue, it seems to be working as intended? If not, please reopen with a playground repro
