### ISSUE TITLE
[🐞] Error Overlay too vague: provides no File or Frame

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#3638]
### Which component is affected?

Qwik Runtime

### Describe the bug

2 different examples of errors I've encountered:

<img width="1274" alt="CleanShot 2023-04-03 at 12 19 26@2x" src="https://user-images.githubusercontent.com/1393142/229569021-b024fd80-d413-4a81-9ffe-60e0e90a84c3.png">

<img width="1308" alt="CleanShot 2023-03-26 at 16 55 26@2x" src="https://user-images.githubusercontent.com/1393142/229569498-37bc520a-221e-470f-aa00-7e49f1e37c48.png">

I am not sure how to provide a reproduction, because the error is too vague so I'm not even sure how to reduce it from my entire app.

### Reproduction

N/A

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.26 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.asdf/installs/nodejs/16.14.0/bin/node
    Yarn: 3.4.1 - ~/.asdf/installs/nodejs/16.14.0/bin/yarn
    npm: 8.3.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 111.1.49.132
    Chrome: 111.0.5563.146
    Firefox: 109.0.1
    Safari: 15.2
  npmPackages:
    @builder.io/qwik: ^0.100.0 => 0.100.0
    @builder.io/qwik-city: ^0.100.0 => 0.100.0
    @builder.io/sdk-qwik: workspace:* => 0.1.16
    undici: 5.14.0 => 5.14.0
    vite: 4.0.3 => 4.0.3
```
```


### Additional Information

_No response_

**Comment by manucorporat** [comment]
Gonna close this issue since this is more like a design/specific error issue, some errors dont have a file/frame that is useful.
