### ISSUE TITLE
[📖] Add 404 Error page fallback 

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#3639]
### Suggestion

Overall, the 404 page of [qwik.builder.io/docs](http://qwik.builder.io/docs) is too aggressive: https://qwik.builder.io/docs/components/inline-components/

There should be a fallback that still renders the site, and docs sidebar, and has a nested 404 in the middle where the MDX should be rendered. 

<img width="1197" alt="CleanShot 2023-04-03 at 12 24 14@2x" src="https://user-images.githubusercontent.com/1393142/229569944-2274b25a-9666-4709-8d05-24b3d6868c5a.png">

**Comment by gioboa** [comment]
I will work on this.

**Comment by gioboa** [comment]
Closed by #5393
