### ISSUE TITLE
[✨] Expose `waitUntil` function to users

### ISSUE THREAD

**Issue by GregBrimble** [BuilderIO/qwik#3655]
### Is your feature request related to a problem?

Users are unable to schedule work to happen after a Response is returned. Like `env`, we should expose `waitUntil` to users somehow.

### Describe the solution you'd like

Not completely sure about how we should do it, but here's one option that would be a breaking change,

```
platform: {
  env,
  waitUntil
}
```

https://github.com/BuilderIO/qwik/blob/8db17e40f2515708cf76ca368754a95e0a40a136/packages/qwik-city/middleware/cloudflare-pages/index.ts#L72

### Describe alternatives you've considered

```
platform: {
  waitUntil
  ...env,
}
```

Benefit of not being a breaking change, but gets squashed by any env binding that shares the same name.

```
platform: env,
ctx: { waitUntil }
```

Alternatively, we could expose a new concept, a sibling of `platform`, which is for stuff like this.

**Comment by mhevery** [comment]
Could you add a use case of how you would expect to use such an API?

**Comment by mhevery** [comment]
I see the context: https://egghead.io/lessons/supabase-use-waituntil-to-perform-work-after-cloudflare-worker-returns-response

**Comment by GregBrimble** [comment]
Yeah, exactly! I might want to, for example, put something into the cache, or send errors to Sentry, or log to an analytics service, but don't want to block the response on that work.

**Comment by mhevery** [comment]
It feels like this should be a generic feature of Qwik City which underneath uses specific implementations such as CF.

**Comment by manucorporat** [comment]
It would appreaciate some help to know what's the right thing to do with cloudflare

**Comment by IgorMinar** [comment]
Thanks @manucorporat for looking into this. We'll discuss internally and get back to you. My preference would be to expose the entire [`ExecutionContext`](https://unpkg.com/browse/@cloudflare/workers-types@4.20230404.0/2022-11-30/index.d.ts#LC290:~:text=declare%20interface%20ExecutionContext,%7D) object and not just the `waitUntil` function, but I'd like to sync up with our folks first before asking for that here.

**Comment by petebacondarwin** [comment]
I agree with @IgorMinar - it would be nice to simply expose the whole `ExecutionContext` object, which would mean that QwikCity doesn't have to keep updating every time Cloudflare adds properties/methods to this object.

**Comment by manucorporat** [comment]
i thought Cloudflare added all their APIs under the env property (which i found odd)

**Comment by manucorporat** [comment]
This should fix it
https://github.com/BuilderIO/qwik/pull/3931

**Comment by petebacondarwin** [comment]
Awesome! Thanks @manucorporat
