### ISSUE TITLE
[🐞] custom 404 page not loading

### ISSUE THREAD

**Issue by carepollo** [BuilderIO/qwik#3658]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I am doing a custom 404 page, following the article the [docs](https://qwik.builder.io/docs/advanced/routing) but doesn't load my custom page, keeps loading the default 404 default page.

### Reproduction

https://stackblitz.com/edit/node-swd2sp?file=qwik-app/src/routes/404.tsx

### Steps to reproduce

Do the following steps
- npm create qwik@latest
- create component named 404.tsx under the `src/routes` path
- npm run dev

### System Info

```shell
System:
    OS: Linux 6.1 undefined
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 14.22 GB / 18.91 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.6.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Brave Browser: 111.1.49.132
    Chromium: 111.0.5563.146
    Firefox: 111.0.1
```

### Additional Information

package json
```
    "@builder.io/qwik": "0.24.0",
    "@builder.io/qwik-city": "~0.7.0",
    "@types/eslint": "8.21.3",
    "@types/node": "^18.15.3",
    "@types/node-fetch": "latest",
    "@typescript-eslint/eslint-plugin": "5.56.0",
    "@typescript-eslint/parser": "5.56.0",
    "autoprefixer": "^10.4.13",
    "eslint": "8.36.0",
    "eslint-plugin-qwik": "0.24.0",
    "node-fetch": "3.3.0",
    "postcss": "^8.4.16",
    "prettier": "2.8.6",
    "sass": "^1.57.1",
    "tailwindcss": "^3.1.8",
    "typescript": "5.0.2",
    "undici": "5.21.0",
    "vite": "4.2.1",
    "vite-tsconfig-paths": "3.5.0"
```

**Comment by adamdbradley** [comment]
At this time custom 404 pages do not work in dev mode or preview mode. It should be working however in production. Are you seeing and issue in production?

**Comment by carepollo** [comment]
in production is working fine.

**Comment by MiguelValdez-mv** [comment]
It's strange, it doesn't work for me neither in development nor in production :sweat_smile: @carepollo 

I assume that this problem is not completely solved yet, right? @manucorporat

**Comment by adamdbradley** [comment]
This should be fixed now that the 404.html files will always be generated with and without the ssg `include` setting: https://github.com/BuilderIO/qwik/commit/2cbc1a19d00303159536f08ce8906c71841680f5
