### ISSUE TITLE
[🐞] Swiper does not work in production, and it does not show any error

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#3665]
### Which component is affected?

Qwik Runtime

### Describe the bug

I use Swiper on my website. It works when I use `npm run dev`. But when I use `npm run build` or `npm run preview` it does not work anymore, and it does not show me any error.

### Reproduction

https://github.com/Nefcanto/QwikSwiperBuild

### Steps to reproduce

- `git clone https://github.com/Nefcanto/QwikSwiperBuild`
- `cd QwikSwiperBuild`
- `npm install`
- `npm run dev`
- Go to `http://localhost:5173/`
- It works (ignore the reloading, that's because of our config related to Docker containers)
- Now stop the app
- `npm run preview`
- Again go to `http://localhost:5173/`
- Slides are beneath each other
- No error is in browser's console

### System Info

```shell
System:
    OS: Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 9.55 GB / 15.52 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/partytown: ^0.7.6 => 0.7.6 
    @builder.io/qwik: ^0.100.0 => 0.100.0 
    @builder.io/qwik-city: ^0.100.0 => 0.100.0 
    @builder.io/qwik-react: ^0.5.0 => 0.5.0 
    vite: ^4.2.1 => 4.2.1
```

**Comment by sprngLf** [comment]
`"swiper": "^9.2.0"` has bug in it, it is still in `dev` mode use `9.0.0` instead.

**Comment by Nefcanto** [comment]
@sprngLf thank you for the note. I looked at the swiper repo, and I saw no sign of `dev` in the labels or branches. They have released the `9.2.0`. Can you show me their bug?

I would of course test with `9.2.0`. But it might be that Qwik has a bug. Because `9.2.0` works just fine in the development environment.

**Comment by sprngLf** [comment]
> @sprngLf thank you for the note. I looked at the swiper repo, and I saw no sign of `dev` in the labels or branches. They have released the `9.2.0`. Can you show me their bug?
> 
> I would of course test with `9.2.0`. But it might be that Qwik has a bug. Because `9.2.0` works just fine in the development environment.

Yeah sorry, I was mistaken thinking it's in still `dev`. The bug that I encountered in `9.2.0` is in nav pagination bullets, when I click the first bullet it doesn't work.

**Comment by meysamzi** [comment]
I almost have the same problem with Swiper when SSL stops working in my host, in this situation, Swiper doesn't work well

**Comment by Nefcanto** [comment]
After upgrading to Qwik 0.103.0 this bug got solved.

**Comment by meysamzi** [comment]
Thanks for sharing the solution.
