### ISSUE TITLE
[✨] Qwik City Add sveltekit `afterNavigate` equivalent 

### ISSUE THREAD

**Issue by sprngLf** [BuilderIO/qwik#3666]
### Is your feature request related to a problem?

Yes, I want to be able to run something inside `layout.tsx` file when the user navigates to a new page when using `<Link>`

### Describe the solution you'd like

something like sveltekit's `afterNavigate`

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by swwind** [comment]
Not familiar with sveltekit, but maybe duplicated to #2202.

**Comment by sprngLf** [comment]
thameus#6784 from discord help me to solve this.

Solution:
```
const location = useLocation();

useVisibleTask$( ({ track }) => {

    track(() => location.url.href);

})

```
