### ISSUE TITLE
[🐞] Route action result is not rendered after navigation

### ISSUE THREAD

**Issue by mhdmas** [BuilderIO/qwik#3727]
### Which component is affected?

Qwik Runtime

### Describe the bug

Expected Behavior: The route action (routeAction$) submission returns a result value that can be assigned to a Signal and displayed on the UI when needed. This behavior is observed on page load.

Observed Behavior: After navigating from one page to another, the value of the route action submission is not rendered on the UI.

Please note that the reproduction URL is not working as expected on Stackblitz since the route action is redirecting to localhost.

### Reproduction

https://stackblitz.com/edit/qwik-starter-jkqlym?file=vite.config.ts

### Steps to reproduce

Navigate manually to "/second" and click on "Send action" button, the order id from the action result should show, and this is the normal behavior, to reproduce the bug, please follow the steps below:

- Navigate manually to "/first".
- Click om "Navigate to Second page" button, this will programmatically navigate to "/second".
- Click on "Send action" button.
- The order id is not present.
- Click on "Send action" button **again**.
- The order is present.

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 272.13 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.101.0 => 0.101.0 
    @builder.io/qwik-city: ~0.101.0 => 0.101.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

**Comment by blecorre-mnp** [comment]
+1, the `navigate()` method seems to disable `routeAction$()` but also `useOn()` in my case.
