### ISSUE TITLE
[📖] onSubmitCompleted$ Event Handler

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/qwik#3742]
### Suggestion

From what I see there isn't any documentation covering the onSubmitCompleted$ event handler. This was the perfect solution to the problem I was having, and the person who recommended it to me found it in the type definitions.

I can see in VSCode a description now of what it does:
"Event handler executed right after the action is executed successfully and returns some data."

Although for many others I think it would be very beneficial to have this in the docs.

Relevant conversation in the discord:
https://discord.com/channels/842438759945601056/1095037577435824210/1095037577435824210

If there's anything I can do that would contribute to that documentation would love to hear it. Should I make a PR about it and include it in a subsection on the route action/form action page?

**Comment by zanettin** [comment]
Hi @thejackshelton 👋 
imo it would be great to have this documented 👍  atm we just have it on the [API docs](https://qwik.builder.io/api/qwik-city/#formprops). and yes, from my point of view it could be just added to the route loader docs page 🙏

**Comment by thejackshelton** [comment]
Added it to Form Actions a couple weeks back 

![image](https://github.com/BuilderIO/qwik/assets/104264123/0a1d17e6-66dc-4188-b52e-4c1b3856d647)

**Comment by thejackshelton** [comment]
https://qwik.builder.io/docs/action/#actions-with-event-handlers

Added it to form actions a couple weeks back

**Comment by thejackshelton** [comment]
Closing now. Forgot I had this open.
