### ISSUE TITLE
[✨] Support serializing BigInt

### ISSUE THREAD

**Issue by steve8708** [BuilderIO/qwik#3748]
### Is your feature request related to a problem?

Right now working with prisma and supabase is rough, because by default the postgres IDs are bigint, so transfering them from server$ means a lot of additional mapping of things back and forth

### Describe the solution you'd like

Support serializing bigint (e.g. just convert to a string and back)

### Describe alternatives you've considered

Right now, I'm doing a lot of manual serialization and deserialization ever time (a lot of places in my app)

**Comment by manucorporat** [comment]
Should be simple! going to look into it!

**Comment by steve8708** [comment]
amazing 🎉 🙏

**Comment by steve8708** [comment]
![image](https://user-images.githubusercontent.com/844291/231906111-ed506911-c23c-48cf-8ce8-6ec018808705.png)
