### ISSUE TITLE
[📖] Netlify functions -> RequestHandlerNetlify no longer exists

### ISSUE THREAD

**Issue by yasserlens** [BuilderIO/qwik#3750]
### Suggestion

The documentation suggests using RequestHandlerNetlify type for an onGet request. However, that interface/class is no longer there as of v0.100.0.

I see PlatformNetlify instead. Not sure yet how that maps to the deprecated RequestHandlerNetlify. A clarification in the docs would be appreciated.

**Comment by adamdbradley** [comment]
Thanks, will update to remove the old content: https://github.com/BuilderIO/qwik/pull/4189
