### ISSUE TITLE
[🐞] `server$` RequestEvent is undefined during SSR

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#3751]
### Which component is affected?

Qwik City (routing)

### Describe the bug

The `server$` function has an undefined RequestEvent attached to `this` when rendered on the server inside a `useTask$` or `useResource$`.

Understandably, it's just calling the function and not in fact making a request, however, this means we don't have access to necessary information to complete the server function, such as:

- `sharedMap` which is where i store session data
- `cookies` that I need to pass on with my RPC calls
- other `headers` such as a traceparent

Is it possible to still attach these to the function during SSR, the same event from the page request would make sense.

Example:

```tsx
const request = server$(async function () {
  console.log(this) // <- undefined
})

export default component$(() => {
  useTask$(async ({ track }) => {
    await request()
  })
})
```

### Reproduction

https://github.com/DustinJSilk/qwik-server-scope

### Steps to reproduce

- Install & run
- see the logged `undefined` in the console
- click the button and see it is no longer undefined

### System Info

```shell
N/A
```

**Comment by phyrog** [comment]
@manucorporat As far as I can tell, this is not fixed in 1.0. I cloned the reproduction repo linked above and updated the dependencies to their latest versions with `pnpm up --latest` (getting qwik and qwik-city 1.0.0) and I can still see this behavior (`this` is undefined on SSR).
