### ISSUE TITLE
[🐞] eslint rule `qwik/use-method-usage` prevents using use* methods in custom hooks

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#3787]
### Which component is affected?

Qwik Runtime

### Describe the bug

The latest release of eslint-plugin-qwik Eslint now throws an error:

`Calling use* methods in non-root component.`

This seems like a mistake, as use* methods have been working perfectly fine when used in functions that are called in a `component$`.

If this is not a mistake, can we reconsider this change because it prevents developers from creating new hooks composed by qwik use* methods.

A basic example, this is no longer allowed:

```tsx
export function useSession() {
  return useContext(SessionContext).session
}
```

### Reproduction

N/A

### Steps to reproduce

Use a use* method outside of a root component

### System Info

```shell
N/A
```

**Comment by robisim74** [comment]
This Qwik linter rule was recently introduced: it would be a serious regression if custom hooks could no longer be built.

In any case, in my opinion, this rule should not be checked by a linter, but by the compiler even in dev mode.

Linters should be used to _analyzes code for **potential** errors, coding **style** issues, and **best practices** violations_ (by ChatGpt...) and not for code construction errors (which, I repeat, should be the job of the compiler).

Again in my opinion, linters should be optional: if we look at a newly created app with Qwik, it has 13 dependencies, 6 of which are linters! Almost 50%!

  "@builder.io/qwik": "0.102.0",
  "@builder.io/qwik-city": "~0.102.0",
  **"@types/eslint": "8.37.0",**
  "@types/node": "^18.15.9",
  **"@typescript-eslint/eslint-plugin": "5.57.1",**
  **"@typescript-eslint/parser": "5.57.1",**
  **"eslint": "8.37.0",**
  **"eslint-plugin-qwik": "0.102.0",**
  **"prettier": "2.8.7",**
  "typescript": "5.0.3",
  "undici": "5.21.0",
  "vite": "4.3.0-beta.3",
  "vite-tsconfig-paths": "4.2.0"

Useful? perhaps, but not required to build an app.

But maybe that's a topic for a discussion.

**Comment by manucorporat** [comment]
The optimizer will not use `identifier` names to fail or not. Use-methods checking is a definitely a linter thing imo.

Custom use methods are still allowed inside custom hook methods, this must be a regression.
