### ISSUE TITLE
[BUG] Better types and autocompletion for events

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#381]
**Describe the bug**
Common dom events should show up in autocompletion and types should be more specific.

**Expected behavior**
keyup event for example, should get KeyboardEvent as first argument.

**Screenshots**
<img width="681" alt="Screenshot 2022-04-10 at 12 26 45" src="https://user-images.githubusercontent.com/127379/162615857-a503c55c-3949-4a4f-bb96-282bf0cbb33a.png">

**Desktop (please complete the following information):**

**Additional context**

**Comment by mhevery** [comment]
I believe this is working, so I am closing it.
