### ISSUE TITLE
[🐞]Playground & Tutorial are broken / 404 repl-server-host

### ISSUE THREAD

**Issue by duongphuhiep** [BuilderIO/qwik#3811]
### Which component is affected?

Qwik Playground

### Describe the bug

Unable to live preview the codes in the Playground (since several days)

![image](https://user-images.githubusercontent.com/1638594/232636309-a737ff55-5a4b-4989-b224-46b28aec8ad2.png)

![image](https://user-images.githubusercontent.com/1638594/232636511-27848ebb-8617-4ad1-b08c-b5a8ddec860c.png)

### Reproduction

https://qwik.builder.io/tutorial/welcome/overview/

### System Info

```shell
System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    
  Browsers:
    Chrome: 112.0.5615.121
    Firefox: 112.0
```

**Comment by manucorporat** [comment]
Shoudl be fixed now!
