### ISSUE TITLE
[🐞] starter app does not work on windows

### ISSUE THREAD

**Issue by konayukis** [BuilderIO/qwik#3824]
### Which component is affected?

Qwik Runtime

### Describe the bug

I also bumbed into this problem [#280](https://github.com/BuilderIO/qwik/issues/280)

### Reproduction

N/A

### Steps to reproduce

`pnpm start`
![image](https://user-images.githubusercontent.com/70825886/232821961-5bfdd16c-76f6-4bc9-87b3-7f60ea8886d2.png)

`pnpm run build`
![image](https://user-images.githubusercontent.com/70825886/232822327-22a89637-8838-45d0-9426-0dc7888c8413.png)

`npx envinfo --system --npmPackages '{vite,undici,@builder.io/*}' --binaries --browsers`
![image](https://user-images.githubusercontent.com/70825886/232822898-ce732286-2fa4-474f-9eea-a7e65da3dfba.png)

### System Info

```shell
pnpm 7.1.5
node 16.15.0
windows 10 22H2
browsers  Edge 112.0.1722.48
```

**Comment by KaanSali** [comment]
Hello,

Non-English characters in the path is causing this problem.
Use need to use a path like : C:\QwikProjects\qwik-app

That will solve your problem.

**Comment by konayukis** [comment]
not support Non-English characters in the path
