### ISSUE TITLE
[📖] the demo for component lazy loading is not found

### ISSUE THREAD

**Issue by wtlin1228** [BuilderIO/qwik#3830]
### Suggestion

The demo of https://qwik.builder.io/docs/components/overview/#lazy-loading is not found

![Screen Shot 2023-04-19 at 1 59 35 PM](https://user-images.githubusercontent.com/16910748/232980428-54051b0f-b96f-40fa-a316-6350f25f3a44.png)

Maybe need to check this code sandbox 
https://github.com/BuilderIO/qwik/blob/main/packages/docs/src/routes/docs/(qwik)/components/overview/index.mdx#:~:text=%3CCodeSandbox%20src%3D%22/src/routes/demo/component/lazy/index.tsx%22%20style%3D%7B%7B%20height%3A%20%2710em%27%20%7D%7D%20sandbox%3D%7Bfalse%7D%3E

**Comment by zanettin** [comment]
thanks @wtlin1228 for mentioning this 🙏  fix is prepared 👍
