### ISSUE TITLE
[📖] Explain more for how to use the "previous form data"

### ISSUE THREAD

**Issue by wtlin1228** [BuilderIO/qwik#3861]
### Suggestion

The `action.formData` API behaves differently depending on the presence of `params.qaction` in the URL. When this parameter is not present, the API returns undefined.

In situations where the JavaScript is disabled and the form is submitted for the first time, `params.qaction` is added to the URL, and `action.formData` is updated with the form's data. Subsequent submissions with different values also update action.formData.

However, when JavaScript is enabled again, `action.formData` stops getting updated. This behavior can be confusing, and it requires a more thorough explanation. Could you provide additional context or details about this issue?

ref: https://qwik.builder.io/docs/action/#previous-form-state

**Comment by zanettin** [comment]
Hi @wtlin1228 👋 
Thanks a lot for this inputs! would you have time to create a PR for the first iteration of improvements in that regard? 😄

**Comment by wtlin1228** [comment]
Yes, I would be happy to create a PR for it.

**Comment by zanettin** [comment]
Hi @wtlin1228 👋 
Just wanted to check-in real quick to ask, if you're still interested in providing a PR for this topic 👼  would be very much appreciated 🙏

**Comment by wtlin1228** [comment]
> Hi @wtlin1228 👋 Just wanted to check-in real quick to ask, if you're still interested in providing a PR for this topic 👼 would be very much appreciated 🙏

Thank you for reaching out! I would love to contribute a PR for this topic. However, I wanted to inform you that I am currently on a three-week vacation . As soon as I return next week, I will be more than happy to work on it. 😁

**Comment by zanettin** [comment]
Hi @wtlin1228 👋 oh that sounds nice 🏝️ no hurries at all! just wanted to ask if u r still interested and have some time. thank you very much for helping on this 🙏
