### ISSUE TITLE
[🐞]  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tuurbo** [BuilderIO/qwik#3863]
### Which component is affected?

Qwik Runtime

### Describe the bug

After updating from Qwik 0.102.0 to 0.103.0 I get `RangeError: Maximum call stack size exceeded` when mutating state from useStore and routeLoader$

See stackblitz below

### Reproduction

https://stackblitz.com/edit/qwik-starter-xweueu?file=src%2Froutes%2Findex.tsx

### System Info

```shell
stackblitz

-- AND --

System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 13.86 GB / 31.68 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0
    @builder.io/qwik: 0.103.0 => 0.103.0
    @builder.io/qwik-city: 0.103.0 => 0.103.0
    vite: 4.3.0 => 4.3.0
```

**Comment by manucorporat** [comment]
Got a fix, but, this line:
```
      reversed: item.product.options.reverse(), // <---------------
```
is also mutation `item.product.options.`

There is a mutation inside the render function
