### ISSUE TITLE
[DOCS] Typo in https://qwik.builder.io/guide/why-qwik

### ISSUE THREAD

**Issue by jasikpark** [BuilderIO/qwik#387]
**How can the documentation be improved?**

Fix Frustat -> Frustrate

https://qwik.builder.io/guide/why-qwik

![D3F7AC20-2BBA-49CE-8D5A-FD4BFCB62C2D](https://user-images.githubusercontent.com/10626596/163025251-d749925c-2b4b-407a-948d-fac2aad0c763.png)

**Comment by codercatdev** [comment]
#392 should close this, thanks for finding it!
