### ISSUE TITLE
[🐞] Issue with IntrinsicElements and no children

### ISSUE THREAD

**Issue by tzdesign** [BuilderIO/qwik#3870]
### Which component is affected?

Qwik Runtime

### Describe the bug

Hi there,

we experience an issue with typescript types and can't solve it.

We have polymorphic components with dangerouslySetInnerHTML and no children.

#### In Version 0.102

With children and no dangerouslySetInnerHTML it is fine, with dangerouslySetInnerHTML only it breaks:

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/3037096/233604610-9229fa25-8679-4e67-9d65-21f33f70994a.png">

```tsx
import type { QwikIntrinsicElements } from '@builder.io/qwik';
import { component$, useStylesScoped$ } from '@builder.io/qwik';

export default component$(
  <C extends keyof QwikIntrinsicElements>(props: VeryFunCompnent<C>) => {
    const { as: propAs, text, ...rest } = props;
    const Component = (propAs ?? 'div') as string;
    return <Component dangerouslySetInnerHTML={makeMePretty(text)} {...rest} />;
  }
);

export type VeryFunCompnent<C extends keyof QwikIntrinsicElements = 'button'> =
  QwikIntrinsicElements[C] & {
    text: string;
    as?: C;
  };

export function makeMePretty(text: string): string {
  return text.replace(/\n/g, '<br>\n');
}
```

#### In Version 0.103

Even the polymorphic component with children breaks

```tsx
import type { QwikIntrinsicElements } from '@builder.io/qwik';
import { component$, Slot, useStylesScoped$ } from '@builder.io/qwik';

export default component$(
  <C extends keyof QwikIntrinsicElements>(props: ButtonProps<C>) => {
    const { color = 'primary', as: propAs, ...rest } = props;
    const Component = (propAs ?? 'button') as string;
    return (
      <Component class={['button', color]} {...rest}>
        <Slot name="start" />
        <div class="label">
          <Slot />
        </div>
        <Slot name="end" />
      </Component>
    );
  }
);

export type ButtonProps<C extends keyof QwikIntrinsicElements = 'button'> =
  QwikIntrinsicElements[C] & {
    as?: C;
    color?: ButtonColor;
  };

export type ButtonColor =
  | 'primary'
  | 'secondary'
  | 'positive'
  | 'notice'
  | 'inherit';
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-qads2x?file=src%2Fcomponents%2FVeryFunComponent.tsx

### Steps to reproduce

Just run it on stackblitz in preview and it will fail.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Additional Information

This started in Version 0.100 and continued.

Is there a better way to do polymorphism without casting to string?

**Comment by tzdesign** [comment]
Does someone know where jsx-qwik-attributes is coming from?
I'm in the code base here
https://github.com/BuilderIO/qwik/blob/980bcad32817efa8c2f891db8ad46397b001eb54/packages/qwik/src/core/render/jsx/types/jsx-generated.ts#L2

I want to figure out what's wrong with polymorphism and some specific elements, but the issue of the children type might be in that generated file. If you point me in the right direction, I will check if I'm right.

```tsx
export default component$(
  <C extends keyof ButtonAllowedTags>(props: ButtonProps<C>) => {
    const { color = 'primary', as: propAs, ...rest } = props;
    useStylesScoped$(styles);
    const Component = (propAs ?? 'button') as string;
    return (
      <Component class={['button', color]} {...rest}>
          <Slot name="start" />
          <div class="label">
            <Slot />
          </div>
          <Slot name="end" />
      </Component>
    );
  }
);

export type ButtonAllowedTags = Pick<
  QwikIntrinsicElements,
  'button' | 'a'
>;
export type ButtonProps<C extends keyof ButtonAllowedTags = 'button'> =
  ButtonAllowedTags[C] & {
    as?: C;
    /**this is the color of the button */
    color?: ButtonColor;
  };
```
This works, but as soon as I don't pick the element, it does not. Typescript is crying hard and I don't want to do a cast to any.
It was working in 0.22 for example. Stopped working after going into 0.100 and is still an issue.

If I just put div into the pick list I get:
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/3037096/235889987-75a9e0bf-1353-48b9-b443-0b7853171946.png">

**Comment by gioboa** [comment]
is it solved with the latest version of Qwik?

**Comment by tzdesign** [comment]
@gioboa wasn't able to check it yet. Will take a look in the next days. From what I know of quick, it should be fixed.

**Comment by wmertens** [comment]
@tzdesign note that this is now documented at https://qwik.dev/docs/components/overview/#polymorphic-components so hopefully everything works as expected

**Comment by the-zimmermann** [comment]
@wmertens @gioboa removed `{null}` and everything works. `PropsOf` is the shit, thanks @wmertens 🔥

**Comment by tzdesign** [comment]
@wmertens @gioboa removed `{null}` and everything works. `PropsOf` is the shit, thanks @wmertens 🔥
