### ISSUE TITLE
[🐞] SPA routing is preventing browser defaults

### ISSUE THREAD

**Issue by tzdesign** [BuilderIO/qwik#3871]
### Which component is affected?

Qwik Runtime

### Describe the bug

When you press cmd + click on a link, qwik uses preventDefault. 

The default browser experience would open a new tab. If you add shift to the party, it'll even open it directly.
I know there are several other shortcuts to open in a new window or private window.

Qwik should not prevent that kind of functionality.

### Reproduction

https://stackblitz.com/edit/qwik-starter-qads2x?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Run it on stackblitz.

## Click flower app with cmd 
You just get routed

## Click todo app with cmd
You get to a new tab

### System Info

```shell
See stackblitz
```

**Comment by manucorporat** [comment]
is it a thing in other metaframeworks like nextjs, when using Link?

**Comment by tzdesign** [comment]
@manucorporat no I think you are preventing default.
In react-router and next it's only preventing default if shiftKey, meta and ctrl are not true.

I checked it with our internal apps and my personal nextjs page.

We discussed this with @hamatoyogi and @shairez, and I think we agreed that qwik should avoid preventing browser APIs as much as possible.

You can call it a feature request, but I would say it should have been implemented in the same way already.

**Comment by tzdesign** [comment]
@jordanw66 I agree, trying to fake the default behavior is not an option.

I think that qwik suppresses the default behavior here is a mistake. However, I don't know how important it is to everyone to go to the qwik-loader here. 

Do you think it's justified to pursue it here? I personally use meta + shift + click every single day.

@manucorporat what is your opinion about it?

**Comment by tzdesign** [comment]
@jordanw66 perfect to pointing to it. Your suggestion is awesome. The question is, how deep do we want to go.
I might want to implement it for all developers and pass the allowmodifiers as a type like that:

```ts
export type AllowModifiers = SingleOrArray<
  keyof Pick<QwikMouseEvent, 'altKey' | 'ctrlKey' | 'metaKey' | 'shiftKey'>
>;
```

This way it's connected to the event and the developer can be specific.
For link we set linkProps to all of them.

I have some space tomorrow and can check it out, but maybe @manucorporat can tell us if this is ok. We also can catch up and talk about it, as Manu wanted to write e2e tests for navigation?

**Comment by gioboa** [comment]
This is solved by [sync$()](https://qwik.builder.io/docs/cookbook/sync-events/#example-sync-with-state)

**Comment by tzdesign** [comment]
@gioboa @mhevery just perfect 🥹

The sync$ is also a pretty awesome new feature

**Comment by gioboa** [comment]
Nice, I'm glad to hear that 😉
