### ISSUE TITLE
[🐞] Qwik ESLint plugin recently triggered a strange error

### ISSUE THREAD

**Issue by fabian-hiller** [BuilderIO/qwik#3887]
### Which component is affected?

Qwik ESLint

### Describe the bug

The Qwik ESLint plugin recently (v0.103.0) throws the following error: `Calling use* methods in non-root component.` Is this a bug? Technically, my approach is not a problem. If this rule remains as it is, I will need to update the Modular Forms documentation.

<img width="964" alt="Screenshot 2023-04-20 at 14 42 19" src="https://user-images.githubusercontent.com/35291865/233798995-5e3eac5b-dede-4e8f-85f3-00d3cea467f1.png">

### Reproduction

https://stackblitz.com/edit/modular-forms-qwik-actions-r8dy77?file=src%2Froutes%2Ftodos%2Findex.tsx%3AL130

### Steps to reproduce

Is ESLint executed in StackBlitz? If not, the project must be run locally in VS Code.

### System Info

```shell
I think that this information is not relevant here.
```

**Comment by manucorporat** [comment]
I think it's a good practice to put all the use methods as unnested as possible, but the use case you showed, should be perfectly valid! gonna fix
