### ISSUE TITLE
[🐞] Unneccessary prefetched scripts are all counting in Lighthouse and PageSpeed

### ISSUE THREAD

**Issue by fmotlagh03** [BuilderIO/qwik#3916]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to get a high lighthouse/pagespeed score, and there are a lot of problems that they report which are related to scripts.

I have nothing above the fold. I just have a bunch of texts and HTML elements styled using Tailwind. I have even removed my menu icon for mobile and added a screen-tall division below my hero section to make sure that there is no script whatsoever required for above the fold.

Yet when I load my website, I see a lot of scripts being shown on the Network tab. As I searched their names, I found this line:

```
    <script type="module">
        document.dispatchEvent(new CustomEvent("qprefetch",{detail:{"bundles":["q-ec256a11.js","q-160ad389.js","q-2e7bf3e0.js","q-6a24878f.js","q-fc65f989.js","q-46c1b641.js","q-8628d751.js","q-98014a2f.js","q-ff5adcb4.js","q-5973ca3f.js","q-af16d7c2.js"]}}))
    </script>
```

This was related to `npm run preview`. And when I use `npm run build` and then serve my website using `node server/entry.express.js` I see this code too:

```
const appBundles = [["q-08ffd6c0.js", [3, 7, 9, 38], ["2x5T0jzLsAk", "5OkQdGGyL4A", "Yy6gnsbRWKY"]], ["q-0dcae3c6.js", [7, 19, 38]], ["q-10b39364.js", [7]], ["q-160ad389.js", []], ["q-161aad97.js", [7, 19]], ["q-172cd13a.js", [7, 9, 13, 19, 38], ["PdBZ3iDbPQA"]], ["q-1d05b01b.js", [7]], ["q-1d920454.js", []], ["q-1e7e6950.js", [7, 19], ["yDcyHPF1T2o"]], ["q-243bd65c.js", [7]], ["q-2ce37848.js", [7, 19, 35, 38], ["Ossmb4bjxMg"]], ["q-2da619ef.js", [7, 9, 38]], ["q-358d68f6.js", [7]], ["q-3ea0777e.js", [7, 19]], ["q-439a8f9a.js", [7, 9, 12, 38], ["A1ssYUErBQY", "RCk6LUpoQlU"]], ["q-45aab3b6.js", []], ["q-47452b66.js", [3, 7, 9, 26, 38], ["lWuAeLArgaY", "Lzju0uqPTFo", "MT4d0htQN4o"]], ["q-4a824742.js", [7]], ["q-5227d92e.js", [7, 9, 20, 38]], ["q-552e253f.js", [7], ["1QKKC0NVXEU"]], ["q-560d235e.js", [7]], ["q-565b4350.js", [7, 19], ["02wMImzEAbk", "fX0bDjeJa0E", "RPDJAz33WLA", "TxCFOy819ag"]], ["q-5fabcee5.js", [7, 9, 20, 38]], ["q-6532db9c.js", [7]], ["q-7d659ea4.js", [3, 7, 9, 26, 38], ["NJUuur5nzBE", "VV2g4riGEdk", "zF8k4Nbb9FI"]], ["q-8066be06.js", [7]], ["q-8628d751.js", []], ["q-8e413b83.js", [1, 7, 19, 38], ["H9K60qOuPGA"]], ["q-a27ce943.js", [7, 9, 12, 38]], ["q-ae4d730f.js", [7, 9, 19, 34, 38], ["dKRXGwXw2mQ"]], ["q-b5c0ff21.js", [3, 7, 9, 12, 26, 38], ["4j4plRMj3gE", "7820qma5lxY", "BUa4FGplYBI"]], ["q-bddd59fd.js", [7], ["UGxYUkCVUps"]], ["q-c2e9cded.js", [7, 19], ["AKetNByE5TM", "KnNE9eL0qfc"]], ["q-d6d97ec6.js", [7], ["vrZDxnDuCBU"]], ["q-d6dee33d.js", [7, 19]], ["q-db71af1a.js", [7, 19]], ["q-e530fb79.js", [7]], ["q-f96edf9a.js", [7], ["NyacM5awRMY"]], ["q-fc65f989.js", []], ["q-fc90b43b.js", [4, 7, 9, 19, 38], ["UdIHNtZ13Ow"]]];
```

Now the problem is that they affect both Lighthose and PageSpeed scores.

I see this problems in the PageSpeed report:

![imageedit_0_5413915476](https://user-images.githubusercontent.com/16555459/234251249-e40b6c3c-cf18-4f92-aaa1-1770785e1b29.png)

The are both orange warnings and it seems that they both contribute to my rather low score (between 70 and 80).

What should I do? I chose Qwik only because of this reason to get high lighthouse score. 

### Reproduction

I can't provide reproduction link

### System Info

```shell
System:
    OS: Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 10.14 GB / 15.51 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.5 - /usr/local/bin/npm
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0 
    @builder.io/qwik: ^0.103.0 => 0.103.0 
    @builder.io/qwik-city: ^0.103.0 => 0.103.0 
    @builder.io/qwik-react: ^0.5.0 => 0.5.0 
    vite: ^4.3.1 => 4.3.1
```

**Comment by Dindaleon** [comment]
This is a known issue, I hope it will be fixed soon. I have halted all development using qwik until this has been resolved. It's Qwik's premise to have 0kB on load, without it you may as well use any other framework.

https://github.com/BuilderIO/qwik/issues/3756

**Comment by Dindaleon** [comment]
> @Dindaleon That issue is not related, that is regarding an increase in a specific bundle size. Qwik is not meant to download 0kB of JS on load and I am not sure where you heard this but it's a misunderstanding. It is supposed to be O(1). It actually loads 1kB inlined in the HTML to begin with (and always has) and only loads other JS when needed, however it will still prefetch scripts for the page in the background so that it is ready in the cache for when it needs to be loaded.

1kB inline sure, no problem! But no 50kB (in three files. Even for a blank page loading unnecessary ~50kB of JS is ridiculous). I have versions of Qwik where I load no javascript at all and I hope future versions will do the same. I have seen youtube videos showing this and it's pretty awesome. I don't understand why it would change. It's the one feature I like most.

**Comment by Dindaleon** [comment]
I understand your point and of course i want immediate action when a user clicks something; however, I would like the scripts to be loaded after the first load, not with it (I don't know if that is how it actually is working at the moment). The way you are putting it sound like that, if so, that's good I guess. I do not want to load ~50kB on the first load, nor when a page is practically a blank page.

**Comment by Dindaleon** [comment]
@jordanw66 I just updated to the latest version and it is beautiful! :heart:

**Comment by gioboa** [comment]
Hey @fmotlagh03, thanks for opening this issue, is it still a valid issue with the latest version of Qwik?

**Comment by gioboa** [comment]
This seems solved.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.

**Comment by nhayhoc** [comment]
![image](https://github.com/BuilderIO/qwik/assets/16068499/77831e15-873b-4ed4-bdd3-1b74c2e3b13a)
Same here, @builder.io/qwik": "^1.4.5"


```
export default component$(() => {
  const PostData = useFetchUrl();

  return (
    <Resource
      value={PostData}
      onPending={() => <Loading />}
      onRejected={(err: any) => (
        <p>looxi roo {err.status ? err.status : err.message} </p>
      )}
      onResolved={(res) => (
        <div class="mb-10">
          <div class="bg-gray-6 ">
            <Wrapper class="relative">
              <h1 class="text-2xl font-bold py-9">
                {res.title ? res.title : "Không tìm thấy tài nguyên"}
              </h1>
              {res.title && <Category>{res.category}</Category>}
            </Wrapper>
          </div>
        </div>
      )}
    />
  );
});

```

In index.tsx it oke, but [slug] first load 50kb js

**Comment by wmertens** [comment]
@nhayhoc can you give more details? What is in those 50kb? Why are they being loaded? Do you have useVisibleTask that triggers loading the framework early?
