### ISSUE TITLE
[🐞] 404 page not working with fastify ssr

### ISSUE THREAD

**Issue by JustinMorritt** [BuilderIO/qwik#3925]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I've added in the Fastify integration and after building then running `npm run deploy` either locally or on my final deployed server I get an Internal Server Error when accessing any page that doesn't exist. I don't have any custom 404 page, also this works fine when running `npm run dev`  i just see the default 404 page. 

![image](https://user-images.githubusercontent.com/8742013/234394896-0853d360-b28e-44a3-ad1f-a71901147310.png)
![image](https://user-images.githubusercontent.com/8742013/234395083-e256a6de-4f50-415a-94a3-10d2c1849c91.png)

### Reproduction

https://stackblitz.com/edit/qwik-starter-7cf2ow?file=.stackblitzrc

### Steps to reproduce

1. go to stack blitz demo
2. navigate to a route that doesn't exist to trigger a 404 
3. see error

### System Info

```shell
  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 1.88 GB / 15.79 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: 0.103.0 => 0.103.0
    @builder.io/qwik-city: 0.104.0 => 0.104.0
    fastify: ^4.15.0 => 4.15.0
    fastify-plugin: ^4.5.0 => 4.5.0
    undici: 5.22.0 => 5.22.0
    vite: 4.3.2 => 4.3.2
```

**Comment by JustinMorritt** [comment]
When I comment out the log in the router's catch block, everything seems to work fine and i get the default 404 page.
![image](https://user-images.githubusercontent.com/8742013/234612814-0245bbea-f631-4787-832d-543b172b1015.png)
I'm suspecting the error is not in the format that pino is wanting ?

**Comment by zanettin** [comment]
closed via https://github.com/BuilderIO/qwik/pull/4879
