### ISSUE TITLE
[📖] "Edit this page" links to wrong path

### ISSUE THREAD

**Issue by fabian-hiller** [BuilderIO/qwik#3939]
### Suggestion

When I click on "Edit this page" on [this](https://qwik.builder.io/docs/integrations/supabase/) page, I get the 404 page from GitHub. Problem is the [`OnThisPage`](https://github.com/BuilderIO/qwik/blob/main/packages/docs/src/components/on-this-page/on-this-page.tsx#L50) component.

**Comment by zanettin** [comment]
Thx for mentioning this @fabian-hiller 🙏 
affects all pages under `integrations`, `deployments`, `community` and under `advanced` the `sitemap` link
