### ISSUE TITLE
[🐞] useOn does not work in dev mode

### ISSUE THREAD

**Issue by literalpie** [BuilderIO/qwik#3945]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am using the `useOn` hook in a component while running in dev mode (no SSR, using `vite --mode dev`). I expect it to work like normal/SSR mode and trigger the callback function when the event is triggered, but this doesn't happen.

I notice that in SSR, where things work as expected, `on:click=...` gets added to the element, but in dev mode, there is no `on:click`.

### Reproduction

https://stackblitz.com/edit/qwik-use-on-document-bug?file=package.json,src%2Froutes%2Findex.tsx

### Steps to reproduce

To see this work, run `npm run start` in the stackblitz. To see it break, run `vite --mode dev`.

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 79.45 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 3.4.1 - /opt/homebrew/bin/yarn
    npm: 9.6.5 - ~/Developer/Web/storybook-framework-qwik/node_modules/.bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.4
    Safari Technology Preview: 16.4
  npmPackages:
    @builder.io/qwik: 0.104.0 => 0.104.0 
    @builder.io/qwik-city: ~0.104.0 => 0.104.0 
    vite: 4.3.2 => 4.3.2
```

### Additional Information

This is causing problems [in storybook-framework-qwik](https://github.com/literalpie/storybook-framework-qwik/issues/51) because the storybook renderer uses the dev mode renderer. 

(as an aside, is it intentional that `npm run dev` does the same thing as `npm run start`? I would expect it to do `vote --mode dev`)

**Comment by manucorporat** [comment]
I think this got fixed by https://github.com/BuilderIO/qwik/commit/477ef908d07cc4eee7460be9ac1abffede640608

**Comment by manucorporat** [comment]
Can you try if this is still a problem in 105?

**Comment by literalpie** [comment]
It's fixed! I tested in both a minimal repro similar to the stackblitz, and in a storybook example. Thank you!
