### ISSUE TITLE
[🐞] useOnWindow does not work in conditionally rendered components

### ISSUE THREAD

**Issue by cmbartschat** [BuilderIO/qwik#3948]
### Which component is affected?

Qwik Runtime

### Describe the bug

Reported here: https://discordapp.com/channels/842438759945601056/1100343282669723669/1100343282669723669

It seems only elements that are part of the initial server-side render will have their window events registered. 

### Reproduction

https://qwik.builder.io/playground/#version=0.104.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwdXNlU2lnbmFsJTJDJTIwJTI0JTJDJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlT25XaW5kb3clMjAlN0QlMjBmcm9tJTIwJTVDJTIyJTQwYnVpbGRlci5pbyUyRnF3aWslNUMlMjIlM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwTGlzdGVuZXIlMjAlM0QlMjBjb21wb25lbnQlMjQoKHByb3BzJTNBJTIwJTdCbmFtZSUzQSUyMHN0cmluZyU3RCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBjb3VudCUyMCUzRCUyMHVzZVNpZ25hbCgwKSU1Q24lNUNuJTIwJTIwdXNlT25XaW5kb3coJ2NsaWNrJyUyQyUyMCUyNCgoKSUyMCUzRCUzRSU3QiUyMCU1Q24lMjAlMjAlMjAlMjBjb3VudC52YWx1ZSUyQiUyQiU1Q24lMjAlMjAlN0QpKSU1Q24lNUNuJTIwJTIwcmV0dXJuJTIwJTNDcCUzRSU3QnByb3BzLm5hbWUlN0QlMjBjb3VudCUzQSUyMCU3QmNvdW50LnZhbHVlJTdEJTNDJTJGcCUzRSU1Q24lN0QpJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwc2hvd2luZ1RvZ2dsZSUyMCUzRCUyMHVzZVNpZ25hbChmYWxzZSklM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ0xpc3RlbmVyJTIwbmFtZSUzRCdhbHdheXMnJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2xhYmVsJTIwZm9yJTNEJ3RvZ2dsZSclM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDaW5wdXQlMjB0eXBlJTNEJ2NoZWNrYm94JyUyMGJpbmQlM0FjaGVja2VkJTNEJTdCc2hvd2luZ1RvZ2dsZSU3RCUyMGlkJTNEJ3RvZ2dsZSclMkYlM0UlMjBTaG93JTIwY29uZGl0aW9uYWwlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGbGFiZWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdCc2hvd2luZ1RvZ2dsZS52YWx1ZSUyMCUyNiUyNiUyMCUzQ0xpc3RlbmVyJTIwbmFtZSUzRCdjb25kaXRpb25hbCclMkYlM0UlN0QlMjAlNUNuJTIwJTIwJTIwJTIwJTNDJTJGJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEKSUzQiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlbmRlclRvU3RyaW5nJTJDJTIwdHlwZSUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwQXBwJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0MlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkYlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE

### Steps to reproduce

1. Click the checkbox to show the conditional Listener
2. Click a few times
3. See that the "always" listener has count increasing, but the "conditional" listener is stuck at 0

### System Info

```shell
Playground/Windows/Firefox
```

**Comment by manucorporat** [comment]
Beautiful bug report! thank you so much!

here's the fix!
https://github.com/BuilderIO/qwik/pull/3955
