### ISSUE TITLE
[🐞] qwik rendering issue caused by chrome extension

### ISSUE THREAD

**Issue by tuurbo** [BuilderIO/qwik#3960]
### Which component is affected?

Qwik Runtime

### Describe the bug

I came a across an issue where the chrome extension Dashlane (a password manager) prepends inputs with an element to assist with autocompleting, which causes some rendering issues. While I understand a 3rd party extension modifying the page isn't Qwik's fault. I wanted to bring it to your attention because there could be other extensions (related or unrelated to Dashlane) that do something similar and break the users page.

### Reproduction

https://stackblitz.com/github/tuurbo/qwik-render-bug?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

I split the demo into 2 parts. 

First half is the bug caused by Dashlane if you want download and test the literal Dashlane extension.
Second half mimics the extension inserting an element in the page.

Clicking the button in the demo will cause the text "(This will disappear)" to be removed.

### System Info

```shell
stackblitz
```

**Comment by tuurbo** [comment]
I updated to Qwik 1.2.11 and simplified the example repo. Not sure if this is bug addressable but leaving this open in case someone wants to take a look.

https://stackblitz.com/github/tuurbo/qwik-render-bug?file=src%2Froutes%2Findex.tsx
https://github.com/tuurbo/qwik-render-bug

**Comment by mhevery** [comment]
Do you know what kind of DOM transformation does the extension do? Do they add elements? Delete comments? Can you send a snippet of what the broken output looks likeL

**Comment by tuurbo** [comment]
From what I remember the dashlane extension would prepend a span element right before every input element. Now it inserts it after the input and no longer breaks my original example repo. I removed that part of the example to show an example of what could break an app. The new simplified version of my repo mimics the old behavior without the extension.

**Comment by mhevery** [comment]
Hmm, that seems like an issue. I imagine this would break other frameworks that rely on correct DOM structure... 

Not sure there is much to do here, so I am going to close the issue. Let me know otherwise.
