### ISSUE TITLE
[🐞] missing doc for in inline components limitation of Slots

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#3988]
a limitation of inline components that needs to be added to the docs

**Comment by moaoa** [comment]
mentioned  [here](https://github.com/BuilderIO/qwik/blob/5bdbd63552e0f42e325319ac3ef912add0ba1abf/packages/qwik/src/core/render/jsx/slot.public.ts#L6)

**Comment by shairez** [comment]
Thanks @moaoa 

I'll change it to a docs issue
