### ISSUE TITLE
[✨] i18n and l10n support

### ISSUE THREAD

**Issue by MohammadMiras** [BuilderIO/qwik#3989]
### Is your feature request related to a problem?

I want to migrate my current website which is multilingual to Qwik, and I don't see any documentation or good online articles regarding this

### Describe the solution you'd like

I would love to be able to support multiple locales for my website. To be able to implement i18n and l10n in my website.

I would like to be able to incorporate locale in the URL. For example, the default locale would be served using default URLs, like `domain.tld` and `domain.tld/about`. But locale-specific pages would be served having a locale in their root path. For example `domain.tld/locale` or `domain.tld/locale/about`.

### Describe alternatives you've considered

I literally have not found anything that I can use. There are very few resources online for Qwik for this issue.

**Comment by ahnpnl** [comment]
Does this doc https://qwik.builder.io/docs/integrations/i18n/#internationalization help you?

**Comment by MohammadMiras** [comment]
@ahnpnl thank your for your help. But that link does not help me at all. It's just a simple post and it only focuses on translation (which in my case is not a concern at all, since API does all the translation).

What I want to know is how can I put the locale inside the URL and omit it from the default locale? Can you help me regarding that?

**Comment by ahnpnl** [comment]
You should check those libraries to see how they work. I use `qwik-speak` and the documentation is pretty good to start with and the author is also very helpful in answering questions in `Discussion` section

**Comment by gioboa** [comment]
Hey @MohammadMiras thanks for the discussion and thanks @ahnpnl for sharing details.
For i18n you can find information [here](https://qwik.builder.io/docs/integrations/i18n/#internationalization) 
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
