### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module[BUG]

### ISSUE THREAD

**Issue by codthing** [BuilderIO/qwik#399]
**Describe the bug**

- When I started the development service according to the official tutorial, I reported this error:

```base
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: 
http://localhost:3000/src/h_main_main_onmount.js
```

- when `yarn build`:

```base
[vite:html-inline-proxy] Could not load 
F:workspaceqwik-appindex.html?html-proxy&index=0.js (imported by index.html): Cannot read property '0' of undefined
error during build:
TypeError: Could not load F:workspaceqwik-appindex.html?html-proxy&index=0.js (imported by 
index.html): Cannot read property '0' of undefined
    at Object.load (F:\workspace\qwik-app\node_modules\vite\dist\node\chunks\dep-9c153816.js:21283:65)
    at F:\workspace\qwik-app\node_modules\rollup\dist\shared\rollup.js:22779:37
error Command failed with exit code 1.
```

**To Reproduce**

1. `npm create qwik@latest`
2. `cd qwik-todo`
3. `yarn`
4. `yarn start`      `yarn build`

**Expected behavior**

**Screenshots**

- yarn start

![image](https://user-images.githubusercontent.com/16655229/163408326-5df3b82a-a909-4e17-8bb9-473e1866865c.png)

- yarn build

![image](https://user-images.githubusercontent.com/16655229/163410038-22530aac-1e87-4781-8154-7b6fedf64c17.png)

**Desktop (please complete the following information):**

```base
windows [10 Pro]
node [14.18.2]
yarn [1.22.17]
npm [8.3.0]
```

```base
"devDependencies": {
    "@builder.io/qwik": "0.0.18-7",
    "@types/express": "4.17.13",
    "@types/node": "17.0.17",
    "express": "4.17.2",
    "typescript": "4.5.5",
    "vite": "2.8.6"
  }
```

**Additional context**

**Comment by igrep** [comment]
Looks duplicate with https://github.com/BuilderIO/qwik/issues/280

**Comment by codthing** [comment]
@igrep 
It's been a long time without any progress on this at all.

**Comment by manucorporat** [comment]
is this still a problem?
