### ISSUE TITLE
[🐞] Build breaks with NODE_ENV != production with qwik 0.105.0: `jsxDEV" is not exported` with mdx files

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#3993]
### Which component is affected?

Qwik Runtime

### Describe the bug

Running the qwik build script with an mdx file in the routes folder and setting NODE_ENV to development causes a build error:

```
1: import { _jsxC, RenderOnce } from '@builder.io/qwik';
2: /*@jsxRuntime automatic @jsxImportSource @builder.io/qwik*/
3: import {Fragment as _Fragment, jsxDEV as _jsxDEV} from "@builder.io/qwik/jsx-dev-runtime";
                                  ^
error during build:
RollupError: "jsxDEV" is not exported by "node_modules/.pnpm/@builder.io+qwik@0.105.0(undici@5.22.0)/node_modules/@builder.io/qwik/core.min.mjs", imported by "src/routes/[...]".
```

### Reproduction

https://github.com/DustinJSilk/qwik-issue-jsxDev-mdx

### Steps to reproduce

- pnpm i
- pnpm build.client
- Observer error

### System Info

```shell
N/A
```

**Comment by manucorporat** [comment]
Should be fixed in 0.106.0!
