### ISSUE TITLE
[✨] Server Timing API for loaders/actions/server$

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#4011]
### Is your feature request related to a problem?

During development, we could add server-timing metrics to loaders, actions and server$. It will helps debug when a response is slow because a loader is taking a long time.

### Describe the solution you'd like

- Human readable ids
- Figure how performance.now() across servers
- Implemenetation based on sharedMap (should be easy)

### Describe alternatives you've considered

Not doing it

### Additional context

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing

**Comment by manucorporat** [comment]
Merged!

**Comment by zanettin** [comment]
soooooo cool! 🙏 🚀
