### ISSUE TITLE
[🐞] Application built for Deno platform does not run on Deno Deploy

### ISSUE THREAD

**Issue by derkoe** [BuilderIO/qwik#4013]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I have create a Qwik app and added the new Deno integration (https://qwik.builder.io/docs/deployments/deno/). When deploying the resulting application to [Deno Deploy](https://deno.com/deploy) the following runtime error occurs:

```
TypeError: Cannot read properties of undefined (reading 'deno')
    at router (file:///src/entry.deno.js:1217:30)
    at serveHttp (file:///src/entry.deno.js:1324:36)
    at eventLoopTick (ext:core/01_core.js:165:11)
```

The issue seems to be that `Deno.version` is undefined in Deno Deploy (see https://github.com/denoland/deploy_feedback/issues/98). 

This filed is used in the middleware here: https://github.com/BuilderIO/qwik/blob/c3998998a08eee6f92ded7d048bd66b9877e6e85/packages/qwik-city/middleware/deno/index.ts#L54
  

### Reproduction

https://github.com/derkoe/qwik-deno

### Steps to reproduce

Clone the repo and deploy it to Deno Deploy

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
    Memory: 26.47 GB / 31.01 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.local/share/rtx/installs/nodejs/18.16.0/bin/node
    npm: 9.5.1 - ~/.local/share/rtx/installs/nodejs/18.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
  npmPackages:
    @builder.io/qwik: 0.107.0 => 0.107.0
    @builder.io/qwik-city: ^0.107.0 => 0.107.0
    undici: 5.22.0 => 5.22.0
    vite: 4.3.3 => 4.3.3
```

**Comment by manucorporat** [comment]
maybe we can remove it in the meantime! cc @adamdbradley
