### ISSUE TITLE
[🐞] Creating a new Qwik app pre-populates the name field instead of using a placeholder

### ISSUE THREAD

**Issue by jordanw66** [BuilderIO/qwik#4026]
### Which component is affected?

Starters / CLI

### Describe the bug

When creating a new Qwik app with versions 0.104.0+ (including 1.0), the name is pre-populated with `./qwik-app` forcing you to erase it, as opposed to the placeholder functionality in previous versions.

I assume this issue was introduced with this commit: https://github.com/BuilderIO/qwik/commit/0d1007351c1710cb1ae366baa6989ac7a4114490

### Reproduction

N/A

### Steps to reproduce

1. Run `npm create qwik@0.103.0` and observe previous behavior.
2. Run `npm create qwik@0.104.0` and observe the bug behavior.

### System Info

```shell
N/A
```

**Comment by manucorporat** [comment]
Also noticed it! is it an easy fix?

**Comment by zanettin** [comment]
will have a look at this 👍
