### ISSUE TITLE
[🐞] `navigate()` to a child route no longer works

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#4032]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Calling navigate to a child route does not navigate and the promise never resolves.
But, navigating to a route 2 levels deep did work.

This this happens in a `useVisibleTask` or a QRL called from a useVisibleTask

```tsx
useVisibleTask$(async () => {
    console.log("This is called");
    await navigate("/demo/");
    console.log("This never runs");
  });
```

### Reproduction

https://github.com/DustinJSilk/qwik-issue-navigate

### Steps to reproduce

Install and run
expect the home page to redirect to /demo/

### System Info

```shell
N/A
```

**Comment by manucorporat** [comment]
There are several issues open about awaits in tasks, notice it's holding the render. This is a cause of a dead-lock, not sure how we can solve this without you dont returning the promise.

**Comment by manucorporat** [comment]
As a workaround:
```tsx
useVisibleTask$(() => {
    console.log("This is called");
    navigate("/demo/").then(() => {
      console.log("This never runs");
    });
  });
  ```

**Comment by DustinJSilk** [comment]
Perfect thanks for taking a look @manucorporat !

**Comment by devpikachu** [comment]
> As a workaround:
> 
> ```tsx
> useVisibleTask$(() => {
>     console.log("This is called");
>     navigate("/demo/").then(() => {
>       console.log("This never runs");
>     });
>   });
> ```
> 
> ie, dont return the promise

Perhaps this should be mentioned on the docs for tasks until (and if) it is fixed, as currently if one hits such an issue, they'd have to find this (or one of the other) issues which is less than ideal.
