### ISSUE TITLE
[🐞] aria-current not updating

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#4041]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm building a `PageLink` component that set `aria-current` to page when the current page is the one described by the href.
It works well except that the first anchor is not updated on page change. 
I suppose it has to do with the `useLocation`, but I'm not sure.

```jsx
import { component$, Slot, useComputed$ } from '@builder.io/qwik';
import { useLocation, Link } from '@builder.io/qwik-city';
import type { LinkProps } from '@builder.io/qwik-city';

const normalize = (pathname: string) => {
  return pathname[pathname.length - 1] === '/'
    ? pathname.slice(0, -1)
    : pathname;
};

export const PageLink = component$((props: LinkProps) => {
  const { url } = useLocation();
  if (!props.href) throw new Error('PageLink should have a href');
  const href = props.href;
  const current = useComputed$(() =>
    normalize(href) === normalize(url.pathname) ? 'page' : undefined
  );
  return (
    <Link {...props} aria-current={current.value}>
      <Slot />
    </Link>
  );
});
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-frgqvy?file=src/components/page-link.tsx

### System Info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 16.69 GB / 31.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1095.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: 1.0.0 => 1.0.0
    @builder.io/qwik-city: 1.0.0 => 1.0.0
    undici: 5.22.0 => 5.22.0
    vite: 4.3.3 => 4.3.3
```

**Comment by manucorporat** [comment]
Gonna look into this issue, but also thinking `<Link>` could do this built-in!

**Comment by GrandSchtroumpf** [comment]
Yes that would be cool if Link was doing it by default. Another issue I had with Link, but not really related to this issue, is that we cannot hook the new view transition api into it: https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API
I can use `useNav` and a button instead but I loose a lot of a11y and preloading...

**Comment by manucorporat** [comment]
Not sure what you mean, yes you can, we even have a demo built with View Transitions:
https://pics-qwik.pages.dev/

**Comment by GrandSchtroumpf** [comment]
oh wow ! I'm sorry I should have looked more into the code before talking 😅.
I think that is worth been mentioned in the doc 😊

**Comment by GrandSchtroumpf** [comment]
Awesome. I'm a little bit confused why this PR would make it work when location changes while it's currently not updating though.
Thanks for the update !

**Comment by GrandSchtroumpf** [comment]
It might be an over-optimization if the tag doesn't react without clicking on it. It means that the only way to add/remove the aria-current is to do it with the Dom api with `el.setProperty` ?

**Comment by GrandSchtroumpf** [comment]
@jordanw66 thanks for the detailed answer and issue. 
I'll close this one in favor of your then.
