### ISSUE TITLE
[🐞] `service-worker.js` with non-root `basePathname` is not being generated properly

### ISSUE THREAD

**Issue by jessezhang91** [BuilderIO/qwik#4043]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I am building a production build of an application with `basePathname`. I expect the `service-worker.js` to cache build files. What actually is happening is the generated `service-worker.js` does not have `appBundles`, `linkBundles`, etc. variables defined because the qwik-city vite plugin is looking for the `service-worker.js` in the wrong place due to `basePathname` being defined.

### Reproduction

n/a

### Steps to reproduce

1. Create a new qwik project w/ the express integration
2. Define a non-root `base` in the `vite.config.ts`
3. Run `npm run build`
4. Check the browser networks tab to verify that the service worker is not intercepting any requests to cache.
5. Check the generated `dist/<base>/service-worker.js` file is missing the `appBundles`, `linkBundles`, etc. variables at the top of the file.

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 8.08 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox Developer Edition: 113.0
    Safari: 16.4
  npmPackages:
    @builder.io/qwik: ^1.0.0 => 1.0.0 
    @builder.io/qwik-city: ^1.0.0 => 1.0.0 
    undici: ^5.22.0 => 5.22.0 
    vite: 4.3.4 => 4.3.4
```

### Additional Information

I believe this was caused by https://github.com/BuilderIO/qwik/pull/3994

**Comment by manucorporat** [comment]
fixed by https://github.com/BuilderIO/qwik/pull/4044
