### ISSUE TITLE
 [📖] tutorial: recursive store is outdated

### ISSUE THREAD

**Issue by aivarsliepa** [BuilderIO/qwik#4067]
### Suggestion

Part of the tutorial about [recursive store](https://qwik.builder.io/tutorial/store/recursive) is outdated.
Now `useStore()` tracks objects deeply by default.

We could either:
* remove this section entirely
* teach the inverse scenario where it's possible to remove this deep reactivity by providing `{deep: false}` to options.

**Comment by theunhackable** [comment]
I would like to work on this

**Comment by aivarsliepa** [comment]
This was fixed in #4072
