### ISSUE TITLE
[DOCS] Link to web.dev case studies page for real-world examples

### ISSUE THREAD

**Issue by bradfrosty** [BuilderIO/qwik#407]
**How can the documentation be improved?**

The link to web.dev on the Qwik landing page takes you to the web.dev landing page. It seems like it should link to the [web.dev Case Studies](https://web.dev/tags/case-study/) page.

On a related note, you might consider linking to [wpostats.com](https://wpostats.com/). The web.dev case studies page is not always about performance, but wpostats is strictly performance case studies. It aggregates posts (including from web.dev) that highlight the business value of perf.

**Comment by SkyDiverCool** [comment]
I want to take this on.

I think linking to web.dev case studies is better that wpostats due to web.dev being more widely known/familiar to developers.

Also I think adding links to the articles shown in the table is a good idea to allow people to read the full article if they are interested in it.

**Comment by ImBIOS** [comment]
I agree with this, here #951 I've made PR

**Comment by zanettin** [comment]
since the PR got merged, we should close the issue as well 👍  cc: @shairez 🙏

**Comment by shairez** [comment]
thanks @bradfrosty @ImBIOS and @zanettin !
