### ISSUE TITLE
[✨] improve 404 pages

### ISSUE THREAD

**Issue by naorpeled** [BuilderIO/qwik#4085]
At the moment when you reach a 404 page in a QwikCity app,
you only see a 404 message.

What I'm proposing is that in addition to the message,
you'll also see all the available routes, like what Gatsby does ([here](https://www.gatsbyjs.com/static/ea5e1e0405ce033127573ac8a5dd3508/0b569/gatsby-default-404.png)).

@manucorporat this is something we've discussed a while ago but didn't have the time to implement it.
Let me know if this is greenlit, if so I'd like to take this task now.

**Comment by theunhackable** [comment]
Hello! Can you assign this to me? I would like to work on it...

Thank You 🙏🏻

**Comment by adamdbradley** [comment]
Yeah looks like a great idea! This is where the generic 404 html lives: https://github.com/BuilderIO/qwik/blob/47c4de6465dfce48220b1e1cf5e1c92ec9e43b85/packages/qwik-city/middleware/request-handler/error-handler.ts#L10

This is where the 404 is created during development: https://github.com/BuilderIO/qwik/blob/47c4de6465dfce48220b1e1cf5e1c92ec9e43b85/packages/qwik-city/buildtime/vite/dev-server.ts#L252

Would love to get a PR adding this feature! Thanks

**Comment by naorpeled** [comment]
> Yeah looks like a great idea! This is where the generic 404 html lives: https://github.com/BuilderIO/qwik/blob/47c4de6465dfce48220b1e1cf5e1c92ec9e43b85/packages/qwik-city/middleware/request-handler/error-handler.ts#L10
> 
> This is where the 404 is created during development: https://github.com/BuilderIO/qwik/blob/47c4de6465dfce48220b1e1cf5e1c92ec9e43b85/packages/qwik-city/buildtime/vite/dev-server.ts#L252
> 
> Would love to get a PR adding this feature! Thanks

Awesome, will start working on it ASAP!
