### ISSUE TITLE
[🐞] ESLint rules do not point to their docs

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#4097]
### Which component is affected?

Qwik Runtime

### Describe the bug

If an ESLint rule finds an issue, it will have a URL that points to `https://github.com/BuilderIO/qwik` instead of a more specific URL:

<img width="956" alt="CleanShot 2023-05-07 at 13 43 06@2x" src="https://user-images.githubusercontent.com/1393142/236690861-ee012634-3158-4065-9ff4-2e079e3a3a41.png">

https://github.com/BuilderIO/qwik/blob/b98019567447814833f31e08ae9df0855fc04765/packages/eslint-plugin-qwik/src/loaderLocation.ts#L23

### Reproduction

N/A

### Steps to reproduce

https://github.com/BuilderIO/qwik/blob/b98019567447814833f31e08ae9df0855fc04765/packages/eslint-plugin-qwik/src/loaderLocation.ts#L23

### System Info

```shell
N/A
```

### Additional Information

I'm not sure what the best URL is for this particular eslint rule, but also some other rules also don't point to docs that explain valid/invalid code:

https://github.com/BuilderIO/qwik/blob/b98019567447814833f31e08ae9df0855fc04765/packages/eslint-plugin-qwik/src/unusedServer.ts#L10-L11

https://github.com/BuilderIO/qwik/blob/b98019567447814833f31e08ae9df0855fc04765/packages/eslint-plugin-qwik/src/useMethodUsage.ts#L12

**Comment by zanettin** [comment]
Hi @samijaber 

My idea would be to offer smth similar to https://eslint.org/docs/latest/rules/. So an overview with all `qwik` eslint rules + a detail view where we explain good and bad examples.

i quickly hacked the overview together:
![localhost_3000_docs_advanced_eslint_](https://user-images.githubusercontent.com/3241476/236922749-e5725a4b-7a2b-40b5-9d83-3d3e1edae744.png)

Is this going into the direction you thought about @samijaber ?
And @manucorporat what do you think? continue or go with another solution instead?

**Comment by manucorporat** [comment]
i would love it so much!
