### ISSUE TITLE
[📖] add docs for `useId`

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#4120]
### Suggestion

We need to document the `useId` api.

@n8sabes  -  do you think it's feasible to throw a quick doc (using chatgpt based on #2468)  for this API ?

If you don't have time that's cool, but you're the obvious first person as you're the great magician who implemented it :)

At any case, thanks! 🙏

**Comment by gioboa** [comment]
@n8sabes if for you it's ok I will create the doc section for this. Let me know.

**Comment by n8sabes** [comment]
@gioboa, Thanks for prodding me on this issue. I have something written up and will submit a PR this weekend. I was thinking about putting it just after [Component>Overview just after Getting hold of DOM element](https://qwik.builder.io/docs/components/overview/#getting-hold-of-dom-element) -- what do you guys think?

**Comment by gioboa** [comment]
After ref description sounds good to me
