### ISSUE TITLE
CLI documentation link points to 404 page[🐞]

### ISSUE THREAD

**Issue by joschan21** [BuilderIO/qwik#4121]
### Which component is affected?

Qwik City (routing)

### Describe the bug

If you make a mistake using the routeAction$, the linked documentation page is a 404 - resource not found.

`  16:22  warning  `routeAction$()` can only be declared in `layout.tsx`, `index.tsx` and `plugin.tsx` inside the `src/routes` directory, instead it was declared in "C:/Users/Josch/Desktop/qwik-test/src/components/starter/counter/counter.tsx".
Please check the docs: https://qwik.builder.io/qwikcity/loader  qwik/loader-location`

Cheers

### Reproduction

https://qwik.builder.io/qwikcity/loader

### Steps to reproduce

I tried this inside of the default counter component, that's how the error popped up:

`
  const useRequest = routeAction$((props) => {
    console.log('make req')
  })`

### System Info

```shell
Windows 10, not relevant tho
```

**Comment by whale2002** [comment]
It has been resolved.
https://github.com/BuilderIO/qwik/pull/4153
