### ISSUE TITLE
[📖] Add docs for eslint-plugin-qwik

### ISSUE THREAD

**Issue by AethesticCoder** [BuilderIO/qwik#4136]
### Suggestion

Hello i want to modify the qwik eslint rules so i can have a custom eslint than fix my needs but i dont see where is the doc of all the rules in eslint-plugin-qwik

**Comment by zanettin** [comment]
Hi @LuisCoderDev 
We're working on smth in this direction (#4097). Till this is released you find all the rules and the presets here https://github.com/BuilderIO/qwik/blob/main/packages/eslint-plugin-qwik/index.ts. Does this help for now?

**Comment by LuisCoderDev** [comment]
it help a little bit, yes the rules are there but they don't have a description, so i have to figure out what the rule make

**Comment by zanettin** [comment]
yes that is correct. as written above, it's currently on my desk to create a dedicated page for it 🎉 thanks for your patience 🙏

**Comment by zanettin** [comment]
quick update: the PR is now finalized and will be available soonish. (https://github.com/BuilderIO/qwik/pull/4137). i'll close this issue for now. please feel free to re-open it when needed 🙏
