### ISSUE TITLE
[🐞] Mapped array of objects no re-render on changes

### ISSUE THREAD

**Issue by rainyEra** [BuilderIO/qwik#4140]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am rendering array of objects with different properties. On Click Checkbox I expect my mapped array to re-render to apply conditional styles, but it's not reflecting changes. Even if I add more items to array — no re-renders.

### Reproduction

https://codesandbox.io/p/sandbox/my-qwik-basic-starter-u1wjyw?file=%2Fsrc%2Froutes%2Findex.tsx%3A1%2C1

### System Info

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 313.01 MB / 1.63 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @builder.io/qwik: ^0.100.0 => 0.100.0 
    @builder.io/qwik-city: ^0.100.0 => 0.100.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

**Comment by manucorporat** [comment]
I would recommend to update to latest qwik, 1.0.0

**Comment by rainyEra** [comment]
> I would recommend to update to latest qwik, 1.0.0

Oh my god.. I was using codesandbox template... Thanks!!
