### ISSUE TITLE
[🐞] Failed to install dependency (v1.1.0)

### ISSUE THREAD

**Issue by gabriiels** [BuilderIO/qwik#4141]
### Which component is affected?

Starters / CLI

### Describe the bug

Failed to install dependency

![fix-qwik-1](https://github.com/BuilderIO/qwik/assets/49616724/2da1d2a3-fd52-4e96-ac85-9786ed071fb9)

![fix-qwik-2](https://github.com/BuilderIO/qwik/assets/49616724/3ebfa778-bb69-4441-9f34-6c0a1ec1c51c)

System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS

**Comment by manucorporat** [comment]
I cant reproduce the issue!

**Comment by manucorporat** [comment]
what error do you get when doing pnpm install manually?

**Comment by manucorporat** [comment]
Should be fixed now! published manually! thank you! it got messed up by a wrong release script

**Comment by manucorporat** [comment]
Thank you for letting us now! somehow on my compuler it was installing correctly, maybe some locally linked version. no idea!
