### ISSUE TITLE
[🐞] scss imports dont work well

### ISSUE THREAD

**Issue by AesthetiCoder** [BuilderIO/qwik#4144]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

i am importing some mixins and variables in main.scss but i get this error in my scss file.

looks like the order of imports in scss is not correct, or vite with qwik dont work well with this type of scss.

also the styles load well just is the modal error that i get from qwik vite i think, if you run pnpm build also fail the build because this error

```js
[sass] Undefined mixin.
  ╷
3 │ ┌   @include responsive(desktop)
4 │ │   {
5 │ │     font-size: 75%;
6 │ └   }
  ╵
  src\global\style\base\_base.scss 3:3  root stylesheet
```

### Reproduction

https://github.com/LuisCoderDev/qwik-scss

### Steps to reproduce

just install all dependencies and run `pnpm dev` after that you will see the error of the imports, there are just varaiables colors in other files in the style folder, all the imports are well organize but still getting this error, this doesn't happen to me in other framework

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 6.56 GB / 15.87 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/qwik: 1.1.0
    @builder.io/qwik-city: ^1.1.0
    undici: ^5.22.0 => 5.22.0
    vite: 4.3.3 => 4.3.3
    sass: ^1.62.1
```

**Comment by manucorporat** [comment]
Most likely related to https://github.com/vitejs/vite/issues/11837

Qwik supports scss through vite

**Comment by AesthetiCoder** [comment]
Hello the [vite issue](https://github.com/vitejs/vite/issues/11837) is closed and the error still persist in qwik

**Comment by AesthetiCoder** [comment]
No update ?

**Comment by AesthetiCoder** [comment]
3 months and it looks like qwik still don't work well with sass

**Comment by gioboa** [comment]
Hey @AesthetiCoder , thanks for opening this issue 👍 
I linked the PR that solves this issue.
So I'm closing this for now, feel free to re-open it if it's still an issue for you.
