### ISSUE TITLE
[📖] Qwik Homepage - color transition

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/qwik#4146]
### Suggestion

The Qwik homepage has a really nice blend of colors and a smooth slider animation for the showcase. I think to match this a subtle transition on the colors of the tab component would fit well. It allows the font-color to transition from de-emphasized to emphasized without a very sudden change to the user.

CSS declaration used:
transition: color 300ms ease;

With transition
https://gyazo.com/3ccf9d6fbaffad77198ff444ae274530

Without transition
https://gyazo.com/eec77a249151794951e29895aa62a316

Let me know what you think!

**Comment by manucorporat** [comment]
sure! can you open a PR? happy to merge

**Comment by thejackshelton** [comment]
> sure! can you open a PR? happy to merge

I don't think I can since it's the Qwik homepage, right?

**Comment by zanettin** [comment]
that is correct @thejackshelton 👍

**Comment by adamdbradley** [comment]
Thanks for opening the issue and providing the CSS. At one point we did have a transition like that, but later decided we like the faster transition. I think for now we'll keep it as is. Thanks.

**Comment by adamdbradley** [comment]
Welp I take that back! After a bit more chatting it over looks like we'll update the transition to what you suggested. Thanks!

**Comment by thejackshelton** [comment]
Sure thing! Anything for my favorite framework haha
