### ISSUE TITLE
[📖] generic types like `React.ComponentProps<'button'>`

### ISSUE THREAD

**Issue by DanavsSite** [BuilderIO/qwik#4148]
### Suggestion

does this feature even exist?

**Comment by zanettin** [comment]
Hi @DanavsSite 👋 
Thanks for this question. 
Qwik offers generics to type the props like so:

```
type MyProps = {
  name: string,
  age: number,
}

export default component$<{name: string, age: number}>((props) => { ... }
export default component$<MyProps>((props) => { ... }
export default component((props: MyProps) => { ... }
```

hope this helps 🙏

**Comment by cmbartschat** [comment]
I think what this issue is asking about is `QwikIntrinsicElements["button"]` which represents all the attributes a native html button supports. Would be good to document somewhere since Qwik is typescript-first, though I don't think react doesn't even document `React.ComponentProps`, they just have: https://react.dev/reference/react-dom/components/common

**Comment by shairez** [comment]
Good idea @cmbartschat !

Want to help us with a PR for that?

**Comment by hbendev** [comment]
I guess we should extend the docs about the [provided interface itself](https://qwik.builder.io/api/qwik/#qwikintrinsicelements), and add a small documentation about native html attributes under the "Components" docs page. Maybe under the [`Overview`](https://qwik.builder.io/docs/components/overview/) or the[ `Rendering`](https://qwik.builder.io/docs/components/rendering/) menus.

**Comment by hbendev** [comment]
Another related thing I discovered is that therer are separate `DOMAttributes` and `QwikDOMAttributes` interfaces defined, with only the latter being exported from qwik.

However, the current `DOMAttribues` interface is already a "Qwik"-specific type based on the definition: [`interface DOMAttributes<T> extends QwikProps<T>, QwikEvents<T>`](https://github.com/BuilderIO/qwik/blob/b47453c2529ab26b185098c2cc0720a12db908ea/packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts#LL274C1-L274C70). Shouldn't this be renamed to `QwikDOMAttributes` and be exported directly?
