### ISSUE TITLE
[🐞] Hot reloading do not work in Tailwind CSS

### ISSUE THREAD

**Issue by Easy-Cloud-in** [BuilderIO/qwik#4159]
### Which component is affected?

Qwik Runtime

### Describe the bug

Hot reloading not working when we modify Tailwind CSS class in Qwik latest version.

Removed all the defaults in global css.

### Reproduction

 Tailwind CSS

### Steps to reproduce

 Tailwind CSS

### System Info

```shell
win 10, node 16.X
```

**Comment by gioboa** [comment]
Hey @Easy-Cloud-in, thanks for opening this issue.
I tried with the latest version of Qwik and it's working fine.
Can you provide the steps to reproduce this issue please?

**Comment by gioboa** [comment]
This seems solved.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
