### ISSUE TITLE
[✨] Serialize Set & Map

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#4164]
### Is your feature request related to a problem?

I use `Set` & `Map` a instead of `Array` & `Object` as more and more developers are doing these days (even recommended by Steve from builder.io: https://www.youtube.com/watch?v=hubQQ3F337A)
But in Qwik I stopped using it as it required a lot of back and forth between `Set` & `Array` and `Map` and `Object` to store the state.
It would be a great developer experience improvement to serialize these primitives.

### Describe the solution you'd like

Currently qwik serialize some JS primitives like BigInt & Date. I think `Set` & `Map` should be serialized too as they are very useful to manage state.
Maybe the `{ deep: true }` option in `useStore` might be an issue, but I think it could be ignored for Set & Map (if this is an issue)

### Describe alternatives you've considered

Use Object & Array

**Comment by Dindaleon** [comment]
Yeah, this would be great!

**Comment by manucorporat** [comment]
Love it so much!

**Comment by manucorporat** [comment]
I will look into it! Should not be hard

**Comment by barel-mishal** [comment]
I just look into this feature and notice that it does not work when I use empty set just when I add into a set some data then it not error. 

another thing this is updating but it not reactive for some reason:
![image](https://github.com/BuilderIO/qwik/assets/56759851/96f57579-bd97-4bb9-8971-781f9ea09cb5)

in the photo you can see the number 1 this is because I use new Set([""]) so the size is start. 

this is the code I use on empty index.tsx:
```tsx
import { component$, useComputed$, useSignal } from "@builder.io/qwik";

export default component$(() => {
    const signalSet = useSignal(new Set<string>([""]));
    const computeSize = useComputed$(() => signalSet.value.size);
    
    return <div class={'flex gap-3 flex-col'}>
        <div>
            {computeSize.value}
        </div>
        <button onClick$={() => {
            signalSet.value.add(Math.random().toString());
            console.log(signalSet.value);
            }} class={'p-3 rounded-md bg-sky-800 m-2 text-sky-50'}>Add</button>
    </div>
});
```

**Comment by mhevery** [comment]
> Hey, i'm facing the same problem. Set's are not reactive?

Unfortunately, they are not. Not much we can do about that.
