### ISSUE TITLE
[🐞] drop event not working

### ISSUE THREAD

**Issue by PatrickJS** [BuilderIO/qwik#4167]
### Which component is affected?

Qwik Runtime

### Describe the bug

drag and drop doesn't work because of a few things.
* drop event is not firing off
* dataTransfer api doesn't work without drop and dragstart
* it seems like you need to active all events before it will work so maybe an issue with qwikLoader?
* you have to use `ref` and not `event.target`

This is likely an issue with async functions and dataTransfer needs to be available synchronously. 

### Reproduction

https://stackblitz.com/edit/qwik-starter-sv2ndq?file=src%2Froutes%2Findex.tsx,src%2Froutes%2Flayout.tsx

### Steps to reproduce

stackblitz.

use html drag and drop api

### System Info

```shell
chrome
```

### Additional Information

I also only ran this in dev. If I fire off the qrl and use ref then I need to active each event before everything to work correctly (stackblitz example would need to be updated to show my workaround)

**Comment by manucorporat** [comment]
Unfortunately it's one of this events that must be handled syncronously, not good way to solve it, but there is a workaround:
https://qwik.builder.io/docs/components/events/#synchronous-event-handling
