### ISSUE TITLE
[🐞] [integrations, vitest] Watchmode does not recognize component's template changes

### ISSUE THREAD

**Issue by GregOnNet** [BuilderIO/qwik#4168]
### Which component is affected?

Qwik Runtime

### Describe the bug

- When I test a Component and edit the JSX-Template to make a red test green, the test still fails
- After restarting vitest the test is green.
- 🎥 [See the video for a detailed explanation](https://www.loom.com/share/2b5b495ba85f4f15a0a49b7703d4b279)

### Reproduction

https://github.com/GregOnNet/qwik-qwikify-mui-

### Steps to reproduce

Same setup like in https://github.com/BuilderIO/qwik/issues/4162

```
git clonse https://github.com/GregOnNet/qwik-qwikify-mui-
cd qwik-qwikify-mui-
pnpm install
pnpm test.unit # The test fails, it is expected

# Open a 2nd terminal session and run

git checkout test-passes # the test still fails, but should pass

# Vitest will rerun the test, but the test will be red
# After restarting vitest the test will be green.
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 15.93 GB / 31.90 GB
  Binaries:
    Node: 18.15.0 - ~\AppData\Local\fnm_multishells\22708_1683784793077\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.0 - ~\AppData\Local\fnm_multishells\22708_1683784793077\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.22621.1
```

**Comment by GregOnNet** [comment]
Hi,

i just noticed that I forgot to push `main`. That's why the issue was not reproducable.
I pushed the missing commit and the reproduction should work now.

Thanks @gioboa for pointing it out. 🤗

**Comment by GregOnNet** [comment]
I just updated to Qwik `1.2.13` and vitest `0.34.6`. And the error does not occur any more.

That's why I close this issue.

**Comment by gioboa** [comment]
Thanks @GregOnNet
