### ISSUE TITLE
[🐞]i want to use ant design ui ,but it use less。did qwik support less?

### ISSUE THREAD

**Issue by doudouma** [BuilderIO/qwik#4169]
### Which component is affected?

Qwik Runtime

### Describe the bug

[🐞]i want to use ant design ui ,but it use less。did qwik support less?

### Reproduction

null

### Steps to reproduce

null

### System Info

```shell
null
```

**Comment by manucorporat** [comment]
yes! you can use less!
https://qwik.builder.io/docs/components/styles/#css-preprocessors
