### ISSUE TITLE
[🐞] request.headers are empty in `routeLoader$` , `routeAction$` and `globalAction$`

### ISSUE THREAD

**Issue by aivarsliepa** [BuilderIO/qwik#4175]
### Which component is affected?

Qwik City (routing)

### Describe the bug

```typescript
export const useExample = routeLoader$(async requestEv => {
  console.log(requestEv.headers); // this is empty
  console.log(requestEv.request.headers); // workaround - this contains all the headers
  return "example";
});
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-schx2x?file=src%2Froutes%2Flayout.tsx

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 19.64 GB / 31.95 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 113.0.5672.93
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^1.1.1 => 1.1.1
    @builder.io/qwik-city: ^1.1.1 => 1.1.1
    undici: 5.22.0 => 5.22.0
    vite: 4.3.3 => 4.3.3
```

### Additional Information

This has some further implications, that `@supabase/auth-helpers-qwik` is causing error, when server client's `auth.getUser()` is called.

```
Error: The "host" request header is not available
    at isSecureEnvironment (D:\src\qwik-app\node_modules\@supabase\auth-helpers-shared\dist\index.js:216:11)
    at Object.removeItem (D:\src\qwik-app\node_modules\@supabase\auth-helpers-shared\dist\index.js:394:31)
    at D:\src\qwik-app\node_modules\@supabase\gotrue-js\dist\main\lib\helpers.js:145:19
    at Generator.next (<anonymous>)
    at D:\src\qwik-app\node_modules\@supabase\gotrue-js\dist\main\lib\helpers.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (D:\src\qwik-app\node_modules\@supabase\gotrue-js\dist\main\lib\helpers.js:27:12)
    at removeItemAsync (D:\src\qwik-app\node_modules\@supabase\gotrue-js\dist\main\lib\helpers.js:144:43)
    at SupabaseAuthClient.<anonymous> (D:\src\qwik-app\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:1105:53)
    at Generator.next (<anonymous>)
```

**Comment by aivarsliepa** [comment]
Looking at the source code, it looks like `requestEvent.headers` are intended to be **response** headers:
* [type definition](https://github.com/BuilderIO/qwik/blob/977dd1ca9817c1ef839f577bf7c487cd64cadca9/packages/qwik-city/middleware/request-handler/types.ts#LL240C1-L240C1)
* [send()](https://github.com/BuilderIO/qwik/blob/977dd1ca9817c1ef839f577bf7c487cd64cadca9/packages/qwik-city/middleware/request-handler/request-event.ts#L75)

However:
* in [docs](https://github.com/BuilderIO/qwik/blob/977dd1ca9817c1ef839f577bf7c487cd64cadca9/packages/qwik-city/middleware/request-handler/request-event.ts#L75) it says otherwise.
* in [supabaseClient](https://github.com/BuilderIO/qwik/blob/977dd1ca9817c1ef839f577bf7c487cd64cadca9/packages/supabase-auth-helpers-qwik/src/utils/createSupabaseClient.ts#LL143C1-L143C1) usage is also as **request** headers

**Comment by manucorporat** [comment]
What you describe as workaround is actually the correct way:

`ev.headers`: response headers
`ev.request.headers`: request headers (they ones you read)


Add some extra docs!
https://github.com/BuilderIO/qwik/pull/4184

**Comment by aivarsliepa** [comment]
Follow up PR #4185
