### ISSUE TITLE
[📖] Include showcase of class prop

### ISSUE THREAD

**Issue by devagja** [BuilderIO/qwik#4179]
### Suggestion

https://qwik.builder.io/docs/components/styles/#styles

Hello, 
I have noticed in several Qwik projects that they use prop className instead of class. 
I think it should be more widely known how to extend the component's class in docs.

https://github.com/BuilderIO/qwik/pull/4114

The description in this PR is quite intuitive. We could include it in the documentation.

**Comment by manucorporat** [comment]
Would u like to open a PR? i think it would be a great addition!

**Comment by devagja** [comment]
sure! 
https://github.com/BuilderIO/qwik/pull/4197/files

**Comment by manucorporat** [comment]
Fixed! https://github.com/BuilderIO/qwik/pull/4197
