### ISSUE TITLE
[🐞] Getting started issues

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#4182]
### Which component is affected?

Starters / CLI

### Describe the bug

I created an empty dir, changed into it and ran `pnpm create qwik@latest`

This failed, because pnpm didn't see a package.json in the directory.

Then I did `npm create qwik@latest`. This launched the wizard.

Then it asked where to put it, and said I could use `.` or `./` for the current directory. I did `.`.

Then it said that the directory `.` already existed and wasn't empty. I told it to remove and create.

That installed everything but afterwards I was still in the deleted `.` directory, and I had to do `cd $PWD` to go into the new directory

### Reproduction

about:new

### System Info

```shell
System:
    OS: Linux 5.15 NixOS 22.11 (Raccoon) 22.11 (Raccoon)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 5.42 GB / 15.20 GB
    Container: Yes
    Shell: 5.1.16 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nix-profile/bin/node
    Yarn: 1.22.15 - ~/bin/yarn
    npm: 9.5.0 - ~/.nix-profile/bin/npm
  npmPackages:
    @builder.io/qwik: ^1.1.1 => 1.1.1 
    @builder.io/qwik-city: ^1.1.1 => 1.1.1 
    undici: 5.22.0 => 5.22.0 
    vite: 4.3.5 => 4.3.5
```

**Comment by adamdbradley** [comment]
Would you be able to copy and paste the entire interaction? I'd like to make sure I understand the incorrect flow. Thanks

**Comment by wmertens** [comment]
pnpm in an empty dir fails:

```
🍀 🐚  Sat May 13 00:18:37 ~/Projects/sync-ui-qwik
13748 $ pnpm create qwik@latest
 ERROR  No package.json (or package.yaml, or package.json5) was found in "/home/wmertens/Projects/sync-ui-qwik".
```

this is with npm:

```
◇  Where would you like to create your new project? (Use '.' or './' for current directory)
│  .
│
●  Creating new project in  /home/wmertens/Projects/sync-ui-qwik  ... 🐇│
◇  Directory "./" already exists and is not empty. What would you like to do?
│  Overwrite and replace this directory
│

[...]

○  Result ────────────────────────────────────────────────╮
│                                                         │
│  🦄  Success!                                           │

[...]

└  Happy coding! 🐇
direnv: error LoadConfig() Getwd failed: getwd: no such file or directory
🍀 🐚  Fri May 12 16:47:56 ~/Projects/sync-ui-qwik
13747 $ npm i
/nix/store/njh6p007ymbmcgas5l7sqqxfmm394zx1-nodejs-18.15.0/lib/node_modules/npm/lib/cli.js:48
    throw err
    ^

Error: ENOENT: no such file or directory, uv_cwd

[...]

🍀 🐚  Fri May 12 16:48:30 ~/Projects/sync-ui-qwik
13749 $ cd $PWD
🍀 🐚  Fri May 12 16:48:36 ~/Projects/sync-ui-qwik on master
13750 $ npm i

added 310 packages, and audited 311 packages in 4s
```

**Comment by gioboa** [comment]
Hey @wmertens, thanks for opening this issue, I saw that this steps are working with the latest version of Qwik, btw a lot of things happened during this months. 🚀
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
