### ISSUE TITLE
[🐞] Reactivity Issue with Parameter Assignment in Store

### ISSUE THREAD

**Issue by barel-mishal** [BuilderIO/qwik#4190]
### Which component is affected?

Qwik Optimizer (Rust) - I am not certain if this is the actual issue, but among the available options, it seems to be the most fitting.

### Describe the bug

Bug Details:
There is an issue with the 'onInput' function. While the button passes the value and it is visible, the value of 'name' does not exhibit similar behavior.

Cause:
The issue occurs because, in the store, the parameter does not get reassigned upon creation, leading to a disruption in reactivity. Below is an image demonstrating how the store is defined see the 

I have reimplemented the issue, but I am unsure how to describe it effectively. I would like to direct you to this link so you can review the code yourself: https://github.com/barel-mishal/no-reactive

### Reproduction

https://github.com/barel-mishal/no-reactive

### Steps to reproduce

run the qwik project as usual:
npm start or npm run dev

try push the button it works (the nItems are hardcoded in the object). But in the input try to put some text you should see some text but you don't 

### System Info

```shell
I Saw other like me so it probably not just my computer. 

I am working on wsl latest version of qwik
```

### Additional Information

no additional

**Comment by manucorporat** [comment]
Should be fixed in here:
https://github.com/BuilderIO/qwik/pull/4186

Downgrade to `1.0.0` or wait for `1.1.2` we might release today!
