### ISSUE TITLE
[📖] Ecosystem - replace @qwikest/icons with icônes.js

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/qwik#4192]
### Suggestion

On the Qwik Ecosystem page one of the top libraries is @qwikest/icons. While everyone loved the DX of the package, it hasn't been working since the 1.0 release to my knowledge.

I've had several conversations with Qwik community members that have been flustered with the icon library. In each conversation I've been recommending the use of https://icones.js.org/ instead, due to the Qwik integration and availability of icons.

From what I understand the creator of the package is working on several other projects outside of it, and it will be a while before he gets back around to it.

If this package could be removed from the ecosystem page with icônes in its place that would be much appreciated. Then when the author or any contributors get the package working again we can make a PR for it as an integration.

Discord Channel References:
https://discord.com/channels/842438759945601056/1105851336169357374
https://discord.com/channels/842438759945601056/1106222651355176960
https://github.com/qwikest/icons/issues/10
https://github.com/qwikest/icons/issues/11

**Comment by NiklasPor** [comment]
FYI we just fixed the entrypoint and package size problems in version `0.0.8`. I'm sorry for the inconveniences caused 😢 Let's see if everything is going fine now. manus suggestion helped a lot 👀

**Comment by manucorporat** [comment]
hey jolks!

is it working now? i am fine to rearrange in the docs, not strong opinions here. The docs for icons are important when people search, or Qwik AI to provide some reasonable answer :)

**Comment by da8ah** [comment]
Yes it is working now. I just test it with qwik (latest 1.1.2 & 0.107.0) and @qwikest/icons (v0.0.8) + tailwind too.

There's still the warnings but idk if they are actually from qwik. Anyhow, now icons are ready to go.
Lots of thanks to @NiklasPor for all the hard work!

![image](https://github.com/BuilderIO/qwik/assets/62577449/2c0ac0c7-8e3e-4055-935c-44eb15dbd805)
![image](https://github.com/BuilderIO/qwik/assets/62577449/fe2b7b63-84f1-4762-9b72-db17c07334ca)

**Comment by NiklasPor** [comment]
Other libraries are also facing the warnings, so it's at least not specific to this one. There's also an issue inside the qwik repo tracking it

**Comment by thejackshelton** [comment]
Ah I didn't realize it was currently being worked on! @NiklasPor thank you for putting the time in to fix this. I know it was unexpected but we really appreciate your package. I'll make sure to mention that it's working in 1.1.2.

**Comment by zanettin** [comment]
@thejackshelton can we close this as resolved? 🙏

**Comment by thejackshelton** [comment]
yup!
