### ISSUE TITLE
[📖] Must specify that server$ requires to be created in layout.tsx or index.tsx

### ISSUE THREAD

**Issue by piscopancer** [BuilderIO/qwik#4201]
### Suggestion

otherwise an app breaks during the startup fase and throws errors like these
> GET http://localhost:3000/ net::ERR_CONNECTION_RESET 200 (OK)

or

> A parser-blocking, cross site (i.e. different eTLD+1) script, <URL>, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See <URL> for more details.

**Comment by manucorporat** [comment]
It's not required to be created in index.tsx or layout.tsx, not sure how you got to this issue. But i suggest opening an issue + a repo case! this should not happen.
