### ISSUE TITLE
[✨] improve dx for useOn, useOnDocument, and useOnWindow

### ISSUE THREAD

**Issue by barel-mishal** [BuilderIO/qwik#4213]
### Is your feature request related to a problem?

When using useOn or similar functions, the documentation provides event names to help understand what needs to be entered. However, for first-time users or those unfamiliar with this API or others like React, the absence of autocomplete can make the process somewhat confusing and time-consuming.

### Describe the solution you'd like

This pull request #4160 introduces an enhancement to the Qwik framework that improves the developer experience by providing autocompletion for well-known event names when using the useOn, useOnDocument, and useOnWindow functions. The change maintains support for custom event names as strings, offering flexibility to developers while making it easier to work with predefined event names.

I utilized event names already provided by Qwik along with a utility type function. This change means that any additional event support in Qwik will be added or removed accordingly. Here is the code:

```ts
// Utility types for supporting autocompletion in union types
export type Primitive = null | undefined | string | number | boolean | symbol | bigint;

export type LiteralUnion<LiteralType, BaseType extends Primitive> =
  | LiteralType
  | (BaseType & Record<never, never>);

export type PascalCaseEventLiteralType = LiteralUnion<QwikKeysEvents, string>;

// Example usage of the utility type
export const useOnWindow = (
  event: PascalCaseEventLiteralType | PascalCaseEventLiteralType[],
  eventQrl: QRL<(ev: Event) => void> | undefined
) => _useOn(`window:on-${event}`, eventQrl);

```
The LiteralUnion type is a workaround for TypeScript's issue with autocompletion in union types (see [Microsoft/TypeScript#29729](https://github.com/Microsoft/TypeScript/issues/29729)). It enables the creation of a union type that combines primitive types and literal types without sacrificing autocompletion in IDEs. This type will be removed as soon as it's not needed anymore.

By using the LiteralUnion type, developers can now enjoy autocompletion for predefined event names while still having the flexibility to use custom event names as strings.

### Describe alternatives you've considered

Alternatives considered:

Manually listing all event names without using the LiteralUnion utility type:
While this approach would allow autocompletion for known event names, it would not support custom event names, limiting the flexibility for developers who need to work with events not listed in the predefined set.

Keeping the original code without any changes:
The original implementation did not offer autocompletion for known event names, which could lead to mistakes and lower productivity for developers. Although it supported custom event names, the improved developer experience from providing autocompletion was deemed valuable enough to justify the change.

Using mapped types or conditional types:
Another option could be to use TypeScript's advanced type features, such as mapped types or conditional types, to generate the union of known event names and the string type. However, this approach might not guarantee autocompletion support in IDEs and could be more complex to implement and maintain.

After considering these alternatives, the decision was made to utilize the LiteralUnion utility type to achieve the desired balance between providing autocompletion for known event names and maintaining support for custom event names as strings.

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/pull/4160
