### ISSUE TITLE
[🐞] SVG icon does not re-render conditionally using Slot

### ISSUE THREAD

**Issue by motss** [BuilderIO/qwik#4215]
### Which component is affected?

Qwik Runtime

### Describe the bug

SVG icon does not re-render using `Slot` when toggling between its visibility state. However, using a render prop does not have such problem.

### Reproduction

https://stackblitz.com/edit/qwik-starter-v2xwcp

### Steps to reproduce

1. Go to https://stackblitz.com/edit/qwik-starter-v2xwcp
1. Run `npm install && npm run dev`
1. Click `Toggle icons` to see the SVG icons re-render and notice the difference
1. Optionally, you can also change the default value of `$visible` signal for a different initial render and the outcome is still the same.

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.54 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - ~/Library/Caches/fnm_multishells/80809_1683976973119/bin/node
    npm: 9.6.4 - ~/Library/Caches/fnm_multishells/80809_1683976973119/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Chrome Canary: 115.0.5770.0
    Firefox: 98.0.2
    Firefox Nightly: 112.0a1
    Safari: 16.4
    Safari Technology Preview: 16.4
  npmPackages:
    @builder.io/qwik: ^1.1.1 => 1.1.1 
    undici: ^5.22.1 => 5.22.1 
    vite: ^4.3.5 => 4.3.5
```

**Comment by manucorporat** [comment]
seems like a bug with content projection and SVG, i will look into it with highest priority
