### ISSUE TITLE
[🐞] Stylies not working for table tags.

### ISSUE THREAD

**Issue by vasucp1207** [BuilderIO/qwik#4221]
### Which component is affected?

Qwik Runtime

### Describe the bug

Styling is not working for table tags in the component library starter in vs-code, but styles working in stackblitz template.

### Stackblitz(working)

https://stackblitz.com/edit/qwik-starter-adwhfp?file=src%2Froutes%2Findex.tsx,src%2Fglobal.css

### Steps to reproduce

```ts
// src/components/TableHead.tsx
import { component$, useStylesScoped$ } from '@builder.io/qwik';

export const TableHead = component$(() => {
  useStylesScoped$(AppCSS);
  return (
    <thead class='head-cont'>
      <tr>
          <td class='cell'>
              head
           </td>
          )
        })}
      </tr>
    </thead>
  );
});

export const AppCSS = `
.head-cont {
  display: flex;
  width: 100%;
  padding: 3px;
}

.cell {
  width: 100%;
  font-weight: 500;
  font-size: 17px;
  color: red;
}
`;

```

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 208.17 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Safari: 15.6.1
  npmPackages:
    vite: ^4.3.0 => 4.3.5
```

**Comment by manucorporat** [comment]
can u provide a little app that shows the breaking behaviour?
can you try to reproduce in the repl?
https://qwik.builder.io/examples/introduction/hello-world/

**Comment by manucorporat** [comment]
I would appreciate a stackblitz link that i can test locally instead of screenshots :)
https://qwik.new/

**Comment by manucorporat** [comment]
table elements are special, i dont think this is qwik related but how html works. lots of styling does not apply to table.
