### ISSUE TITLE
[🐞]While run by adding lottie or Rive - Runtime error - "__vite_ssr_import_3__.useClientEffectQrl is not a function"

### ISSUE THREAD

**Issue by rishabhnayak** [BuilderIO/qwik#4227]
### Which component is affected?

Qwik Runtime

### Describe the bug

While adding lottie or Rive
Runtime error - "__vite_ssr_import_3__.useClientEffectQrl is not a function"
Error occurs Only above qwik version - 0.25.0

### Reproduction

npm install --save qwik-lottie

### Steps to reproduce

Install Lottie / Rive
1.npm install --save qwik-lottie
2.Add the code
import { component$, useStore } from '@builder.io/qwik';
import { QwikLottie } from 'qwik-lottie';

export default component$(() => {
  const store = useStore({
    options: {
      path: 'https://assets7.lottiefiles.com/packages/lf20_M6jA5UNDHa.json',
    },
  });
  return (
    
      <div>
        <QwikLottie options={store.options} />
      </div>

  );
});
3.You will get error when you run the application

### System Info

```shell
__vite_ssr_import_3__.useClientEffectQrl is not a function
```

**Comment by BasilDimopoulos** [comment]
experiencing this as well

**Comment by thejackshelton** [comment]
useClientEffect is the previous API to useVisibleTask I believe. Are you using the qwik-rive integration?

**Comment by rishabhnayak** [comment]
Yes I am using qwik-rive exactly as in documentation and getting this error
on qwik version only above 0.25.0

**Comment by gioboa** [comment]
Thanks @rishabhnayak, thanks for opening this issue, but I think this is not a Qwik bug.
Please open this issue in the library GitHub, I'm closing this issue for now.
