### ISSUE TITLE
[🐞](useStore): Too many things being re-rendered when a slice of the state changes

### ISSUE THREAD

**Issue by julianobrasil** [BuilderIO/qwik#4228]
### Which component is affected?

Qwik Runtime

### Describe the bug

By reading the tutorial, I had understood that by passing the store as a prop to a component, I'd render only the node that depended on a slice of the store value, when that value changed. 

By executing the counter store example, it seems that all the nodes that depend on slices of the store are being re-rendered when I change one of them.

```ts
type Counters = {
  countA: number;
  countB: number;
}

type Props = {
  counters: Counters
}
export const DisplayA: Component<Props> = component$(({counters}) => {
  return <>Display A: <span>{counters.countA}</span></>
})
export const DisplayB: Component<Props> = component$(({counters}) => {
  return <>Display B: <span>{counters.countB}</span></>
})
export default component$(() => {
  const counter = useStore({countA: 0,countB: 0})
  return <>
      <p>
        <button onClick$={() => counter.countA++}>+1 A</button>
        <DisplayA counters={counter} />
      </p>
      <p>
        <button onClick$={() => counter.countB++}>+1 B</button>
        <DisplayB counters={counter} />
      </p>
    </>;
});
```

![Kapture 2023-05-15 at 06 34 28](https://github.com/BuilderIO/qwik/assets/25405143/e8dfb0c1-c722-49dc-ac73-d4c668fc8729)

If, instead of the `useStore(...)`, I use 2 signals, like this, everything works as expected:

```ts
// const counter = useStore({countA: 0,countB: 0});
const counterASignal = useSignal(0);
const counterBSignal = useSignal(0);
```

### Reproduction

Here you have a [Playground Reproduction](https://qwik.builder.io/playground/#version=1.1.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwdHlwZSUyMENvbXBvbmVudCUyQyUyMGNvbXBvbmVudCUyNCUyQyUyMHVzZVN0b3JlJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbnR5cGUlMjBDb3VudGVycyUyMCUzRCUyMCU3QiU1Q24lMjAlMjBjb3VudEElM0ElMjBudW1iZXIlM0IlNUNuJTIwJTIwY291bnRCJTNBJTIwbnVtYmVyJTNCJTVDbiU3RCU1Q24lNUNudHlwZSUyMFByb3BzJTIwJTNEJTIwJTdCJTVDbiUyMCUyMGNvdW50ZXJzJTNBJTIwQ291bnRlcnMlNUNuJTdEJTVDbmV4cG9ydCUyMGNvbnN0JTIwRGlzcGxheUElM0ElMjBDb21wb25lbnQlM0NQcm9wcyUzRSUyMCUzRCUyMGNvbXBvbmVudCUyNCgoJTdCY291bnRlcnMlN0QpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCUzQyUzRURpc3BsYXklMjBBJTNBJTIwJTNDc3BhbiUzRSU3QmNvdW50ZXJzLmNvdW50QSU3RCUzQyUyRnNwYW4lM0UlM0MlMkYlM0UlNUNuJTdEKSU1Q25leHBvcnQlMjBjb25zdCUyMERpc3BsYXlCJTNBJTIwQ29tcG9uZW50JTNDUHJvcHMlM0UlMjAlM0QlMjBjb21wb25lbnQlMjQoKCU3QmNvdW50ZXJzJTdEKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAlM0MlM0VEaXNwbGF5JTIwQiUzQSUyMCUzQ3NwYW4lM0UlN0Jjb3VudGVycy5jb3VudEIlN0QlM0MlMkZzcGFuJTNFJTNDJTJGJTNFJTVDbiU3RCklNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMGNvdW50ZXIlMjAlM0QlMjB1c2VTdG9yZSglN0Jjb3VudEElM0ElMjAwJTJDY291bnRCJTNBJTIwMCU3RCklNUNuJTIwJTIwcmV0dXJuJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ3AlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDYnV0dG9uJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwY291bnRlci5jb3VudEElMkIlMkIlN0QlM0UlMkIxJTIwQSUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NEaXNwbGF5QSUyMGNvdW50ZXJzJTNEJTdCY291bnRlciU3RCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ3AlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDYnV0dG9uJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwY291bnRlci5jb3VudEIlMkIlMkIlN0QlM0UlMkIxJTIwQiUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NEaXNwbGF5QiUyMGNvdW50ZXJzJTNEJTdCY291bnRlciU3RCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRiUzRSUzQiU1Q24lN0QpJTNCJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q25pbXBvcnQlMjBBcHAlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQyUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFVHV0b3JpYWwlM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiUyQyUyMmhpZGRlbiUyMiUzQXRydWUlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlNUNuaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTJDJTIyaGlkZGVuJTIyJTNBdHJ1ZSU3RCU1RA%3D%3D)

### Steps to reproduce

Not apply, the url is for the playground

### System Info

```shell
Not apply, the url is for the playground
```

**Comment by wmertens** [comment]
More context: Only the text nodes of the interpolations are changing, not the spans or anything else.

**Comment by manucorporat** [comment]
Both version should work the same actually. there is clearly a bug! i think it should be trivial fix! will look into ti
