### ISSUE TITLE
[🐞] Qwik AI has an endless loading spinner

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/qwik#4237]
### Which component is affected?

Qwik Documentation

### Describe the bug

When a user has an option to use AI in the Qwik documentation the spinner will load endlessly and not provide an output

https://gyazo.com/af0f49fd6f2b9d134a8850f09effa92f

### Reproduction

https://qwik.builder.io/

### Steps to reproduce

Go to the Qwik documentation and click on "search"

Type an example prompt for Qwik AI
"What does useVisibleTask$ do?"

Click on the AI option and it will continually load and not provide a response.

### System Info

```shell
This is related to the documentation.
```

### Additional Information

References from additional users highlighting the issue:
https://discord.com/channels/842438759945601056/842438761287254019/1108011678198673460
https://discord.com/channels/842438759945601056/842438761287254019/1107352475033403412

**Comment by gioboa** [comment]
Hey @thejackshelton, thanks for opening this issue, I tested the AI in the Qwik documentation right now and it's working.
So I'm closing this issue 👍
