### ISSUE TITLE
[✨]Integrate Qwik with Bun

### ISSUE THREAD

**Issue by gabriiels** [BuilderIO/qwik#4239]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I wish Qwik had an integration with Bun

Explore the possibility of creating a Qwik template with Bun

https://bun.sh/docs/templates#official-templates

https://github.com/bun-community/create-templates

QWIK + BUN === GOAT

**Comment by ansarizafar** [comment]
I am also interested in Qwik + Bunjs for creating ChatGPT/Bing/Microsoft Copilot plugins.

**Comment by JoeSlayn** [comment]
Would love to see that happen for further enhanced performances and better DX.

**Comment by PiWizard3852** [comment]
I think this would be really great!

**Comment by blueagler** [comment]
Both are the fastest!

**Comment by birkskyum** [comment]
Tracking ticket in Bun 

* https://github.com/oven-sh/bun/issues/3783

**Comment by pleclech** [comment]
Hi there,
I'm not really an expert on qwik internals nor bun, but I've got a [branch](https://github.com/pleclech/qwik/tree/bun-adapter) where there's a basic bun adapter that works like the deno one.

**Comment by mhevery** [comment]
If you would like to create a PR that would be great:
- https://qwik.builder.io/docs/deployments/#add-a-new-deployment
- Example for firebase adapter: https://github.com/BuilderIO/qwik/pull/4778

**Comment by pleclech** [comment]
@EamonHeffernan 

Thanks.
I 'm quite busy for the moment todo the PR for my branch.

Some problems i encountered when doing the adapter:
- for the Bun undeclared var i had to add an [env file](https://github.com/BuilderIO/qwik/compare/main...pleclech:qwik:bun-adapter#diff-f50f9bd51c13097d3d1d94078782a306ed50c4d5550db683fe1ab231d758441b)
- for the user to use the adapter i had to add a [type definition file](https://github.com/BuilderIO/qwik/compare/main...pleclech:qwik:bun-adapter#diff-96832ef4cbc8154fabf3a4dfe5acab58f8a5ca534532a3377ac12619a2486d24)
- as for adding @types/bun.d.ts into tsconfig.json, if i remember well it was causing conflict with some type from deno

**Comment by EamonHeffernan** [comment]
> @EamonHeffernan
> 
> Thanks. I 'm quite busy for the moment todo the PR for my branch.
> 
> Some problems i encountered when doing the adapter:
> 
>     * for the Bun undeclared var i had to add an [env file](https://github.com/BuilderIO/qwik/compare/main...pleclech:qwik:bun-adapter#diff-f50f9bd51c13097d3d1d94078782a306ed50c4d5550db683fe1ab231d758441b)
> 
>     * for the user to use the adapter i had to add a [type definition file](https://github.com/BuilderIO/qwik/compare/main...pleclech:qwik:bun-adapter#diff-96832ef4cbc8154fabf3a4dfe5acab58f8a5ca534532a3377ac12619a2486d24)
> 
>     * as for adding @types/bun.d.ts into tsconfig.json, if i remember well it was causing conflict with some type from deno

I had created my own branch before seeing your branch, I ran into some of those issues, however I believe that the issues should be resolved in my pr.

**Comment by sebacc92** [comment]
I would love to see hits integration happen; it would be awesome"

**Comment by chuikoffru** [comment]
Hello @EamonHeffernan. 

When I build my app with Bun adapter, and open page with routerLoader(({env}) => {
   console.log(env.get("SOME_ENV"))
})

I've got an error.

**Comment by phyrog** [comment]
@chuikoffru I opened a PR to fix this issue: #5601
