### ISSUE TITLE
[🐞] Reactivity is broken when comparing multiple signals in a ternary

### ISSUE THREAD

**Issue by cmbartschat** [BuilderIO/qwik#4242]
### Which component is affected?

Qwik Runtime (or maybe Optimizer)

### Describe the bug

There appears to be some issues with reactivity in the following case:

### Reproduction

[Playground](https://qwik.builder.io/playground/#version=1.1.2&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU2lnbmFsJTIwJTdEJTIwZnJvbSUyMCU1QyUyMiU0MGJ1aWxkZXIuaW8lMkZxd2lrJTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwZmlyc3QlMjAlM0QlMjB1c2VTaWduYWwoJTVDJTIyJTVDJTIyKSUzQiU1Q24lMjAlMjBjb25zdCUyMHNlY29uZCUyMCUzRCUyMHVzZVNpZ25hbCglNUMlMjIlNUMlMjIpJTNCJTVDbiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ21haW4lM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDZGl2JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ2xhYmVsJTIwZm9yJTNEJTVDJTIyZmlyc3QlNUMlMjIlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdCJTVDJTIyRmlyc3QlMjAlNUMlMjIlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDaW5wdXQlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWQlM0QlNUMlMjJmaXJzdCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YWx1ZSUzRCU3QmZpcnN0LnZhbHVlJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG9uSW5wdXQlMjQlM0QlN0IoXyUyQyUyMGUpJTIwJTNEJTNFJTIwKGZpcnN0LnZhbHVlJTIwJTNEJTIwZS52YWx1ZSklN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcGxhY2Vob2xkZXIlM0QlNUMlMjJ0eXBlJTIwaGVyZSU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGbGFiZWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGZGl2JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2RpdiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NsYWJlbCUyMGZvciUzRCU1QyUyMnNlY29uZCU1QyUyMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0IlNUMlMjJTZWNvbmQlMjAlNUMlMjIlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDaW5wdXQlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWQlM0QlNUMlMjJzZWNvbmQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdmFsdWUlM0QlN0JzZWNvbmQudmFsdWUlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwb25JbnB1dCUyNCUzRCU3QihfJTJDJTIwZSklMjAlM0QlM0UlMjAoc2Vjb25kLnZhbHVlJTIwJTNEJTIwZS52YWx1ZSklN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcGxhY2Vob2xkZXIlM0QlNUMlMjJ0eXBlJTIwaGVyZSU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGbGFiZWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGZGl2JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ3AlM0VGaXJzdCUyMHZhbHVlJTNBJTIwJTVDJTIyJTdCZmlyc3QudmFsdWUlN0QlNUMlMjIlM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ3AlM0VTZWNvbmQlMjB2YWx1ZSUzQSUyMCU1QyUyMiU3QnNlY29uZC52YWx1ZSU3RCU1QyUyMiUzQyUyRnAlM0UlNUNuJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ3AlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTdCJTVDJTIyU3RhdHVzJTNBJTIwJTVDJTIyJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3QmZpcnN0LnZhbHVlJTIwJTI2JTI2JTIwc2Vjb25kLnZhbHVlJTIwJTI2JTI2JTIwZmlyc3QudmFsdWUlMjAlM0QlM0QlM0QlMjBzZWNvbmQudmFsdWUlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNGJTIwJTVDJTIyQ29sbGlzaW9uJTIwZGV0ZWN0ZWQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNBJTIwJTVDJTIyTm8lMjBjb2xsaXNpb24lNUMlMjIlN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGcCUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZtYWluJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMHR5cGUlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D)

### Steps to reproduce

1. Type "foo" in the first input field
2. Type "foo" in the second input field
3. See that "No collision" is displayed in the even though the two values are equal
4. Type "bar" in the second field
5. Type "bar" in the first field (order matters)
6. See that "Collision detected" is now shown
7. Type "baz" in the second field
8. See that "Collision detected" is still shown even though the two values are now different

### System Info

```shell
Playground/Firefox/Windows
```

### Additional Information

This is not a recent regression, looks like it's been the case since 0.20.0

**Comment by tuurbo** [comment]
Possibly related? https://github.com/BuilderIO/qwik/issues/4249

**Comment by cmbartschat** [comment]
The workaround that I found is moving the ternary into `useComputed$`

**Comment by cmbartschat** [comment]
Fixed by https://github.com/BuilderIO/qwik/pull/4297
