### ISSUE TITLE
[🐞]Hot reload not working always for SCSS and TSX changes

### ISSUE THREAD

**Issue by tudor-sport-thieme** [BuilderIO/qwik#4243]
### Which component is affected?

Qwik Runtime

### Describe the bug

The hot reload does not work properly in some specific components. When we apply some changes to scss and TSX files the changes are not picked up on hot reload and we need to restart the dev server to see the changes applied. This started happening more offen as the complexity of the app increased.

One thing that we noticed is that this issues happen for us only in the Header and the Footer components which live in the main layout file. That lead us to conclude that maybe this issue doesn’t affect components which live in the <Slot /> of the layout. Unfortunately, this didn’t turn out to be true - if we take - for instance - the Header component and make it appear somewhere in the <Slot /> this issue persists

### Reproduction

https://stackblitz.com/edit/qwik-starter-yguv5g?file=src/components/Header/MainNavigation/MainNavigation.scss

### Steps to reproduce

1 - Open the stakblitz repo.

2 - Fork the repo to be abble to save changes

3 - Uncomment the lines in the scss file *'src/components/TestComponent/TestComponent.scss'* and save (this changes should be visible with hot reload)

<img width="770" alt="Screenshot 2023-05-17 at 09 21 07" src="https://github.com/BuilderIO/qwik/assets/102809136/f63604fc-1dbf-44d0-b751-ce0304184517">

4 - Uncomment the lines in the scss file *'src/components/Header/MainNavigation/MainNavigation.scss'* and save (this changes are not instantly reflected)

<img width="692" alt="Screenshot 2023-05-17 at 09 20 36" src="https://github.com/BuilderIO/qwik/assets/102809136/1a36f57a-bdf8-473e-ab1b-a54e1ae3761c">

5 - Uncomment the `<p>` element (Unnecessary element) in the file TSX file *'src/components/Header/MainNavigation/MainNavigation.tsx'* and save (this changes are sometimes displayed and sometimes not, this is unstable)

<img width="739" alt="Screenshot 2023-05-17 at 09 20 46" src="https://github.com/BuilderIO/qwik/assets/102809136/ffd664a5-1561-4093-95e0-f27fe3f0dd3c">

6 - You can change the steps 3, 4 and 5 and see how the app behaves with the hot reload.

7 - Restart the dev server and see the last saved changes to the files related to step 3 and 4.

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 54.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 108.0.2
    Safari: 16.4
  npmPackages:
    @builder.io/qwik: 1.1.0 => 1.1.0 
    @builder.io/qwik-city: ^1.1.0 => 1.1.0 
    undici: 5.22.0 => 5.22.0 
    vite: 4.3.3 => 4.3.3
```

**Comment by rohan-kadkol** [comment]
Possible similar issue: https://github.com/BuilderIO/qwik/issues/1901

**Comment by wmertens** [comment]
FWIW it sort of used to work in the past. Now when I use vanilla-extract and change the css.ts file, I can see that the file gets re-parsed, the css gets recreated and requested, but the page doesn't change, even on reloading the page.

This happens both with direct .css imports and with useStyle$(str) where str changes.

I'm guessing that the css is actually being cached?

**Comment by gioboa** [comment]
I tested all the steps with the latest version of Qwik ( v1.3.0 + Vite 5 ) and it's working fine.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
