### ISSUE TITLE
[🐞] Unable to return value from onGet/RequestHandler

### ISSUE THREAD

**Issue by brachypelma** [BuilderIO/qwik#4246]
### Which component is affected?

Qwik City (routing)

### Describe the bug

On [this documentation page about request handling](https://qwik.builder.io/docs/advanced/request-handling/#request-and-response-handlers), the first code example block shows an onGet being used to return a value:

```ts
import type { RequestHandler } from '@builder.io/qwik-city';
 
export const onGet: RequestHandler<ProductData> = async ({ params }) => {
  // put your DB access here (hard coding data for simplicity)
  return {
    skuId: params.skuId,
    price: 123.45,
    description: `Description for ${params.skuId}`,
  };
};
```

But when I try to return any value from my own onGet method, I get an error like this:

`Type '({ cookie }: RequestEvent<QwikCityPlatform>) => boolean' is not assignable to type 'RequestHandler'.
  Type 'boolean' is not assignable to type 'void | Promise<void>'`

[The type declaration for `RequestEvent` does](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/middleware/request-handler/types.ts) have the return type hard-coded as `Promise<void> | void`.

I'm not sure if this is a documentation issue or a bug (or me just not knowing what's going on again...). I would like to be able to return a value from a `RequestHandler`. I don't know if that used to be possible or was supposed to be possible, but as far as I can tell, the documentation is telling people to do something that can't be done.

### Reproduction

https://github.com/brachypelma/request-handler-test

### Steps to reproduce

Run `npm install`
Run `npm run dev`

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 45.19 GB / 62.53 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 112.0.2
  npmPackages:
    @builder.io/qwik: ^1.1.3 => 1.1.3 
    @builder.io/qwik-city: ^1.1.3 => 1.1.3 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.5 => 4.3.5
```

### Additional Information

onGet added to src/routes/index.tsx in demo repo.

**Comment by gioboa** [comment]
Hi @brachypelma 
the APIs changed in this months and with the latest version of Qwik and this code, is working fine.
[Here is](https://qwik.builder.io/docs/endpoints/) the new documentation
```
import { type RequestHandler } from '@builder.io/qwik-city';
 
export const onGet: RequestHandler = async ({ json }) => {
  json(200, { hello: 'world' });
};
```
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
