### ISSUE TITLE
[🐞] Signals in ternary causing elements to rerender that shouldn't

### ISSUE THREAD

**Issue by tuurbo** [BuilderIO/qwik#4249]
### Which component is affected?

Qwik Runtime

### Describe the bug

- open stackblitz.
- click button multiple times.
- see elements between signals get rerendered.

### Reproduction

https://stackblitz.com/edit/qwik-starter-qcfttx?file=src%2Froutes%2Findex.tsx

### System Info

```shell
stackblitz

-- and --

  System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 11.21 GB / 31.68 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0
    @builder.io/qwik: 1.1.4 => 1.1.4
    @builder.io/qwik-city: 1.1.4 => 1.1.4
    vite: 4.3.7 => 4.3.7
```

**Comment by rjsdnql123** [comment]
Isn't it because of the timeout?

**Comment by tuurbo** [comment]
No the timeouts were just make it visually obvious the rerendering was happening. It happens without timeouts as well. https://stackblitz.com/edit/qwik-starter-snhypq?file=src%2Froutes%2Fother-text.tsx
