### ISSUE TITLE
[🐞] Cannot load page after build with express

### ISSUE THREAD

**Issue by anboo44** [BuilderIO/qwik#4255]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I upgraded qwik version to 1.1.4. After, I used command: `pnpm build` & `node entry.express.js` to run production mode.
I waited very long time but page cannot be loaded. 
I try to change to another qwik version. I discovered this problem comes from `qwik-city` at version `1.1.3` and `1.1.4`. It is OK at version `1.1.2`.
Please fix it.

` 
// ~~> Work OK
"@builder.io/qwik": "1.1.4",
"@builder.io/qwik-city": "1.1.2",
`
` 
// ~~> Not OK
"@builder.io/qwik": "1.1.4",
"@builder.io/qwik-city": "1.1.3",
`

### Reproduction

[Link Repository](https://gitlab.com/eval360v4/frontend-v4/-/tree/dev?ref_type=heads)

### System Info

```shell
System:
    OS: MacBook Pro (14-inch, 2021)
    CPU: Apple M1 Pro
    Memory: 8GB / 16 GB
  Binaries:
    Node: v18.16.0
    pnpm: 7.29.1
  Browsers:
    Brave: Version 1.50.121  Chromium: 112.0.5615.138 (Official Build)  (arm64)
    Chrome: Version 113.0.5672.126 (Official Build) (arm64)
```

**Comment by manucorporat** [comment]
we cant fix without a simple repo case, we can use the debug the issue.

**Comment by anboo44** [comment]
@manucorporat I have updated link of my repository. Please check it. Thank you

**Comment by anboo44** [comment]
It works successfully at version 1.1.5. So, I close this issue
