### ISSUE TITLE
[🐞] auth does not work when there is [...org]/[...repo] route

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#4262]
### Which component is affected?

Qwik Runtime

### Describe the bug

1. I have `[...org]/[...repo]/index.tsx` route which catches pretty much everything.
2. I have also instarred auth (with GitHub)

The signout/signi does not work unless I define `login/index.tsx` route. (Anything so that there is a way to escape the catch all above.

### Reproduction

https://github.com/mhevery/qwik-workshop/commit/baa13d19d3b7c5220400268bea3a3afad0c08ad4

### Steps to reproduce

`/login` can be used to sign in whereas any other URL does not work.

### System Info

```shell
na
```

**Comment by ulic75** [comment]
I'm not sure the solution but I think the issue only occurs at the root level route because the index.tsx has an onPost which is returning a response first before the auth stuff can do it's work.

**Comment by mhevery** [comment]
that makes sense
