### ISSUE TITLE
[🐞] QwikCity not found pages throw error in production with fastify

### ISSUE THREAD

**Issue by lucastonelli** [BuilderIO/qwik#4263]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Hey, I hope you're doing well.

 I may have encountered an issue with the boostraped project.

Run `npm create qwik@latest`, then `npm run qwik add` and `npm run build`. Run `npm run serve` and open a page that does not exist. For example `localhost:3000/1`. You'll get:

![image](https://github.com/BuilderIO/qwik/assets/52139329/79ba73d6-35fb-4bcd-99d9-2f9ff2c51694)

Setting the ORIGIN previously doesn't work:
![image](https://github.com/BuilderIO/qwik/assets/52139329/d50e7be9-cf6f-4bb2-ad31-1f53003af168)

I've tried setting it in multiple ways, making sure the host is always matching the origin:

```javascript
await fastify.listen({ port: PORT, host: 'localhost' });
```

And I'm rebuilding (`npm run build`) after every ORIGIN change, just to be sure.

Be aware that the reproduction URL I've provided starts the dev script by default, make sure to follow the steps described to replicate the issue.

### Reproduction

https://stackblitz.com/edit/qwik-starter-t6nafz

### Steps to reproduce

Described above.

### System Info

```shell
System:
  OS: Linux 6.2 Pop!_OS 22.04 LTS
  CPU: (12) x64 AMD Ryzen 5 5500
  Memory: 15.48 GB / 31.13 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
  npm: 9.5.1 - ~/.nvm/versions/node/v19.8.1/bin/npm
Browsers:
  Chrome: 113.0.5672.92
  Firefox: 113.0
npmPackages:
  @builder.io/qwik: ^1.1.4 => 1.1.4 
  @builder.io/qwik-city: ^1.1.4 => 1.1.4 
  undici: 5.22.1 => 5.22.1 
  vite: 4.3.5 => 4.3.5
```

**Comment by KenParsons** [comment]
Just commenting here to confirm I've had this issue. And it seems to persist through in other ways, such as some odd behavior with an endpoint with an `onPost` export. I don't have great details yet as it's been a bit evasive, forgive me. But this is quite a gotcha in fastify+qwik right now

**Comment by zanettin** [comment]
closed via https://github.com/BuilderIO/qwik/pull/4879
