### ISSUE TITLE
[🐞] Static Store data is not dynamically tree-shaked

### ISSUE THREAD

**Issue by julianobrasil** [BuilderIO/qwik#4266]
### Which component is affected?

Qwik Runtime

### Describe the bug

According to [the docs](https://qwik.builder.io/tutorial/understanding/capturing/) we should expect any value in a store (created with a `useSTore(...)`) that is not going to change at the browser to not be serialized. Those non-client-changing values should be dynamically tree-shaked.

However, if I try code below, the `largeData` is being serialized and sent to the browser regardless it's not even used anywhere in the code after the store initialization: 

```ts
interface AppStore {
  counter: { count: number };
  largeData: any;
}
export default component$(() => {
  const store = useStore<AppStore>( {
      counter: { count: 1 },
      largeData: { data: 'PRETEND THIS IS A LARGE DATASET' },
    },
    { deep: true });

  const counter = store.counter;
  return (
    <>
      <code>&lt;App&gt;</code>
      <br />
      Click <button onClick$={() => counter.count++}>+1</button>
    </>
  );
});
```

If I use the code above, I see, on the browser devtools:

![Screenshot 2023-05-18 at 06 44 19](https://github.com/BuilderIO/qwik/assets/25405143/cabce60e-f49a-4e3d-bde5-1bac6c336f0c)

### Reproduction

https://qwik.builder.io/playground/#version=1.1.4&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMkMlMjAlMjQlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuaW50ZXJmYWNlJTIwQXBwU3RvcmUlMjAlN0IlNUNuJTIwJTIwY291bnRlciUzQSUyMCU3QiUyMGNvdW50JTNBJTIwbnVtYmVyJTIwJTdEJTNCJTVDbiUyMCUyMGxhcmdlRGF0YSUzQSUyMGFueSUzQiU1Q24lN0QlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0b3JlJTIwJTNEJTIwdXNlU3RvcmUlM0NBcHBTdG9yZSUzRSglNUNuJTIwJTIwJTIwJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGNvdW50ZXIlM0ElMjAlN0IlMjBjb3VudCUzQSUyMDElMjAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwbGFyZ2VEYXRhJTNBJTIwJTdCJTIwZGF0YSUzQSUyMCdQUkVURU5EJTIwVEhJUyUyMElTJTIwQSUyMExBUkdFJTIwREFUQVNFVCclMjAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCU3QiUyMGRlZXAlM0ElMjB0cnVlJTIwJTdEJTVDbiUyMCUyMCklM0IlNUNuJTIwJTIwY29uc29sZS5sb2coJ1JlbmRlciUzQSUyMCUzQ0FwcCUyRiUzRScpJTNCJTVDbiUyMCUyMGNvbnN0JTIwY291bnRlciUyMCUzRCUyMHN0b3JlLmNvdW50ZXIlM0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0MlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDY29kZSUzRSUyNmx0JTNCQXBwJTI2Z3QlM0IlM0MlMkZjb2RlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JyJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMENsaWNrJTIwJTNDYnV0dG9uJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwY291bnRlci5jb3VudCUyQiUyQiU3RCUzRSUyQjElM0MlMkZidXR0b24lM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTVDbmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VUdXRvcmlhbCUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkYlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTJDJTIyaGlkZGVuJTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q25pbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChvcHRzJTNBJTIwUmVuZGVyT3B0aW9ucyklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwcmVuZGVyVG9TdHJpbmcoJTNDUm9vdCUyMCUyRiUzRSUyQyUyMG9wdHMpJTNCJTVDbiU3RCU1Q24lMjIlMkMlMjJoaWRkZW4lMjIlM0F0cnVlJTdEJTVE

### System Info

```shell
Reproducible on the playground, no need to create a project on any specify system
```

**Comment by manucorporat** [comment]
We cant solve this problem, that why we recommend using signals, not stores. we cant tree shake parts of a single store.
