### ISSUE TITLE
[🐞] problem with server-streaming-responses

### ISSUE THREAD

**Issue by alimrb** [BuilderIO/qwik#4267]
### Which component is affected?

Qwik Runtime

### Describe the bug

https://qwik.builder.io/docs/server$/#streaming-responses 

this example throws 
[vite] Internal server error: Code(3): Only primitive and object literals can be serialized

or on production link bellow:

Value at index 0 does not have a transferable type.

### Reproduction

https://qwikstarter4p8iaj-pxmr--5173--9c8944bc.local-credentialless.webcontainer.io/demo/server-test

### Steps to reproduce

click on start button

### System Info

```shell
OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 6.90 GB / 15.24 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/qwik: ^1.1.1 => 1.1.1
    @builder.io/qwik-city: ^1.1.1 => 1.1.1
    undici: 5.22.0 => 5.22.0
    vite: 4.3.5 => 4.3.5
```

**Comment by manucorporat** [comment]
I need some source code i can use to reproduce the issue.
