### ISSUE TITLE
[✨] Built-in utility components similar to Solid

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/qwik#4278]
### Is your feature request related to a problem?

Talked with Ahn#1702 in qwik-dx-suggestions about his experience with utility components in Solid.js

**They're similar to a ternary or control flow operators but used as utility components.**

For example, here's solid's show component:

```tsx
<Show
  when={loggedIn()}
  fallback={<button onClick={toggle}>Log in</button>}
>
  <button onClick={toggle}>Log out</button>
</Show>
```

There are others such as for loop, switch case, etc.

### Describe the solution you'd like

Similar built-in utility components with Qwik. Especially since in Qwik I don't believe you can use conditions in your JSX. I think it has to do with the serialization.

Utility componenets could bridge the gap on that end. Making code more explicit with better readability.

### Describe alternatives you've considered

An alternative would be to use conditional logic above our JSX, but I believe this is a current limitation that Qwik has. 

### Additional context

Ahn's feedback on why he believes utility components would be a good addition to Qwik:

_I think it’s very helpful for fullstack developers who aren’t smooth in using jsx, bridging the gap when switching between projects for them. From my experience, such utility components help a lot in my team. It’s also quite declarative and straight forward than the traditional ternary
In other frameworks, such utility components have different names like directives in vue or angular_

Discord reference:
https://discord.com/channels/842438759945601056/1051909037257666630/1109435425694691429

**Comment by cmbartschat** [comment]
Related: https://github.com/BuilderIO/qwik/issues/2678

**Comment by shairez** [comment]
We discussed it back in the day and decided not to put it inside of the core to minimize the api surface area we need to maintain.
Plus it could be easily be done in user land.

So there was an attempt to start something like that under Qwikifiers but it needs reviewing and ownership - 
https://github.com/qwikifiers/qwik-flow

If anyone wants to help with that, please DM me on discord

Closing this for now
