### ISSUE TITLE
[🐞] [integrations, vitest] Test fails when use qwik city Form component

### ISSUE THREAD

**Issue by diecodev** [BuilderIO/qwik#4284]
### Which component is affected?

Qwik Runtime

### Describe the bug

Unit Testing fails when you test a component with the qwik city Form component.

### Reproduction

https://stackblitz.com/edit/qwik-starter-9umxmj?file=src%2Fcomponents%2Fstarter%2Fform%2Flogin.test.tsx

### Steps to reproduce

- Create a qwik component.
- Use the qwik city Form component inside your custom component.
- Run the test (e.g. "Should have 2 inputs to email and password" ~ "Should have a form tag").
- Check the console errors.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12450H
    Memory: 2.00 GB / 7.73 GB
  Binaries:
    Node: 18.16.0 - ~\AppData\Local\fnm_multishells\28704_1684645509934\node.EXE
    npm: 9.5.1 - ~\AppData\Local\fnm_multishells\28704_1684645509934\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: 1.1.4 => 1.1.4
    @builder.io/qwik-city: 1.1.4 => 1.1.4
    undici: 5.22.1 => 5.22.1
    vite: 4.3.5 => 4.3.5
```

### Additional Information

This is the error that appears in my console (besides the test failure):

![qwik city error because qwik city Form component](https://github.com/BuilderIO/qwik/assets/51871681/89855038-c706-4476-bb9f-be9ff9766d70)

**Comment by diecodev** [comment]
@manucorporat this bug was fixed?

**Comment by adamayres** [comment]
@diecodev When testing components that use context from qwik-city, such as `Link` or `Form`, you need to wrap your test in `QwikCityMockProvider`. In your case it would look something like:

```tsx
describe('Login form', async () => {
  const { screen, render } = await createDOM();

  it('Should render', async () => {
    await render(
      <QwikCityMockProvider>
        <LoginForm />
      </QwikCityMockProvider>
    );
    expect(screen.outerHTML).toContain('<form');
  });
});
```

I also noticed that this does not work (entirely) on version 1.0.0, which you had set in your example. After updating your example to 1.2.6 and wrapping it in `QwikCityMockProvider` it works, here is a working example:

https://stackblitz.com/edit/qwik-starter-sdvki5?file=src%2Fcomponents%2Fstarter%2Fform%2Flogin.test.tsx

I don't think this is documented yet, but here is a relevant conversation on discord: 

https://discord.com/channels/842438759945601056/1131645076506939412/1131645076506939412

**Comment by njoguamos** [comment]
@adamayres Thank you. Your solution worked.
