### ISSUE TITLE
[✨] Ability to pass `AbortController` to `server$()`

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#4309]
### Is your feature request related to a problem?

Sometimes it would be convenient to abort an in-flight `server$()`. It would be great if you could pass `AbortController` to `server$` as an additional argument

### Describe the solution you'd like

  const users = useResource$(({ track, cleanup }) => {
    track(debouncedFilter);
    const controller = new AbortController();
    cleanup(() => controller.abort());
    return server$(() => {
      //...
    }, { abort: controller }); // <===== HERE
  });

### Describe alternatives you've considered

just ignoring the output

**Comment by DanielAdolfsson** [comment]
This is already implemented in merged PR #4214, and a couple of fixes are waiting to be merged in PR #4290. Dunno when it will be merged though :)

**Comment by gioboa** [comment]
`AbortSignal` is implemented 

> AbortSignal is optional, and allows you to cancel a long running request by terminating the connection.

Here is the [docs](https://qwik.builder.io/docs/server$/)

Thanks @DanielAdolfsson for your contribution.
