### ISSUE TITLE
[🐞] Serialization does not always reuse strings from DOM

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#4335]
### Which component is affected?

Qwik Runtime

### Describe the bug

Qwik serialization only sometimes reuses strings from DOM.

### Reproduction

https://stackblitz.com/edit/qwik-starter-qe2ajh?file=package.json,src%2Froutes%2Findex.tsx

### Steps to reproduce

1. https://stackblitz.com/edit/qwik-starter-qe2ajh?file=README.md,src%2Froutes%2Findex.tsx
2. Click `test` button
3. Notice that the Qwik/JSON has `Spanish` even though `Manu` was correctly reused. I would expect `Spanish` to also back refer to the DOM.

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
Spanish is never rendered in the HTML as a text node

**Comment by mhevery** [comment]
What do you mean? It is right here: 
<img width="165" alt="image" src="https://github.com/BuilderIO/qwik/assets/111951/c8bae4a5-9f7f-4f7f-9351-aec157db992c">

**Comment by mhevery** [comment]
Ohh I see `Spanish` is rendered as `<span>Manu/Spanis</span>` with no id. How do you know if the ID needs to be placed on the HTML or not? Is it because it is not a signal?

**Comment by mhevery** [comment]
Ohh I think I understand. Not a signal, therefore there is no way to know that we may need this ID, hence we can't save it.

Wondering if we should close this issue, or is it something that we could fix... I think I am just going to close it for now.
