### ISSUE TITLE
Qwik errror during build. ReferenceError: exports is not defined in ES module scope

### ISSUE THREAD

**Issue by Maikpwwq** [BuilderIO/qwik#4337]
### Discussed in https://github.com/BuilderIO/qwik/discussions/4336

<div type='discussions-op-text'>

<sup>Originally posted by **Maikpwwq** May 25, 2023</sup>
How to solve this qwik framework error during build a static site: 

```
   ReferenceError: exports is not defined in ES module scope
    at file:///media/oem/MyFiles/8_DEVELOPMENT/nexasoft/server/@qwik-city-plan.mjs:1:1097
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
```
And the reference is about this line of code, 
```
exports.__esModule=!0;var K=require("@builder.io/qwik"),Le=require("../components/header/header");exports.default=K.component$(function(){return React.createElement(React.Fragment,null,React.createElement("main",null,React.createElement(Le.default,null),...
```
I am facing this issue since I update my dependencies with Qwik V1

I try this, ```<script>var exports = {};</script>```, but still trow me an error.

This is my project repository: https://github.com/Maikpwwq/nexasoft</div>

**Comment by gioboa** [comment]
Did you solve this problem?
