### ISSUE TITLE
[🐞] calling `noSerialize` causes more things to serialize

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#4342]
### Which component is affected?

Qwik Runtime

### Describe the bug

Calling `noSerialize` causes more things to serialize

Also, I think `noSerialize` only works on naked (non-proxy objects). I think the value we store for no-serialize should be always naked, which means we need a check to unwrap it.

### Reproduction

https://stackblitz.com/edit/qwik-starter-vkbi8v?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

1. open https://stackblitz.com/edit/qwik-starter-vkbi8v?file=src%2Froutes%2Findex.tsx
2. Notice that very little state is serialized.
3. Go to the source and uncomment `noSerialize(state.value.hide);`
4. Notice that a whole bunch more data is now serialized

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
Will look into it with priority

**Comment by manucorporat** [comment]
This is working as expected, it's serializing more not because `noSerialize` but because the get access, it's creating susbscriptions that requires the component to rerender:
```
  noSerialize(state.value.hide);
  noSerialize(nakedStore.hide1);
  noSerialize(store.hide2);
```
