### ISSUE TITLE
defaultPrevented is still false even after setting preventdefault:wheel to true on input element

### ISSUE THREAD

**Issue by og-dev** [BuilderIO/qwik#4343]
```typescript
<input
      type="number"
      name="amount"
      preventdefault:wheel={true}
/> 
```
I'm triying to disable the scroll wheel changing the number in an input number field.
But defaultPrevented is still false even after setting preventdefault:wheel to true on input element

How is preventdefault:wheel supposed to behave? 

Using `onWheel$` doesn't work either

**Comment by cmbartschat** [comment]
[Here is a playground showing the issue](https://qwik.builder.io/playground/#version=1.1.4&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU2lnbmFsJTJDJTIwdXNlVmlzaWJsZVRhc2slMjQlMjAlN0QlMjBmcm9tJTIwJTVDJTIyJTQwYnVpbGRlci5pbyUyRnF3aWslNUMlMjIlM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBpbnB1dFJlZiUyMCUzRCUyMHVzZVNpZ25hbCUzQ0hUTUxJbnB1dEVsZW1lbnQlM0UoKSUzQiU1Q24lNUNuJTIwJTIwdXNlVmlzaWJsZVRhc2slMjQoKGN0eCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBpbnB1dCUyMCUzRCUyMGN0eC50cmFjaygoKSUyMCUzRCUzRSUyMGlucHV0UmVmLnZhbHVlKSUzQiU1Q24lMjAlMjAlMjAlMjBpZiUyMChpbnB1dCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29uc3QlMjBoYW5kbGVyJTIwJTNEJTIwKGUlM0ElMjBXaGVlbEV2ZW50KSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBlLnByZXZlbnREZWZhdWx0KCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBpbnB1dC5hZGRFdmVudExpc3RlbmVyKCU1QyUyMndoZWVsJTVDJTIyJTJDJTIwaGFuZGxlciklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY3R4LmNsZWFudXAoKCklMjAlM0QlM0UlMjBpbnB1dC5yZW1vdmVFdmVudExpc3RlbmVyKCU1QyUyMndoZWVsJTVDJTIyJTJDJTIwaGFuZGxlcikpJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlN0QpJTNCJTVDbiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQyUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NwJTNFTm9ybWFsJTIwaW5wdXQlM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2lucHV0JTIwdHlwZSUzRCU1QyUyMm51bWJlciU1QyUyMiUyMG5hbWUlM0QlNUMlMjJub3JtYWwlNUMlMjIlMjB2YWx1ZSUzRCU1QyUyMjAlNUMlMjIlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDcCUzRURlZmF1bHQlMjBwcmV2ZW50ZWQlM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2lucHV0JTIwdHlwZSUzRCU1QyUyMm51bWJlciU1QyUyMiUyMG5hbWUlM0QlNUMlMjJub3JtYWwlNUMlMjIlMjB2YWx1ZSUzRCU1QyUyMjAlNUMlMjIlMjBwcmV2ZW50ZGVmYXVsdCUzQXdoZWVsJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ3AlM0VNYW51YWwlMjBwcmV2ZW50RGVmYXVsdCgpJTIwKHRoaXMlMjBvbmUlMjB3b3JrcyklM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2lucHV0JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJlZiUzRCU3QmlucHV0UmVmJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0QlNUMlMjJudW1iZXIlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbmFtZSUzRCU1QyUyMm5vcm1hbCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YWx1ZSUzRCU1QyUyMjAlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjB0eXBlJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBBcHAlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQyUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

**Comment by og-dev** [comment]
> [Here is a playground showing the issue](https://qwik.builder.io/playground/#version=1.1.4&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU2lnbmFsJTJDJTIwdXNlVmlzaWJsZVRhc2slMjQlMjAlN0QlMjBmcm9tJTIwJTVDJTIyJTQwYnVpbGRlci5pbyUyRnF3aWslNUMlMjIlM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBpbnB1dFJlZiUyMCUzRCUyMHVzZVNpZ25hbCUzQ0hUTUxJbnB1dEVsZW1lbnQlM0UoKSUzQiU1Q24lNUNuJTIwJTIwdXNlVmlzaWJsZVRhc2slMjQoKGN0eCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBpbnB1dCUyMCUzRCUyMGN0eC50cmFjaygoKSUyMCUzRCUzRSUyMGlucHV0UmVmLnZhbHVlKSUzQiU1Q24lMjAlMjAlMjAlMjBpZiUyMChpbnB1dCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29uc3QlMjBoYW5kbGVyJTIwJTNEJTIwKGUlM0ElMjBXaGVlbEV2ZW50KSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBlLnByZXZlbnREZWZhdWx0KCklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBpbnB1dC5hZGRFdmVudExpc3RlbmVyKCU1QyUyMndoZWVsJTVDJTIyJTJDJTIwaGFuZGxlciklM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY3R4LmNsZWFudXAoKCklMjAlM0QlM0UlMjBpbnB1dC5yZW1vdmVFdmVudExpc3RlbmVyKCU1QyUyMndoZWVsJTVDJTIyJTJDJTIwaGFuZGxlcikpJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlN0QpJTNCJTVDbiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQyUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NwJTNFTm9ybWFsJTIwaW5wdXQlM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2lucHV0JTIwdHlwZSUzRCU1QyUyMm51bWJlciU1QyUyMiUyMG5hbWUlM0QlNUMlMjJub3JtYWwlNUMlMjIlMjB2YWx1ZSUzRCU1QyUyMjAlNUMlMjIlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDcCUzRURlZmF1bHQlMjBwcmV2ZW50ZWQlM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2lucHV0JTIwdHlwZSUzRCU1QyUyMm51bWJlciU1QyUyMiUyMG5hbWUlM0QlNUMlMjJub3JtYWwlNUMlMjIlMjB2YWx1ZSUzRCU1QyUyMjAlNUMlMjIlMjBwcmV2ZW50ZGVmYXVsdCUzQXdoZWVsJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ3AlM0VNYW51YWwlMjBwcmV2ZW50RGVmYXVsdCgpJTIwKHRoaXMlMjBvbmUlMjB3b3JrcyklM0MlMkZwJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2lucHV0JTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJlZiUzRCU3QmlucHV0UmVmJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHR5cGUlM0QlNUMlMjJudW1iZXIlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbmFtZSUzRCU1QyUyMm5vcm1hbCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB2YWx1ZSUzRCU1QyUyMjAlNUMlMjIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjB0eXBlJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBBcHAlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQyUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

Thanks [cmbartschat](https://github.com/cmbartschat) for posting a minimal reproduction of this issue

**Comment by cmbartschat** [comment]
No problem, looks like this issue doesn't have the tags/title format as other issues like https://github.com/BuilderIO/qwik/issues/4342, do you have access to update that?

**Comment by og-dev** [comment]
> No problem, looks like this issue doesn't have the tags/title format as other issues like #4342, do you have access to update that?

No, I don't have access to update title/tag format.
If you can do it, please do. I'll appreciate that.

**Comment by manucorporat** [comment]
Thanks @cmbartschat for the repo case! 

The issue seems related to Passive events, if we check the console logs we see this:
```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.`
```
