### ISSUE TITLE
Deno middleware breaks binary artefacts in Safari

### ISSUE THREAD

**Issue by jaroel** [BuilderIO/qwik#4345]
https://github.com/BuilderIO/qwik/blob/784225efe11aa7c9cf8926ed8276cda96037188e/packages/qwik-city/middleware/deno/index.ts#L112

This breaks non-text files like images in Safari. Chrome works fine.
When I replace `Deno.readTextFile` locally with `Deno.readFile` Safari is happy again.

This is in Safari Version 16.5 (18615.2.9.11.4) on MacOs 13.4 (22F66) on an M1.

**Comment by manucorporat** [comment]
would u be up to make a PR?

**Comment by jaroel** [comment]
@manucorporat here ya go
