### ISSUE TITLE
[🐞] Calling `next()` in endpoint throws exception

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#4351]
### Which component is affected?

Qwik Runtime

### Describe the bug

```
import { component$ } from '@builder.io/qwik';
import { type RequestHandler } from '@builder.io/qwik-city';

export const onGet: RequestHandler = async ({ next }) => {
  console.log('onGET start');
  next();  // <== COMMENTING THIS OUT WILL MAKE IT WORK
  console.log('onGET end');
};

export const onRequest: RequestHandler = async ({ next }) => {
  console.log('onRequest start');
  next();
  console.log('onRequest end');
};

export default component$(() => {
  console.log('Render default component');
  return <div>Hello Qwik!</div>;
});
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-jh9mbv?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

1. navigate to https://stackblitz.com/edit/qwik-starter-jh9mbv?file=src%2Froutes%2Findex.tsx
2. Notice component rendering.
3. Uncomment `next()`  in https://stackblitz.com/edit/qwik-starter-jh9mbv?file=src%2Froutes%2Findex.tsx
4. Observe that the project now fails.

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
Workaround/fix:
```tsx
export const onGet: RequestHandler = async ({ next }) => {
  console.log('onGET start');
  // UNCOMMENT TO SEE EXCEPTION
  await next();
  console.log('onGET end');
};

export const onRequest: RequestHandler = async ({ next }) => {
  console.log('onRequest start');
  await next();
  console.log('onRequest end');
};
```
the reason is crashing is that by shadowing the promise, qwik does not know when the qwik render finish, causing a misorder with headers

**Comment by mhevery** [comment]
Ohh, that makes total sense. Can't believe I did not think of it. Would it be possible to have a good error message when the user forgets to await?

**Comment by keuller** [comment]
I did some tests regarding it and, this behaviour only occurs on `dev mode`. When I perform `pnpm build && pnpm preview` this error won't happen.

**Comment by mhevery** [comment]
I think the issue was missing `await` keyword. Once added everything works as expected.
