### ISSUE TITLE
[✨] Unattended CLI app creation

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#4353]
### Is your feature request related to a problem?

In Next.js we use this command to create an app automatically (unattended) by providing parameters:

    npx --yes create-next-app next --use-npm --js --eslint --no-src-dir --app --import-alias @/* --tailwind

Let us have the same experience in Qwik's CLI.

### Describe the solution you'd like

I would like to be able to create a Qwik app automatically without interacting with the CLI.

### Describe alternatives you've considered

There is no alternative solution for now.

**Comment by manucorporat** [comment]
I would love to see a PR to enable this! i think it was possible at some point, maybe we need docs? i am not sure

**Comment by b4s36t4** [comment]
@manucorporat Would love to work on this, any help or readme on the cli package to start things quickly?!

**Comment by balaji-sivasakthi** [comment]
I would like to work on this feature to bring qwik CLI as like as next js.  
@manucorporat  can you assign it to me?

**Comment by MrWaip** [comment]
@manucorporat Hi! Still relevant? Maybe I try to implement it?

**Comment by zanettin** [comment]
@MrWaip i would still be interessted in yes 🙏 thanks for your time!

**Comment by MrWaip** [comment]
Someone check PR https://github.com/BuilderIO/qwik/pull/4932

Maybe It's crap :D

**Comment by MrWaip** [comment]
<img width="810" alt="image" src="https://github.com/BuilderIO/qwik/assets/37497663/316df9af-a558-42f2-a830-8ca1b5f0304c">

**Comment by zanettin** [comment]
Hi @MrWaip 👋 
thanks again for your time and for creating the PR! and sorry that it may takes a bit longer to review and approve it. we do our bests to tackle each PR and issue in the best possible way 👼 thanks again for sour help and patience 🙏
