### ISSUE TITLE
[✨] `server$` needs middleware

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#4366]
### Is your feature request related to a problem?

```typescript
import { component$ } from '@builder.io/qwik';
import { server$, type RequestHandler } from '@builder.io/qwik-city';

export const onRequest: RequestHandler = async ({ next }) => {
  console.log('onRequest start');
  await next();
  console.log('onRequest end');
};

export default component$(() => {
  console.log('Render default component');
  return (
    <div
      onClick$={() => {
        server$(() => console.log('SERVER'))();
      }}
    >
      Hello Qwik!
    </div>
  );
});

```

In the above code, the `onRequest` methods run on the initial render. But not on `server$`. This is in issues because I would like to do authentication on all requests, including `server$`, which means I would like to execute the `onRequest` so that I can ensure that auth is working.

### Describe the solution you'd like

Run `onRequest` as part of `server$`

### Describe alternatives you've considered

Doing auth in each request is not scalabale.

**Comment by RaeesBhatti** [comment]
I created a PR that adds a little documentation around this topic: https://github.com/BuilderIO/qwik/pull/5033
