### ISSUE TITLE
[🐞] Reactivity is broken when using props spreading combined with useResource$

### ISSUE THREAD

**Issue by cmbartschat** [BuilderIO/qwik#4368]
### Which component is affected?

Qwik Runtime

### Describe the bug

Something weird is happening when passing a resolved resource value as a prop to a component, which passes it as a prop to another component that is using props spreading.

Seems like some sort of race condition because adding a delay fixes the problem.

### Reproduction

https://stackblitz.com/edit/qwik-starter-4mkvzb?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Open the stackblitz
2. Run the server (dev or preview)
3. See that the two buttons are disabled and say "Text is empty"
4. Type into the text box
5. See that the buttons both now say "Example button"
6. However, the first button is no longer disabled, while the second one is still disabled, which is unexpected.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4 
    @builder.io/qwik-city: ^1.1.4 => 1.1.4 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.5 => 4.3.5
```

**Comment by manucorporat** [comment]
Looking into it!
