### ISSUE TITLE
[🐞] Stragen Behavior with Docker and csrf-protection

### ISSUE THREAD

**Issue by incacola** [BuilderIO/qwik#4372]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I build a Docker container with Express once I publish my container to PROD the images and Videos do not get showed.

Locally during it works followings things work:
 - Fonts
 - Images
 - svg
 - Videos

Tested with qwik preview, pnpm run dev & docker run.

After Deployment only following things work:
 - Fonts
 - svg
Videos and Images are missing. I did try to turn off the csrf-protection to see if that is the issue but it seems not to work.
I will attach two images to compare. 
<img width="199" alt="Bildschirmfoto 2023-05-30 um 09 48 03" src="https://github.com/BuilderIO/qwik/assets/9801192/1faefb8b-8e81-4712-8607-66cdfa97cc8a">
<img width="204" alt="Bildschirmfoto 2023-05-30 um 09 50 56" src="https://github.com/BuilderIO/qwik/assets/9801192/8bbaba1c-09fa-4148-9c6e-e6e6b96f858a">

Here is the code of the Dockerfile and the express file: 

```Dockerfile
FROM node:20.2-alpine3.16 as build

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY ./ ./

# Build the project
RUN npm run build

FROM node:20.2-alpine3.16 as production

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/server ./server
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./package.json

EXPOSE 3000

ENV ADDRESS=0.0.0.0 PORT=3000

# Start the application
CMD [ "ORIGIN=https://wao.army node", "server/entry.express"]
```

```jsx
/*
 * WHAT IS THIS FILE?
 *
 * It's the entry point for the Express HTTP server when building for production.
 *
 * Learn more about Node.js server integrations here:
 * - https://qwik.builder.io/docs/deployments/node/
 *
 */
import { createQwikCity, type PlatformNode } from '@builder.io/qwik-city/middleware/node';
import qwikCityPlan from '@qwik-city-plan';
import { manifest } from '@qwik-client-manifest';
import render from './entry.ssr';
import express from 'express';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

declare global {
  interface QwikCityPlatform extends PlatformNode {}
}

// import compression from 'compression';

// Directories where the static assets are located
const distDir = join(fileURLToPath(import.meta.url), '..', '..', 'dist');
const buildDir = join(distDir, 'build');

// Allow for dynamic port
const PORT = process.env.PORT ?? 3000;
const ADDRESS = process.env.ADDRESS ?? 'localhost';

// Create the Qwik City Node middleware
const { router, notFound } = createQwikCity({ render, qwikCityPlan, manifest, checkOrigin: false });

// Create the express server
// https://expressjs.com/
const app = express();

// Enable gzip compression
// app.use(compression());

// Static asset handlers
// https://expressjs.com/en/starter/static-files.html
app.use(`/build`, express.static(buildDir, { immutable: true, maxAge: '1y' }));
app.use(express.static(distDir, { redirect: false }));

// Use Qwik City's page and endpoint request handler
app.use(router);

// Use Qwik City's 404 handler
app.use(notFound);

// Start the express server
app.listen(PORT, () => {
  /* eslint-disable */
  console.log(`Server started: http://${ADDRESS}:${PORT}/`);
});
```

### Reproduction

https://wao.army/

### Steps to reproduce

npm run qwik add express
Dockerbuild
Deploy

And see if the images are there.

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 240.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Brave Browser: 113.1.51.118
    Chrome: 112.0.5615.49
    Firefox: 108.0.1
    Safari: 16.4
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0 
    @builder.io/qwik: ^1.1.2 => 1.1.2 
    @builder.io/qwik-city: ^1.1.2 => 1.1.2 
    undici: 5.22.0 => 5.22.0 
    vite: 4.3.5 => 4.3.5
```

**Comment by octoper** [comment]
I don't think that an issue with CSRF, you should also copy the `public` folder inside the docker container.

**Comment by manucorporat** [comment]
can you console.log the value of buildDir? and distDir and see if it's correct?

**Comment by incacola** [comment]
> I don't think that an issue with CSRF, you should also copy the `public` folder inside the docker container.

The public Folder gets build during the Docker build inside the container.

**Comment by incacola** [comment]
> > I don't think that an issue with CSRF, you should also copy the `public` folder inside the docker container.
> 
> The public Folder gets build during the Docker build inside the container.

Hey Manu here are the logs you requested. 

```bash
Here is the logs of the distDir:  /app/dist
Here is the logs of the buildDir:  /app/dist/build
Server started: http://0.0.0.0:3000/
```

**Comment by incacola** [comment]
> can you console.log the value of buildDir? and distDir and see if it's correct?

Hey Manu here are the logs: 

```Bash
Here is the logs of the distDir:  /app/dist
Here is the logs of the buildDir:  /app/dist/build
Server started: http://0.0.0.0:3000/
```

**Comment by barbalex** [comment]
I used this example to build my own node server with docker. Would be great if the docs included such an example.

**Comment by incacola** [comment]
I found out that the issue has something to do with the create emty template. I will have to check the difference in code and then update this issue so that we can fix it for everyone before we include it in the docks.

**Comment by incacola** [comment]
There is also now a new ```entry.express.js``` file so I do not know if the issue still persist. I will close the issue since there is an easy workaround.

**Comment by incacola** [comment]
> I used this example to build my own node server with docker. Would be great if the docs included such an example.

Wrote an article about it on our website but as I said I do not know if the issue still persist.

https://wao.army/articles/how-to-deploy-a-qwik-app-with-docker/

**Comment by barbalex** [comment]
@incacola  By the way, I am using a fastify server (https://github.com/barbalex/bb4/blob/master/backend/app/Dockerfile) and have not encoutered your issue
