### ISSUE TITLE
[🐞] Type error with async component$ render function

### ISSUE THREAD

**Issue by rshackleton** [BuilderIO/qwik#4376]
### Which component is affected?

Qwik Runtime

### Describe the bug

When using an async render function ([which the docs imply should be supported here](https://qwik.builder.io/docs/components/rendering/#async-rendering)) TypeScript reports an error with the return type. However, the code itself compiles and runs as expected with the initial rendering being blocked while the promise is resolved.

```
Argument of type '() => Promise<JSX.Element>' is not assignable to parameter of type 'OnRenderFn<{}>'.
  Type 'Promise<Element>' is missing the following properties from type 'JSXNode<any>': type, props, immutableProps, children, and 2 more.(2345)
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-h1dy5b?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Create a new Qwik project
Change a component to async render
Type error appears.

### System Info

```shell
  System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 115.02 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.2
    Safari: 15.4
```

**Comment by ulic75** [comment]
@zanettin, I believe your wrote this doc that demonstrates the issue in question ([Advanced/ESLint](https://qwik.builder.io/docs/advanced/eslint/#use-method-usage)).  Is the async function in the example erroneous? I was under the impression that components had to be synchronous.

**Comment by zanettin** [comment]
Hi @ulic75 and @rshackleton 👋 

thanks for pinging me! i have the eslint examples from the unit test file and i guess that during my local tests TSC was not working correctly. That's why these examples are on the page. i can't see any cases on the code base where this is used by now. maybe it was once an option. 

hope @manucorporat can bring in a bit light to this. i can't tell if this is just an TS typing issue or smth that is technically not/no longer possible tbh

**Comment by manucorporat** [comment]
We dont allow to return a promise in `component$` on purpose, this is not an issue. after await of reactivity would be broken, leaving developers confused why the component is not rerendering when the state changes.

**Comment by manucorporat** [comment]
We might need to fix the docs, the render is async, but the components must return some JSX syncronously.

It's possible to do this:

```tsx
<div>{promise}</div>
```
