### ISSUE TITLE
[🐞] context change in useTask$ not rendering

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#4383]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm building a Tab list with this API :
```jsx
export default component$(() => {
  return (
    <TabGroup>
      <Tab label="Label">Some content in the panel</Tab>
    </TabGroup>
  );
});
```
The labels in Tab update a context in the TabGroup to display the list of labels.
It works well with `useVisibleTask$` but not with `useTask$`, so it means rendering on the browser instead of pure HTML from SSR.
Here is the code :
```jsx
const TabsContext = createContextId<any>('TabsContext');

export const TabGroup = component$(() => {
  const tabs = useSignal<string[]>([]);
  useContextProvider(TabsContext, tabs);
  return (
    <div>
      <div role="tablist">
        {tabs.value.map((label) => (
          <button key={label}>{label}</button>
        ))}
      </div>
      <Slot />
    </div>
  );
});
export const Tab = component$(({ label }: { label: string }) => {
  const tabs = useContext(TabsContext);

  // Working
  // useVisibleTask$(() => {
  //   tabs.value = tabs.value.concat(label);
  // });

  // Not working
  useTask$(() => {
    tabs.value = tabs.value.concat(label);
  });
  return (
    <div role="tabpanel">
      <Slot />
    </div>
  );
});
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-hv3ksh?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

`npm start`
No label is displayed.
Comment out `useVisibleTask$` and it's working.

### System Info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 17.36 GB / 31.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1095.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4
    @builder.io/qwik-city: ^1.1.4 => 1.1.4
    undici: 5.22.1 => 5.22.1
    vite: 4.3.5 => 4.3.5
```

**Comment by GrandSchtroumpf** [comment]
As a complementary note: Another issue using `useVisibleTask$` is that we cannot use `display: none` on the tabpanel that are not selected as it wouldn't run `useVisibleTask$. Which can create performance issue as `useVisibleTask$` of all component inside the panels will run at once.

**Comment by cmbartschat** [comment]
I think this is the same underlying issue as https://github.com/BuilderIO/qwik/issues/4210#issuecomment-1546913098

**Comment by wmertens** [comment]
> As a complementary note: Another issue using `useVisibleTask$` is that we cannot use `display: none` on the tabpanel that are not selected as it wouldn't run `useVisibleTask$. Which can create performance issue as `useVisibleTask$` of all component inside the panels will run at once.

You can work around this by either setting the strategy to document-idle, or by rendering `<><div/><PreviousReturn /></>` which will attach the visibility check to that extra div.

**Comment by wmertens** [comment]
The problem you're encountering was solved in Qwik-UI by making the tabgroup an inline component, which gets the children and can read all the labels. This also fixes the problem of out-of-order rendering, so that the labels stay in child order and not in child render order.

https://github.com/qwikifiers/qwik-ui/blob/02acf3ef5ff2a43626c93a53e86f5ba2a4263996/packages/kit-headless/src/components/tabs/tabs.tsx#L68-L71

**Comment by gxanshu** [comment]
I'm getting same problem too. I'm trying to update the context from useTask$ and it updates the context state but UI is not rerendering.

**Comment by wmertens** [comment]
I'm closing this as old and probably fixed. @gxanshu can you create a new issue with a repro (preferably in https://qwik.dev/playground) if it's not fixed yet?

**Comment by nhayhoc** [comment]
https://qwik.dev/playground/#f=7VbLSsNAFN33K0JWkYYUV0pJBtwIutCFy1JETDSB0oqlSAnz7577mMk0pg%2FBjdAu%2Brp37uPkzLl3hzTXV0OsSf30TfXDj00yKQPTHh%2FZqUfaU%2FgneJGi4GBUoNA%2B0VsWsGmkG4GMmdncWJPEei5Gc6ORhLqjOVjs8rkw9AzE3pSw%2BhaTSxz1JhzVvOLjLqSmuYCn3yBc1AgRM4gDZL8II2Rctlgy0WTKBPc9Ph%2BbdZ24WJTK0pu7govGtE1p8wm%2B4PZps7er1aFeZXr%2BTbstbz%2FWd80%2F4YoMHFOiuv0rRmUZG59f65fle1XGqZTT9XcMioNY%2FgAI62q3mrWEQ5BuPLbmpiyZHLLZEoanSGAH1ToEsqNhMpsrUH3JVhjTSBjM1R7Dkz2H8Pyqt1rFEtKiC1xdfVbANUBnCBZVAeKK6kOOxcLsjTiN2vunx4dMVvjmbStVaQJQkE5LnM0iECC%2BeV6Bfv1HPpFo%2FvnQncbrPGb%2B35j5Bg

I am trying to update a component's context inside a useTask hook, anticipating that this would trigger a re-render of the component, similar to the behavior in React's useEffect when updating the state. However, after the context is updated, no update signal in provider component, no re-render occurs, leaving the component's UI in an outdated state.

**Comment by wmertens** [comment]
@nhayhoc you're using an array in a signal and then mutating it, that doesn't work.

If you want to mutate arrays you need to use useStore.

**Comment by wmertens** [comment]
You're mutating the store while rendering, and by the time you're rendering the items, the json stringify was already sent to the client
