### ISSUE TITLE
[🐞] Custom 404 page does not works

### ISSUE THREAD

**Issue by keuller** [BuilderIO/qwik#4399]
### Which component is affected?

Qwik Runtime

### Describe the bug

According to the documentation [Custom 404 page](https://qwik.builder.io/docs/advanced/routing/#custom-404-page) we must create a file named `404.tsx` inside `src/routes` folder. However,  when we try to build the application `pnpm build` the process fails the following message:

```shell
[vite-plugin-qwik-city] Could not load /Users/keuller/workspace/personal/basic/@qwik-city-plan (imported by src/s_02wmimzeabk.js): More than one route has been found for pathname "/". Please narrow it down to only one of these:
  - /Users/keuller/workspace/personal/basic/src/routes/400.tsx
  - /Users/keuller/workspace/personal/basic/src/routes/index.tsx
error during build:
Error: Could not load /Users/keuller/workspace/personal/basic/@qwik-city-plan (imported by src/s_02wmimzeabk.js): More than one route has been found for pathname "/". Please narrow it down to only one of these:
  - /Users/keuller/workspace/personal/basic/src/routes/400.tsx
  - /Users/keuller/workspace/personal/basic/src/routes/index.tsx
```

Looks like the builder recognises `400.tsx` file as a root file.

### Reproduction

N/A

### Steps to reproduce

Create a file named `400.tsx` inside `src/routes` folder and try to run the application.

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 16.00 GB
    Shell: /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4
    @builder.io/qwik-city: ^1.1.4 => 1.1.4
    undici: 5.22.1 => 5.22.1
    vite: 4.3.5 => 4.3.5
```

**Comment by ehrencrona** [comment]
The issue here seems to be a typo in the filename: it's supposed to be `404.tsx` and not `400.tsx`

**Comment by gioboa** [comment]
@keuller can we close it?
