### ISSUE TITLE
[🐞] nonce is missing on scripts

### ISSUE THREAD

**Issue by tzdesign** [BuilderIO/qwik#4411]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I'm not sure what exactly this code is. It looks like something in qwik city.

These two tags are rendered in preview without a nonce.

```html
    <script>
    (function() {
        const l = location
        , c = l.pathname + l.search
        , t = "_qCityPopstateFallback"
        , o = "_qCityHistory";
        window[t] || (window[t] = ()=>{
            window[o] || c === (l.pathname + l.search) || l.reload()
        }
        ,
        setTimeout(()=>{
            addEventListener("popstate", window[t])
        }
        , 0))
    }
    )();
</script>
<!--/qv-->
<!--/qv-->
<script q:key="1Z_0">
    ((s,a,i,r)=>{
        i = (e,t)=>{
            t = document.querySelector("[q\\:base]"),
            t && a.active && a.active.postMessage({
                type: "qprefetch",
                base: t.getAttribute("q:base"),
                ...e
            })
        }
        ,
        document.addEventListener("qprefetch", e=>{
            const t = e.detail;
            a ? i(t) : t.bundles && s.push(...t.bundles)
        }
        ),
        navigator.serviceWorker.register("/service-worker.js").then(e=>{
            r = ()=>{
                a = e,
                i({
                    bundles: s
                })
            }
            ,
            e.installing ? e.installing.addEventListener("statechange", t=>{
                t.target.state == "activated" && r()
            }
            ) : e.active && r()
        }
        ).catch(e=>console.error(e))
    }
    )([])
</script>
```

### Reproduction

 https://github.com/the-zimmermann/csp-nonce-issue

### Steps to reproduce

Just run preview

Run a qwik app with a plugin middleware:

plugin@csp.ts

```ts
import type { RequestHandler } from '@builder.io/qwik-city';

export const onRequest: RequestHandler = (ev) => {
  const nonce = Date.now().toString(55);
  ev.sharedMap.set('@nonce', nonce);

  const csp = [
    `default-src 'self' 'unsafe-inline'`,
    `font-src 'self' `,
    `img-src 'self' `,
    `script-src 'strict-dynamic' 'unsafe-inline' 'nonce-${nonce}' `,
    `style-src 'self' 'unsafe-inline'`,
    `frame-src 'self' 'nonce-${nonce}'`,
    `object-src 'none'`,
    `base-uri 'self'`,
    `require-trusted-types-for 'script'`
  ];

  ev.headers.set(
    'Content-Security-Policy',
    csp.join('; ')
  );
};

```

### System Info

```shell
Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Edge: 113.0.1774.57
    Firefox: 108.0.2
    Safari: 16.4
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4 
    @builder.io/qwik-city: ^1.1.4 => 1.1.4 
    undici: 5.22.0 => 5.22.0 
    vite: 4.3.3 => 4.3.3
```

**Comment by manucorporat** [comment]
mind creating a new PR?! would be very happy to merge it!

**Comment by tzdesign** [comment]
@manucorporat I still have no idea what the flow of qwik-city is.
I looked up the code and the first script implements clientNavigate, but no clue where it is embedded.

The second one might be sw-prefetch.ts

But somehow, this looks correctly implemented:
```ts
export const ServiceWorkerRegister = (props: { nonce?: string }) =>
  jsx('script', { dangerouslySetInnerHTML: swRegister, nonce: props.nonce });
```

**Comment by DustinJSilk** [comment]
@tzdesign can you share a link to a repository or stackblitz to reproduce the issue and i will try and help

**Comment by tzdesign** [comment]
@DustinJSilk Stackblitz fails somehow. These guys seem to be having trouble.

See https://github.com/the-zimmermann/csp-nonce-issue

I just added the plugin the scripts are reported and one odd thing a temporary script or smt?

<img width="987" alt="image" src="https://github.com/BuilderIO/qwik/assets/3037096/79b23927-6b05-4a64-84fe-e687f8a9ad1a">

<img width="358" alt="image" src="https://github.com/BuilderIO/qwik/assets/3037096/42ca56ce-716c-49b2-aa3d-41e8ad4ea7d8">

**Comment by DustinJSilk** [comment]
I see you havent passed the nonce to the ServiceWorkerRegister. Try updating your root.tsx file to include this:

```tsx
  const nonce = useServerData<string | undefined>('nonce')
 
  return <QwikCityProvider>
      <head>
        <meta charSet="utf-8" />
        <link rel="manifest" href="/manifest.json" />
        <RouterHead />
      </head>
      <body lang="en">
        <RouterOutlet />
        <ServiceWorkerRegister nonce={nonce} />
      </body>
    </QwikCityProvider>
```

**Comment by tzdesign** [comment]
@DustinJSilk if you do this in my repository do you still see the issue pointing to a missing script (closing <style/>)

**Comment by DustinJSilk** [comment]
Feel free to submit a PR with documentation. 
We manually pass the none to the service worker since it is a lite component (not created with `component$`) and was not easy to pass the value to the component automatically.

I don't use `require-trusted-types-for` in my CSP policy. Removing that solves the TrustedScriptURL issue.

**Comment by tzdesign** [comment]
@DustinJSilk I've removed require-trusted-types-for and you're right about that, but would you please check again?

There are still bugs like when there are some temporary scripts, if you follow the link in dev-tools, you end up at the end of a style tag and there are no script tags anymore.

@jordanw66 thanks for clarifying

<img width="435" alt="image" src="https://github.com/BuilderIO/qwik/assets/3037096/b6cf308b-8b70-4e1d-ba2e-dd2f775a5ade">

**Comment by tzdesign** [comment]
@DustinJSilk I'm pretty busy too, but I checked it out. v1.0.0 works fine, not a single report in the console.

I added a page to the docs in this pr #4440. 
I will check another version after lunch and let you know what I find.

**Comment by tzdesign** [comment]
@DustinJSilk looks like version 1.1 is already having this issue. 

I think it's the new RouterOutlet by @manucorporat with a plain script.
https://github.com/BuilderIO/qwik/blob/6dd1b47923b62f9673c93040cdd19778f3a4ce92/packages/qwik-city/runtime/src/router-outlet-component.tsx#L33

Would it be save to add ```useServerData``` here?
```tsx

/**
 * @public
 */
export const RouterOutlet = component$(() => {
  _jsxBranch();

  const nonce = useServerData<string | undefined>('nonce');

  const { value } = useContext(ContentInternalContext);
  if (value && value.length > 0) {
    const contentsLen = value.length;
    let cmp: JSXNode | null = null;
    for (let i = contentsLen - 1; i >= 0; i--) {
      cmp = jsx(value[i].default, {
        children: cmp,
      });
    }
    return (
      <>
        {cmp}
        <script dangerouslySetInnerHTML={popStateScript} nonce={nonce}></script>
      </>
    );
  }
  return SkipRender;
});

```

If yes let me know, I can create another PR

**Comment by DustinJSilk** [comment]
Yes that looks like it would work. Have you managed to test if it solves the problem in your repo?

**Comment by tzdesign** [comment]
@DustinJSilk In my pr I changed the router-outlet, but there is a discussion if it should be changed to a prop instead of useServerData. Let's see what Manu thinks as he has rewritten this file.

**Comment by DustinJSilk** [comment]
@tzdesign is there a PR open for this change yet? I havent seen one.

(A prop would make sense as it keeps it inline with how the nonce is passed to the service worker)
