### ISSUE TITLE
[✨] Serialize Uint8Array & other TypedArray

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#4416]
### Is your feature request related to a problem?

I'm using webauthn to manage credentials. It using a lot of Uint8Array. It would be a great devX improvement to support serializing TypedArray out-of-the-box.
```jsx
// Generate random Uint8Array challenge on the server
export const useChallenge = routeLoader$(() => new Uint8Array([...]));

export const verify = server$((credentials: AuthenticatorResponse) => {
  // verify credentials from the client
});

export default component$(async () => {
  const challenge = useChallenge();
  const signup = event$(() => {
    const credentials = await navigator.credential.create({
      publicKey: {
        challenge,
        ...
      }
    });
    await verify(credentials.response);
  });
  return <button onClick$={signup}>Signup</button>
});
```

### Describe the solution you'd like

Ideally Qwik would serialize/deserialize the native TypedArray. As they are supported by all browsers, node, deno and web workers, it would greatly reduce the difficulty of doing it manually at every step.

### Describe alternatives you've considered

Doing it manually

**Comment by genki** [comment]
I think the `Uint8Array` is widely used and important compared to other typed arrays.
So I made it and sent a PR.
