### ISSUE TITLE
[🐞] `this` is undefined in server$ function when called consequentially. 

### ISSUE THREAD

**Issue by thekip** [BuilderIO/qwik#4417]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When two or more `$server` functions called one after each other the second called function would have `this === undefined`

This doesn't happen when they called concurrently in `Promise.all`

```ts
const serverFunctionA = server$(async function () {
  console.log('serverFunctionA', this);
  return true;
});

const serverFunctionB = server$(async function () {
  console.log('serverFunctionB', this); // <--- here `this` would be undefined
  return true;
});

export default component$(() => {
  const resource = useResource$(async () => {
    const resultA = await serverFunctionA();
    const resultB = await serverFunctionB();

    return { resultA, resultB };
  });

  return (
    <Resource
      value={resource}
      onResolved={({ resultA, resultB }) => (
        <>
          {resultA} {resultB}
        </>
      )}
    />
  );
});
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-jdcnqd?file=src%2Froutes%2Findex.tsx

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 75.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 3.5.1 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 95.0.2
    Safari: 16.4
  npmPackages:
    @builder.io/qwik: 1.1.4 => 1.1.4 
    @builder.io/qwik-city: ~1.1.4 => 1.1.4 
    @builder.io/qwik-react: ^0.5.0 => 0.5.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

**Comment by hbendev** [comment]
I might not have time to fix this in the coming weeks. However, I can share where this issues arises from.

In [use-core.ts](https://github.com/BuilderIO/qwik/blob/592dadedb6a00156a8e6bf110adbe5f3795d9025/packages/qwik/src/core/use/use-core.ts#L114C5-L114C40), when  `x_component_resource_useResource_hash` (the qrl callback of `useResource`) is ran, the invoke context is removed after the first server function (`serverFunctionA`) is scheduled. This is because useResource does return a `ResourceReturn` object, before values are resolved. The context should somehow be kept through this async flow.

**Comment by mees-van-wel** [comment]
What's the status on this?

**Comment by hbendev** [comment]
@genox reported a similar issue in a Discord thread: https://discord.com/channels/842438759945601056/1160923192538439711/1160923192538439711.

**Comment by notcod** [comment]
Is there any info when it will be fixed? :+1:

**Comment by gioboa** [comment]
I'll look at it 😊

**Comment by PatrickJS** [comment]
this was auto closed. @wmertens can cut a new release. I had tests to confirm it only worked with the fix. bun, deno, and cloudflare supports async_hooks
