### ISSUE TITLE
[📖] How to enable 'nonce' setting ?

### ISSUE THREAD

**Issue by solomancode** [BuilderIO/qwik#4423]
### Suggestion

How to enable 'nonce' setting ? I couldn't find help in the docs. on how to configure it.

I'm getting the following issues when I deploy my app to Google Cloud Run.
![image](https://github.com/BuilderIO/qwik/assets/7840989/eda8321a-f17c-4b33-9b9f-b991fb2957a5)

**Comment by arkhvoid** [comment]
This is CSP related issue, not a Qwik issue. Since Qwik inline script in html, you need to add `unsafe-inline` to your CSP `script-src` or simply get rid of CSP header. CSP header is either insert by your http server, in this case Google Cloud, or a meta tag in your html head tag.

If you don't want to allow inline script, as the log suggested, you have to either copy the hash the browser generated for you to your `script-src` or have a server to generate `nonce-{random-value}` to every script tag on every request and add it to the `script-src`.

**Comment by ahnpnl** [comment]
It was added as a feature but not documented, see https://github.com/BuilderIO/qwik/issues/2663 Basically in your codes, use `sharedMap` to add `nonce`

**Comment by solomancode** [comment]
@ahnpnl Thanks.

**Comment by LukeSchlangen** [comment]
Hi! Googler here. I experienced this same issue when deploying a Qwik application to Cloud Run today.

I'm not a CSP or Qwik expert, but I'd like to help people avoid this issue if there's something we can do.

Is there something we could do on our and to allow deployments to work out-of-the-box on Cloud Run without this error? What would be the best way to do this?

Is there something we can do on the `npm run qwik add cloud-run` command to make this work?

**Comment by LukeSchlangen** [comment]
@ahnpnl shared a solution on Discord, but I can't figure out how to implement it. I tried making these changes to the project, but the build is failing. I think I'm likely doing the configuration incorrectly?

https://discord.com/channels/842438759945601056/842438761287254019/1103749344588468368

```
import crypto from 'crypto';
export const nonce = crypto.randomBytes(16).toString('hex');

/**Thedefaultheadersusedbyhelmet*/
export const DEFAULT_CSP_HEADERS = {
  'Content-Security-Policy': [
    `default-src 'self'`,
    `base-uri 'self'`,
    `font-src 'self' https:data:'`,
    `form-action'self'`,
    `frame-ancestors 'self' img-src 'self' data:`,
    `object-src 'none'`,
    `script-src https: 'nonce-${nonce}' 'strict-dynamic' 'unsafe-eval'`,
    `script-src-attr 'none'`,
    `style-src'self'https:'unsafe-inline'`,
    `upgrade-insecure-requests`,
  ].join(';'),
  'Cross-Origin-Embedder-Policy': 'require-corp',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
  'Origin-Agent-Cluster': '?1',
  'Referrer-Policy': 'no-referrer',
  'X-Frame-Options': 'SAMEORIGIN',
  'Strict-Transport-Security': 'max-age=15552000;includeSubDomains',
  'X-Content-Type-Options': 'nosniff',
  'X-DNS-Prefetch-Control': 'off',
  'X-Download-Options': 'noopen',
  'X-Permitted-Cross-Domain-Policies': 'none',
  'X-XSS-Protection': '0',
};
```

And

```
import type { RequestHandler } from "@builder.io/qwik-city";

import { DEFAULT_CSP_HEADERS, nonce } from '../../config/cspHeaders';

export const onRequest: RequestHandler = ({ sharedMap, headers }) => {
  if (import.meta.env.DEV) {
    sharedMap.set('@nonce', nonce);
    Object.entries(DEFAULT_CSP_HEADERS).forEach(([headerName, headerValue]) => {
      headers.set(headerName, headerValue);
    });
  }
};
```

I've included the @ahnpnl's original images: 

![first image](https://github.com/QwikDev/qwik/assets/5384581/63460199-6ca9-4b74-8eae-2cc58f42cba1)
![second-image](https://github.com/QwikDev/qwik/assets/5384581/36e7e93e-29d4-4b4f-8e69-8c865ea42366)

**Comment by rpdave** [comment]
So I was able to use the above code and it works well. Here is what I did

1. Create a new file `src/config/cspHeaders.ts`, paste the below
```ts
import crypto from 'crypto';
export const nonce = crypto.randomBytes(16).toString('hex');

/**Thedefaultheadersusedbyhelmet*/
export const DEFAULT_CSP_HEADERS = {
  'Content-Security-Policy': [
    `default-src 'self'`,
    `base-uri 'self'`,
    `font-src 'self'`,
    `form-action 'self'`,
    `frame-ancestors 'self'`,
    `img-src 'self' data:`,
    `object-src 'none'`,
    `script-src 'nonce-${nonce}' 'strict-dynamic' 'unsafe-eval'`,
    `script-src-attr 'none'`,
    `style-src 'self' 'unsafe-inline'`,
    `upgrade-insecure-requests`,
  ].join(';'),
  'Cross-Origin-Embedder-Policy': 'require-corp',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
  'Origin-Agent-Cluster': '?1',
  'Referrer-Policy': 'no-referrer',
  'X-Frame-Options': 'SAMEORIGIN',
  'Strict-Transport-Security': 'max-age=15552000;includeSubDomains',
  'X-Content-Type-Options': 'nosniff',
  'X-DNS-Prefetch-Control': 'off',
  'X-Download-Options': 'noopen',
  'X-Permitted-Cross-Domain-Policies': 'none',
  'X-XSS-Protection': '0',
};
```

2. Create/Update a new plugin.ts you want this to be the first plugin that runs so it must be plugin.ts IMO
```ts
import type { RequestHandler } from "@builder.io/qwik-city";
import { DEFAULT_CSP_HEADERS, nonce } from "~/config/cspHeaders";

export const onRequest: RequestHandler = ({ sharedMap, headers }) => {
  sharedMap.set("@nonce", nonce);
  Object.entries(DEFAULT_CSP_HEADERS).forEach(([headerName, headerValue]) => {
    headers.set(headerName, headerValue);
  });
};
```

3. Update entry.could-run.tsx
```ts
...
import { DEFAULT_CSP_HEADERS } from "./config/cspHeaders";
....

server.on("request", (req, res) => {
  for (const header of Object.entries(DEFAULT_CSP_HEADERS)) {
    res.setHeader(...header);
  }

....
```

These are all the changes I made and I can confirm it works for me
