### ISSUE TITLE
[🐞] Cannot find module '@qwik-city-not-found-paths.js'

### ISSUE THREAD

**Issue by tscpp** [BuilderIO/qwik#4426]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I am running my application in development (`npm run dev`), and it works just fine. It is when I try to preview (`npm run preview`) it breaks.

I have noticed that the chunk `server/assets/entry.preview-<hash>.js` is generated which tries to import `./@qwik-city-not-found-paths.js`, but the file exists in the parent directory.

The error I am getting is:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/projects/qwik-starter-pbsez5/server/assets/@qwik-city-not-found-paths.js' imported from /home/projects/qwik-starter-pbsez5/server/assets/entry.preview-40db5240.mjs
```

This issue seems _very_ wired. For example, the implementation of `foo()` is `Object.fromEntries([])`. When I change it, the issue is gone. I have no idea what is happening.

I have successfully been able to reproduce this issue by removing more and more stuff from my original application which has modules imported similar, and where the exact same issue occurs. The reproduction is as small as I possibly could get it.

### Reproduction

https://stackblitz.com/edit/qwik-starter-pbsez5

### Steps to reproduce

1. Run `npm run dev` and you will notice the application works.
2. Run `npm run preview` and the application will break with the same error message.
3. Run `npm run build.preview`. Notice that `server/assets/entry.preview-<hash>.js` is built (which causes this issue).

### System Info

```shell
System:
  OS: Linux 5.0 undefined
  CPU: (2) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 0 Bytes / 0 Bytes
  Shell: 1.0 - /bin/jsh
Binaries:
  Node: 16.14.2 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 7.17.0 - /usr/local/bin/npm
npmPackages:
  @builder.io/qwik: ^1.1.4 => 1.1.4 
  @builder.io/qwik-city: ^1.1.4 => 1.1.4 
  undici: 5.22.1 => 5.22.1 
  vite: 4.3.5 => 4.3.5
```

**Comment by tscpp** [comment]
I have fixed this issue be reorganizing the modules a bit. I don't have this issue anymore. But I am happy to help if needed.

**Comment by samyosm** [comment]
I too am running into this issue, I believe it occurs whenever you use `import()`. May I know how you solved it?

Here's the simplest reproduction:
https://stackblitz.com/edit/qwik-starter-tgvuqv?file=src%2Froutes%2Findex.tsx&view=editor
