### ISSUE TITLE
[🐞] Tasks that track the url run again after cleaning up and the component has already been destroyed

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#4432]
### Which component is affected?

Qwik Runtime

### Describe the bug

When navigating away from the URL, the task `cleanup` is called, but then the task is run again even though the component is destroyed.
This causes a few unexpected issues to occur.

See the below example, you will notice in the console the logs will show:

```
Running task for path:  /
Cleaning up task for path /child/
Running task for path:  /child/
```

When it should show:

```
Running task for path:  /
Cleaning up task for path /
```

```tsx
import { component$, useComputed$, useVisibleTask$ } from "@builder.io/qwik";
import { Link, useLocation } from "@builder.io/qwik-city";

export default component$(() => {
  const { url } = useLocation();

  const pathname = useComputed$(() => url.pathname);

  useVisibleTask$(({ track, cleanup }) => {
    track(() => pathname.value);

    // This should only run on page load for path '/'
    console.log("Running task for path: ", pathname.value);

    // This should only run when leaving the page
    cleanup(() => console.log("Cleaning up task for path", pathname.value));
  });

  return (
    <>
      <Link href="/child/">Click me</Link>
    </>
  );
});

```

### Reproduction

https://github.com/DustinJSilk/qwik-issue-nav-signals

### Steps to reproduce

Run the app
Click on the link
See the issue in the console

### System Info

```shell
N/A
```

**Comment by manucorporat** [comment]
Makes sense! I will look into it! great explanation of the issue!
