### ISSUE TITLE
[🐞] Optimizer incorrectly extracts functions which depend on global functions

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#4438]
### Which component is affected?

Qwik Optimizer (rust)

### Describe the bug

There are 2 problems:

Assume:
```typescript
      <div>{toggle.value ? $localize`singular` : $localize`plural`}</div>
```

The above code gets extracted to:
```html
<script q:func="qwik/json">
document.currentScript.qFuncs=[
  (p0,)=>(p0.value?$localize`singular`:$localize`plural`)
]
</script>
```

## Issue 1

The problem is the `$localize` is now `undefined` because `$localize` only exists in the dev build but not in the production build. (The production build removes `$localize` from src, but it can't reach `$localize` in `<script q:funct="qwik/json">`)

## Issue 2
the execution of the `$localize` should have failed in the browser and those it throws an exception. It seems that Qwik has swaled the exception, this made debugging much harder. It would be easier to understand what the issue was if the exception was thrown.

### Reproduction

https://stackblitz.com/edit/qwik-starter-75rr5q

### Steps to reproduce

1. Navigate: https://stackblitz.com/edit/qwik-starter-75rr5q
2. Click `toggle`:
3. Observe that only one set of bindings changes and the other is ignored.

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
The alternative is to remove fine grained updates... what is localize$ is a bad idea after all?
