### ISSUE TITLE
[🐞] Initial value of range input is incorrect when step is specified after value in the component

### ISSUE THREAD

**Issue by cmbartschat** [BuilderIO/qwik#4455]
### Which component is affected?

Qwik Runtime

### Describe the bug

Looks like there's a bit of an edge case where the prop order between `value` and `step` on an `<input type='range'>` can cause differing behavior.

In this case, the slider is reset to an incorrect value unexpectedly.

### Reproduction

[Playground](https://qwik.builder.io/playground/#version=1.1.5&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU2lnbmFsJTJDJTIwJTI0JTIwJTdEJTIwZnJvbSUyMCU1QyUyMiU0MGJ1aWxkZXIuaW8lMkZxd2lrJTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnN0JTIwc2hvd2luZ0lucHV0cyUyMCUzRCUyMHVzZVNpZ25hbCh0cnVlKSUzQiU1Q24lNUNuJTIwJTIwY29uc3QlMjBoYW5kbGVUb2dnbGUlMjAlM0QlMjAlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwc2hvd2luZ0lucHV0cy52YWx1ZSUyMCUzRCUyMGZhbHNlJTNCJTVDbiUyMCUyMCUyMCUyMHNldFRpbWVvdXQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwc2hvd2luZ0lucHV0cy52YWx1ZSUyMCUzRCUyMHRydWUlM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTJDJTIwMjAwKSUzQiU1Q24lMjAlMjAlN0QpJTNCJTVDbiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2RpdiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NidXR0b24lMjB0eXBlJTNEJTVDJTIyYnV0dG9uJTVDJTIyJTIwb25DbGljayUyNCUzRCU3QmhhbmRsZVRvZ2dsZSU3RCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBUb2dnbGUlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYnV0dG9uJTNFJTVDbiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0JzaG93aW5nSW5wdXRzLnZhbHVlJTIwJTI2JTI2JTIwKCU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0MlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDaW5wdXQlMjB0eXBlJTNEJTVDJTIycmFuZ2UlNUMlMjIlMjB2YWx1ZSUzRCU1QyUyMjAuNSU1QyUyMiUyMHN0ZXAlM0QlNUMlMjIwLjElNUMlMjIlMjBtaW4lM0QlNUMlMjIwJTVDJTIyJTIwbWF4JTNEJTVDJTIyMSU1QyUyMiUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NpbnB1dCUyMHR5cGUlM0QlNUMlMjJyYW5nZSU1QyUyMiUyMHN0ZXAlM0QlNUMlMjIwLjElNUMlMjIlMjB2YWx1ZSUzRCU1QyUyMjAuNSU1QyUyMiUyMG1pbiUzRCU1QyUyMjAlNUMlMjIlMjBtYXglM0QlNUMlMjIxJTVDJTIyJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjApJTdEJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmRpdiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjB0eXBlJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBBcHAlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQyUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

### Steps to reproduce

1. Open the playground
2. See that both sliders are in the halfway position.
3. Click "Toggle"
4. The sliders will disappear and reappear
5. One slider has been incorrectly "rounded" to the end of the input, the other is fine. The only difference between the two is the order `step` is declared relative to `value`.

### System Info

```shell
N/A
```

**Comment by manucorporat** [comment]
I recall this very same issue when working at stencil and iconic! Wonder how other framework solve this issue 🤔

**Comment by cmbartschat** [comment]
@manucorporat  This is what preact does - https://github.com/preactjs/preact/pull/1435

Depending on prop order might not work for props spreading...
