### ISSUE TITLE
[🐞] Redirecting in `onRequest` from a route that doesn't export a default breaks redirect and adds `q-data.json` to the path

### ISSUE THREAD

**Issue by riencoertjens** [BuilderIO/qwik#4502]
### Which component is affected?

Qwik City (routing)

### Describe the bug

redirecting in `onRequest` from a route that does not export a default component adds `q-data.json` to the path and breaks the redirect

### Reproduction

https://github.com/riencoertjens/qwik-redirect-issue-reproduction

### Steps to reproduce

- `npm install`
- `npm run start` or `npm run preview`
- on homepage, click on "Go to `/broken` link using either the Link or the button

**expectation:**
redirects to `/broken/route`

what **happens:**
redirects to `/broken/q-data.json/route`

- manually navigating to `/broken` redirects as expected
- when there's a default export in the parent route it works as well

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 130.25 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4 
    @builder.io/qwik-city: ^1.1.4 => 1.1.4 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.5 => 4.3.5
```

**Comment by barbalex** [comment]
I tested with v1.2.4 and it works now 🎆
