### ISSUE TITLE
[🐞] using menu.md and having a route named `menu` causes an error

### ISSUE THREAD

**Issue by ulic75** [BuilderIO/qwik#4504]
### Which component is affected?

Qwik Runtime

### Describe the bug

If I'm using a menu.md file for creating a menu using useContext and I also have a route named `menu` then I receive the following error when trying to run with `preview` and during a build.

```
Identifier 'Menu' has already been declared (Note that you need plugins to import files that are not JavaScript)
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-kd1pse

### Steps to reproduce

npm run preview

### System Info

```shell
Stackblitz
```

**Comment by hbendev** [comment]
A possible quick solution would be appending "Markdown" to the generated import statements. I'd be happy to make the changes with tests if this seems a reasonable solution.

```javascript
import * as Menu from "/home/hbendev/Projects/qwik-starter-kd1pse/src/routes/menu/index";
import * as MenuMarkdown from "/home/hbendev/Projects/qwik-starter-kd1pse/src/routes/menu.md";
```

**Comment by ulic75** [comment]
My workaround for now was move the "routes/menu/" route into a grouped layout, "routes/(dummy}/menu/".

**Comment by hbendev** [comment]
Well, that works, but sounds very hacky, and not developer friendly.

On the other hand, my proposed solution isn't perfect either. No matter what we append to variable name, this conflict can arise (even in nested routes):

```javascript
import * as MenuMarkdown from "/home/hbendev/Projects/qwik-starter-kd1pse/src/routes/menu.md";
import * as DemoFlowerMenuMarkdown from "/home/hbendev/Projects/qwik-starter-kd1pse/src/routes/demo/flower/menu.md";
 ```
 
 We'd have to make them all unique. But for this, [`createFileId`](https://github.com/BuilderIO/qwik/blob/623150177c1901a7d6236080d243e08885b94900/packages/qwik-city/utils/fs.ts#L90) should be modified. My idea is to either add
 1.  a required 'type' parameter, that can either be `'menu'`, `'route'`, `'plugins'` etc.
 2.  an optional parameter that would be pushed to the current id.
