### ISSUE TITLE
[📖] server$ doc page is 404ing

### ISSUE THREAD

**Issue by Coly010** [BuilderIO/qwik#4505]
### Suggestion

The following page returns a 404.

it is the `server$` page and it is definitely listed as a menu item under `Qwik City` heading.

https://qwik.builder.io/docs/server$/

**Comment by barbalex** [comment]
Yeah. I am trying to decide whether to use server$ or routeLoader$ to fetch data. This is very hard when the server$ docs are missing.

To not end negatively: I absolutely LOVE qwik. You definitely pulled me off of react after ten years!

**Comment by manucorporat** [comment]
Should be fixed now! sorry for the inconvenience
