### ISSUE TITLE
SSG include/exclude pages 

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#4523]
### Is your feature request related to a problem?

I'm building a blog with a search page to find a post. When I change searchParams in the search page the results are the same if I use an anchor (not a Link). I think this is because SSG doesn't takes into account searchParams.

### Describe the solution you'd like

1. Support searchParams for prerendering (Incase there is a limited amount of options).
2. Being able to exclude pages from SSG to use SSR instead.

Both could be done in the `onStaticGenerate` return function.

### Describe alternatives you've considered

I used SPA navigation to the search page.
Another solution is to use `useVisibleTask` to perform the query.
But both solutions are client side, so we cannot cache the result of the query on the server.

**Comment by gioboa** [comment]
You can configure this behaviour with [include and exclude](https://github.com/BuilderIO/qwik/blob/7920da000be0c2efa921b3efcb510444fbccea40/packages/qwik-city/adapters/shared/vite/index.ts#L261) props in your Qwik SSG adapter.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
