### ISSUE TITLE
[🐞] Creating a layout.tsx without default component$ creates cryptic error

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#4531]
### Which component is affected?

Qwik Runtime

### Describe the bug

1. I created `layout.tsx` so that I can add a middleware function. 
2. I did not create a `export default component$()` because I did not need it.
3. When I created a route I got this cryptic error:

```
The <Type> of the JSX element must be either a string or a function. Instead, it's a "undefined": undefined.
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-vvenru

### System Info

```shell
na
```

**Comment by devcaeg** [comment]
@manucorporat @mhevery 

After updating QwikJS to its latest version (v.1.3.5), this error is appearing on my screen, the weird thing is that sometimes it appears, sometimes not. 

It should be noted that I don't have any "layout.tsx" in my project that doesn't have an "export default component$".
