### ISSUE TITLE
[🐞] ERROR in ./node_modules/@builder.io/qwik-worker/lib/index.qwik.mjs 12:55-64 export 'default' (imported as 'workerUrl') was not found in './worker.js?worker&url' (module has no exports)

### ISSUE THREAD

**Issue by punithnpg** [BuilderIO/qwik#4549]
### Which component is affected?

Qwik Runtime

### Describe the bug

Quick Worker 

ERROR in ./node_modules/@builder.io/qwik-worker/lib/index.qwik.mjs 12:55-64
export 'default' (imported as 'workerUrl') was not found in './worker.js?worker&url' (module has no exports) 

ERROR in ./node_modules/@builder.io/qwik/core.mjs 151:49-56
Module not found: Error: Can't resolve 'process/browser' in '/Users/punithgowda/Documents/Metamap/dashboard/node_modules/@builder.io/qwik'

### Reproduction

https://stackblitz.com/edit/qwik-starter-yccqus?file=src%2Fcomponents%2Fstarter%2Fcounter%2Fcounter.tsx

### Steps to reproduce

import { worker$ } from '@builder.io/qwik-worker'; 

and use it in a JSX component function

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 67.47 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 114.1.52.126
    Chrome: 114.0.5735.133
    Safari: 16.2
  npmPackages:
    @builder.io/qwik-worker: ^0.0.1 => 0.0.1
```

**Comment by hamatoyogi** [comment]
I've looked at the reproduction, seems like it's trying to export a worker as a component.

The idea of worker$ is to move computation or function execution to a web worker, not the rendering...
