### ISSUE TITLE
[🐞] use-method-usage warn for use* in condition

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#4552]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I want to create create an id for my element if it's not provided in props : 
```jsx
export const Nav = component$((props: QwikIntrinsicElements['nav']) => {
  const id = props.id ?? useId(); // Calling use* methods in non-root component.
})
```
This throw a eslint error, while it's working correctly at runtime

### Reproduction

https://stackblitz.com/edit/qwik-starter-8hpxvm?file=src%2Froot.tsx

### Steps to reproduce

```
npm install
npm run build
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22623
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 20.21 GB / 31.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1095.0), Chromium (114.0.1823.51)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: 1.1.5 => 1.1.5
    @builder.io/qwik-city: ^1.1.5 => 1.1.5
    undici: 5.22.1 => 5.22.1
    vite: 4.3.9 => 4.3.9
```

**Comment by GrandSchtroumpf** [comment]
@jordanw66 thank for the feedback.
What do you mean by "it either is or isn't" ?

This code is currently working at runtime. The id is generated and bound with the nav element.
```jsx
export const Nav = component$((props: QwikIntrinsicElements['nav']) => {
  const id = props.id ?? useId();
  return <nav id={id}>
    <Slot/>
  </nav>
});
return default component$(() => {
 return <>
    <Nav /> {/* id is generated */}
    <Nav id="test" /> {/* id is test*/}
 </>
})
``` 
If it's working at runtime I don't think it should create an eslint error

**Comment by manucorporat** [comment]
@jordanw66 is correct and the lint is correct, the fact its working correctly does not mean it will, or under some condition it will fail.

use methods can not be executed conditionally, useId() must be always executed, it's workign in your example because most likely you are not toggling props.id from existing to not existing.

If that was the cause, it will likely crash in a nasty way.

**Comment by manucorporat** [comment]
it's a simple rule, use methods can not be called conditionally:

```tsx
export const Nav = component$((props: QwikIntrinsicElements['nav']) => {
  const newId = useId();
  const id = props.id ?? newId;
})
```

**Comment by GrandSchtroumpf** [comment]
Ok thanks I understand better the problem
