### ISSUE TITLE
[✨] `image-warning` elements should float with position fixed

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#4559]
### Is your feature request related to a problem?

The image-warning elements can break layouts that use custom scroll areas or when modal windows open. The image-warning elements push the page size around and need to be deleted from the dom during development.

### Describe the solution you'd like

A nice improvement would be to position them fixed above all content so they dont interfere with the page layout. We'd need to the track user scrolls and page resizes to reposition them within the window.

### Describe alternatives you've considered

An option to disable the image-warnings all together if they break your layouts, but then you dont get the nice feature.

**Comment by manucorporat** [comment]
Not sure which solution u are suggesting, could u point it the CSS fix?

**Comment by manucorporat** [comment]
Should be fixed in main!

**Comment by DustinJSilk** [comment]
Amazing dude! Ill give this a look now!
