### ISSUE TITLE
[✨] useServerTask$

### ISSUE THREAD

**Issue by GrandSchtroumpf** [BuilderIO/qwik#4572]
### Is your feature request related to a problem?

I'm building a Firebase integration for qwik and I need to differentiate server query from client query because
1. There are different lib for the server (`firebase-admin`) or the client (`firebase`).
2. I do an http query on the server and I've got a global subscription on the client.

I cannot use `routeLoader$` as it would not use global subscription on the client.
I would rather not use `useTask$` because I'll load the server library `firebase-admin` in the client on SPA navigation.

### Describe the solution you'd like

Ideally I would like to do something like that (I simplified firebase related code for readability): 
```jsx
const path = 'users';
const state = useSignal();
useServerTask$(async () => {
  state.value = await admin.firestore.get(path);
});
useVisibleTask$(() => {
  const unsubscribe = firebase.firestore.subscribe(path, (data) => {
    state.value = data;
  })
  return unsubscribe;
})
```

### Describe alternatives you've considered

Currently I do that : 
```jsx
useTasks$(async () => {
  if (!isServer) return;
  const admin = await getFirebaseAdmin(); // QRL function to not load the 
  // do the query
})
useVisibleTask$(() => {
  const firebase = getFirebase();
  // do the subscription if not ongoing subscription on this query
})
```
For SPA navigation `useTask$` will be triggered alongside the `useVisibleTask$` which means a extra network call we can avoid when the browser is already busy (navigation). And it reduce DevX by having to wrap the library into another file (QRL).

**Comment by manucorporat** [comment]
`useServerTask$()` will not happen, we actually tried this API, and confused everyone. People expected it to execute on change etc, and then expect this client/server version of all APIs, which affects the understanding of how the lifecycle works, and that it will happen once. 

if you do:
useTasks$(async () => {
  if (isServer) {
  const admin = await getFirebaseAdmin(); // QRL function to not load the 
  // do the query
  }
})
```
the optimzier will remove the import to firebase admin!

**Comment by GrandSchtroumpf** [comment]
Ok good to know thanks.
Will the optimizer remove it from the bundle if `getFirebaseAdmin` is part **not** a QRL ?
If I use the lib directly in the `useTask$` after the if statement I see the lib being download in the browser console, that's why I ended up wraping the whole lib in a QRL, which seemed a extra step that could have been avoid somehow.
