### ISSUE TITLE
[🐞] Duplicate loader id "g8XUlGCLMBQ" detected. Please ensure that all loader ids are unique.

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#4603]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to integrate Auth.js into my Qwik app.

This is the message I get now:

> Duplicate loader id "g8XUlGCLMBQ" detected. Please ensure that all loader ids are unique.

And this is the stack trace:

```
    at /project/node_modules/@builder.io/qwik-city/vite/index.cjs:23956:21
    at Array.map (<anonymous>)
    at /project/node_modules/@builder.io/qwik-city/vite/index.cjs:23952:22
    at Object.next (/project/node_modules/@builder.io/qwik-city/vite/index.cjs:24295:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runNext (/project/node_modules/@builder.io/qwik-city/vite/index.cjs:24538:5)
    at async /project/node_modules/@builder.io/qwik-city/vite/index.cjs:24967:26
```

What do you think I should do? Nowhere has a clear message on what went wrong and where I have done something wrong in *my code*.

Google search presents nothing related to Qwik or Vite.

### Reproduction

The message is so obscure, I can't even create a reproduction example

### Steps to reproduce

I don't know. The message is not clear.

### System Info

```shell
System:
    OS: Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 11.35 GB / 15.50 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.7.2 - /usr/local/bin/npm
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0 
    @builder.io/qwik: ^1.1.5 => 1.1.5 
    @builder.io/qwik-auth: ~0.1.0 => 0.1.0 
    @builder.io/qwik-city: ^1.1.5 => 1.1.5 
    undici: 5.22.1 => 5.22.1 
    vite: ^4.3.9 => 4.3.9
```

### Additional Information

Please make the message clearer.

**Comment by manucorporat** [comment]
I saw the other issue with Auth.js you reported, thanks for taking a look at all this! 
Happy to help, but not sure how this is happening without a repo case, i imagine you might be exporting the same loader in several places?
If i can see the source code i can probably point that out and also, probably improve the error message!

**Comment by Nefcanto** [comment]
@manucorporat Also please note that this code is gathered using our site builder, built upon Qwik and docker, and other technologies. So if you see stupid things like `tsconfig.json` that extends a sibling file called `TsConfigBase.json` don't think of us as stupid :D. Using an infra, we reuse that `TsConfigBase.json` across many many projects.

**Comment by diecodev** [comment]
@Nefcanto I think the problem may be in some of the errors listed below that your code presents:

- routeLoader can only be declared inside src/routes folder.
- All routeLoder must be exported so that it can be used in every component needed.
- All routeLoader must start with prefix ```use```

It may be one of those errors or maybe something else, though. I'll leave the [documentation](https://qwik.builder.io/docs/route-loader/) for you to take a look and maybe you can find some other error there (since you are using an infrastructure and your repo is quite ambiguous)

**Comment by manucorporat** [comment]
I think somewhere in the code base the same loader is reexported several times, trying to improve the error message, but not sure how i can auto detect it.
