### ISSUE TITLE
[🐞] useResource inside a custom hook does not track custom hook's parameter value

### ISSUE THREAD

**Issue by ptzar80** [BuilderIO/qwik#4621]
### Which component is affected?

Qwik Runtime

### Describe the bug

When using useResource$ inside a custom hook, one would expect that the track method of useResource$ would be able to track the value of the custom hook's param (when type of the value is a primitive), but that does not happen. However, when the type of the param is a Signal holding a primitive, useResource$ is able to track the Signal's value. Is that intended to be so? It seems reasonable to expect that custom hook's param is "reactive" and triggers changes when its value changes.

### Reproduction

https://stackblitz.com/edit/custom-hook-track?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

In the main route we have a Signal that holds a "switcher" value that can be toggled. This value is being passed to two custom hooks which both contain a useResource$ which mimics an API call, and they both return a ResourceReturn value. The first custom hook takes the Signal's value as a param and the second one take the whole Signal as a param. There are 2 Resources in the route, one for each hook. By clicking the toggle button, one can observe how only the Resource holding the value returned from the hook which is taking the Signal as a param follows the local change, while the other one always stays the same.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4 
    @builder.io/qwik-city: ^1.1.4 => 1.1.4 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.5 => 4.3.5
```

### Additional Information

The System info output comes from StackBlitz, but the same issue happens in the local app with System Info:

System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 88.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 108.0.2
    Safari: 16.5.1
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4 
    @builder.io/qwik-city: ^1.1.4 => 1.1.5 
    undici: 5.22.0 => 5.22.0 
    vite: 4.3.3 => 4.3.3

**Comment by ahnpnl** [comment]
I think this is expected behavior. It’s related to `signal`, `reactivity` and `Proxy` concepts. We can only track the thing which is reactive. The same applies to track in other hooks like `useTask$` or `useVisibleTask$`. 

There is one except to this is, if you track component props, it will work because component props are always reactive.

**Comment by shairez** [comment]
Thanks @ahnpnl 

Yes this is the expected behavior - once you "unwrap" a signal and pass only it's `.value`, you are dealing with a primitive and not a reactive value.

So the "reactivity" or "subscription" of the track happens at the exact time you call `.value`
that's why passing a signal or a store is necessary instead of primitive values.

Thanks for the report and care!

**Comment by ptzar80** [comment]
@ahnpnl @shairez thank you for the explanation! I guess I got a bit confused because component's props are always reactive, but custom hook's are not and I believed they are. All clear now! ;)

**Comment by tzdesign** [comment]
@shairez should we add something about this to the docs?

Maybe in the Task below [Use Hook Rules](https://qwik.builder.io/docs/components/tasks/#use-hook-rules).

Something like ***Custom Hook Parameters***
