### ISSUE TITLE
[🐞] CLI - Some integrations do not work

### ISSUE THREAD

**Issue by nsdonato** [BuilderIO/qwik#4639]
### Which component is affected?

Starters / CLI

### Describe the bug

Some integrations do not work on new version 1.2.0

Tailwind
Postcss

Example tailwind:
![image](https://github.com/BuilderIO/qwik/assets/7875216/57fae1c3-a524-4bd7-b538-e44c5706bc16)
![image](https://github.com/BuilderIO/qwik/assets/7875216/16131df0-87d0-4442-b619-74aeeabd931e)

### Reproduction

https://qwikstarter-brkx--5173--a19575a2.local-credentialless.webcontainer.io

### Steps to reproduce

Run `npm run qwik add tailwind` or select after run `npm run qwik add tailwind`

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.23 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.6.2 - ~/Library/pnpm/pnpm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5.1
  npmPackages:
    @builder.io/qwik: ^1.2.0 => 1.2.0 
    @builder.io/qwik-city: ^1.2.0 => 1.2.0 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.9 => 4.3.9
```

### Additional Information

Stackblitz has version 1.1.4, although I don't know if it is related to the CLI, in fact it works to add the integration there. 🚨

**Comment by toddmorey** [comment]
Experiencing the same bug in local development (tailwind).

**Comment by manucorporat** [comment]
Working on a fix!
