### ISSUE TITLE
[🐞] Problem with version 1.2.2 witch globalAction not working 

### ISSUE THREAD

**Issue by gabriiels** [BuilderIO/qwik#4650]
### Which component is affected?

Qwik City (routing)

### Describe the bug

In version 1.1.5 it works fine

I just changed to version 1.2.2 and it doesn't work

It's basically a login

It doesn't give me any error, it just doesn't work globalAction

I'm investigating the error better but so far with the preview I get this error:

![error-qwik-version-1 2 2](https://github.com/BuilderIO/qwik/assets/49616724/29946a1d-9961-441b-8d49-d1dd78c2f22c)

### System Info

```shell
Linux
```

**Comment by thejackshelton** [comment]
![image](https://github.com/BuilderIO/qwik/assets/104264123/5a4b99da-a714-445c-987f-96a4ad8b5712)

According to the docs here, globalAction should work outside of /routes, but routeAction should only be declared inside the /routes directory

**Comment by thejackshelton** [comment]
@gabriiels I think this is an issue yeah.

**Comment by manucorporat** [comment]
Will look with higest priority today

**Comment by manucorporat** [comment]
cc @jordanw66

**Comment by manucorporat** [comment]
I can't reproduce the issue! i tested exactly the same code and it works for me

**Comment by manucorporat** [comment]
can you provide a repo? the source provided is not enough to reproduce
