### ISSUE TITLE
[🐞] Navigation broke on v1.2+

### ISSUE THREAD

**Issue by origranot** [BuilderIO/qwik#4654]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Hey, seems like couple things broke when I updated my Qwik version.
My application did work smoothly before the update.

https://www.loom.com/share/1389e62341824e22885864701d04d5db

- I do use main layout and dashboard layout

REPO: (https://github.com/origranot/reduced.to)

### Other information
Seems like @jordanw66 reproduce it!
https://github.com/BuilderIO/qwik/issues/4658

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 17.53 GB / 31.95 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.3.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.58)
    Internet Explorer: 11.0.19041.1566
```

### Additional Information

Tried also on Mac and windows.

Issue occur on dev and build.

**Comment by barel-mishal** [comment]
Hi, I successfully manage to reproduce the issue. 

If you try open the app and click on "Using the Link" the link component will not redirect the page but the Using the a tag its working:
![image](https://github.com/BuilderIO/qwik/assets/56759851/9b225c2b-6dbe-4b1a-a048-c4675d0b1cf5)

**Comment by barel-mishal** [comment]
> Amazing will try to fix and release today!

Hi I just did a update please make sure you pull the latest changes. I cleaned a bit the project.

**Comment by origranot** [comment]
> > > Amazing will try to fix and release today!
> > 
> > 
> > Hi I just did a update please make sure you pull the latest changes. I cleaned a bit the project.
> 
> I tried that reproduction in its current state and the `Link` works for me, are you sure it's broken for you?

I will appreciate if you can install my project and test it.
If you need anything I will be happy to assist.
