### ISSUE TITLE
Failed to fetch dynamically imported module / Not allowed to load local resource [🐞] 

### ISSUE THREAD

**Issue by IRediTOTO** [BuilderIO/qwik#4665]
### Which component is affected?

Qwik Runtime

### Describe the bug

Hi, I just upgrade Qwik to newest version, but it work not as old version. I don't  sure what did you changed, why it so error :(  As I understand 1.0 mean ready for production, I am trying to learn Qwik to work but why it is so buggy 😢  
I get this error 
`TypeError: Failed to fetch dynamically imported module: file:///D:/Job/src/qwikcityprovider_component_usetask_02wmimzeabk.js`
`Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: file:///D:/Job/src/link_component_handleclick_event_i1cv0pyjnr0.js`

This error happened with just for simple thing like `Link` component,  I didn't write something complex in component, just use `useSignal` `useTask$`. 
I must restart VIte to make it work again. I found [error](https://stackoverflow.com/questions/69300341/typeerror-failed-to-fetch-dynamically-imported-module-on-vue-vite-vanilla-set) same as like that on google, related to Vitejs
![image](https://github.com/BuilderIO/qwik/assets/15695252/55e14468-0348-4cd7-91f9-ddc9a7604eac)

https://github.com/BuilderIO/qwik/assets/15695252/8f08e9c1-b20c-4be4-bc76-0a92337480a5

### Reproduction

https://github.com/BuilderIO/qwik/

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 15.53 GB / 31.77 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.58)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0 
    @builder.io/qwik: ^1.2.3 => 1.2.3 
    @builder.io/qwik-auth: ~0.1.0 => 0.1.0 
    @builder.io/qwik-city: ^1.2.3 => 1.2.3 
    @builder.io/qwik-react: ^0.5.0 => 0.5.0 
    undici: 5.22.1 => 5.22.1
    vite: 4.3.9 => 4.3.9
```

**Comment by origranot** [comment]
This issue also happens to me after the update to 1.2.3.

**Comment by manucorporat** [comment]
Without a simple reproduction code i can't fix this issue :(

**Comment by gilbertoalbino** [comment]
I am having the same issue while trying to learn from Qwikschool.com!
But what got me quite disturbed is that if I make any mistake while coding, and save, the whole application stops working.
To reproduce is very simple!
1) Create an empty app `npm create qwik@latest`
2) `npm start`
2) Create a new page1/index.tsx
```
import { component$, useSignal } from "@builder.io/qwik"; 
export default component$(() => {
  const showMessageSignal = useSignal(false);
  return (
    <>  
      <button onClick$={()=>{showMessageSignal.value=true;}}>Show message!</button>  
      { showMessageSignal.value? 'Hello Error' : null }
    </>
  );
}); 
```
3) Make any mistake, and save; like:
`{ showMessageSignal? 'Hello Error' : null }`

4) Correct the mistake:
`{ showMessageSignal.value? 'Hello Error' : null }`

And that's it, the only way to work is to close the window and run `npm start` again

The same behaviour happens you have more link pointing to other pages, and you change anything after `npm start`.

My package.json file has these devDependencies:
```
  "devDependencies": {
    "@builder.io/qwik": "^1.2.3",
    "@builder.io/qwik-city": "^1.2.3",
    "@types/eslint": "8.40.2",
    "@types/node": "^20.3.1",
    "@typescript-eslint/eslint-plugin": "5.60.0",
    "@typescript-eslint/parser": "5.60.0",
    "eslint": "8.43.0",
    "eslint-plugin-qwik": "^1.2.3",
    "prettier": "2.8.8",
    "typescript": "5.1.3",
    "undici": "5.22.1",
    "vite": "4.3.9",
    "vite-tsconfig-paths": "4.2.0"
  }
```

**Comment by barbalex** [comment]
I reverted to v1.1.5 to not have this issue

**Comment by barbalex** [comment]
I am still getting this error with v1.2.3, seems that https://github.com/BuilderIO/qwik/pull/4686 did not solve this (too)

**Comment by gilbertoalbino** [comment]
A new release haven't been published yet to the time of this comment. Maybe in v1.2.4 it will be patched.

As said previously, it only affects Windows, so I manually changed the the installed files in `node_modules`, and it did work. 

But of course, this is just a remedy, not a solution, and obviously not a good practice!

If you temporarily want to learn Qwik and v1.2.4 is not released, you can try it like so.

Search  `node_modules\@builder.io\qwik\optimizer.cjs` file search for:

`hook && (manifest.mapping[hook.name]` 
 
Manually change from:

`hook && (manifest.mapping[hook.name] = url2);`

To:

` hook && (manifest.mapping[hook.name] =  relativeURL(url2, opts.rootDir));`

**Again: This is not good practice! Don't do this as a final solution**

Just to mention that this error just happens in Development, if you build to production, everything will work correctly!

> I am still getting this error with v1.2.3, seems that #4686 did not solve this (too).
> 
> All `Link`s are erroring and not linking.

**Comment by barbalex** [comment]
@gilbertoalbino 
Thanks!

You could also use [patch-package](https://github.com/ds300/patch-package) to patch it a bit more sustainably.

**Comment by gilbertoalbino** [comment]
@barbalex I add new content to my previous comment!
Thanks for the tip!

**Comment by barbalex** [comment]
Just tested v1.2.4: Link's are working again. Thanks guys!
