### ISSUE TITLE
[🐞] 404 on docs tutorial examples

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/qwik#4667]
### Which component is affected?

Qwik Playground

### Describe the bug

The app view on any of the tutorial examples with the route /tutorial provide a 404 on the app preview / output

**Ex:**
404 - https://qwik.builder.io/repl/16ihu4lkrkq/

### Reproduction

https://qwik.builder.io/tutorial/welcome/overview/

### Steps to reproduce

Navigate to any of the tutorial examples

Wait for the app view to load (bottom right if on desktop)

### System Info

```shell
N/A
```

**Comment by whooof** [comment]
Any news on that? is it working for someone?

**Comment by gioboa** [comment]
Not yet, would you like to investigate on it?

**Comment by ryuujo1573** [comment]
@gioboa Hi

I came to [this example](https://qwik.builder.io/examples/introduction/hello-world/) and the expected web output did not work.

I've check all of examples/tutorials, and these REPL resulting workloads always return 404.
Is anything going wrong?

[qwik.builder.io.zip](https://github.com/BuilderIO/qwik/files/13198440/qwik.builder.io.zip)
Here's the `.har` file.

**Comment by gioboa** [comment]
We need to figure out why we have 404, I will report this issue to the core team.
