### ISSUE TITLE
[🐞] Error when using <Form /> component

### ISSUE THREAD

**Issue by gustavocadev** [BuilderIO/qwik#4679]
### Which component is affected?

Qwik City (routing)

### Describe the bug

Error when using the Form component without an Action
![image](https://github.com/BuilderIO/qwik/assets/84424661/de090f2e-dde4-48f4-ae17-86716b7936e1)

![image](https://github.com/BuilderIO/qwik/assets/84424661/f378d69d-aa65-49fe-9249-ee846a2e8cbf)

OS: Windows 11 & macOS 12.6.7
Qwik version: 1.2.3
Qwik City version: 1.2.3

### Reproduction

https://github.com/gustavocadev/poke-qwik

### Steps to reproduce

Run `pnpm install` followed by `pnpm dev` and then we go to `http://localhost:5173/pokemons/list-ssr/?offset=20` we need to click the button `Siguientes` and reload the page and occurs the error

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 4.98 GB / 12.92 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.5 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22621.1928.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: 1.2.3 => 1.2.3
    @builder.io/qwik-city: 1.2.3 => 1.2.3
    undici: 5.22.1 => 5.22.1
    vite: 4.3.9 => 4.3.9
```

**Comment by manucorporat** [comment]
I can reproduce! i will fix asap!

**Comment by gustavocadev** [comment]
> I can reproduce! i will fix asap!

Thanks! 😎
