### ISSUE TITLE
[✨] splitProps, mergeProps to keep reactivity when working with props

### ISSUE THREAD

**Issue by TeddyLourson** [BuilderIO/qwik#4681]
### Is your feature request related to a problem?

*Problem 1.*
Often, you need some props to be passed to a children component (but not all of the props). The first thing that come in mind (at least from React) is to do this `const { value1, …rest } = props;` and then spreading the rest props on the children component. However by doing so, we’re losing reactivity in the case we had props which could be a reactive value (like an object from a useStore being passed as props).

*Problem 2.*
Sometimes you need to add some default values to props. The first thing that come in mind (at least from React) is to do this `const { value1 = "default", …rest } = props;` and then if the value1 has not been provided in the props, it will be using the default value instead. However, by doing so, we’re losing reactivity in the case we had props which could be a reactive value (like an object from a useStore being passed as props).

### Describe the solution you'd like

1. Inspired from SolidJs. (See : https://www.solidjs.com/tutorial/props_split)
This is where a splitProps method could be useful to allow for splitting parts of the props in groups based on a set of provided keys in this way : `const [local, rest] = splitProps(props, ["greeting", "name"]);`
This method should allow for splitting the props in groups that would still be reactive to changes made in the parent component that shared the props and for children components that will receive the props so that any update would affect the store.

2. Inspired from SolidJs. (See : https://www.solidjs.com/tutorial/props_defaults)
This is where a mergeProps method could be useful to allow for merging default props with reactive props in this way : `const merged = mergeProps({ greeting: "Hi", name: "John" }, props);`
This method should allow for merging the props with some defaults that would still be reactive to changes made in the parent component that shared the props and for children components that will receive the props so that any update would affect the store.

### Describe alternatives you've considered

I can’t think of any alternatives available in Qwik as of now and it seems like a pretty common use-case that most people coming from React would expect to work out of the box.

**Comment by manucorporat** [comment]
I agree this is a performance issue we should solve, but I trully believe it should not solved by adding a new API.
In this thread i explain our philosophy:
https://twitter.com/manucorporat/status/1624416525695287296

We already have some optimizer logic that optimizes this patterns, out goal is to keep extending the capabilities of the optimizer without adding a new API, and teach developers best practices.

In solid, it's different because it does not work at all without it, but in Qwik it does work, so there is less incentive for Qwik users to use the proposed APIs.

**Comment by TeddyLourson** [comment]
I think I just need to wrap my head around Qwik's Signals and Stores.
For some reason I thought that I could update a store when it is passed as props to a child component by mutating the props itself, which is something I never did in React but for some reason thought would be something "doable" with Qwik. Instead I should just pass a QRL to allow the child to update the store in the parent as I would usually do in React or simply pass a Signal in case of simple primitive values.

I agree that it would actually be less ideal to have new APIs for it instead of using what people are used to.
