### ISSUE TITLE
[🐞] Symbols are replaced with full file URLs in dev mode after useNavigate then modifying the page

### ISSUE THREAD

**Issue by jordanw66** [BuilderIO/qwik#4682]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

In dev mode, if you navigate using `useNavigate` or `Link` and then edit the page, Vite will automatically reload the page and then all symbols will be specified as full file URLs. (`/home/user/.../...` etc)

On Linux these will still load probably because the url structure is `/home/xxx/...`, I assume it's the same for OSX, so this issue will go unnoticed but on Windows url structure is `file://` and especially causes an error when the qwik loader attempts to load it.

This is the cause of this issue: https://github.com/BuilderIO/qwik/issues/4665

Also for more details, in the SPA shim for example I get the symbol/chunk for the SPA init script:

```tsx
const [symbol, chunk] = getPlatform().chunkForSymbol(init.getSymbol(), null)!;
```

The value of chunk here will also be a full file URL just like all the others on the page.

### Reproduction

https://github.com/jordanw66/issue-qwik-file-urls

### Steps to reproduce

1. Clone the reproduction.
2. Run it in dev mode.
3. Follow the instructions.
4. Notice the issue.

### System Info

```shell
N/A
```

**Comment by manucorporat** [comment]
Might be related to:
https://github.com/BuilderIO/qwik/issues/4665

**Comment by manucorporat** [comment]
You are amazing @jordanw66 saved me hours trying to figure out why windows fails! gonna fix + e2e test
