### ISSUE TITLE
[🐞] Issue with panda css integration.

### ISSUE THREAD

**Issue by ps6067966** [BuilderIO/qwik#4683]
### Which component is affected?

Qwik Runtime

### Describe the bug

npm run qwik add pandacss

As per documentation. I have used this to integrate it but nothing seems to be working. 

In Panda CSS, Qwik docs.
https://panda-css.com/docs/getting-started/qwik

Things are different, even code is different from qwik integration. 
I have tried both and both are not working. 

I love Qwik and Panda. I'm not able to use it. 
Please guide me.

### Reproduction

-

### Steps to reproduce

-

### System Info

```shell
-
```

**Comment by ps6067966** [comment]
In IDE no hints.

**Comment by ps6067966** [comment]
![image](https://github.com/BuilderIO/qwik/assets/26248740/5ae681ff-f7a5-4104-9ebc-9eab1ff5dba8)

**Comment by ps6067966** [comment]
This one also i have tried.

**Comment by ps6067966** [comment]
![image](https://github.com/BuilderIO/qwik/assets/26248740/8cf4ad23-1cdb-4d43-9f43-50b7f937f2a7)

**Comment by manucorporat** [comment]
We need a repo to reproduce the issue to help you!

**Comment by ps6067966** [comment]
Thank you. Issue is fixed. I restarted my vs code. after that it's working.
