### ISSUE TITLE
[🐞] Redirect does not trigger the useOnWindow/useOnDocument events

### ISSUE THREAD

**Issue by sreeisalso** [BuilderIO/qwik#4701]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm using useOnWindow to get the WebOTP for login, the useOnWindow event trggered when I visit the route directly, but same is not triggered when redirected to the url from an action.
I have created the minimal reproduction of the isssue in stackblits

### Reproduction

https://stackblitz.com/edit/qwik-starter-kdfhuf?file=src%2Froutes%2Findex.tsx

### System Info

```shell
System:
    OS: Linux 6.0 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 2.13 GB / 7.66 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.1 - /usr/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
  npmPackages:
    @builder.io/qwik: ^1.2.3 => 1.2.3 
    @builder.io/qwik-city: ^1.2.3 => 1.2.3 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.9 => 4.3.9
```

**Comment by sreeisalso** [comment]
@manucorporat can you tell me where to look in the source code to get understanding of how to solve this?

**Comment by manucorporat** [comment]
The `load` even is only dispatched once, not sure how would u expect it to fire after SPA navigation. I don't think there is anything we can do about this.

The `load` is working when u go to the page, because the browser dispatch the `load` event when the page loads. After that, it does not dispatch it anymore

**Comment by manucorporat** [comment]
What you need is `useVisibleTask$`

**Comment by sreeisalso** [comment]
Yeah true, sorry for the silly question.
