### ISSUE TITLE
[🐞] Internal server error: Missing Qwik City Env Data

### ISSUE THREAD

**Issue by qwibbert** [BuilderIO/qwik#4720]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I am trying to use a RouteLoader (see below) in my application to fetch a record from a Pocketbase instance. I keep however constantly getting the vague error `Missing Qwik City Env Data` when trying to use this loader. When removing the RouteLoader code the error swiftly disappears. I am sorry for the vague description but I don't know what is wrong either. Since the code needs my database instance to function I am not able to provide a reproduction URL.

Anyone who has an idea about what this error could mean?

![Schermafdruk van 2023-07-04 21-29-02](https://github.com/BuilderIO/qwik/assets/51886174/dd4c8c4f-07cd-49a1-9b8b-37c0f661465f)
![Schermafdruk van 2023-07-04 21-28-37](https://github.com/BuilderIO/qwik/assets/51886174/e18e0302-df32-46d7-aa64-b36509c6339a)
![Schermafdruk van 2023-07-04 21-29-37](https://github.com/BuilderIO/qwik/assets/51886174/5c8b2d62-e303-41ae-9af8-406ceed48036)
![Schermafdruk van 2023-07-04 21-33-31](https://github.com/BuilderIO/qwik/assets/51886174/da6cb8e5-447f-4709-9a64-bfd3d9cdc862)

### Reproduction

/

### Steps to reproduce

1. `npm install`
2. `npm run dev`

### System Info

```shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 1.87 GB / 7.67 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.1/bin/npm
  npmPackages:
    @builder.io/qwik: ^1.2.4 => 1.2.4 
    @builder.io/qwik-city: ^1.2.4 => 1.2.4 
    @builder.io/qwik-react: ^0.5.0 => 0.5.0 
    undici: 5.22.0 => 5.22.0 
    vite: ^4.3.9 => 4.3.9
```

**Comment by manucorporat** [comment]
Would love to help and possibly fix the issue, but i can't do much without a repo or code i can try myself and get the error. The reproduction steps are not enough :(
