### ISSUE TITLE
[🐞] ESLint message implies plugin can export routeLoader, but it cannot

### ISSUE THREAD

**Issue by literalpie** [BuilderIO/qwik#4722]
### Which component is affected?

Qwik Runtime

### Describe the bug

I got this eslint error:

> `routeLoader$()` can only be declared in `layout.tsx`, `index.tsx` and `plugin.tsx` inside the src/routes directory, instead it was declared in "[etc]/src/server-helpers/standup-series.ts".

So I tried putting the loader in `plugin.tsx` (at the root of my routes folder), but this gave me a different error:

> Internal server error: routeLoader$ "useStandupSeries_routeLoader_Pr80s4nu1Dg" was invoked in a route where the it was not declared. This is because the routeLoader$ was not exported in a 'layout.tsx' or 'index.tsx' file of the existing route.

It seems like one of these errors is wrong. I suspect the eslint error is, because the docs don't mention the possibility of putting actions and loaders in a `plugin.tsx`.

### Reproduction

https://stackblitz.com/edit/qwik-loader-eslint-p9stor?file=src%2Froutes%2Fplugin.tsx,src%2Froutes%2Findex.tsx

### Steps to reproduce

* Add `routeLoader$(...)` to a file that isn't in the routes folder. Notice the eslint error.
* Add a `routeLoader$()` to routes/plugin.ts, and attempt to use it. Notice the runtime error.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 70.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Chrome Canary: 117.0.5870.0
    Safari: 16.5.1
    Safari Technology Preview: 17.0
  npmPackages:
    @builder.io/qwik: ~1.2.34 => 1.2.3 
    @builder.io/qwik-city: ~1.2.34 => 1.2.3 
    undici: ^5.22.1 => 5.22.1 
    vite: ^4.3.9 => 4.3.9
```

**Comment by manucorporat** [comment]
The eslint is right! there is a bug that prevents the `.tsx` extension to work with plugins, as a workaround you can rename the file to `plugin.ts`.

Here's the upcoming fix:
https://github.com/BuilderIO/qwik/pull/4726
