### ISSUE TITLE
[🐞] Qwik crashes with v1.2.5 when using `--mode` build arguments

### ISSUE THREAD

**Issue by DustinJSilk** [BuilderIO/qwik#4732]
### Which component is affected?

Qwik City (routing)

### Describe the bug

After updating to v1.2.5, qwik crashes with the following error on production and preview builds when using a `--mode` vite build argument:

```
pnpm build --mode staging
```

```
TypeError: getPlatform is not iterable (cannot read property Symbol(Symbol.iterator))
```

Reverting back to v1.2.4 seems to have fixed it.
The error looks to be thrown in the SPA shim here: https://github.com/BuilderIO/qwik/blob/05a5fcf5273d74e5de45f97f0102aec7769fa3fe/packages/qwik-city/runtime/src/spa-shim.ts#L12C52-L12C52

@jordanw66 fyi looks like this crosses over the SPA work done last week.

I will update this issue with a repo soon

### Reproduction

TBC

### System Info

```shell
N/A
```

**Comment by DustinJSilk** [comment]
Thanks for the help @jordanw66 !!
Yes my project is quite old but i do import `qwikCityPlan` before `render` already.

I'll keep commenting out and removing things from my project until i find the root cause.

**Comment by DustinJSilk** [comment]
This is the error that throws before the getPlatforms error:

```
Cannot resolve symbol spa_init_DyVc0YBIqQU in {
  '02wMImzEAbk': [
    'QwikCityProvider_component_useTask_02wMImzEAbk',
    'qwikcityprovider_component_usetask_02wmimzeabk.js'
  ],
  GdhH0ytx8bI: [ 'root_component_GdhH0ytx8bI', 'root_component_gdhh0ytx8bi.js' ],
  TxCFOy819ag: [
    'QwikCityProvider_component_TxCFOy819ag',
    'qwikcityprovider_component_txcfoy819ag.js'
  ],
  e0ssiDXoeAM: [
    'RouterOutlet_component_e0ssiDXoeAM',
    'routeroutlet_component_e0ssidxoeam.js'
  ],
  mtwFi60Avug: [
    'overview_component_mtwFi60Avug',
    'overview_component_mtwfi60avug.js'
  ],
  RPDJAz33WLA: [
    'QwikCityProvider_component_useStyles_RPDJAz33WLA',
    'qwikcityprovider_component_usestyles_rpdjaz33wla.js'
  ],
  fX0bDjeJa0E: [
    'QwikCityProvider_component_goto_fX0bDjeJa0E',
    'qwikcityprovider_component_goto_fx0bdjeja0e.js'
  ]
}
```

**Comment by manucorporat** [comment]
I actually got this crash in 1.2.4 too, dont think it's a 1.2.5 regression

**Comment by manucorporat** [comment]
I will try to work on this tomorrow

**Comment by DustinJSilk** [comment]
Thanks @manucorporat !!

**Comment by DustinJSilk** [comment]
I see! Should this be controlled by the NODE_ENV environment variable, which can then be dropped into each .env file

**Comment by DustinJSilk** [comment]
Thanks @jordanw66 ! I'll investigate dev/production modes and see if there's an issue to raise, and I'll close this issue for now
