### ISSUE TITLE
[✨] useVisibleTask$ rootMargin option

### ISSUE THREAD

**Issue by hugotox** [BuilderIO/qwik#4737]
### Is your feature request related to a problem?

Hello!

I'm creating a lazy loaded section that needs to fetch data client side only, and I was able to achieve that by using `useVisibleTask$`.

Now, the rendering of this section might vary depending on the data, so to prevent CLS issues I would like to set the `rootMargin` option to the intersection observer used under the hood.

### Describe the solution you'd like

I'm imagining the `useVisibleTask$` taking an optional parameter for the observer:

```
  useVisibleTask$(() => {
     ...
    },
    { strategy: 'intersection-observer', observerOptions: { rootMargin: '200px' } }
  )
```

### Describe alternatives you've considered

I was poking around the code, and looks like all `useVisibleTask$` are sharing the intersection observer instance [here](https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/qwikloader.ts#L135-L145), so it's not clear to me how can we pass this option without creating an observer per each hook, which would be a performance disaster.

**Comment by gioboa** [comment]
Thanks for this proposal. I close it because we have #5031
