### ISSUE TITLE
Pass inline styles through PostCSS

### ISSUE THREAD

**Issue by Zizico2** [BuilderIO/qwik#475]
### Is your feature request related to a problem?

Inline styles don't get pre-processed by postcss

### Describe the solution you'd like

It would be nice if there was a way to have PostCSS pre-process inline styles.

### Describe alternatives you've considered

Using css modules works fine.

**Comment by manucorporat** [comment]
I dont think we can support this, it goes a against qwik design principles to inject this built-in into Qwik, inlined styles are just a string, qwik has no way to know it's a style.

We want to rely on Vite community of plugin to inject this kind of functionality, it needs to be done file based. However I can see someone could implement a custom plugin that tries to understand qwik code to inject this. But surely not a priority from the core team
