### ISSUE TITLE
[🐞]Qwik Sandbox 404 - https://qwik.builder.io/repl/3c2avyzefk/

### ISSUE THREAD

**Issue by c-m-a** [BuilderIO/qwik#4764]
### Which component is affected?

Qwik Runtime

### Describe the bug

When you go to Qwik Sandbox the App tab shows a 404 error using Firefox.

![image](https://github.com/BuilderIO/qwik/assets/1708609/f1de79ef-036c-4089-b865-bbf50c7ce003)

### Reproduction

https://qwik.builder.io/examples/introduction/hello-world/#version=1.2.6&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDcCUzRUhlbGxvJTIwUXdpayUzQyUyRnAlM0UlM0IlNUNuJTdEKSUzQiU1Q24lMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGZW50cnkuc2VydmVyLnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMHR5cGUlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEFwcCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D

### Steps to reproduce

Click on Qwik Sandbox

### System Info

```shell
Ubuntu, Firefox v115
```

**Comment by mhevery** [comment]
Adam wrote: my guess right now is it has something to do with https://github.com/BuilderIO/qwik/blob/9c0b3071afebbca5ff6fb7ffbf15bd96b1f50115/packages/qwik/src/optimizer/src/plugins/image-size-server.ts
[image-size-server.ts](https://github.com/BuilderIO/qwik/blob/9c0b3071afebbca5ff6fb7ffbf15bd96b1f50115/packages/qwik/src/optimizer/src/plugins/image-size-server.ts)
```
import bmp_1 from 'image-size/dist/types/bmp.js';
import cur_1 from 'image-size/dist/types/cur.js';
import dds_1 from 'image-size/dist/types/dds.js';
import gif_1 from 'image-size/dist/types/gif.js';
Show more
<https://github.com/[BuilderIO/qwik](https://github.com/BuilderIO/qwik)|BuilderIO/qwik>BuilderIO/qwik | Added by [GitHub](https://builder-internal.slack.com/services/B0225J1RSHY)
[2:35](https://builder-internal.slack.com/archives/D024X9SFYAJ/p1689111323310489)
some import isn't getting resolved correctly so then it tries to use rollup's file system, which it should never get to

**Comment by denghongcai** [comment]
same here.

more info from diagnostics tab

```shell
Error: Could not load /app_component_ncbm0trxwgc.js (imported by app.tsx): Cannot access the file system (via "fs.readFile") when using the browser build of Rollup. Make sure you supply a plugin with custom resolveId and load hooks to Rollup. at fe (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:12:23466) at Object.eval [as readFile] (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:12:353107) at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:12:359412) at async ul.work (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:12:353044)
```

**Comment by gioboa** [comment]
Great, thanks @maiieul
