### ISSUE TITLE
[🐞] Stoybook integration uses inconsistent task name

### ISSUE THREAD

**Issue by sarvex** [BuilderIO/qwik#4765]
### Which component is affected?

Starters / CLI

### Describe the bug

These are the contents of package.json 
```
    "build": "qwik build",
    "build-storybook": "storybook build",
    "build.client": "vite build",
    "build.preview": "vite build --ssr src/entry.preview.tsx",
    "build.server": "vite build -c adapters/vercel-edge/vite.config.ts",
    "build.types": "tsc --incremental --noEmit",
    "deploy": "vercel deploy",
    "dev": "vite --mode ssr",
    "dev.debug": "node --inspect-brk ./node_modules/vite/bin/vite.js --mode ssr --force",
    "fmt": "prettier --write .",
    "fmt.check": "prettier --check .",
    "lint": "eslint \"src/**/*.ts*\"",
    "preview": "qwik build preview && vite preview --open",
    "start": "vite --open --mode ssr",
    "storybook": "storybook dev -p 6006",
    "test.e2e": "playwright test",
    "test.unit": "vitest components",
    "test.unit.ui": "vitest --ui components",
    "qwik": "qwik"
```

All the integration `adapter` `vitest` `playwright` follow the standard naming convention - separation by `.`

However storybook uses the `-` as in kebab-case

### Reproduction

https://stackblitz.com/edit/qwik-starter-doesgq?file=package.json

### Steps to reproduce

```powershell
pnpm create qwik@latest
pnpm install
pnpm qwik add storybook
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.33 GB / 15.84 GB
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.6.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.7 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1928.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0
    @builder.io/qwik: 1.2.6 => 1.2.6
    @builder.io/qwik-city: 1.2.6 => 1.2.6
    undici: 5.22.1 => 5.22.1
    vite: 4.4.2 => 4.4.2
```

**Comment by DustinJSilk** [comment]
_I think_ this is because chromatic requires the `build-storybook` script by default to deploy. 
https://www.chromatic.com/docs/setup#run-chromatic

Otherwise you'd need to add an argument like `chromatic --build-script-name=build.storybook`
`build-storybook` could just be removed, and leave it to the user to add if they need it

**Comment by zanettin** [comment]
thx @sarvex for creating this issue and the PR 🙏 

i totally see your point! imo it's not the goal of the framework to switch cmds used by a particular 3rd party as @DustinJSilk stated. everybody working with storybook is used to this command and therefor we should not switch it by default. if smb feels that it should be named like u suggest, it's simple to switch, right? 😄 

thx again for raising this issue and creating the PR 🙏 i'll close both for now but feel free to re-open it when neede 👍
