### ISSUE TITLE
[🐞] useContent() always return undefined

### ISSUE THREAD

**Issue by tanftw** [BuilderIO/qwik#4787]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm using useContent() to return items from menu.md, previous version works fine but 1.2.x return undefined. I have created a stackblitz reproduction.

### Reproduction

https://stackblitz.com/edit/qwik-starter-zhy6u4?file=src%2Froutes%2Fmenu.md,src%2Froutes%2Flayout.tsx

### Steps to reproduce

- Create menu.md with items
- Use useContent() in layout.tsx
- It return undefined

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 11.80 GB / 15.59 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 19.3.0 - /mnt/wslg/runtime-dir/fnm_multishells/15056_1689232911462/bin/node
    Yarn: 1.22.19 - /mnt/wslg/runtime-dir/fnm_multishells/15056_1689232911462/bin/yarn
    npm: 9.6.4 - /mnt/wslg/runtime-dir/fnm_multishells/15056_1689232911462/bin/npm
    pnpm: 8.6.3 - /mnt/wslg/runtime-dir/fnm_multishells/15056_1689232911462/bin/pnpm
  npmPackages:
    @builder.io/qwik: 1.2.6 => 1.2.6 
    @builder.io/qwik-city: 1.2.6 => 1.2.6 
    undici: 5.22.0 => 5.22.0 
    vite: ^4.3.9 => 4.4.3
```

**Comment by maiieul** [comment]
@tanftw Your stackblitz's working fine, isn't it?

**Comment by tanftw** [comment]
@maiieul Thank you, I think it was fixed in the recent version so I will close this issue.
