### ISSUE TITLE
[📖] Link refresh attr issue on docs

### ISSUE THREAD

**Issue by VinceDZiree** [BuilderIO/qwik#4792]
### Suggestion

I'm getting started with qwik. I'm following the doc.

On this page: https://qwik.builder.io/docs/routing/#refreshing

The ```<Link reload>Refresh</Link>``` does not give a clickable link.

the rendered HTML:
```
<a on:click="/src/link_component_handleclick_event_i1cv0pyjnr0.js#Link_component_handleClick_event_i1Cv0pYJNR0[0 1 2 2]" q:key="AD_1" q:id="8"><!--qv q:s q:sref=7 q:key=-->Refresh<!--/qv--></a>
```

This is giving a text that is not clickable

**Comment by zanettin** [comment]
Good news @VinceDZiree - the docs are correct 😄 fixed the code in the referenced PR 👍 thx again for raising this issue 🙏
