### ISSUE TITLE
Publish Qwikcity to NPM

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#482]
### Is your feature request related to a problem?

In order to allow people to build MPA applications `@builder.io/qwikcity` needs to be published.

### Describe the solution you'd like

Run `npm create qwik@latest` and have an option to create a simple website.

### Describe alternatives you've considered

Qwik without Qwikcity requires too much wiring on the part of the developer.

**Comment by adamdbradley** [comment]
https://www.npmjs.com/package/@builder.io/qwik-city
