### ISSUE TITLE
[🐞] inconsistent rendering between SSR and CSR

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#4824]
### Which component is affected?

Qwik Runtime

### Describe the bug

SSR interprets `<button disabled={''}>` as disabled but CSR interprets it as NOT disabled. 

### Reproduction

https://stackblitz.com/edit/qwik-starter-u3vczw?file=README.md,src%2Froutes%2Findex.tsx

### Steps to reproduce

Click on the toggle button and observe that the target button disabled does not correctly follow from SSR.

### System Info

```shell
n/a
```

**Comment by Varixo** [comment]
what behaviour is expected? 
`disabled=""` is a valid attribute, so CSR should add it or SSR should ignore attributes with empty values?

**Comment by mhevery** [comment]
I would say that `""` should render as `<button disabled/>`. So I think CSR is correct, and SSR behavior is wrong.

**Comment by Varixo** [comment]
If so, then SSR is correct and CSR is not. I will create a PR, please verify :D

**Comment by manucorporat** [comment]
`disabled` is a boolean, not a string. JSX is not attributes.

**Comment by manucorporat** [comment]
Imo, it should not be fixed, but emit a warning in dev mode.

**Comment by iamriajul** [comment]
I've <option> tag uses, 
![image](https://github.com/BuilderIO/qwik/assets/24244379/f81fc62b-cefd-49f8-9d09-6c4853feddd4)
Here the output works as expected when it SSR rendered, but the option's value attribute does get disappeared when it is CSR rendered.
It is causing serious bugs!

**Comment by iamriajul** [comment]
![image](https://github.com/BuilderIO/qwik/assets/24244379/3ae30ce8-3376-452c-9424-5586d28351cd)
This is when SSR rendered.
![image](https://github.com/BuilderIO/qwik/assets/24244379/cf2c1aee-b33d-412b-a04b-7b0f92164c3d)
This is when CSR rendered.

**Comment by wmertens** [comment]
@iamriajul can you share that piece of code or something like it?

**Comment by iamriajul** [comment]
```html
<option value={''}>Select</option>
```

**Comment by wmertens** [comment]
@iamriajul Can you explain why value="" is needed? I agree that CSR and SSR should do the same thing but I don't know what the correct thing is.

Here's a playground. SSR will render `""` as `value` and `true` as `value=""`. CSR will render `""` as nothing and `true` as `value="true"`. Which is correct?

https://qwik.builder.io/playground/#v=1.2.19&f=Q0o0pkbm2BKNDqL2pTj9QAIDWk3YIgzWMNBESl1QV0KqGIXs1ErbaogWPWCeK02thfsJGC2geAWL2ioZKtkZ2uhDxNCVwKorRA0I1WSkZGekoKuQnJGfD6or8kBRDdSAyxyoLmMlO2MCSkyU7EwIKFGyAzZ9klPxq6oGVSC1diASVaENMEOAPAXlJRVB49oG0j5DNEuqNTRt7ZADUFu7FsiHxgJQJbDABsYTvGEHNAWUQkZz9NDM0QA

**Comment by iamriajul** [comment]
> Can you explain why value="" is needed

It's the initial value of my signal.
eg:
```tsx
const method = useSignal<'' | 'VIDEO' | 'AUDIO'>();
// Where `` empty string means no filtering is applied.
// And `VIDEO`or `AUDIO` means their filtering is applied respectively.
<select bind:value={method}>
<option value="">Select a Filter</option>
<option value="VIDEO">Video Filter</option>
<option value="AUDIO">Audio Filter</option>
</select>
```

When user doesn't select any option or select the first item which is `Select a Filter` with value of empty string ` `.  the signal then updated accordingly with empty string. but when in CSR mode the the HTML doesn't even have the value attribute that results in my Signal value to be `Select a Filter` when user select the first item. But I don't expect my signal to have `Select a Filter` as instead of ` ` empty string.

**Comment by wmertens** [comment]
Ok we discussed with Misko and both SSR and CSR should do the following:

- anything falsy (not string, not number) => attribute removed
- true => `<div attr/>`
- "" => `<div attr=""/>`

So both need fixing
