### ISSUE TITLE
[🐞] fastify adapter ignores the bind address configured in `vite.config.ts`

### ISSUE THREAD

**Issue by genki** [BuilderIO/qwik#4826]
### Which component is affected?

Starters / CLI

### Describe the bug

I configured the bind address to "0.0.0.0" in the `vite.config.ts` like this:

```ts
export default defineConfig(() => {
  return {
  ...
    server: {
      host: "0.0.0.0",
    },
  ...
});
```

and it effects on the dev server and preview mode correctly, but the Fastify starts like this:

```
$ node server/entry.fastify
{"level":30,"time":1689757347171,"pid":70902,"hostname":"mba22.local","msg":"Server listening at http://[::1]:3000"}
{"level":30,"time":1689757347172,"pid":70902,"hostname":"mba22.local","msg":"Server listening at http://127.0.0.1:3000"}
```

Looking into the `adapters/fastify/vite.config.ts`, it inherits the base config but more things could be required for configure the fastify.

### Reproduction

https://github.com/genki/qwik-test/tree/add_fastify

### Steps to reproduce

1. clone the repo above
2. `pnpm i`
3. `pnpm run build.server`
4. `pnpm serve`

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
    Memory: 415.28 MB / 24.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.7.2 - /opt/homebrew/bin/npm
    pnpm: 8.6.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @builder.io/qwik: 1.2.6 => 1.2.6 
    @builder.io/qwik-city: latest => 1.1.4 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.0 => 4.4.0
```

**Comment by manucorporat** [comment]
That configuration only affects the vite dev server, if you want to change anything related to fastify, look at the `entry.fastify.tsx` file created as part of the integration

**Comment by genki** [comment]
@manucorporat Thanks letting me know :)
BTW, how about to change the default bind addr from "127.0.0.1" to "0.0.0.0"?
Because this adapter is not for dev but for production that is typically need to be reached from other host.
