### ISSUE TITLE
[✨] qwik-city: routes should allow aliases for i18n

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#4835]
### Is your feature request related to a problem?

When doing i18n, SEO people like it when URLs are also translated. This is the same as aliasing paths.

### Describe the solution you'd like

Allow comma separated names as a route path, for example `/[...locale]/blog,blogue,blog/[id]`

### Describe alternatives you've considered

`|` is also a good candidate but it can be problematic on the command line. Normally, people don't put commas in paths so that should be safe.

**Comment by claudioshiver** [comment]
I added route rewriting in this PR, hope it will be merged soon: #5122

**Comment by mhevery** [comment]
Resolved by #5122
