### ISSUE TITLE
[🐞] Unable to load 404 page with fastify adapter

### ISSUE THREAD

**Issue by dheeruasdf** [BuilderIO/qwik#4854]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I have followed the following docs for the setup of fastify adapter, everything is working fine except for the custom error handler pages.
https://qwik.builder.io/docs/deployments/node/

It is giving the following error on landing to a non found page
```
TypeError: Cannot read properties of undefined (reading 'Symbol(pino.msgPrefix)')
    at LOG (file:///home/projects/qwik-starter-mdegks/node_modules/pino/lib/tools.js:68:22)
    at router2 (file:///home/projects/qwik-starter-mdegks/server/entry.fastify.mjs:1365:7)
    at async Object.eval (file:///home/projects/qwik-starter-mdegks/server/entry.fastify.mjs:1437:5)
```

I have dubugged the issue and found out that the following code is the culprit
https://github.com/BuilderIO/qwik-city-build/blob/dd3c8b03a1163a1783ec163688a7eeb1a790fe15/middleware/node/index.mjs#L212-L221

when a page is not available then `requestHandler` is returning `null` 
so I have tried moving the `next()` method in line 221 into the if block, and it has started working.

I could have raised a PR but I am very new to the process. Appreciate someones help to do so.

### Reproduction

https://stackblitz.com/edit/qwik-starter-qeafye?file=src%2Froutes%2F404.tsx

### Steps to reproduce

Run the following steps in sequence
1. npm install
2. npm run build
3. npm run serve

### System Info

```shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 818.19 MB / 5.64 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.2.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v19.2.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
  npmPackages:
    @builder.io/qwik: ^1.2.6 => 1.2.6 
    @builder.io/qwik-city: ^1.2.6 => 1.2.6 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.6 => 4.4.6
```

**Comment by robertwach** [comment]
Same issue here

**Comment by zanettin** [comment]
closed via https://github.com/BuilderIO/qwik/pull/4879
