### ISSUE TITLE
[🐞] Weird error with no clarification. useLexicalScope()

### ISSUE THREAD

**Issue by AmirSa12** [BuilderIO/qwik#4858]
### Which component is affected?

Qwik Runtime

### Describe the bug

Hey,
in my qwik component, I have this:
```
  let divRef = useSignal<HTMLElement | undefined>();
  let isDown = false;
  let startX: number | undefined = 0;
  let scrollLeft: number | undefined = 0;

  const handleMouseDown = $((e: QwikMouseEvent) => {
    console.log("working");
    isDown = true;
    console.log(divRef.value!.scrollLeft);
    startX = e.pageX - divRef.value!.offsetLeft;
    scrollLeft = divRef.value!.scrollLeft;
  });
```

```
<div
              class="flex gap-1.2rem"
              ref={divRef}
              preventdefault:click
              onMouseDown$={handleMouseDown}
```

and when I click on the divRef, the function fires, but there is a weird error appearing in my console: Uncaught (in promise) TypeError: Assignment to constant variable.

I checked, it is comming from where the code gets into another file when exported
in that file there is this:

```
import {useLexicalScope} from "/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/core.mjs?v=f3aa43fc";
export const MainCards_component_handleMouseDown_MRSfAw1p2to = (e)=>{
    const [isDown,rootRef,scrollLeft,startX] = useLexicalScope();
    console.log("working");
    console.log(rootRef.value.scrollLeft);
    startX = e.pageX - rootRef.value.offsetLeft;
    scrollLeft = rootRef.value.scrollLeft;
}
```

which I believe it is from the const at the useLexicalScope()

any ideas how to fix this issue?

### Reproduction

https://stackblitz.com/edit/qwik-starter-1tmyq3?file=src%2Froutes%2Findex.tsx,src%2Fcomponents%2Fissue.tsx

### System Info

```shell
Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.9 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.18362.387.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0
    @builder.io/qwik: ^1.2.6 => 1.2.6
    @builder.io/qwik-auth: ~0.1.0 => 0.1.0
    @builder.io/qwik-city: ^1.2.6 => 1.2.6
    @builder.io/qwik-react: 0.5.0 => 0.5.0
    undici: 5.22.1 => 5.22.1
    vite: 4.4.0 => 4.4.0
```

**Comment by wmertens** [comment]
We determined in discord that it should be done with a store, so the problem here is that the scope captures a `let` and makes it into a `const`.

The scope capture should maybe complain if it captures a `let`?

**Comment by manucorporat** [comment]
Our eslint already complains about this, thoughts to improve the lint error.

Wondering why you are not getting the lint message.
![Uploading Screenshot 2023-07-27 at 13.21.14.png…]()

**Comment by AmirSa12** [comment]
Thanks @manucorporat. yeah It was weird for me not getting the message.
anyways, I put the value in a useStore({}) hook as the message says.
