### ISSUE TITLE
[✨] Route change progress indicator or listeners for on route change start/complete

### ISSUE THREAD

**Issue by robertwach** [BuilderIO/qwik#4869]
### Is your feature request related to a problem?

Most of the times when navigating from www.example.com to www.example.com/about the url changes and  2s later the content for the new page appears. 

At times on slow network when you click on a link there is no response that navigation has begun which can lead to user clicking multiple times.

### Describe the solution you'd like

Is there a function that could indicate navigation start or something similar that could help implement navigation progress indicator

### Describe alternatives you've considered

 way to integrate with packages like nprogress (https://ricostacruz.com/nprogress)

**Comment by Varixo** [comment]
Hey, did you try this?
https://qwik.builder.io/docs/api/#uselocation
```ts
const location = useLocation();
...
{location.isNavigating &&
   <div id="spinner"></div>
}
```

**Comment by robertwach** [comment]
> Hey, did you try this? https://qwik.builder.io/docs/api/#uselocation
> 
> ```ts
> const location = useLocation();
> ...
> {location.isNavigating &&
>    <div id="spinner"></div>
> }
> ```

Thank you. The api helps integrate a transition indicator. Thank once again.
