### ISSUE TITLE
[📖] Where is the index.html location for Docs package bundle results

### ISSUE THREAD

**Issue by Lutece** [BuilderIO/qwik#4882]
### Suggestion

Hello, there is a problem while i translating into Korean. 
I have a question about the document index page.
I want to modify the components on the main page of the document, but the HTML on the page is acquired using api and cannot be modified directly.
Also, if i look at the built results, i cannot find the document index page html file. (Page 404 appears.)
What should I do?

**Comment by robertwach** [comment]
Have you tried implementing your logic on root.tsx or layout.tsx? Qwik does not have an index.html at least from what have observed. Check this out https://qwik.builder.io/docs/api/#qwikcityprovider

**Comment by zanettin** [comment]
thx @shairez for answering this 🙏 hope this helps @Lutece. i'll close this for now but feel free to re-open if needed.
