### ISSUE TITLE
[📖] `useResource$()` link leads nowhere

### ISSUE THREAD

**Issue by Hades32** [BuilderIO/qwik#4890]
### Suggestion

This doesn't lead anywhere: https://qwik.builder.io/docs/components/tasks/#useresource
And I still don't know the details about that function and if it only runs on the server or not

**Comment by zanettin** [comment]
Hi @Hades32 👋 
thanks for the headsup 🙏 the docs can be foud here https://qwik.builder.io/docs/components/state/#useresource
i'll adjust the invalid link 👍
