### ISSUE TITLE
[🐞] leaflet.js gets 403 while trying to fetch marker icons

### ISSUE THREAD

**Issue by sharifrezvani** [BuilderIO/qwik#4895]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm using leaflet.js to show maps on my website. Everything works great except when I add markers, leaflet.js tries to load the default marker icon from browser, and it hits 403 because it tries to reach the `node_modules` directory.

This is the URL it tries to fetch:

```
https://example.local/@fs/Base/Qwik/node_modules/leaflet/dist/images/marker-icon.png
```

### Reproduction

There is no need for reproduction

### System Info

```shell
System:
    OS: Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 9.65 GB / 15.50 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0 
    @builder.io/qwik: ^1.2.6 => 1.2.6 
    @builder.io/qwik-auth: ~0.1.0 => 0.1.0 
    @builder.io/qwik-city: ^1.2.6 => 1.2.6 
    undici: 5.22.1 => 5.22.1 
    vite: ^4.4.6 => 4.4.7
```

**Comment by Pterygoidien** [comment]
Hi, I used leaftlet as well and it works good with both markers and clusters. My project is open source if you want to check it out (not optimized yet, but working !) : here it is[Here it is (Qwik-vlock)](https://github.com/Pterygoidien/qwik-vlock/tree/main/src/components/map) . 

How did you try to import it in your file ?

**Comment by shairez** [comment]
Thanks for the help @Pterygoidien !

Closing it for now as it seems like it is resolved by the answer
