### ISSUE TITLE
[✨] rename component$ to $$

### ISSUE THREAD

**Issue by dmitryuck** [BuilderIO/qwik#4898]
### Is your feature request related to a problem?

no actually, just an readability improvement

### Describe the solution you'd like

currently, we have

```
export const MyComp = component$(() => {
  ...
});
```

the idea is to rename a long component definition to a short one

```
export const MyComp = $$(() => {
  ...
});
```

having that two key features of framework `$() - reactive function` and `$$() - reactive component`, make it shorter and simpler 

### Describe alternatives you've considered

no alternatives I see

**Comment by shairez** [comment]
Thanks for the suggestion @dmitryuck 
This is not a small change and will affect lots of people (especially content creators) and overall perception of stability of the framework. 
Personally I like `component$` as I believe it conveys better the meaning to the developer. ($ and $$ might be too close and thus confusing)

We also predict that most of the time, components will be generated either by CLI, nx generators, snippets or copy& paste, so it's not as common as reactive functions.

So while we like to keep names short, it's not a change we are planning to consider for the near future.

I'm closing it for now, but thanks again for trying to make Qwik better!
