### ISSUE TITLE
[📖] clientConn how does this work

### ISSUE THREAD

**Issue by primozs** [BuilderIO/qwik#4909]
### Suggestion

_The best part is that you don’t need to know how any of those work. ClientConn API abstracts this complexity and provides a normalized API you can use regardless of where you deploy or self-host.

https://www.builder.io/blog/qwik-1-2-performance-autopilot_

ClientConn, how does this work? I don't want to use any APIS I am not choosing.

**Comment by zanettin** [comment]
Hi @primozs 👋 
Thanks for asking. this functionality was added here https://github.com/BuilderIO/qwik/pull/4433/files and returns the information qwik-city receives from the hosting service. so no magic involved 🪄 😃
