### ISSUE TITLE
[🐞] updating a Signal in different functions does not trigger re-render

### ISSUE THREAD

**Issue by yasserlens** [BuilderIO/qwik#4919]
### Which component is affected?

Qwik Runtime

### Describe the bug

I have strange behavior that may be a bug. Here is what happens:
- I have a Signal ```const isLoading =  useSignal(false);```
- The state is modified by multiple functions (wrapped by $(...)) inside a component$(..)
- The signal is set to "true" before the start of loading lazily loaded code, which is supposed to bring an element into the DOM.
- Then set to false when the reference to that DOM element is in view.
- Upon inspection, the Signal updates without problems
- However, the rendered page does not reflect that.
- This is mainly noticed when the updates to the signal happen in different functions.
- [update] actually, in the code example below, updating the signal value doesn't update the UI even if moved to the same function (e.g. onClick - when tried in Qwik's Playground using a fake delay via an await new Promise(..))

Code snippet is below in the reproduction section.

### Reproduction

https://stackblitz.com/edit/qwik-starter-mvw12k?file=src%2Fcomponents%2Fstarter%2Frender-issue%2Frender.tsx

### Steps to reproduce

```typescript
import { component$, useSignal, useTask$, $, type Signal } from '@builder.io/qwik';
import { type PropFunction, type QwikMouseEvent } from "@builder.io/qwik";

export interface ButtonProps {
  label: string;
  isLoading?: Signal<boolean>;
  onClick$?: PropFunction<(event: QwikMouseEvent<HTMLButtonElement, MouseEvent>) => void>;
}

export function InlineButton(props: ButtonProps) {
  return (
    <button onClick$={props.onClick$}>
      {props?.isLoading?.value ? (
        <> Loading ... </>
      ) : (
        <>{props.label}</>
      )}
    </button>
  );
}


export default component$(() => {
  const isLoading = useSignal(false);
  const counter = useSignal(0);

  useTask$(async ({ track }) => {
    track(() => counter.value);
    await new Promise(resolve => setTimeout(resolve, 2000));
    isLoading.value = false;
    console.log('finish. isLoading?', isLoading.value);
  });

  const onClick = $(async () => {
    counter.value += 1;
    isLoading.value = true;
    console.log('start. isLoading?', isLoading.value);
  });

  return (<>
    <p>Hello Qwik</p>
    {/** Both the div below and the button below it do not show the "loading" state. */}
    <div>
      {(isLoading.value === true) ? (<>isLoading...</>) : (<>Idle</>)}
    </div>
    <div>
      <InlineButton label={'NEXT'} onClick$={onClick} isLoading={isLoading} />
    </div>
  </>);
});

```

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (12) x64 Apple M2 Pro
    Memory: 107.24 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
    pnpm: 7.9.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.3
  npmPackages:
    @builder.io/qwik: ^1.2.6 => 1.2.6 
    @builder.io/qwik-city: ^1.2.6 => 1.2.6 
    undici: ^5.22.1 => 5.23.0 
    vite: ^4.4.0 => 4.4.8
```

**Comment by shairez** [comment]
Hi @yasserlens !

Thanks for submitting the issue

This is not actually a bug.

If you think about it, the `Task` always runs before the render... 
So the `await` with the timer blocks the rendering from happening, until the promise resolves.

If you change the code to be "non blocking" like 
```
useTask$(async ({ track }) => {
    track(() => counter.value);
    
    new Promise(resolve => setTimeout(resolve, 2000)).then(()=>{
      isLoading.value = false;
        console.log('finish. isLoading?', isLoading.value);
    });
    
  });
  ```
  
it will work as you expect it to work.

This is from the [tasks docs](https://qwik.builder.io/docs/components/tasks/) - 

![image](https://github.com/BuilderIO/qwik/assets/1430726/a67cf488-8ae9-4e13-9aef-0603bf72f326)

Hope this clears things up
