### ISSUE TITLE
[🐞] Server functions cant run functions that are defined outside of the top level

### ISSUE THREAD

**Issue by M-M-M-M-M-M-M-M-M-M** [BuilderIO/qwik#4923]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I want to define `func` inside of `test` and run it in a server function, but doing this causes a `Dynamic require` error
```ts
const test = async () => {
  let func = $(()=>"Working!") 
  let serverFunc = server$(async () => {
    return func()
  })
  return serverFunc()
}

console.log(await test())
```

Expected outcome: log `Working!`
Outcome: `Uncaught (in promise) Error: Dynamic require of "/src/test_func_7dytemg6cq8.js" is not supported`

Notes: 
* If you move `func` out of the `test` function and into the top level, it works
* If you dont serialize `func` you get an error saying `You might need to convert it to a QRL using $(fn):`. However if you run it in the top level without serializing it you dont get this error
* If you log `func` in the server it actually is defined. It's a `[AsyncFunction: invokeQRL]`. Still wont run though
* Trying to clone the function doesnt fix the issue. Returns the same error as before

### Steps to reproduce

Run this:
`git clone https://github.com/M-M-M-M-M-M-M-M-M-M/Qwik-JS-Server-Func-Bug && cd ./Qwik-JS-Server-Func-Bug && npm i && npm start` 

### System Info

```shell
System:
    OS: Linux 5.17 Fedora Linux 36 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Memory: 3.17 GB / 15.49 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.1/bin/npm
  npmPackages:
    @builder.io/qwik: ^1.2.6 => 1.2.6 
    @builder.io/qwik-city: ^1.2.6 => 1.2.6 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.0 => 4.4.0 
```

### Additional Information

There isnt a Reproduction link because for some reason `server$` breaks stackblitz. If you want to try to get it working, [here's a link](https://stackblitz.com/edit/qwik-starter-dkw4td?file=src%2Froutes%2Findex.tsx), but whatever's causing stackblitz to not work isnt related to my issue

**Comment by hamatoyogi** [comment]
Can you please explain the use case or problem you're trying to solve?

**Comment by M-M-M-M-M-M-M-M-M-M** [comment]
With my app all the requests sent to the server are signed with a crypto graphic key. Because of this all my functions have this boilerplate.
```ts
const user = {
  publicKey: "xxxxxx",
  privateKey: "xxxxxxx"
}

// boilerplate starts here
type Data = {"username": string}
const changeUsername = async (data: Data) => {
  let signedData = await sign(data, user)
  let serverFunc = server$(async function (signedData: string, publicKey: string) {
    let data: Data = await verify(signedData, publicKey)
    // [...]
    return response
  })
  return await serverFunc(signedData, user.publicKey)
}
```
I made a function that does all of this automatically, but it doesnt work because of this bug.

**Comment by M-M-M-M-M-M-M-M-M-M** [comment]
@hamatoyogi I found a workaround. I can store the function in an object and then pass that object into my function, that way it still counts as being defined as being on the top level.

I'm not opening myself up to code injections with this, am I?

**Comment by hamatoyogi** [comment]
> @hamatoyogi I found a workaround. I can store the function in an object and then pass that object into my function, that way it still counts as being defined as being on the top level.
> 
> I'm not opening myself up to code injections with this, am I?

hard to say without seeing the code... But generally:

The server$ function in Qwik is designed to always execute on the server. It's a form of RPC (Remote Procedure Call) mechanism between the client and server. When you use server$, it wraps a function and returns an async proxy to the function. On the server, the proxy function directly calls the wrapped function, and a HTTP endpoint is automatically created by the server$() function.

As for security, it's important to note that server$ functions can read HTTP cookies, headers, or environment variables, which could potentially expose sensitive information if not handled properly. However, Qwik does not inherently make your application less secure. The security of your application largely depends on how you handle and protect sensitive data within your server$ functions.

For example, if you're accessing a database within a server$ function, you should ensure that you're properly authenticating and authorizing those requests. You should also avoid exposing sensitive information in HTTP responses.

In terms of storing the server$ function on an object, as long as the object itself is secure and not exposed to any potential threats, it should not pose a security risk. However, it's always important to follow best practices for security in your specific context.

For more information, you can refer to the [Qwik documentation on server$](https://qwik.builder.io/docs/server$/). If you have specific security concerns, it may be best to consult with a security expert or conduct a security audit of your application.
