### ISSUE TITLE
[✨] Create new Markdown route with CLI

### ISSUE THREAD

**Issue by brandonpittman** [BuilderIO/qwik#4931]
### Is your feature request related to a problem?

I have a lot of Markdown-backed routes. These routes have to be in a folder: `/route-path/index.md`.

### Describe the solution you'd like

I'd like to be able to use `npm run qwik new` to add a route that has an `index.md` not an `index.tsx`.

Maybe… `npm run qwik new /path/to/route:md`

### Describe alternatives you've considered

Writing my own shell script.

**Comment by shairez** [comment]
Thanks for the issue @brandonpittman !
This could be a great PR added by the community
Care to give it a go?
