### ISSUE TITLE
[📖] SSG on Cloudflare Pages

### ISSUE THREAD

**Issue by mattp0123** [BuilderIO/qwik#4943]
### Suggestion

Add more details of how to config Cloudflare Pages adapter in this [section](https://qwik.builder.io/docs/deployments/cloudflare-pages/#cloudflare-pages-function-invocation-routes) about how to pre-render pages / prevent function invocations. Like:
```typescript
export default extendConfig(baseConfig, () => {
  return {
    build: {
      ssr: true,
      rollupOptions: {
        input: ['src/entry.cloudflare-pages.tsx', '@qwik-city-plan'],
      },
    },
    plugins: [
      cloudflarePagesAdapter({
        ssg: {
          include: ['/*'], // Pre-render all pages on build time.
        },
      }),
    ],
  };
});
```

**Comment by gioboa** [comment]
Here is the [piece of code](https://github.com/QwikDev/qwik/blob/8d1c0b05d3a8c7d98de163707a21e359c9fd56de/packages/qwik-city/adapters/shared/vite/index.ts#L226) that is managing SSG
