### ISSUE TITLE
[🐞] Component prop mutation based on loader not adjusting classes properly

### ISSUE THREAD

**Issue by Joru-chan** [BuilderIO/qwik#4959]
### Which component is affected?

Qwik Runtime

### Describe the bug

We use a value returned by a loader to display our pagination as well as manage the Previous and Next button statuses.

What I expect:
When using the state, the disabled prop from our Button component reflected the change properly. "Previous" button is disabled when on page 1, enabled on > 1.

What happens:
Once we started using loaders, it stopped changing within the component. The "Previous" button keeps the disabled state. Upon refreshing, it adapts fine. 

More:
- We seem to only be encountering this bug when we use loaders + our button as <Link>. 
- We tried directly putting a <Link> instead with a mock class `disabled` and the change was reflected correctly. Only when within a prop does it not change the classes.
- We are currently using the workaround of using an anchor instead of <Link> in our button, doing an MPA navigation instead of SPA.

### Reproduction

https://stackblitz.com/edit/qwik-starter-knzhvr?file=src%2Fcomponents%2Fsearch-results%2Fpagination.tsx

### Steps to reproduce

To reproduce please open the preview in a new tab in order to see the query params do change properly

Click on Next and see the URL change, the page number change, but the disabled prop not updating the class properly for the "Previous" button. Therefore, the button stays disabled when it's not supposed to.

This works as intended when we directly use a <Link> component however our Button component uses an `as` prop to which we pass `a`, `button`, or `<Link>` in order to reuse the design for multiple semantic purposes.

### System Info

```shell
On stackblitz =p


  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4 
    @builder.io/qwik-city: ^1.1.4 => 1.1.4 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.5 => 4.3.5
```

**Comment by manucorporat** [comment]
does it still reproduce with 1.2.7?

**Comment by mhevery** [comment]
> does it still reproduce with 1.2.7?

https://stackblitz.com/edit/qwik-starter-knzhvr is on 1.2.7 and it seems to work correctly.

**Comment by mhevery** [comment]
Closing as fixed, please open new one if you still see it.
