### ISSUE TITLE
[🐞] Qwik City's `useLocation` doesn't detect the origin scheme

### ISSUE THREAD

**Issue by FHachez** [BuilderIO/qwik#4965]
### Which component is affected?

Qwik City (routing)

### Describe the bug

We are using the `useLocation` for to set the canonical url like in the Qwik City starter. Once we put the Qwik app behind a reverse proxy like AWS Cloudfront or behind `ngrok` or simply a load balancer, the canonical url is with `http` instead of `https`.

In our RouterHead we have:
```ts
export const RouterHead = component$(() => {
  const head = useDocumentHead();
  const loc = useLocation();

  return (
    <>
      <title>{head.title}</title>
      <link rel="canonical" href={loc.url.href} /
...
```

### Reproduction

https://registry.jolimont.rosa.be/fr/search/

### Steps to reproduce

# Live example
1. Go to the reproduction url https://registry.jolimont.rosa.be/fr/search/ 
2. The url is with https but the canonical url is with http.

# To reproduce locally
1. Install the qwik starter.
2. Serve it via ngrok.
4. The canonical url in the page is with `http` instead of `https`.
![image](https://github.com/BuilderIO/qwik/assets/3494000/d4e4fb83-a899-46ff-b156-3299e5dcfa41)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.1.4 => 1.1.4 
    @builder.io/qwik-city: ^1.1.4 => 1.1.4 
    undici: 5.22.1 => 5.22.1 
    vite: 4.3.5 => 4.3.5
```

### Additional Information

It's unclear for me what is the best way for Qwik to detect the origin and scheme. Client side it is easy but it isn't on the server side. I would expect Qwik City to rely on the `origin` header, but it's not a mandatory header.

I would rather not rely on the `ORIGIN` parameter int he vite config https://qwik.builder.io/docs/guides/static-site-generation/#origin because we want to serve the same app under different domains.

Maybe we should be able to pass the origin to the `renderToStream` function? I would prefer a good default but I don't mind handling the logic if needed.

**Comment by mhevery** [comment]
Looked into it, and I can't think of a way for the QwikCity to know what the original protocol was. It is not something that is reliably sent over to the server. (Unless you know of a way)

May I suggest this workaround?  When generating URLs just generate them without the protocol, that way they will default to the same protocol as the current page, which will solve the issue.

```JSX
{location.url.toString().substring(location.url.protocol.length)}
```

**Comment by FHachez** [comment]
I don't fully get your idea.

I've investigated a bit more. My understanding is that we cannot trust the headers in general. We need to rely on the host.

Once we use a reverse proxy we can't rely on the host anymore but we can setup the reverse proxy to forward the headers. The reverse proxy adds X-forwarded-* cookies with the original host.

We can even tell expresse.js to handle this with http://expressjs.com/tr/guide/behind-proxies.html 
`app.set('trust proxy', true)`

req.hostname will come from X-Forwarded-Host

I'm going to try this out.

**Comment by mhevery** [comment]
My understanding is that there are two problems:
- Forwarding of the host: This is done through the `Host` header, and it already works. But `Host` header does not contain the protocol (http/https) only the host. such as `my-host.com`
- Forwarding of the protocol. Was the original request `http` or `https`. This information I don't know how to get.

So my suggestion is to just do `//server.name/path` by skipping `http:` the URL in the browser will default to whatever the current protocol scheme is.

**Comment by mhevery** [comment]
Ahh https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto is what I was missing. Let me dig into it further.
