### ISSUE TITLE
[🐞] The "dist" folder is not generated in "dev" mode

### ISSUE THREAD

**Issue by devcaeg** [BuilderIO/qwik#4969]
### Which component is affected?

Qwik Runtime

### Describe the bug

The "dist" folder is not generated in development mode, but it is generated in "preview" mode. This happens with Qwik version 1.2.7.

### Reproduction

https://stackblitz.com/edit/qwik-starter-s46xwt?file=package.json

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
    Memory: 461.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /opt/homebrew/bin/npm
    pnpm: 8.6.12 - /usr/local/bin/pnpm
    Watchman: 2023.08.07.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 16.5.2
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.0 
    @builder.io/qwik: 1.2.7 => 1.2.7 
    @builder.io/qwik-city: ~1.2.7 => 1.2.7 
    undici: 5.23.0 => 5.23.0 
    vite: 4.4.9 => 4.4.9
```

**Comment by mhevery** [comment]
Yes, this is working as intended. To have fast dev experience, the code generation and vite work differently in the dev mode. The main difference is that in dev mode, each symbol is in a separate URL and there is no 'manifest.json'.

What problem do you wish to solve by having the dev mode generated?

**Comment by devcaeg** [comment]
> Yes, this is working as intended. To have fast dev experience, the code generation and vite work differently in the dev mode. The main difference is that in dev mode, each symbol is in a separate URL and there is no 'manifest.json'.
> 
> What problem do you wish to solve by having the dev mode generated?

Oh, I get it. I found the change strange, because in previous versions the "dist" folder was generated, and in the changelog of version 1.2.7 I didn't see anything mentioning this change.

The only question I have is what would happen with plugins/complements, which make changes in the "dist" folder. For example I had a plugin that made changes in the "dist" folder, I will have to change the focus.

**Comment by mhevery** [comment]
I don't believe that dist folder was ever generated in dev mode. This has always worked that way.

Vite plugins usually make changes on the fly, so dist folder is should not be an issue.

But I am not an expert on this and may misunderstand these things.
