### ISSUE TITLE
[🐞] A layout can not prevent a page from being evaluated

### ISSUE THREAD

**Issue by phcoliveira** [BuilderIO/qwik#4975]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I opened an [issue on Discord](https://discord.com/channels/842438759945601056/1142596925426778112) first.

I am having some problems in achieving a gateway system. I am porting a small app from a Svelte codebase to Qwik, and such gateway system used to work there.

The idea is simple: given that the file layout.tsx is evaluated before its underlying pages, it should prevent them to be rendered by returning `null`.

### Reproduction

https://stackblitz.com/edit/qwik-starter-plozm1?file=src%2Froutes%2Ffoobar%2Findex.tsx

### Steps to reproduce

Open the console before clicking on the link `Go to foobar`.

The page /routes/foobar/index.tsx has a console log triggered by a `useTask`$ hook. Even its visible task also runs.

However, the page should never be rendered because its sibling layout.tsx returns null.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 12.81 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.volta/tools/image/node/16.15.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.11.0 - ~/.volta/tools/image/npm/8.11.0/bin/npm
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 116.0.5845.96
    Firefox: 116.0.1
    Safari: 16.5.2
```

### Additional Information

[You can do the same with an example using Svelte Kit. But, with Svelte, the `console.log()` from `routes/foobar/+page.svelte` does not run.](https://stackblitz.com/edit/node-3keecz?file=src%2Froutes%2Ffoobar%2F%2Blayout.svelte)

**Comment by mhevery** [comment]
This works as expected. Because of the way Qwik serializes components, it needs to be able te recover project content without having to re-run all code. This means that the projected content is always rendered (even if it is not projected.)

If you don't want to render content at this location you should use middleware to do authentication and redirect to a different page. 

Could you better explain what is the overall behavior you would like to achieve?

**Comment by phcoliveira** [comment]
Sure! For example, I have this component:
```tsx
// require-anonymous-authentication
import {component$, Slot, useContext, useTask$} from '@builder.io/qwik';

import {authenticationContextId} from '~/lib/components';

export const RequireAnonymousAuthentication = component$(() => {
  const authentication = useContext(authenticationContextId);

  useTask$(
    (task) => {
      const send = task.track(() => authentication.send);
      if (!send) return;

      send({type: 'SIGN_IN', data: {method: 'Anonymously'}});
    },
    {eagerness: 'load'}
  );

  return authentication.state.matches('Authenticated') ? <Slot /> : null;
});
```
I don't think the `authentication` context is important to this matter, but let me know if you think differently.

Then, I use it on a `layout.tsx` file to try and prevent underlying pages to be rendered because they need an authentication user. Otherwise, I would have to do defensive programming checking if the user is authenticated, which defeats the purpose of the component and layout.
```tsx
// src/routes/(app)/layout.tsx
import {component$, Slot} from '@builder.io/qwik';

import {RequireAnonymousAuthentication} from '~/lib/components';

export default component$(() => {
  return (
    <RequireAnonymousAuthentication>
      <Slot />
    </RequireAnonymousAuthentication>
  );
});
```

**Comment by mhevery** [comment]
So authentication should never run on the client as it could be easily bypassed. It should always run on the server.

Things such as auth should be done in middleware, not in components. 

NOTE: as a side note, the `<Slot>` will only pre-render components one level deep. So you could introduce an extra component inside the projected content, and it will not eagerly render. But again I think you are approaching this problem not in "qwik" way.

**Comment by phcoliveira** [comment]
So, using the logic, I also have a component named `RequirePartyMember` to only allow the `<Slot />` to be open when you are a member of a party. Otherwise, you will be redirected to creating a party. So it makes no sense to render the game when you are not in a party.

**Comment by phcoliveira** [comment]
Likewise, the game page is always initialized as well, even when you are not a member of a party.

**Comment by mhevery** [comment]
Since the page is not rendered is there an issue? Or are you saying that rendering the page has a side-effect that you want to avoid?

Why not move the auth logic into the default expert component then?

**Comment by phcoliveira** [comment]
Yes, precisely, as the underlying pages expected some condition to be fulfilled, they were breaking. What troubled me for some time is that I thought it was about a race condition.

When I made the experiment above and discovered that the pages were being run (even the visible tasks), I thought it was a bug because SvelteKit is not like that.

So, instead of using a component such as `RequireAnonymousAuthentication` in a layout file, I can have an async hook to be used by each page inside a task. Given that a `useTask$` blocks the rendering of such page, I can achieve the same thing in a different way. Something like:

```tsx
component$(() => {
  useTask$(async () => {
    await useAnonymousAuthentication()
  })
  // carry on
});
```

Thanks for your readiness.
