### ISSUE TITLE
[🐞] ESLint dev configuration errors

### ISSUE THREAD

**Issue by jessezhang91** [BuilderIO/qwik#4980]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug
	
I am running dev mode with a `tsconfig.json` that has [project references](https://www.typescriptlang.org/tsconfig#references) defined.

I am getting a ``Parsing error: ESLint was configured to run on `<tsconfigRootDir>/src/root.tsx` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json`` warning (which is slowing down the initial dev build since it's printing it for every file referenced).

I expect there not to be an error.

### Reproduction

https://stackblitz.com/edit/qwik-starter-ro4pwa?file=tsconfig.app.json,tsconfig.json

Example warning:
```
[vite] warning: Parsing error: ESLint was configured to run on `<tsconfigRootDir>/src/root.tsx` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
  Plugin: vite-plugin-qwik
  File: /home/projects/qwik-starter-wmq6la/src/root.tsx:undefined:undefined
```

### Steps to reproduce

1. `npm install`
2. `npm run dev`
3. Terminal should be logging the warning.

### System Info

```shell
System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.29 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Firefox Developer Edition: 116.0
    Safari: 16.6
  npmPackages:
    @builder.io/qwik: ^1.2.7 => 1.2.7
    @builder.io/qwik-city: ^1.2.7 => 1.2.7
    undici: ^5.23.0 => 5.23.0
    vite: 4.4.9 => 4.4.9
```

### Additional Information

I think this is related to: https://github.com/BuilderIO/qwik/pull/4873

Digging into the code a little bit, I think the issue comes from the eslint options defined here:
https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/optimizer/src/plugins/eslint-plugin.ts#L30

I can fix this by exposing the `tsconfigFileNames` option here:
https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/optimizer/src/plugins/plugin.ts#L83
and defining something like `{ tsconfigFileNames: ['tsconfig.json', 'tsconfig.app.json'] }` in the vite plugin config.

(I'm happy to put up a PR that exposes this option.)

**Comment by mhevery** [comment]
PR would be great! Go for it!
