### ISSUE TITLE
Playground counter example: clicking Click button increments counter by 2

### ISSUE THREAD

**Issue by dzearing** [BuilderIO/qwik#499]
### Qwik Version

https://qwik.builder.io/examples

### Operating System (or Browser)

MacOS/Safari

### Node Version (if applicable)

n/a

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Judging the code, the counter should increment by 1 when the button callback is executed:

```js
import { component$, useStore } from '@builder.io/qwik';

export const App = component$(() => {
  const store = useStore({ count: 0 });

  return (
    <div>
      <p>Count: {store.count}</p>
      <p>
        <button onClick$={() => store.count++}>Click</button>
      </p>
    </div>
  );
});
```

### Actual Behaviour

Incremented by 2. Note that the first click goes from 0 to 1, but subsequent clicks go from 1 -> 3, 3 -> 5, etc.

There are numerous other issues wrt editting. If you try to add curly brackets around the click handler logic, the app stops rendering and diagostics presents confusing error messages:

```js
TypeError: s.exports.render is not a function at _ (https://qwik.builder.io/repl/repl-sw.js:1:2332) at D (https://qwik.builder.io/repl/repl-sw.js:4:511)
```

**Comment by manucorporat** [comment]
Should be fixed already! Thanks a lot for the PR!
