### ISSUE TITLE
[🐞] Link element and SPA navigation does not work in SSG

### ISSUE THREAD

**Issue by lbensaad** [BuilderIO/qwik#4995]
### Which component is affected?

Qwik Runtime

### Describe the bug

I have a static web site generated by qwik and served by nginx using HTTPS.  
I set domain test.com and subdomain dev.test.com to point to 127.0.0.1 where nginx is runing
When I navigate a Link element in test.com then SPA navigation  works  as expected and there is no page reload. But if I brows in dev.test.com then all Link elements will reload in every click and behaves as MPA.

In the reproduction serving the pages using http-server over HTTP has the same problem. SPA navigation does work, it work as MPA where every click on Link elements reload the page.

### Reproduction

https://github.com/lbensaad/qwik-spa-broken

### Steps to reproduce

Run `pnpm install` then `pnpm dev`  and brows pages A and B you will see that SPA navigation is working as expected.
Now run `pnpm build` followed by `http-server dist` open the website  and you will see that SPA navigation does not work, it is working as MAP with full page reload on each click.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
    Memory: 6.23 GB / 15.59 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Firefox: 116.0.3
  npmPackages:
    @builder.io/partytown: latest => 0.8.0 
    @builder.io/qwik: latest => 1.2.7 
    @builder.io/qwik-city: latest => 1.2.7 
    vite: latest => 4.4.9
```

### Additional Information

For my production web site using nginx and HTTPS, SPA is brown only when served from subdomain like dev.test.com

**Comment by mhevery** [comment]
So I think your example is missconfigured.

https://github.com/lbensaad/qwik-spa-broken/blob/main/adapters/static/vite.config.ts#L15 You set the site to `https://yoursite.qwik.dev/b/` but the URL in the browser is `http://localhost:8080/a`. This fails this check 

https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/runtime/src/qwik-city-component.tsx#L157-L163

The check is there as you can only client-side navigate to the same origin, and in this case, you are going cross-origin.

**Comment by lbensaad** [comment]
ooppss, sorry, thanks, I am closing it.
