### ISSUE TITLE
v1.2.8: 404 for routes when building starter with node-server or express or fastify adapters [🐞]

### ISSUE THREAD

**Issue by jmmon** [BuilderIO/qwik#5020]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I am building the starter after adding the express adapter (also have tested with node-server adapter). 

I expect to be able to serve the build and have routes work properly. 

Actually, the /demo/todolist and /demo/flower routes are both giving me 404 errors. I also get a 404 when making a custom /test route (to make sure it's not due to nesting). This happens on builds utilizing express or node-server adapters.

### Reproduction

https://stackblitz.com/edit/qwik-starter-ltxo4g?file=package.json

### Steps to reproduce

From the repro link, 
- run build and then 
- `node server/entry.express.js` to serve the build. 
- Then click on a link to the todo app or the flower. You'll see it is a 404.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.47 GB / 15.85 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.5.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.4.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.54)
    Internet Explorer: 11.0.19041.1566
```

### Additional Information

I tested with express and node-server. Vhanx on Discord has reported fastify adapter has a similar issue, no routes other than the main index page are working. 

Vhanx confirmed downgrading to 1.2.6 fixed the issue for his fastify adapter.
I've confirmed that downgrading to v1.2.7 fixed the issue for the express adapter.

Something changed probably between 1.2.7 and 1.2.8 which is causing the issue. I was wondering if it has to do with: 
v1.2.8 release notes: "fix(qwik-city): cleanup matchRouteRequest by @gioboa in https://github.com/BuilderIO/qwik/pull/4967"

**Comment by mhevery** [comment]
There was a temporary regression fixed by https://github.com/BuilderIO/qwik/pull/5004 This should be working as soon as we cut a new release.

**Comment by gioboa** [comment]
@jmmon palese try the new 1.2.9 release.
