### ISSUE TITLE
[🐞] Custom 404 page doesn't work

### ISSUE THREAD

**Issue by RaeesBhatti** [BuilderIO/qwik#5030]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I followed the documentation (https://qwik.builder.io/docs/advanced/routing/#custom-404-page) and created a `404.tsx` file in my route and expected it render when my `index.tsx` throws a 404 error. My `404.tsx` file didn't render, instead Qwik showed it's own custom error page.

### Reproduction

https://stackblitz.com/edit/qwik-starter-gkytdd?file=src%2Froutes%2Fmyroute%2F404.tsx

### Steps to reproduce

-  `npm install && npm run dev`
-  Then visit `/myroute/` for that web container.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 20.08 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Firefox: 115.0.2
    Safari: 17.0
  npmPackages:
    @builder.io/qwik: ^1.2.6 => 1.2.6 
    @builder.io/qwik-city: ^1.2.6 => 1.2.6 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.0 => 4.4.0
```

### Additional Information

We're running 3 production Qwik websites and handling different errors correctly within the `index.tsx` rendering logic is really cumbersome.

**Comment by gioboa** [comment]
Thanks for your report, I will look into that

**Comment by RaeesBhatti** [comment]
From my investigation of this, the `getErrorHtml` function gets called when an `ErrorResponse` is encountered.
https://github.com/BuilderIO/qwik/blob/4802cd40e51eef2b0dc653d5bb1bdc36cf012c6b/packages/qwik-city/middleware/request-handler/user-response.ts#L52-L58

But the `getErrorHtml` function itself doesn't take the error page templates like `404.tsx` into account and simple returns the Qwik internal error page.
https://github.com/BuilderIO/qwik/blob/4802cd40e51eef2b0dc653d5bb1bdc36cf012c6b/packages/qwik-city/middleware/request-handler/error-handler.ts#L13-L53

I hope that helps!

**Comment by gioboa** [comment]
I tested the 404 feature and works as expected.
Here is the [404 explanation](https://qwik.builder.io/docs/advanced/routing/#custom-404-page)
Note this particular caveat
>  Note: During `development` and in `preview` mode, the custom `404 pages will not be rendered`, but instead the default Qwik City 404 page will show. However, when building the app for production, the custom 404 page will be statically generated as a static 404.html file.
