### ISSUE TITLE
[✨] yarn 3 compatibility 

### ISSUE THREAD

**Issue by ianlet** [BuilderIO/qwik#5038]
### Is your feature request related to a problem?

Creating a new Qwik project in a Yarn v3 (or v4) workspace with PnP doesn't seem to work because some dependencies (in that case `vite` required by `qwik-city`) are not directly (e.g. non-dev) declared.

Running `yarn start` in a fresh Yarn workspace with PnP yields the following error:
```
failed to load config from /tmp/yarn-workspaces/apps/qwik-app/vite.config.ts
error when starting dev server:
Error: @builder.io/qwik-city tried to access vite, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: vite
Required by: @builder.io/qwik-city@npm:1.2.10 (via /tmp/yarn-workspaces/.yarn/cache/@builder.io-qwik-city-npm-1.2.10-ce870c4cb0-ee342c06a8.zip/node_modules/@builder.io/qwik-city/vite/)
```

### Describe the solution you'd like
Properly declare dependencies in order to support Yarn v3/v4 which has a more strict approach. See [this](https://yarnpkg.com/features/pnp#ghost-dependencies-protection) for more information, especially the info callout.

### Describe alternatives you've considered
Meanwhile, it is possible to configure Yarn with `pnpMode: loose` in order to make it allow "loose" dependencies. Adding this to the `.yarnrc.yml` config file makes the problem mentionned above "go away".

### Additional context
You can reproduce the situation described here with these steps:

1. Create a new Yarn project
```
cd /tmp
mkdir qwik-yarn-workspaces
cd qwik-yarn-workspaces
yarn init
yarn set version stable
yarn install
```

2. Configure Yarn workspaces by editing the `package.json` to add the following configuration:
```
"workspaces": [
  "apps/*"
]
```

3. Create the qwik app:
```
mkdir apps/
cd apps
yarn create qwik
cd qwik-app
yarn install
```

Finally, try to run the app with `yarn start`. This should produce the error above.

```shell
System:
    OS: Linux 6.4 Arch Linux
  Binaries:
    Node: 20.5.1 - /tmp/xfs-27d5cd2e/node
    Yarn: 3.6.3 - /tmp/xfs-27d5cd2e/yarn
    npm: 9.8.0 - ~/.asdf/plugins/nodejs/shims/npm
  Packages:
    @builder.io/qwik: 1.2.10
    @builder.io/qwik-city: 1.2.10
    vite: 4.4.7
    undici: 5.1.6
```

### Additional Information

The dependency `vite` reported here might not be the only one not properly declared. When running PnP in "loose" mode (`pnpMode: loose` in `.yarnrc.yml`), the command `yarn start` works but it logs many dependency issues:

```
(node:177787) [MODULE_NOT_FOUND] Error: vite tried to access supports-color, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:177787) [MODULE_NOT_FOUND] Error: @builder.io/qwik-city tried to access vite, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:177787) [MODULE_NOT_FOUND] Error: @builder.io/qwik-city tried to access undici, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:177787) [MODULE_NOT_FOUND] Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
(node:177787) [MODULE_NOT_FOUND] Error: @builder.io/qwik tried to access vite, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:177787) [MODULE_NOT_FOUND] Error: @builder.io/qwik tried to access eslint, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:177787) [MODULE_NOT_FOUND] Error: eslint-plugin-qwik tried to access @typescript-eslint/utils, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:177787) [MODULE_NOT_FOUND] Error: eslint-plugin-qwik tried to access typescript, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:177787) [MODULE_NOT_FOUND] Error: @builder.io/qwik-city tried to access @builder.io/qwik, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:177787) [MODULE_NOT_FOUND] Error: @mdx-js/mdx tried to access @types/hast, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:177787) [MODULE_NOT_FOUND] Error: @mdx-js/mdx tried to access @types/estree, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:177787) [MODULE_NOT_FOUND] Error: @mdx-js/mdx tried to access source-map, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Comment by gioboa** [comment]
Thanks for the report. @ianlet would you like to create a PR to solve this issue? Thanks in advance

**Comment by ianlet** [comment]
Sure, I'm giving it a try right now.

**Comment by gioboa** [comment]
Thanks, for what I understand this should be a config improvement

**Comment by ianlet** [comment]
Probably! The only thing I am "worried" about is that this specific error (`vite` being required by `qwik-city`) might only be the tip of the iceberg and actually making the whole project "PnP-proof" would be more than just properly declaring this dependency in `qwik-city`.

I'll keep you updated as I go.

**Comment by gioboa** [comment]
Btw I am looking at yarn PnP and I'm trying to understand if it's the standard way to manage yarn projects or it's a specific use case. Maybe you could give me feedback about that

**Comment by ianlet** [comment]
@gioboa I wrote to you on discord, check your DM.

**Comment by ianlet** [comment]
@gioboa I updated the description to document it as an enhancement/feature request rather than a bug.

**Comment by gioboa** [comment]
Thanks @ianlet 🚀
