### ISSUE TITLE
[🐞] Link to navigate between two dynamic route segents with the same base route doesn't reload content of page

### ISSUE THREAD

**Issue by joma1021** [BuilderIO/qwik#5043]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When using Link to navigate between two dynamic route segents with the same base route (e.g. for **article/[slug]:** _.../article/article-1_ and _.../article/article-2_) the content of the page does not rerender. I would expect useResource in the component to reexecute and reload the content based on the changed useLocation().params.

### Reproduction

https://github.com/joma1021/realworld-qwik/tree/bugfix/link-page-reload-issue

### Steps to reproduce

1. create a profile via signup
2. navigate to a different profile via global articles (e.g. click on Anah Benešová): _.../profile/Anah%20Benešová/_
3. click on your profile in the nav bar: _.../profile/yourProfileName/_

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 320.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    npm: 9.8.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
  npmPackages:
    @builder.io/qwik: ^1.2.10 => 1.2.10 
    @builder.io/qwik-city: ^1.2.10 => 1.2.10 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.0 => 4.4.0
```

**Comment by gioboa** [comment]
Can you create a simpler example in stackblitz please?
You can use [qwik.new](https://stackblitz.com/edit/qwik-starter)

**Comment by joma1021** [comment]
https://stackblitz.com/edit/qwik-starter-kjdkjj?file=src%2Froutes%2Farticle%2F%5Bslug%5D%2Findex.tsx

I hop this is working. If i navigate from article-1 to article-2 using the Link component the content is not reloading.

**Comment by claudioshiver** [comment]
@joma1021 there are two issues in your code. first you need to get at least the params object and not directly the slug. so `const { params } = useLocation();` will work but `const slug = useLocation().params.slug;` will not. then useResource$ callback has a track method so you need to do something like:

```
const article = useResource$<string>(async ({ track }) => {
    track(() => params.slug);
    return (params.slug === '1') ? 'article-1' : 'article-2';
  });
```

**Comment by claudioshiver** [comment]
@mhevery @gioboa i think you can close this issue

**Comment by gioboa** [comment]
Thanks 👍
