### ISSUE TITLE
[✨] Exposing `matchRoute` from qwik-city

### ISSUE THREAD

**Issue by jessezhang91** [BuilderIO/qwik#5053]
### Is your feature request related to a problem?

In this PR https://github.com/BuilderIO/qwik/pull/4954, the interface of routes defined in `@qwik-city-plan` changed from the first element being a RegExp to a string (which uses `matchRoute` to test if a provided pathname matches the route).

For our site, we were using the RegExp to test request pathnames in Express so that we can glean information about the matched page module outside of the qwik-city middleware (more info on why we're doing this below).

To continue doing this, we will now need `matchRoute` exposed so that we can use that to test pathnames where before we just used the RegExps.

---

The long story:
For our [website](https://orchard.com/), we are using the qwik express middleware, [apicache-plus](https://www.npmjs.com/package/apicache-plus) for server-side caching, and [GrowthBook](https://github.com/growthbook/growthbook) for A/B testing. We managed to cobble together something with `apicache-plus` (which supports the streaming output from qwik-city while `apicache` does not) and GrowthBook to cache rendered variants of pages so that subsequent requests that match the same GrowthBook features will be served immediately and can bypass the qwik-city middleware altogether and achieve the best TTFB possible.

This had been working great but then we started running so many experiments at once that there ended up being too many variants and the cache hit ratio plummeted to practically 0. Our site's TTFB measurably increased because of this. Since we only really cared about certain features per route/page, we could improve the cache hit ratio by defining an allowlist of features manually per route and compute the cache key only based on those features (rather than all features).

The simple solution would have been to just define a mapping of pathnames to feature allowlist and just have all of this live outside of qwik and qwik-city. However, we thought it would be better DX to define this allowlist directly in the qwik route/page module. We traced through how `DocumentHead` works and realized if we just added another exported constant, it would show up in the `@qwik-city-plan` route modules! (We recognize this is likely a not supported functionality that can change at any time but we figured we would ask about that when that happened 😇.) Plus the route definitions had a RegExp right there for us to test pathnames.

So, we created a little utility function that would extract the route/page module from the `@qwik-city-plan` given a path:
```
import type { Component } from '@builder.io/qwik';
import type { DocumentHead } from '@builder.io/qwik-city';
import qwikCityPlan from '@qwik-city-plan';

export interface QwikPageModule {
  default: Component<any>;
  head: DocumentHead;
  growthBookFeatures?: string[];
}

type QwikPageModuleFn = () => QwikPageModule;
type QwikRoute = [RegExp, [...unknown[], QwikPageModuleFn], ...unknown[]];

export function getQwikPageModule(path: string): QwikPageModule | undefined {
  const matchingRoute = (qwikCityPlan.routes as QwikRoute[]).find((route) => {
    return route[0].test(path);
  });
  if (matchingRoute == null) {
    return;
  }

  const moduleFns = matchingRoute[1];
  const pageModuleFn = moduleFns[moduleFns.length - 1] as QwikPageModuleFn;
  return pageModuleFn();
}
```
and this pushed our cache hit ratios back into a happy state (and for pages we don't do any testing on, made it even better!).

Very long story short, I would like to have `matchRoute` exported so that I can replace `route[0].test(path)` with `matchRoute(route[0], path)` so that we can continue doing what we're doing 😅.

### Describe the solution you'd like

Export `matchRoute` from `@builder.io/qwik-city`

I'm happy to put up a PR for this.

### Describe alternatives you've considered

The simplest alternative is to just not do what I'm doing 😄 since I'm relying on probably "private interfaces/APIs" and whatnot but this way does give the best DX!

I have spent a little time thinking if this is possible by using qwik plugins rather than outside of qwik but I think to get the best cache response performance, it would have to happen before the qwik-city middleware attempts to process the request. If there was a way to plug into the qwik-city middleware to short-circuit and return cached results based on some dynamic input parameters, that would solve my problem as well but I think that's a way more complex framework change.

### Additional context

Thank you for reading perhaps far too much context than needed. As an aside, if any of this caching and A/B testing stuff is interesting, I would be more than happy to chat more about this part of our implementation and potentially even see how we can incorporate learnings from this into qwik-city or as a separate module.

**Comment by mhevery** [comment]
> The simplest alternative is to just not do what I'm doing 😄 since I'm relying on probably "private interfaces/APIs" and whatnot but this way does give the best DX!

Yeah, this is private....  🤔 

Weary of exposing that functionality. 

Could you just copy this [file](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/runtime/src/route-matcher.ts) into your codebase? There may be some bug fixes from time to time, but it is unlikely to change drastically.

**Comment by jessezhang91** [comment]
Oh, that's a very good point. I completely failed to realize that all of the functionality is contained in that file. I will do exactly that, thanks!

**Comment by mhevery** [comment]
Perfect!
