### ISSUE TITLE
[🐞] CORS: request to a different origin

### ISSUE THREAD

**Issue by Emt-tz** [BuilderIO/qwik#5056]
### Which component is affected?

Qwik Runtime

### Describe the bug

i am doing a normal javascript fetch function defined like 
```
static sendSms = (async (number: string, message: string = ".") => {
        const token = await this.login()
        if (token !== "") {
            const response = await fetch('https://apis/', {
                method: 'POST',
                headers: {
                    "Authorization": `Bearer ${token}`,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    "to": number,
                    "from": "",
                    "content": message,
                }),
            });
            if (response.ok) {
                const data = await response.json();
                return data;
            } else {
                throw new Error('Failed to push sms');
            }
        } else {
            throw new Error('Failed to push sms');
        }
    })```

but i am always getting this issue here 
```
Access to fetch at 'https://apis/' from origin 'https://domain.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
The same api works on postman.

### Reproduction

https://ohs-health.org/sms

### Steps to reproduce

_No response_

### System Info

```shell
Browsers Chrome, also Localhost and Cloudflare server
```

**Comment by gioboa** [comment]
Hi @Emt-tz , this issue is not related to Qwik but the browser is blocking your request because usually allows a request in the same origin for security reasons. btw your issue doesn't have a title, please add a comprehensive title next time.
Please post your question on the [Discord help chat](https://discord.com/channels/842438759945601056/1046929728948408370) I'm more then happy to help you.

**Comment by Emt-tz** [comment]
Okay i have asked a question there

**Comment by gioboa** [comment]
Thanks @Emt-tz
