### ISSUE TITLE
[🐞] Tracking DOM Element reference causes QWIK WARN Serializing dirty task

### ISSUE THREAD

**Issue by ilianiv** [BuilderIO/qwik#5067]
### Which component is affected?

Qwik Runtime

### Describe the bug

1. Get a signal of DOM element ref
2. track() the signal.value in useTask$()
3. A server warning occurs: `QWIK WARN Serializing dirty task. Looks like an internal error.`
4. Doesn't execute the useTask$ when the reference signal gets changed

### Reproduction

https://stackblitz.com/edit/qwik-starter-f1bgnu?file=src%2Froutes%2Findex.tsx,package.json

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.2.10 => 1.2.10 
    @builder.io/qwik-city: ^1.2.10 => 1.2.10 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

### Additional Information

If you change the initial value of `const shown` to `false` (const shown = useSignal(false)) everything works ok.

**Comment by mhevery** [comment]
Simpler reproduction:
```typescript
import { component$, useSignal, useTask$ } from "@builder.io/qwik";

export default component$(() => {
  const ref = useSignal<HTMLElement>();

  useTask$(({ track }) => {
    track(() => ref.value);
    console.log("H1 tracked", ref.value);
  });
  return (
    <>
      <h1 ref={ref}>TEST</h1>
    </>
  );
});
```

**Comment by mhevery** [comment]
## OK here is what is happening.

- The `useTask$` tracks `ref`. 
- The task runs before JSX and sets up a subscription on `ref`
- The component is rendered, and the `ref` is updated with `MockElement` (since SSR). This update marks the task as dirty.
- During serialization the `QWIK WARN Serializing dirty task. Looks like an internal error.` is shown because we are serializing a task that is dirty (Task needs to re-run) But during SSR we don't re-run tasks.

## Solution

It is not clear to me what the right solution is. Here are the options:
- Suppress error, but that is kind of wrong since the task is dirty and needs to re-run. For example, during CSR you would expect the task to run twice. Once with `ref` of `null` and once when `ref` gets set. But in the case of SSR the second execution of the task is swallowed by the serializer. One can't eagerly execute the tasks on the client as this is not a `useVisibleTask$`
- Logically one would expect that the task runs twice. Once during initialization as part of SSR and then eagerly on the client once the `ref` is set to the actual DOM references. So is this another way to run code eagerly??? I don't like that idea since in wast number of cases we are only interested when `ref` changes not when it is deserialized.


🤔 


# Workaround

1. Ignore the error....
2. Use `useVisibleTask$` when you want to track if the element changes and want to be eagerly notified about the change.

**Comment by devcaeg** [comment]
> ## OK here is what is happening.
> * The `useTask$` tracks `ref`.
> * The task runs before JSX and sets up a subscription on `ref`
> * The component is rendered, and the `ref` is updated with `MockElement` (since SSR). This update marks the task as dirty.
> * During serialization the `QWIK WARN Serializing dirty task. Looks like an internal error.` is shown because we are serializing a task that is dirty (Task needs to re-run) But during SSR we don't re-run tasks.
> 
> ## Solution
> It is not clear to me what the right solution is. Here are the options:
> 
> * Suppress error, but that is kind of wrong since the task is dirty and needs to re-run. For example, during CSR you would expect the task to run twice. Once with `ref` of `null` and once when `ref` gets set. But in the case of SSR the second execution of the task is swallowed by the serializer. One can't eagerly execute the tasks on the client as this is not a `useVisibleTask$`
> * Logically one would expect that the task runs twice. Once during initialization as part of SSR and then eagerly on the client once the `ref` is set to the actual DOM references. So is this another way to run code eagerly??? I don't like that idea since in wast number of cases we are only interested when `ref` changes not when it is deserialized.
> 
> 🤔
> 
> # Workaround
> 1. Ignore the error....
> 2. Use `useVisibleTask$` when you want to track if the element changes and want to be eagerly notified about the change.

As additional information, if instead of doing "track(() => ref.value);" you do "track((() => ref);" the error disappears and everything runs normally (apparently).

**Comment by ilianiv** [comment]
I appreciate your explanation, @mhevery, but none of the workarounds seem sufficient.
`1. Ignore the error....` - I can't ignore it because it never again executes the useTask$ block despite the fact that ref.value is tracked. I think this is a bug.
`2. Use useVisibleTask$` - Isn't delaying client-side code execution the main goal of QwikJS? In my example, I don't immediately need the correct reference, but once the button is pressed.

**Comment by mhevery** [comment]
> I appreciate your explanation, @mhevery, but none of the workarounds seem sufficient.

Yes, I agree with you this is a bug. A workaround is something you can do until a proper solution is found. Sorry if none of the workarounds fit your needs.

> `1. Ignore the error....` - I can't ignore it because it never again executes the useTask$ block despite the fact that ref.value is tracked. I think this is a bug.
I agree, it is a bug... I just don't have a good solution...

> `2. Use useVisibleTask$` - Isn't delaying client-side code execution the main goal of QwikJS? In my example, I don't immediately need the correct reference, but once the button is pressed.

Can you track the button pressing rather than the ref?

**Comment by ilianiv** [comment]
Thank you, @mhevery. I just wanted to confirm that this is a bug.

**Comment by mhevery** [comment]
> using `useComputed$` also gives this error in a similar way, like in this following code:
> 
> ```ts
>     const swiper = useSignal<Element & { swiper: SwiperClass }>();
>     const active = useComputed$(() => swiper.value ? swiper.value!.swiper.activeIndex : 0)
> ```

yes, it is the same issue. `useCompute` and `useTask` are essentially the same under the hood.

**Comment by damianpumar** [comment]
can I take this issue and try to solve it  @mhevery ?

**Comment by gioboa** [comment]
Yep @damianpumar let's go for it. thanks 💪

**Comment by mhevery** [comment]
> can I take this issue and try to solve it @mhevery ?

Yes, but let's discuss the solution first. I don't think there is an easy fix, so I don't want you to spend time on a solution that will not be mergeable into a repo.

**Comment by wmertens** [comment]
Since this is a special and desired case, would it not be ok to suppress the error if the task is dirty only because of MockElement signals?

The task does run on the client once the ref is populated, right? So this is useful to run server setup and client setup in one hook?

@devcaeg your workaround doesn't actually set up a listener, so the task isn't dirty.

**Comment by wmertens** [comment]
Also, the error would better be "Task needs rerunning due to tracked signals. This is impossible during SSR and should not be allowed to happen."

**Comment by mhevery** [comment]
yeah, it is not clear to me what the "correct" solution is...

**Comment by damianpumar** [comment]
Hi team! I was thinking how to tackle this issue, and after a lot of tests I have one idea:
- Put a warning before the actual one just to inform the developer to use the "useVisibleTask$" only for element ref.

I don't know how to re-run the dirty task for refs... in case that you don't agree with this solution, I'd like to do a pair programming with anyone of you to review other solution.

Many thanks!

**Comment by wmertens** [comment]
@mhevery how about populating refs during SSR using untrackedValue? Then tasks won't rerun but the serializer still works

**Comment by mhevery** [comment]
> @mhevery how about populating refs during SSR using untrackedValue? Then tasks won't rerun but the serializer still work

This is not about the warning, but rather what should happen if the value changes after it has been rendered? In this case the ref changes after the value renders. So if you are tracking it than the code does not re-run neither on server nor on client. We  lose one transition....

**Comment by wmertens** [comment]
@mhevery but for refs specifically, we know that they can only be useful in the client, and they are connected at the end of the SSR? So it doesn't make sense to react on them?

**Comment by mhevery** [comment]
> @mhevery but for refs specifically, we know that they can only be useful in the client, and they are connected at the end of the SSR? So it doesn't make sense to react on them?

I think it does make sense to react to them, but on the client only???

**Comment by wmertens** [comment]
I'm confused :) so in the particular case of refs being assigned to signals during SSR, they don't have to cause tasks to rerun, right? 

So in that particular case, they shouldn't mark listening tasks as dirty during SSR?

**Comment by wmertens** [comment]
@mhevery sorry forgot to tag you above

**Comment by mhevery** [comment]
Well depends on how you look at it. When you have a unified execution model then a setting of a ref should cause `useTask` to rerun. The question is where? At the server or at the client? Arguments can be made for both.

**Comment by wmertens** [comment]
On the server is impossible when the element was already emitted...

**Comment by devcaeg** [comment]
Any update?

For now the alternative is to use "useVisibleTask$" or use "useTask$" with "eagerness" in "load" or "visible".

**Comment by damianpumar** [comment]
I think we don't have any update about this issue. I have time to review it, but I need some help from you guys, so I don't know if you @wmertens have time to review as a pair programming, maybe together we can fix it.

Thanks!

**Comment by wmertens** [comment]
I think this is fixed by #5741

**Comment by gioboa** [comment]
> Simpler reproduction:
> 
> ```ts
> import { component$, useSignal, useTask$ } from "@builder.io/qwik";
> 
> export default component$(() => {
>   const ref = useSignal<HTMLElement>();
> 
>   useTask$(({ track }) => {
>     track(() => ref.value);
>   });
>   return <h1 ref={ref}>TEST</h1>;
> });
> ```

I tested this example in the playground and Qwik 1.4.4 solves it.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you. Thanks.

**Comment by intellix** [comment]
does this error still occur when using something like this instead?

```ts
useOnDocument(
  'load',
  $(() => {
    const ref = store.contentRef;
    if (!ref || store.firstLoad) return;
    store.firstLoad = true;
    ref.style.maxHeight = ref.scrollHeight + 'px';
  })
);
```
