### ISSUE TITLE
Optimizer inlines large blobs of styles

### ISSUE THREAD

**Issue by jaroel** [BuilderIO/qwik#5069]
The optimizer inlines css below a certain length/size, which is awesome for "small" stuff. I use tailwind and it adds quite a bit, but apparently not enough :)

https://github.com/BuilderIO/qwik/blob/86a9452be1572c84868a5ebee3ad417cf304b70f/packages/qwik/src/optimizer/src/plugins/vite.ts#L463

Changing the setting from 20000 to 200 makes my global.css a separate file again.
-rw-r--r--@ 1 roel  wheel  26671 Aug 31 12:17 /tmp/2e2.html
-rw-r--r--@ 1 roel  wheel  40947 Aug 31 12:17 /tmp/2e4.html

I personally could try to not use global.css/tailwind, maybe use pandacss instead. Maybe make the 20000 configurable?

Any other opinions?

**Comment by jaroel** [comment]
I spent an good hour setting checkout up and trying to figure out where I need to add something like `inlineStylesUpToBytes: 20000` as a default value.

Please point me to where I need to add `some key` and `some default value ` to `some type`, so tsc will actually help me.

**Comment by mhevery** [comment]
I am not a vite expert so I don't know of the top of my head. 

Have you tried adding the option to `QwikVitePluginOptions` and than reading from that instead of hard coding it to 20000
