### ISSUE TITLE
[🐞] Stackblitz template (qwik.new) does not work with server$

### ISSUE THREAD

**Issue by fabiobiondi** [BuilderIO/qwik#5076]
### Which component is affected?

StackBlitz Template (  [https://qwik.new/](Qwik.new) )

### Describe the bug

I'm trying to create an example on Stackblitz to demonstrate how `server$` works but I got errors using the template provided by the [https://qwik.new/](Qwik.new) url.

This is a simple snippet that generates the error:

```tsx
import { component$, useSignal } from '@builder.io/qwik';
import { server$ } from '@builder.io/qwik-city';

export const loadUsers = server$(async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  return res.json();
});

export default component$(() => {
  const totalUsers = useSignal(0);

  return (
    <>
      <button
        onClick$={async () => {
          const res = await loadUsers();
          console.log('client', res.length);
          totalUsers.value = res.length;
        }}
      >
        LOAD USERS: {totalUsers.value}
      </button>
    </>
  );
});
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-eao3pt?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

To reproduce the problem just click the "LOAD USERS" button.

I get this error:

```
out2Clone.tee is not a function or its return value is not iterable
```

### System Info

```shell
Qwik version: 1.2.10
```

### Additional Information

I'm not sure but it seems related to the NodeJs version used in StackBlitz (v.16) and/or `undici` package

### Error screenshot

![image](https://github.com/BuilderIO/qwik/assets/1772083/263ba85e-10a5-4e5d-bcbe-236317d1f367)

**Comment by mhevery** [comment]
This requires that SB be upgraded to the latest node... They are in the progress of fixing it.

**Comment by fabiobiondi** [comment]
Thank you for the info, Misko

**Comment by mhevery** [comment]
https://github.com/stackblitz/webcontainer-core/issues/1172

I am going to close this as there is nothing for Qwik team to do other than wait for SB to fix their side...

**Comment by SamVerschueren** [comment]
This is now fixed https://stackblitz.com/edit/qwik-starter-bzygwv?file=src%2Froutes%2Findex.tsx 🙏 .
