### ISSUE TITLE
onFocusIn$ / onFocusin$ doesn't work, likely due to spelling mismatch

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/qwik#508]
### Qwik Version

0.0.20-7

### Operating System (or Browser)

OSX

### Which component is affected?

Qwik Runtime

### Expected Behaviour

`onFocusIn$` works

### Actual Behaviour

It doesn't.

### Additional Information

I suspect this is because of a capitalization mismatch:

`onFocusIn$` in `manifest.ts`

`onFocusin$` in `jsx-qwik-attributes.ts`

The `I` is cap in one, lowercase in the other. From a few spot checks, it appears the spelling usually exactly matches between various references to an event.

I'm happy to do a PR, ideally if I knew:

Which spelling is preferred?

What is an appropriate test? Testing this specific event seems outside the point of handling all events generically; I thought about a test that verifies the spelling of each event matches between these two lists. Or I thought about not testing it, since it's a typo fix.

**Comment by manucorporat** [comment]
When you mean it does not work, you meant the event is not dispatched? can you provide a small piece of code that reproduces the issue?

I think types should not affect runtime behaviour, which does not mean there is not another bug in the types

**Comment by kylecordes** [comment]
(In the two days since I wrote the above, @adamdbradley enhanced the playground to keep the state in the URL!)

**Comment by Varixo** [comment]
Now it works, thanks to the playground we can easily verify that this was fixed in 0.0.109.
```tsx
import { component$, useStore } from '@builder.io/qwik';

export const App = component$(() => {
  const state = useStore({ name: "World" });
  return (
    <div class="my-app p-20">

      <h1 class="text-3xl mb-2">Congratulations Qwik is working!</h1>

      <p>Open the console then click in to each input.</p>

      <p><input onFocus$={() => console.log("onFocus$")} /></p>

      <p><input onFocusIn$={() => console.log("onFocusIn$")} /></p>

      <p><input onFocusin$={() => console.log("onFocusin$")} /></p>

      <p>Verify the underlying onfocusin works:</p>
    </div>
  );
});
```
 I think we can close this issue?

**Comment by zanettin** [comment]
thx @Varixo for your check. hope @kylecordes can confirm it? if so, feel free to close the issue 🙏

**Comment by manucorporat** [comment]
Amazing! closing
