### ISSUE TITLE
[🐞] Unable to use `import()` function. 

### ISSUE THREAD

**Issue by samyosm** [BuilderIO/qwik#5100]
### Which component is affected?

Qwik Runtime

### Describe the bug

When attempting to import a file within a route loader using the import() function, the functionality operates correctly when executing npm run dev. However, it encounters an error when running npm run preview.

Here is the relevant code snippet:

```js
import { component$ } from "@builder.io/qwik";
import { routeLoader$, type DocumentHead } from "@builder.io/qwik-city";

export const useLoader = routeLoader$(async () => {
  import('/README.md');
});

export default component$(() => {
  return (<> </>);
});
```

Here is the error I am getting:
```shell
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/projects/qwik-starter-tgvuqv/server/assets/@qwik-city-not-found-paths.js' imported from /home/projects/qwik-starter-tgvuqv/server/assets/README-3974460e.mjs
    at get (https://qwikstartertgvuqv-01i1.w-corp.staticblitz.com/blitz.33975f1d.js:67:7048)
    at triggerUncaughtException (https://qwikstartertgvuqv-01i1.w-corp.staticblitz.com/blitz.33975f1d.js:334:379081)
    at processPromiseRejections (https://qwikstartertgvuqv-01i1.w-corp.staticblitz.com/blitz.33975f1d.js:249:3749)
    at processTicksAndRejections (https://qwikstartertgvuqv-01i1.w-corp.staticblitz.com/blitz.33975f1d.js:111:1108)
    at _0x586465 (https://qwikstartertgvuqv-01i1.w-corp.staticblitz.com/blitz.33975f1d.js:329:278733) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
#### Notes

When I try to import Markdown files, the bug only occurs when importing from outside `src/routes` and when the file imported isn't `index.{md, mdx, tsx, ts}`.

### Reproduction

https://stackblitz.com/edit/qwik-starter-tgvuqv?file=src%2Froutes%2Findex.tsx&view=editor

### Steps to reproduce

1. Run `npm run dev` and notice the application works.
2. Run `npm run preview` and notice the application break.

### System Info

```shell
  System:
    OS: Linux 6.4 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 10.89 GB / 15.35 GB
    Container: Yes
    Shell: 3.6.1 - /bin/fish
  Binaries:
    Node: 18.17.1 - ~/.local/share/nvm/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.local/share/nvm/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.local/share/nvm/v18.17.1/bin/npm
    pnpm: 8.6.12 - /usr/bin/pnpm
  Browsers:
    Chromium: 115.0.5790.170
  npmPackages:
    @builder.io/qwik: ^1.2.10 => 1.2.10 
    @builder.io/qwik-city: ^1.2.10 => 1.2.10 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7 
```

### Additional Information

Similar to #4426, but hasn't been solved.

**Comment by shairez** [comment]
Thanks @samyosm 

Can you please describe the use case you have for trying to import the README? Or something alike?

**Comment by samyosm** [comment]
Instead of using a headless CMS, I thought of using plain markdown files for content management. 

In QwikJS, however, I find it cumbersome to have each post be under a directory. For me, it poses three issues:

- Directory names were long
- I don't necessarily want each post to have the same URL as the directory name. I would rather have the slug be markdown metadata
- I18n was troublesome

To solve these issues, I thought of having all posts under a directory. Then use vite dynamic imports to fetch a post based on a dynamic route ID. 

Note: I don't want to import the `README.md`, it was just for the minimal reproduction.

**Comment by mhevery** [comment]
It sounds like you want to implement your own router on top of Qwik. 🤔 Possible, but it is a lot of work....

So in your case, `import` in dev mode works because Vite serves up all of the files. In production, there is no vite and files don't get served hence the error you see. 

I think the way I would do this is to create a Vite plugin which will place all of the files `md` files into an object like this;

```typescript
// File generated by vite plugin
export const mdFiles =  {
  '/my.md': $(`content of my.md`),
  '/other.md': $(`content of other.md`),
};
```

In your code, you can then read any file as `await mdFiles['/my.md']` etc...


I don't think there is an action for the Qwik team, so I would like to close this issue, if it is ok with you.

**Comment by samyosm** [comment]
I can see that creating a vite plugin might be hard, but I'm ready to do it if you think my issue isn't related to the Qwik framework.

PS: May I know the difference between:

```js
export const mdFiles =  {
  '/my.md': $(`content of my.md`),
  '/other.md': $(`content of other.md`),
};
```

and 

```js
export const mdFiles =  {
  '/my.md': `content of my.md`
  '/other.md': `content of other.md`,
};
```

and why you think that the former is needed?

**Comment by samyosm** [comment]
Actually, never mind. I found it to be possible without creating a custom plugin. That is, by using [eager imports](https://vitejs.dev/guide/features.html#glob-import-as).

_I leave here want I've done to help those who might have a similar problem._

For example:
```ts
// Fetch
export const useLoader = routeLoader$(async () => {
  const modules = import.meta.glob('/src/posts/*.md', { eager: true });

  const posts: any[] = [];

  for (const path in modules) {
    // @ts-ignore
    const post = modules[path].default().children.type();
    posts.push(post)
  }

  return posts;
});

// Display
export default component$(() => {
  const data = useLoader();
  return (
    <div>
      {data.value.map(t => <>{t}</>)}
    </div>
  )
});
```

If you really wanted to, you could also import individual files using [raw imports](https://vitejs.dev/guide/assets.html#importing-asset-as-string):

```ts
const post = await import('/src/posts/hello.md?raw');

// Dynamic
const post = await import('/src/posts/{file}.md?raw');
```

I'm not sure if you are willing to take action on this, so I leave the decision of closing this issue the staff.

**Comment by gioboa** [comment]
I close this issue because that's a nice solution. Thanks for sharing @samyosm
