### ISSUE TITLE
[✨] Allow Signal<string | undefined | null> for bind:value on inputs

### ISSUE THREAD

**Issue by meenie** [BuilderIO/qwik#5101]
### Is your feature request related to a problem?

I'm working with Supabase and when you query for data on a string field that is allowed to be null, the generated types from Supabase set the field type to `string | null`.  I can't set the field directly to `bind:value` because it is always expecting `Signal<string | undefined>` so I have to keep converting them back and forth.

### Describe the solution you'd like

Set the type for `bind:value` to `Signal<string | undefined | null>`

### Describe alternatives you've considered

My only other alternative without having to have the conversion code is to not use `bind:value` and keep the signal up-to-date using an `onInput$` callback.

**Comment by mhevery** [comment]
```typescript
  const opacity = useSignal(0.5);
  return (
    <div>
      Opacity:{" "}
      <input
        type="range"
        min="0"
        max="1"
        step="0.05"
        value={opacity.value}
        onInput$={(e) =>
          (opacity.value = (e.target as HTMLInputElement).valueAsNumber)
        }
      />{" "}
      <input type="range" min="0" max="1" step="0.05" bind:value={opacity} />{" "}
        //                                            ^^^^^^^^^^
       // Type 'Signal<number>' is not assignable to type 'Signal<string | undefined>'.
       //   Types of property 'value' are incompatible.
      //     Type 'number' is not assignable to type 'string'.ts(2322)
      {opacity.value}
      <Child opacity={opacity.value} />
    </div>
  );
```

This is because `bind:value` is a macro expands to
```typescript
      <input
        value={opacity.value}
        onInput$={(e, t) => (opacity.value = t.value)}
      //                     ^^^^^^^^^^^^^
      // Type 'string' is not assignable to type 'number'.ts
      />
```


As such the macro has no understanding of types. It just assumes `.value`, which is a string.

I think this is a `Won't Fix` as there is no easy way for the `bind:value` macro to know what the right thing to do is.

**Comment by mhevery** [comment]
I am going to close this as won't fix, to keep the repo clean, but feel free respond and or discuss this here..
