### ISSUE TITLE
[✨] Support as a MFE

### ISSUE THREAD

**Issue by jthibodeauCrakmedia** [BuilderIO/qwik#5108]
### Is your feature request related to a problem?

Actually, Qwik is an **_awesome_** project for an integral website.

The problem is that what if we want to use multiple small part of the HTML-first framework?

### Describe the solution you'd like

- Support standalone MFE that have an entry bundle js for the client that easily map the chunks. 
- SSR is supported.
- Client files can be transpilled for browser compatibility via configuration. ex: SystemJS, RequireJS, etc.

### Describe alternatives you've considered

We actually tried an approach to make it as a component but it didn't work when we tried to access it via MFE approach.

Actual generated code as part standalone: 
![image](https://user-images.githubusercontent.com/67754779/219696994-f887c689-02c3-4625-98f7-b91d3950e65e.png)

### Additional context

Regarding this request, we want to integrate that feature with the [ILC namecheap](https://github.com/namecheap/ilc) ecosystem.

Reopen https://github.com/BuilderIO/qwik/issues/3015

**Comment by mhevery** [comment]
`demand` ??? You mean `reqest`??? 😄

**Comment by mhevery** [comment]
So it is not clear to me what you are asking. It seems like a very generic request. What specific issue can we fix to enable this for you?

We have a MFE demo here: https://github.com/gioboa/qwik-dream-demo

**Comment by jthibodeauCrakmedia** [comment]
This _request_ was to generic and not clear at all. I'll close it! Thanks

**Comment by mhevery** [comment]
> This _request_ was to generic and not clear at all. I'll close it! Thanks

Happy to help you through any specific issues. Just let us know.
