### ISSUE TITLE
[✨] add `resolved` prop to QRL objects

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#5117]
### Is your feature request related to a problem?

Often when working with QRL functions, they are just `$()` wrapped synchronous functions and once they loaded they are always loaded.

It would be nice to be able to get the resolved value without having to await it, in cases where you are sure that the QRL is loaded.

### Describe the solution you'd like

Add a `.resolved: undefined | T` prop to `QRL<T>`, which gets the resolved value when `resolve()` completes.

Suppose you have this recursive function:

```js
const fib = n => n > 1 ? (fib(n-1)+fib(n-2)) : 1
```

To make it a QRL you would have to make it be
```js
const __ref = {}
__ref.fib$ = $(async () {const fib = await fib$.resolve(); return n > 1 ? (fib(n-1)+fib(n-2)) : 1 })
const {fib$} = __ref
```

and with this proposal it could instead be
```js
const __ref = {}
__ref.fib$ = $(() {const fib = fib$.resolved; return n > 1 ? (fib(n-1)+fib(n-2)) : 1 })
const {fib$} = __ref
```

Which is safe, since when the function runs, it was already loaded.

### Describe alternatives you've considered

See the await example above.

**Comment by mhevery** [comment]
I think that is a great idea!

**Comment by wmertens** [comment]
@mhevery I gave it a quick try, does that look plausible?
