### ISSUE TITLE
[✨] RequestEvent is not available in qwik-auth (credentials provider)

### ISSUE THREAD

**Issue by Aslemammad** [BuilderIO/qwik#5123]
### Is your feature request related to a problem?

> I'm not sure if this is a bug or a feature, but something's missing. 

In the [Credentials](https://authjs.dev/reference/core/providers_credentials) provider of Authjs, there's an `authorize` function. And the second parameter is the request object. Currently there's no way to access the parent RequestEvent object for it so we can pass it to the database instantiator. 
So I tried coming up with a hack. 

```ts
const requestMap = new WeakMap<Request, RequestEvent>()

export const { onRequest: _onRequest, useAuthSession, useAuthSignin, useAuthSignout } =
  serverAuth$(({ env }) => ({
    secret: env.get("AUTH_SECRET"),
    trustHost: true,
    providers: [
      Credentials({
        id:'credentials',
        name: "Credentials",
        credentials: {
          email: { label: "Email", type: "text" },
          password: { label: "Password", type: "password" },
        },
        async authorize(credentials, _req) {
          const req = requestMap.get(_req)
          if (!req) {
            throw new Error('An impoosible case')
          }
          const { db } = createClient(req)
          console.log(db)
        },
      }),
    ] as Provider[],
  }));

export function onRequest(req: RequestEvent) {
  requestMap.set(req.request, req)
  return _onRequest(req)
}

```
Where I create a (Weak)Map out of the native request and their RequestEvent holders. 
But it didn't work and the `An impoosible case` appears. And the reason is that the request object that gets passed to Authjs is created before passing, and there's no way to access it.

https://github.com/BuilderIO/qwik/blob/bd130b603ec67ed8e3a9478927dbb6f94b483558/packages/qwik-auth/src/index.ts#L133C1-L138C1

### Describe the solution you'd like

Passing the same `req.request` to Authjs somehow so we can have access to the same native request object as the one in the RequestEvent.

### Describe alternatives you've considered

There may be an alternative solution, I'd like to see if there's a better one. Only this hack came to my mind.

**Comment by gioboa** [comment]
Thanks @Aslemammad for your report. [Here is](https://github.com/BuilderIO/qwik/blob/bd130b603ec67ed8e3a9478927dbb6f94b483558/packages/qwik-auth/src/index.ts#L29) the implementation. Would you like to drop a PR for this?

**Comment by Aslemammad** [comment]
Sure, why not? Let me do so!

**Comment by Aslemammad** [comment]
Funny, There was no need to re-implement anything, by reading the code for finding a solution, I found out the `serverAuth$` already gives access to the RequestEvent object which solves this issue.

```ts
  serverAuth$((req) => ({
    secret: req.env.get("AUTH_SECRET"),
    ...
```

**Comment by gioboa** [comment]
Nice 👍
