### ISSUE TITLE
[🐞] qwik optimizer vite plugin should probably use rollup cache internally

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#5125]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

The playground wasn't working because rollup was using cached versions of transformed files, which meant that between invocations, the `(ssr)transformedOutputs` maps weren't populated.

See https://github.com/BuilderIO/qwik/pull/5124

So probably the vite plugin should use the rollup cache instead of having internal Map()s

### Reproduction

just the playground :)

### System Info

```shell
n/a
```

**Comment by mhevery** [comment]
Resolved in https://github.com/BuilderIO/qwik/pull/5124

**Comment by shairez** [comment]
nice catch @wmertens !
