### ISSUE TITLE
[🐞] Qwik City - Mixed dynamic and static routing segments no longer match expected URL paths

### ISSUE THREAD

**Issue by maxrpeterson** [BuilderIO/qwik#5126]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I have a use case for a mix of dynamic route segments and static route segments. This routing used to work as of Qwik/Qwik City v1.2.7, but as of >=1.2.8 the same exact routes now result in a 404 page.

Given a page route like the following is created:
```
src/routes/[...dynamicOne]/static-segment/[...dynamicTwo]/index.tsx
```

I expect visiting a URL like the following will render that page:
```
http://localhost:5173/abc/xyz/static-segment/more-dynamic-123/
```

In addition to the StackBlitz I created and linked below which demonstrates the bug, I created a repo with Qwik and Qwik City locked to 1.2.7 in order to demonstrate that this used to work. [Check out that repo here.](https://github.com/maxrpeterson/qwik-city-routing-bug-working/)

### Reproduction

https://stackblitz.com/edit/qwik-starter-6z4lzr?file=README.md

#### On the StackBlitz:
- once the linked StackBlitz page loads, ensure latest Qwik & Qwik City were installed:
  `npm ls @builder.io/qwik @builder.io/qwik-city`
- visit a path like `/abc/xyz/static-segment/more-dynamic-123/` and notice that the expected page is not rendered and the 404 page is rendered instead

**NOTE** for the StackBlitz app, the 404 page seems to only render on Chrome, on other browsers tested (Firefox, Safari, Edge) there is a syntax error that happens when visiting the example route. If you update Qwik & Qwik City to >=1.2.8 in the [working example app](https://github.com/maxrpeterson/qwik-city-routing-bug-working/) and load the example route in those other browsers, the 404 page is rendered without the syntax errors.

#### On [the example repo](https://github.com/maxrpeterson/qwik-city-routing-bug-working/) where this route is **working**:
- Clone the app
- `npm install`
- ensure Qwik & Qwik City 1.2.7 was installed:
  `npm ls @builder.io/qwik @builder.io/qwik-city`
- `npm start`
- visit a path like `http://localhost:5173/abc/xyz/static-segment/more-dynamic-123/` and notice that the expected page is rendered
- To see the same route in the same app breaking on >=1.2.8:
  - update Qwik and Qwik City to either latest or 1.2.8:
    `npm i @builder.io/qwik@latest @builder.io/qwik-city@latest`
    or
    `npm i @builder.io/qwik@1.2.8 @builder.io/qwik-city@1.2.8`
  - run the app again with `npm start`
  - visit the same path (`http://localhost:5173/abc/xyz/static-segment/more-dynamic-123/`)
  - notice that the 404 page is rendered instead

### System Info

**output from StackBlitz linked above:**

```shell
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.2.10 => 1.2.10 
    @builder.io/qwik-city: ^1.2.10 => 1.2.10 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7 
```

**output in working repo on local machine (working repo linked above in description):**

```shell
  System:
    OS: macOS 13.5.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 186.47 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.0 - ~/.nvm/versions/node/v20.6.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v20.6.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.6
  npmPackages:
    @builder.io/qwik: ^1.2.7 => 1.2.7 
    @builder.io/qwik-city: ^1.2.7 => 1.2.7 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7 
```

**Comment by mhevery** [comment]
This was a regression which we believe should be fixed.

Can you verify by installing from nightly?
```
  "dependencies: {
    "@builder.io/qwik": "github:BuilderIo/qwik-build#main",
    "@builder.io/qwik-city": "github:BuilderIo/qwik-city-build#main",
    ...
  }
```

**Comment by mhevery** [comment]
Yup it is fixed as your test case is already passing, will cut a new release soon for you. https://github.com/BuilderIO/qwik/pull/5133

**Comment by maxrpeterson** [comment]
Great news, thanks very much @mhevery. tested with my example app and it's working on the nightly build.

Should I go ahead and close this issue as resolved? Or is there any other process step to link this to the ticket that resolves? Either way, looks good from my end 👍 

Thanks again!

**Comment by mhevery** [comment]
Resolved: https://github.com/BuilderIO/qwik/pull/5133
