### ISSUE TITLE
[🐞] Custom data- attribute on a component vanish

### ISSUE THREAD

**Issue by dmitryuck** [BuilderIO/qwik#5128]
### Which component is affected?

Qwik Runtime

### Describe the bug

When I set a custom data- attribute to the component there is no in dom element.

I do like this:

`<DescriptionGrid data-cols="3">...</DescriptionGrid>`

and I expect my **data-cols** attribute stay in element and will be in dom tree, but it is no there

I receive like this:

```
<div 
  class="_descriptionGrid_iujil_1" 
  q:key="V0_1" 
  data-qwik-inspector="components/product/description/description-grid.tsx:6:5">
  ...
</div>
```

seems qwik removes it, please check this case

### Reproduction

no need

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 3.86 GB / 15.94 GB
  Binaries:
    Node: 20.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.4 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.44)
    Internet Explorer: 11.0.22000.120
```

**Comment by ulic75** [comment]
I can't reproduce it in the playground.

https://qwik.builder.io/examples/introduction/hello-world/#v=1.2.10&f=Q040xnDv0CbRgOtP3RJgOWyrlAHyk9JoMhomyQgA

**Comment by mhevery** [comment]
Yes we need a repro on http://qwik.new

**Comment by dmitryuck** [comment]
It looks like component receives only variables declared in properties, everything other parameters passed in the component removed, I believe this is an expected behaviour

**Comment by wmertens** [comment]
@dmitryuck it should work. Are you passing {...props} to your div?
