### ISSUE TITLE
[🐞] <Link> does not work as it should in nginx https version of the basic app

### ISSUE THREAD

**Issue by Kasheftin** [BuilderIO/qwik#5143]
### Which component is affected?

Qwik Runtime

### Describe the bug

When I create the basic app (npm create qwik@latest) and serve it with nginx, the behavior is different depending on whether the HTTP or HTTPS version is used.
Every `<Link>` click triggers a full app reload in HTTPS version. It works as SPA in HTTP version. 

### Reproduction

https://github.com/Kasheftin/basic-qwik-app

### Steps to reproduce

1. Create the basic app with `npm create qwik@latest`
2. Replace `<a href="/demo/flower">` with `<Link href="demo/flower">` in `src/routes/index.tsx` file (import Link from "@builder.io/qwik-city"
3. Run `npm run preview`
4. Notice when `http://localhost:4173/` is opened and the link to the flower app is pressed, it loads `http://localhost:4173/demo/flower/q-data.json` URL, it acts like an SPA app, there's no full page reload.
5. Open the same app in HTTPS through the locally running nginx, here's the basic config I use:
```
server {
  server_name lithuanime.com;
  root /home/kasheftin/work/qwik-demo-app;

  location / {
    proxy_pass http://localhost:4173;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    add_header 'Referrer-Policy' 'strict-origin-when-cross-origin';
    add_header 'Cross-Origin-Opener-Policy' 'same-origin-allow-popups';
  }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/lithuanime.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/lithuanime.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
``` 
6. Click the link to the flower app. Notice the whole new HTML document is being loaded from the `/demo/flower` path, there's no `q-data.json` magic.

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 21.90 GB / 31.30 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v19.8.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
  npmPackages:
    @builder.io/qwik: ^1.2.10 => 1.2.10 
    @builder.io/qwik-city: ^1.2.10 => 1.2.10 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

### Additional Information

Here's the demo of HTTP SPA:
![Peek 2023-09-11 11-38 - HTTP SPA](https://github.com/BuilderIO/qwik/assets/379267/bf8b128c-f72c-4930-81cb-4a425bff2242)

Here's the demo of HTTPS no SPA:
![Peek 2023-09-11 11-38 - HTTPS NO SPA](https://github.com/BuilderIO/qwik/assets/379267/44cc1b42-001f-4223-a83b-d716426631ce)

**Comment by mhevery** [comment]
I believe this was fixed in https://github.com/BuilderIO/qwik/pull/4982 Can you verify that nginx correctly sends `X-Forwarded-Host` and `X-Forwarded-Proto` headers?

Without these headers, it looks to Qwik as if you are navigating to a different domain hence the full refresh.

**Comment by Kasheftin** [comment]
Thanks a lot!
I can confirm that adding `X-Forwarded-Host` and `X-Forwarded-Proto` headers solves the issue for the production version.
A small issue is that it does not help in development (`npm run dev`). 
Do you have any clue why this happens?

**Comment by mhevery** [comment]
Do you use NGINX in development? What kind of headers is nginx adding by default? 

Unless the nginx has its own headers, which we need to add, I don't think there is much to be done here, and I think we should close the issue.

**Comment by Kasheftin** [comment]
I did a small investigation about dev mode and found out that `PROTOCOL_HEADER` and `HOST_HEADER` variables are not set there. Then `getOrigin` is checking for `(req.socket.encrypted || req.connection.encrypted ? "https" : "http")` which is false for some reason. As a result, `serverData.url` is set to HTTP instead of HTTPS. 

A quick fix for supporting https in dev mode is just to add this to the .env file:
```
PROTOCOL_HEADER=X-Forwarded-Proto
HOST_HEADER=X-Forwarded-Host
```

**Comment by notcod** [comment]
Nginx conf that works:
```
        proxy_pass      http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
