### ISSUE TITLE
Image Optimizer warning when using SVG from public folder (unnecessary?)[🐞]

### ISSUE THREAD

**Issue by jmmon** [BuilderIO/qwik#5170]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I am using SVG images served from the public folder. I expected to use them in an image tag without any lint warinings.

Actually, I get a lint warning:
```
/home/projects/qwik-starter-qzsaky/src/routes/index.tsx
  8:37  warning  Local images can be optimized by importing using ESM, like this:

  import ImgQwik from '~/media/logo/qwik.svg?jsx';
  <ImgQwik />

See https://qwik.builder.io/docs/integrations/image-optimization/#responsive-images  qwik/jsx-img

✖ 1 problem (0 errors, 1 warning)
```

I may be missing something, but I don't think the image optimizer provides any benefit for SVG images, and if that's the case then SVG files should be filtered out when looking for images to optimize.

### Reproduction

https://stackblitz.com/edit/qwik-starter-qzsaky?file=src%2Fmedia%2Fqwik.svg

### Steps to reproduce

Run `npm run lint`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.2.10 => 1.2.10 
    @builder.io/qwik-city: ^1.2.10 => 1.2.10 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

**Comment by mhevery** [comment]
SVG images can also be optimized...

🤔 

But you are right; it would be nice to be able to opt out of this. Can you use standard lint comments to tell it to ignore this rule for this file?

**Comment by mhevery** [comment]
I just checked you can add `/* eslint-disable qwik/jsx-img */` to the top of the file to disable this.

I am going to close this issue as I don't think there is much to do for us her. Feel free to re-open or create a new one.
