### ISSUE TITLE
[🐞] Qwik serializer could fail on binary string

### ISSUE THREAD

**Issue by genki** [BuilderIO/qwik#5175]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am writing an app that receives a random binary string generated in server side.
The random string is generated like this:
```ts
const getRandomString = () => {
  const random = new Uint8Array(16);
  crypto.getRandomValues(random);
  return String.fromCharCode.apply(null, random);
};
```
It is usually works fine, but sometimes, I found the Qwik serializer fails on the serialization of that binary string.
Here is the error log:
```
Uncaught (in promise) SyntaxError: Cannot convert ;,ëÆ¹L¥yçRÂ«8âc;E©vÚõüx* to a BigInt (at serializers.js:344:16)
    at BigInt (<anonymous>)
    at Object.$prepare$ (serializers.js:344:16)
    at Object.prepare (serializers.js:463:37)
    at _deserializeData (resume.js:65:72)
    at serverQrl_stuff_wOIPfiQ04l4 (index.qwik.mjs:1248:29)
    at async qrl (qrl-class.js:23:24)
    at async routes_component__Fragment_button_onClick_ahXys9A4F8E (index.tsx:19:36)
    at async dispatch (?qfunc=fYK4WiVJmoo:96:29)
    at async HTMLDocument.processDocumentEvent (?qfunc=fYK4WiVJmoo:113:17)
```

I guess the serializer has a bug on the treatment of the binary string.

### Reproduction

https://github.com/genki/qwik-test/tree/bad_serialize

### Steps to reproduce

I made a reproduction app at the link above.
Please clone the repo and `pnpm run dev` then click the button to reproduce this issue.

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M2
    Memory: 91.97 MB / 24.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /opt/homebrew/bin/npm
    pnpm: 8.7.5 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.6
  npmPackages:
    @builder.io/qwik: 1.2.11 => 1.2.11 
    @builder.io/qwik-city: latest => 1.2.11 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.0 => 4.4.0
```

**Comment by genki** [comment]
Here is the code snippet of the reproduction app.
```ts
const binstr = '\x18;\x13,ëÆ¹L\x0F\x97¥y\x90çRÂ«8âc;E\x19©vÚõ\x96üx*\x92';

export const getFoo = server$(async function (){
  return {foo:"foo", bar:binstr};
});

export default component$(() => {
  const foo = useSignal("initial");
  useStyles$(styles);
  return (
    <>
      <h1>Hi 👋</h1>
      <p>foo: {foo.value}</p>
      <button onClick$={async () => {
        foo.value = JSON.stringify(await getFoo());
      }}>Click me</button>
    </>
  );
});
```

**Comment by genki** [comment]
May be relating with #5173

**Comment by genki** [comment]
In above case, the `binstr` starts with `\u0018` so that the serializer may mistakenly recognized it as `BitIng`.

https://github.com/BuilderIO/qwik/blob/bfe8040f13d9970d36807aae6447e0c9d6e5fedb/packages/qwik/src/core/container/serializers.ts#L504

This could happen if you try to deserialize the value that is not serialized. 
I think there must be a flag that the value is serialized or not.

**Comment by genki** [comment]
Sent a PR to fix the issue :)

**Comment by mhevery** [comment]
Yes, that is exactly what is going on...
