### ISSUE TITLE
[🐞] broken link when use action.submit() then nav("somelink")

### ISSUE THREAD

**Issue by barel-mishal** [BuilderIO/qwik#5177]
### Which component is affected?

Qwik City (routing)

### Describe the bug

[Repo](https://github.com/barel-mishal/navigation-broken)

The repo above is a reproduction of the none working navigation.

Explanation about the broken link:
When use useNavigate and routeAction together on the same button the navigation not working although the job of action.submit() was finish. 

Two state when the link not working:
1. when navigate from one page to another using Link/useNavigate then try click on the link (in the repo I color this button red). If you refresh the page the red link going to work. But 
2. if you try to write something in the input the link will also get broken

My workaround to make the broken link work is to warp the nav("someroute") in a setTimeout like this setTimeout( () => nav("/laxical-scope/my-scope"), 0 ) then it will work not matter what.

### Reproduction

https://github.com/barel-mishal/navigation-broken

### Steps to reproduce

explain above

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 1.49 GB / 7.66 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.5.0 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @builder.io/qwik: ^1.1.1 => 1.2.11 
    @builder.io/qwik-city: ^1.1.1 => 1.2.11 
    undici: 5.22.0 => 5.22.0 
    vite: 4.3.5 => 4.3.5
```

**Comment by mhevery** [comment]
Thanks for the nice repro....

**Comment by barelmishal** [comment]
Thanks for the qwik fix! @mhevery

**Comment by mhevery** [comment]
Good repo, gets your qwik fix. ❤️ . Wish other's understood that.
