### ISSUE TITLE
[🐞] Missing `code` property on `QwikKeyboardEvent`

### ISSUE THREAD

**Issue by devatina11yb** [BuilderIO/qwik#5189]
### Which component is affected?

Qwik Runtime

### Describe the bug

The `code` property is missing on `QwikKeyboardEvent`, I believe this is an oversight.

### Reproduction

_No reponse_

**Comment by mhevery** [comment]
> ### Which component is affected?
> Qwik Runtime
> 
> ### Describe the bug
> The `code` property is missing on `QwikKeyboardEvent`, I believe this is an oversight.
> 
> ### Reproduction
> _No reponse_
> 
> ### Steps to reproduce
> _No response_
> 
> ### System Info
> _No response_
> 
> ### Additional Information
> _No response_

Can you provide more context....

**Comment by devatina11yb** [comment]
> > The `code` property is missing on `QwikKeyboardEvent`, I believe this is an oversight.
> 
> Can you provide more context....

Sure,

**Comment by devatina11yb** [comment]
I accidently closed the issue.

**Comment by mhevery** [comment]
Ohh I see.... Yes, any chance we could get you to create a PR with a fix?

**Comment by devatina11yb** [comment]
> Ohh I see.... Yes, any chance we could get you to create a PR with a fix?

Sure, I’ll take care of it.

**Comment by gioboa** [comment]
Thanks 😉
