### ISSUE TITLE
Whether similar to PUBLIC_URL is supported[✨]

### ISSUE THREAD

**Issue by ldw1216** [BuilderIO/qwik#5211]
### Is your feature request related to a problem?

I need to publish assets (css and js) to the CDN, so I came up with something like PUBLIC_URL for create-react-app or asset_Prefix for next. Has Qwik been implemented or considered for implementation?

### Describe the solution you'd like

Adding a configuration similar to the PUBLIC_URL of create-react-app or assetPrefix of next makes it easier to deploy the project。
Reference：
create-react-app:  https://create-react-app.dev/docs/advanced-configuration
next:  https://nextjs.org/docs/app/api-reference/next-config-js/assetPrefix

### Describe alternatives you've considered

Perhaps there is an implementation of vite? I can't find it.

**Comment by mhevery** [comment]
We don't but this should be trivial for you to work around....

```typescript
export const MyImg = (props) => {
  return <img src={'https://my-cdn/path/' + props.src} {...props}/>
};
```

Would that work?

**Comment by ldw1216** [comment]
Thank you for your answer.
I said the assert is that qwik generated js and CSS, such as http://localhost:3000/p/build/q-1d36ff58.js.
I see vite has the relevant configuration, but it does not work。
vite.config.ts:

`import { defineConfig } from "vite";
import { qwikVite } from "@builder.io/qwik/optimizer";
import { qwikCity } from "@builder.io/qwik-city/vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig(() => {
  return {
    plugins: [qwikCity(), qwikVite(), tsconfigPaths()],
    experimental: {
      renderBuiltUrl(filename: string) {
        return 'http://cdn.myDomain.com/' + filename + '?pid=va'
      },
    },
    preview: {
      headers: {
        "Cache-Control": "public, max-age=600",
      },
    },
  };
});
`

**Comment by mhevery** [comment]
I need clarification on your question. Qwik as part of the build, creates the JS files. These files need to be hosted on the same URL as the server. (Do you want to host them elsewhere? that can be done, one just needs to update the `q:base` attribute.)

**Comment by ldw1216** [comment]
Yes, I want to host them elsewhere。How to update the q:base attribute.

**Comment by wmertens** [comment]
@ldw1216 check out your entry.ssr.ts file, you can set it there

**Comment by ldw1216** [comment]
@wmertens  Really work！But there are new problems，a cross-domain error occurred in the js request。
I set the base: 'http://127.0.0.1:5176/build/',  Then access it with http://localhost:5176, display error MissingAllowOriginHeader 。

```typescript
export default function (opts: RenderToStreamOptions) {
  return renderToStream(<Root />, {
    manifest,
    ...opts,
    base: process.env.NODE_ENV === 'production' ? 'http://127.0.0.1:5176/build/' : opts.base,
    // Use container attributes to set attributes on the html tag.
    containerAttributes: {
      lang: "en-us",
      ...opts.containerAttributes,
    },
  });
}
```

**Comment by ldw1216** [comment]
Thinks to @wmertens  @mhevery  ， It's OK by modifying the entry.node-server.tsx.
```typesctip
server.on("request", (req, res) => {
  if (req.url?.includes('/build')) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  }
  staticFile(req, res, () => {
    router(req, res, () => {
      notFound(req, res, () => { });
    });
  });
});```

**Comment by wmertens** [comment]
Alright, closing this 👍

**Comment by Rainnut** [comment]
> @wmertens 确实有效！但是又有新问题了，js请求出现跨域错误。 我设置了base: ' [http://127.0.0.1:5176/build/ '，然后用](http://127.0.0.1:5176/build/)[http://localhost](http://localhost:5176)访问： [5176](http://localhost:5176) , 显示错误 MissingAllowOriginHeader 。
> 
> ```ts
> export default function (opts: RenderToStreamOptions) {
>   return renderToStream(<Root />, {
>     manifest,
>     ...opts,
>     base: process.env.NODE_ENV === 'production' ? 'http://127.0.0.1:5176/build/' : opts.base,
>     // Use container attributes to set attributes on the html tag.
>     containerAttributes: {
>       lang: "en-us",
>       ...opts.containerAttributes,
>     },
>   });
> }
> ```

I adopted this solution. It seems that most of the js files can be placed on the cdn, but there are a small number of static resources that are still not placed on the cdn and are still obtained from the build path of the ssr service.

**Comment by dostufffancy** [comment]
it only affected `js` files not `png` and `css` files. same issue #3759
