### ISSUE TITLE
[🐞] Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function - Chrome 117

### ISSUE THREAD

**Issue by coderaidershaun** [BuilderIO/qwik#5213]
### Which component is affected?

Qwik Runtime

### Describe the bug

Thanks: 
First, this is my fav framework. Lots more videos to come soon on YT.

Issue: 
Just launched a Qwik instance on the new Chrome browser version 117 (Github url provided).

No modifications have been made to the default installation.

When checking the console on Chrom 117, I get the following errors on running in dev mode:

Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function
  at isAllowedPropertyValue (lockdown-install.js:1:53384)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at isAllowedPropertyValue (lockdown-install.js:1:53041)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at lockdown-install.js:1:55523
  at repairIntrinsics (lockdown-install.js:1:144597)
  at lockdown-install.js:1:145462
  at lockdown-run.js:4:3
  
Protecting intrinsics failed: ReferenceError: harden is not defined
  at lockdown-more.js:69:13
  at Set.forEach (<anonymous>)
  at protectIntrinsics (lockdown-more.js:44:22)
  at lockdown-more.js:97:5
  
Note: No issues coming up on other browsers.

![Screenshot 2023-09-25 at 19 26 58](https://github.com/BuilderIO/qwik/assets/122157792/e3c0456f-b841-4bb7-816e-836a398b1df2)

### Reproduction

https://github.com/coderaidershaun/qwik-error-example.git

### Steps to reproduce

yarn create qwik (or npm create qwik@latest [I have tried both]

Select basic project or empty project

yarn dev (or npm run dev)

open the console in the latest Google Chrome 117

Note: I don't see this issue in other browsers.

### System Info

```shell
MacOS
```

**Comment by Varixo** [comment]
probably this error is coming from a chrome plugin

**Comment by gioboa** [comment]
@Varixo is right. The problem comes from a Chrome Extension https://github.com/MetaMask/metamask-extension/issues/20847
I will close this issue.
Thanks @coderaidershaun for the kind words about Qwik.

**Comment by gioboa** [comment]
No problem. 😉

**Comment by eleven980828** [comment]
Worked out，Is metamask
