### ISSUE TITLE
[🐞] Prefetched files with no-cache headers are re-fetched again

### ISSUE THREAD

**Issue by intellix** [BuilderIO/qwik#5215]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I'm building my application for production and if I visit a Cloudflare Pages deployed application and sit there for a few seconds and then click a link, there's a moment of lag whilst it downloads the required bundle and executes it.

Example of 200ms download by the SW after clicking a button:
![image](https://github.com/BuilderIO/qwik/assets/1162531/003d8c3d-c02d-4a62-9e51-6b73a02a3562)

Here are the timings of the download:
![image](https://github.com/BuilderIO/qwik/assets/1162531/cd9d2039-4b8a-43ab-a202-a58a241ff4b4)

If I look at Cache Storage in chrome, I can see the code was already prefetched as expected: 
![image](https://github.com/BuilderIO/qwik/assets/1162531/a74860c3-dc46-4da5-adf5-417378419354)

And if I look inside that cache entry I can see the contents were also downloaded (I don't just have a reference): 
![image](https://github.com/BuilderIO/qwik/assets/1162531/80389660-11b2-4c63-b4fb-0f209d68ec10)

My application was deployed via Cloudflare Pages and the routing says the file gets excluded from paid invocations (essentially a static file delivery). When I look at the headers of the files being requested I can see that there's always a cache miss or that CF says the max-age is 0 so it shouldn't be cached by the browser: 
<img width="399" alt="Screenshot 2023-09-25 at 13 59 22" src="https://github.com/BuilderIO/qwik/assets/1162531/3d7ad215-b1d8-4006-8661-60d74b4ee982">

After playing around a little with the new CF Cache Rules that are in beta, I was able to enforce a 5 minute cache for all JS files within the build/ directory:
<img width="1036" alt="Screenshot 2023-09-26 at 09 25 16" src="https://github.com/BuilderIO/qwik/assets/1162531/f0c1bc2d-5ec1-488f-bf31-8f4d9c142013">

And now I'm seeing the files taking 1ms (I guess due to browser cache now realising it already has the file).

So my question is: If the contents of the script were prefetched and cached within the service worker, when I click my button, why would it revisit the network and spend 200ms downloading a script that it already has, just because there's no browser cache on it. Was the file prefetched in a previous session and it's now stale?

- If the file was cached/stale from a previous session, why did it not re-prefetch it?
- If the file was pre-fetched there and then, why did it go back to the network to redownload it?
- If this is expected behaviour, maybe the Cloudflare integration guide should tell users to apply a cache to JS bundles (I see this click delay question coming up constantly in tickets/discord)
- I assume the file names are hashes of the content and I should be able to set those caches to Immutable?

### Reproduction

N/A

### System Info

```shell
@builder.io/qwik: ~1.2.12 => 1.2.12 
@builder.io/qwik-city: ~1.2.12 => 1.2.12 
@builder.io/qwik-react: 0.5.0 => 0.5.0 
@builder.io/sdk-qwik: ^0.6.2 => 0.6.2 
undici: ^5.24.0 => 5.24.0 
vite: ~4.4.0 => 4.4.9
```

**Comment by mhevery** [comment]
Do you have a URL that I can experiment with to see this behavior?

Also, when you say "link" do you mean `<a href>` or `<Link>`? There is a known issue with `<Link>`, which I am currently working on.

**Comment by mhevery** [comment]
Also:
1. Can you verify that the file is on the Application file BEFORE you click the navigate?

If the above is true, then the caching headers from CF should not matter.... I think the files are not in the application cache before you navigate...

Best would be to have a URL I can try so I could see what is going on.
