### ISSUE TITLE
[✨] HMR (Hot Module Replacement) Support 

### ISSUE THREAD

**Issue by antmoux** [BuilderIO/qwik#5235]
### Is your feature request related to a problem?

Looks like HMR is not implemented with Qwik.

https://github.com/BuilderIO/qwik/blob/138171fbf79a45399ae806ff789a3a7318f8729d/packages/qwik-city/buildtime/vite/dev-server.ts#L256

Is that correct? This was the only HMR code snippet that I was able to find.

### Describe the solution you'd like

Would be a much better DX have HMR support. This is now our main problem holding us to use Qwik as our first choice framework.

### Describe alternatives you've considered

No other options really.

**Comment by mhevery** [comment]
Not sure what you mean by HMR, but when I develop code in dev mode, the UI updates as I change the source. So from my point of view, it works. 

What have you tried that did not work?

**Comment by mhevery** [comment]
Ohh I see... https://github.com/BuilderIO/qwik/issues/1901

**Comment by mhevery** [comment]
Closing as duplicate: https://github.com/BuilderIO/qwik/issues/1901
