### ISSUE TITLE
Cross drive installation with pnpm fails (Windows) [🐞]

### ISSUE THREAD

**Issue by DitlevHB** [BuilderIO/qwik#5256]
### Which component is affected?

Starters / CLI

### Describe the bug

Running pnpm create qwik@latest on drive D while pnpm is installed on drive C causes the error "EXDEV: cross-device link not permitted" while installing the pnpm dependencies. 

Solution: A follow up pnpm install in the project directory on drive D installs the dependencies correctly. 

Not sure if there is an easy fix for this, but I thought I would mention this bug.

### Reproduction

N/A

### Steps to reproduce

Run pnpm create qwik@latest on a Windows machine with two drives. 
The pnpm installation should be executed on the drive where pnpm is not installed. 

### System Info

```shell
Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Roaming\npm\pnpm.CMD
```

**Comment by mhevery** [comment]
I believe that is an issue with `pnpm` not qwik. Will close the issue, but let me know if I am misunderstanding.
