### ISSUE TITLE
[🐞] Dynamic tag breaks reactivity

### ISSUE THREAD

**Issue by mishimalisa** [BuilderIO/qwik#5266]
### Which component is affected?

Qwik Runtime

### Describe the bug

In the code below, when you modify the `isActive` property, it doesn't actually update the component class.
```jsx
export const Tag = component$(
  ({ isButton, isActive }) => {
    const Tag = isButton ? 'button' : 'div';
    return <Tag class={isActive ? 'active' : ''}>My tag</Tag>;
  }
);
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-drxiwj?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

1. Run `npm install && npm run dev`
2. Create a component that uses dynamic tag and a reactive property
3. Try to update the reactive property

### System Info

```shell
"vite": "4.4.9"
"@builder.io/qwik": "^1.2.12"
"@builder.io/qwik-city": "^1.2.12"
```

**Comment by wmertens** [comment]
Faster-loading repro: https://qwik.builder.io/playground/#v=1.2.12&f=7Va7CsIwFN39iji1hVonBUsTwb2bH9CitUuhUHEoJf%2FuSW5elSJdBbeE3Pc9ufcEoDkeTkugSf32pSOtrTVYotzL8Vq3SD5AFNzHE0bQRVOJFCf1NzHkZI6l5IrEjAXSt%2BLszCLiIBHLWQRaApdK2KJTiWtWwidnGDq1PmmdSIpyxIJriz2EAV%2FG5AYFWfUJKCYXDff1iR9192ySQMZ4X5QJKECVUXAovN9lu1vf9UOOtO5MVkrDJmjaSEXw%2FGOKEy5sXBnm06vh2%2FldClJyLO6rJYreWwrvUlDIn5YGA7mC2m7dq1bMAnHF8U2yL9oCQPqfKr86Vd4

The button button can be used to make it re-render. Seems to be a special case for `class` somehow.

**Comment by wmertens** [comment]
So the difference is that the dynamic tag converts into _jsxC and the fixed tag into _jsxQ.

Somehow _jsxC doesn't subscribe to changes in the props object.

**Comment by wmertens** [comment]
This works, which is creating JsxNodeImpl with the proxied props in `immutableProps`:
```js
    return /*#__PURE__*/ _jsxQ("div", null, {
        class: _fnSignal((p0)=>p0.isActive ? 'active' : '', [
            props
        ]),
        "data-meep": _fnSignal((p0)=>p0.isActive, [
            props
        ])
    }, "My div", 3, "4e_1", {
        fileName: "app.tsx",
        lineNumber: 14,
        columnNumber: 12
    });
```

This fails, and creates JsxNodeImpl with the props+_IMMUTABLE in the mutableProps, nothing in immutableProps:
```js
const MyTag_component_10GogOBkekQ = (props)=>{
    // uncomment to force rerender
    // console.log(isButton, isActive)
    const Tag = props.isButton ? 'button' : 'div';
    return /*#__PURE__*/ _jsxC(Tag, {
        get class () {
            return props.isActive ? 'active' : '';
        },
        get "data-meep" () {
            return props.isActive;
        },
        children: "My tag",
        [_IMMUTABLE]: {
            class: _fnSignal((p0)=>p0.isActive ? 'active' : '', [
                props
            ]),
            "data-meep": _fnSignal((p0)=>p0.isActive, [
                props
            ])
        }
    }, 3, "4e_0", {
        fileName: "app.tsx",
        lineNumber: 8,
        columnNumber: 12
    });
};
```

So my guess is that the immutableprops aren't called and the subscription doesn't fire.

**Comment by wmertens** [comment]
When putting the _jsxC component in the playground and adding console logging to the _fnSignal calls, you can see that they never get called. Commenting out the class or data-meep getters doesn't help.

Moving the _fnSignal calls to the normal part of the props breaks the app.

Maybe @adamdbradley or @manucorporat can weigh in? I don't know what the immutableprops are supposed to be for.

**Comment by mhevery** [comment]
nice debug work!

**Comment by wmertens** [comment]
Ok, the reason is that string tags don't subscribe use immutableprops when rendering. Here's an updated playground that mixes "button" and a B component. When B renders, it triggers the generated props signals, but "button" doesn't do that.

https://qwik.builder.io/playground/#v=1.2.12&f=7VY9a8MwEN37K66TY3DsIXQxsgoeunnrVgoxtWICCTZuCwlG%2F70nnT6c1ElMQoZCNxmfnt47ne7esGieFqNVE%2FnxS0uaWxGo%2Bp5SUpSCYv9a1pgDD8xwAHGVgVmP7SjXtiLClXqn2PBkiv9dwsDAEIgNh2cIyI8EkEKAFgXPVcG2UlW4dihZ74BxT6lXek8g9Vyfb4VofZDkxR4nYM0SRMD6BpAPmLFjScV6J6r76MrvIGir6E6Q9XJZ1gkxliYSv57mStNECDKdJ2jmI%2BzajDOqB%2BjjOG4lZ6pKE%2B5sazgu1qT9ar35rWoRwJ7Mkvy35rN9maS44sn8i52tys2nCAcxht5ozMCVLmNij63A26v5R7NpuhRVVyDfnKB3FdR0%2BPpTQLOyrqDuBLqcRbsDuVTANk2mAZkrcs65n4UZt%2FRjnKzfIns8%2FJb8q6lrdCC0193nWUDS6gGH3w6QdB4DdqZ1Mupbloy6uwNaLqP%2BVu0fj%2BDaxG0w7llODjYFcSEeB8L%2FBP%2BrE%2FwH
