### ISSUE TITLE
[🐞] qwik new CamelCaseComponent exported component becomes Camelcasecomponent

### ISSUE THREAD

**Issue by chug2k** [BuilderIO/qwik#5282]
### Which component is affected?

Starters / CLI

### Describe the bug

I created a new component using `qwik new` and I lost camelcase in the Props and export declaration.

### Reproduction

n/a

### Steps to reproduce

just use qwik new. 

### System Info

```shell
System:
    OS: macOS 12.6.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 79.23 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.5
  npmPackages:
    @builder.io/qwik: ^1.2.13 => 1.2.13 
    @builder.io/qwik-city: ^1.2.13 => 1.2.13 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

### Additional Information

Sorry to drop such a trivial bug. I am learning qwik for the first time, so submitting the issue with a goal of submitting a PR for it shortly as soon as I get my bearings.

**Comment by wmertens** [comment]
Can you provide more details? How are you creating CamelCaseComponent and how do you import it, where do you notice the problem?
