### ISSUE TITLE
[🐞] [vite] Internal server error: Missing Qwik City Env Data

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#5283]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I updated our Qwik from `1.2.12` to `1.2.13` and now we get this error:

```
6:38:52 AM [vite] Internal server error: Missing Qwik City Env Data
  File: /SiteBase/Qwik/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:3283:26
      at AsyncFunction.QwikCityProvider_component_TxCFOy819ag (/SiteBase/Qwik/node_modules/@builder.io/qwik-city/index.qwik.mjs:628:11)
      at AsyncFunction.invoke (/SiteBase/Qwik/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:3283:26)
      at /SiteBase/Qwik/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:8321:35
      at then (/SiteBase/Qwik/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:447:56)
      at /SiteBase/Qwik/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:8307:20
      at /SiteBase/Qwik/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:1582:27
      at safeCall (/SiteBase/Qwik/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:434:25)
      at executeComponent (/SiteBase/Qwik/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:1582:12)
      at renderSSRComponent (/SiteBase/Qwik/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:3634:17)
      at renderNodeVirtual (/SiteBase/Qwik/dist-dev/tsc-out/packages/qwik/src/core/util/implicit_dollar.js:3538:16)
```

And it does not tell us what is wrong with our code. What file? Which line? Why this error? What should we do to fix it? No information that can help us get there.

We do have the `.env` file at the root and we do have some variables in it.

And this problem only appears sometimes. That's the bad part.

### Reproduction

I can give you access to our private repo

### System Info

```shell
System:
    OS: Linux 6.2 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 8.95 GB / 15.49 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.0 - /usr/local/bin/npm
  Browsers:
    Chromium: 117.0.5938.149
  npmPackages:
    @builder.io/partytown: ^0.8.1 => 0.8.1 
    @builder.io/qwik: ^1.2.13 => 1.2.13 
    @builder.io/qwik-auth: ~0.1.3 => 0.1.3 
    @builder.io/qwik-city: ^1.2.13 => 1.2.13 
    undici: ^5.25.4 => 5.25.4 
    vite: ^4.4.11 => 4.4.11
```

**Comment by Nefcanto** [comment]
This happens for non-existing images in the `__image_info` path.

**Comment by wmertens** [comment]
How can these images not exist?

**Comment by Nefcanto** [comment]
@wmertens, we get data from API—for example, a list of weblog posts. One post might have a problem in its image and the API might return a non-existing URL for its image, or even an empty URL.

**Comment by wmertens** [comment]
@mhevery I wonder if this is fixed by the recent env fix

**Comment by TimKieu** [comment]
Pls consider 2 ways of using env with VITE:
process.env.VARS or
import.meta.env.VARS

**Comment by Nefcanto** [comment]
@TimKieu it has nothing to do with the usage pattern. It happens when an image does not exist.

**Comment by mhevery** [comment]
This is interesting. I would love to get to the bottom of this, but I need "minimal" reproduction, please.  (Acces to your large repo is not a substitute for a minimal repro.)

**Comment by Nefcanto** [comment]
@mhevery thank you for helping. [This](https://stackblitz.com/edit/qwik-starter-w6e7gz?file=package.json,src%2Froutes%2Findex.tsx) is an MRE. I simply replace the `index.tx` content with `<img src='/non-existing-image' />` tag.

You should see the error.
