### ISSUE TITLE
[🐞] Storybook integration doesn't take Tailwind integration into account

### ISSUE THREAD

**Issue by bebraw** [BuilderIO/qwik#5304]
### Which component is affected?

Qwik Runtime

### Describe the bug

After adding Tailwind (`npm run qwik add tailwind`) and Storybook (`npm run qwik add storybook`) to a Qwik project through integrations, Tailwind classes aren't picked up by Storybook.

I also noticed that the version of Storybook included to the integration is fairly old so it may be worth upgrading. I did this in my demonstration project already.

### Reproduction

https://github.com/bebraw/qwik-repro

### Steps to reproduce

1. `npm install`
2. `npm run storybook`
3. Note that the default button is missing styling

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 11.11 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    pnpm: 8.9.0 - /usr/local/bin/pnpm
    Watchman: 2023.10.09.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 117.0.5938.149
    Edge: 117.0.2045.55
    Safari: 17.0
  npmPackages:
    @builder.io/qwik: ^1.2.13 => 1.2.13
    @builder.io/qwik-city: ^1.2.13 => 1.2.13
    undici: 5.25.4 => 5.25.4
    vite: 4.4.11 => 4.4.11
```

**Comment by gioboa** [comment]
Thanks for reporting it. would you like to do a PR for this issue?

**Comment by bebraw** [comment]
Ok, here's the initial PR: https://github.com/BuilderIO/qwik/pull/5308 . Feel free to amend to fit your guidelines better testing-wise etc.
