### ISSUE TITLE
[📖] QRL page could use more additional links

### ISSUE THREAD

**Issue by bebraw** [BuilderIO/qwik#5305]
### Suggestion

At https://qwik.builder.io/docs/advanced/qrl/#see-also, the link seems broken. I believe it should point to https://qwik.builder.io/api/qwik/#qrl or some other resource.

It might also be good if the QRL page showed how to implement a prop callback pattern since that's one of the first instances where users coming from React are likely to run into issues.

**Comment by gioboa** [comment]
Thanks for reporting it, you are right, we need to fix it. would you like to do a PR for this issue?

**Comment by bebraw** [comment]
Ok, here we go: https://github.com/BuilderIO/qwik/pull/5307 .
