### ISSUE TITLE
codebook/portal/portal-provider[🐞]

### ISSUE THREAD

**Issue by georgetakla** [BuilderIO/qwik#5320]
### Which component is affected?

Qwik Runtime

### Describe the bug

I tried to build the portal cookbook, but I get two errors on portal-provider.tsx

1- When referencing "**portals**" inside a different scope ($), Qwik needs to serialize the value, however "portals.value.contexts.id.__brand_context_type__" is unknown, which could be serializable or not, please make the type for specific.
Check out https://qwik.builder.io/docs/advanced/dollar/ for more details.eslint[qwik/valid-lexical-scope](https://qwik.builder.io/docs/advanced/eslint/#valid-lexical-scope)

```
      $((name: string, jsx: JSXNode, contexts?: ContextPair<any>[]) => {
        const portal: Portal = {
          name,
          jsx,
          close: null!,
          contexts: [...(contexts || [])],
        };
        portal.close = $(() => {
          **portals**.value = **portals**.value.filter((p) => p !== portal);
        });
        portal.contexts.push({
          id: PortalCloseAPIContextId,
          value: portal.close,
        });
        **portals**.value = [...**portals**.value, portal];
        return portal.close;
      })
 ```
 2- Calling use* methods in wrong function.eslint[qwik/use-method-usage](https://qwik.builder.io/docs/advanced/eslint/#use-method-usage)
(alias) useContextProvider<any>(context: ContextId<any>, newValue: any): void
import useContextProvider
Assign a value to a Context.

Use **useContextProvider**() to assign a value to a context. The assignment happens in the component's function. Once assigned, use useContext() in any child component to retrieve the value.

Context is a way to pass stores to the child components without prop-drilling.
```
  export const WrapJsxInContext = component$<{
    jsx: JSXNode;
    contexts: Array<ContextPair<any>>;
  }>(({ jsx, contexts }) => {
    contexts.forEach(({ id, value }) => **useContextProvider**(id, value));
    return (
      <>
        {/* Workaround: https://github.com/BuilderIO/qwik/issues/4966 */}
        {/* {jsx} */}
        {[jsx].map((jsx) => jsx)}
      </>
    );
  });
```

got

### Reproduction

NA

### Steps to reproduce

copy the code of portal-provider to a file in vs code and eslint will show the errors

### System Info

```shell
NA
```

**Comment by mhevery** [comment]
Could you create a reproduction of the issue on http://qwik.new showing the error.

**Comment by georgetakla** [comment]
I tried to duplicate the issue on HTTP://qwik.new and created portal-provider.tsx file there. but there is no error.
I am sharing with you the error that I get from eslint of qwik/valid-lexical-scope on portals.value and portal variables

![Screenshot 2023-10-27 at 4 02 28 PM](https://github.com/BuilderIO/qwik/assets/117195571/9154621e-b310-4114-868f-88cd0e34c39a)

**Comment by thejackshelton** [comment]
Hey @georgetakla, we're actually solving this issue natively with the Popover API in the upcoming Qwik UI version.

For now you can follow our previous portal implementation here:
https://github.com/qwikifiers/qwik-ui/blob/main/packages/kit-headless/src/components/qwik-ui-provider/qwik-ui-provider.tsx
https://github.com/qwikifiers/qwik-ui/blob/main/packages/kit-headless/src/components/combobox/combobox-portal.tsx

**Comment by georgetakla** [comment]
thank you @thejackshelton! I will check it out

**Comment by gioboa** [comment]
@georgetakla did you solve the issue? Can we close it?

**Comment by georgetakla** [comment]
No. but go ahead and close it

Thanks
--George


From: Giorgio Boa ***@***.***>
Date: Saturday, February 3, 2024 at 7:36 AM
To: BuilderIO/qwik ***@***.***>
Cc: George Takla ***@***.***>, Mention ***@***.***>
Subject: Re: [BuilderIO/qwik] codebook/portal/portal-provider[🐞] (Issue #5320)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@georgetakla<https://github.com/georgetakla> did you solve the issue? Can we close it?
