### ISSUE TITLE
[🐞] qwik new component Error

### ISSUE THREAD

**Issue by l6037600** [BuilderIO/qwik#5321]
### Which component is affected?

Starters / CLI

### Describe the bug

In [Utilities section](https://qwik.builder.io/docs/project-structure/#utilities) on project structure page, it says by running this command:

<pre>pnpm qwik new button</pre>

It throws an error:

<pre>TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined</pre>

I checked the source code. In my local running environment, (cli.cjs)at line 3034`template.relative` is `undefined`.

when i specify `template.relative` value, A new error has appeared:
<pre>(cli.cjs)at line 3049: await import_node_fs7.default.promises.writeFile(fileOutput, templateOut, { encoding: "utf-8" });
Error: EISDIR: illegal operation on a directory, open 'D:\xxx\qwik-xxx\src\components\button'
</pre>

Then I modified the code from `fileOutput` to `${fileOutput}/index.tsx` and the error disappeared.
I also tried changing the dependency package version
I don’t know if it’s due to my local operating environment, incompatible versions of dependent packages, or other reasons

### Reproduction

https://github.com/l6037600/qwik-cli-new-component-error

### Steps to reproduce

Run pnpm qwik new button

### System Info

```shell
System:
    OS: Windows 11
    CPU: Intel(R) Core(TM)
    Memory: 6.00 GB / 12.00 GB
    Shell: PowerShell
  Binaries:
    Node: 20.8.1 - C:\Program Files\nodejs\node.exe
    npm: 8.19.2 - C:\Users\Administrator\AppData\Roaming\npm
    pnpm: 8.9.2 - C:\Users\Administrator\AppData\Roaming\pnpm
  Browsers:
    Edge: 118.0.2088.46
  npmPackages:
    @builder.io/qwik: 1.2.13
    @builder.io/qwik-city: 1.2.13
    undici: 5.22.1
    vite: 4.4.7
```

**Comment by mhevery** [comment]
I am unable to reproduce this on a clean `npm create qwik@latest` Need better repro instructions.

**Comment by Neschadin** [comment]
> I am unable to reproduce this 

hi! i have the same problem

`pnpm qwik new my-button`
![image](https://github.com/BuilderIO/qwik/assets/73835274/23929ced-4794-4846-b729-1ca34e5484bc)

https://github.com/Neschadin/qwik-empty

**Comment by gioboa** [comment]
@Neschadin can you try with Qwik 1.2.15 pls?

**Comment by l6037600** [comment]
> @Neschadin您可以尝试使用 Qwik 1.2.15 吗？

I still get the same error

**Comment by alex-bluetrain** [comment]
I have the same error, the problem seems to be at parseTemplatePath in qwil/cli.cjs

the "relative" attribute is undefined, because the split fails.
I changed it to this, and it works:
```
function parseTemplatePath(path3, type) {
  console.log("PARSE TEMPLATE PATH:",path3, type);
  // const parts = path3.split(`/${type}/`);
  const parts = path3.split(type);
  return {
    absolute: path3,
    relative: parts[1]
  };
}
```

**Comment by Neschadin** [comment]
> @Neschadin can you try with Qwik 1.2.15 pls?

the same
![image](https://github.com/BuilderIO/qwik/assets/73835274/29e97d2f-5970-4f7d-b774-7c8b037e6497)

**Comment by thejackshelton** [comment]
@Neschadin this happens with pnpm only?

**Comment by Neschadin** [comment]
> @Neschadin this happens with pnpm only?

yeap

**Comment by gioboa** [comment]
@alex-bluetrain you found the right place to modify. Would you like to drop a PR for that pls?
