### ISSUE TITLE
[🐞] qwikInsights vite plugin does not normalize paths like the qwikVite plugin

### ISSUE THREAD

**Issue by intellix** [BuilderIO/qwik#5337]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I'm playing with qwikInsights to improve performance of our Qwik app. We're also using qwik-nx to support multiple apps in the same codebase with shared libraries. 

I noticed before that the dist directory was hardcoded in the original plugin and did a PR to fix it.

I now have 2 more problems:
- The qwikVite plugin assumes q-insights.json exists within the /dist folder (doesn't take qwikInsights plugin options into account)
- The qwikInsights plugin doesn't normalize paths like the qwikVite plugin does

So this means that if you configure the outDirs in qwikVite, the same value isn't going to work when passing in a value to the qwikInsights plugin:

```ts
qwikVite({
  client: {
    outDir: '../../dist/apps/myapp/client',
  },
  ssr: {
    outDir: '../../dist/apps/myapp/server',
  },
  tsconfigFileNames: ['tsconfig.app.json'],
}),
qwikInsights({
  outDir: '../../dist/apps/myapp/client',
  publicApiKey: loadEnv('', '.', '').PUBLIC_QWIK_INSIGHTS_KEY,
}),
```

In fact, even removing the `../../` from qwikInsights outdir is proving problematic for me as well.

### Reproduction

N/A

### System Info

```shell
N/A
```

**Comment by mhevery** [comment]
@gioboa perhaps you could offer your expertise here.

**Comment by gioboa** [comment]
Yep. @intellix let's do pair programming
