### ISSUE TITLE
use of <Link> not working whit storybook[🐞]

### ISSUE THREAD

**Issue by davidbalu10** [BuilderIO/qwik#5346]
### Which component is affected?

Qwik Runtime

### Describe the bug

```
<Link href="/" title="San y sam" class="text-black">
    <p>hola</p>
</Link>
<a href="/" title="San y sam" class="text-black">
    <p>hola 2</p>
</a>
```

If I use <Link> the element inside is not displayed, if I use <a> it is displayed, all this in storybook (npm run storybook) http://localhost:6006/

### Reproduction

http://localhost:6006/

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
    Memory: 7.56 GB / 15.90 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.61)
    Internet Explorer: 11.0.19041.3570
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.1
    @builder.io/qwik: ^1.2.12 => 1.2.12
    @builder.io/qwik-auth: 0.1.1 => 0.1.1
    @builder.io/qwik-city: ^1.2.12 => 1.2.12
    undici: ^5.26.4 => 5.26.4
    vite: 4.4.7 => 4.4.7
```

**Comment by mhevery** [comment]
So we need a real reproduction, not http://localhost. 😁 Please create a minimal repro in Git Hub for us to clone with clear instructions on how to reproduce, and we will be happy to look at it.

In the meantime, I am going to close this issue. Feel free to re-open with reproduction.
