### ISSUE TITLE
[🐞] routeLoader crashing when using Firebase integration with Firestore

### ISSUE THREAD

**Issue by vdemcak** [BuilderIO/qwik#5354]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to execute Firestore queries in my `routeLoader$` in order to fetch and pre-render data server-side. Everything works fine in development and when using the `preview` command, but upon deploying the app to Firebase Hosting and Cloud Functions ([Using the Firebase integration](https://qwik.builder.io/docs/deployments/firebase/)), the app returns `Error 500 - Internal Server Error`.

Upon opening the Cloud Function logs, I can see, that it fails with the following error message:
```
TypeError: Cannot set properties of undefined (setting 'fromParams')
    at ClientPool.clientFactory (file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:167322:43)
    at ClientPool.acquire (file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:153428:31)
    at ClientPool.run (file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:153535:28)
    at file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:168168:28
    at Firestore._retry (file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:168038:26)
    at async file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:145922:33
Caused by: Error
    at AggregateQuery._get (file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:145879:21)
    at AggregateQuery.get (file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:145869:19)
    at Object.s_eNFdi8qBn48 (file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:168225:68)
    at Object.invoke (file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:1461:42)
    at file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:4100:131
    at then (file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:137:81)
    at file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:4091:14
    at Object.qrl (file:///workspace/server/assets/@qwik-city-plan-c264a646.mjs:4071:18)
    at file:///workspace/server/entry-firebase.mjs:464:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
```

I reduced my `routeLoader$` and application functions to be as simple as possible:

``` tsx

// /lib/firestore.ts
import { Firestore } from '@google-cloud/firestore';

export const firestore = new Firestore({
  projectId: 'some-project',
  credentials: {
    client_email: 'email@gserviceaccount.com',
    private_key: "supersecret"
  }
});


// /routes/challenges/index.tsx
import { firestore } from '~/lib/firestore';

export const useChallenges = routeLoader$(async () => {
  const countRes = await firestore.collection('challenges').count().get();

  return countRes.data();
});

export default component$(() => {
  const challenges = useChallenges();

  return (
    <div>
      <h1>Challenges</h1>
      <pre>{JSON.stringify(challenges.value, null, 2)}</pre>
    </div>
  );
});

```

It this an issue on my end(Am I including the package incorrectly) or is it an issue on Qwik/Functions side?

### Reproduction

N/A - Firebase project required

### Steps to reproduce

Start a new qwik project, add and configure the Firebase integration, add `@google-cloud/firestore` or `firebase-admin` package, try executing FIrestore queries in `routeLoader$`, upload to Firebase Hosting + Firebase Functions, opening a route that utilizes `routeLoader$` should result in an `Error 500 - Internal Server Error`.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 102.78 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.9.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 17.0
  npmPackages:
    @builder.io/qwik: ^1.2.13 => 1.2.13 
    @builder.io/qwik-city: ^1.2.13 => 1.2.13 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

**Comment by gioboa** [comment]
Thanks for opening this issue. Would you like to open a PR for that? I can help you with the process if you want.

**Comment by mhevery** [comment]
Actually, I don't think this is an issue with QwikCity but with FB. `ClientPool.clientFactory` is firebase code, not Qwik-City code. The `/@qwik-city-plan-c264a646.mjs:167322:43` is misleading as it is the default name of the bundle, which contains all of the code, including Firebase.

**Comment by vdemcak** [comment]
> Actually, I don't think this is an issue with QwikCity but with FB. `ClientPool.clientFactory` is firebase code, not Qwik-City code. The `/@qwik-city-plan-c264a646.mjs:167322:43` is misleading as it is the default name of the bundle, which contains all of the code, including Firebase.

I've opened an issue on the [googleapis/nodejs-firestore](https://github.com/googleapis/nodejs-firestore/issues/1929) repo and they've confirmed that it's an issue on their side. I'm closing the issue and thanks for your help and time.

**Comment by gioboa** [comment]
Thanks for the update 👍
