### ISSUE TITLE
[🐞] Dynamic class change doesn't work in version "@builder.io/qwik" 1.2.14, but works in version 1.2.13

### ISSUE THREAD

**Issue by notcod** [BuilderIO/qwik#5356]
### Which component is affected?

Qwik Runtime

### Describe the bug

Code bellow works fine on version ...13, but not in version ...14

**Qwik 14 doesn't change class on click, but only on page referesh**

```
export const NavLink = component$<LinkProps>((props) => {
  const location = useLocation();
  const pathname = location.url.pathname;
  return (
    <>
      <li>
        <Link {...props}
          class={[
            props.class as string,
            "block rounded py-2 pl-3 pr-4 transition-[hover] hover:bg-gray-100 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:p-0 lg:hover:bg-transparent lg:hover:text-violet-700 lg:dark:hover:bg-transparent lg:dark:hover:text-blue-500",
            pathname == props.href ? "text-[red]" : "text-gray-900",
          ]}
        >
          <Slot />
        </Link>
      </li>
    </>
  );
});
```

### Reproduction

@builder.io/qwik

### System Info

```shell
Debian 12
```

**Comment by gioboa** [comment]
Hi @notcod can you recreate the case in [qwik.new](https://qwik.new/) pls?

**Comment by wmertens** [comment]
@notcod I tried to recreate in [this playground](https://qwik.builder.io/playground/#v=1.2.14&f=7VZNi8IwEP0rszkl0M1h2d3DYrrnXfwCvYkHD2kpqCkWQQn9785kahOlB6%2BCh9LQziTz8fLmJaD5%2FvwaAk0GhOMszuBHUMRZj2kGmmSvEY6cXMo6lGGEbJb%2FQYmVQU5ECusEhf9fzKaa9UJVnGWdBXLL4EO1CDZ0UnfnzAcPod2G6x2KEILzWutg2PY%2FgBWN8avkE3BwmsXOhmRCAPCNiSiqE436YEP824hbA96jaibW1vALYodvAT8g9u49rFPzdQwpNhXjpm7EvlI3KZNrR%2FF57Cp32qsqsXZ9a2Wx2TZWJTe9Qwxrvih1vFQmR2eNLHi05q1ftvnSleXW9jKR%2FefgsMcHIwrnBM4eqoDx0YsTImC26sUjT8gjFw) but it seems to work fine with a signal

**Comment by mhevery** [comment]
Yes, we need a minimal repro to look at this. Also, you can help us by pin-pointing the exact change that caused it by bisecting the change. 

All builds are here: https://github.com/BuilderIO/qwik-build

you can update your `package.json` like this:
```
-    "@builder.io/qwik": "^1.2.6",
+    "@builder.io/qwik": "BuilderIO/qwik-build#SHA",
```

Where SHA can be gotten from https://github.com/BuilderIO/qwik-build/commits/main

**Comment by notcod** [comment]
On qwik.new it looks like it works fine, but on my PC following all this steps:

- npm create qwik@latest
- change /src/routes/layout.tsx => https://gist.github.com/notcod/ec770329fb54197811a6369723ef9a6b
- navigate to page /demo/flower/ - URL changes, page changes without refresh, but just class doesn't change to "text-red", when I refresh page, than class is correct:
Before refresh:
![image](https://github.com/BuilderIO/qwik/assets/77313746/954812ec-33d8-4e27-a042-8806e49fd061)

After refresh:
![image](https://github.com/BuilderIO/qwik/assets/77313746/f35cdaf7-f40d-42c9-b760-91e09b947d72)

It looks like class is changing only on server 
...............................
But when I update package.json:
```
  "devDependencies": {
    "@builder.io/qwik": "1.2.13",
    "@builder.io/qwik-city": "1.2.13", 
```
npm update && npm run dev

It works fine and change class like it should

**Comment by notcod** [comment]
> Yes, we need a minimal repro to look at this. Also, you can help us by pin-pointing the exact change that caused it by bisecting the change.
> 
> All builds are here: https://github.com/BuilderIO/qwik-build
> 
> you can update your `package.json` like this:
> 
> ```diff
> -    "@builder.io/qwik": "^1.2.6",
> +    "@builder.io/qwik": "BuilderIO/qwik-build#SHA",
> ```
> 
> Where SHA can be gotten from https://github.com/BuilderIO/qwik-build/commits/main

f9336a725265a55a6efd0661f73eadc5eea5f72d => WORKS
3abb783b1785a60bdfd1c4001e3dba2de9828e37=> DOESN'T WORK

**Comment by wmertens** [comment]
@notcod thank you! Too bad it's that commit 🥹. I'll check it out.

**Comment by notcod** [comment]
> @notcod thank you! Too bad it's that commit 🥹. I'll check it out.

It looks like you messed up, and I can see it's really big commit 😬🥺
I'm sorry.

**Comment by notcod** [comment]
But I don't understand how it works on qwik.new?
Try to re-create problem using my gist.
`/src/routes/layout.tsx => https://gist.github.com/notcod/ec770329fb54197811a6369723ef9a6b`

**Comment by wmertens** [comment]
the worst thing is that it was squashed :sob:
Luckily I have the original commits still. I really don't like squashing.

**Comment by notcod** [comment]
I wish I knew JS better to help you. But I'm a primary PHP dev. I tried a few other attributes, and it works fine, just with "class" it doesn't work, maybe it will help you to find solution faster

**Comment by mhevery** [comment]
@wmertens thanks for looking into this.

**Comment by jessezhang91** [comment]
I ran into a very different issue that broke at the same exact commit that @notcod found.

Replication (1.2.14): https://stackblitz.com/edit/qwik-starter-1mtn8m?file=package.json,src%2Froutes%2Fpagination.tsx
Click a link, it should change that one to "active". Strangely if you comment out the `useLocation()` it works.

Previous Working (1.2.13): https://stackblitz.com/edit/qwik-starter-nwtwum?file=package.json,src%2Froutes%2Fpagination.tsx
Click a link, it will change that one to "active".

I'm not sure if there's a more direct replication. I tried to simplify it down further and it seemed to work fine. Only when I added the `useLocation` did things break.

I would've filed a different bug but the fact it matched exactly the same commits from this thread makes me think its the same underlying issue.

**Comment by notcod** [comment]
It makes no sense to use the `onClick$` event. Yes, it works, but I don't think it's necessary to complicate the code. I'll stick with version 13 until the dev team fixes the issue.

**Comment by wmertens** [comment]
Thank you, that helps a lot to narrow down the problem

**Comment by wmertens** [comment]
Thank you, that helps a lot to narrow down the problem

**Comment by jessezhang91** [comment]
@wmertens here's a spec replicating this issue: https://github.com/BuilderIO/qwik/compare/main...jessezhang91:qwik:jz/issue5356-spec

I tried to look through your commit but have no idea where to exactly begin debugging this issue. I suspect it has something to do with the refactored `findParentCtx` and perhaps how that plays with loops but that's just a pure guess given the replication.

**Comment by jessezhang91** [comment]
Oh that's super cool! Thanks for the tip!

Looking at that, I wonder if the way the signal is being passed in could be affecting how the component wakes up (the map case doesn't have `_fnSignal` while the array case does).

For the 3 variations:
* w/ loop and w/ context, not working: no `_fnSignal` => maybe not subscribing to the signal and waking up to react to client-side changes?
* w/o loop and w/ context, working: has `_fnSignal` => i'm wondering if this hints to serializing a subscription?
* w/ loop and w/o context, working: no `_fnSignal` but also no `useContext` so it doesn't call the bit of code that replaces `$parentCtx$` with a further up ancestor? (`ctx.$parentCtx$ = getParentProvider(ctx.$parentCtx$, containerState);`)

**Comment by wmertens** [comment]
So actually the subscriptions are already serialized during SSR, so that when a signal changes the loader knows which functions to run. It seems that useContext interferes with the listener registration somehow. Maybe I missed a parentCtx use, I thought it was only used to figure out the nearest contextProvider.

**Comment by notcod** [comment]
I come back to work on project with version "1.2.16" and to try to fix issue.
Something strange is going on or you fixed something?
![image](https://github.com/BuilderIO/qwik/assets/77313746/71d3c210-90d1-4ecc-97b8-5fc0f865b1e4)
Component "NavLink" works fine, but "NavLink2" doesn't work. Only difference is that I removed pathname in const and used "location.url.pathname == props.href"

**Comment by wmertens** [comment]
@notcod no, no fix yet, I'm working on it.

**Comment by wmertens** [comment]
@notcod @jessezhang91 many thanks for your assistance, it should be fixed in 1.2.17. My great idea for skipping straight to parents with defined contexts was not :)

**Comment by wmertens** [comment]
FYI the build just landed on qwik-build if you want to try

**Comment by jessezhang91** [comment]
Just tested it w/ the latest SHA on qwik-build and my original issue is gone! Thank you!
