### ISSUE TITLE
[🐞] deploy integration node Cannot find package 'undici' imported from entry.node-server.mjs

### ISSUE THREAD

**Issue by sysmat** [BuilderIO/qwik#5369]
### Which component is affected?

Qwik Runtime

### Describe the bug

- npm run qwik add node
- npm run build
- folder server & dist are build
- copy folders to my serever & run  `node entry.node-server` I get error:

```
Cannot find package 'undici' imported from entry.node-server.mjs
```

### Reproduction

aaa

### Steps to reproduce

- npm run qwik add node
- npm run build
- folder server & dist are build

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 10.88 GB / 31.75 GB
  Binaries:
    Node: 18.18.2  
    Yarn: 1.22.19 
    npm: 10.0.0
    pnpm: 8.10.0 
  Browsers:
    Chrome: 118.0.5993.118
    Edge: Spartan (44.22000.120.0), Chromium (118.0.2088.76)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @builder.io/qwik: ^1.2.15 => 1.2.15
    @builder.io/qwik-city: ^1.2.15 => 1.2.15
    undici: ^5.27.0 => 5.27.0
    vite: ^4.5.0 => 4.5.0
```

### Additional Information

https://qwik.builder.io/docs/deployments/node/#production-deploy should be more detailed on how to deploy if this meta-framework be more used

**Comment by mhevery** [comment]
may be fixed by https://github.com/BuilderIO/qwik/pull/5042

**Comment by gioboa** [comment]
This is the `entry.node-server.mjs` file.

<img width="889" alt="Screenshot 2023-11-01 at 08 58 33" src="https://github.com/BuilderIO/qwik/assets/35845425/a9ce4a29-089a-49ba-bb0b-13c9a084c931">

it looks for an external deps so you need to have them in the `node_modules` folder in the same location of your `entry.node-server` file.

**Comment by sysmat** [comment]
- @gioboa thx, I'm new to this meta-framework
- it would be super in integration & build create node_moduls with dependencies which are actually needed

**Comment by sysmat** [comment]
undici are devDependencies but actually  needed at runtime

**Comment by gioboa** [comment]
we can close this issue because it's working as expected.
You can create a PR for you proposal if you want 💪

**Comment by wmertens** [comment]
> undici are devDependencies but actually needed at runtime

This depends on your deploy environment. Undici is an implementation of `fetch`, it's included in recent node versions. So if you need it in prod you need to add it to your dependencies yourself.

**Comment by sysmat** [comment]
ok, but many building tools do it. I don't know this framework, just experimenting with it. Maybe I'll try to do it(rollup, vite, esbuild are basic building blocks do do it?)

**Comment by gioboa** [comment]
> ok, but many building tools do it. I don't know this framework, just experimenting with it. Maybe I'll try to do it(rollup, vite, esbuild are basic building blocks do do it?)

The first idea on top of my head is to create a `post build` [Vite plugin](https://vitejs.dev/guide/api-plugin.html#plugin-ordering) that do this things automatically.
