### ISSUE TITLE
Qwik Vercel Edge functions not working with server functions

### ISSUE THREAD

**Issue by Nedimko123** [BuilderIO/qwik#5373]
My qwik version is `1.1.5`
It always throws error even when I tried a blank server$ function
In Development mode everything works, though!

```
  const testServer = server$(async () => {
    try {
      const res = await axios.get(
        "https://jsonplaceholder.typicode.com/todos/1"
      );
      return res.data;
    } catch (error) {
      throw "Vercel is so bad";
    }
  });
```

**Comment by mhevery** [comment]
can you upgrade to the latest and provide a repro?

**Comment by Nedimko123** [comment]
> can you upgrade to the latest and provide a repro?

Hopefully this helps someone:

Seems like WE CANNOT use AXIOS with edge function, we need to convert all axios functions to regular FETCH ones

It's a limitation of Edge Functions in General.

References:
https://vercel.com/docs/functions/edge-functions/edge-runtime
https://vercel.com/guides/library-sdk-compatible-with-vercel-edge-runtime-and-functions#library-recommendations
