### ISSUE TITLE
[✨] qwik-labs types: Needs to support base prefix

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#5417]
### Is your feature request related to a problem?

When you set `config.base` in vite config, this makes sure your app gets served from that base url. The setting is available in the app itself at [`import.meta.env.BASE_URL`](https://vitejs.dev/guide/env-and-mode.html#env-variables).

### Describe the solution you'd like

[untypedAppUrl](https://github.com/BuilderIO/qwik/blob/eaf939fda440f5bf75e8bf16d0b4df176001a56f/packages/qwik-labs/src/qwik-types/public-api.ts#L2) needs to support the base.

Not sure what that entails, perhaps it must make sure that the returned URLs always start with the base?

### Describe alternatives you've considered

The alternatives would be:
- no change needed, everything already works maybe?
- the programmer needs to include the base into all the URLs in the app, manually.

### Additional context

I'm just creating this issue because I notice it might be a problem. Setting base is probably somewhat rare.

**Comment by tera-ny** [comment]
Hi @wmertens  
I want to contribute to the qwik community, so I will work on this issue. 🚀

**Comment by tera-ny** [comment]
I would be happy to have a review when you have time.  (#5615)
