### ISSUE TITLE
[🐞] Qwik sends server version of components to browser (instead of browser version)

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#5418]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I have a npm package that exports Qwik components. I want to have server, browser and edge versions of each. I use the `exports` key in `package.json` to dictate which one should be used.

When importing this package in a Qwik webapp, it will always send the server version of a component to the browser instead of the browser version.

### Reproduction

https://github.com/samijaber/qwik-monorepo-playground/tree/qwik-server-import

### Steps to reproduce

- pnpm i
- cd app
- pnpm dev

Look at the console logs, and the network tab: `qwik-monorepo-playground/lib/lib/node/index.qwik.mjs` gets sent to the browser instead of `qwik-monorepo-playground/lib/lib/browser/index.qwik.mjs`

<img width="1350" alt="CleanShot 2023-11-10 at 11 32 28@2x" src="https://github.com/BuilderIO/qwik/assets/1393142/3e209f2e-c3e9-4c0d-ac97-12525dacae15">

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 394.16 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 21.1.0 - ~/.asdf/installs/nodejs/21.1.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/21.1.0/bin/yarn
    npm: 10.2.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.10.2 - ~/.asdf/installs/nodejs/21.1.0/bin/pnpm
    Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 118.1.59.124
    Chrome: 119.0.6045.123
    Safari: 15.2
  npmPackages:
    @builder.io/qwik: ^1.2.17 => 1.2.17 
    undici: ^5.26.0 => 5.27.2 
    vite: ^4.4.11 => 4.5.0
```

**Comment by mhevery** [comment]
Qwik always sends what is in the  `package.json` `qwik` property. In your case 
```
"qwik": "./lib/browser/index.qwik.mjs",
```

If you want to control sending different code to client vs server use 

```
import {isServer} from '@builder.io/qwik/build';

export MyFn = isBrowser ? fnA : fnB;
```

Keep in mind that `isBrowser` is dynamic until there is full build at which point it should tree shake the other branch.

**Comment by samijaber** [comment]
> Qwik always sends what is in the `package.json` `qwik` property. In your case
> 
> ```
> "qwik": "./lib/browser/index.qwik.mjs",
> ```

But as per my github issue, Qwik is actually sending `/lib/node/index.qwik.mjs`. It does not respect the `qwik` property.

**Comment by mhevery** [comment]
Difference between dev mode vs build mode.
