### ISSUE TITLE
Type error when extending component with generic prop [🐞]

### ISSUE THREAD

**Issue by guzart** [BuilderIO/qwik#5422]
### Which component is affected?

Qwik Runtime

### What I am doing:

I want to extend a component that accepts a generic Prop object. 

```tsx
// Message.tsx
import { component$ } from "@builder.io/qwik";

export type MessageProps<T> = {
  message: T | undefined;
  style?: string;
}

export const Message = component$(function <T>(props: MessageProps<T>) {
  const { message, ...other } = props;
  return <div {...other}>{message?.toString()}</div>
})
```

```tsx
// ColoredMessage.tsx

import { component$ } from "@builder.io/qwik";
import { Message, type MessageProps } from "./Message";

type Props<T> = MessageProps<T> & {
  color: string;
}

export const ColoredMessage = component$(function <T>(props: Props<T>) {
  // The TS error appears in '<Message'
  return <Message {...props} style={`color: ${props.color};`} />
})
```

### What I expect:

No error 😄 .

### What's actually happening:

I receive this error:

```
Type '{ style: string; message: T | undefined; color: string; }' is not assignable to type 'IntrinsicAttributes & TransformProps<MessageProps<T>> & ComponentBaseProps & { children?: JSXChildren; }'.
  Type '{ style: string; message: T | undefined; color: string; }' is not assignable to type 'TransformProps<MessageProps<T>>'.
    Types of property 'message' are incompatible.
      Type 'T | undefined' is not assignable to type 'TransformProp<T | undefined>'.
        Type 'undefined' is not assignable to type 'TransformProp<T | undefined>'.
```

```
Type 'T | undefined' is not assignable to type 'TransformProp<T | undefined>'.
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-cyipju?file=src%2Fcomponents%2FColoredMessage.tsx

### Steps to reproduce

It renders correctly, the error appears on the editor.

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.23 GB / 64.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.8.0 - ~/.asdf/installs/nodejs/20.8.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 10.1.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.10.30.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 119.1.60.114
    Chrome: 119.0.6045.123
    Firefox: 119.0.1
    Safari: 17.1
```

### Additional Information

Thank you!

**Comment by wmertens** [comment]
TypeScript doesn't work that way - you can't make a constant generic and all Qwik Components are constants.

Here's an approach that might work for you: https://qwik.builder.io/playground/#v=1.1.5&f=7VY9a8MwEN39K4Qo%2BQCjDh0Kjq0MpUOHbtlKIaVxITR1SpQMwdF%2Fz9PpFNly%2FkAgo8%2BW7r13d8%2FXaZrnJ5TvUbzXxmC6XCgqHbshFxfzzAnTGwq%2Bbsz6%2B3VTe1Pmisi0gjKqQnXnTGjpf1MuNPRxyvz5aCEW4iRg6fUPnGU1wxuyy3nBqwTgi9F1BB9j7Crjz6QGnA5pIpuyh%2BHQ%2FOI%2F2mg9mdByc6mWv6AN2HKhlNrCyHfgWvlFyAEM44Hsog2fWN3ysbnah9aaWr9PYW6yDKK%2FbDew6lVX%2B4w06oiTyjViaDjZ0SQh3b%2B4x51JFpwjkB8MezjrGNEJG5akJSd%2FaCmu6NHOltb1nWPW1%2F84AJMEvkxsrtKj8ry0Hkw1XKnS5eBOglBJRGSoViVpgCRATe8edYMedQY

```tsx
// Message.tsx
import { component$, Component, QwikIntrinsicElements } from "@builder.io/qwik";

export type MessageProps<T> = {
  message: T | undefined;
  style?: string;
} & QwikIntrinsicElements['div']

export const Message = component$<MessageProps<unknown>>((props) => {
  const { message, ...other } = props;
  return <div {...other}>{message?.toString()}</div>
})

// ColoredMessage.tsx

type Props<T> = MessageProps<T> & {
  color: string;
}

export const ColoredMessage = component$((props: Props<unknown>) => {
  return <Message {...props} style={`color: ${props.color};`} />
})

export const MyColoredMessage = ColoredMessage as Component<Props<string>>

export default (()=><MyColoredMessage color="red" message="Hello" />)
```

**Comment by guzart** [comment]
Thank you for your response @wmertens! Your solution solves my immediate problem!

What I really want to accomplish is to let TypeScript infer the type of a property based on the type of the property that was passed to the component. Do you know if there's a way to do it without having the end user do a type assertion?

For example, the way it's accomplished in Headless UI [radio group component](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/radio-group/radio-group.tsx#L491-L507) ([demo](https://playcode.io/1660351)).

As I understand it, they are doing a type assertion on the returned component to "force it" to work with TypeScript inference. I tried doing a similar type assertion for Qwik, but doing a type assertion and the functions returning [`Component`](https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/core/component/component.public.ts#L46) did not work.

I have to admit that I am very ignorant when it comes to TypeScript types, so this is probably a basic question on my part. But when you mention "you can't make a constant generic" why is it that Qwik components are constants? I thought that "React-ish" components were at their core functions with a signature of `(props) => object`. So I thought it would be similar to something like this:

```js
const smth = <T>(message: T) => { console.log(String(message)) }

smth(4) // TS infers T is number
smth('hello') // infers T is string
```

**Comment by guzart** [comment]
In this [new StackBlitz](https://stackblitz.com/edit/qwik-starter-rjvx2l?file=src%2Fcomponents%2FColoredMessage.tsx) I added two components that use the generic component and TypeScript is able to correctly infer the types for the `onClick$` parameter based on the type of a given property. Looks like the issue is when I try to passthrough the received properties into a children component.

```ts
export const ColoredMessage = component$(function <T>(props: Props<T>) {
  return (
    <Message 
        // Type checking fails here
        message={props.message} 
        // but not here
        onClick$={props.onClick$} 
        style={`color: ${props.color};`} 
     />
  )
})
```

Could this be related to how Qwik types are defined to ensure components props are serialized correctly?

**Comment by wmertens** [comment]
You need to "instantiate" each generic component with the proper type, like the MyColoredMessage above, or maybe do lots of overriding.

The problem stems from the fact that you can only specify generics on a function definition, not on a function constant. And a Qwik Component is always a function constant.

**Comment by wmertens** [comment]
@guzart I was wrong, you can do generics for component$. Here's an example:

```tsx
    export const Poly = component$(
      <C extends keyof QwikIntrinsicElements>({
        as,
        ...props
      }: { as?: C } & QwikIntrinsicElements[C]) => {
        const Cmp = (as || 'div') as any as FunctionComponent<typeof props>;

        return <Cmp {...props}>hi</Cmp>;
      }
    );

    <Poly as="a" href="foo" />
    // <Poly<'a'> as="a" href="foo" /> also works
```

But the current types don't work for this. I made https://github.com/BuilderIO/qwik/pull/5672 to fix that
