### ISSUE TITLE
[🐞]  Issue with list item keys not updating in DOM

### ISSUE THREAD

**Issue by samwalters3** [BuilderIO/qwik#5428]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am experiencing an issue where list items are not updating correctly in the DOM when using the Qwik framework. Despite using unique keys for each list item, the changes are not reflected in the rendered output. The `key` attribute seems to be ignored, and instead, I see `data-qwik-inspector` attributes with no `q:key` present in the `<li>` tags.

### Reproduction

https://stackblitz.com/edit/qwik-starter-qsgti2?file=src%2Froutes%2Fadd-names%2Findex.tsx

### Steps to reproduce

1. Use the button to add the input field's text to the list.
2. Observe that the list in the DOM does not contain q:key which force the client to render all the items

### System Info

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 3.03 GB / 7.67 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.9.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
  npmPackages:
    @builder.io/qwik: ^1.2.17 => 1.2.17
    @builder.io/qwik-city: ^1.2.17 => 1.2.17
    @builder.io/qwik-react: 0.5.0 => 0.5.0
    undici: ^5.26.0 => 5.27.2
    vite: ^4.4.11 => 4.5.0
```

### Additional Information

I have followed the recommended practices for list rendering in Qwik, but the issue persists. Any guidance or assistance in resolving this would be greatly appreciated.

Thank you for your help!

**Comment by wmertens** [comment]
To see the q:key you need to pause the container.
It seems to work correctly for me, how do you know everything re-renders?
You can copy this code into the playground, that's faster to play with and you can see the console logs from server and client to detect renders.

Iterating over the list will always cause re-rendering of the parent component.

**Comment by samwalters3** [comment]
Thanks for your response. I'm a bit confused. If an <li> item has a unique key, doesn't that prevent it from re-rendering when we push a new item to the array? I'm concerned about the potential performance impact on the client side when rendering a large number of list items

**Comment by wmertens** [comment]
@samwalters3 See https://qwik.builder.io/playground/#v=1.2.17&f=7VZNS8QwEP0rsQhtIdsFL%2BqyKXj07kWWRYS6rFjtghSR0v%2Fue5Nk0hYPexXsqW3mI5O8efMmoLm5vv0NNFZHrjVnIchXfM%2Fx42YwGoRqrBDQWLqa5zCd0bk%2Ffxx9DiPalhPMta%2F1IJ7bNV4BuPMgGzSG0LvTUgouGSRBXz6gfzYmz63%2FRXbcmN0epBVEy27PJSJc4z03TShwmgveB1NIrkpDV4jxDpsL55DE441PMGO66tR%2FHpd%2BSDczjP%2BRM8dpc2VM25rjiVItXrw4KirAWj3kzSImA%2FmHDekyUkqm%2F7oP0VOXbiierMHgJ3dJ0cs9Y29huZJEZQp8aqFCjh0x47JHihFOqJREZKTLvlYHDjLwuCiJ1VW0SEj2%2BjPJriFcxljfNRiyneGEV5kavfo2tUYsX84eYq0o%2BBoxJ4WpLVzlpt9evp0H8CgYwQdzeh9d0V2iv7T47Tom9yI6NN8%2FY%2F5JxvwB

To iterate over the list, the render function needs to run, but as you can see each list item only renders once when added. Iterating over the items happens in the vDOM only.
