### ISSUE TITLE
[✨] add property named include for qwikVite using glob pattern file matching

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/qwik#5436]
### Is your feature request related to a problem?

In Astro, you can use multiple JSX based frameworks, including Qwik.

https://github.com/QwikDev/astro/issues/13

Unfortunately, additional config is needed for multiple JSX frameworks to work together.

The Astro docs approach to doing this is an `include` option with a glob pattern of where the framework component files are.

```tsx
import { defineConfig } from 'astro/config';
import preact from '@astrojs/preact';
import react from '@astrojs/react';
import svelte from '@astrojs/svelte';
import vue from '@astrojs/vue';
import solid from '@astrojs/solid-js';

export default defineConfig({
  // Enable many frameworks to support all different kinds of components.
  // No `include` is needed if you are only using a single framework!
  integrations: [
    preact({
      include: ['**/preact/*']
    }),
    react({
      include: ['**/react/*']
    }),
    solid({
      include: ['**/solid/*'],
    }),
    qwik({ /* haven't set this up yet */ })
  ]
});
```

This is needed to prevent conflicts and ensure correct processing when using multiple JSX frameworks in the same project, as each framework can handle its own specific files/folders.

What this also means is each integration must customize this option under the hood. 

For example, in the Solid integration they do this:

```tsx
plugins: [ solid({ include, exclude, dev: isDev, ssr: true }),    {
name:
  '@astrojs/solid:config-overrides', enforce : 'post', config() {
    return {
    esbuild : {  // To support using alongside other JSX frameworks, still let
   // // esbuild compile stuff. Solid goes first anyways. include:
   // /\.(m?ts|[jt]sx)$/,       },      };     },    },   
],
```

And then in their vite plugin:

```tsx
export interface Options {
  /**
   * A [picomatch](https://github.com/micromatch/picomatch) pattern, or array of patterns, which specifies the files
   * the plugin should operate on.
   */
  include?: FilterPattern;
```

Which uses this library:
https://github.com/micromatch/picomatch

### Describe the solution you'd like

An include option that can be taken directly from the astro config and supplied to qwikVite

For example:
```tsx
import { defineConfig } from 'astro/config';
import preact from '@astrojs/preact';
import react from '@astrojs/react';
import svelte from '@astrojs/svelte';
import vue from '@astrojs/vue';
import solid from '@astrojs/solid-js';
import qwik from '@qwikdev/astro';

export default defineConfig({
  // Enable many frameworks to support all different kinds of components.
  // No `include` is needed if you are only using a single framework!
  integrations: [
    preact({
      include: ['**/preact/*']
    }),
    react({
      include: ['**/react/*']
    }),
    solid({
      include: ['**/solid/*']
    }),
    qwik({ include: ['**/qwik/*'] })
  ]
});
```

```tsx
// up top
export default function createIntegration(include): AstroIntegration

plugins: [
  qwikVite({
    include
  }),
],
```

### Describe alternatives you've considered

Being fixed in Astro core. This does seem like a separation of concerns issue. Renderers should not be able to perform actions with files other renderers, especially when it knows their entrypoints.

That said, I am unsure of how this implementation would look on the Astro side.

**Comment by mhevery** [comment]
Seems like this has been roslved with https://github.com/QwikDev/astro/pull/20 and should be closed?

**Comment by thejackshelton** [comment]
> Seems like this has been roslved with [QwikDev/astro#20](https://github.com/QwikDev/astro/pull/20) and should be closed?

I believe the initial scaffolding was set up, but we still need the include option with the wildcard paths for qwikVite.

> The include would definitely be required because JSX needs to be compiled correctly for each framework. That part has to be configured by the user because it happens during Vite’s compilation stage instead of during rendering.

**Comment by mhevery** [comment]
OK, want to take a stab at a PR?
