### ISSUE TITLE
[🐞] Tailwind with scoped CSS doesn't work

### ISSUE THREAD

**Issue by VarPDev** [BuilderIO/qwik#5441]
### Which component is affected?

Qwik Runtime

### Describe the bug

I added tailwind and tried using css in scoped CSS mode (as per the [documentation](https://qwik.builder.io/docs/components/styles/#scoped-css)).
If in the css I use the syntax `@apply <class-name>` tailwind does not work.

### Reproduction

Here you can see the tag h1 not change text color
https://stackblitz.com/edit/qwik-starter-gez3tf?file=src%2Fcomponents%2Fstarter%2Fhero%2Fhero.tsx

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 101.13 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v21.1.0/bin/yarn
    npm: 10.2.0 - ~/.nvm/versions/node/v21.1.0/bin/npm
    pnpm: 8.10.4 - ~/.nvm/versions/node/v21.1.0/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 16.2
  npmPackages:
    @builder.io/qwik: ^1.2.15 => 1.2.15 
    @builder.io/qwik-city: ^1.2.15 => 1.2.15 
    undici: ^5.26.0 => 5.27.0 
    vite: ^4.4.11 => 4.5.0
```

**Comment by wmertens** [comment]
@VarPDev what was the issue?

**Comment by VarPDev** [comment]
@wmertens my bad, in my local environment doesn't work tailwind with scoped css, initially also on stackblitz, but I realized that I had forgotten a configuration file and now on stackblitz it works while locally it doesn't.
So I'll try to understand why

**Comment by VarPDev** [comment]
I found the difference between stackblitz and my local
In local env the icon class becamo scoped for the component changing name but not change on the html generated so the class doesn't match
in stackblits this doesn't happen

the css in styles variable in LOCAL env:
```
._icon_mcn59_1 {
  /* absolute */
  left: 0px;
  top: 0px;
  bottom: 0px;
  display: flex;
  height: 3rem;
  align-items: center;
  padding-left: 0.75rem;
}

._icon_mcn59_1 svg {
  height: 100%;
}
```

the css in styles variable on stackblitz:
```
h1 {
  --tw-text-opacity: 1;
  color: rgb(220 38 38 / var(--tw-text-opacity));
}

h2 {
  color: green;
}
```

**Comment by wmertens** [comment]
@VarPDev You're confusing modules and scoped styles, and also, classnames can change but element tags can't.

By importing from .module.css, you're getting an object with attributes for each class, because the classes got renamed. So you need to use `${styles.icon}` instead of `"icon"`.
However, you're also adding `?inline`, which gives you only the css text.

So you need to use .module.css without inline, which will include the css into the global css. If you want to use inline but scoped, you have to use `useStylesScoped$`

**Comment by VarPDev** [comment]
@wmertens yes I got confused and it confused me even more to see that on stackblitz although the css file was a module it worked as if it was scoped. Renaming the file and using it as scoped locally works but I remain confused by stackblitz
