### ISSUE TITLE
[🐞] Exclusive Props type breaks HTMLAttributes?

### ISSUE THREAD

**Issue by iivvaannxx** [BuilderIO/qwik#5447]
### Which component is affected?

Qwik Runtime

### Describe the bug

# What I need?

I am trying to create a simple wrapper component over two HTML elements. These are `<input>` and `<textarea>`, it's something I successfully did in the past with React and some other framework. But I can't get Qwik to **type safely** let me do this.

The concept is simple, I have a TSX component that can be either one of the two elements mentioned above. This is decided through a `multiline` prop. According to the types I will write below, this prop can either be always `true` or not be defined at all. If true (or defined) the component should render the `<textarea>`, otherwise the `<input>`.

Because it is a wrapper element, I may want to enforce some properties or add some extra ones, but the main intention is to allow the native attributes as props, then type-check them using an exclusive OR (XOR) type. This **forbids the two types to overlap**, ensuring that native props of each element will not get mixed. 

For example, the `rows` attribute of  a `<textarea>` wouldn't work if the `multiline` prop is not present, as the component is expecting the native attributes of an `<input>` element exclusively. This would work exactly the same the other way around, let's say for the `type` attribute of an `<input>`, if the `multiline` prop is present, then the props would not be valid as the component is expecting the native attributes of a `<textarea>` exclusively and `type` isn't one of them. 

# The problem

Any of the `XOR` types I tried work as I would expect. I tried the types from the [`ts-xor`](https://github.com/maninak/ts-xor) and [`ts-essentials`](https://github.com/ts-essentials/ts-essentials) packages with no success. Neither does a manual XOR type declaration.

I expect it to work out of the box, because I tried the exact-same code, but adapted to React, and it works. See the examples below.

# Type declarations

This is how the type definitions look like:

```ts
// --- Using the XOR type from the 'ts-essentials' library. ----------------------

type Without<Type1, Type2> = { [P in Exclude<keyof Type1, keyof Type2>]?: never };

type XOR<Type1, Type2> = Type1 | Type2 extends object
  ? (Without<Type1, Type2> & Type2) | (Without<Type2, Type1> & Type1)
  : Type1 | Type2;

// --- See: https://github.com/ts-essentials/ts-essentials/blob/master/lib/xor/index.ts --------------------

/** Props for when the component is an <input>. */
interface InputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'children'> {

  // Enforce the type.
  type: string
}

/** Props for when the component is a <textarea> */
interface TextAreaProps extends Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'children'> {

  // Enforce a true 'multiline' attribute.
  multiline: true
}

type Props = XOR<InputProps, TextAreaProps> & {

  // --- Some common props down here ---

  // Enforce the name.
  name: string
}
```
This is how they look in my machine and with the React example. The Qwik example forced me to use different types (`QwikIntrinsicElements`) because couldn't find these ones. However the Typescript error still persisted.

# Examples

React Example: https://stackblitz.com/edit/vitejs-vite-tmh53x?file=src%2FTextField.tsx
Qwik Example: https://stackblitz.com/edit/qwik-starter-tkdn9c?file=src%2Fcomponents%2Ftext-field.tsx

Is the exact same component, in React the types are just fine, but not with Qwik. It seems to overwrite the types of the native attributes with `PropFnInterface<unknown[], unknown> | undefined`, and I don't think that should be expected behaviour.

This is the full error message for the `cols` property that I receive in my machine:

```log
Type '{ 'aria-required': boolean | undefined; 'aria-invalid': boolean; 'aria-errormessage': string; class: string; cols?: PropFnInterface<unknown[], unknown> | undefined; dirName?: PropFnInterface<unknown[], unknown> | undefined; ... 261 more ...; error: string; } | { ...; }' is not assignable to type 'TextareaHTMLAttributes<HTMLTextAreaElement>'.
  Type '{ 'aria-required': boolean | undefined; 'aria-invalid': boolean; 'aria-errormessage': string; class: string; cols?: PropFnInterface<unknown[], unknown> | undefined; dirName?: PropFnInterface<unknown[], unknown> | undefined; ... 261 more ...; error: string; }' is not assignable to type 'TextareaHTMLAttributes<HTMLTextAreaElement>'.
    Types of property 'cols' are incompatible.
      Type 'PropFnInterface<unknown[], unknown> | undefined' is not assignable to type 'number | undefined'.
        Type 'PropFnInterface<unknown[], unknown>' is not assignable to type 'number'.
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-tkdn9c?file=src%2Fcomponents%2Ftext-field.tsx

### Steps to reproduce

No need to start the project, just look into `src/components/text-field.tsx` and see the Typescript error.

![image](https://github.com/BuilderIO/qwik/assets/47715589/147f0b04-3691-4968-be2b-f1b140504394)

### System Info

```shell
Qwik Example Stackblitz:

System:
    OS: Linux 5.0 undefined
    CPU: (7) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.9.2 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.2.11 => 1.2.11 
    @builder.io/qwik-city: ^1.2.11 => 1.2.11 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7

My Machine:

System:
    OS: Linux 6.1 NixOS 23.05 (Stoat) 23.05 (Stoat)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 6.57 GB / 15.56 GB
    Container: Yes
    Shell: 5.2.15 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 18.17.1 - /etc/profiles/per-user/iivvaannxx/bin/node
    pnpm: 8.8.0 - /etc/profiles/per-user/iivvaannxx/bin/pnpm
    bun: 1.0.7 - /nix/store/77xfz4sy5rdjy7lh29nydg6g67gnmx7z-bun-1.0.7/bin/bun
  Browsers:
    Brave Browser: 118.1.59.117
  npmPackages:
    @builder.io/qwik: ^1.2.17 => 1.2.17
```

### Additional Information

The React example may flag an error over the `<textarea>` element saying that "it's not defined", don't know why. If it does, simply erase "textarea" and write it again. It makes the error go away in my case.

Of course, I could use `{...props as InputProps }` or `{...props as TextAreaProps }`, and the error goes away, but should that be necessary? It's just a workaround for me.

**Comment by karinchechik** [comment]
At the return statement in `text-field.ts`, the `props.multiline` check is not specific enough.

Change it to:
`props.multiline === true`

I tried it in the stackblitz code you added, and checked both cases.

**Comment by iivvaannxx** [comment]
Well, that actually fixed it! Still I don't know why on React works without the specific comparison. Thanks!
