### ISSUE TITLE
[🐞]An error in the docs

### ISSUE THREAD

**Issue by zwl1619** [BuilderIO/qwik#5448]
### Which component is affected?

Qwik City (routing)

### Describe the bug

There is an error in the following code, the code is form here:
https://qwik.builder.io/docs/integrations/prisma/#show-user-detail

![Snipaste_2023-11-16_22-06-58](https://github.com/BuilderIO/qwik/assets/13177997/bfbf4386-8890-4345-8f93-21fc153b2bca)

I copied the code in the red box into vscode , it has an error:
```
Type 'number' is not assignable to type 'string'.
```

And  command `npm run qwik add prisma` would generate this code, so the two places need to be corrected.

### Reproduction

https://qwik.builder.io/docs/integrations/prisma/#show-user-detail

### System Info

```shell
Type 'number' is not assignable to type 'string'.
```

**Comment by gioboa** [comment]
Thanks for you help @zwl1619 
Would you like to create a PR for that?

**Comment by dotarjun** [comment]
hey I'd like to work on this

**Comment by gioboa** [comment]
Thanks @dotarjun 
Looking forward to seeing your PR 🚀

**Comment by zwl1619** [comment]
@dotarjun great!

**Comment by zwl1619** [comment]
update:
@dotarjun   This error Will not appear when using SQLite, but only when using MongoDB. So this issue should be closed?

**Comment by gioboa** [comment]
We can simply add a comment to clarify it
```
// e.g. read from SQLite
```
cc @dotarjun
