### ISSUE TITLE
[✨] ESLint Warning around `useVisibleTask$`

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#5454]
### Is your feature request related to a problem?

`useVisibleTask$` should be used with caution. Have an ESLint warning around it.

### Describe the solution you'd like

Whenever I use `useVisibleTask$` I should get a lint warning that this will cause the code to run eagerly and that it should be used only as the last result. The warning should include instructions on how to disable the warning if that is what I want to do.

see: https://qwik.builder.io/docs/guides/best-practices/#avoid-registering-dom-events-in-usevisibletask

Warning
```
Qwik tries very hard to defer client code execution for as long as possible. This is done to give the end-user the best possible user experience. Running code eagerly blocks the main thread, which prevents the user from interacting until the task is finished.

`useVisibleTask$` is provided as an escape hatch. Sometimes it is the only way to achieve the result. In that case, add:

`
// eslint-disable-next-line no-use-visible-task
`

To the line before `useVisibleTask$` to acknowledge you understand.
```

### Describe alternatives you've considered

Just having documentation does not seem to be enough.

**Comment by gioboa** [comment]
I'm working on this one

**Comment by wmertens** [comment]
@gioboa It should also list alternatives:

- run on SSR with useTask
- run in event handlers like onClick
- run during render but inside `if (isBrowser)`
