### ISSUE TITLE
[🐞] Directory import is not supported resolving ES modules imported from

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#5464]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I upgraded to Vite 5 and updated the dependencies. I'm using `@auth/core` and `@builder.io/qwik-auth`.

After update when I run `npm run build` I get this error:

> Internal server error: Directory import '/home/projects/qwik-starter-y42h1d/node_modules/@auth/core/lib/actions' is not supported resolving ES modules imported from /home/projects/qwik-starter-y42h1d/node_modules/@auth/core/lib/index.js

Since it might be related to configuration, I'm going to send this issue to Qwik and Vite and Auth/Core repos.

### Reproduction

https://stackblitz.com/edit/qwik-starter-y42h1d?file=package.json

### System Info

```shell
System:
    OS: Linux 6.2 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
    Memory: 6.85 GB / 15.49 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
  Browsers:
    Chromium: 119.0.6045.159
  npmPackages:
    @builder.io/partytown: ^0.8.1 => 0.8.1 
    @builder.io/qwik: ^1.2.18 => 1.2.18 
    @builder.io/qwik-auth: ~0.1.3 => 0.1.3 
    @builder.io/qwik-city: ^1.2.18 => 1.2.18 
    undici: ^5.27.2 => 5.27.2 
    vite: ^5.0.0 => 5.0.0
```

**Comment by gioboa** [comment]
we are working on Vite 5 integration in [this PR](https://github.com/BuilderIO/qwik/pull/5451) 
is it working with Vite 4?

**Comment by Nefcanto** [comment]
@gioboa the `@auth/core` team solved it in https://github.com/nextauthjs/next-auth/pull/9205
