### ISSUE TITLE
Is there a way to get all the available routes?

### ISSUE THREAD

**Issue by Nedimko123** [BuilderIO/qwik#5471]
With dev mode, when you go to a 404 page, you get a list of all the routes, is there a way that we can also get all the routes without going to that page, but rather through SSR?

**Comment by maiieul** [comment]
This looks like a Help question. Could you ask in the Discord qwik-help channel instead?

Although, just in case, maybe you're looking for [menus](https://qwik.builder.io/docs/advanced/menu/)?

**Comment by Nedimko123** [comment]
> This looks like a Help question. Could you ask in the Discord qwik-help channel instead and close the issue? You can ping me @maiieul
> 
> Although, just in case, maybe you're looking for [menus](https://qwik.builder.io/docs/advanced/menu/)?

Not looking for menus, I am looking for a way to check if the route is an actual route for the breadcrumb component since sometimes the route is not available and I have it as a link, but I don't want to manually enter all the routes I have, though..

**Comment by DustinJSilk** [comment]
```ts
import qwikCityPlan from '@qwik-city-plan'

export const onGet: RequestHandler = () => {
  // Not sure what the types are but they arent properly exposed
  const routes = qwikCityPlan.routes as [any, any, any, string, any][]

  for (const route of routes) {
    console.log(route[3])
  }
}
```

**Comment by Nedimko123** [comment]
> ```ts
> import qwikCityPlan from '@qwik-city-plan'
> 
> export const onGet: RequestHandler = () => {
>   // Not sure what the types are but they arent properly exposed
>   const routes = qwikCityPlan.routes as [any, any, any, string, any][]
> 
>   for (const route of routes) {
>     console.log(route[3])
>   }
> }
> ```

You're a freaking legend, man! Thanks a lot!
