### ISSUE TITLE
[🐞] Prefetch redirects to error pages.

### ISSUE THREAD

**Issue by eglove** [BuilderIO/qwik#5474]
### Which component is affected?

Qwik City (routing)

### Describe the bug

`<Link prefetch={true} href="/this-page-doesnt-exist" />`

If the route on the href is not found on prefetch (such as when the user hovers over the element), the page is immediately redirected to the 404 page. This shouldn't happen until the user clicks or navigates to the page.

### Reproduction

https://github.com/eglove/examples/blob/main/apps/qwik-example/src/routes/index.tsx

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 5.58 GB / 31.76 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.5 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.58)
    Internet Explorer: 11.0.22621.1
```

**Comment by mhevery** [comment]
Would love to get a PR on this.
