### ISSUE TITLE
[🐞] Performance: "Link" loads unnecessary js chunks when a different "q:base" is set

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#5478]
### Which component is affected?

Qwik City (routing)

### Describe the bug

As with `$localize`, we usually build different js chunks for each locale:

```
dist/builld/q-*.js  # Original chunks
dist/builld/en/q-*.js
dist/builld/it/q-*.js
```
and we set the `q:base` to determine the base URL to use for loading the chunks in the browser:
```
export function extractBase({ serverData }: RenderOptions): string {
  if (import.meta.env.DEV) {
    return "/build";
  } else {
    return "/build/" + serverData!.locale;
  }
}
```

Everything seems to work, but when browsing through Link in SPA mode, many of the original chunks that shouldn't be needed are also loaded (this way, some files are loaded twice):

![image](https://github.com/BuilderIO/qwik/assets/14012361/11029710-b6b9-41a1-a155-d73b7c792553)

### Reproduction

https://github.com/robisim74/qwik-i18n-bug

### Steps to reproduce

All you need to do is start a new Qwik app, add i18n, and a page to navigate using Link.

Anyway:
- download the repo
- npm install && npm run preview
- navigate to http://localhost:4173/en
- open the network tab
- click on PAGE link in the center
- inspect the chunks loaded in network tab

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 29.56 GB / 31.19 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.0 - /usr/bin/node
    npm: 9.8.1 - /usr/bin/npm
  npmPackages:
    @builder.io/qwik: ^1.2.19 => 1.2.19 
    @builder.io/qwik-city: ^1.2.19 => 1.2.19 
    undici: ^5.26.0 => 5.28.0 
    vite: ^4.4.11 => 4.5.0
```

### Additional Information

In elements tab, I noticed that there are in the head `modulePreload` that do not have the `q:base` set, and files that load correspond to unnecessary original chunks:

![image](https://github.com/BuilderIO/qwik/assets/14012361/44112c3e-4107-46b5-9d81-5e29bdc37a25)

Thanks!

**Comment by wmertens** [comment]
I'd like to add to this that css files are also inlined once for each locale :-/

**Comment by mhevery** [comment]
This is an issue with vite. You need to disable `modulePreload: false` https://stackoverflow.com/questions/70980498/disable-preload-in-vite

**Comment by wmertens** [comment]
@mhevery can't we disable it by default in the qwikVite plugin? I see that [it's set to `{polyfill: false}`](https://github.com/BuilderIO/qwik/blob/eed27027a1f26e60221c55c4f0414ab3d05c06d1/packages/qwik/src/optimizer/src/plugins/vite.ts#L304-L306)
