### ISSUE TITLE
[🐞] MDX integration from "Qwik Website Guide" is not working

### ISSUE THREAD

**Issue by ValentinBossi** [BuilderIO/qwik#5522]
### Which component is affected?

Qwik Runtime

### Describe the bug

When following the MDX Guide on https://qwik.builder.io/docs/guides/mdx/ the steps are not working.
![image](https://github.com/BuilderIO/qwik/assets/19373754/85aa09ea-d8e6-44f9-8e29-f2a7251401c5)

### Reproduction

https://stackblitz.com/edit/qwik-starter-jb8ppw?file=src%2Froutes%2Fdemo%2Fmdx%2Findex.mdx

### Steps to reproduce

Open stackblitz from URL and go to /mdx where the example is not working

### System Info

```shell
Windows but also stackblitz
```

**Comment by gioboa** [comment]
Hi, the starter application has a different structure than the documentation one.
If you are starting from the "Basic App" starter you need to use this syntax
```
---
title: Hello World Title
tags:
  - super
  - exiting
  - docs
---
import Counter from "../../../components/starter/counter/counter";

This is a simple hello world component.
<Counter />
```

By the way, in Stackblitz it doesn't work anyway due to their environment.
Thanks for your commitment and help @ValentinBossi

**Comment by ValentinBossi** [comment]
thanks, its working with a new line after the import.
is there a case where we dont need a new line? otherwise it would be better to have a working example in the docs with the new line.

**Comment by gioboa** [comment]
> thanks, its working with a new line after the import. is there a case where we dont need a new line? otherwise it would be better to have a working example in the docs with the new line. i can make a PR if needed.

I don't think so b/c without the new line is failing. Would you like to contribute and create a PR for that?
