### ISSUE TITLE
[🐞] Served app does not restore url search params on page load [Deno]

### ISSUE THREAD

**Issue by ianlet** [BuilderIO/qwik#5526]
### Which component is affected?

Qwik City / Deno Adapters

### Describe the bug

`useLocation` returns an empty `URLSearchParams` on page load when served by the Deno integration.

There is no issue when navigating to an URL with search params (e.g. `navigate('/?a=a')` or with the `Link` component) though. It's only happening on full page load/refresh.

### Reproduction

https://github.com/ianlet/bug-qwik-deno-search-params

### Steps to reproduce

* Clone the project from the reproduction link
* Run `yarn` to install it
* Run `yarn build` to build the deno server
* Run `yarn serve` to serve the deno server
* Open `localhost:3009`
* Click on the big button `click me`
* Notice the search params were displayed correctly
* Reload the page (make sure the search params are still in the URL)
* Notice the search params are not displayed (`url.searchParams` from `useLocation` is empty)

You can also add this bit of code in any component of a project served by Deno to reproduce the issue:
```ts
const location = useLocation();
console.log(location.url.searchParams);
```

### System Info

```shell
System:
    OS: Linux 6.6 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 14.43 GB / 31.17 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
  Binaries:
    Node: 20.5.1 - /tmp/xfs-caeab81d/node
    Yarn: 2.4.3 - /tmp/xfs-caeab81d/yarn
  Browsers:
    Chromium: 119.0.6045.159
  npmPackages:
    @builder.io/qwik: ^1.2.19 => 1.2.19
    @builder.io/qwik-city: ^1.2.19 => 1.2.19
    undici: ^5.26.0 => 5.28.2
    vite: ^4.4.11 => 4.5.1
```

### Additional Information

I tried the same with a fresh `Node Express` server, and I cannot reproduce the issue.

This is quite a big blocker for my product as my clients share quite often URLs containing search params. So I'm already digging into the codebase to see if I could find the culprit, but if you have a better idea than me thanks for pointing me in the right direction :)

**Comment by gioboa** [comment]
Thanks @ianlet for your feedback. So if with `node` is ok we can assume that the issue could be in the `deno` integration.
You can DM me on Discord and I will help you to figure out the fix.
