### ISSUE TITLE
[🐞] Scroll Position doesn't reset to 0 when it was triggered by SSR / Form Submit Redirection.

### ISSUE THREAD

**Issue by iamriajul** [BuilderIO/qwik#5537]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When anyone submits a form, and the action does throw/return a redirection then the redirection happens correctly but the scroll position doesn't get reset to 0 in the new page.

### Reproduction

https://github.com/iamriajul/qwik-repro-ssr-redirection-scroll-position-bug

### Steps to reproduce

- pnpm install
- pnpm start
- Now scroll to the footer.
- Now see above the footer there's a form.
- Submit the form.
- The bug: Page stays at the footer.

### System Info

```shell
  System:
    OS: macOS 13.5.1
    CPU: (16) x64 ************ 8-Core Processor             
    Memory: 207.31 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 8.9.2 - ~/.nvm/versions/node/v16.20.2/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.105
    Edge: 120.0.2210.61
    Safari: 16.6
  npmPackages:
    @builder.io/partytown: ^0.8.1 => 0.8.1 
    @builder.io/qwik: ^1.2.19 => 1.2.19 
    @builder.io/qwik-city: ^1.2.19 => 1.2.19 
    @builder.io/qwik-react: 0.5.0 => 0.5.0 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

**Comment by gioboa** [comment]
Hi @iamriajul we are using HTTP headers to do the redirection [here is the code](https://github.com/BuilderIO/qwik/blob/609d070156794aba1a245841b572465eb001d277/packages/qwik-city/middleware/request-handler/request-event.ts#L197)
is there a way to force a "scroll to top" with headers? 🤔

**Comment by iamriajul** [comment]
This bug only happens when a routeAction$ (and other Action maybe) returns redirect, but this bug doesn't occur when a routeLoader$ returns a redirect.

**Comment by iamriajul** [comment]
I'm not clear what are you talking about, both `routeLoader$` and `routeAction$` runs on server, they return similar response, but qwik-city-component handles their response differently.
![image](https://github.com/BuilderIO/qwik/assets/24244379/87365d35-e626-4c49-8e89-5e9d5fa1aab3)
![image](https://github.com/BuilderIO/qwik/assets/24244379/eed81919-3272-4b65-90f8-9492e5a112c3)
![image](https://github.com/BuilderIO/qwik/assets/24244379/3d492a99-411c-4677-8527-7287b81d5c3b)

**Comment by gioboa** [comment]
Could I encourage you to create a PR with this feature?

**Comment by iamriajul** [comment]
I don't understand much here, what to change or not. I think @manucorporat can help here.

**Comment by iamriajul** [comment]
@gioboa I've submitted a PR. The issue is hampering our user experiences currently.

**Comment by gioboa** [comment]
You can test your implementation right now with [this method](https://github.com/BuilderIO/qwik/blob/main/CONTINUOUS_BUILD.md#continuous-build-artifacts)
Thanks @iamriajul from your commitment.
