### ISSUE TITLE
[🐞] console "[vite] warning :..." messages still show up even when eslint rule is disabled

### ISSUE THREAD

**Issue by maiieul** [BuilderIO/qwik#5555]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

Some Eslint rules appear in the dev console as "[vite] warning : ..." messages. This has gotten especially annoying with the new "qwik/no-use-visible-task" eslint rule.

Ex:

> 10:27:45 PM [vite] warning: Qwik tries very hard to defer client code execution for as long as possible.
This is done to give the end-user the best possible user experience.
Running code eagerly blocks the main thread, which prevents the user from interacting until the task is finished.
"useVisibleTask$" is provided as an escape hatch.

> When in doubt, instead of "useVisibleTask$()" use:
> - useTask$ -> perform code execution in SSR mode.
> - useOn() -> listen to events on the root element of the current component.
> - useOnWindow() -> listen to events on the window object.
> - useOnDocument() -> listen to events on the document object.

> Sometimes it is the only way to achieve the result.
In that case, add:
// eslint-disable-next-line qwik/no-use-visible-task
to the line before "useVisibleTask$" to acknowledge you understand.

  > Plugin: vite-plugin-qwik
  > File: /home/maieul/dev/vite-warnings-repro/src/routes/index.tsx:5:3
  3  |  
  4  |  export default component$(() => {
  5  |    useVisibleTask$(() => {
     |     ^
  6  |      console.log("Hello World!");
  7  |    });
^C⏎          

### Reproduction

https://github.com/maiieul/qwik-vite-warnings-repro

### Steps to reproduce

- pnpm dev
- load the page to see the warning

### System Info

```shell
System:
    OS: Linux 6.6 Fedora Linux 38 (Workstation Edition)
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-1340P
    Memory: 16.89 GB / 31.06 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.10.5 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.71
  npmPackages:
    @builder.io/qwik: ^1.3.0 => 1.3.0 
    @builder.io/qwik-city: ^1.3.0 => 1.3.0 
    undici: ^5.26.0 => 5.28.2 
    vite: ^5.0.6 => 5.0.7
```

### Additional Information

I think those kinds of vite warnings shouldn't appear in the dev console at all since this should be the job of eslint.

**Comment by maiieul** [comment]
P.S. using ` // eslint-disable-next-line qwik/no-use-visible-task` comments removes the warnings from the console, but it should at least be up to the developer if he wants to disable it globally or per comment.

I think we probably should remove those vite warnings related to the eslint rules. This should be handled by eslint only.

**Comment by gioboa** [comment]
I tried with these two rules and after refreshing VSCode, eslint is working fine.
```
"qwik/no-use-visible-task": "off"
"qwik/loader-location": "off"
```
btw the warnings come from `"lint": "eslint \"src/**/*.ts*\"",` scripts so you can try to run it in the terminal too

**Comment by maiieul** [comment]
I still get the warnings, even when turning off eslint and removing the `lint` script from package.json.

![Screenshot from 2023-12-11 12-44-14](https://github.com/BuilderIO/qwik/assets/45822175/6e86fc53-bff1-43aa-9a98-6a9f2356f07a)
