### ISSUE TITLE
[🐞]Fix the type of onClick$ to be PropFunction

### ISSUE THREAD

**Issue by primozs** [BuilderIO/qwik#5567]
### Which component is affected?

Qwik Runtime

### Describe the bug

Is this correct or not?

type ContextMenuItemProps = {
  onClick$?: PropFunction<(event: MouseEvent) => void>;
};

in 
    "@builder.io/qwik": "^1.3.0",
    "@builder.io/qwik-city": "^1.3.0",

I get this

Using "onClick$" as an event handler, however functions are not serializable.
Did you mean to wrap it in `$()`?

Fix the type of onClick$ to be PropFunction

### Reproduction

none

### System Info

```shell
System:
    OS: Linux 5.14 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 22.28 GB / 31.09 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.11.0 - ~/.local/share/pnpm/pnpm
    bun: 1.0.14 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.101
    Chrome: 120.0.6099.71
```

**Comment by primozs** [comment]
I know about QwikIntrinsicElements

so what is then a PropFunction is this example below not the same?
 
from the docs

import { type PropFunction, component$, Slot } from '@builder.io/qwik';

export default component$(() => {
  return <CmpButton onClick$={() => alert('CLICKED!')}>click me!</CmpButton>;
});

export const CmpButton = component$<{
  // Important to tell TypeScript that this is async
  onClick$?: PropFunction<() => void>;
}>((props) => {
  return (
    <button onClick$={props.onClick$}>
      <Slot />
    </button>
  );
});

**Comment by wmertens** [comment]
Ah ok I understand now. I overhauled the types a bit and this might not work correctly in 1.3.0 but in the upcoming release it should work, I'll double-check and add a test if needed

**Comment by wmertens** [comment]
@primozs yes it seems to work in the upcoming release. You can try yourself if you like by installing the build like this: https://github.com/BuilderIO/qwik-build?tab=readme-ov-file#install-specific-build-artifact

**Comment by primozs** [comment]
@wmertens thank You
