### ISSUE TITLE
[🐞] Error when building my app with prisma

### ISSUE THREAD

**Issue by kokecar11** [BuilderIO/qwik#5570]
### Which component is affected?

Qwik Runtime

### Describe the bug

When I build my application with prisma it generates an error and I have not been able to deploy the changes in Vercel.
![Captura de pantalla 2023-12-12 a la(s) 6 09 50 p  m](https://github.com/BuilderIO/qwik/assets/42183700/c0941e01-ad35-4aa8-858d-680b8772c5b9)

### Reproduction

https://stackblitz.com/edit/qwik-starter?file=package.json

### Steps to reproduce

pnpm qwik add prisma

### System Info

```shell
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 493.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Brave Browser: 120.1.61.101
    Chrome: 120.0.6099.71
    Safari: 17.2
  npmPackages:
    @builder.io/partytown: ^0.8.1 => 0.8.1
    @builder.io/qwik: ^1.2.14 => 1.2.14
    @builder.io/qwik-auth: 0.1.0 => 0.1.0
    @builder.io/qwik-city: ^1.2.14 => 1.2.14
    undici: 5.22.1 => 5.22.1
    vite: 4.3.5 => 4.3.5
```

**Comment by jcarpintero11** [comment]
> Is it the same issue of this one #4075?

Yes, it's the same one, it won't let me do build

**Comment by kokecar11** [comment]
> Is it the same issue of this one #4075?

Yes, it's the same one, it won't let me do build

**Comment by gioboa** [comment]
Let's close this one and we can continue in the other one. Thanks
