### ISSUE TITLE
qwik docs: multi-language website [📖]

### ISSUE THREAD

**Issue by xzfnn** [BuilderIO/qwik#5589]
### Suggestion

When does the document support internationalization

**Comment by gioboa** [comment]
Hi @xzfnn, can you explain more in the detail your needs pls?

**Comment by xzfnn** [comment]
> 嗨，你能详细解释一下你的需求吗？

Can the official document have language switching function, such as Chinese, Japanese, Korean, etc

**Comment by wmertens** [comment]
@xzfnn maybe you'd like https://www.npmjs.com/package/compiled-i18n

**Comment by xzfnn** [comment]
> @xzfnn也许你会喜欢https://www.npmjs.com/package/compiled-i18n

https://qwik.builder.io/docs/           This link doesn't seem to integrate this plugin

**Comment by gioboa** [comment]
I see. you are asking for a multi-language documentation, right?

**Comment by xzfnn** [comment]
> 明白了。你要求一个多语言的文档，对吧？

Yes, using translation plugins can lead to many word translation errors, which is not conducive to learning. Could you please help your team

**Comment by xzfnn** [comment]
> > 明白了。你要求一个多语言的文档，对吧？
> 
> 是的，使用翻译插件会导致很多单词翻译错误，不利于学习。你能帮帮你的团队吗

Thank you to your team

**Comment by wmertens** [comment]
@xzfnn you can use the docs AI in the search box to ask questions in your language

**Comment by xzfnn** [comment]
> 您可以使用搜索框中的 docs AI 以您的语言提问

Okay, thank you very much

**Comment by gioboa** [comment]
@shairez are we planning something for the multi-language support?

**Comment by shairez** [comment]
@gioboa we decided that it'll be too much to handle all the translations in the core and keep them up to date.

A good solution might be to install a translator plugin that might do it automatically

@xzfnn if you want to help with researching such plugin (I think wordpress sites have something similar), that'll be awesome!

**Comment by gioboa** [comment]
Thanks @shairez for your thoughts.
So I'm closing this issue for now.
