### ISSUE TITLE
[✨] Export ServerQRL type

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#5622]
### Is your feature request related to a problem?

Until Qwik City v1.3.0, `server$` function had `QRL` return type (and it was really useful, because a `server$` function could be assigned directly to a QRL type declaration), but from v1.3.1 has `ServerQRL` type.

### Describe the solution you'd like

Export the new type [ServerQRL](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/runtime/src/types.ts#L798)

### Describe alternatives you've considered

Tried implementing a type that satisfied both QRL and ServerQRL, without success. The only alternative is to recreate the ServerQRL type ourselves.

### Additional context

Thanks!

**Comment by gioboa** [comment]
Hi @robisim74, does this [PR](https://github.com/BuilderIO/qwik/pull/5623) solve your issue?

**Comment by robisim74** [comment]
Yes!

**Comment by gioboa** [comment]
Nice, I close it. I take this opportunity to thank you @robisim74 for the great effort you put into Qwik.
