### ISSUE TITLE
[✨] Improve support for Qwik elements which are rendered under non-Qwik nodes (pass context, remove assertion)

### ISSUE THREAD

**Issue by yanivhamo** [BuilderIO/qwik#5636]
### Is your feature request related to a problem?

Sometimes we end up with a DOM tree where some of the ancestors were created outside of Qwik, something like this:

```
<QwikRoot>
  <div> <!-- created by a 3rd party e.g. Leaflet -->
     <QwikElement />
  </div>
</QwikRoot>
```

This structure is not common. It happens when the developer calls render() themselves, and hands over the resulting node to a 3rd party library. A concrete example is Qwik elements inside Leaflet popups (mentioned in https://github.com/BuilderIO/qwik/issues/3869). In the specific case of Leaflet, we do something like this:

```
const L = await import('leaflet'); // must be in useVisibleTask$ because Leaflet accesses 'window'
const marker = L.circleMarker(L.latLng(0, 0), { radius: 32 });
const popupDiv = document.createElement('div');
await render(popupDiv, <QwikElement />);   // <---- here we call render()
marker.bindPopup(popupDiv);
```

This results in an error and a warning:

1. Error: If QwikElement accesses context provided by QwikRoot, e.g. i18n locale handlingm or site theme, we get: `Error: Code(13): Actual value for useContext() can not be found, make sure some ancestor component has set a value using useContextProvider()`
2. Warning: An assertion fails because Qwik Core does not expect to have a non-Qwik ancestor: `Error: Internal assert, this is likely caused by a bug in Qwik: element must be connected to the dom`

We can work around the error by having QwikRoot pass context in the props of QwikElement. Then everything works, reactivity is preserved. And the assertion warning, well, we can just ignore it.

To ease playing around with this issue, I created a full minimal example in: https://stackblitz.com/edit/qwik-starter-by4ppy?file=src%2Froutes%2Findex.tsx

### Describe the solution you'd like

If it is possible to pass the context by props, then it should also be possible to have it passed automatically by the library (given that one common ancestor is providing this context).

We can also consider not printing the warning in case a Qwik ancestor is found.

There might be tons of other issues that are needed to be addressed in order to fully support this case.

### Describe alternatives you've considered

There are no good alternatives if we want to keep using Qwik elements in these cases. I tried to switch to creating elements using vanilla JS for passing to Leaflet's popup, but I felt like I'm back in the '90s :) I missed the ease of use of Qwik and reusing elements I have already created.

**Comment by wmertens** [comment]
This is not really supported, but to make it work in v1 you have to render the component once in the browser, making sure it uses the context. Once that's done, you can move it inside third-party DOM.
In v2, it might just work.
