### ISSUE TITLE
[🐞] Pass PropFunction to component does not work in onClick$ event

### ISSUE THREAD

**Issue by diecodev** [BuilderIO/qwik#5652]
### Which component is affected?

Qwik Runtime

### Describe the bug

I got a Class with some properties, one of then is `props.toast.action.onClick` this props is optional is totally typed. when i fire the toast, the `action.onClick` function is not apearing in the button that is render when the props is passed to the Toaster component:

### The trigger code:
![image](https://github.com/BuilderIO/qwik/assets/51871681/fe518f6a-9ee5-4cfb-be35-bce4c8ab601d)

## The Toaster component:
![image](https://github.com/BuilderIO/qwik/assets/51871681/b56cabad-dd4a-4618-8e00-01fa4555428c)

> [!WARNING]
> the `onMouseOver$` attribute is to show you that only the `onClick$` attr is not working. The attribute is not even in the html rendered

## HTML OUTPUT:
> Notice that the rendered button has not the on:click="..." attribute

![image](https://github.com/BuilderIO/qwik/assets/51871681/9a231c30-b90b-475a-94ec-e3c6e59de751)

## Console logs
![image](https://github.com/BuilderIO/qwik/assets/51871681/67fbffb9-604b-47e0-b601-45d6b7174b6d)

### PS
I thought for a moment that I was not passing the function to the Toaster component, but it does happen:

- Just showing the action trigger event:
![image](https://github.com/BuilderIO/qwik/assets/51871681/d768ab5c-7650-4bf5-a1fc-d48385fd94d6)

- Invoking the props:
![image](https://github.com/BuilderIO/qwik/assets/51871681/46adc8b0-3d91-4f7d-8062-c721aa850dc3)

### Reproduction

https://stackblitz.com/edit/qwik-starter-uqxx1t?file=src%2Froot.tsx

### Steps to reproduce

clone the repo (fix-gh-issue branch) and then go to `/packages/qwik-fix` folder just run:

```
pnpm install
pnpm start
```

Go to `http://localhost:5173/` and use the action button rendered and show the browser console

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12450H
    Memory: 522.05 MB / 7.73 GB
  Binaries:
    Node: 20.10.0 - ~\AppData\Local\fnm_multishells\22352_1703949366162\node.EXE
    Yarn: 1.22.21 - ~\AppData\Local\fnm_multishells\22352_1703949366162\yarn.CMD
    npm: 10.2.3 - ~\AppData\Local\fnm_multishells\22352_1703949366162\npm.CMD
    pnpm: 8.12.1 - ~\AppData\Local\fnm_multishells\22352_1703949366162\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: 1.3.1 => 1.3.1
    undici: ^5.26.0 => 5.28.2
    vite: ^5.0.6 => 5.0.10
```

**Comment by wmertens** [comment]
can you try this with 1.3.2? Also, it's better if you can reproduce it in the playground, make is as minimal as possible.

**Comment by diecodev** [comment]
@wmertens Ok, I updated the link to the example repo. I'll leave the link [here too](https://stackblitz.com/edit/qwik-starter-uqxx1t?file=src%2Froot.tsx):

**Comment by wmertens** [comment]
This is fixed in the latest releases, right?

**Comment by diecodev** [comment]
@wmertens Yes, it works! Thank you so much for the fix, I was looking forward to launch my qwik component.
