### ISSUE TITLE
[🐞] class attribute for dynamic/polymorphic component does not appear in dom

### ISSUE THREAD

**Issue by dsm23** [BuilderIO/qwik#5659]
### Which component is affected?

Qwik Runtime

### Describe the bug

So I have this polymorphic anchor component that contains tailwind styles and should easily be a `button` tag, or an `a` tag or accept qwik city's `Link` component. The component looks like this:

```jsx
import { component$, Slot } from "@builder.io/qwik";
import { twMerge } from "tailwind-merge";

const defaultElement = "a";

export const Anchor = component$(
  ({ as: Component = defaultElement, ...props }) => (
    <Component
      {...props}
      class={twMerge(
        "-mx-1 px-1 text-sky-900 outline-none hover:underline focus:rounded focus:bg-yellow-500 print:underline dark:text-sky-300",
        props.class
      )}
    >
      <Slot />
    </Component>
  ),
);

export default Anchor;
```

This component appears to be doing the polymorphism ok but it does not contain any styles. In the dom in the browser inspection, it does not have a class attribute when the component is used like this:

```jsx
<Anchor href="<some-url>">Some Text</Anchor>
```

However, if the `props.class` line is commented it out in the Anchor comment, the class attribute does appear. If it is replaced with the value `undefined`... then the class attribute also does appear. Another way that I can guarantee the class attribute to appear is if I use the Anchor component like so:

```jsx
<Anchor href="<some-url>" class="">Some Text</Anchor>
```

Surely, this can't be expected behaviour

### Reproduction

N/A

### Steps to reproduce

I didn't make a reproduction on stackblitz because stackblitz was breaking when I changed the dependencies. However, I did get up to the point of 4 different anchor tags and my issue with the class attribute was not reproducing. Perhaps this could be a mac vs linux thing?

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 32.46 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    npm: 9.2.0 - ~/Library/pnpm/npm
    pnpm: 8.13.1 - ~/Library/pnpm/pnpm
    bun: 1.0.20 - /usr/local/bin/bun
    Watchman: 2023.12.04.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 78.1.0.1
    Chrome: 120.0.6099.129
    Edge: 120.0.2210.91
    Safari: 17.2.1
  npmPackages:
    @builder.io/qwik: ^1.3.1 => 1.3.1 
    @builder.io/qwik-city: ^1.3.1 => 1.3.1 
    vite: ^5.0.6 => 5.0.10
```

EDIT: specifically, the place in my code where I'm using the Anchor component: https://github.com/dsm23/dsm23-qwik-city-portfolio/blob/main/src/components/sections/home/index.tsx

**Comment by wmertens** [comment]
This is fixed by #5650, it will be released soon, in the meantime you can try the build at https://github.com/BuilderIO/qwik-build
