### ISSUE TITLE
Can't change vite output dir

### ISSUE THREAD

**Issue by L1lith** [BuilderIO/qwik#567]
### Qwik Version

0.0.21

### Operating System (or Browser)

Node

### Node Version (if applicable)

16.15.0

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

I ran `npm init qwik@latest`, and I selected the qwik-city starter (but I don't think it matters), then I changed my vite config to modify the output folder, expecting it to change the output directory when running `npm run build`

vite.config.js
```js
import { defineConfig } from 'vite';
import { qwikVite } from '@builder.io/qwik/optimizer';
import { qwikCity } from '@builder.io/qwik-city/vite';
import { resolve } from 'path';
/* VITE_IMPORTS */

export default defineConfig(() => {
  const pagesDir = resolve('pages');

  return {
    /* VITE_CONFIG */
    build: {
      outDir: '../resources/' // This is ignored
    },
    plugins: [
      qwikCity({
        pagesDir,
        layouts: {
          default: resolve('src', 'layouts', 'default', 'default.tsx'),
        },
      }),
      qwikVite(/* VITE_QWIK */),
      /* VITE_PLUGINS */
    ],
  };
});
```

### Actual Behaviour

I expected it to output to the "../resources" dir, but instead it puts everything in the "dist" folder

**Comment by tanepiper** [comment]
+1 this would be absolutely necessary for our pipeline

**Comment by ImBIOS** [comment]
We can set the output of the build in the `qwikVite()` options like this:
```typescript
import { defineConfig } from "vite";
import { qwikVite } from "@builder.io/qwik/optimizer";
import { qwikCity } from "@builder.io/qwik-city/vite";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig(() => {
  return {
    ssr: { target: "webworker", noExternal: true },
    plugins: [
      qwikCity(),
      qwikVite({
        client: {
          outDir: "resources/", // This is ignored
        },
      }),
      tsconfigPaths(),
    ],
  };
});
```
It will make the output to the `resources` folder like this:
![image](https://user-images.githubusercontent.com/41441643/183097528-ad51b7ba-11e4-45e5-b798-6e8fa0f10a0d.png)

**Comment by adamdbradley** [comment]
Thanks for reporting the issue and thanks @ImBIOS for writing the docs 💪 

Closed with https://github.com/BuilderIO/qwik/pull/943
