### ISSUE TITLE
[🐞] React Material integration broken in Vite v5

### ISSUE THREAD

**Issue by engineersamwell** [BuilderIO/qwik#5692]
### Which component is affected?

Qwik React

### Describe the bug

When attempting to use Qwik + React integration with vite version 5 (ex. 5.0.11) the following error is encountered:

```
error: [vite] Internal server error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object
```

### Reproduction

https://stackblitz.com/edit/qwik-starter?file=package.json,src%2Fintegrations%2Freact%2Fmui.tsx,src%2Froutes%2Freact%2Findex.tsx

### Steps to reproduce

- npm create qwik@latest
- cd qwik-app
- Change the vite version to 5.0.11 and npm i (though technically I did a fully clean npm install at this point after deleting node_modules)
- npm run qwik add react
- From the react.tsx at https://qwik.builder.io/docs/integrations/react/#6-using-react-libraries copy the code into the mui.tsx
- In index.tsx add the signal and

```bash
<Example
				selected={selected.value}
				onSelected$={(v) => (selected.value = v)}
			>
				Selected tab: {selected.value}
			</Example>
```

- [vite] Internal server error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Note the above stackblitz isn't working due to `sharp` binary issues, otherwise it should reproduce the issue.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (20) arm64 Apple M1 Ultra
    Memory: 2.41 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    bun: 1.0.7 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 17.2.1
  npmPackages:
    @builder.io/qwik: ^1.3.3 => 1.3.3
    @builder.io/qwik-city: ^1.3.3 => 1.3.3
    @builder.io/qwik-react: 0.5.0 => 0.5.0
    undici: 5.22.1 => 5.22.1
    vite: 4.5.1 => 4.5.1
```

**Comment by sidmohanty11** [comment]
Hello @engineersamwell, I actually faced this exact issue. The workaround that worked for me was:

Converting these

```jsx
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import Box from '@mui/material/Box';
```

to

```jsx
import { Tabs, Tab, Box } from '@mui/material';
```

**Comment by gioboa** [comment]
Thanks @sidmohanty11 for sharing your solution. @engineersamwell is it working for you?
