### ISSUE TITLE
[🐞] incompatibility of 1.3..4 with undici 6.3.0

### ISSUE THREAD

**Issue by tidiview** [BuilderIO/qwik#5699]
### Which component is affected?

Qwik Runtime

### Describe the bug

version 1.3.4 do not work with undici 6.3.0.
It works with undici 5.28.2.

### Reproduction

https://2eefcd7a.worktop-qwikcity.pages.dev/

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
    Memory: 1.00 GB / 7.86 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.121)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @builder.io/qwik: ^1.3.4 => 1.3.4
    @builder.io/qwik-city: ^1.3.4 => 1.3.4
    undici: ^5.28.2 => 5.28.2
    vite: ^5.0.11 => 5.0.11
```

**Comment by gioboa** [comment]
The reproduction website is working fine.
Which error do you have? Can you post a screenshot?

**Comment by carlosfernandezcabrero** [comment]
Hi 👋,

I have the same problem. I attach the output log with the details of conflict:
```
npm install
npm WARN workspaces qwik-ts in filter set, but no workspace folder present
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: qwik-ts@undefined
npm ERR! Found: undici@6.3.0
npm ERR! node_modules/undici
npm ERR!   dev undici@"^6.3.0" from qwik-ts@undefined
npm ERR!   qwik-ts
npm ERR!     qwik-ts@undefined
npm ERR!     node_modules/qwik-ts
npm ERR!       workspace qwik-ts from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer undici@"^5.14.0" from @builder.io/qwik@1.3.4
npm ERR! node_modules/@builder.io/qwik
npm ERR!   dev @builder.io/qwik@"^1.3.4" from qwik-ts@undefined
npm ERR!   qwik-ts
npm ERR!     qwik-ts@undefined
npm ERR!     node_modules/qwik-ts
npm ERR!       workspace qwik-ts from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```


To solve the error I change the dependency undici version from “^6.3.0” to “^5.14.0”.

**Comment by JoepKockelkorn** [comment]
This is because of the peerDependency range, so technically it's not a bug. It's intended behaviour. Did you try to run with undici 6.3.0 and verify it still works at runtime? If so, the peerDependency range could be expanded.

**Comment by tidiview** [comment]
Here error after upgrade to qwik 1.3.5 [it's working fine locally on Windows] [it's NOT working on Cloudflare Pages, see below]
![20230115_2327-Capture](https://github.com/BuilderIO/qwik/assets/14911996/a8cb480b-04f2-4ac1-b523-a0361f930438)
Here the package.json
![20230115_2326-Capture](https://github.com/BuilderIO/qwik/assets/14911996/04b96f48-d004-49b6-a640-82deb09c4ca8)
To solve this error I changed dependency to "^5.28.2"

**Comment by wmertens** [comment]
@tidiview can you try with the version qwik@dev ?

**Comment by n3oney** [comment]
@wmertens I'm trying to try @builder.io/qwik@dev, but for some reason it's missing the `qwik` binary so I can't build it. Using bun as the package manager.

**Comment by wmertens** [comment]
Hmm sorry, probably my fault. Checking.

**Comment by n3oney** [comment]
Hi, after recreating the project using cloudflare's CLI I don't have any issues anymore.

**Comment by gioboa** [comment]
@tidiview do you have any news?

**Comment by tidiview** [comment]
@wmertens @gioboa 
Sorry, for the delay to respond.
I just upgrade to qwik@1.4.0 on Cloudflare and the problem is solved.
Thank you.

**Comment by gioboa** [comment]
👍 great
