### ISSUE TITLE
[🐞] routeLoader$ is not being called in navigation event

### ISSUE THREAD

**Issue by Complugg3d** [BuilderIO/qwik#5712]
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm using Prisma in the routeLoader, one for edit and one for read, after storing the value in the edit component 

`import {
  component$,
  useStore,
  useSignal,
  noSerialize,
  useVisibleTask$,
  type NoSerialize,
} from "@builder.io/qwik";
import { Form, routeAction$, routeLoader$, useNavigate } from "@builder.io/qwik-city";
import { PrismaClient } from "@prisma/client";
import * as MonacoE from "monaco-editor";

import editorWorker from "monaco-editor/esm/vs/editor/editor.worker?worker";
import jsonWorker from "monaco-editor/esm/vs/language/json/json.worker?worker";
import cssWorker from "monaco-editor/esm/vs/language/css/css.worker?worker";
import htmlWorker from "monaco-editor/esm/vs/language/html/html.worker?worker";
import tsWorker from "monaco-editor/esm/vs/language/typescript/ts.worker?worker";
import { db } from "~/db/db";

export const useReadSnippet = routeLoader$(async (request) => {
  const { id } = request.params;
  const snippet = await db.snippet.findUnique({
    where: {
      id: Number(id),
    },
  });
  if (!snippet) {
    request.fail(404, { message: "Snippet not found" });
    request.status(404);
  }
  console.log("emgv read snippet", snippet);
  return snippet;
});

export const useEditSnippet = routeAction$(async (form) => {
  const prisma = new PrismaClient();
  const snippet = await prisma.snippet.update({
    where: {
      id: +form.id,
    },
    data: {
      code: form.code.toString(),
    },
  });
  console.log("emgv snippet", snippet);
  
});

export default component$(() => {
  const navigate = useNavigate();
  const snippet = useReadSnippet();
  const editSignal = useSignal(snippet.value?.code || "");
  const editorRef = useSignal<HTMLElement>();
  const editAction = useEditSnippet();
  const store = useStore<{
    monacoInstance: NoSerialize<MonacoE.editor.IStandaloneCodeEditor>;
  }>({
    monacoInstance: undefined,
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(() => {
    self.MonacoEnvironment = {
      getWorker(_, label) {
        if (label === "json") {
          return new jsonWorker();
        }
        if (label === "css" || label === "scss" || label === "less") {
          return new cssWorker();
        }
        if (label === "html" || label === "handlebars" || label === "razor") {
          return new htmlWorker();
        }
        if (label === "typescript" || label === "javascript") {
          return new tsWorker();
        }
        return new editorWorker();
      },
    };

    const editor = MonacoE.editor.create(editorRef.value!, {
      value: "",
      theme: "vs-dark",
      language: "javascript",
    });

    // Monaco is not serializable, so we can't serialize it as part of SSR
    // We can however instantiate it on the client after the component is visible
    store.monacoInstance = noSerialize(editor);
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ track }) => {
    track(() => snippet.value);
    track(() => store.monacoInstance);
    console.log("emgv client task", snippet.value);
    if (snippet.value.code && store.monacoInstance) {
      store.monacoInstance.setValue(snippet.value.code);
    }
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(() => {
    store.monacoInstance?.onDidChangeModelContent(() => {
      const newValue = store.monacoInstance?.getValue();

      editSignal.value = newValue || "";
    });
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(async ({ track }) => {
    track(() => editAction.status);

    if (editAction.status === 200) {
      await navigate(`/snippets/${snippet.value?.id}`);
    }
  });

  console.log("emgv component snippet", snippet.value);

  return (
    <>
      <div
        style={{
          height: "40vh",
        }}
        ref={editorRef}
      ></div>
      <Form action={editAction}>
        <input
          type="hidden"
          id="title"
          name="title"
          value={snippet.value?.title}
        />
        <input type="hidden" id="code" name="code" value={editSignal.value} />
        <input type="hidden" id="id" name="id" value={snippet.value?.id} />
        <button type="submit" class="rounded border p-2">
          Save
        </button>
      </Form>
    </>
  );
});
`
The show component is showing a cached value instead of the latest one

`import { Resource, component$, useResource$ } from "@builder.io/qwik";
import { Link, routeLoader$, useLocation } from "@builder.io/qwik-city";
import { db } from "~/db/db";

export const useReadSnippet = routeLoader$(async (request) => {
  const { id } = request.params;

  const snippet = await db.snippet.findUnique({
    where: {
      id: Number(id),
    },
  });
  if (!snippet) {
    request.status(404);
  }
  return snippet;
});

export const SnippetsShow = component$(() => {
  const snippet = useReadSnippet();

  if (!snippet.value?.code) return <div>Opps not found</div>;

  return (
    <div>
      <div class="rounded border p-4">
        <div
          style={{
            justifyContent: "space-between",
            margin: "1rem",
          }}
          class="m-4 flex items-center justify-between"
        >
          <h3 class="text-xl font-bold">{snippet.value.title}</h3>
          <div class="flex gap-4">
            <Link
              class="rounded border p-2"
              href={`/snippets/${snippet.value.id}/edit`}
            >
              Edit
            </Link>
            <button class="rounded border p-2">Delete</button>
          </div>
        </div>
        <pre class="rounded bg-gray-100 p-2">
          <code>{snippet.value.code}</code>
        </pre>
      </div>
    </div>
  );
});

export default SnippetsShow;
`

is this a bug? 

### Reproduction

https://github.com/Complugg3d/snippets-qwik

### Steps to reproduce

Run npm install 
then npm  start

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 19.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    Watchman: 2022.12.26.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.2.1
  npmPackages:
    @builder.io/qwik: ^1.3.2 => 1.3.2
    @builder.io/qwik-city: ^1.3.2 => 1.3.2
    undici: ^5.26.0 => 5.28.2
    vite: ^5.0.6 => 5.0.10
```

**Comment by Complugg3d** [comment]
So it looks like the client is not receiving the latest value but the server has it
<img width="273" alt="Screenshot 2024-01-14 at 11 50 28 a m" src="https://github.com/BuilderIO/qwik/assets/8353641/da5b9a9c-f025-42ce-8090-f9e3aabd7d7f">
<img width="731" alt="Screenshot 2024-01-14 at 11 51 54 a m" src="https://github.com/BuilderIO/qwik/assets/8353641/9bdf18e1-e02b-4dd6-9597-abe509c02e36">

**Comment by wmertens** [comment]
@Complugg3d did you resolve the issue? What was the problem?
