### ISSUE TITLE
[🐞] <Low priority> since v1.4.0 fixes the error on v1.3.5: Newly created project on v1.3.5 of Qwik generates VS Code IDE warnings (red squigglies) for all JSX DOM elements. 

### ISSUE THREAD

**Issue by calirails** [BuilderIO/qwik#5737]
### Which component is affected?

Qwik Developer Experience (in VSCode)

### Describe the bug

I am learning Qwiki and followed the documentation to create a new project. After I create the new project, I expect the generated .tsx to have error free JSX but instead get red squigglies and errors on each DOM element that indicates 
``JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.ts(7026)`` I've tried searching on Google and Discored but have not found a relevant article to help fix this and hope you can guide me on what to do.

<img width="672" alt="image" src="https://github.com/BuilderIO/qwik/assets/942698/1b8c9192-e135-4bab-a7db-ea3ccd729056">

### Reproduction

https://github.com/calirails/qwik-starter

### Steps to reproduce

1. I created a new project using the @latest tag that maps to v1.3.5 of '@builder/qwik' and '@builder/qwik-city'.
`$yarn create qwik@latest`
2. I select new qwik city project and take all the defaults for remaining options
3. I cd into the new directory
`$cd qwik-app`
4. I open up VS Code and see the errors with every generated .tsx file; including the file at: /src/components/starter/header/header.tsx
`$code .`
5. All .tsx files with components, including the file at: /src/components/starter/header/header.tss contains the errors that are shown above in the description; i.e.
```JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.ts(7026)```

### System Info

```shell
npx envinfo --system --npmPackages '{vite,undici,@builder.io/*}' --binaries --browsers
Need to install the following packages:
  envinfo@7.11.0
Ok to proceed? (y) y

  System:
    OS: macOS 14.2.1
    CPU: (24) arm64 Apple M2 Ultra
    Memory: 51.72 GB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - ~/.nvm/versions/node/v20.3.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.0/bin/npm
    pnpm: 7.14.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Edge: 120.0.2210.144
    Safari: 17.2.1
  npmPackages:
    @builder.io/qwik: ^1.3.5 => 1.3.5
    @builder.io/qwik-city: ^1.3.5 => 1.3.5
    undici: * => 5.28.2
    vite: ^5.0.11 => 5.0.11
```

### Additional Information

I am running on a mac air sonoma. I use NVM and have this setup.
node -v
v20.3.0
npm -v
9.6.7

**Comment by wmertens** [comment]
Yes, 1.4 is indeed the fix for that. There's no real breakage so upgrade away :)
