### ISSUE TITLE
[🐞] computed signals do not get serialized with refs

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/qwik#5738]
### Which component is affected?

Qwik Runtime

### Describe the bug

It seems that Qwik does not register when the computed signal should be serialized.

According to wout, this might be fixed in v2?

<img width="830" alt="image" src="https://github.com/BuilderIO/qwik/assets/104264123/19191ae8-58c2-43ea-a6de-0d4d33c6a07c">

### Reproduction

https://qwik.builder.io/playground/#v=1.3.5&f=Q0o0xhbG2BKNDqL2BTPhiVlHgfIEBQmd3Mqg1DRg8CCqeY8QXx8ncDvDNScVlFXsNIDuRaiHigJVQ7QhchjCbHggg43XA%2BbX0lSQGbWaXHCTMoDFfE4qpP4GmoSqHbn9gGwlxChNuFGwXAFpGAG5wEYM2M5aRNugGtmmWjswreCbCm9NjeagoZqDAA

### Steps to reproduce

Load playground
Click on the button

### System Info

```shell
N / A
```

**Comment by wmertens** [comment]
So the problem is the dirty task. Rendering the JSX changes the ref signal, and that in turn marks the useComputed as dirty but doesn't rerun it. The computed signal doesn't get updated and gets serialized as `undefined` and then on the client it doesn't get updated either.

Not sure how to tackle this.

**Comment by wmertens** [comment]
As you can see, on the server side it never reruns tasks, but on the client side it does:

https://qwik.builder.io/playground/#v=1.4.0&f=7VbLCsIwEPyVHAQrFvEgemoPguJBL%2BIPiKQI1haqPZSSf3d2N01SqOJV8NRHNjuzyT4mSJrVYjmUNLGfvvzqkjlWI8V%2FuNN9kVpyFNtkOLfQ9alJV3gVw3tz1BkOzQ%2F%2F3emwX7P62OSaCiiNEEVnn5VlaB1l5%2FyhJ4E7uwnLYufL0rJQfDyhbBhXdVGQbiHKZDuOCWeG4q%2FZt7tJZiv%2FiZLBohMXUctKwbhY34A8YQ0ANo7Y4UQwHGRC4wTF5qK6Yk7lWgQIogoPtA8Shu%2Fpw1NQ1qLs8AkVxvDGi5s2RDIpP9VBOzkoLeBjF0lSoiW8L72rmhOXjgXpTMlTy8dzIB8XYT%2BdmtTqDZhg5gDEkZHtW3XTTdLaDYazXmQsuP6b1e81qxc

I think we have to check for dirty tasks before outputting the result
