### ISSUE TITLE
[🐞]why the index.html file isn't being created. after using npm run build in qwik project?

### ISSUE THREAD

**Issue by Kavin-Sunware** [BuilderIO/qwik#5747]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I try to build a project. using npm run build. I expected to create index.html file in dist or build folder, however the actual result did not include the index.html.
![image](https://github.com/BuilderIO/qwik/assets/110604348/5452dd70-7bae-4731-9025-7f147422f6da)

### Reproduction

none

### System Info

```shell
npx
```

**Comment by gioboa** [comment]
Hi @Kavin-Sunware, out of the box with the [Qwik CLI](https://qwik.builder.io/docs/getting-started/#create-an-app-using-the-cli) you have a SSR project, so no static files like index.html. You can use the [static site adapter](https://qwik.builder.io/docs/deployments/static/) to create your html files.

**Comment by Kavin-Sunware** [comment]
hey @gioboa Thanks!, let me try.

**Comment by gioboa** [comment]
Nice. :+1: So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
Thanks
