### ISSUE TITLE
[🐞] Qwik starter code has duplicated CSS code in global.css

### ISSUE THREAD

**Issue by linkfang** [BuilderIO/qwik#5756]
### Which component is affected?

Qwik Runtime

### Describe the bug

Use any package manager to create a new qwik app, e.g. `npm create qwik@latest` and then check the `global.css`, we will see duplicated CSS code.

I looked into the source code and found the reason of this duplication is the `mergeCss` function in `packages\qwik\src\cli\add\update-files.ts`. 

Proposals:
I personally have 2 proposals.
1. When creating a new Qwik app, I am not sure if there is a solid reason to merge the initial styles instead of using the selected starter/template one? So, if possible, I guess we can overwrite the global.css file instead of merging it?
2. If merging the global.css is indeed a necessary step, then maybe we should trim the `global.css` files in different directories to make sure the code in base version won't appear in other instances (`/basic/src/global.css`, `/site-with-visual-cms/src/global.css`, etc.).   
And probably, we could also put the base version at the top so that other version can override the base style. Put base version at top can also avoid empty lines at the top when create qwik with `empty` option. Because for now the merging logic doesn't skip new lines when `srcContent` is empty, here is the code in `update-files.ts` `line 186`: `const mergedContent = srcContent.trim() + '\n\n' + destContent.trim() + '\n';` 

Thanks!

### Reproduction

https://stackblitz.com/edit/qwik-starter-nq65tm?file=src%2Fglobal.css

### Steps to reproduce

The link should open `global.css` by default and the duplicated code should be easy to see.

As mentioned above, the base style is at the bottom of the file which is a little bit strange as the selected starter CSS code will be override by base version if they define different styles.

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 4.57 GB / 15.60 GB
  Binaries:
    Node: 21.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/partytown: ^0.8.2 => 0.8.2
    @builder.io/qwik: workspace:* => 1.4.0
    undici: * => 6.3.0
    vite: ^5.0.11 => 5.0.11
```

**Comment by gioboa** [comment]
Nice catch :clap: i.e. in the basic starter I don't want any CSS variables at all.
I think the first way (overwrite the global.css) is more predictable process.
Merging CSS is ok, but it can mess up things in different scenarios, so the overwrite way is more robust.
May I ask you to drop a PR for that pls?

**Comment by linkfang** [comment]
Hi @gioboa , I dig into the code a little deeper and find that the `mergeCss` is useful when we add a CSS library by `qwik add`, e.g. `npm run qwik add pandacss`. In this case, we don't want the new `global.css` generated by pandacss overwrite what we already have, because we might already add our own css in `global.css` 

So, I would like to check what process is calling the function, if it's project initialization, then overwrite, but if it's not, then merge. How does this sound?

And is there a way for me to play around with `npm create qwik@latest`? I meant a way for me to use my local version to create a new qwik project instead of installing the latest version from npm. 
For now I am playing around with the one inside `node_modules`, so I can only see the process of `npm run qwik add [library name]` but can't see anything when initialize.

**Comment by gioboa** [comment]
It sounds nice. You can use `cli.qwik` script or build and link the library to test it.
