### ISSUE TITLE
[🐞] HMR not working in starter template (issue with Vite 5.0)

### ISSUE THREAD

**Issue by kevhof** [BuilderIO/qwik#5773]
### Which component is affected?

Starters / CLI

### Describe the bug

I created a new Qwik project with `npm create qwik@latest`.

The issue is that HMR doesn't work on every file. For example:
- updating `starter/hero/hero.tsx` --> HMR works
- updating `starter/footer/footer.tsx` --> HMR doesn't work

The issue seems to be linked to Vite version. Vite 5.0 default installed version seems to be causing the issue. Installing Vite 4 last version resolves the issue.

### Reproduction

https://stackblitz.com/edit/github-y5nrmn?file=src%2Fcomponents%2Fstarter%2Fhero%2Fhero.tsx

### Steps to reproduce

On your local machine, run `npm create qwik@latest` and follow the steps.

The issue:
- updating `starter/hero/hero.tsx` --> HMR works
- updating `starter/footer/footer.tsx` --> HMR doesn't work

Now revert back to Vite 4 and HMR works again :
```shell
npm uninstall vite
npm install -D vite@4
```

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 115.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.234
  npmPackages:
    @builder.io/qwik: ^1.4.1 => 1.4.1 
    @builder.io/qwik-city: ^1.4.1 => 1.4.1 
    undici: * => 6.4.0 
    vite: ^5.0.12 => 5.0.12
```

**Comment by wmertens** [comment]
Hmm. There are also some weird errors with Vite 5 sometimes. I suppose we should downgrade Vite to 4 in the starters, there's no real downside to that.

**Comment by wmertens** [comment]
@balaji-sivasakthi Github closes issues automatically when their PR gets merged :)
