### ISSUE TITLE
[DOCS] Need to have an example using router with .(js,ts)x

### ISSUE THREAD

**Issue by harrytran998** [BuilderIO/qwik#579]
**How can the documentation be improved?**
I add an `index.tsx` file and delete all the MDX files in the pages folder with `Qwik-city` with the router example. But it does not work 🥹. Hopefully, your team can have a basic example with routing support! Thanks <3

**Comment by nnelgxorz** [comment]
#545 shows that jsx and tsx files aren't supported in routes at the moment.

I think you can work around it by using an .mdx file to define the route, and making your .tsx file a layout that the .mdx file references.

**Comment by manucorporat** [comment]
We will add this features along with nested layouts, catch all routes and params next week!

**Comment by nnelgxorz** [comment]
Hey @harrytran998! The new Qwik City starter has .tsx routes and there are also [Qwik City docs](https://qwik.builder.io/qwikcity/overview) that explain further. Hope that helps!

**Comment by manucorporat** [comment]
QwikCity docs are available now! and more to come
