### ISSUE TITLE
[BUG] useServerMount does not run

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#580]
### Qwik Version

0.0.23

### Operating System (or Browser)

Linux

### Node Version (if applicable)

v16.3.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

The callback that is passed to useServerMount is executed.

### Actual Behaviour

It doesn't seem to execute the callback.

### Additional Information

Reproduction Steps:

1. Spin up a new starter with npm init qwik@latest
2. Use the standard starter (any server, default options)
3. Add the following code to app.tsx under the state declaration:
`useServerMount$(() => {
    console.log("Running server mount");
    state.name = "Qwik"
  });`
4. npm run dev. The console log is never printed and name is still set as 'World'

**Comment by manucorporat** [comment]
We have an internal discussion in the team about this, by default `npm run dev` is running qwik fully in the browser, no server. So no code runs.

```
npm run dev.ssr
```

should do the trick, we might make it the default option soon!

**Comment by manucorporat** [comment]
can you provide a sample code that reproduces the issue?
ideally a playground link: https://qwik.builder.io/playground

**Comment by nnelgxorz** [comment]
You bet! Thanks for all the help!

[Reproduction](https://qwik.builder.io/playground#version=0.0.24&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZhcHAudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGNvbXBvbmVudCUyNCUyQyUyMHVzZVN0b3JlJTJDJTIwdXNlU2VydmVyTW91bnQlMjQlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzdGF0ZSUyMCUzRCUyMHVzZVN0b3JlKCU3QiU1Q24lMjAlMjAlMjAlMjBuYW1lJTNBJTIwJ1dvcmxkJyU1Q24lMjAlMjAlN0QpJTIwJTVDbiUyMCUyMHVzZVNlcnZlck1vdW50JTI0KGFzeW5jKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ1J1bm5pbmclMjBzZXJ2ZXIlMjBtb3VudCUyMGNhbGxiYWNrJyklNUNuJTIwJTIwJTIwJTIwc3RhdGUubmFtZSUyMCUzRCUyMCdRd2lrJyU1Q24lMjAlMjAlN0QpJTVDbiUyMCUyMHJldHVybiUyMCUzQ3AlM0VIZWxsbyUyMCU3QnN0YXRlLm5hbWUlN0QlM0MlMkZwJTNFJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlbmRlclRvU3RyaW5nJTJDJTIwUmVuZGVyVG9TdHJpbmdPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMHJlbmRlcihvcHRzJTNBJTIwUmVuZGVyVG9TdHJpbmdPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZwbGF5Z3JvdW5kJTJGcm9vdC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwQXBwJTIwJTdEJTIwZnJvbSUyMCcuJTJGYXBwJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBSb290JTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwKCU1Q24lMjAlMjAlMjAlMjAlM0NodG1sJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2hlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDdGl0bGUlM0VIZWxsbyUyMFF3aWslM0MlMkZ0aXRsZSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2JvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDQXBwJTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmJvZHklM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGaHRtbCUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCUzQiU1Q24lMjIlN0QlNUQ%3D)

**Comment by manucorporat** [comment]
Thanks a lot for the repo case! https://github.com/BuilderIO/qwik/pull/586
this should fix it, hope to merge today and ship a new release

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/pull/586
