### ISSUE TITLE
[✨] Allow to use native fetch in browser

### ISSUE THREAD

**Issue by ziimakc** [BuilderIO/qwik#5808]
### Is your feature request related to a problem?

I would like to avoid downloading 2.6mb `undici` in browser while native `fetch` is available there.

```
(https://site.test/@fs/home/me/apps/test/node_modules/.pnpm/@builder.io+qwik@1.4.3_@types+node@20.11.16_undici@6.6.0/node_modules/@builder.io/qwik/core.mjs?v=b666f2aa)
```

### Describe the solution you'd like

Add a configuration option to use native `fetch` if targeting modern browser.

**Comment by wmertens** [comment]
Solved by #5702 but we didn't merge yet because it's a breaking change in node versions.

However I learned today that node 16 doesn't even work :)
