### ISSUE TITLE
[✨] Support for routing without file system based routing

### ISSUE THREAD

**Issue by saurabhgupta050890** [BuilderIO/qwik#5829]
### Is your feature request related to a problem?

Currently the only way to have routes is based on file system routing. This seems like a industry standard right now but in many cases file based routing is actually not useful. In our use case the routes are highly dynamic and tying folder structure to routes (as is the case with file system routes) is not suitable

### Describe the solution you'd like

A way to disable file system routing and provide configurations which describe routes and corresponding page mapping.

### Describe alternatives you've considered

We are using a nextjs in our app currently and it does provide an option to disable file system routes. Couldn't find any alternative for qwik and qwik city

**Comment by dejurin** [comment]
You could use **...catchall**, works great.

**Comment by wmertens** [comment]
@saurabhgupta050890  Right, ...catchAll is meant for that, and you can create helper functions that implement the sort of routing you want. I'm going to close this to keep the issue list short, but if you come up with a nice way to do it or want to discuss it, feel free to update this PR or go to the dx-discussions channel on discord to flesh it out.
