### ISSUE TITLE
[📖] "bun start" crashes on windows (for now)

### ISSUE THREAD

**Issue by codethinki** [BuilderIO/qwik#5833]
### Suggestion

your doc is wrong, there is no "bun start" it is "bun run start" (getting started page), nothing too serious

**Comment by gioboa** [comment]
I created a project from scratch and it's working fine in my env 

![image](https://github.com/BuilderIO/qwik/assets/35845425/e9337f81-3a10-4f3d-b183-1a3b897a338a)

**Comment by codethinki** [comment]
okay apparently i did something wrong. Now its at least showing an error instead of saying there is no start when using "bun start": 
![image](https://github.com/BuilderIO/qwik/assets/89145039/b639cb11-6879-4a34-bc14-b598e888b9d8)

Should be because bun is still experimental on windows maybe you could include that. But then again they say don't use bun on windows its experimental so idk but your right the command works as is (at least on linux). 

("bun run start" still works fine)

**Comment by gioboa** [comment]
Unfortunately we can't do so much to solve this bun limitation. In the [bun codebase](https://github.com/oven-sh/bun/blob/e171f04ce6233b7d2360902c758b87a72de77dfd/src/shell/subproc.zig#L1253) there is a specific throw for that. 

> Should be because bun is still experimental on windows maybe you could include that. But then again they say don't use bun on windows its experimental so idk but your right the command works as is (at least on linux).

It's a good idea. Would you like to drop a PR for that pls?

**Comment by codethinki** [comment]
i think i did it idk never done that before
