### ISSUE TITLE
[🐞] requestEvent.request.formData() in routeAction$

### ISSUE THREAD

**Issue by sontui** [BuilderIO/qwik#5850]
### Which component is affected?

Qwik Runtime

### Describe the bug

Can't access to requestEvent.request.formData() in routeAction$
This throws the error `[vite] Internal server error: The body has already been consumed.`

`import { component$ } from "@builder.io/qwik";`
`import { Form, routeAction$ } from "@builder.io/qwik-city";`
`export const useUploadFileAction = routeAction$(async (data, requestEvent) => {`
`	const formData = await requestEvent.request.formData();`
`	console.log(formData);`
`});`
`export default component$(() => {`
`	const useAction = useUploadFileAction();`
`	return (`
`		<Form action={useAction} class="space-y-4">`
`			<input type="file" name="file[]" multiple={true} id="file" required />`
`			<button type="submit">Valider</button>`
`		</Form>`
`	);`
`})`

Please help me to fix this or find an alternative to recover sent files
In Qwik@1.4.5 =>
![Qwik1 4 5](https://github.com/BuilderIO/qwik/assets/52534548/878af461-0521-40ee-9f46-1a0a70f3a692)

For information, I tried on qwik@1.1.5 and it worked in this version
In Qwik@1.1.5 =>
![Qwik1 1 5](https://github.com/BuilderIO/qwik/assets/52534548/975be887-9a34-4242-b901-ce932b968ebf)

### Reproduction

https://github.com/sontui/test-app

### Steps to reproduce

npm install
npm start
try to upload a file and see the error in console

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
    Memory: 3.10 GB / 15.89 GB
  Binaries:
    Node: 20.11.0 - C:\produits\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.2.0 - C:\produits\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.19041.3636
```

**Comment by notcod** [comment]
```
export const useUploadFileAction = routeAction$(async (data, requestEvent) => {
	console.log(data);
});
```

**Comment by sontui** [comment]
Thanks @notcod. I tried this but I had a mistake in my code after...
Have a nice day !
