### ISSUE TITLE
[📖] Provide a section on how to disable ESLint rules

### ISSUE THREAD

**Issue by hosseinitabar** [BuilderIO/qwik#5852]
### Suggestion

I want to disable this warning:

> DockerContainer | 11:51:53 AM [vite] warning: Calling use* methods in wrong function.
DockerContainer |   Plugin: vite-plugin-qwik

And I found out that the source code is [here](https://github.com/BuilderIO/qwik/blob/58b01ef26cf2f02d566d5154b50b433db77a313e/packages/eslint-plugin-qwik/src/useMethodUsage.ts#L16).

Yet I have no idea what rule should I disable in my ESLint configuration file.
I thought maybe it could be a good idea that you provide a section in your docs site to tell us about linting and related stuff.

Thanks

**Comment by gioboa** [comment]
[here](https://qwik.dev/docs/advanced/eslint/) you can find the documentation
