### ISSUE TITLE
[📖] docs layout issue with changed browser-wide default font size

### ISSUE THREAD

**Issue by asteo-net** [BuilderIO/qwik#5853]
### Suggestion

The `font-size` is not defined on the `html` tag, thus the browser default is used for the `rem` unit.
With `1rem != 16px`, the layout is broken (left nav overlaps with main content for values <16px).

**Comment by wmertens** [comment]
Could I implore you for a quick PR?

**Comment by asteo-net** [comment]
Sure. I took the time to fix it properly instead of just adding `html { font-size: 16px; }`.
This way, it will not worsen the experience for different font sizes. Still, the website lacks proper font-size etiquette (should always avoid absolute values for font-sizes). Just something to keep in mind for the future ;-)
