### ISSUE TITLE
Qwik showcase page has zooms in after scrolling to certain part

### ISSUE THREAD

**Issue by bwmp** [BuilderIO/qwik#5881]
https://github.com/BuilderIO/qwik/assets/67001116/2953d49d-1a02-4f93-aa74-acdc24ed9ae5

I dont know how else to describe it other that showing it or people trying it for themselves

**Comment by wmertens** [comment]
There's a thumbnail that 404s, https://qwik.dev/showcases/itbusinesshub_com_.webp, and as soon as that tries to load, all the images on the page become very wide.

It's as if the 404 causes some CSS constraint to be lifter.

**Comment by pleopardi** [comment]
There are three images missing: `itbusinesshub_com_.webp`, `radixstream_com_.webp`, and`www_anirbandas_in_.webp`

Adding a `width: "100%"` to the img element on the showcase page should fix it nonetheless, I tried it live with the developer tools open.

I also wanted to open a PR but I have issues running the project for local development (some Rust dependencies requiring different versions), I may try again with more time to troubleshoot it.

**Comment by gioboa** [comment]
I'm recreating all the images with `pnpm build.showcase` script. Let's see if it solves the issue.

**Comment by gioboa** [comment]
Thanks @pleopardi for your help. I added the missing images and now it's working fine.
Closed by #5889
