### ISSUE TITLE
[🐞] Custom 404 is generated, but not used automatically

### ISSUE THREAD

**Issue by intellix** [BuilderIO/qwik#5890]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I'm trying to use a custom 404 page and followed the example from the docs: https://qwik.dev/docs/advanced/routing/ - as I'm understanding it, I need to create a 404.tsx in routes and go to /sdfdsfdsf to see my custom 404 page instead of the default one. After doing that, I'm seeing the **default** 404 page and a 404.html file generated which I can visit. 

I was under the impression that instead of seeing the default 404 page, it would use my custom 404 page. If only the default 404 is used locally for development purposes, then I guess the docs should reflect that behaviour. 

### Reproduction

https://stackblitz.com/edit/qwik-starter-uhmynv

### Steps to reproduce

1. Create a qwik city project `pnpm create qwik@latest`
2. Add a 404.tsx at the base and fill it with something like "Custom 404"
3. Go to /avsdgfsdfsdfdsf - notice that the default 404 is used

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 87.45 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.volta/tools/image/node/18.18.2/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.4 - ~/.volta/tools/image/npm/8.19.4/bin/npm
    pnpm: 8.15.3 - ~/.volta/tools/image/pnpm/8.15.3/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Edge: 122.0.2365.52
    Safari: 17.3.1
  npmPackages:
    @builder.io/qwik: ^1.4.5 => 1.4.5 
    @builder.io/qwik-city: ^1.4.5 => 1.4.5 
    undici: * => 6.6.2 
    vite: ^5.0.12 => 5.1.4 
```

### Additional Information

In this screenshot you can see that it generated a 404.html file and it's viewable but it's not being used. I tried both dev and preview and neither of them ever worked.

<img width="440" alt="Screenshot 2024-02-25 at 09 51 58" src="https://github.com/BuilderIO/qwik/assets/1162531/3004f5f9-fe4f-40ad-9734-5eec50ecc140">

**Comment by gioboa** [comment]
Hi, it's working ad intended
[Here is](https://qwik.dev/docs/advanced/routing/#custom-404-page) the doc
Extract from the docs
>Note: During development and in preview mode, the custom 404 pages will not be rendered, but instead the default Qwik City 404 page will show. However, when building the app for production, the custom 404 page will be statically generated as a static 404.html file.
