### ISSUE TITLE
[🐞] qwik.dev is down/gives a 404

### ISSUE THREAD

**Issue by holgergp** [BuilderIO/qwik#5928]
### Which component is affected?

Qwik Playground

### Describe the bug

This is just a heads up. The [qwik.dev](https://qwik.dev/) website is down for me. I get a 404 when trying to access it. And https://downforeveryoneorjustme.com/qwik.dev agrees with me. 
Maybe just a glitch.

### Reproduction

https://qwik.dev/

### System Info

```shell
https://downforeveryoneorjustme.com/qwik.dev
```

**Comment by wmertens** [comment]
My fault, back up now

**Comment by holgergp** [comment]
Thank you!
