### ISSUE TITLE
[🐞] ALT+CLICK doesnt work on windows but works on linux

### ISSUE THREAD

**Issue by LazyClicks** [BuilderIO/qwik#5933]
### Which component is affected?

Qwik Runtime

### Describe the bug

npm or pnpm create qwik@latest
pnpm or npm dev
ALT + CLICK on any elemnent
nothing happens
this error on chrome console appears

`Not allowed to load local resource: file:///C:/Users/ayoub/Desktop/playing-around/qwik-app/src/components/starter/hero/hero.tsx:10:12`

tried it in multiple windows machine same issue, ona new laptop that was sealed, same issue
on my work desktop as well same issue, so far i tried it in 4 different machines and all have that issue
my friend who has a dual boot system with windows and linux, it works for him in linux and not in windows

### Reproduction

https://github.com/LazyClicks/alt-click-qwik

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 309.89 MB / 15.91 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.22621.1
```

**Comment by Joristdh** [comment]
Duplicate of #3710

**Comment by LazyClicks** [comment]
> Duplicate of #3710

thank u
