### ISSUE TITLE
Add support for module path aliases (vite-tsconfig-paths)

### ISSUE THREAD

**Issue by IgnusG** [BuilderIO/qwik#594]
### Is your feature request related to a problem?

It's common for front-end projects to define module aliases to simplify relative paths from `../../../../../../../components/...` to something like `~/components/...`. There are a lot of different tools and plugins to achieve this (Vite itself supports them I believe natively). 

Qwik however does not seem to work with at least one of these popular plugins: [`vite-tsconfig-paths`](https://www.npmjs.com/package/vite-tsconfig-paths).

### Describe the solution you'd like

Ideally these plugins would work inside Qwik without any additional setup as part of the Vite pipeline.

### Describe alternatives you've considered

You can always say you don't/won't support aliases (many people advocate they are too magical anyway).

Projects that get large often do however need a more concise way of specifying imported modules and aliases are by far the simplest to setup (albeit with exceptions).

**Comment by manucorporat** [comment]
I think they should work... are you getting some error message? or silently not working?

**Comment by manucorporat** [comment]
thank you! i will look into it tomorrow!
