### ISSUE TITLE
[Alpha]: Context does not work when provided through a provider component using content projection

### ISSUE THREAD

**Issue by IgnusG** [BuilderIO/qwik#599]
### Qwik Version

0.0.25

### Operating System (or Browser)

Edge

### Which component is affected?

Qwik Runtime

### Expected Behaviour

I would expect the following to work:
```typescript
interface Colors {
  primary: string;
}

const ColorContext = createContext<Colors>("colorContext");

const ColorProvider = component$(({ colors: Colors }) => {
  const state = useStore(colors);
  
  useContextProvider(ColorContext, state);

  return <> <Slot /> </>;
});

const Text = component$(() => {
  const colors = useContext(ColorContext);

  return <p>Primary color: {colors.primary}</p>;
});

const App = component$(() => {
  const colors: Colors = { primary: "green" };

  return (
    <ColorProvider colors={colors}>
      <Text />
    </ColorProvider>
  );
});
```

This does not appear to work as `<Text />` seems to think its parent is `App` because that's where it's defined and not `ColorProvider` even though that's its parent in the rendered tree.

This pattern is very common in React and I think it should be supported if possible.

### Actual Behaviour

Currently one receives a context does not exist error if the above is used. To get this to work the provider cannot use content projection for its consumers:

For example like this (similar to code that's in the E2E folder):
```typescript
interface Colors {
  primary: string;
}

const ColorContext = createContext<Colors>("colorContext");

const Text = component$(() => {
  const colors = useContext(ColorContext);

  return <p>Primary color: {colors.primary}</p>;
})

const App = component$(() => {
  const colors: Colors = { primary: "green" };

  const state = useStore(colors);
  
  useContextProvider(ColorContext, state);

  return (
      <Text />
  );
});
```

### Additional Information

This feels unnatural and I spent quite a few hours going back and forth testing and comparing when I get this error and when context works as expected.

> Since it's an alpha feature (and undocumented too - sorry for poking around it lol 😅) I assume this might be a bug. But maybe this is intended to preserve the scope of the projected content or some other semantics of Slots, in which case I would have to say again that it feels unnatural in the way we think of context (especially from the React realm) and could became a footgun in the future.

**Comment by manucorporat** [comment]
The issue makes a lot of sense! it should be fixed + added new tests on monday!
Thanks for opening this amazing detailed and explained issue :)

**Comment by IgnusG** [comment]
Thanks for the super fast fix @manucorporat! 🚀
