### ISSUE TITLE
[🐞] requestEvent.url.hash is always the empty string, even when the URL contains a hash

### ISSUE THREAD

**Issue by blakeley** [BuilderIO/qwik#5996]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When I navigate to a route like `/articles/cool-story#my-header`,
I expect `requestEvent.url.hash` to contain the string `"#my-header"` or `"my-header"`
Instead, it contains the empty string `""`

### Reproduction

https://stackblitz.com/edit/qwik-starter-d6vo28?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Load the reproduction URL, click on either of the links in the demo. Note that the code contains text to display the urlHash.value, but it never displays anything. Also note that the `routeLoader$` logs the value of `requestEvent.url` and shows `.hash` to be empty.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 889.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.7.4 - /opt/homebrew/bin/pnpm
    bun: 1.0.29 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.112
    Edge: 122.0.2365.80
    Safari: 17.2.1
  npmPackages:
    @builder.io/qwik: ^1.5.1 => 1.5.1 
    @builder.io/qwik-city: ^1.5.1 => 1.5.1 
    undici: * => 6.7.1 
    vite: ^5.1.4 => 5.1.6
```

### Additional Information

This issue is likely related to https://github.com/BuilderIO/qwik/issues/4767, but it is a distinct issue; this one is about the server-side `requesteEvent.url.hash` whereas that is about the client-side `useLocation()` hook value.

**Comment by wmertens** [comment]
I'm afraid that's just how HTTP works, browsers don't send the URL hash to servers, only the query. You can verify this yourself by looking at the network tab in your browser.
