### ISSUE TITLE
Immutable/Mutable Props Behave Strangely

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#600]
### Qwik Version

0.0.25

### Operating System (or Browser)

Linux

### Which component is affected?

Qwik Runtime

### Expected Behaviour

In this contrived example, there is an array of Widgets which at the moment only contain ids that are rendered with a map function. When you click a rendered Widget, it sorts the array to put the clicked widget at the top of the list.

[Playground link](https://qwik.builder.io/playground#version=0.0.25&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZhcHAudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGNvbXBvbmVudCUyNCUyQyUyMHVzZVN0b3JlJTJDJTIwY3JlYXRlQ29udGV4dCUyQyUyMHVzZUNvbnRleHRQcm92aWRlciUyQyUyMHVzZUNvbnRleHQlMkMlMjBtdXRhYmxlJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGludGVyZmFjZSUyMEFwcFN0YXRlJTIwJTdCJTVDbiUyMCUyMHdpZGdldHMlM0ElMjBXaWRnZXREYXRhJTVCJTVEJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBTVEFURSUyMCUzRCUyMGNyZWF0ZUNvbnRleHQlM0NBcHBTdGF0ZSUzRSgnR2xvYmFsU3RhdGUnKSU1Q24lNUNuaW50ZXJmYWNlJTIwV2lkZ2V0RGF0YSUyMCU3QiU1Q24lMjAlMjBpZCUzQSUyMG51bWJlciU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwV2lkZ2V0JTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSUyMCU3QmRhdGElM0ElMjBXaWRnZXREYXRhJTdEKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCY291bnQlM0ElMjAwJTdEKSU1Q24lMjAlMjBjb25zdCUyMGFwcCUyMCUzRCUyMHVzZUNvbnRleHQoU1RBVEUpJTVDbiUyMCUyMHJldHVybiUyMCUzQ2J1dHRvbiUyMGlkJTNEJTdCJTYwJTI0JTdCcHJvcHMuZGF0YS5pZCU3RCU2MCU3RCUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBzdGF0ZS5jb3VudCUyMCUzRCUyMHN0YXRlLmNvdW50JTIwJTJCJTIwMSUzQiU1Q24lMjAlMjAlMjAlMjBhcHAud2lkZ2V0cy5zb3J0KChhJTJDJTIwYiklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ1Byb3AlMjBJRCclMkMlMjBwcm9wcy5kYXRhLmlkKSU1Q24lMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChhLmlkJTIwJTNEJTNEJTNEJTIwcHJvcHMuZGF0YS5pZCklMjAlN0JyZXR1cm4lMjAxJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKGIuaWQlMjAlM0QlM0QlM0QlMjBwcm9wcy5kYXRhLmlkKSUyMCU3QnJldHVybiUyMC0xJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMDAlNUNuJTIwJTIwJTIwJTIwJTdEKSU1Q24lMjAlMjAlMjAlMjAlN0QlN0QlM0UlNUNuJTIwJTIwJTIwJTIwSUQlM0ElMjAlN0Jwcm9wcy5kYXRhLmlkJTdEJTIwQ291bnQlM0ElMjAlN0JzdGF0ZS5jb3VudCU3RCU1Q24lMjAlMjAlM0MlMkZidXR0b24lM0UlNUNuJTdEKSU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzdGF0ZSUzQSUyMEFwcFN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCJTVDbiUyMCUyMCUyMCUyMHdpZGdldHMlM0ElMjAlNUIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdCaWQlM0ElMjAwJTJDJTIwY291bnQlM0ElMjAwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3QmlkJTNBJTIwMSUyQyUyMGNvdW50JTNBJTIwMCU3RCU1Q24lMjAlMjAlMjAlMjAlNUQlNUNuJTIwJTIwJTdEKSU1Q24lMjAlMjB1c2VDb250ZXh0UHJvdmlkZXIoU1RBVEUlMkMlMjBzdGF0ZSklNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTNFJTVDbiUyMCUyMCUyMCU3QnN0YXRlLndpZGdldHMubWFwKGRhdGElMjAlM0QlM0UlMjAlM0NXaWRnZXQlMjBkYXRhJTNEJTdCZGF0YSU3RCUyRiUzRSklN0QlNUNuJTIwJTIwJTNDJTJGZGl2JTNFJTNCJTVDbiU3RCklM0IlMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcGxheWdyb3VuZCUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJUb1N0cmluZ09wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwcmVuZGVyKG9wdHMlM0ElMjBSZW5kZXJUb1N0cmluZ09wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBBcHAlMjAlN0QlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D)

### Actual Behaviour

First, when clicking a widget (either first click or second click) you will get an error that props are immutable by default. This is seems wrong because the id of the Widget is only referenced, never modified.

Change line 38 so that `data={data}` becomes `data={mutable(data)}`.

Now the immutable props error goes away, but the props.data.id is now undefined in the onClick$ handler as shown by the console log on line 19. [Reproduction](https://qwik.builder.io/playground#version=0.0.25&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZhcHAudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGNvbXBvbmVudCUyNCUyQyUyMHVzZVN0b3JlJTJDJTIwY3JlYXRlQ29udGV4dCUyQyUyMHVzZUNvbnRleHRQcm92aWRlciUyQyUyMHVzZUNvbnRleHQlMkMlMjBtdXRhYmxlJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGludGVyZmFjZSUyMEFwcFN0YXRlJTIwJTdCJTVDbiUyMCUyMHdpZGdldHMlM0ElMjBXaWRnZXREYXRhJTVCJTVEJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBTVEFURSUyMCUzRCUyMGNyZWF0ZUNvbnRleHQlM0NBcHBTdGF0ZSUzRSgnR2xvYmFsU3RhdGUnKSU1Q24lNUNuaW50ZXJmYWNlJTIwV2lkZ2V0RGF0YSUyMCU3QiU1Q24lMjAlMjBpZCUzQSUyMG51bWJlciU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwV2lkZ2V0JTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSUyMCU3QmRhdGElM0ElMjBXaWRnZXREYXRhJTdEKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCY291bnQlM0ElMjAwJTdEKSU1Q24lMjAlMjBjb25zdCUyMGFwcCUyMCUzRCUyMHVzZUNvbnRleHQoU1RBVEUpJTVDbiUyMCUyMHJldHVybiUyMCUzQ2J1dHRvbiUyMGlkJTNEJTdCJTYwJTI0JTdCcHJvcHMuZGF0YS5pZCU3RCU2MCU3RCUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBzdGF0ZS5jb3VudCUyMCUzRCUyMHN0YXRlLmNvdW50JTIwJTJCJTIwMSUzQiU1Q24lMjAlMjAlMjAlMjBhcHAud2lkZ2V0cy5zb3J0KChhJTJDJTIwYiklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ1Byb3AlMjBJRCclMkMlMjBwcm9wcy5kYXRhLmlkKSU1Q24lMjAlMjAlMjAlMjAlMjAlMjBpZiUyMChhLmlkJTIwJTNEJTNEJTNEJTIwcHJvcHMuZGF0YS5pZCklMjAlN0JyZXR1cm4lMjAxJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKGIuaWQlMjAlM0QlM0QlM0QlMjBwcm9wcy5kYXRhLmlkKSUyMCU3QnJldHVybiUyMC0xJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMDAlNUNuJTIwJTIwJTIwJTIwJTdEKSU1Q24lMjAlMjAlMjAlMjAlN0QlN0QlM0UlNUNuJTIwJTIwJTIwJTIwSUQlM0ElMjAlN0Jwcm9wcy5kYXRhLmlkJTdEJTIwQ291bnQlM0ElMjAlN0JzdGF0ZS5jb3VudCU3RCU1Q24lMjAlMjAlM0MlMkZidXR0b24lM0UlNUNuJTdEKSU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzdGF0ZSUzQSUyMEFwcFN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCJTVDbiUyMCUyMCUyMCUyMHdpZGdldHMlM0ElMjAlNUIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdCaWQlM0ElMjAwJTJDJTIwY291bnQlM0ElMjAwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3QmlkJTNBJTIwMSUyQyUyMGNvdW50JTNBJTIwMCU3RCU1Q24lMjAlMjAlMjAlMjAlNUQlNUNuJTIwJTIwJTdEKSU1Q24lMjAlMjB1c2VDb250ZXh0UHJvdmlkZXIoU1RBVEUlMkMlMjBzdGF0ZSklNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTNFJTVDbiUyMCUyMCUyMCU3QnN0YXRlLndpZGdldHMubWFwKGRhdGElMjAlM0QlM0UlMjAlM0NXaWRnZXQlMjBkYXRhJTNEJTdCbXV0YWJsZShkYXRhKSU3RCUyRiUzRSklN0QlNUNuJTIwJTIwJTNDJTJGZGl2JTNFJTNCJTVDbiU3RCklM0IlMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcGxheWdyb3VuZCUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJUb1N0cmluZ09wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwcmVuZGVyKG9wdHMlM0ElMjBSZW5kZXJUb1N0cmluZ09wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBBcHAlMjAlN0QlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D)

Now, if you destructure the props by adding `const {id} = props.data;` to line sixteen and changing the props.data.id references to just id, you have access to the id again. [Reproduction](https://qwik.builder.io/playground#version=0.0.25&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZhcHAudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGNvbXBvbmVudCUyNCUyQyUyMHVzZVN0b3JlJTJDJTIwY3JlYXRlQ29udGV4dCUyQyUyMHVzZUNvbnRleHRQcm92aWRlciUyQyUyMHVzZUNvbnRleHQlMkMlMjBtdXRhYmxlJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGludGVyZmFjZSUyMEFwcFN0YXRlJTIwJTdCJTVDbiUyMCUyMHdpZGdldHMlM0ElMjBXaWRnZXREYXRhJTVCJTVEJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBTVEFURSUyMCUzRCUyMGNyZWF0ZUNvbnRleHQlM0NBcHBTdGF0ZSUzRSgnR2xvYmFsU3RhdGUnKSU1Q24lNUNuaW50ZXJmYWNlJTIwV2lkZ2V0RGF0YSUyMCU3QiU1Q24lMjAlMjBpZCUzQSUyMG51bWJlciU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwV2lkZ2V0JTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSUyMCU3QmRhdGElM0ElMjBXaWRnZXREYXRhJTdEKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCY291bnQlM0ElMjAwJTdEKSU1Q24lMjAlMjBjb25zdCUyMGFwcCUyMCUzRCUyMHVzZUNvbnRleHQoU1RBVEUpJTVDbiUyMCUyMGNvbnN0JTIwJTdCaWQlN0QlMjAlM0QlMjBwcm9wcy5kYXRhJTNCJTVDbiUyMCUyMHJldHVybiUyMCUzQ2J1dHRvbiUyMGlkJTNEJTdCJTYwJTI0JTdCcHJvcHMuZGF0YS5pZCU3RCU2MCU3RCUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBzdGF0ZS5jb3VudCUyMCUzRCUyMHN0YXRlLmNvdW50JTIwJTJCJTIwMSUzQiU1Q24lMjAlMjAlMjAlMjBhcHAud2lkZ2V0cy5zb3J0KChhJTJDJTIwYiklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwY29uc29sZS5sb2coJ1Byb3AlMjBJRCclMkMlMjBpZCklNUNuJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoYS5pZCUyMCUzRCUzRCUzRCUyMGlkKSUyMCU3QnJldHVybiUyMDElN0QlNUNuJTIwJTIwJTIwJTIwJTIwJTIwaWYlMjAoYi5pZCUyMCUzRCUzRCUzRCUyMGlkKSUyMCU3QnJldHVybiUyMC0xJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMDAlNUNuJTIwJTIwJTIwJTIwJTdEKSU1Q24lMjAlMjAlMjAlMjAlN0QlN0QlM0UlNUNuJTIwJTIwJTIwJTIwSUQlM0ElMjAlN0Jwcm9wcy5kYXRhLmlkJTdEJTIwQ291bnQlM0ElMjAlN0JzdGF0ZS5jb3VudCU3RCU1Q24lMjAlMjAlM0MlMkZidXR0b24lM0UlNUNuJTdEKSU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzdGF0ZSUzQSUyMEFwcFN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCJTVDbiUyMCUyMCUyMCUyMHdpZGdldHMlM0ElMjAlNUIlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdCaWQlM0ElMjAwJTJDJTIwY291bnQlM0ElMjAwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3QmlkJTNBJTIwMSUyQyUyMGNvdW50JTNBJTIwMCU3RCU1Q24lMjAlMjAlMjAlMjAlNUQlNUNuJTIwJTIwJTdEKSU1Q24lMjAlMjB1c2VDb250ZXh0UHJvdmlkZXIoU1RBVEUlMkMlMjBzdGF0ZSklNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTNFJTVDbiUyMCUyMCUyMCU3QnN0YXRlLndpZGdldHMubWFwKGRhdGElMjAlM0QlM0UlMjAlM0NXaWRnZXQlMjBkYXRhJTNEJTdCbXV0YWJsZShkYXRhKSU3RCUyRiUzRSklN0QlNUNuJTIwJTIwJTNDJTJGZGl2JTNFJTNCJTVDbiU3RCklM0IlMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcGxheWdyb3VuZCUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJUb1N0cmluZ09wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwcmVuZGVyKG9wdHMlM0ElMjBSZW5kZXJUb1N0cmluZ09wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBBcHAlMjAlN0QlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D)

**Comment by nnelgxorz** [comment]
All this strangeness goes away when the Widget component is keyed.

Maybe not a bug and more an opportunity for better error messages or documentation?

**Comment by manucorporat** [comment]
Looking into the issue right now!

**Comment by nnelgxorz** [comment]
Thanks Manu!

**Comment by manucorporat** [comment]
Fixed https://github.com/BuilderIO/qwik/commit/91a566f15605928eaf242a0df591a63f7e8caf6b
