### ISSUE TITLE
Keyed Dom Nodes

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#602]
### Is your feature request related to a problem?

When rendering data into components that have internal state, nodes appear to be recycled so nodes do not track with data.

For example, in this playground example, the buttons are reordered randomly after every click. If you continuously click the top button, the count changes for the top bottom, regardless of what ID has been placed in that position

[Reproduction](https://qwik.builder.io/playground#version=0.0.25&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZhcHAudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGNvbXBvbmVudCUyNCUyQyUyMHVzZVN0b3JlJTJDJTIwY3JlYXRlQ29udGV4dCUyQyUyMHVzZUNvbnRleHRQcm92aWRlciUyQyUyMHVzZUNvbnRleHQlMkMlMjBtdXRhYmxlJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGludGVyZmFjZSUyMEFwcFN0YXRlJTIwJTdCJTVDbiUyMCUyMHdpZGdldHMlM0ElMjBXaWRnZXREYXRhJTVCJTVEJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBTVEFURSUyMCUzRCUyMGNyZWF0ZUNvbnRleHQlM0NBcHBTdGF0ZSUzRSgnR2xvYmFsU3RhdGUnKSU1Q24lNUNuaW50ZXJmYWNlJTIwV2lkZ2V0RGF0YSUyMCU3QiU1Q24lMjAlMjBpZCUzQSUyMG51bWJlciU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwV2lkZ2V0JTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSUyMCU3QmRhdGElM0ElMjBXaWRnZXREYXRhJTdEKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCY291bnQlM0ElMjAwJTdEKSU1Q24lMjAlMjBjb25zdCUyMGFwcCUyMCUzRCUyMHVzZUNvbnRleHQoU1RBVEUpJTVDbiUyMCUyMHJldHVybiUyMCUzQ2J1dHRvbiUyMGlkJTNEJTdCJTYwJTI0JTdCcHJvcHMuZGF0YS5pZCU3RCU2MCU3RCUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBzdGF0ZS5jb3VudCUyMCUzRCUyMHN0YXRlLmNvdW50JTIwJTJCJTIwMSUzQiU1Q24lMjAlMjAlMjAlMjBhcHAud2lkZ2V0cy5zb3J0KCgpJTIwJTNEJTNFJTIwMC41JTIwLSUyME1hdGgucmFuZG9tKCkpJTVDbiUyMCUyMCUyMCUyMCU3RCU3RCUzRSU1Q24lMjAlMjAlMjAlMjBJRCUzQSUyMCU3QnByb3BzLmRhdGEuaWQlN0QlMjBDb3VudCUzQSUyMCU3QnN0YXRlLmNvdW50JTdEJTVDbiUyMCUyMCUzQyUyRmJ1dHRvbiUzRSU1Q24lN0QpJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMEFwcCUyMCUzRCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTNBJTIwQXBwU3RhdGUlMjAlM0QlMjB1c2VTdG9yZSglN0IlNUNuJTIwJTIwJTIwJTIwd2lkZ2V0cyUzQSUyMCU1QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0JpZCUzQSUyMDAlMkMlMjBjb3VudCUzQSUyMDAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdCaWQlM0ElMjAxJTJDJTIwY291bnQlM0ElMjAwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3QmlkJTNBJTIwMiUyQyUyMGNvdW50JTNBJTIwMCU3RCU1Q24lMjAlMjAlMjAlMjAlNUQlNUNuJTIwJTIwJTdEKSU1Q24lMjAlMjB1c2VDb250ZXh0UHJvdmlkZXIoU1RBVEUlMkMlMjBzdGF0ZSklNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTNFJTVDbiUyMCUyMCUyMCU3QnN0YXRlLndpZGdldHMubWFwKGRhdGElMjAlM0QlM0UlMjAlM0NXaWRnZXQlMjBkYXRhJTNEJTdCbXV0YWJsZShkYXRhKSU3RCUyRiUzRSklN0QlNUNuJTIwJTIwJTNDJTJGZGl2JTNFJTNCJTVDbiU3RCklM0IlMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcGxheWdyb3VuZCUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJUb1N0cmluZ09wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwcmVuZGVyKG9wdHMlM0ElMjBSZW5kZXJUb1N0cmluZ09wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBBcHAlMjAlN0QlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D)

### Describe the solution you'd like

Many vdom libraries have keyed nodes, so that nodes can be tied to a specific piece of data with an id.

Perhaps Qwik already has this, but I wasn't able to find documentation.

### Describe alternatives you've considered

Using the example above, keep the count state inside of the WidgetData. However, because of the issue described in #600 it is not apparent how to actual make this work.

 [Example](https://qwik.builder.io/playground#version=0.0.25&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZhcHAudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGNvbXBvbmVudCUyNCUyQyUyMHVzZVN0b3JlJTJDJTIwY3JlYXRlQ29udGV4dCUyQyUyMHVzZUNvbnRleHRQcm92aWRlciUyQyUyMHVzZUNvbnRleHQlMkMlMjBtdXRhYmxlJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGludGVyZmFjZSUyMEFwcFN0YXRlJTIwJTdCJTVDbiUyMCUyMHdpZGdldHMlM0ElMjBXaWRnZXREYXRhJTVCJTVEJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBTVEFURSUyMCUzRCUyMGNyZWF0ZUNvbnRleHQlM0NBcHBTdGF0ZSUzRSgnR2xvYmFsU3RhdGUnKSU1Q24lNUNuaW50ZXJmYWNlJTIwV2lkZ2V0RGF0YSUyMCU3QiU1Q24lMjAlMjBpZCUzQSUyMG51bWJlciU1Q24lMjAlMjBjb3VudCUzQSUyMG51bWJlciU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwV2lkZ2V0JTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSUyMCU3QmRhdGElM0ElMjBXaWRnZXREYXRhJTdEKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMGFwcCUyMCUzRCUyMHVzZUNvbnRleHQoU1RBVEUpJTVDbiUyMCUyMHJldHVybiUyMCUzQ2J1dHRvbiUyMGlkJTNEJTdCJTYwJTI0JTdCcHJvcHMuZGF0YS5pZCU3RCU2MCU3RCUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZyhwcm9wcy5kYXRhLmNvdW50KSU1Q24lMjAlMjAlMjAlMjBwcm9wcy5kYXRhLmNvdW50JTIwJTNEJTIwcHJvcHMuZGF0YS5jb3VudCUyMCUyQiUyMDElNUNuJTIwJTIwJTIwJTIwYXBwLndpZGdldHMuc29ydCgoKSUyMCUzRCUzRSUyMDAuNSUyMC0lMjBNYXRoLnJhbmRvbSgpKSU1Q24lMjAlMjAlMjAlMjAlN0QlN0QlM0UlNUNuJTIwJTIwJTIwJTIwSUQlM0ElMjAlN0Jwcm9wcy5kYXRhLmlkJTdEJTIwQ291bnQlM0ElMjAlN0Jwcm9wcy5kYXRhLmNvdW50JTdEJTVDbiUyMCUyMCUzQyUyRmJ1dHRvbiUzRSU1Q24lN0QpJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMEFwcCUyMCUzRCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTNBJTIwQXBwU3RhdGUlMjAlM0QlMjB1c2VTdG9yZSglN0IlNUNuJTIwJTIwJTIwJTIwd2lkZ2V0cyUzQSUyMCU1QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0JpZCUzQSUyMDAlMkMlMjBjb3VudCUzQSUyMDAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTdCaWQlM0ElMjAxJTJDJTIwY291bnQlM0ElMjAwJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3QmlkJTNBJTIwMiUyQyUyMGNvdW50JTNBJTIwMCU3RCU1Q24lMjAlMjAlMjAlMjAlNUQlNUNuJTIwJTIwJTdEKSU1Q24lMjAlMjB1c2VDb250ZXh0UHJvdmlkZXIoU1RBVEUlMkMlMjBzdGF0ZSklNUNuJTIwJTIwcmV0dXJuJTIwJTNDZGl2JTNFJTVDbiUyMCUyMCUyMCU3QnN0YXRlLndpZGdldHMubWFwKGRhdGElMjAlM0QlM0UlMjAlM0NXaWRnZXQlMjBkYXRhJTNEJTdCbXV0YWJsZShkYXRhKSU3RCUyRiUzRSklN0QlNUNuJTIwJTIwJTNDJTJGZGl2JTNFJTNCJTVDbiU3RCklM0IlMjIlN0QlMkMlN0IlMjJwYXRoJTIyJTNBJTIyJTJGcGxheWdyb3VuZCUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJUb1N0cmluZ09wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwcmVuZGVyKG9wdHMlM0ElMjBSZW5kZXJUb1N0cmluZ09wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBBcHAlMjAlN0QlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D)

**Comment by nnelgxorz** [comment]
Closing as I found out this already exists as the key property.

**Comment by intellix** [comment]
I was also under the impression this was missing, due to it not being in the Qwik version of this example: https://qwik.builder.io/docs/cheat/qwik-react/#create-a-component-that-renders-a-list-of-the-presidents
