### ISSUE TITLE
Code split loading[🐞]

### ISSUE THREAD

**Issue by primozs** [BuilderIO/qwik#6028]
### Which component is affected?

Qwik Runtime

### Describe the bug

"@builder.io/qwik": "^1.5.1",
 "@builder.io/qwik-city": "^1.5.1",

Writing onClick$ handlers in some cases loads js before event actually happens.
I was expecting that code would load on actual click event.

`
 <button
        onClick$={() => {
          console.log('no javascript is loaded on page load only on click');
        }}
      >
        test1
      </button>

      <button
        onClick$={() => {
          isOpenSig.value = true;
        }}
      >
        javascript loaded on page load, instead of on click
      </button>

      {/* no javascript loaded on page load, mostly not possible workaround */}
      {isOpenSig.value && (
        <button
          onClick$={() => {
            isOpenSig.value = false;
          }}
        >
          close
        </button>

`
 using signals or functions from custom reusable hook in onClick handler, loads even more js, before onClick event actually happens 

sometimes hook can be rewritten in normal function then code is again not loaded before event actually happens.

Is this expected or its a bug? 

### Reproduction

https://stackblitz.com/edit/qwik-starter-suaufp?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

try different button examples one by one and check network tab

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 17.87 GB / 31.07 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.12.1 - ~/.local/share/pnpm/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 122.1.63.174
    Chrome: 122.0.6261.128
```

**Comment by wmertens** [comment]
Loading JS on click would cause noticable lag.

In dev mode, Qwik fetches JS on hover, and in production it fetches when the component is visible.

See the advanced docs for more information.

Closing as this is expected, but thanks for reporting concerns!

**Comment by primozs** [comment]
Thx for explanation but in production it is not just fetching when the component is visible but like I tried to describe.
If the code is not touching qwik it si loading on click.
Cheers
