### ISSUE TITLE
[🐞] ERR_TOO_MANY_REDIRECTS – Redirect loop on qwik.dev

### ISSUE THREAD

**Issue by mathiasschopmans** [BuilderIO/qwik#6032]
### Which component is affected?

Qwik Website

### Describe the bug

Visiting https://qwik.dev/ results in a redirect loop. :(

![screenshot](https://github.com/BuilderIO/qwik/assets/193253/4e2d9dba-0305-4b74-9bb1-715f59f0ff25)

https://qwik.builder.io/ is working fine.

### Reproduction

https://qwik.dev/

### Steps to reproduce

`curl -I https://qwik.dev/`

```
HTTP/2 308
date: Wed, 20 Mar 2024 13:55:11 GMT
location: https://qwik.dev/
```

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.51 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 123.0.6312.58
    Safari: 17.4
```

**Comment by mathiasschopmans** [comment]
// cc @wmertens

**Comment by gioboa** [comment]
#6034 solved this problem, @mathiasschopmans thanks for opening this issue :+1:
