### ISSUE TITLE
[🐞] Build static with custom origin protocol is broken

### ISSUE THREAD

**Issue by srapport** [BuilderIO/qwik#6069]
### Which component is affected?

Qwik City (routing)

### Describe the bug

[THIS LINE](https://github.com/BuilderIO/qwik/blob/e9ebce1e7071e703cbfa10c2e671ae681acf980a/packages/qwik-city/adapters/shared/vite/index.ts#L135) of code results in broken custom protocols in static builds.

Fixing this is required for our CapacitorJS integration to support the custom protocol on iOS `capacitor://`. Currently it prefixes `https://` and then includes the protocol within the path.

We should also figure out how to include a test case for this. 🤔

Cc: @wmertens

### Reproduction

https://github.com/BuilderIO/qwik/blob/e9ebce1e7071e703cbfa10c2e671ae681acf980a/packages/qwik-city/adapters/shared/vite/index.ts#L135

### Steps to reproduce

Build static with:

```ts
import { staticAdapter } from '@builder.io/qwik-city/adapters/static/vite';
import { extendConfig } from '@builder.io/qwik-city/vite';
import baseConfig from '../../vite.config';

export default extendConfig(baseConfig, () => {
    return {
        build: {
            ssr: true,
            rollupOptions: {
                input: ['@qwik-city-plan'],
            },
        },
        plugins: [
            staticAdapter({
                origin: 'capacitor://',
            }),
        ],
    }```;
});
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 250.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
    pnpm: 8.7.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 123.0.6312.87
    Safari: 16.4
  npmPackages:
    @builder.io/partytown: ^0.10.0 => 0.10.0
    @builder.io/qwik: workspace:^ => 1.5.1
    undici: * => 6.6.2
    vite: ^5.1.6 => 5.1.6
```

**Comment by n8sabes** [comment]
Thank you @wmertens,  but now ---

Please clone this repo:
[qwik-static-navigate](https://github.com/n8sabes/qwik-static-navigate)

This test fails the static build process: [HERE](https://github.com/BuilderIO/qwik/blob/fd2ccbd641c12afce90ec45696c9d598cd4a34d7/packages/qwik-city/static/main-thread.ts#L239)

**Comment by wmertens** [comment]
@PatrickJS can you fix that check as well? I'm traveling

**Comment by n8sabes** [comment]
@wmertens, @PatrickJS -- Thanks for the help w/ this.

In the test [repo](https://github.com/n8sabes/qwik-static-navigate), you'll see the input variations of `origin` and how they are transformed, all of which should build.

`localhost`
`http://`
`capacitor://`
`capacitor://localhost`
etc.

**Comment by n8sabes** [comment]
Below are instructions for a Hybrid Qwik Capacitor app _(Native Qwik App via Capacitor)_. The [sample repo](https://github.com/n8sabes/qwik-static-navigate) is a simple reproduction of the navigate to anchor issue. **_Note:** Geolocation used in the instructions below are not required for the sample repo._

# Capacitor Qwik


## Install Capacitor

After creating your Qwik app `npm create qwik@latest`, add Capacitor to your project and create a config for your app.

```shell
npm install --save-dev @capacitor/core @capacitor/cli 
npx cap init [name] [id] --web-dir=dist
```

## Build the Web App

The compiled web assets will be copied into each Capacitor native platform during the next step.

```shell
npm run qwik add static
npm run build
```

## Install the native platforms you want to target

Apple logoAndroid logo
Capacitor's native projects exist in their own top-level folders and should be considered part of your app (check them into source control).

```shell
npm i @capacitor/ios @capacitor/android
npx cap add android
npx cap add ios
```

## Adding calls to Native APIs

With Capacitor installed, adding calls to native device features is as straight forward as calling other JavaScript methods.

```ts
import { component$, useSignal } from "@builder.io/qwik";
import { Geolocation, type Position } from "@capacitor/geolocation";

export default component$(() => {
  const locSignal = useSignal<Position>();

  return (
    <div>
      <h1>Geolocation</h1>
      <p>Your location is:</p>
      <p>Latitude: {locSignal.value?.coords.latitude}</p>
      <p>Longitude: {locSignal.value?.coords.longitude}</p>
      <button
        onClick$={async () => {
          const coordinates = await Geolocation.getCurrentPosition();
          locSignal.value = coordinates;
        }}
      >
        Get Current Location
      </button>
    </div>
  );
});
```
***NOTE:** [Apple requires privacy descriptions to be specified in `Info.plist` for location information.](https://capacitorjs.com/docs/apis/geolocation#ios)*
