### ISSUE TITLE
[🐞] qwik.dev home page doesn't load the content

### ISSUE THREAD

**Issue by s-voloshynenko** [BuilderIO/qwik#6082]
### Which component is affected?

Qwik Runtime

### Describe the bug

1. Go to [qwik.dev](https://qwik.dev/)
2. Scroll down
3. Showcase/Qwik media, etc content are missing.
4. On mobile you can load those sections with a few clicks.

![qwik dev](https://github.com/BuilderIO/qwik/assets/10322046/5c52eaad-4348-4229-86cf-d0a657979367)

### Reproduction

https://qwik.dev/

### Steps to reproduce

Gif is attached to the bug description

### System Info

```shell
MacOs,Chrome Version 123.0.6312.87 (Official Build) (x86_64)
```

**Comment by wmertens** [comment]
Possibly due to #6073?

**Comment by s-voloshynenko** [comment]
Was fixed by https://github.com/BuilderIO/qwik/pull/6087
