### ISSUE TITLE
[🐞] the qwik CLI should not clear the console history

### ISSUE THREAD

**Issue by milahu** [BuilderIO/qwik#6102]
### Which component is affected?

Starters / CLI

### Describe the bug

clearing the console history can hide build errors

clearing the console history is rude
because it also deletes output from previous commands

https://github.com/BuilderIO/qwik/blob/7bc759c7ec00c197b9a546460eaad218ab6e43be/packages/qwik/src/cli/run.ts#L64-L66

vite has the option `npx vite --clearScreen false`
but i would simply remove the `console.clear`, i dont see any value in it

### Reproduction

no

### System Info

```shell
qwik version 7bc759c7ec00c197b9a546460eaad218ab6e43be
```

**Comment by wmertens** [comment]
Agreed. PR welcome
