### ISSUE TITLE
[BUG] [0.0.26] How is preventdefault:* supposed to behave?

### ISSUE THREAD

**Issue by mahmoudajawad** [BuilderIO/qwik#625]
As I'm looking into component-based routing (#543) that behaves as SPA (Component would be used as page content and it would replace portion of the current view) and MPA (Accessing the page through a route should also work), I found the following snippet in the served source:
```js
element.hasAttribute("preventdefault:" + eventName) && ev.preventDefault();
```

First, I couldn't find any reference to this in the docs. Second, using it on a link (anchor element) actually worked and made the link stale and doesn't navigate to the page in `href`. However, adding `preventdefault:click` to link seems to disable `onClick$` as well:
```jsx
<a href="/about" onClick$={() => {alert(123);}}> {/* clicking on linking causing page to navigate to /about, but shows alert as well */}
<a href="/about" preventdefault:click onClick$={() => {alert(123);}}> {/* clicking on linking doesn't do anything at all */}
```

So, is this the expected behaviour of `preventdefault:*`? And, if so, what is a situation where using it actually serves a purpose (documentation request), and if not, is this supposed to be changed into a bug issue?

**Comment by manucorporat** [comment]
seems like a bug! i will fix and update the docs to reflect this! thanks a lot for pointing this out.

because of how qwik works, user code might not be there when a click happens, to an API to preventDefault is necessary.

**Comment by mahmoudajawad** [comment]
Thanks, @manucorporat, I'll also try to give it sometime and maybe I can figure out something about it.

**Comment by manucorporat** [comment]
Added this new docs: https://qwik.builder.io/docs/components/events#prevent-default

and new end to end tests about this feature
