### ISSUE TITLE
[BUG] CSS styles from `global.css` not applied in any starter

### ISSUE THREAD

**Issue by wtho** [BuilderIO/qwik#626]
### Qwik Version

0.0.26

### Operating System (or Browser)

Linux 5.18.1, Chromium 102.0.5005.115

### Node Version (if applicable)

18.3.0

### Which component is affected?

Starters / CLI

### Expected Behaviour

The global styles should be applied, in both, DEV and SSR builds

### Actual Behaviour

The styles are never added to the websites. They only seem to be applied when loaded e. g. via `useStyles$`.

### Additional Information

A workaround seems to add the styles to a `component$` using `useStyles$`, which is also how it currently works in the `packages/docs` project:
```tsx
import styles from '../../global.css';

import { component$, useStyles$ } from '@builder.io/qwik'

export const App = component$(() => {
  useStyles$(styles)
  // [...]
})
```

Related (was closed although not solved, this issue is now the follow-up): https://github.com/BuilderIO/qwik/issues/583

**Comment by manucorporat** [comment]
This should be fixed in the last release!

**Comment by wtho** [comment]
@manucorporat it **still** does not work. Please reopen.

Reproduction:
1. `npm init qwik@latest`
2. *Project Name* -> `qwik-app`
3. *Select a Starter* -> `Starter`
4. *Select a Server* -> `Setup later`
5. *Features* -> `Prettier`
6. `cd qwik-app`
7. `npm install`
8. `npm start`
9. Add `html { background-color: red }` to `global.css`
10. Open `localhost:3000` - no red background visible, rule not applied
