### ISSUE TITLE
Suggestion: event naming should be similar to React

### ISSUE THREAD

**Issue by dzearing** [BuilderIO/qwik#634]
### Is your feature request related to a problem?

In the TODO example, `onKeyup$` is used on the Header's input. I was confused by the naming, because I've used `onKeyUp` (capital U) in React for many years. I understand the idea - converting all lowers like `keyup` to camelCasing needs to follow predictable logic. But I think it would help developers transition to Qwik to try and not invent new things which require new muscle memory to be formed unnecessarily.

### Describe the solution you'd like

onKeyUp => onKeyUp$
onKeyDown => onKeyDown$
onFocusIn => onFocusIn$

etc. Follow React naming here, avoid a new thing to teach.

### Describe alternatives you've considered

n/a

### Additional context

If the only thing we have to learn is when to use $ and Qrl, I think we'll be ok. :D

**Comment by manucorporat** [comment]
Agreed! i think its a matter of types, pretty sure both names will actually work, since we lowercase the whole name: could you find some other mismatches? https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/core/render/jsx/types/jsx-generated.ts

**Comment by kylecordes** [comment]
Related: focusin does't work right now. see #508

**Comment by manucorporat** [comment]
Fixed https://github.com/BuilderIO/qwik/commit/57cbe1f4e98a6a879eff2c7106085a61137bcac6
