### ISSUE TITLE
[DOCS] Standard error codes

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#651]
Qwik introduces new concepts that are strange for current developer, such as which kind of information can be serialized, and the ryles of the $ dollar scope.

Looking forward, we will have a well defined error code IDs for every part of the tooling, codes we can references and point to sections in our docs.

```
Optimizer: OXX
Runtime: RXX
ESLINT: EXX
Vite: VXX
Bundler plugin: BXX
CLI: CXX
```

This way when an error happens, we will be able to point developers to a section within the docs:
```
https://qwik.builder.io/docs/error/O23
```

## Every error is a markdown

Errors codes should be static, and never reused, if an error is deprecated, the code still applies and new errors get a new value from a monotonic counter.

This way we can keep a markdown for every error, where we can explain in detail with text, images, or other components that explain the issue, also developers can edit the error help

**Comment by zishiwu123** [comment]
@manucorporat Does the error code structure you envision for Qwik look similar to the one in [Highcharts](https://github.com/highcharts/highcharts/tree/master/errors)? They have one errors.json file listing each error code id and a text description. Then for each error code id, there is a folder containing a readme.md file containing a more detailed description and links to documentation.

**Comment by manucorporat** [comment]
YES! exactly like that is what I was imagining! @adamdbradley is finishing some big changes in QwikCity, which powers the routing in the docs site, once we have that, i think we will start with setting up the errors docs in the site.

Thanks for sharing the link!! We will get all their ideas!

Good thing, is that we will be able to use .mdx, meaning that we can even show interactive code, or the playground for common errors!

**Comment by manucorporat** [comment]
For the runtime errors, this is what we do: https://github.com/BuilderIO/qwik/blob/main/packages/qwik/src/core/error/error.ts#L33

So we can treeshake the error messages in prod mode (to keep build smaller).

**Comment by manucorporat** [comment]
Done!
