### ISSUE TITLE
Add a paragraph about createContext & useContext

### ISSUE THREAD

**Issue by yjaaidi** [BuilderIO/qwik#663]
`createContext` and `useContext` are not documented yet.

It would be nice to also add a paragraph mentioning how prop drilling can be a bottleneck and why using contexts should be preferred.
A document page with anti-patterns/gotchas could summarize this kind of issues.

**Comment by manucorporat** [comment]
Done! https://github.com/BuilderIO/qwik/pull/664

Planning to do another guide about data passing and merge it with reactivity, i think we can put some info about the tradeoffs there, also in component anatomy, when i talk about props, definively would be nice to go into a deeper explanation
