### ISSUE TITLE
[DOCS]

### ISSUE THREAD

**Issue by Vikingslord** [BuilderIO/qwik#665]
The sidebars are not sticking properly for the docs section for large screens. It's working fine for smaller screens.
![image](https://user-images.githubusercontent.com/65084644/175455668-9c1e7cd6-2593-46a2-b1fd-4a71f6b76eb4.png)

**Comment by mhevery** [comment]
Any chance you would be willing to take this on and fix it?

**Comment by nnelgxorz** [comment]
I'm unable to reproduce this on Chrome or Firefox. @Vikingslord, which browser are you using?

**Comment by nnelgxorz** [comment]
Also @Vikingslord, what resolution is your screen?

**Comment by Vikingslord** [comment]
> Any chance you would be willing to take this on and fix it?

Yes I'll try and fix it.

**Comment by Vikingslord** [comment]
> I'm unable to reproduce this on Chrome or Firefox. @Vikingslord, which browser are you using?

I'm using Microsoft Edge.

**Comment by Vikingslord** [comment]
> Also @Vikingslord, what resolution is your screen?

it's 1536 x 864

**Comment by shairez** [comment]
@Vikingslord thanks for the report!
curious - why did you close this issue? is it resolved on your side?

**Comment by Vikingslord** [comment]
> @Vikingslord thanks for the report! curious - why did you close this issue? is it resolved on your side?
Hi, yes for some apparent reason, it's working fine on edge now.

**Comment by shairez** [comment]
@Vikingslord Thanks for the update!
