### ISSUE TITLE
Merging bindings on Host Element is not working

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#668]
[ [Repro](http://localhost:3000/playground#version=0.0.30&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwSG9zdCUyQyUyMFFSTCUyQyUyMFNsb3QlMkMlMjB1c2VTdG9yZSUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWsnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMEFwcCUyMCUzRCUyMGNvbXBvbmVudCUyNCgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjBjb25zdCUyMHN0b3JlJTIwJTNEJTIwdXNlU3RvcmUoJTdCJTIwY291bnQlM0ElMjAwJTIwJTdEKSUzQiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ015QnV0dG9uJTIwb25DbGljayUyNCUzRCU3QigpJTIwJTNEJTNFJTIwc3RvcmUuY291bnQlMkIlMkIlN0QlMjBob3N0JTNBc3R5bGUlM0QlN0IlN0IlMjBiYWNrZ3JvdW5kQ29sb3IlM0ElMjAncmVkJyUyMCU3RCU3RCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlN0JzdG9yZS5jb3VudCU3RCU1Q24lMjAlMjAlMjAlMjAlM0MlMkZNeUJ1dHRvbiUzRSU1Q24lMjAlMjApJTNCJTVDbiU3RCklM0IlNUNuJTVDbmludGVyZmFjZSUyME15QnV0dG9uUHJvcHMlMjAlN0IlNUNuJTIwJTIwb25DbGlja1FybCUzRiUzQSUyMFFSTCUzQyhldmVudCUzQSUyMEV2ZW50KSUyMCUzRCUzRSUyMHZvaWQlM0UlM0IlNUNuJTdEJTVDbmV4cG9ydCUyMGNvbnN0JTIwTXlCdXR0b24lMjAlM0QlMjBjb21wb25lbnQlMjQoJTVDbiUyMCUyMChwcm9wcyUzQSUyME15QnV0dG9uUHJvcHMpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDSG9zdCUyMG9uQ2xpY2tRcmwlM0QlN0Jwcm9wcy5vbkNsaWNrUXJsJTdEJTIwc3R5bGUlM0QlN0IlN0IlMjBiYWNrZ3JvdW5kQ29sb3IlM0ElMjAnbGlnaHRwaW5rJyUyQyUyMHBhZGRpbmclM0ElMjAnMWVtJyUyMCU3RCU3RCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NTbG90JTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRkhvc3QlM0UlNUNuJTIwJTIwJTIwJTIwKSUzQiU1Q24lMjAlMjAlN0QlMkMlNUNuJTIwJTIwJTdCJTIwdGFnTmFtZSUzQSUyMCdidXR0b24nJTIwJTdEJTVDbiklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q25pbXBvcnQlMjAlN0IlMjBBcHAlMjAlN0QlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRVR1dG9yaWFsJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTJDJTIyaGlkZGVuJTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMiU1Q25pbXBvcnQlMjAlN0IlMjByZW5kZXJUb1N0cmluZyUyQyUyMFJlbmRlck9wdGlvbnMlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJTJGc2VydmVyJyUzQiU1Q25pbXBvcnQlMjAlN0IlMjBSb290JTIwJTdEJTIwZnJvbSUyMCcuJTJGcm9vdCclM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwcmVuZGVyKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiUyQyUyMmhpZGRlbiUyMiUzQXRydWUlN0QlNUQ%3D) ]

When both the parent and child bind to host element the chlid wins. This is not correct as parent should have higher prioriy.

```typescript
import { component$, Host, QRL, Slot, useStore } from '@builder.io/qwik';

export const App = component$(() => {
  const store = useStore({ count: 0 });
  return (
    <MyButton onClick$={() => store.count++} host:style={{ backgroundColor: 'red' }}>
      {store.count}
    </MyButton>
  );
});

interface MyButtonProps {
  onClickQrl?: QRL<(event: Event) => void>;
}
export const MyButton = component$(
  (props: MyButtonProps) => {
    return (
      <Host onClickQrl={props.onClickQrl} style={{ backgroundColor: 'lightpink', padding: '1em' }}>
        <Slot />
      </Host>
    );
  },
  { tagName: 'button' }
);

```

In the above example, the final `background-color` should be `red` and it should have `padding` of `1em`

**Comment by manucorporat** [comment]
Duplicated of https://github.com/BuilderIO/qwik/issues/263
