### ISSUE TITLE
ROADMAP: $state immutable

### ISSUE THREAD

**Issue by tomByrer** [BuilderIO/qwik#7]
[reference](https://github.com/BuilderIO/qwik/blob/main/ROADMAP.md#state-management)
For some reason I thought there wasn't a global state, but saved in the DOM?  Or is this the state cached in memory while said DOM is processed?

Is this state directly accessible by user code, or only via Quik?
Either way, I lean towards which ever is fastest.  Could try non-immutable for v1, then visit the question again for v2; seems getting rid of immutable would be harder for programmers than adding later.

---

BTW, I thought of using [flatstr](https://github.com/davidmarkclements/flatstr) to before saving/sending state in microservices.  Performance gains from using flatstr:
```
ManySmallConcats: 28%
SeveralLargeConcats: 21% 
ExponentialSmallConcats: 46%
ExponentialLargeConcats: 33%
```
> best place to use flatstr is just prior to passing it to an API that eventually runs non-v8 code (such as fs.WriteStream, or perhaps xhr or DOM apis in the browser).

**Comment by mhevery** [comment]
Hi @tomByrer ,

Thanks for your question.

1. The roadmap doc, is more of a mental dump for me than anything else. We are trying hard to make sure there is no state. `$state` is an instance variable that allows us to separate transient vs persistent state for entities. 
2. Currently you can think of the current API as the low-level API and we may choose to put something on top of it to make it more friendly, but it would not be to replace the low-level things only to augment it.

PS: If this answers your question, can we close this issue?

**Comment by tomByrer** [comment]
cheers
