### ISSUE TITLE
Trivial constants sometimes misdetected as mutable

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/qwik#703]
### Qwik Version

0.0.33

### Operating System (or Browser)

OSX

### Node Version (if applicable)

16

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Mutable error emitted only on data that changes

### Actual Behaviour

In a component source file, define a global constant.

```
export const foo = [];
```

In the component, bind that to something

```
blah={foo}
```

No other code refers to this constant, and the child component does not use the prop at all.

In some cases (maybe only "production" builds?), an error nonetheless occurs, stating that mutable() should have been used.

It displays a before and after value, visually identical.

### Additional Information

I will hopefully **isolate this with a minimum repro in the future**; but I entered it now in case someone spots this and knows what is wrong.

**Comment by manucorporat** [comment]
maybe, instead of a repo, you could try reproduce in the playground!
https://qwik.builder.io/playground

Not sure how this bug could be happening…

**Comment by kylecordes** [comment]
This might turn out to be array-specific, maybe arrays are always detected as a mutation even with neither the identity or state of the array changes.

**Comment by nnelgxorz** [comment]
@manucorporat This appears to work on latest now that mutable has been deprecated.

**Comment by zanettin** [comment]
@shairez @manucorporat @adamdbradley 🔝sry for pinging you again 👼  what @nnelgxorz said: on latest version `mutation` is deprecated therefor this issue won't exist any longer.

**Comment by shairez** [comment]
Thanks @zanettin for the triaging!

Closing this for now, feel free to re-open if it's still relevant
