### ISSUE TITLE
[Bug] Dev server crashes when adding a folder

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#717]
### Qwik Version

QwikCity Dev Release

### Operating System (or Browser)

Debian Linux

### Node Version (if applicable)

16

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

When running the dev server, I should be able to create an empty folder in the routes directory

### Actual Behaviour

When a new folder is added the dev server crashes.

**Comment by mhevery** [comment]
Can you please provide reproduction steps? It is hard to fix without knowing exact sequence of things that needs to be done.

**Comment by nnelgxorz** [comment]
No problem.

- Create a Qwik CIty starter and open in an IDE. (I'm using vscode)
- Start the dev server with `npm run dev` or `npm run dev.ssr`
- While the server is running go into `src/routes` and a new folder.
- The dev server should crash with an error like `TypeError: Cannot read property 'on' of undefined`

**Comment by nnelgxorz** [comment]
I'm guessing there just needs a be a check added in the Qwik City plugin to differentiate between a newly added file and a newly added folder.

**Comment by nnelgxorz** [comment]
@mhevery Is the provided information enough to reproduce the issue?

**Comment by nnelgxorz** [comment]
Fixed in Qwik City 0.0.29. Thanks @adamdbradley!
