### ISSUE TITLE
[Bug] 404.(md,mdx,tsx,jsx) route breaks rendering

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#722]
### Qwik Version

Qwik CIty Dev Release

### Operating System (or Browser)

Debian Linux

### Node Version (if applicable)

v16.3.0

### Which component is affected?

Qwik City

### Expected Behaviour

I should be able to add a 404 route to my routes folder. This is a common use case supported by a lot of hosts.

### Actual Behaviour

An error is logged to the browser and pages no longer render. Dev server continues to run.

### Additional Information

Looks like this is caused by a bad import. The following error code is logged in the browser.

`Uncaught SyntaxError: underscore can appear only between digits, not after the last digit in a number @qwik-city-plan:7:17`

Inspecting the file at `http://localhost:3000/@qwik-city-plan` shows the bad import on line 7

`import * as 404_ from "/src/routes/404.md?import";`

Not sure if Vite or Qwik City is appending that underscore.

**Comment by mhevery** [comment]
This is already implemented in the new Qwik City branch. Should be fixed when that branch lands.

**Comment by nnelgxorz** [comment]
Fixed in latest.
