### ISSUE TITLE
Unable to use (build/serve) Qwik app that uses Qwik lib

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/qwik#742]
### Qwik Version

0.0.34

### Operating System (or Browser)

OSX

### Node Version (if applicable)

16

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

Create a trivial lib using the starter.

Create a trivial app using the starter.

`npm i` the lib to the app.

App should work both in `dev` and `build` + `serve`.

### Actual Behaviour

`npm run dev` in the app works!

But... `npm run build` doesn't. I've seen various failure modes, the one in this repro is:

```
Identifier directly after number
file: /Users/kcordes/projects/Qwik/qwik-lib-repro/example-app/src/entry_Counter.js:2:10
1: export { KeQObwj8Uik } from "./keqobwj8uik.js";
2: export { 3L0LnWO3YPk } from "./3l0lnwo3ypk.js";
             ^
error during build:
Error: Identifier directly after number
    at error (/Users/kcordes/projects/Qwik/qwik-lib-repro/example-app/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/Users/kcordes/projects/Qwik/qwik-lib-repro/example-app/node_modules/rollup/dist/shared/rollup.js:12555:16)
```

### Additional Information

Repro:

https://github.com/kylecordes/qwik-lib-repro

**Comment by kylecordes** [comment]
Related hint, but harder to reproduce: in a more complex scenario that also fails, I get an error message "Computing file stem for" with no filename listed. That error came from inside the Rust code, while the error in this repro seems to come from a file naming problem in the JavaScript output.

**Comment by manucorporat** [comment]
looking into it with highest priority, i think i know what is going on!

**Comment by manucorporat** [comment]
https://github.com/BuilderIO/qwik/pull/743

**Comment by manucorporat** [comment]
Fixed!

**Comment by kylecordes** [comment]
@manucorporat it appears the publish of this commit failed:

https://github.com/BuilderIO/qwik/actions/runs/2642623742

... I'll look for another way to update the repro and verify.

**Comment by kylecordes** [comment]
With `link` I was able to get past the above error, to a different one:

```
src/components/app/app.tsx:8:5 - error TS2307: Cannot find module '@builder.io/qwik/jsx-runtime' or its corresponding type declarations.
```

... but I think might be an artifact of `link`, so I'll wait for a published `qwik` with the fix above, then retest and report any new error in a new issue.

**Comment by kylecordes** [comment]
That was an adventure. Upon running the right build target to locally recompile the Rust code where the fix occurred, and then linking the right dist directory…

I can confirm this issue is fixed.
