### ISSUE TITLE
Qwik City Middleware

### ISSUE THREAD

**Issue by adamdbradley** [BuilderIO/qwik#780]
### Is your feature request related to a problem?

Currently only the last "page" module/component can handle a request and response, like `onGet`. @manucorporat had a good idea on how to add middleware to each of the parent layouts and even top level root, so things like authentication could easily be added to routes.

### Describe the solution you'd like

Each layout can handle a request and modify a child response.

### Describe alternatives you've considered

🤸‍♂️

**Comment by adamdbradley** [comment]
Shipped in https://github.com/BuilderIO/qwik/pull/960

**Comment by locriacyber** [comment]
How to use this?
