### ISSUE TITLE
Simplify `EndpointHandler` by adding the ability to just return the body

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#805]
### Is your feature request related to a problem?

I'd like to save the characters of having to retype the `status` and `headers`

 

### Describe the solution you'd like

I think returning just the `body` object as an additional return type option could help, while adding good defaults for headers or status.

Thought about creating PR by changing [this line](https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/runtime/src/library/types.ts#L216) and then changin the implementation of `getEndpointResponse` accordingly

But would love to hear your thoughts first

### Describe alternatives you've considered

Maybe a wrapper for the default return... but hmm... that's another step in the way

**Comment by leibale** [comment]
Closed in #824

**Comment by shairez** [comment]
Thanks @leibale
