### ISSUE TITLE
useResource$ throws error if executed by track-Function

### ISSUE THREAD

**Issue by GregOnNet** [BuilderIO/qwik#806]
### Qwik Version

0.0.37

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

18

### Which component is affected?

Qwik Runtime

### Expected Behaviour

When using `useResource$` with `track`, the code the resource-Function is successfully executed (e.g. reloading data from an API).

### Actual Behaviour

An error is thrown:

```
"Code(22): Components using useServerMount() can only be mounted in the server, if you need your component to be mounted in the client, use "useMount$()" instead"
```

![image](https://user-images.githubusercontent.com/444278/179778609-8f12ca6a-946c-44e6-a1bf-2bb6c84dcf9e.png)

## Reproduction

```
git clone https://github.com/GregOnNet/kanban-board
cd kanban-board

# make sure that Node 18 is installed

npm install

# Console 1
npm run app:start

# Console 2
npm run api:start

# Visit browser at localhost:3000
# Open DevTools
# Click on Button "Reload"
# Sometimes Click on Button "Reload" a 2nd time
#    Error should be thrown by the server
```

**Comment by manucorporat** [comment]
Seems like this issues in related with the usage of useServerMount(), not useResource(), am i missing something?

**Comment by GregOnNet** [comment]
@manucorporat Thanks for the hint.

I accidentally was using `useServerMount$` in my `kanban-board-list`.

**Learning** Mix and Match `useResource$` and `useServerMount$` leads into an error.

Closing this issue.
