### ISSUE TITLE
Fetch polyfill not loading

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#808]
### Qwik Version

v0.0.37

### Operating System (or Browser)

Debian Linux

### Which component is affected?

Qwik City

### Expected Behaviour

I should be able to use fetch in an onGet endpoint.

### Actual Behaviour

An error `fetch is not a function`

### Additional Information

To reproduce:

Start a new Qwik City starter
Add an onGet handler to a route
Call fetch from inside the handler

**Comment by manucorporat** [comment]
is node-fetch in your deps?

**Comment by manucorporat** [comment]
Does it happen in dev.ssr? build + serve? which server?

**Comment by nnelgxorz** [comment]
Dev.ssr. I haven't tried build and server.

`"node-fetch": "2.6.7"` is in my package json.

**Comment by nnelgxorz** [comment]
Oh, weird. I was able to call fetch without importing and wouldn't get an error in VSCode. If I actually import fetch from node-fetch then everything works.

Confusing, but I think this works for now. :+1:

**Comment by nnelgxorz** [comment]
Closed prematurely. The fetch polyfill is not loading in dev.ssr or with build + server.

**Comment by manucorporat** [comment]
could you try to reproduce this in a freshing creating starter? we changed a couple of things regarding ESM and updated node-fetch to 3, looking at the code, i cant see how fetch might be undefined.

If you confirm this still happens, i will look deep  into it

**Comment by nnelgxorz** [comment]
I can confirm it's still happening. Here is a minimal repro: https://github.com/nnelgxorz/missing-fetch-polyfill

Created using `npm init qwik@latest`

Thanks for your help!
