### ISSUE TITLE
Expected TreeShaking but whole library is downlaoded 

### ISSUE THREAD

**Issue by GregOnNet** [BuilderIO/qwik#813]
### Qwik Version

0.0.37

### Operating System (or Browser)

Mac Chrome

### Node Version (if applicable)

18

### Which component is affected?

Qwik Runtime

### Expected Behaviour

When I write `import { randUuid } from @ngneat/falso;` & resume my App, I expect that only the JS-Code of `randUuid` is downloaded in order to perform the operation.

### Actual Behaviour

When I write `import { randUuid } from @ngneat/falso;` & resume my App, the whole Library is loaded from the server.

https://user-images.githubusercontent.com/444278/180059756-6f8ec156-d193-4955-aa43-ec0f057c7181.mp4

### Additional Information

Reproduction

```
git clone https://github.com/GregOnNet/kanban-board
cd kanban-board

# make sure that Node 18 is installed

npm install

# Console 1
npm run app:start

# Console 2
npm run api:start

# Visit browser at localhost:3000
# Open DevTools
# Click on Button "Reload"
# Check the Network Tab for ngneat/falso
```

**Comment by mhevery** [comment]
You are running in dev mode without any bundling. You need to create a full build so that rollup can run and do its magic. Usually that is done through `yarn build` see: https://github.com/BuilderIO/qwik/blob/main/starters/apps/base/package.json#L6

**Comment by GregOnNet** [comment]
Ahh, thank you for clarification.
Somehow, I thought the `dev.srr`-command would run a build.
