### ISSUE TITLE
[DOCS] ability to filter content with a search bar

### ISSUE THREAD

**Issue by gioboa** [BuilderIO/qwik#822]
**How can the documentation be improved?**
having the ability to filter content with a search bar is definitely a cool improvement
Here an example 
<img width="991" alt="Screenshot 2022-07-21 at 11 39 18" src="https://user-images.githubusercontent.com/35845425/180184136-13a230d4-f586-4822-9433-357e8c4da37f.png">

**Comment by manucorporat** [comment]
yes! so we already have a Open source account approved by Argolia, we are waiting to update qwikcity docs to the latest qwikcity before making changes to it.

Definively, planning to add search!
