### ISSUE TITLE
Query part is missing from `useLocation().href`

### ISSUE THREAD

**Issue by leibale** [BuilderIO/qwik#826]
### Qwik Version

0.0.38

### Operating System (or Browser)

any

### Which component is affected?

Qwik City

### Expected Behaviour

When navigating to '/test?a=a' `useLocation().href` should be `'/test?a=a'`

### Actual Behaviour

the value is `'/test'` (without the querystring part)

**Comment by mhevery** [comment]
That was removed intentionally. @manucorporat

**Comment by manucorporat** [comment]
not totally intentionally,the query params should still be in the href

**Comment by manucorporat** [comment]
Should be fixed now!
