### ISSUE TITLE
[vite] Internal server error: Failed to load PostCSS config

### ISSUE THREAD

**Issue by lanzoninicola** [BuilderIO/qwik#836]
### Qwik Version

 "@builder.io/qwik": "0.0.38", "@builder.io/qwik-city": "0.0.23"

### Operating System (or Browser)

Win10

### Node Version (if applicable)

 16.13.1 (Currently using 64-bit executable)

### Which component is affected?

Starters / CLI

### Expected Behaviour

Opening the initial page in the browser

### Actual Behaviour

Steps to reproduce from the terminal:

1. npm init qwik@latest
2. Select a name to the project
3. Select starter: Qwik city
4. Select server: Cloudflare Pages
5. Select features: Prettier, Tailwindcss

6. Move to the project folder
7. Run npm install
8. Run npm start

### Additional Information

Full error output: [qwik_terminal_output.txt](https://github.com/BuilderIO/qwik/files/9172842/qwik_terminal_output.txt)

**Comment by lanzoninicola** [comment]
I don't know, but it seems related to https://github.com/vitejs/vite/issues/5316

**Comment by dacki** [comment]
I ran into the same issue on linux. Following the error message I could at least rename the files to `postcss.config.cjs` and `tailwind.config.cjs` as a workaround.

**Comment by nnelgxorz** [comment]
Qwik City is using Vite 3 now, which went all in on ESM. CommonJS files need to be explicitly named as .cjs, like @dacki said. :+1:

**Comment by chmich** [comment]
had the same error. i removed the `postcss.config.js` and it works.
Vite 3.1.3

**Comment by YohannesTz** [comment]
> 

Thanks! also worked for me too!

**Comment by AGirlHasNoName100** [comment]
mee too @chmich

**Comment by dev-seahouse** [comment]
> 

do you mean renaming from postcss.config.ts to postcss.config.js? it works for me.

**Comment by PhytonNet** [comment]
I solved this issue by deleting the node_modules directory, and ran `npm i` again.

**Comment by xuyaofang** [comment]
mee too @chmich 
Vite 3.2.0

**Comment by claudioares** [comment]
Tive esse erro usando o linux ubuntu. Eu removi trocando a extensão .js do arquivo (postcss.config.js) para extensão .cjs ( postcss.config.cjs).

**Comment by Aprotix** [comment]
> I solved this issue by deleting the node_modules directory, and ran `npm i` again.

This worked instantly

**Comment by georginklv** [comment]
I have the same problem with vuetify 3, none of this above works for me. Any ideas ?

**Comment by Jays0x** [comment]
I had the same issue but when I removed postCSS.config file it worked!

**Comment by vinayakkuradia** [comment]
For those who are trying to make **Tailwind** work with **Vite**, follow below steps:
- Rename `postcss.config.js` to `postcss.config.cjs` (keep `tailwind.config.js` as it is)
- Change the content of `postcss.config.cjs` as follows:
`
module.exports = ({ env }) => ({
  plugins: [
     require('tailwindcss')(), require('autoprefixer')()
  ]
})
`

The above is array format for plugins.
Ref: [Vite Postcss Config](postcss-load-config) [Postcss Load Config](https://github.com/postcss/postcss-load-config/blob/main/README.md#array)

**Comment by evn-seyednov** [comment]
In my case deleted `type: mode` from `package.json` resolved the issue

**Comment by phukao** [comment]
Add
"type": "module"
to package.json

**Comment by chmich** [comment]
What @phukao said also solved another problem for me. Only way to get svelte to run on vite.

**Comment by sathishg1990** [comment]
``dfdf

**Comment by pedroferreira37** [comment]
@chmich, I'm using Svelte on WSL2. I was getting the same error, but I just run npm install -D tailwindcss postcss autoprefixer and it worked.

**Comment by Ishan-Sandaruwan** [comment]
> had the same error. i removed the `postcss.config.js` and it works. Vite 3.1.3

its worked

**Comment by jaceksl1** [comment]
> had the same error. i removed the `postcss.config.js` and it works. Vite 3.1.3

the best solution

**Comment by nireve** [comment]
Resolved this by upgrading to postcss@8.4.28 and tailwind@3.3.3 (on vite@3.1.3).

**Comment by DavilmanXD** [comment]
> I ran into the same issue on linux. Following the error message I could at least rename the files to `postcss.config.cjs` and `tailwind.config.cjs` as a workaround.

Thaaaaaaaaaaaaaaaaaaaaks

**Comment by nasrulhazim** [comment]
> * module.exports = ({ env }) => ({ plugins: [ require('tailwindcss')(), require('autoprefixer')() ] })

nice. it works. thank you so much.

**Comment by eugene-makarov** [comment]
Replacing `module.exports` with `export default` worked for me

```
// postcss.config.js

export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  }
}
```

**Comment by akberqureshi361** [comment]
> I solved this issue by deleting the node_modules directory, and ran `npm i` again.

the best solutions thank you

**Comment by prathu9** [comment]
> Replacing `module.exports` with `export default` worked for me
> 
> ```
> // postcss.config.js
> 
> export default {
>   plugins: {
>     tailwindcss: {},
>     autoprefixer: {},
>   }
> }
> ```

This is bext solution.

**Comment by adamaslan** [comment]
not working for me
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.1",
    "vite": "^5.2.0"

**Comment by wmertens** [comment]
@adamaslan looks like there's a ( on line 4 in your index.css file that it doesn't expect.

**Comment by johnston75** [comment]
VITE v4.5.3. I rename postcss.config.js and this works for me. thanks....

Anyway, there is still no fixed solution to this problem, the solutions still vary. I don't know the root cause.

**Comment by KING9045** [comment]
> For those who are trying to make **Tailwind** work with **Vite**, follow below steps:
> 
>     * Rename `postcss.config.js` to `postcss.config.cjs` (keep `tailwind.config.js` as it is)
> 
>     * Change the content of `postcss.config.cjs` as follows:
>       `module.exports = ({ env }) => ({ plugins: [ require('tailwindcss')(), require('autoprefixer')() ] })`
> 
> 
> The above is array format for plugins. Ref: [Vite Postcss Config](postcss-load-config) [Postcss Load Config](https://github.com/postcss/postcss-load-config/blob/main/README.md#array)

I had same issue and it worked for me using the above reference

**Comment by VybzTech** [comment]
> I ran into the same issue on linux. Following the error message I could at least rename the files to `postcss.config.cjs` and `tailwind.config.cjs` as a workaround.

This helped me too 19/04/24

**Comment by willzfrank** [comment]
Here's the reworded response:

---

Here are the steps that worked for me:

1. I converted `postcss.config.js` to `postcss.config.cjs`.
2. I updated my `tailwind.config.js` file as follows:

```
/** @type {import('tailwindcss').Config}*/
export const content = ['./src/**/*.{js,jsx,ts,tsx}']
export const theme = {
  extend: {},
}
export const plugins = []
```

3. Finally, I ran `npm run dev`.

**Comment by omerwaqaskhan** [comment]
```
"postcss": "^8.4.38",
"postcss-import": "^16.1.0",
"tailwindcss": "^3.4.3",
"vite": "^5.2.10"
```

Only deleting the file `postcss.config.js` works.
Nothing else works

**Comment by andreakouakou09** [comment]
with VITE 4.5.3 Rename `postcss.config.js` to `postcss.config.mjs

**Comment by Michaecyber** [comment]
removed the postcss.config.js and it will works.

**Comment by Mohamed-Sayed-Ismail** [comment]
remove autoprefixer: {} 22-06-2024

**Comment by insomniagung** [comment]
> For those who are trying to make **Tailwind** work with **Vite**, follow below steps:
> 
> * Rename `postcss.config.js` to `postcss.config.cjs` (keep `tailwind.config.js` as it is)
> * Change the content of `postcss.config.cjs` as follows:
>   `module.exports = ({ env }) => ({ plugins: [ require('tailwindcss')(), require('autoprefixer')() ] })`
> 
> The above is array format for plugins. Ref: [Vite Postcss Config](postcss-load-config) [Postcss Load Config](https://github.com/postcss/postcss-load-config/blob/main/README.md#array)

thanks it works for me.

**Comment by bsayat** [comment]
hi everyone.

I changed this code

`module.exports = {
  plugins: {
    'postcss-import': {},
    tailwindcss: {},
    autoprefixer: {},
  }
}
`
to this
`export default {
  plugins: {
    'postcss-import': {},
    tailwindcss: {},
    autoprefixer: {},
  }
}
`
and it helped

**Comment by arturfurtado** [comment]
Tryed to change module.exports = { plugins: { 'postcss-import': {}, tailwindcss: {}, autoprefixer: {}, } }  to export default { plugins: { 'postcss-import': {}, tailwindcss: {}, autoprefixer: {}, } } and didnt worked, somehow deleting postcss.config.js and running "npm run dev" worked fine.

**Comment by sandroweb** [comment]
> I ran into the same issue on linux. Following the error message I could at least rename the files to `postcss.config.cjs` (or `postcss.config.mjs`) and `tailwind.config.cjs` (or `tailwind.config.mjs`) as a workaround.

Thank you a lot! Good hint!!!

**Comment by AgabaM** [comment]
I face this error when Ever I npm run dev newly installed vite react app what can I do [plugin:vite:css] [postcss] It looks like you're trying to use `tailwindcss` directly as a PostCSS plugin. The PostCSS plugin has moved to a separate package, so to continue using Tailwind CSS with PostCSS you'll need to install `@tailwindcss/postcss` and update your PostCSS configuration.

**Comment by wmertens** [comment]
@AgabaM see the tailwind upgrading instructions for going from v3 to v4

**Comment by AlexONeillTI** [comment]
It looks like they may have updated the docs for this - https://tailwindcss.com/docs/installation/using-vite. Following these instructions I was able to resolve the error.

**Comment by AnasSiddiqui18** [comment]
I had the same issue, so i solved it after installing auto-prefixer plugin.
