### ISSUE TITLE
[DOCS] Footer text hard to read.

### ISSUE THREAD

**Issue by kaleem68** [BuilderIO/qwik#837]
### Problem
As shown in the screenshot inside the rectangle, the "Get Started" text is tough to read.

<img width="1315" alt="Screenshot 2022-07-24 at 6 32 21 AM" src="https://user-images.githubusercontent.com/13909729/180628573-84d23d5b-9cef-4ffe-8374-351a7aab8a9b.png">

### Suggestions
Change the color of the text "Get Started" in the footer area to something easily visible.

### Article Source
https://www.builder.io/blog/our-current-frameworks-are-on-we-need-o1

### Browser
Google Chrome 
Version 103.0.5060.134 (Official Build) (arm64)
### OS
macOS Monterey
Version 12.3.1

**Comment by felixsanz** [comment]
the rectangle should be an orange button, but anyway doesn't pass contrast test

**Comment by kaleem68** [comment]
I have drawn the rectangle to highlight the point the text inside the Rectangle "Get Started" is not visible and the text color of "Get Started" should change to something visible to eye, hope this clears up any confusion.

**Comment by felixsanz** [comment]
I meant that i see it like this, with an orange rectangle

![1659727570](https://user-images.githubusercontent.com/6182099/183147267-30c87309-f118-4faf-a543-5f98cebe72c7.png)

**Comment by kaleem68** [comment]
@felixsanz Thanks for pointing out that I see "orange rectangle" has been added. This sort of fixes this issue. @mhevery, are you satisfied with the orange box changes, and does it pass the contrast test that @felixsanz has pointed out? If so, we can close this issue.

**Comment by adamdbradley** [comment]
Thanks for reporting the issue, should be fixed now.
