### ISSUE TITLE
Deploy Tests

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#857]
### Is your feature request related to a problem?

Qwik is very fast moving project. It's hard to make sure everything stays in sync and works for users.

### Describe the solution you'd like

A test suite that generates a new starter and deploys it to the various hosting providers that Qwik supports; Netlify and Cloudflare to start, with the ability to add more as middlewares/starter servers are added.

To start, just being able to manually check in on all the hosted sites and verify they are up and running is a huge leap forward.

Automated testing could be added later.

### Describe alternatives you've considered

Not have tests? 🤷 

### Additional context

The Docs site sort of serves the purpose, but ideally we have something that is synced to the current state of the starter CLI.

**Comment by manucorporat** [comment]
We got them now 
https://github.com/builderIO/qwik-city-e2e
