### ISSUE TITLE
Qwikloader does not work with runtimeQRLs

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#860]
I have created a repro here: https://stackblitz.com/edit/js-z6rmar?file=index.js,index.html

- The page renders!
- But no events work! The reason is that because it is client-side rendering the system needs to generate `/runtimeQRL`s. But it seems like our `qwikloader` no longer has code to process these. Not sure what happened there. 

1. So you should be able to render the application
2. until `qwikloader` is fixed to support `runtimeQRL` things will not interact.

**Comment by lifeiscontent** [comment]
@mhevery fwi, I updated the repro without the React.createElement hacks, just needed to set `    "jsxImportSource": "@builder.io/qwik"
` in tsconfig.json
