### ISSUE TITLE
[Bug] RTL Support From Html Tag

### ISSUE THREAD

**Issue by timsar2** [BuilderIO/qwik#863]
### Qwik Version

v0.0.34

### Operating System (or Browser)

windows chrome

### Node Version (if applicable)

18.6.0

### Which component is affected?

Qwik City

### Expected Behaviour

From root.tsx: By setting Right To Left inside of the Html tag, The page's direction must be RTL

```
export default () => {
  return (
    <Html lang="ar" dir="rtl">
      <Head />
      <Body />
    </Html>
  );
};
```

### Actual Behaviour

But the page's direction is still in LTR mode

### Additional Information

If I put direction in global.css it's working
```
:root{
    direction: rtl;
}
```
_No response_

**Comment by nnelgxorz** [comment]
@timsar2 I think I found the issue. I'll try to get a PR for you today. 👍

**Comment by shairez** [comment]
Thanks @nnelgxorz !
