### ISSUE TITLE
Qwik City Cloudflare starter does not build

### ISSUE THREAD

**Issue by michaelbromley** [BuilderIO/qwik#868]
### Qwik Version

0.0.39

### Operating System (or Browser)

Win11

### Node Version (if applicable)

18.6.0

### Which component is affected?

Starters / CLI

### Expected Behaviour

* `npm init qwik@latest` - select Qwik City with Cloudflare deployment
* `npm install`
* `npm run build`

Expected: build without errors

### Actual Behaviour

Partial output:

```
src/entry.cloudflare.tsx:6:25 - error TS2304: Cannot find name 'PagesFunction'.

6 export const onRequest: PagesFunction = async ({ request, next, waitUntil }) => {
                          ~~~~~~~~~~~~~
```

```
src/entry.cloudflare.tsx:28:33 - error TS2345: Argument of type '{ url: any; }' is not assignable to parameter of type 'RenderToStreamOptions'.
  Property 'stream' is missing in type '{ url: any; }' but required in type 'RenderToStreamOptions'.

28     const result = await render({
                                   ~
29       url: request.url,
   ~~~~~~~~~~~~~~~~~~~~~~~
30     });
   ~~~~~`
```

```
src/routes/api/[org]/[user].json/index.ts:2:16 - error TS2307: Cannot find module 'os' or its corresponding type declarations.     

2 import os from 'os';
                 ~~~~

src/routes/api/[org]/[user].json/index.ts:12:11 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.

12     node: process.versions.node,
             ~~~~~~~
```

### Additional Information

Several of the TypeScript compiler errors can be handled with config:

* In the default `tsconfig.json`, there is `types: ["vite/client"]`. This causes TS to ignore all the type defs in the `node_modules/@types` dir, including the `node` types, which account for a few of the build errors.
* Setting `"noImplicitAny": "false"` gets rid of a bunch more errors. Obviously not the _ideal_ solution but fixing those properly should be pretty easy.

Other errors are not so obvious:

* I've got no idea where the  `PagesFunction` type is supposed to come from.
* Per the Qwik type defs, this render function needs a `stream` property rather than `url`:
   ```ts
   // Generate Qwik SSR HTML
   const result = await render({
     url: request.url,
   });
   ```

**Comment by nnelgxorz** [comment]
Related to #850 

You should be able to copy the Cloudflare Middleware from here

https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/middleware/cloudflare-pages/index.ts

Into your entry.cloudflare file. The middlewares should be set up with the renderToStream options.

**Comment by nnelgxorz** [comment]
Actually, changing my answer.

Changing the entry.cloudflare.tsx file to this

```ts
import render from './entry.ssr';
import { qwikCity } from "@builder.io/qwik-city/middleware/cloudflare-pages"
import qwikCityPlan from '@qwik-city-plan';

/**
 * Cloudflare Pages Request Handler
 */
export const onRequest = async (args: any) => {
  const handler = qwikCity(render, qwikCityPlan);
  return await handler(args)
};

```

Gets everything building for me.

**Comment by kylecordes** [comment]
Same problem here, but the above from @nnelgxorz does not work, because `qwik-city-plan` can't be found.

```
[vite]: Rollup failed to resolve import "@qwik-city-plan" from "src/s_3yhhhhxufdw.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Comment by nnelgxorz** [comment]
@kylecordes What version of Qwik City are you on? I got a Netlify site working with a similar setup on 0.0 29 this morning.

**Comment by adamdbradley** [comment]
Should be fixed in the next release, thanks for opening the issue.

- https://github.com/BuilderIO/qwik/pull/938
- https://github.com/BuilderIO/qwik/pull/937
