### ISSUE TITLE
input field onInput is not working properly

### ISSUE THREAD

**Issue by harshmangalam** [BuilderIO/qwik#870]
### Qwik Version

0.0.39

### Operating System (or Browser)

Chrome(Ubuntu 20.04)

### Node Version (if applicable)

16.16.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

`onInput` should do what we passed in callback like set the input value in `store`.

### Actual Behaviour

onInput is not working as expected .It only log the InputEvent on input text change without any console.log

### Additional Information

```jsx
  <input
          type="text"
          value={store.text}
          class="bg-gray-700 py-2 px-4 focus:ring-2 focus:ring-gray-400 focus:outline-none rounded-md"
          onInput$={()=>console.log("hi")}
        />

```

It should log "hi" in console but it always log InputEvent object in console on input value change.
`onChange` and `onKeyup` is working fine

**Comment by nnelgxorz** [comment]
Hi @harshmangalam! 

This works for me if I update the store.text value in the onInput$ handler. `(e) => store.text = (e.target as HtmlInputEvent).value`

I made a playground link here: 

https://qwik.builder.io/playground#version=0.0.39&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3RvcmUlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBBcHAlMjAlM0QlMjBjb21wb25lbnQlMjQoKCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBzdG9yZSUyMCUzRCUyMHVzZVN0b3JlKCU3QiUyMHRleHQlM0ElMjAnSGkhJyUyMCU3RCklM0IlNUNuJTIwJTIwcmV0dXJuJTIwJTNDaW5wdXQlNUNuJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMnRleHQlNUMlMjIlNUNuJTIwJTIwJTIwJTIwdmFsdWUlM0QlN0JzdG9yZS50ZXh0JTdEJTVDbiUyMCUyMCUyMCUyMGNsYXNzJTNEJTVDJTIyYmctZ3JheS03MDAlMjBweS0yJTIwcHgtNCUyMGZvY3VzJTNBcmluZy0yJTIwZm9jdXMlM0FyaW5nLWdyYXktNDAwJTIwZm9jdXMlM0FvdXRsaW5lLW5vbmUlMjByb3VuZGVkLW1kJTVDJTIyJTVDbiUyMCUyMCUyMCUyMG9uSW5wdXQlMjQlM0QlN0IoZSklM0QlM0UlMjAlN0IlMjBjb25zb2xlLmxvZygnaGknKSUzQiUyMHN0b3JlLnRleHQlMjAlM0QlMjAoZS50YXJnZXQlMjBhcyUyMEhUTUxJbnB1dEVsZW1lbnQpLnZhbHVlJTIwJTdEJTIwJTdEJTVDbiUyMCUyMCUyRiUzRSU1Q24lN0QpJTNCJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFwcCUyMCU3RCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE

Let me know if that works for you.

**Comment by harshmangalam** [comment]
Yes, @nnelgxorz i got this error in Ubuntu (Bodhi linux) but working fine in Linux Mint
