### ISSUE TITLE
nested <a /> rendering wrong structure

### ISSUE THREAD

**Issue by youngboy** [BuilderIO/qwik#872]
### Qwik Version

0.0.39

### Operating System (or Browser)

Chrome

### Which component is affected?

Qwik Runtime

### Expected Behaviour

created a reproduce link here https://stackblitz.com/edit/vitejs-vite-hxymdy?file=src/app.tsx

expect DOM to be like

```html
  <a>
    link card
    <a>nest link</a>
  </a>
```

### Actual Behaviour

render as following

```html
  <a>link card</a>
  <a>nest link</a>
```

**Comment by manucorporat** [comment]
This is just how HTML works, `<a>` can not be inside another `<a>`, same as a `<div>` can not be inside a `<p>`
https://codepen.io/manucorporat-the-flexboxer/pen/PoRRezJ
