### ISSUE TITLE
[DOCS] update the docs to include a CDN based no build usage

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [BuilderIO/qwik#898]
It would be great if there is a CDN version of qwik and somewhere around the overview in the docs are updated to show how it can be used: https://qwik.builder.io/docs/components/overview

**Comment by mhevery** [comment]
What is "CDN version of qwik" in your mind?

**Comment by manucorporat** [comment]
I think he means a iife mode, where qwik is imported as a script, and at least a version of client bootstrapping works.
am i wrong?

**Comment by zanettin** [comment]
Hi @ahmed-adly-khalil 
After all the above "guessing" - can you help us with a quick reply of what you would expect? 🙏  thanks a lot

**Comment by ahmed-adly-khalil** [comment]
I meant something like this https://unpkg.com/preact?module

**Comment by noeliadv** [comment]
@ahmed-adly-khalil 

I don't know if you found a solution to this, but if not: are you talking about this?: https://unpkg.com/@builder.io/qwik@1.2.1/core.mjs ?

And about "?module" ⚠️:
![image](https://github.com/BuilderIO/qwik/assets/118256861/c8a76403-b927-40d2-987c-03e44ea68710)

**Comment by shairez** [comment]
@ahmed-adly-khalil does @noeliadv 's answer help you?

**Comment by gioboa** [comment]
This issue is stale, so I'm closing it for now.
@ahmed-adly-khalil feel free to re-open it if it's still an issue for you.
Thanks.
