### ISSUE TITLE
[Bug] Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by gioboa** [BuilderIO/qwik#900]
### Qwik Version

0.0.29

### Operating System (or Browser)

macOs + Chrome

### Node Version (if applicable)

v18.4.0

### Which component is affected?

Qwik City

### Expected Behaviour

Application loads correctly the resources 

### Actual Behaviour

I run this [repo](https://github.com/vendure-ecommerce/storefront-qwik-starter) with _npm run dev.ssr_ and works good with @builder.io/qwik-city _"0.0.26"_ 
<img width="647" alt="Screenshot 2022-08-02 at 21 23 09" src="https://user-images.githubusercontent.com/35845425/182456620-ea57dbb4-c37a-495b-80eb-5ff9935f0729.png">

but if I upgrade to **"0.0.29"** I've got these errors in network chrome tab 

<img width="566" alt="Screenshot 2022-08-02 at 21 24 46" src="https://user-images.githubusercontent.com/35845425/182456949-106758ea-3168-4569-9219-ab6cb2cc1e05.png">

<img width="565" alt="Screenshot 2022-08-02 at 21 25 11" src="https://user-images.githubusercontent.com/35845425/182457085-75b10892-5642-42f4-96b8-3f210c62e0dd.png">

**Comment by gioboa** [comment]
btw with **@builder.io/qwik-city "0.0.29"** inside CloudFlare [look](https://45162a4c.storefront-qwik-starter.pages.dev) is working like a charm 🤔

**Comment by kylecordes** [comment]
Same failure here - "dev" seems broken in qwik-city .29.

(Also same happy progress with CloudFlare!)

**Comment by nnelgxorz** [comment]
Instructions to fix locally for people who can't wait to play:
- Go into `node_modules/@builder.io/qwik-city/vite`
- In `index.mjs` and `index.cjs` search for the function `isVitePathname`
- Replace the body of the function with `return pathname.startsWith("/@fs/") || pathname.startsWith("/@id/") || pathname.startsWith("/@qwik-city-plan") || pathname.startsWith("/@vite/") || pathname.startsWith("/src/") || pathname.startsWith("/favicon.ico") || pathname.startsWith("/node_modules/");` and save.

**Comment by manucorporat** [comment]
is this still a problem? a lot of things have changed

**Comment by gioboa** [comment]
we solved it with this config and upgrading Qwik + Qwik City
