### ISSUE TITLE
Qwik 0.1 Beta Iteration planning

### ISSUE THREAD

**Issue by manucorporat** [BuilderIO/qwik#910]
# Qwik 0.1 Beta

## Checklist
- [x] All public APIs documented
- [x] Collect and ship all pending breaking changes
- [x] Review and split all APIs between stable and alpha
- [x] Most used APIs are stable
- [x] Feature freeze
- [x] Doc site big review
- [x] Check minimum requirements (node, npm, yarn, osx, windows...)
- [x] Check not major open issues
- [x] Clean github issues
- [ ] Green light from core team
- [ ] Green light from community
- [ ] Plan Roadmap to 1.0
- [x] Write blog post
- [x] Prepare social media
- [ ] Schedule small event
- [ ] Verify all starters with all server
   - [ ] Check actual deployment in all servers (express, cloudflare, netlify)
   - [ ] Check `npm start`, `npm run dev.ssr`, `npm run build` and `npm run lint`

## Requirements
- Follow semver for new features, raising minor.
- Next announcement is 1.0-rc0
- Clear expectations
- Usable for production
- Happy path works great (windows, linux, mac)
- Breaking changes still possible, but not massive
- Like all software, bugs are expected but minor
- Cloudflare, netlify, express servers work great

**Comment by nnelgxorz** [comment]
YES!

**Comment by manucorporat** [comment]
## Possible API changes

### Different prefix of `useScopedStyles$()`

Currently:
- `useStyles`
- `useScopedStyles`

Proposal:
- `useStyles`
- `useStylesScoped`

Benefits, autocompletion in IDEs will help discover the styling apis.


### useUserContext()

Name does not reflect what it is, approved renamed to `useEnvData()`

### `useWatch`, `useClientEffect` first argument

This two APIs get the tracker as first argument, while `useResource$()` returns a object.
`useResource` API is more future proof, and it's the prefered by the core team and community, should we update useWatch and useClientEffect for consistency?

### QwikCity <Content/>

Does not reflect well what it is, approved rename to `<RouterOutlet />`

**Comment by adamdbradley** [comment]
`useUserContext()` renamed to `useEnvData()` https://github.com/BuilderIO/qwik/commit/13a81d3eaf1920dbc7ef188e92d676ef70dbd90f

`<Content/>` renamed to `<RouterOutlet/>` https://github.com/BuilderIO/qwik/commit/34887e79bd1e705a9816c731d979bb77af2363f1

**Comment by manucorporat** [comment]
Major public API review: https://github.com/BuilderIO/qwik/pull/916/files

**Comment by manucorporat** [comment]
https://github.com/BuilderIO/qwik/pull/912

- `useScopedStyles()` -> `useStylesScoped()`
- `useWatch$((track) => {})` -> `useWatch$(({track}) => {})`
- `useClientEffect$((track) => {})` -> `useClientEffect$(({track}) => {})`
- `useServerMount$(): Resource<>` -> `useServerMount$(): void`
- `useMount$(): Resource<>` -> `useMount$(): void`

**Comment by manucorporat** [comment]
Design decision for `<Host>`:
https://github.com/BuilderIO/qwik/issues/930

**Comment by manucorporat** [comment]
Removing useDocument()?
https://github.com/BuilderIO/qwik/issues/1074

Discussion needed

**Comment by lzxb** [comment]
Qwik is great. I like it very much

**Comment by manucorporat** [comment]
We did it! closing issue!

**Comment by shairez** [comment]
Great job everyone! 👏👏👏
