### ISSUE TITLE
Worker Prefetch results ignored by browser

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#919]
### Qwik Version

v0.0.0.39

### Operating System (or Browser)

Debian Linux

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Prefetched files are in the cache and ready to go.

### Actual Behaviour

The browser refetches the files that the worker already fetched.

### Additional Information

You can check it the network tab here and then click the Cart button in the top right: https://33f24279.storefront-qwik-starter.pages.dev/

**Comment by mhevery** [comment]
https://www.loom.com/share/0cf6c67be84a491a850a88baa0a091fe

**Comment by nnelgxorz** [comment]
My bad. Moral of the story: Don't have disable cache on in your network tab while debugging.
