### ISSUE TITLE
HMR doesn't work on `npm run dev.ssr`

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#928]
### Qwik Version

0.0.39

### Operating System (or Browser)

Windows / Chrome

### Node Version (if applicable)

16.13.0

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

I expect to have hot module reloading (or at least an update) when I run `npm run dev` which in turn runs `npm run dev.ssr`

If I run `npm run dev.client` which just runs `vite`, it does work...

### Actual Behaviour

Auto-reload doesn't work, I need to refresh the browser manually to see updates

**Comment by adamdbradley** [comment]
This should be fixed in the next release. Will leave this open until then.

**Comment by nnelgxorz** [comment]
I can confirm this is working now. 👍

**Comment by shairez** [comment]
Awesome, thanks @nnelgxorz and @adamdbradley !
