### ISSUE TITLE
Remove <Host/> component

### ISSUE THREAD

**Issue by adamdbradley** [BuilderIO/qwik#930]
### Is your feature request related to a problem?

If it's "possible to remove `<Host/>`, let's remove it.

### Describe the solution you'd like

Idea from a discussion @mhevery and I just had:
- Internally, there always needs to be an actual actual <div> (or whatever) host component
- However, what if the <Host/> component user's write never existed at all, it's not something they import and use
- And the "host" component qwik generates, ALWAYS is [display: contents](https://developer.mozilla.org/en-US/docs/Web/CSS/display#box)??
- So "qwik's" host is kinda never really there to begin with.
- It's a host element for qwik to interact with, but it's not something to the user has to worry about since it's basically silent.
- The "user's" host is whatever the heck they want it to be, or no host at all
- Exactly like react in how it can return a top level element, or a fragment with an array of children

So user could return

```tsx
return (
  <footer>my footer</footer>
)
```

And qwik would generate

```tsx
<div q:host>
  <footer>myfooter</footer>
</div>
```

Or the user could return

```tsx
return (
  <Fragment>
    <span>a</span>
    <span>b</span>
  </Fragment>
)
```

And qwik would generate

```tsx
<div q:host>
    <span>a</span>
    <span>b</span>
</div>
```

And now the component's css would flow how they'd expect, and their component could continue act like display inline if that's what the top level components were. Just like how react devs would expect their components to render and flow. 

This allows us to completely remove `<Host/>`, and now users wouldn't have to worry about adding `{ tagName: 'footer' }`, which are both strange to traditional JSX frameworks.

```tsx
export default component$(() => { 
    return (
      <Host>
        <ul>
          ...
        </ul>
      </Host>
    );
  },
  {
    tagName: 'footer',
  }
);
```

becomes

```tsx
export default component$(() => {
    return (
      <footer>
        <ul>...</ul>
      </footer>
    );
  } 
);
```

I also think this makes the internal code much easier now, because it doesn't have to worry about merging attributes.

For example, let's say that below is a React app.

```tsx
export default function App() {
  return (
    <div>
      <CmpA style={ { color: 'red' } }/>
    </div>
  );
}

function CmpA() {
  return (
    <>
      <h1>Hello!</h1>
    </>
  );
}
```

The red color `styles` wouldn't actually apply to the `h1`, cuz what would the "style" be getting assigned to? It's a component prop, not an actual attribute. The example above wouldn't work in React (which is expected).

Thoughts

### Describe alternatives you've considered

Keep `<Host/>` :

**Comment by nnelgxorz** [comment]
Interesting proposal. I'm curious how this would work in the case where you want to control the Host tag? 

There are a lot of cases in styling where you would want to have a footer tag, for example, without the wrapper. So `<footer q-host=''">Whatever</footer>.

Is that still possible in this scenario?

**Comment by adamdbradley** [comment]
Because the real wrapping `<div q:host>` would have [display: contents](https://developer.mozilla.org/en-US/docs/Web/CSS/display#box)

>These elements don't produce a specific box by themselves. They are replaced by their pseudo-box and their child boxes. 

This is already how `<Slot/>` works and why Qwik adding a wrapping `<div>` doesn't affect the styling of the inner slot content.

So if you wanted to control `<footer>` you'd just add the props/attributes no different than all the other nodes.

**Comment by adamdbradley** [comment]
Should follow up that you still "could" use the existing `<Host/>` as it works today, but only if you imported and used it, and set the `tagName` option. Otherwise (IMO) the much better default is to work like react and never act like a wrapping containing host element exists.

`<Host/>` now becomes an advanced topic buried in the docs.

**Comment by nnelgxorz** [comment]
Okay, cool. Let me try a little experiment on my machine and see if the problem I'm thinking of actually is a problem. :laughing:

**Comment by shairez** [comment]
Yes! I love it!
The simpler we can get it to be, the easier the learning curve will be and developepr happiness will increase

Great proposal! 👏🙏

**Comment by manucorporat** [comment]
https://github.com/BuilderIO/qwik/pull/933

**Comment by manucorporat** [comment]
Strong opinion about we cant remove Host, without actual removing the real host element

**Comment by nnelgxorz** [comment]
Okay, so the main issue I have is that wrapper elements break the flow for css selectors, ie `body>header:{...}` doesn't work if you have a wrapper.

Also it's nice to not have extraneous dom nodes when possible.

But if you can still have access to the tagName prop, then I don't think there's an issue for me.

**Comment by kylecordes** [comment]
I'm skeptical of removing access/control of the host element, unless that host element itself does not exist. `display: contents` is great; but one might want to interop with CSS out there that makes all kinds of assumptions of DOM shape, element names, etc., far behind the contents-of-a-grid-or-flex situation. Apps may find they need to add another layer of DOM inside the component, to make up for missing control of the host element - while there could be arguments that this is costless, it could also be an obstacle to adoption.

**Comment by nnelgxorz** [comment]
We should probably also make sure it's well documented that `display: content` can break the accessibility tree in some browsers. https://adrianroselli.com/2018/05/display-contents-is-not-a-css-reset.html#Bugs

**Comment by adamdbradley** [comment]
Ok, I wasn't aware of the accessibility tree issues. Here's the latest research: https://adrianroselli.com/2022/07/its-mid-2022-and-browsers-mostly-safari-still-break-accessibility-via-display-properties.html

**Comment by nnelgxorz** [comment]
Kinda disconcerting that no one has button working

**Comment by manucorporat** [comment]
I am all for removing the host element, but technically extremely challenging. If we cant remove the actual host element, we cant remove apis to control it, aka <Host/> but I guess some better default like display:contents makes it less of a pain.

Also, i also find it arbitrary that we default to <div>

**Comment by mhevery** [comment]
> Ok, I wasn't aware of the accessibility tree issues. Here's the latest research: https://adrianroselli.com/2022/07/its-mid-2022-and-browsers-mostly-safari-still-break-accessibility-via-display-properties.html

If the above is an issue, then it is already an issue with `<q:slot/>` so https://github.com/BuilderIO/qwik/pull/936 does not change anything.

**Comment by dzearing** [comment]
I'd love to remove `Host` but its purpose seems very needed. `display: contents` helps in some cases, but doesn't really give the user control over positioning of the container. I had a fixed overlay scenario and missed `Host`, and Qwik (intersection observer) thought the component was off screen when it should have been sitting in the corner in a `display:fixed` environment:

```jsx
const FixedComponent = component$(() => (
  <header className="some-display-fixed-overlay">...</header>
);
```
In this case `Host` needs to be used in place of `div` so that the placeholder container can be fixed, and IO can determine it to be visible and load its guts. Easy fix, but not obvious.

If the optimizer could pick out developer intent... that's interesting and would provide the best ergonomics. In the case above it is clear I skipped on a Host definition, and my root is a `header` with a specific class name. Use that to 1. auto inject the missing `<Host as="header" className="..."/>`, and 2. remove the header and replace with document fragment containing children.

But I think there are a lot of edge cases to support for that to be inferred and it might not be realistic.

I don't mind `Host` being explicit, as long as it's obvious when to use it and how. If it were just a little more ergonomic (e.g. move  `as` prop rather than having its props passed into `component$`) and well documented, it's an ergonomics sacrifice that seems worthy enough (you are getting automated async splitting!)

Another thought: it could also be lint-enforced (e.g. `Host` must be used within a `component$` definition.)

**Comment by manucorporat** [comment]
Fixed https://github.com/BuilderIO/qwik/commit/3e18804db2d7937db4576023bfba594e5d6e925d !
