### ISSUE TITLE
Root component: invocation context

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#941]
### Is your feature request related to a problem?

At the moment, _Root_ component in a Qwik City project looks like this:
```
export default () => {
  return (
    <Html lang="en">
      <Head />
      <Body />
    </Html>
  );
};
```
Since it's a simple component, I can't do this:
```
export default () => {
  /* Invoking 'use*()' method outside of invocation context */
  const state = useStore({
    foo: 0  
  });
  
  return (
    <Html lang="en">
      <Head />
      <Body />
    </Html>
  );
};
```
And since it is not possible to change the structure of an HTML document, Qwik City has rewritten the `html` tag so that it can build its own contexts, _thus available in the whole HTML document_.

_This way, the developer is out of control of the entire HTML document and out of the ability to do the same._

### Describe the solution you'd like

```
export default () => {
  useQwikCity();

  /* Other use* methods that will be available in the whole document */
  
  return (
    <html lang="en">
      <Head />
      <Body />
    </html>
  );
};
```

### Describe alternatives you've considered

I tried to use a Qwik `component$` with tagname `html `as _Root_, but without success. In any case, Qwik City would not be importable.

### Additional context

It is important to be able to control the entire HTML document in many real contexts: for example often the contents of the page (including title, description and body) come from a single request to the server/db, or for localization of the page, where the _locale_ must be set from the html tag and must be shared with the whole page.

**Comment by nnelgxorz** [comment]
:+1: I think useDocument can be used to get a reference to the document. You might be able to use that to change attributes from the top level layout.

I agree this is unintuitive.

**Comment by robisim74** [comment]
@nnelgxorz Yes, I do this now:

```
  const doc = useDocument();

  doc.documentElement.lang = myLang;
  doc.title = myTitle;
  ...
```
but it looks like a hack to me.

**Comment by nnelgxorz** [comment]
The title, description and all other head content can be set per page by exporting a head like here.

https://github.com/BuilderIO/qwik/blob/main/starters/apps/qwik-city/src/routes/products/%5Bid%5D.tsx#L51

Still agree about setting html level attributes.

**Comment by robisim74** [comment]
@nnelgxorz  thanks again for your suggestion. But doing so requires either an extra - verbose- request, or passing the data to the child components.

In any case, the reason why I opened this issue is not to find solutions, which also exist.

_As a dev
I want have control over the whole HTML document 
so that i can work in a Qwik way starting with the root component_

These are just my two cents...

**Comment by manucorporat** [comment]
wondering why you cant modify the Head component? or the Body component? useDocument() might not work in SSR, we are thinking to deprecate it, since in server you will not have a DOM

**Comment by robisim74** [comment]
@manucorporat The problem is not being able to modify head / body, the problem is being able to use the hooks (useStore$, useMount$) starting from the root component.

**Comment by manucorporat** [comment]
Fixed! https://github.com/BuilderIO/qwik/commit/3e18804db2d7937db4576023bfba594e5d6e925d

**Comment by robisim74** [comment]
@manucorporat Great!

I tried your commit, and now this works:

```
export const Root = component$(() => {
  const state = useStore<AppContext>({
    lang: 'en-US'  
  });
  
  return (
    <Html lang={state.lang}>
      <Head />
      <Body />
    </Html>
  );
});
```

But there is a side effect of removing `Host` from Qwik City `Html`. 
_The props passed to html tag are lost_: `<!DOCTYPE html><html q:container="paused" q:version="0.0.42-dev20220811094939" q:render="ssr" q:base="/build/">`

https://github.com/BuilderIO/qwik/commit/3e18804db2d7937db4576023bfba594e5d6e925d#diff-3f391beb0f7fd766a067a5969189871c03088cffb739330dd77ca244f45f00d4L108-R106 

Also I'm wondering if it will be appropriate to set the Root as a Qwik `component$` already in the starters

**Comment by manucorporat** [comment]
yes! pending to update starters with the new setup, also, probably Body does not need to be a component anymore, no need.

Regarding the props in html... i dont think we will be able to the problem is that in Qwik we need a container element. it can be anything, a div, an article, or the html itself. this node previously could be merged with a host element, because the host element of a component is also a element, however now, this is not longer the case.

A component within a container can not render the container itself. The alternatives are:
- use containerAttributes in the renderToStream options, it will be static.
- set the lang in body or head, lang can be applied to any element (this would allow to change dynamically)
- use client side DOM apis to alter the html itself. `document.documentElement.setAttribute()` this will not work in SSR

**Comment by robisim74** [comment]
For me the second option is ok, but besides the specific case of lang, it would be advisable not to lose the attributes of the Html tag (it could be confusing in the future). Why not modify the return content of Qwik City `html.tsx` like this?

```
return(
    <html {...props}>
      <Slot />
    </html>
  );
```

It seem works well
