### ISSUE TITLE
Context undefined in production build

### ISSUE THREAD

**Issue by adamdbradley** [BuilderIO/qwik#950]
### Qwik Version

0.0.39-dev20220805031634 (main)

### Operating System (or Browser)

na

### Which component is affected?

Qwik Runtime

### Expected Behaviour

In a production build of the docs site, when the mobile menu icon is clicked, a runtime error happens and white screen of death.

It looks like `contents` is `undefined` here: https://github.com/BuilderIO/qwik/blob/85fd43ecb6f95b986b90b6043c8fccfe120c7198/packages/qwik-city/runtime/src/library/router-outlet.ts#L8

### Actual Behaviour

Menu doesn't work.

### Additional Information

First reported here https://github.com/BuilderIO/qwik/issues/945

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/pull/961
