### ISSUE TITLE
[CITY-0.0.26] Using Link with a route that includes a parameter cashes Qwik or Vite

### ISSUE THREAD

**Issue by mahmoudajawad** [BuilderIO/qwik#958]
### Qwik Version

0.0.39

### Operating System (or Browser)

Fedora 36, Firefox 103

### Node Version (if applicable)

16.14.0

### Which component is affected?

Qwik City

### Expected Behaviour

To be able to navigate to following route:
```services/[service_id]/edit/index.tsx```
with the following `Link`:
```html
<Link href="/services/ID_GOES_HERE/edit">Edit</Link>
```
And not only with: 
```html
<a href="/services/ID_GOES_HERE/edit">Edit</a>
```

### Actual Behaviour

The introduction of `Link` component is great addition to Qwik City as it means apps that depend on live-connections don't have to rebuild the logic.

In using it with the scenario explained in "Expected Behaviour", Vite or Qwik ending up crashes with following exact details:
1. Running an app that contains following directory path: `services/[service_id]/edit/index.tsx`.
2. Browsing to `localhost:5173/services/SERVICE_ID/edit` works fine.
3. Browsing to `localhost:5173/services` which enlists all services and uses `Link` components to link to edit page, then clicking on any of those `Link` components would not result in any change.
4.  Browsing to `localhost:5173/services/SERVICE_ID/edit` now shows white page with no error logs in Qwik console or browser console.
5. To get app to work back fine, Vite build has to be re-triggered by updating a file, or restarted completely, otherwise accessing `localhost:5173/services/SERVICE_ID/edit` would continue to show blank white page.

**Comment by adamdbradley** [comment]
Thanks for opening the issue. Would you be able to create a minimal repo case to help me understand? You can use this stackblitz to fork from https://stackblitz.com/edit/vitejs-vite-mfpvdp?file=src%2Froutes%2F[...skuId]%2Findex.tsx Thanks

**Comment by adamdbradley** [comment]
I think this may have been fixed in the latest releases. Please reopen if you're still experiencing issues, thanks.
