### ISSUE TITLE
rollup optimizer: ESM outputs do not write to symbolsPath

### ISSUE THREAD

**Issue by btakita** [BuilderIO/qwik#96]
I'm am attempting to use ESM for the nodejs server. I'm not able to start the server using the `todo-list` example provided in this repo. The optimizer rollup plugin does not output to symbolsPath.

See:

https://github.com/BuilderIO/qwik/blob/main/src/optimizer/src/rollup/index.ts#L150-L160

https://github.com/BuilderIO/qwik/blob/main/src/server/create-server-renderer.ts#L25-L26

**Comment by mhevery** [comment]
Hey, @btakita is this still an issue with the latest codebase?

**Comment by manucorporat** [comment]
The compiler changed so much, this issue does not longer apply! it should be fixed in latest!
