### ISSUE TITLE
SWC needs to be updated to fix `yield (yield x)` problem.

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#964]
### Qwik Version

0.0.36

### Operating System (or Browser)

Browser

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Preserve `yield (yield x)`

### Actual Behaviour

`yield yield x`

### Additional Information

https://qwik.builder.io/playground#version=0.0.39&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMGNvbnNvbGUubG9nKGZ1bmN0aW9uKihsbyUzQSUyMGFueSUyQyUyMHQlM0ElMjBhbnkpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnNvbGUubG9nKHlpZWxkJTIwKHlpZWxkJTIwbG8pKHQuaHJlZikudGhlbigociklMjAlM0QlM0UlMjByLmpzb24oKSkpJTNCJTVDbiUyMCUyMCU3RCklM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMCUzQ3AlM0VIZWxsbyUyMFF3aWslM0MlMkZwJTNFJTNCJTVDbiU3RCklM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRmVudHJ5LnNlcnZlci50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwcmVuZGVyVG9TdHJpbmclMkMlMjBSZW5kZXJPcHRpb25zJTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayUyRnNlcnZlciclM0IlNUNuaW1wb3J0JTIwJTdCJTIwUm9vdCUyMCU3RCUyMGZyb20lMjAnLiUyRnJvb3QnJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjAob3B0cyUzQSUyMFJlbmRlck9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMHJlbmRlclRvU3RyaW5nKCUzQ1Jvb3QlMjAlMkYlM0UlMkMlMjBvcHRzKSUzQiU1Q24lN0QlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnBsYXlncm91bmQtZGF0YS50cyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjB0eXBlJTIwJTdCJTIwUmVwbE1vZHVsZUlucHV0JTIwJTdEJTIwZnJvbSUyMCcuLiUyRi4uJTJGdHlwZXMnJTNCJTVDbiU1Q25leHBvcnQlMjBpbnRlcmZhY2UlMjBQbGF5Z3JvdW5kQXBwJTIwJTdCJTVDbiUyMCUyMGlucHV0cyUzQSUyMFJlcGxNb2R1bGVJbnB1dCU1QiU1RCUzQiU1Q24lN0QlNUNuJTVDbiUyRioqJTVDbiUyMColMjBHZW5lcmF0ZWQlMjBhdCUyMGJ1aWxkLXRpbWUuJTVDbiUyMColMjBTZWUlMjBwYWNrYWdlcyUyRmRvY3MlMkZwYWdlcyUyRnBsYXlncm91bmQlMkZhcHAlNUNuJTIwKiUyRiU1Q25jb25zdCUyMHBsYXlncm91bmRBcHAlM0ElMjBQbGF5Z3JvdW5kQXBwJTIwJTNEJTIwJTdCJTdEJTIwYXMlMjBhbnklM0IlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMHBsYXlncm91bmRBcHAlM0IlNUNuJTIyJTdEJTJDJTdCJTIycGF0aCUyMiUzQSUyMiUyRnJvb3QudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEFwcCUyMCU3RCUyMGZyb20lMjAnLiUyRmFwcCclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwUm9vdCUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDaHRtbCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NoZWFkJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ3RpdGxlJTNFSGVsbG8lMjBRd2lrJTNDJTJGdGl0bGUlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0Nib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUzQ0FwcCUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZib2R5JTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRmh0bWwlM0UlNUNuJTIwJTIwKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTdEJTVE

**Comment by manucorporat** [comment]
https://github.com/BuilderIO/qwik/commit/82f739b07320e5f675e1e82f381b35a50bc64eb4

**Comment by manucorporat** [comment]
Fixed!
