### ISSUE TITLE
[DOCS] Button "Add new examples" not work

### ISSUE THREAD

**Issue by tinkerbaj** [BuilderIO/qwik#966]
**How can the documentation be improved?**
The button takes you to this link [404 page](https://github.com/BuilderIO/qwik/tree/main/packages/docs/src/pages/examples) but it doesn't exist.

**Comment by nnelgxorz** [comment]
Good catch, it should be https://github.com/BuilderIO/qwik/tree/main/packages/docs/src/repl/apps/examples.
