### ISSUE TITLE
Static Site Generation - SSG

### ISSUE THREAD

**Issue by vargaendre** [BuilderIO/qwik#97]
Hi,

First of all, let me express how much I love the idea behind qwik and what it promises. Resumability is indeed a great thing.

I am looking for a framework to use with my new project. It's going to be many (eventually tens of thousands of) landing pages statically generated from a set of structured data and then hosted as pure HTML files on a CDN. Qwik would be an ideal candidate because performance is very important for me, my content is mostly static but I'd love to provide an app-like UX.

Is it possible to achive my goal with qwik? So, that I would generate many static HTML files from a few templates and lots of data, then just copy the files to the server?

Thank you for reading so far and I appreciate your work a lot!

**Comment by mhevery** [comment]
Yes, Qwik is designed with SSR/SSG and CDNs in mind.

**Comment by L1lith** [comment]
@mhevery I don't see where this is made clear in the Qwik docs how to do this. Whenever I make a starter it just ends up making a server entry point when I run build. I would prefer to have a command or some way to output static HTML directly. Maybe thats possible with some tinkering but I'm not sure how to do that. 

To me it would make sense for the Qwik CLI to be updated to have a SSG starter option.

**Comment by L1lith** [comment]
> Maybe change the meaning of this issue, or make a new one, which is a feature request for such a command line option rather than a question about whether Qwik can do this.

I still don't understand how you would do this in Qwik in the first place though

**Comment by mhevery** [comment]
Yes, this issue was a question please make a new issue.

As of right now when you deploy to Cloudflare/Netlify Qwik will generate pages and cache them. In essence, this will give you a SSG.

If you are looking for a command to just build the system ahead of time (classical SSG) We have not implemented it yet. But would love some contribution. We were thinking of just starting a server and then having a tool that just follows all of the links in localhost and downloads them to local directory. Such as scraper should be easy to write. Would you be up for it?

**Comment by janat08** [comment]
Having this dynamic ssg makes it easier to build autocomplete search if every new input leads to redirect that would hit the cache right?

**Comment by BerndWessels** [comment]
Has there been any progress on this?

I was hoping that resume-ability means in this case that all pages are statically generated and hosted on cloudflare pages as static html files and served directly to the browser. From there they are resumed going through SSR in the cloudflare workers when the user starts interacting with the site in his browser.

That would give us the best performance and lowest use of CPU cycles, right?

Is this the correct way of thinking about it @mhevery ?
