### ISSUE TITLE
Change global.css to global.scss loaded from root.tsx not working anymore

### ISSUE THREAD

**Issue by Zorgatone** [BuilderIO/qwik#988]
### Qwik Version

0.0.39

### Operating System (or Browser)

chrome 103 on windows 11

### Node Version (if applicable)

node 18

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

From the qwik starter, the root component loads the global.css styles and the App component like this:

```typescript
import { App } from "./components/app/app";

import "./global.css";

export default () => {
  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <title>Qwik Blank App</title>
      </head>
      <body>
        <App />
      </body>
    </html>
  );
};
```

If I change `import "./global.css";` to `import "./global.scss";` and rename the file global.css to global.scss it should load the styles and apply them in the page if sass is installed.

### Actual Behaviour

If I change `import "./global.css";` to `import "./global.scss";` and rename the file global.css to global.scss it does NOT load the styles and apply them in the page even if sass is installed.
It compiles the scss styles but does not seem to load them in the page somehow, without any warning or error message anywhere (all the other scss styles in the app are working though)

**Comment by MasterMousa** [comment]
sass don't use :root variables as I know
you should edit every variable to match sass variables syntax
and you should write `import style from './global.scss';`
and import useStyles$ like this `import { useStyles$ } from '@builder.io/qwik';`
and in the first line of the component write this `useStyles$(style);`
this is the solution I found, I don't know if there is another solution or no
**Note:** you should change all another files (like header.css etc..) to match sass syntax

**Comment by zanettin** [comment]
@Zorgatone did the info from @MasterMousa helped you with your issue? for me it sounds like https://github.com/BuilderIO/qwik/issues/749

**Comment by Zorgatone** [comment]
> @Zorgatone did the info from @MasterMousa helped you with your issue? for me it sounds like #749

yes the mentioned issue seems exactly the same.

I would need to install the latest qwik version and test this again when I get home.

And no, I didn't mention the `useStyles$` method, I was trying a global import of a "*.scss" file.
I think it exist a almost identical problem, but when trying to import classes from a "*.module.scss" file.

I'll add a comment after some testing

**Comment by manucorporat** [comment]
going to close this issue! it's a very old version of qwik and probably needs a new repo if this is still the case!
