### ISSUE TITLE
[DOCS] Include discussion of ReactDOM render and renderToString alternatives in Qwik

### ISSUE THREAD

**Issue by dzearing** [BuilderIO/qwik#989]
Simple scenario: Embed an island of Qwik on an existing page. Existing docs/template don't seem to cover how to do this.

In my case, I have an overlay UI I would like to render on top of an app. I don't have a server to apply server rendering, and am decoupled from the app build so I can't be "optimized" at the full app scope. I do think this could still benefit from Qwik's principle of avoiding loading JS until needed. 

So, I need to have entries that have the analogy of what I'd do in react:

index.tsx
```tsx
// Guessing here (this is what should be doc'd.)
import { render } from '@builder.io/qwik';
import { App } from './App';

function init() {
  export function init(targetElement = document.body) {
  const div = document.createElement('div');

  render(<App/>, div);
  targetElement.appendChild(div);
}

init();
```

Docs should cover:

1. Right template to use for embed scenarios (so that the optimizer can split the code up appropriately.)
2. The recommended apis to use to inject the experience (in the above, I'm guessing `render` is the function I should use, and unsure if I should append the element before or after render, and also unsure if this could be a shadow root inside a web component.)

**Comment by wmertens** [comment]
The problem is that Qwik depends on the optimizer to make qwik-city work. So as long as you only use Qwik and not Qwik-City, something like this might work:

```tsx
import * as React from 'react';
import './style.css';
import { component$, jsx } from '@builder.io/qwik';
import { renderToString } from '@builder.io/qwik/server';

const Q = component$(() => jsx('div', { children: 'hello from Qwik' }));

export default function App() {
  const [q, setQ] = React.useState('');
  React.useEffect(() => {
    console.log('hi');
    renderToString(jsx(Q, null)).then(
      (s) => setQ(s.html),
      (e) => setQ(e.message)
    );
  });
  return (
    <div>
      <h1>Hello from React!</h1>
      <div>{q}</div>
    </div>
  );
}
```

Note that the JSX transform for React and Qwik are different so it's best to put Qwik components in their own file and add the proper comment to import the right jsx
